// USGS 3DEP point cloud over one roof.
//
// The public bucket s3://usgs-lidar-public holds every 3DEP project as Entwine
// Point Tiles: a streaming octree, so a house-sized box costs a handful of HTTP
// range-sized objects rather than a 130 MB tile. Measured on the field set:
// 11-13 nodes, 1.9-3.6 MB, one to three seconds cold, against a five-minute
// budget for the whole measurement.
//
// What this is FOR, and what it is not for. Measured 2026-08-28 across five
// addresses: as a SURFACE the lidar loses to the Google DSM badly — about one
// point per square foot against the raster's five to seven samples, and the
// share of facets it can fit a trusted plane through falls on four houses of
// five. It earns its place as an EDGE detector: it is the only source that says
// "a roof line runs HERE" rather than "something here is wrong". Nothing in
// this module measures pitch or area; the DSM keeps that job.
//
// Best-effort by contract: every failure returns null with a reason, and the
// caller draws exactly what it would have drawn without it.

import { externalFetch } from "@/lib/externalCall";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const D2R = Math.PI / 180;
const EARTH_R_M = 6378137;
const FT_PER_M = 3.28084;

const BUCKET = "https://s3-us-west-2.amazonaws.com/usgs-lidar-public";
/** The coordinate → project index. Regenerated by a GitHub Action, ~8.7 MB. */
const INDEX_URL = "https://raw.githubusercontent.com/hobuinc/usgs-lidar/master/boundaries/resources.geojson";
const CACHE_DIR = () => resolve(process.cwd(), ".cache", "lidar");

/** One 3DEP point, in the repo's local frame: feet from the pin, x east, y north. */
export interface CloudPoint {
  x: number;
  y: number;
  /** feet, as the survey recorded it (NOT metres — converted on read). */
  z: number;
  classification: number;
  numberOfReturns: number;
}

export interface LidarCloud {
  points: CloudPoint[];
  project: string;
  /** Ground level from the survey's OWN class-2 returns, feet. NaN when absent. */
  groundFt: number;
  nodes: number;
  bytes: number;
  ms: number;
}

const toWebMercator = (lat: number, lng: number): [number, number] => [
  EARTH_R_M * lng * D2R,
  EARTH_R_M * Math.log(Math.tan(Math.PI / 4 + (lat * D2R) / 2)),
];
const fromWebMercator = (x: number, y: number): { lat: number; lng: number } => ({
  lng: x / EARTH_R_M / D2R,
  lat: (2 * Math.atan(Math.exp(y / EARTH_R_M)) - Math.PI / 2) / D2R,
});

// ── the bucket, with a best-effort disk cache ────────────────────────────────

async function fetchCached(url: string, file: string, timeoutMs: number): Promise<Buffer> {
  const p = resolve(CACHE_DIR(), file);
  try {
    if (existsSync(p)) return readFileSync(p);
  } catch {
    /* unreadable cache is a miss */
  }
  const res = await externalFetch("3dep", file, url, {}, { timeoutMs });
  const buf = Buffer.from(await res.arrayBuffer());
  try {
    mkdirSync(CACHE_DIR(), { recursive: true });
    writeFileSync(p, buf);
  } catch {
    // read-only filesystem (serverless) — the fetch still stands
  }
  return buf;
}

interface IndexFeature {
  properties: { name: string; count: number };
  geometry: { type: string; coordinates: unknown };
}
let indexMemo: IndexFeature[] | null = null;

const inRing2 = (x: number, y: number, ring: number[][]): boolean => {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
};

/**
 * The 3DEP project covering a point, or null. Ranked by point count, so the
 * densest collection wins where several overlap (Kane County IL has a 2008 and
 * a 2018 delivery; the 2018 one is thirteen times denser).
 */
export async function projectFor(lat: number, lng: number, timeoutMs = 30_000): Promise<string | null> {
  if (!indexMemo) {
    const buf = await fetchCached(INDEX_URL, "resources.geojson", timeoutMs);
    indexMemo = (JSON.parse(buf.toString("utf8")) as { features: IndexFeature[] }).features;
  }
  let best: { name: string; count: number } | null = null;
  for (const f of indexMemo) {
    const g = f.geometry;
    const polys = g.type === "Polygon" ? [g.coordinates as number[][][]] : (g.coordinates as number[][][][]);
    let hit = false;
    for (const poly of polys ?? []) {
      if (!poly?.[0] || !inRing2(lng, lat, poly[0])) continue;
      let inHole = false;
      for (let h = 1; h < poly.length; h++) if (inRing2(lng, lat, poly[h])) inHole = true;
      if (!inHole) { hit = true; break; }
    }
    if (hit && (!best || f.properties.count > best.count)) best = { name: f.properties.name, count: f.properties.count };
  }
  return best?.name ?? null;
}

// ── LAS/LAZ ─────────────────────────────────────────────────────────────────

interface LasHeader {
  pointFormat: number;
  pointLength: number;
  count: number;
  scale: [number, number, number];
  offset: [number, number, number];
}
function readLasHeader(buf: Buffer): LasHeader {
  if (buf.toString("ascii", 0, 4) !== "LASF") throw new Error("not a LAS/LAZ file");
  const versionMinor = buf.readUInt8(25);
  const pointFormat = buf.readUInt8(104) & 0x3f; // the top bits flag compression
  const pointLength = buf.readUInt16LE(105);
  let count = buf.readUInt32LE(107);
  if (versionMinor >= 4) {
    const c14 = Number(buf.readBigUInt64LE(247));
    if (c14 > 0) count = c14;
  }
  return {
    pointFormat,
    pointLength,
    count,
    scale: [buf.readDoubleLE(131), buf.readDoubleLE(139), buf.readDoubleLE(147)],
    offset: [buf.readDoubleLE(155), buf.readDoubleLE(163), buf.readDoubleLE(171)],
  };
}

interface LazPerfModule {
  LASZip: new () => {
    open(ptr: number, len: number): void;
    getPoint(ptr: number): void;
    getCount(): number;
    getPointLength(): number;
    getPointFormat(): number;
    delete(): void;
  };
  _malloc(n: number): number;
  _free(p: number): void;
  HEAPU8: Uint8Array;
}
let lazMemo: Promise<LazPerfModule> | null = null;
async function laz(): Promise<LazPerfModule> {
  if (!lazMemo) {
    lazMemo = import("laz-perf").then((m) => (m as unknown as { createLazPerf: () => Promise<LazPerfModule> }).createLazPerf());
  }
  return lazMemo;
}

/** Decode one EPT node into frame-feet points around `origin`. */
async function decodeNode(buf: Buffer, origin: { lat: number; lng: number }): Promise<CloudPoint[]> {
  const header = readLasHeader(buf);
  const mod = await laz();
  const filePtr = mod._malloc(buf.byteLength);
  mod.HEAPU8.set(buf, filePtr);
  const zip = new mod.LASZip();
  zip.open(filePtr, buf.byteLength);
  const len = zip.getPointLength() || header.pointLength;
  const fmt = zip.getPointFormat();
  const n = zip.getCount() || header.count;
  const ptPtr = mod._malloc(len);

  const lonFt = D2R * Math.cos(origin.lat * D2R) * EARTH_R_M * FT_PER_M;
  const latFt = D2R * EARTH_R_M * FT_PER_M;
  const out: CloudPoint[] = new Array(n);
  for (let i = 0; i < n; i++) {
    zip.getPoint(ptPtr);
    // the wasm heap can grow mid-run and detach any buffer captured earlier
    const view = mod.HEAPU8;
    const dv = new DataView(view.buffer, view.byteOffset + ptPtr, len);
    const mx = dv.getInt32(0, true) * header.scale[0] + header.offset[0];
    const my = dv.getInt32(4, true) * header.scale[1] + header.offset[1];
    const mz = dv.getInt32(8, true) * header.scale[2] + header.offset[2];
    const rb = dv.getUint8(14);
    const numberOfReturns = fmt >= 6 ? (rb >> 4) & 0x0f : (rb >> 3) & 0x07;
    const classification = fmt >= 6 ? dv.getUint8(16) : dv.getUint8(15) & 0x1f;
    const { lat, lng } = fromWebMercator(mx, my);
    out[i] = {
      x: (lng - origin.lng) * lonFt,
      y: (lat - origin.lat) * latFt,
      z: mz * FT_PER_M,
      classification,
      numberOfReturns,
    };
  }
  zip.delete();
  mod._free(ptPtr);
  mod._free(filePtr);
  return out;
}

// ── the octree walk ─────────────────────────────────────────────────────────

export interface CloudRequest {
  origin: { lat: number; lng: number };
  /** Frame-feet box to cover, usually the roof plus a margin. */
  box: { x0: number; y0: number; x1: number; y1: number };
  timeoutMs?: number;
  /** Ceiling on nodes fetched, so a pathological box cannot run away. */
  maxNodes?: number;
}

/**
 * Every EPT node meeting the box, decoded and concatenated. EPT is ADDITIVE —
 * each depth adds detail rather than replacing the parent — so the ancestors
 * are fetched too; the leaf alone is a subsample.
 */
export async function fetchCloud(req: CloudRequest): Promise<{ cloud: LidarCloud } | { reason: string }> {
  const t0 = Date.now();
  const timeoutMs = req.timeoutMs ?? 30_000;
  const maxNodes = req.maxNodes ?? 40;
  let project: string | null;
  try {
    project = await projectFor(req.origin.lat, req.origin.lng, timeoutMs);
  } catch (err) {
    return { reason: `3DEP index unreachable: ${err instanceof Error ? err.message : String(err)}` };
  }
  if (!project) return { reason: "no 3DEP project covers this address" };

  let ept: { bounds: number[] };
  try {
    ept = JSON.parse((await fetchCached(`${BUCKET}/${project}/ept.json`, `ept-${project}.json`, timeoutMs)).toString("utf8")) as { bounds: number[] };
  } catch (err) {
    return { reason: `${project}/ept.json unreadable: ${err instanceof Error ? err.message : String(err)}` };
  }
  const b = ept.bounds;

  const lonFt = D2R * Math.cos(req.origin.lat * D2R) * EARTH_R_M * FT_PER_M;
  const latFt = D2R * EARTH_R_M * FT_PER_M;
  const corners: Array<[number, number]> = [
    [req.box.x0, req.box.y0], [req.box.x1, req.box.y0], [req.box.x1, req.box.y1], [req.box.x0, req.box.y1],
  ].map(([fx, fy]) => toWebMercator(req.origin.lat + fy / latFt, req.origin.lng + fx / lonFt));
  const mx0 = Math.min(...corners.map((c) => c[0])), mx1 = Math.max(...corners.map((c) => c[0]));
  const my0 = Math.min(...corners.map((c) => c[1])), my1 = Math.max(...corners.map((c) => c[1]));

  const hier: Record<string, number> = {};
  const loadPage = async (key: string) => {
    const buf = await fetchCached(`${BUCKET}/${project}/ept-hierarchy/${key}.json`, `h-${project}-${key}.json`, timeoutMs);
    Object.assign(hier, JSON.parse(buf.toString("utf8")) as Record<string, number>);
  };
  const keys: string[] = [];
  try {
    await loadPage("0-0-0-0");
    for (let depth = 0; depth <= 20 && keys.length < maxNodes; depth++) {
      const n = 2 ** depth;
      const ix0 = Math.max(0, Math.floor(((mx0 - b[0]) / (b[3] - b[0])) * n));
      const ix1 = Math.min(n - 1, Math.floor(((mx1 - b[0]) / (b[3] - b[0])) * n));
      const iy0 = Math.max(0, Math.floor(((my0 - b[1]) / (b[4] - b[1])) * n));
      const iy1 = Math.min(n - 1, Math.floor(((my1 - b[1]) / (b[4] - b[1])) * n));
      let any = false;
      for (let ix = ix0; ix <= ix1; ix++) {
        for (let iy = iy0; iy <= iy1; iy++) {
          for (const [k, c] of Object.entries(hier)) {
            if (!k.startsWith(`${depth}-${ix}-${iy}-`)) continue;
            any = true;
            if (c === -1) { await loadPage(k); keys.push(k); }
            else if (c > 0) keys.push(k);
          }
        }
      }
      if (!any && depth > 6) break;
    }
  } catch (err) {
    return { reason: `hierarchy walk failed: ${err instanceof Error ? err.message : String(err)}` };
  }

  const unique = [...new Set(keys)].slice(0, maxNodes);
  if (!unique.length) return { reason: `${project} has no nodes over this roof` };

  let points: CloudPoint[] = [];
  let bytes = 0;
  for (const key of unique) {
    try {
      const buf = await fetchCached(`${BUCKET}/${project}/ept-data/${key}.laz`, `data-${project}-${key}.laz`, timeoutMs);
      bytes += buf.length;
      points = points.concat(await decodeNode(buf, req.origin));
    } catch {
      // a missing or corrupt node is not fatal — the rest still describes the roof
    }
  }
  if (!points.length) return { reason: `${project} returned no readable points` };

  const inBox = points.filter((p) => p.x > req.box.x0 && p.x < req.box.x1 && p.y > req.box.y0 && p.y < req.box.y1);
  const groundZ = inBox.filter((p) => p.classification === 2).map((p) => p.z).sort((a, b) => a - b);
  return {
    cloud: {
      points: inBox,
      project,
      groundFt: groundZ.length ? groundZ[Math.floor(groundZ.length / 2)] : NaN,
      nodes: unique.length,
      bytes,
      ms: Date.now() - t0,
    },
  };
}

/** Stable key for logging which cloud a measurement used. */
export const cloudDigest = (c: LidarCloud): string =>
  createHash("sha256").update(`${c.project}:${c.points.length}:${c.nodes}`).digest("hex").slice(0, 12);
