// Smart Proposal procedures — Core building trades. See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  "concrete-contractor": {
    basis: "cubic yards of concrete placed by strength and mix; slab area in sqft by thickness; footings, forms and joints by linear ft",
    steps: [
      { item: "Layout from the plans: slab edges, footing lines, column pads and top-of-concrete elevations set with a transit or laser, pinned and string-lined; embeds and blockouts located", unit: "fixed" },
      { item: "Building permit for the structural concrete, pre-pour footing and reinforcing inspections scheduled, inspection fees", unit: "fixed" },
      { item: "Mobilization and protection: forms, screeds, power trowels and a skid steer delivered; truck and pump access laid out; wash-out pit set; adjacent surfaces covered", unit: "fixed" },
      { item: "Saw-cut, break out and haul away the existing slab or footings (thickness stated), rubble to a recycler", unit: "sqft", when: "existing concrete is removed" },
      { item: "Excavation to subgrade for the slab, footings and column pads, spoils stockpiled on site or hauled to a licensed fill site", unit: "cu yards" },
      { item: "Subgrade preparation: native soil scarified, moisture-conditioned and compacted to 95% Standard Proctor, proof-rolled; soft spots dug out and replaced with crushed stone", unit: "sqft" },
      { item: "Aggregate base: 4-6 in. of 3/4-minus crushed stone placed, graded to the slab elevation and compacted in lifts with a plate or roller compactor", unit: "cu yards" },
      { item: "Footings and thickened edges: 2x lumber forms set to line and grade, staked and braced; continuous #5 bars with corner bars, standees and dowels bent up into the walls or slab", unit: "linear ft" },
      { item: "Slab edge forms: steel or 2x lumber set to grade with keyways, blockouts and screed rails at the pour breaks", unit: "linear ft" },
      { item: "Vapor retarder: 15-mil polyethylene (ASTM E1745 Class A) over the base, seams lapped 6 in. and taped, penetrations and edges sealed", unit: "sqft", when: "the slab is under a building or conditioned space" },
      { item: "Slab reinforcing: #4 bars at 18 in. o.c. each way (or 6x6 W2.9xW2.9 welded wire) on chairs at mid-depth, laps tied, dowels drilled and epoxied into existing concrete", unit: "sqft" },
      { item: "Anchor bolts, hold-downs, column-base templates, sleeves and embed plates set to the plan before the pour", unit: "unit" },
      { item: "Concrete pump with operator and line for placements the truck chute cannot reach", unit: "fixed", when: "the pour cannot be reached by chute" },
      { item: "Footings placed: 3,000-psi concrete, vibrated, struck level at the wall or slab elevation with the dowels set", unit: "cu yards" },
      { item: "Slab placed: 4,000-psi concrete at a 4 in. slump, air-entrained where exposed to freezing, placed to the stated thickness, laser-screeded or wet-screeded and bull-floated", unit: "cu yards" },
      { item: "Finishing: power-trowel hard-trowel finish on interior slabs (FF 35 / FL 25 flatness), medium broom on exterior slabs, edges and joints tooled", unit: "sqft" },
      { item: "Control joints saw-cut to one-quarter of the slab depth within 6-12 hours of finishing, spaced at 24-36 times the thickness each way, or tooled in at the pour", unit: "linear ft" },
      { item: "Curing: liquid membrane curing compound (ASTM C309) sprayed at the finish, or wet-cured 7 days under sheeting; insulated blankets and heat below 40°F", unit: "sqft" },
      { item: "Concrete testing by an accredited lab: slump, air content and cylinder sets cast on site and broken at 7 and 28 days", unit: "fixed", when: "the engineer or specification requires testing" },
      { item: "Forms stripped, tie holes and honeycombing patched, footings and slab edges backfilled in compacted lifts", unit: "linear ft" },
      { item: "Penetrating siloxane sealer applied to exterior flatwork after 28 days of cure", unit: "sqft", when: "exterior flatwork is included" },
      { item: "Final cleanup: form lumber and stakes removed, wash-out pit dug out and disposed of, site raked and swept", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Concrete' or 'Pour' line with no strength, thickness or volume",
      "'Forming' with no linear feet or what is formed",
      "'Rebar' with no bar size, spacing or area",
      "'Mobilization' with nothing in it — say what is delivered and set up",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "pricing base, reinforcing and concrete as one slab line",
      "asphalt paving, plumbing under the slab or framing above it — other trades",
    ],
    notes: [
      "Slab thickness, reinforcing and concrete strength follow the structural drawings or the brief; quantities are measured from the plan dimensions",
      "Rock, groundwater, unsuitable soil or buried debris found at excavation is priced as a change order",
      "Cold-weather protection and hot-weather admixtures are included only when the pour date calls for them",
      "Under-slab plumbing, conduit and radiant tubing are set by their own trades before the vapor retarder goes down",
      "Testing lab fees are passed through at the lab's rate when the engineer requires testing",
    ],
  },

  "framing-contractor": {
    basis: "square feet of floor, wall and roof framed by system; beams, headers and posts each; sheathing by sqft; partitions by linear ft",
    steps: [
      { item: "Layout: foundation checked for square, level and anchor-bolt placement; wall lines, openings and bearing points snapped on the slab or deck from the plans", unit: "fixed" },
      { item: "Engineered lumber and truss submittals: I-joist, beam and truss layouts reviewed against the plan, bearing points and hardware confirmed before the packages are ordered", unit: "fixed" },
      { item: "Sill plates: pressure-treated 2x6 sills on foam sill seal, drilled to the anchor bolts and set with 3x3 plate washers and nuts", unit: "linear ft" },
      { item: "Floor framing: 11-7/8 in. I-joists or 2x10 sawn joists at 16 in. o.c. with rim board, joist hangers at the girders, mid-span blocking and squash blocks under bearing walls", unit: "sqft" },
      { item: "Beams, girders and posts: LVL, PSL or glulam beams and built-up or solid posts set to the plan on post bases and caps, bearing verified", unit: "unit" },
      { item: "Subfloor: 3/4 in. tongue-and-groove OSB or plywood glued to the joists with subfloor adhesive and screwed or ring-shank nailed at 6 in. edge and 12 in. field", unit: "sqft" },
      { item: "Exterior walls: 2x6 studs at 16 in. o.c. with double top plates, corners, jack and king studs, cripples and sills at the rough openings, built flat, raised plumb and braced", unit: "sqft" },
      { item: "Interior partitions: 2x4 studs at 16 in. o.c. with plates, backers at intersections, door rough openings and 2x6 plumbing walls where the drawings call for them", unit: "linear ft" },
      { item: "Headers: LVL or built-up 2x10 and 2x12 headers with flat 2x fillers over each window and door opening, bearing on jack studs per the header schedule", unit: "unit" },
      { item: "Shear walls: rated panels nailed per the schedule (8d at 4 in. edge, 12 in. field), hold-downs on anchor bolts or threaded rods, straps and blocking at the panel edges", unit: "linear ft", when: "the plans call out shear walls or braced wall lines" },
      { item: "Light-gauge steel framing: 20-ga studs at 16 in. o.c. in top and bottom track, screwed and bridged, with boxed headers", unit: "sqft", when: "the plans call for metal framing" },
      { item: "Wall sheathing: 7/16 in. OSB or 1/2 in. CDX plywood (or ZIP panels with taped seams) nailed 6 in. at edges and 12 in. in the field, edges blocked", unit: "sqft" },
      { item: "Blocking and backing: fire blocking at draft openings and soffits, mid-height blocking, and backing for cabinets, grab bars, handrails and drywall edges", unit: "linear ft" },
      { item: "Roof framing: engineered trusses set at 24 in. o.c. with hurricane ties and permanent bracing per BCSI, or stick-framed rafters, ridge, valleys and collar ties", unit: "sqft" },
      { item: "Crane or telehandler with operator for setting trusses, beams and wall panels", unit: "fixed", when: "trusses or beams need a crane" },
      { item: "Roof sheathing: 5/8 in. or 1/2 in. OSB or CDX with H-clips at the unsupported edges, nailed 6 in. at edges and 12 in. in the field", unit: "sqft" },
      { item: "Structural hardware: joist hangers, hurricane ties, straps, post bases and caps per the plan hardware schedule, fastened with the specified nails", unit: "unit" },
      { item: "Stairs: rough stringers cut from 2x12, treads and risers, landings framed and headed off", unit: "unit", when: "the plans include stairs" },
      { item: "Windows and exterior doors set plumb, level and square in the rough openings, shimmed and fastened to the manufacturer's instructions", unit: "unit", when: "window and door setting is in the framer's scope" },
      { item: "Temporary bracing and weather protection: wall braces, guardrails at openings and edges, tarps over open floors and roof between stages", unit: "fixed" },
      { item: "Framing inspection: walk-through with the inspector, engineer's field corrections and the punch list closed out", unit: "fixed" },
      { item: "Cleanup: cutoffs and packaging to the dumpster, floors swept and nails pulled, dumpster and haul fees", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Framing' or 'Lumber' line with no system, size or area",
      "'Hardware' with no hangers, ties or hold-downs named",
      "'Materials' and 'labor' as two lines with no work in them",
      "trim carpentry, siding, drywall or insulation — other trades",
      "pricing walls, sheathing and roof as one framing line",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
    ],
    notes: [
      "Framing lumber, engineered wood and hardware follow the structural drawings; species and grade are stated on the material list",
      "Squaring or shimming a foundation that is out of level by more than 1/2 in. is priced as a change order",
      "Windows, doors, trusses and beams are supplied by the owner or general contractor unless the estimate says otherwise",
      "Weather delays and temporary heat beyond the stated schedule are billed at the day rate",
      "Corrections from engineer's changes after framing starts are priced as a change order",
    ],
  },

  masonry: {
    basis: "square feet of wall by unit type (CMU, brick veneer, stone); lintels, sills and caps by linear ft or each; scaffold and cleaning by fixed",
    steps: [
      { item: "Layout and coursing: wall lines and corners set from the plans, brick ledge and footing checked for level, coursing rods made so bed joints land at heads and sills", unit: "fixed" },
      { item: "Mortar station and stocking: mixer, mortar tubs, sand and cement delivered; masonry units stacked at the wall or on the scaffold by forklift", unit: "fixed" },
      { item: "Frame scaffold with planks, guardrails, toe boards and ladder access set up, raised as the wall goes up and taken down", unit: "fixed", when: "the wall is over 5 ft tall" },
      { item: "Existing masonry removed: brick, block or stone cut out, salvageable units cleaned for reuse, debris to a dumpster", unit: "sqft", when: "existing masonry is removed or replaced" },
      { item: "CMU walls: 8 in. or 12 in. hollow block (ASTM C90) laid in running bond in Type S mortar, joints tooled concave, 9-ga ladder joint reinforcement every 16 in.", unit: "sqft" },
      { item: "Vertical reinforcing: #5 bars in the cells at 32-48 in. o.c. and each side of openings, lapped to the footing dowels, cells cleaned out at the base", unit: "linear ft" },
      { item: "Grout: 2,000-psi coarse grout placed in the reinforced cells and bond beams in lifts, consolidated by vibrator, with cleanouts at high lifts", unit: "cu yards" },
      { item: "Bond beams and lintels: bond-beam block with two #5 bars at floor and top-of-wall, precast or steel-angle lintels over each opening with 8 in. bearing", unit: "unit" },
      { item: "Brick veneer: modular clay brick (ASTM C216 Grade SW) in running bond, Type N mortar, 1 in. air space, adjustable ties at 16 in. o.c. each way, weeps at 24 in. above the flashing", unit: "sqft" },
      { item: "Through-wall flashing at the base, heads and sills: flexible membrane or stainless with a drip edge and end dams, lapped over the weep course", unit: "linear ft" },
      { item: "Stone veneer: natural or manufactured stone (adhered over lath and scratch coat, or anchored) set in a mortar bed, joints raked or grouted", unit: "sqft", when: "stone veneer is specified" },
      { item: "Sills, caps and copings: precast, cast-stone or limestone units set in mortar with a drip and washed joints", unit: "linear ft" },
      { item: "Control and expansion joints: vertical control joints in CMU at 25 ft o.c. and at openings, expansion joints in brick with backer rod and sealant", unit: "linear ft" },
      { item: "Repointing for restoration: deteriorated joints ground out 3/4 in. deep, dampened and repointed in lifts with a mortar matched to the original in color and strength", unit: "sqft", when: "existing walls are restored" },
      { item: "Cold- and hot-weather protection: walls covered at the end of each day, heated enclosures or admixtures below 40°F, damp curing above 100°F", unit: "fixed", when: "work falls in cold or hot weather" },
      { item: "Cleaning: new masonry washed with a masonry detergent approved by the brick manufacturer, pre-wetted and rinsed, mortar smears removed", unit: "sqft" },
      { item: "Water repellent: penetrating siloxane sealer applied to the finished wall after cleaning", unit: "sqft", when: "a sealer is specified" },
      { item: "Cleanup and demobilization: scaffold struck, mixer washed out, broken units and mortar waste hauled away", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Brick' or 'Block' line with no unit size, bond or area",
      "'Scaffolding' with no height or duration",
      "'Mortar' as a separate line — it belongs with the units it lays",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "concrete footings, steel lintels supplied by the steel fabricator, or stucco — other trades",
      "pricing veneer and its flashing, ties and weeps as one line",
    ],
    notes: [
      "Wall area is measured net of openings over 10 sqft; units, mortar type and bond follow the drawings or the brief",
      "The footing or brick ledge is assumed level within 1/2 in.; leveling a bad footing is priced as a change order",
      "Matching existing brick or stone depends on availability; a substitute is approved by the owner before ordering",
      "Steel lintels, embeds and anchors are supplied by the mason unless the drawings assign them to the steel package",
      "Cleaning uses the product the brick manufacturer approves; efflorescence that returns after cleaning is not a defect of the work",
    ],
  },

  "excavation-grading": {
    basis: "cubic yards cut, filled, imported and hauled; grading by sqft; trenching by linear ft; erosion control by linear ft or fixed",
    steps: [
      { item: "Utility locate (811 one-call ticket) and a private-utility scan of the work area, marks maintained through the job", unit: "fixed" },
      { item: "Grading permit, stormwater (SWPPP or erosion-control) permit and inspections, with the fees", unit: "fixed" },
      { item: "Construction staking: cut and fill stakes, grade stakes and offsets set by the surveyor; GPS machine-control model built from the grading plan", unit: "fixed" },
      { item: "Mobilization: excavator, dozer, wheel loader, vibratory roller and water truck delivered by lowboy, fuel and service on site", unit: "fixed" },
      { item: "Silt fence, fiber rolls and inlet protection installed at the downhill limits and around stockpiles", unit: "linear ft" },
      { item: "Stabilized construction entrance: 50 ft rock pad of 3-6 in. stone over geotextile at the site access", unit: "fixed" },
      { item: "Clearing and grubbing: brush, trees under 6 in., stumps and roots removed and chipped or hauled", unit: "sqft", when: "the site is vegetated" },
      { item: "Topsoil stripped 6-12 in. and stockpiled on site for reuse", unit: "cu yards" },
      { item: "Mass excavation: cut to design subgrade with GPS-guided excavator and dozer, material stockpiled or loaded out", unit: "cu yards" },
      { item: "Rock excavation: hoe-ram breaking or drilling and blasting of rock above subgrade", unit: "cu yards", when: "rock is encountered" },
      { item: "Haul-off of excess cut to a licensed fill site or recycler, including trucking and dump fees", unit: "cu yards", when: "the site has excess cut" },
      { item: "Imported structural fill: clean granular or select fill delivered from an approved pit", unit: "cu yards", when: "the site needs fill" },
      { item: "Fill placed and compacted in 8 in. lifts to 95% Modified Proctor (ASTM D1557), moisture-conditioned to the geotech's window", unit: "cu yards" },
      { item: "Compaction testing: nuclear density tests by the geotechnical lab at each lift and at subgrade", unit: "unit" },
      { item: "Building-pad and subgrade fine grading to plus or minus 0.1 ft, proof-rolled with a loaded truck, soft spots removed and replaced", unit: "sqft" },
      { item: "Utility trenching to laser grade at the stated depth, spoils windrowed, trench box or benching in trenches deeper than 5 ft", unit: "linear ft", when: "trenching is in scope" },
      { item: "Dewatering: sump pumps or well points with a settling tank and discharge control", unit: "fixed", when: "groundwater is present" },
      { item: "Water truck for dust control on haul roads and open cuts", unit: "hour" },
      { item: "Slope stabilization: hydroseed or straw and tackifier on cut and fill slopes as they are finished", unit: "sqft", when: "slopes are left exposed" },
      { item: "Final grading and topsoil respread to finished grade, drainage swales shaped to the plan", unit: "sqft" },
      { item: "Demobilization: equipment hauled off, erosion controls removed after the site is stabilized, entrance rock left in place", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Excavation' or 'Grading' line with no volume, depth or area",
      "'Hauling' with no volume or destination",
      "'Equipment' as a line with nothing operated or moved",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "underground utility pipe, concrete or paving — other trades",
      "pricing cut, haul and fill as one earthwork line",
    ],
    notes: [
      "Cut and fill volumes are taken from the grading plan or a site survey and measured in bank cubic yards; shrink and swell are stated in the takeoff",
      "Rock, groundwater, buried debris or contaminated soil is priced as a change order at the stated unit rates",
      "Compaction testing is by the owner's geotechnical lab unless the estimate includes it",
      "Erosion controls are maintained through the job; removal after stabilization is included",
      "Haul distance and dump fees are based on the named disposal site",
    ],
  },

  "foundation-retaining": {
    basis: "linear feet of footing and wall by height and thickness; concrete by cu yards; waterproofing by sqft; drains and backfill by linear ft and cu yards",
    steps: [
      { item: "Layout: footing and wall lines, corners and elevations set from the plans with a transit or laser, batter boards and offsets pinned", unit: "fixed" },
      { item: "Engineering and permit: stamped design for retaining walls over 4 ft or surcharged walls, building permit and the footing and wall inspections", unit: "fixed" },
      { item: "Utility locate (811) and a private scan along the footing line before digging", unit: "fixed" },
      { item: "Excavation for the footings and walls with working room, spoils stockpiled, banks benched or shored per OSHA; existing wall or slab cut back where needed", unit: "cu yards" },
      { item: "Footing subgrade leveled, compacted and checked for the design bearing; over-dig replaced with compacted crushed stone", unit: "sqft" },
      { item: "Footings: 2x forms set to line and grade, continuous #5 bars (three, top and bottom where drawn), corner bars and vertical dowels at the wall spacing, 3,000-psi concrete", unit: "linear ft" },
      { item: "Cast-in-place walls: two-sided panel forms with snap ties, #5 verticals at 12-16 in. o.c. and #4 horizontals at 12 in. o.c., keyway and step-downs formed, forms stripped and tie holes patched", unit: "linear ft" },
      { item: "Anchor bolts, hold-downs, beam pockets, sleeves and embeds set to the plan before the wall pour", unit: "unit" },
      { item: "Concrete pump with operator for the footing and wall placements", unit: "fixed", when: "the pour cannot be reached by chute" },
      { item: "Wall concrete: 4,000-psi placed in 2-4 ft lifts and vibrated, top struck to elevation, cured 7 days before backfill", unit: "cu yards" },
      { item: "Segmental block retaining wall: units on a 6 in. compacted crushed base, first course leveled, geogrid layers at the design spacing, 12 in. of drainage stone behind the face, caps glued", unit: "sqft", when: "a segmental block wall is specified" },
      { item: "CMU stem wall: 8 in. block (ASTM C90) on the footing, cells with #5 bars grouted solid, bond beam at the top with anchor bolts", unit: "linear ft", when: "a block stem wall is specified" },
      { item: "Underpinning: sequential 3-4 ft pits under the existing footing, dry-packed to bearing, or push piers with brackets driven to refusal", unit: "unit", when: "the existing foundation is underpinned" },
      { item: "Waterproofing: fluid-applied membrane at 60 mil dry (or peel-and-stick sheet) on the earth side of the wall, with dimple drainage board or protection board", unit: "sqft", when: "the wall encloses a basement or habitable space" },
      { item: "Damp-proofing: asphalt emulsion sprayed on the earth side of the stem wall", unit: "sqft", when: "the wall is a crawl-space or garage stem wall" },
      { item: "Footing drain: 4 in. perforated PVC or corrugated HDPE in washed stone wrapped in filter fabric, run to daylight or a sump", unit: "linear ft" },
      { item: "Backfill: free-draining gravel against the wall, then native or imported fill compacted in 12 in. lifts, held off the wall until the concrete has cured", unit: "cu yards" },
      { item: "Excess spoils hauled to a licensed fill site, including trucking and dump fees", unit: "cu yards", when: "spoils leave the site" },
      { item: "Inspections: footing and reinforcing inspection before each pour, special inspection of reinforcing and concrete where the engineer requires it", unit: "fixed" },
      { item: "Cleanup and demobilization: forms and ties hauled off, wash-out removed, disturbed grade raked", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Foundation' or 'Wall' line with no height, thickness or linear feet",
      "'Concrete' with no strength or volume",
      "'Waterproofing' with no product, thickness or area",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "framing above the sill, slab-on-grade or landscape above the wall — other trades",
      "pricing the footing, wall and backfill as one line",
    ],
    notes: [
      "Wall height, thickness and reinforcing follow the stamped design or the brief; linear feet are measured along the wall centerline",
      "Bearing soil is assumed as the geotechnical report or the design states; unsuitable soil, rock or water at the footing is priced as a change order",
      "Backfill waits until the concrete reaches design strength; a wall backfilled early by others is not covered by the warranty",
      "Engineering fees and permits are passed through at cost when the owner has not already supplied a stamped design",
    ],
  },

  "structural-steel": {
    basis: "tons of structural steel priced per piece with the weight stated; deck by sqft; misc. metals by linear ft or each; crane by day",
    steps: [
      { item: "Shop drawings and erection drawings: connection design by the fabricator's engineer, piece marks and bolt lists, submitted for the engineer of record's review", unit: "fixed" },
      { item: "Anchor-bolt survey: column lines, bolt projections and base-plate elevations checked against the plan before fabrication is released", unit: "fixed" },
      { item: "Material: A992 wide-flange, A500 Gr. B HSS, A36 plate and angle, A325 or A490 bolts, with mill certifications, per piece with the weight stated", unit: "unit" },
      { item: "Shop fabrication: members cut to length, coped, drilled and punched, stiffeners and connection plates welded to AWS D1.1, fit-up checked", unit: "unit" },
      { item: "Shop coating: SSPC-SP6 blast and shop primer (or hot-dip galvanizing to ASTM A123 for exterior steel)", unit: "sqft" },
      { item: "Delivery: flatbed loads sequenced to the erection plan, unloaded and shaken out at the site", unit: "fixed" },
      { item: "Hydraulic crane with operator, rigger and rigging, sized for the heaviest pick and the reach, day rate", unit: "fixed" },
      { item: "Erection: columns set on leveling nuts or shims, plumbed and temporarily guyed; beams and girders set and connected", unit: "unit" },
      { item: "Base plates grouted with non-shrink grout after the frame is plumbed and bolted", unit: "unit" },
      { item: "Bolted connections: A325 bolts installed snug-tight or pretensioned by turn-of-nut or tension-control bolts per the connection schedule", unit: "unit" },
      { item: "Field welding: moment connections and CJP welds by AWS-certified welders with preheat, backing bars and weld access holes per the drawings", unit: "unit", when: "the drawings call for field-welded connections" },
      { item: "Metal deck: 1-1/2 in. 20-ga galvanized composite or roof deck, puddle-welded or screwed at 12 in. o.c., side laps fastened, pour stop and closures", unit: "sqft", when: "metal deck is in the steel package" },
      { item: "Shear studs: 3/4 in. x 4-7/8 in. headed studs welded through the deck at the spacing on the framing plan", unit: "unit", when: "the floor is composite" },
      { item: "Miscellaneous metals: stair stringers and pans, ledger angles, embed plates, lintels, bollards and pipe supports", unit: "unit", when: "misc. metals are in the steel package" },
      { item: "Special inspection coordination: third-party bolt and weld inspection, ultrasonic testing of CJP welds, inspection reports to the engineer", unit: "fixed" },
      { item: "Field touch-up: zinc-rich primer on field welds, bolt heads and damaged shop coating", unit: "fixed" },
      { item: "Safety: site-specific erection and fall-protection plan, perimeter cable, controlled decking zone, daily crane and rigging inspections", unit: "fixed" },
      { item: "Cleanup and demobilization: shake-out area cleared, scrap and cribbing hauled, crane demobilized", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Steel' or 'Erection' line with no sections, pieces or tonnage",
      "'Crane' with no size, duration or what it lifts",
      "'Welding' with no connection type or count",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "concrete footings, anchor-bolt setting or fireproofing — other trades",
      "pricing fabrication and erection as one steel line",
    ],
    notes: [
      "Tonnage is taken from the structural drawings; the price per piece carries the piece's fabricated weight",
      "Anchor bolts are set by the concrete contractor to the fabricator's template; out-of-tolerance bolts are corrected as a change order",
      "Special inspection is hired by the owner; the fabricator provides access, certifications and the welding procedures",
      "Steel is priced at the mill rate on the estimate date; a mill price change before release is passed through",
      "Erection assumes a clear, compacted crane pad and access; crane matting or a larger crane for reach is priced as a change",
    ],
  },

  "concrete-flatwork": {
    basis: "square feet of slab by thickness and finish; concrete by cu yards; curb, gutter and joints by linear ft; ADA ramps each",
    steps: [
      { item: "Layout and grades: edges, flow lines and spot elevations set from the plan, slopes checked (cross slope under 2% on walks, 1/8 in. per ft minimum for drainage)", unit: "fixed" },
      { item: "Right-of-way or encroachment permit and inspection for public sidewalk, curb and driveway apron work", unit: "fixed", when: "work is in the public right-of-way" },
      { item: "Traffic and pedestrian control: signs, barricades, cones and a closed-walk detour", unit: "fixed", when: "work is along a street or open walkway" },
      { item: "Saw-cut, break out and haul away existing concrete or asphalt (thickness stated), rubble to a recycler", unit: "sqft", when: "existing pavement is removed" },
      { item: "Excavation to subgrade for the slab and base, spoils loaded and hauled", unit: "cu yards" },
      { item: "Subgrade compacted to 95% and proof-rolled, soft spots dug out and replaced", unit: "sqft" },
      { item: "Aggregate base: 4 in. of 3/4-minus crushed stone (6 in. under heavy-duty pads) placed and compacted", unit: "cu yards" },
      { item: "Forms: 2x4 and 2x6 lumber or steel forms set to line and grade, flexible forms at curves, pinned and braced", unit: "linear ft" },
      { item: "Reinforcing: 6x6 W1.4xW1.4 welded wire on chairs or #4 bars at 18 in. o.c. each way; #5 at 12 in. o.c. in dumpster pads and truck aprons", unit: "sqft" },
      { item: "Isolation joints: 1/2 in. expansion material against buildings, columns, curbs and existing slabs, with smooth dowels at truck-traffic joints", unit: "linear ft" },
      { item: "Concrete placed: 4,000-psi air-entrained mix at the stated thickness (4 in. walks, 6 in. drives, 8 in. heavy-duty pads), screeded and bull-floated", unit: "cu yards" },
      { item: "Curb and gutter: machine-extruded or hand-formed 6 in. curb with 18-24 in. gutter, 3,500-psi concrete, expansion joints at 10 ft", unit: "linear ft", when: "curb and gutter is in scope" },
      { item: "ADA curb ramps: ramps at 1:12 with flared sides, landings and cast-in-place detectable warning surfaces to the current PROWAG or state standard", unit: "unit", when: "public walks or accessible routes are included" },
      { item: "Finish: medium broom perpendicular to traffic, edges and joints tooled with a 1/4 in. radius", unit: "sqft" },
      { item: "Control joints saw-cut to one-quarter of the slab depth at a spacing of 24-30 times the thickness, or tooled at the pour", unit: "linear ft" },
      { item: "Curing: membrane curing compound (ASTM C309) sprayed at the finish, insulated blankets below 40°F", unit: "sqft" },
      { item: "Concrete testing by the lab: slump, air and cylinder sets per the specification", unit: "fixed", when: "the specification requires testing" },
      { item: "Forms stripped, edges backfilled and compacted, adjoining asphalt or landscape restored", unit: "linear ft" },
      { item: "Penetrating sealer applied after 28 days", unit: "sqft", when: "a sealer is specified" },
      { item: "Cleanup: form material hauled off, wash-out removed, site swept and traffic control pulled", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Concrete', 'Slab' or 'Sidewalk' line with no thickness, area or finish",
      "'Prep' with no excavation depth, base or compaction",
      "'Joints' with no type, spacing or linear feet",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "asphalt paving, striping or storm drains — other trades",
      "pricing base, reinforcing and concrete as one flatwork line",
    ],
    notes: [
      "Slab thickness, mix and reinforcing follow the plan or the brief; area is measured to the form lines",
      "Subgrade is assumed stable at 95% compaction; unsuitable soil, rock or utilities in the way are priced as a change order",
      "ADA ramps and detectable warnings follow the current accessibility standard adopted by the jurisdiction",
      "Testing is by the owner's lab unless the estimate includes it; cold-weather protection is included only when the pour date requires it",
      "Curing time before traffic: 24-48 hours for foot traffic, 7 days for vehicles",
    ],
  },

  "residential-concrete-flatwork": {
    basis: "square feet of driveway, walk or patio by thickness and finish; concrete by cu yards; tear-out by sqft; edges and joints by linear ft",
    steps: [
      { item: "Site walk and layout: driveway, walk or patio outline painted with the owner, slope set away from the house (1/4 in. per ft), downspouts, meters and door thresholds located", unit: "fixed" },
      { item: "Utility locate (811) plus sprinkler heads, low-voltage lighting and drain lines flagged by hand", unit: "fixed" },
      { item: "City driveway-approach or sidewalk permit and the inspection", unit: "fixed", when: "the apron or public sidewalk is replaced" },
      { item: "Break out, load and haul away the old driveway, walk or patio (thickness stated), including dump fees", unit: "sqft", when: "existing concrete or pavers are removed" },
      { item: "Protection: plywood over the lawn for the truck and skid steer, siding and doors masked from splatter, plants tied back", unit: "fixed" },
      { item: "Excavate and grade the subgrade to depth, spoils hauled off", unit: "cu yards" },
      { item: "Crushed-stone base: 4 in. of 3/4-minus placed and compacted with a plate compactor", unit: "cu yards" },
      { item: "Forms: 2x4 and 2x6 lumber staked to line and grade, bender board at curves, thickened edge at the driveway", unit: "linear ft" },
      { item: "Reinforcing: #3 bars at 24 in. o.c. each way on chairs (or 6x6 welded wire) with fiber in the mix", unit: "sqft" },
      { item: "Expansion joints: 1/2 in. fiber board against the house, garage slab, stoop and existing walks", unit: "linear ft" },
      { item: "Drainage: channel drain at the garage door or catch basin at the low spot, piped 4 in. to daylight or a dry well", unit: "linear ft", when: "water needs to be caught at a low spot or the garage" },
      { item: "Concrete placed: 4,000-psi air-entrained mix, 4 in. at walks and patios and 5-6 in. at the driveway, screeded and floated", unit: "cu yards" },
      { item: "Finish: broom, or exposed aggregate washed with a surface retarder, edges tooled", unit: "sqft" },
      { item: "Decorative finish: integral color, release agent and stamped pattern, or hand-troweled borders", unit: "sqft", when: "a stamped or colored finish is chosen" },
      { item: "Control joints tooled at the pour at 8-10 ft spacing (sawn on stamped work)", unit: "linear ft" },
      { item: "Curing compound sprayed at the finish; plastic and blankets in cold weather", unit: "sqft" },
      { item: "Sealer: acrylic or penetrating sealer after 28 days (two coats on stamped or colored concrete)", unit: "sqft", when: "the finish is sealed" },
      { item: "Forms stripped, edges backfilled with topsoil and seeded, lawn ruts repaired", unit: "linear ft" },
      { item: "Cleanup: stakes and forms hauled, wash-out taken off site, driveway swept; keep-off tape until the concrete can take weight", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Driveway' or 'Patio' line with no thickness, finish or square feet",
      "'Tear-out' with no thickness or dump fee",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "pavers, retaining walls or landscaping — other trades",
      "pricing tear-out, base and new concrete as one line",
    ],
    notes: [
      "Thickness: 4 in. at walks and patios, 5-6 in. at driveways unless the brief says otherwise; area is measured to the form lines",
      "Old concrete is assumed 4 in. unreinforced; thicker or reinforced slabs are priced as a change order",
      "Stay off the new concrete: 24 hours for foot traffic, 7 days for cars",
      "Color and stamp samples are approved by the owner before the pour; sealer is reapplied every 2-3 years by the owner",
      "Sprinkler lines and low-voltage wiring not flagged before digging are repaired at the hourly rate",
    ],
  },

  "residential-foundation-repair": {
    basis: "piers each by type and depth; crack injection and wall bracing by linear ft or each; slab lifting by sqft; assessment and warranty by fixed",
    steps: [
      { item: "Foundation assessment: floor elevation survey with a manometer or Zip Level, crack mapping with photos, drainage and grading review, written repair plan", unit: "fixed" },
      { item: "Structural engineer's stamped repair plan and letter", unit: "fixed", when: "the city, lender or insurer requires an engineer's plan" },
      { item: "Building permit and the inspection, with the fees", unit: "fixed" },
      { item: "Utility locate (811) and hand-probing at each pier location for drains, gas and sprinkler lines", unit: "fixed" },
      { item: "Access pits: 3 x 3 ft pits hand-dug to the footing at each pier location, concrete or landscaping removed and set aside, flooring protected inside", unit: "unit" },
      { item: "Push piers: 2-7/8 in. or 3-1/2 in. galvanized steel pier sections driven hydraulically to refusal on bedrock or load-bearing strata, foundation bracket bolted to the footing, load-tested", unit: "unit" },
      { item: "Helical piers: 2-7/8 in. shaft with 8/10/12 in. helix plates screwed to design torque, bracket set to the footing", unit: "unit", when: "soils or access call for helical piers over push piers" },
      { item: "Synchronized hydraulic lift: the settled section raised toward original elevation, brackets locked and shimmed, lift stopped where cracking risk outweighs the gain", unit: "fixed" },
      { item: "Slab lifting: 5/8 in. injection holes drilled through the sunken slab, high-density polyurethane foam injected to lift and fill voids, holes patched", unit: "sqft", when: "an interior slab, garage or porch has settled" },
      { item: "Crack injection: epoxy or polyurethane injected through surface ports into foundation wall cracks, ports removed and the face ground smooth", unit: "linear ft", when: "cracks leak or need structural bonding" },
      { item: "Carbon-fiber straps: 12 in. wide straps epoxied to a bowing wall at 4 ft o.c. with top anchors", unit: "unit", when: "a basement wall bows less than 2 in." },
      { item: "Wall anchors or steel I-beam braces: plate anchors set in the yard or beams bolted to the floor and joists at 5-6 ft o.c.", unit: "unit", when: "a basement wall bows or leans more than 2 in." },
      { item: "Drainage correction: downspout extensions, regrading against the house or an interior perimeter drain to a sump pump", unit: "linear ft", when: "water at the foundation caused the movement" },
      { item: "Pits backfilled and tamped, concrete patched, sod and landscaping put back", unit: "unit" },
      { item: "Post-repair elevation survey and a report with before and after readings and pier depths", unit: "fixed" },
      { item: "Warranty registration: transferable lifetime pier warranty and the annual monitoring visit", unit: "fixed" },
      { item: "Final cleanup: interior floors cleaned, spoils hauled, walk-through with the owner", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Foundation repair' or 'Piers' line with no pier type, count or depth",
      "'Lift' with no method or what is lifted",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "cosmetic drywall, brick or flooring repair after the lift — other trades unless priced separately",
      "pricing piers and the lift as one line",
    ],
    notes: [
      "Pier count and spacing follow the assessment or the engineer's plan (typically 5-8 ft o.c. along the settled wall); depth to refusal is estimated and adjusted to what is found",
      "Lifting is a best effort: the house is raised only as far as the structure will take without new damage",
      "Cosmetic repairs to drywall, brick, doors and flooring after the lift are excluded",
      "Warranty covers the piers and the repaired section, not areas of the foundation left untreated",
      "Engineer's fees and permits are passed through at cost",
    ],
  },

  "house-lifting": {
    basis: "the lift priced by house footprint (sqft) and lift height; steel, cribbing and jacking by fixed; utilities, foundation and stairs by their own units",
    steps: [
      { item: "Structural engineering: lift plan, needle-beam and main-beam design, new foundation design to the target elevation, stamped drawings", unit: "fixed" },
      { item: "Permits: building permit, floodplain development permit and the FEMA elevation certificate before and after", unit: "fixed" },
      { item: "Utility disconnects: electric meter pulled, gas capped at the meter, water and sewer cut and capped, HVAC lines and ducts detached", unit: "fixed" },
      { item: "Prep: porches, decks, steps, chimney bracing and interior contents secured or removed; fragile finishes photographed", unit: "fixed" },
      { item: "Beam pockets opened through the foundation wall or skirting for steel insertion", unit: "unit" },
      { item: "Steel: W12 to W18 main beams and cross needles inserted under the floor framing, shimmed tight to the joists, cribbing towers built under each beam end", unit: "unit" },
      { item: "Unified hydraulic jacking system: synchronized jacks under each beam, the house lifted in 8-12 in. increments and blocked at each stage", unit: "fixed" },
      { item: "Temporary shoring at the lifted height: cribbing, cross-bracing and wind tie-downs, house held level while foundation work goes on", unit: "fixed" },
      { item: "Old foundation demolished and hauled off (concrete, block or piers)", unit: "cu yards", when: "the old foundation is replaced" },
      { item: "New foundation: footings and stem walls, CMU piers or a full-height wall with reinforcing, anchor bolts and flood vents to the engineered height", unit: "linear ft", when: "the new foundation is in the lift contractor's scope" },
      { item: "House lowered onto the new foundation, sill plates and anchor bolts set and tightened, hold-downs connected", unit: "fixed" },
      { item: "Steel and cribbing removed, beam pockets closed", unit: "fixed" },
      { item: "Utilities reconnected and extended to the new elevation: water, sewer, gas, electric, HVAC", unit: "fixed" },
      { item: "New stairs, landings and porch framing to the raised entries, with guardrails", unit: "unit" },
      { item: "Backfill, grading and settling of the site around the new foundation", unit: "cu yards" },
      { item: "Inspections and the final elevation certificate", unit: "fixed" },
      { item: "Cleanup and demobilization: debris hauled, cribbing trucked off, walk-through with the owner", unit: "fixed" },
    ],
    avoid: [
      "a bare 'House lift' or 'Raise' line with no height, footprint or method",
      "'Steel' with no beam sizes or count",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "interior drywall, siding or landscaping — other trades",
      "pricing the lift and the new foundation as one line",
    ],
    notes: [
      "Lift height and footprint are taken from the brief and the engineer's plan; the house is assumed to be conventionally framed on a perimeter foundation",
      "Hidden rot, termite damage or an undersized floor system found at beam insertion is priced as a change order",
      "Plaster cracks and cosmetic damage from lifting are excluded; the house is lifted and set level within 1/2 in.",
      "Utility company fees, meter resets and the electrician's or plumber's work are passed through or excluded as stated",
      "The FEMA elevation certificate is surveyed by a licensed surveyor and passed through at cost",
    ],
  },

  "seismic-retrofit": {
    basis: "anchor bolts, plates, hold-downs and straps each; cripple-wall bracing by linear ft; engineering, permit and inspection by fixed",
    steps: [
      { item: "Retrofit assessment: crawl-space inspection of the foundation type and condition, existing bolts, cripple-wall height and floor framing, photographed and written up", unit: "fixed" },
      { item: "Retrofit plan: prescriptive Standard Plan A or IEBC Chapter A3 plan set, or an engineer's stamped plan where the house does not fit the standard plan", unit: "fixed" },
      { item: "Building permit and the rough and final inspections", unit: "fixed" },
      { item: "Crawl-space access: hatch enlarged, debris cleared, ducts and wiring moved aside, vapor barrier and work lighting set", unit: "fixed" },
      { item: "Foundation bolting: 5/8 in. anchor bolts at 4-6 ft o.c. drilled into the concrete, set in epoxy (Simpson SET-3G or equal) with 3 x 3 in. plate washers", unit: "unit" },
      { item: "Foundation plates (Simpson UFP10 or equal) where there is no room to drill through the sill", unit: "unit", when: "sill access blocks a vertical bolt" },
      { item: "Cripple-wall bracing: 15/32 in. Structural I plywood nailed to the studs with 8d at 4 in. o.c. at edges, blocking at panel edges, ventilation holes cut", unit: "linear ft" },
      { item: "Framing anchors: Simpson L90 or A35 clips connecting the floor joists and rim to the cripple-wall top plate", unit: "unit" },
      { item: "Hold-downs: HDU hold-downs on threaded rods epoxied into the foundation at the ends of braced wall lines", unit: "unit", when: "the plan is engineered or calls for hold-downs" },
      { item: "Post-to-beam and post-to-pier connections: post caps, bases and straps at interior piers and girders", unit: "unit" },
      { item: "Water heater strapped with a seismic bracing kit at the upper and lower third", unit: "unit" },
      { item: "Automatic seismic gas shutoff valve at the meter", unit: "unit", when: "a gas shutoff valve is requested or required" },
      { item: "Chimney bracing or removal of the unreinforced masonry above the roofline", unit: "fixed", when: "the house has an unreinforced masonry chimney" },
      { item: "Soft-story steel moment frame or shear walls at the garage or ground-floor opening", unit: "unit", when: "the building has a soft story over a garage or open ground floor" },
      { item: "Inspections walked with the inspector, corrections closed out", unit: "fixed" },
      { item: "Cleanup: crawl-space debris hauled, vents and hatch restored, retrofit documentation and photos for the insurer or Earthquake Brace + Bolt program", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Bolting' or 'Bracing' line with no bolt size, spacing or linear feet",
      "'Hardware' with no connector names or count",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "foundation replacement or house lifting — separate scopes",
      "pricing bolts, plywood and clips as one retrofit line",
    ],
    notes: [
      "Bolt and clip spacing follow the standard plan or the engineer's design; counts are measured from the crawl-space survey",
      "An unreinforced or deteriorated concrete foundation that will not hold epoxy anchors is priced as a separate foundation scope",
      "Work above the first floor, chimneys and soft-story frames are excluded unless listed",
      "Program rebates (Earthquake Brace + Bolt) belong to the owner; the documentation package is included",
    ],
  },
};
