// Smart Proposal procedures — Development & Construction Consulting. See ./types.ts.
//
// Professional services: each procedure is the list of deliverables and phases
// the consultant actually bills — kickoff and data collection by the hour,
// research fixed or hourly, each named analysis or report as a fixed
// deliverable (or a unit per scenario, intersection, study, milestone),
// agency meetings and hearings by the hour, fees and notices as fixed
// pass-throughs, monthly services as a unit "per month", reimbursables fixed.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  "land-development-analysis": {
    basis: "fixed fee per deliverable by parcel and number of development scenarios; site time, meetings and revisions by the hour",
    steps: [
      { item: "Kickoff meeting and data request: client objectives, target product, acquisition terms, prior reports, survey and title commitment collected", unit: "hour" },
      { item: "Site reconnaissance: walk the parcel, photograph frontage, access, drainage patterns, existing structures and neighboring uses; note visible wetlands, slopes and utilities", unit: "hour" },
      { item: "Records research: county assessor, recorded plat and deed, title exceptions and easements, FEMA flood map, NWI wetlands, NRCS soils, GIS parcel data and aerial history", unit: "fixed" },
      { item: "Zoning and comprehensive-plan review memo: district, permitted uses, density, setbacks, height, parking, overlay districts and the approval path the intended use triggers", unit: "fixed" },
      { item: "Site constraints exhibit: net developable acreage after floodplain, wetland buffers, steep slopes, easements and required open space, drawn over the survey or GIS base", unit: "fixed" },
      { item: "Conceptual yield plan per scenario: lot or unit layout with road network, stormwater pond footprint and open space, yield stated for each scenario", unit: "unit" },
      { item: "Infrastructure and utility assessment: sewer and water availability or will-serve inquiries, capacity, offsite extension routes, storm outfall, roadway access and turn-lane triggers", unit: "fixed" },
      { item: "Preliminary site development cost opinion by scenario: clearing, grading, roads, utilities, stormwater, offsite extensions, impact and connection fees", unit: "fixed" },
      { item: "Market and absorption inputs: comparable lot or unit pricing, absorption pace and competing supply in the submarket", unit: "fixed" },
      { item: "Development pro forma per scenario: land basis, hard and soft costs, financing, revenue by phase, residual land value, unleveraged IRR and equity multiple with a sensitivity table", unit: "unit" },
      { item: "Land development analysis report: constraints, yield, cost, pro forma and a go/no-go recommendation with the risks that move the number", unit: "fixed" },
      { item: "Presentation of findings to the client, partners or investment committee", unit: "hour" },
      { item: "Pre-application meeting with the planning department to confirm the approval path and known issues before closing", unit: "hour", when: "the client wants the jurisdiction's read before the purchase contingency expires" },
      { item: "Revisions to the yield plan or pro forma for a changed program, pricing or acquisition terms", unit: "hour" },
      { item: "Reimbursables: GIS data, recorded document copies, title and survey copies, printing and mileage", unit: "fixed" },
    ],
    avoid: [
      "a single 'Feasibility analysis' or 'Due diligence' line covering the whole study",
      "'Research' or 'Consulting' with no deliverable named",
      "pricing the pro forma and the report as one line",
      "wetland delineation, boundary survey, geotechnical borings or a Phase I ESA priced as if the analyst performs them",
      "a per-acre fee with no scope behind it",
    ],
    notes: [
      "The yield plan is conceptual for capacity and pricing; it is not an engineered site plan or a plat",
      "Wetland delineation, boundary and topographic survey, geotechnical work and a Phase I ESA are excluded and recommended as separate scopes",
      "Utility will-serve responses depend on the utility's turnaround and are outside the analyst's schedule control",
      "Market and cost inputs are current as of the report date; the pro forma uses the client's cost of capital and return hurdles",
    ],
  },
  "feasibility-study": {
    basis: "fixed fee per study phase and deliverable, scaled by the number of scenarios and the size of the market area; presentations and revisions by the hour",
    steps: [
      { item: "Kickoff workshop: project objectives, decision criteria, scenarios to test, data the client already holds and the study schedule", unit: "hour" },
      { item: "Site and regulatory screening: location, access, zoning fit, utility availability, environmental flags and the approvals each scenario would need", unit: "fixed" },
      { item: "Market analysis: trade-area definition, demographics and employment, competitive supply inventory, rent or sales comparables, absorption history and the development pipeline", unit: "fixed" },
      { item: "Demand estimate and positioning: capture rate, target segment, unit mix or program size and a pricing recommendation", unit: "fixed" },
      { item: "Development program per scenario: massing, unit count or square footage, parking and phasing for each alternative studied", unit: "unit" },
      { item: "Order-of-magnitude cost estimate per scenario: hard costs by building system, site work, soft costs, fees, contingency and escalation to the construction midpoint", unit: "unit" },
      { item: "Operating and financial projections per scenario: 10-year cash flow, stabilized NOI, debt sizing and returns (IRR, cash-on-cash, DSCR)", unit: "unit" },
      { item: "Sensitivity and break-even analysis: rent, cost, cap rate and absorption ranges, and the threshold at which the project stops working", unit: "fixed" },
      { item: "Feasibility report: findings, scenario comparison matrix, recommendation and the assumptions register", unit: "fixed" },
      { item: "Executive summary and lender or investor package version of the report", unit: "fixed", when: "the study supports a financing request or a partner solicitation" },
      { item: "Interviews with brokers, lenders, operators and local officials to test the market findings", unit: "hour" },
      { item: "Presentation of findings to the client, board or lender, with questions taken", unit: "hour" },
      { item: "Revisions for a changed program, an added scenario or updated assumptions after the draft", unit: "hour" },
      { item: "Reimbursables: market data subscriptions, demographic reports, travel and printing", unit: "fixed" },
    ],
    avoid: [
      "one 'Feasibility study' line with a lump sum and no phases",
      "'Market research' with no trade area, comps or absorption named",
      "a financial projection line that does not say which scenarios it covers",
      "a design fee or an engineered cost estimate — the study uses order-of-magnitude costs",
      "'Analysis' or 'Report' as bare lines",
    ],
    notes: [
      "Cost figures are order-of-magnitude for decision-making, not a bid; accuracy is stated in the report",
      "Market data comes from third-party subscriptions and public sources current at the report date",
      "Financial projections use the client's assumptions for equity, debt terms and exit; the consultant does not offer investment advice",
      "Site engineering, environmental studies and appraisals are excluded",
    ],
  },
  "highest-best-use": {
    basis: "fixed fee per analysis by the number of candidate uses tested, as vacant and as improved; inspection, meetings and revisions by the hour",
    steps: [
      { item: "Engagement kickoff: intended use of the analysis, effective date, property rights considered, candidate uses the client wants tested and records collected", unit: "hour" },
      { item: "Property inspection: site size and shape, frontage, topography, access, visibility, improvements and their condition, surrounding uses photographed", unit: "hour" },
      { item: "Legal permissibility test: zoning district and permitted uses, overlays, deed restrictions and covenants, easements, and the realistic path for a use that needs a change", unit: "fixed" },
      { item: "Physical possibility test: usable area after setbacks and easements, soils and drainage flags, utility availability and the building footprint each use requires", unit: "fixed" },
      { item: "Market study per candidate use: supply, demand, rents or sale prices, absorption and vacancy in the competitive area", unit: "unit" },
      { item: "Financial feasibility test per candidate use: development cost, stabilized value or sale proceeds, and residual land value at the returns the market requires", unit: "unit" },
      { item: "Maximally productive conclusion: ranked uses, timing (develop now, hold or interim use) and the ideal improvement described", unit: "fixed" },
      { item: "As-improved analysis: whether the existing improvements contribute value, renovation versus demolition, and the interim use conclusion", unit: "fixed", when: "the property is improved" },
      { item: "Highest and best use report: four-test narrative, exhibits, market data and the conclusion, USPAP-compliant where written by a certified appraiser", unit: "fixed" },
      { item: "Review of the draft with the client and their counsel or lender", unit: "hour" },
      { item: "Deposition or testimony support in litigation, condemnation or an assessment appeal", unit: "hour", when: "the analysis is for litigation, condemnation or an assessment appeal" },
      { item: "Revisions for a changed effective date, an added candidate use or new market evidence", unit: "hour" },
      { item: "Reimbursables: comparable data services, public records, travel and printing", unit: "fixed" },
    ],
    avoid: [
      "a single 'Highest and best use' line without the four tests",
      "'Valuation' or 'Appraisal' as a bare line — the analysis is not a value opinion unless engaged as one",
      "a market study that does not say which uses it covers",
      "pricing the as-vacant and as-improved analyses as one line when both are required",
      "architectural concepts or engineering for the candidate uses",
    ],
    notes: [
      "Conclusions are as of the stated effective date and rely on zoning and market conditions in effect then",
      "A full appraisal or value opinion is a separate engagement; the analysis supports one but is not one",
      "Site engineering, environmental studies and title work are excluded; recorded documents are relied on as furnished",
      "Litigation support is billed hourly with a retainer and is not included in the analysis fee",
    ],
  },
  "zoning-code-analysis": {
    basis: "fixed fee per zoning and code analysis by parcel and proposed use; agency meetings, interpretation requests and revisions by the hour",
    steps: [
      { item: "Kickoff: proposed use and program, site survey, existing plans and any prior approvals or open violations collected", unit: "hour" },
      { item: "Zoning verification: district map, ordinance text, overlay districts, pending amendments, and a zoning verification letter requested from the municipality", unit: "fixed" },
      { item: "Records pull: prior certificates of occupancy, variances, special permits, site plan approvals, open violations and recorded conditions on the parcel", unit: "fixed" },
      { item: "Zoning compliance matrix: permitted and conditional uses, lot area and width, setbacks, height, FAR, lot coverage, open space, parking and loading counts, landscaping and signage against the proposed program", unit: "fixed" },
      { item: "Setback and buildable envelope diagram drawn over the survey: required yards, height planes, easements and the proposed footprint", unit: "fixed" },
      { item: "Building code analysis: occupancy classification, construction type, allowable height and area, fire separation, egress, sprinklers and accessibility under the adopted IBC or IRC edition and local amendments", unit: "fixed" },
      { item: "Nonconformity and change-of-use review: legal nonconforming rights, expansion limits and the triggers a change of occupancy sets off", unit: "fixed", when: "the property is improved or the use is changing" },
      { item: "Approvals memo: every discretionary and ministerial approval the program needs, the deciding body, notice requirements and estimated timeline", unit: "fixed" },
      { item: "Variance and special-permit exposure: each standard not met, the findings the board must make and the strength of the case", unit: "fixed", when: "the program does not meet a standard" },
      { item: "Pre-application meeting with planning and building officials to confirm the interpretation", unit: "hour" },
      { item: "Written code interpretation or determination request to the zoning administrator or building official", unit: "fixed", when: "an ordinance provision is ambiguous for the proposed use" },
      { item: "Revisions to the matrix and memo for a revised program or footprint", unit: "hour" },
      { item: "Reimbursables: municipal document fees, zoning verification letter fee, records copies and mileage", unit: "fixed" },
    ],
    avoid: [
      "'Zoning review' as one line with no matrix, diagram or memo named",
      "'Code compliance' with no code edition or occupancy stated",
      "a variance application or hearing appearance — a separate engagement",
      "architectural or MEP design priced as part of the analysis",
      "'Permits' as a bare line",
    ],
    notes: [
      "The analysis relies on the ordinance and code editions in effect on the report date; pending amendments are flagged, not applied",
      "Interpretations remain the jurisdiction's; a written determination is requested where the text is unclear",
      "The zoning verification letter fee and any records fees are passed through at the municipality's rate",
      "Preparing a variance, special permit or rezoning application is a separate scope",
    ],
  },
  "far-density-study": {
    basis: "fixed fee per study by parcel and the number of massing scenarios modeled; agency confirmation meetings and revisions by the hour",
    steps: [
      { item: "Kickoff and program brief: target use mix, unit sizes, parking approach, survey and zoning designation collected", unit: "hour" },
      { item: "Zoning parameter research: base FAR and density, height and stepback rules, lot coverage, open space, parking ratios, and every bonus or transfer program the site qualifies for", unit: "fixed" },
      { item: "Lot area verification: gross lot area from the survey, street dedications, easements and any area the ordinance excludes from the FAR calculation", unit: "fixed" },
      { item: "FAR tabulation: allowable floor area, exempt areas (below-grade parking, mechanical, balconies), bonus floor area with its conditions, and net sellable or leasable area", unit: "fixed" },
      { item: "Density and unit-yield calculation: maximum units by the density cap, by FAR at the target unit mix and by parking, with the binding constraint identified", unit: "fixed" },
      { item: "Zoning envelope model in 3D: setbacks, height limits, sky-exposure planes, stepbacks and view corridors", unit: "fixed" },
      { item: "Massing scenario: building form, floor plates and floor count fit to the envelope, with FAR, unit count, parking and open space tabulated for that scenario", unit: "unit" },
      { item: "Bonus and incentive analysis: inclusionary housing, transfer of development rights, green-building or public-plaza bonuses and what each costs to earn", unit: "fixed", when: "a bonus or transfer program is available on the site" },
      { item: "Parking and loading fit test: required stalls against the podium or below-grade footprint, ramp geometry and loading berths", unit: "fixed" },
      { item: "Study report and exhibit set: zoning summary, tabulations, massing diagrams and the recommended scenario", unit: "fixed" },
      { item: "Presentation to the client, architect and investment partners", unit: "hour" },
      { item: "Confirmation meeting with the planning department on FAR interpretation and bonus eligibility", unit: "hour", when: "a bonus, exemption or interpretation drives the yield" },
      { item: "Revisions for a changed unit mix, height or parking approach", unit: "hour" },
      { item: "Reimbursables: survey and GIS data, 3D base model purchase and printing", unit: "fixed" },
    ],
    avoid: [
      "'FAR study' as one lump line with no tabulation or massing named",
      "a massing line that does not say how many scenarios it covers",
      "'Zoning' or 'Calculations' as bare lines",
      "schematic design or floor plans — the massing is a zoning envelope, not architecture",
      "pricing the envelope model and the massing scenarios as one line",
    ],
    notes: [
      "Floor area is calculated by the ordinance's definition; the jurisdiction's interpretation of exemptions governs and is confirmed where it drives the yield",
      "Massing is a capacity exercise, not a design; unit counts assume the stated mix and average sizes",
      "Bonus floor area is shown with its conditions; earning it is subject to the approval process",
      "The survey furnished by the client is relied on for lot area; a new survey is excluded",
    ],
  },
  "buildable-area-calc": {
    basis: "fixed fee per parcel exhibit and capacity calculation; field verification, agency confirmation and revisions by the hour",
    steps: [
      { item: "Kickoff: intended use, survey or plat, title commitment with easement documents, and any prior wetland, flood or soils reports collected", unit: "hour" },
      { item: "Base map assembly: boundary and topography from the survey, or GIS parcel lines, LiDAR contours and aerial imagery where no survey exists", unit: "fixed" },
      { item: "Regulatory setback mapping: front, side and rear yards, corner-lot and accessory rules, street-widening lines and required buffers to adjacent districts", unit: "fixed" },
      { item: "Easement and right-of-way plotting: recorded utility, access, drainage and conservation easements located from the title exceptions and drawn to their deeded widths", unit: "fixed" },
      { item: "Environmental constraint overlay: FEMA flood zone and floodway, NWI or delineated wetlands with buffers, stream and shoreline setbacks, slopes above the ordinance threshold and protected trees", unit: "fixed" },
      { item: "Site walk to verify constraints on the ground: flagged wetlands, drainage ways, slope breaks, encroachments and existing structures", unit: "hour" },
      { item: "Septic reserve and well setback allocation: primary and reserve drainfield area and separation distances taken out of the buildable area", unit: "fixed", when: "the parcel is not served by public sewer or water" },
      { item: "Stormwater and open-space set-aside: detention footprint, required open space or landscape percentage deducted", unit: "fixed" },
      { item: "Net buildable area exhibit: gross area, each deduction tabulated and the net envelope drawn with dimensions and acreage", unit: "fixed" },
      { item: "Development capacity calculation: maximum footprint, floor area, units or lots the envelope supports under the density and coverage rules", unit: "fixed" },
      { item: "Confirmation of setback and buffer interpretation with the zoning administrator", unit: "hour", when: "an ordinance provision is unclear for the parcel" },
      { item: "Revisions for a corrected survey, a new wetland delineation or a changed program", unit: "hour" },
      { item: "Reimbursables: GIS and LiDAR data, recorded easement copies and printing", unit: "fixed" },
    ],
    avoid: [
      "'Buildable area' as one line with no deductions itemized",
      "a boundary survey or wetland delineation priced as if the analyst performs it",
      "'Mapping' or 'Site analysis' as bare lines",
      "a capacity number with no envelope exhibit behind it",
    ],
    notes: [
      "Setbacks and buffers are applied from the ordinance in effect; wetland and floodplain lines come from published maps unless a delineation or elevation certificate is furnished",
      "Easements are plotted from the title commitment as furnished; unrecorded easements and encroachments are noted only where seen on the site walk",
      "GIS-based boundaries are approximate; a survey is recommended before design and is excluded here",
      "The capacity calculation is a planning number, not an approval",
    ],
  },
  "lot-split-analysis": {
    basis: "fixed fee per parent parcel by the number of lot configurations tested; agency meetings, neighbor outreach and revisions by the hour",
    steps: [
      { item: "Kickoff: parent parcel deed and plat, survey, target lot count and product, and the client's timing collected", unit: "hour" },
      { item: "Subdivision ordinance research: minimum lot area and width, frontage, minor versus major subdivision thresholds, flag-lot and private-road rules, dedication and improvement standards", unit: "fixed" },
      { item: "Title and plat review: existing lot lines, prior splits, easements, deed restrictions and any plat notes limiting further division", unit: "fixed" },
      { item: "Conceptual lot layout per configuration: lot lines, frontages, access points and any new road or shared drive drawn, each lot checked against the standards", unit: "unit" },
      { item: "Access and road review: driveway spacing and sight distance, private road or cul-de-sac standards, fire apparatus access and turnaround", unit: "fixed" },
      { item: "Utility extension review: sewer and water main proximity, extension length and route, septic and well feasibility per lot where mains are absent, stormwater requirement per lot", unit: "fixed" },
      { item: "Environmental and site screen: floodplain, wetlands, slopes and tree preservation as they land on each proposed lot", unit: "fixed" },
      { item: "Approval roadmap: minor plat or full preliminary-and-final plat process, deciding bodies, notice, plat recording and the estimated timeline", unit: "fixed" },
      { item: "Cost and fee summary: survey and plat preparation, engineering, road and utility improvements, park and impact fees and recording fees", unit: "fixed" },
      { item: "Pre-application meeting with planning and public works on the preferred configuration", unit: "hour" },
      { item: "Site walk with the surveyor to confirm access, drainage and existing improvements against the layout", unit: "hour" },
      { item: "Neighbor and homeowner-association outreach on the split", unit: "hour", when: "the parcel is in an HOA or the split needs neighbor consent" },
      { item: "Revisions to the layout and roadmap for a changed lot count or access plan", unit: "hour" },
      { item: "Reimbursables: recorded document copies, GIS data, application pre-screen fees and mileage", unit: "fixed" },
    ],
    avoid: [
      "'Lot split' as one lump line with no layout, roadmap or fee summary",
      "the plat itself, the boundary survey or the road and utility engineering priced as part of the analysis",
      "'Subdivision' or 'Approvals' as bare lines",
      "a layout line that does not say how many configurations it covers",
    ],
    notes: [
      "The layout is conceptual; the recorded plat and its survey are prepared by a licensed surveyor under a separate scope",
      "Improvement costs are opinions for planning; utility extension costs depend on the utility's requirements and are confirmed at design",
      "Approval timelines are estimates based on the jurisdiction's current calendar and can move with hearing schedules",
      "Application, park, impact and recording fees are passed through at the jurisdiction's published rates",
    ],
  },
  "entitlement-strategy": {
    basis: "fixed fee for the strategy and roadmap deliverables; advocacy, meetings and hearings by the hour; an ongoing strategy retainer per month",
    steps: [
      { item: "Strategy kickoff: project program, deal timing, prior contact with the jurisdiction and known opposition reviewed", unit: "hour" },
      { item: "Regulatory mapping: every entitlement the project needs (general plan amendment, rezoning, PUD, site plan, conditional use, plat, environmental clearance), the deciding body for each and how they sequence", unit: "fixed" },
      { item: "Stakeholder map: elected officials, planning staff, neighborhood groups, business associations, tribes and agencies with a say, each rated by influence and likely position", unit: "fixed" },
      { item: "Political and precedent analysis: recent comparable approvals and denials, council voting patterns, the election calendar and staff turnover that affect timing", unit: "fixed" },
      { item: "Entitlement roadmap and critical-path timeline: submittals, review cycles, hearings and appeal windows on a month-by-month schedule with decision points", unit: "fixed" },
      { item: "Consultant team plan: the studies the approval path requires (traffic, environmental, civil, legal) with scope and sequence for each", unit: "fixed" },
      { item: "Pre-application and staff meetings with the planning director, city manager and reviewing departments", unit: "hour" },
      { item: "Elected-official briefings: one-on-one meetings with council or commission members before the hearing cycle", unit: "hour" },
      { item: "Community outreach program: neighborhood meetings, community-benefits discussion, materials and follow-up", unit: "hour" },
      { item: "Application and submittal coordination: completeness review of the consultant team's packages before filing", unit: "hour" },
      { item: "Hearing preparation and testimony: staff-report response, presentation deck, witness preparation and appearance before the commission and council", unit: "hour" },
      { item: "Ongoing strategy retainer per month: weekly team calls, monitoring of agendas and ordinance changes, and issue response", unit: "unit" },
      { item: "Reimbursables: application and notice fees passed through, meeting venues, printing and travel", unit: "fixed" },
    ],
    avoid: [
      "'Entitlements' or 'Approvals' as one lump line",
      "'Consulting' or 'Coordination' with no meeting, deliverable or retainer named",
      "the technical studies themselves (traffic, environmental, civil) priced as part of the strategy",
      "legal representation — counsel is a separate engagement",
      "a success fee disguised as a line item",
    ],
    notes: [
      "The consultant advises and advocates; approvals are decided by the jurisdiction and are not guaranteed",
      "Technical studies, legal counsel and application fees are separate scopes passed through or contracted directly by the client",
      "The retainer covers the stated monthly cadence; hearings and continuances beyond it are billed hourly",
      "Timeline estimates reflect the jurisdiction's current calendar and staffing",
    ],
  },
  "rezoning-variance": {
    basis: "fixed fee per application package and hearing cycle; neighborhood meetings, hearings and continuances by the hour; fees and notices passed through",
    steps: [
      { item: "Kickoff and case assessment: the relief sought, the ordinance criteria the board must find, site facts, prior denials and a candid read of the odds", unit: "hour" },
      { item: "Site and neighborhood documentation: photographs, existing conditions, adjacent zoning and uses, and the physical conditions that support the request", unit: "hour" },
      { item: "Application package: forms, ownership affidavit, legal description, site plan and elevation coordination, assembled and filed with the jurisdiction", unit: "fixed" },
      { item: "Justification statement: point-by-point response to the variance hardship criteria or the rezoning consistency-and-compatibility findings, with supporting exhibits", unit: "fixed" },
      { item: "Hearing exhibits: zoning map excerpt, aerial with context, setback diagram and rendering board sized for the hearing room", unit: "fixed" },
      { item: "Public notice: mailed notice to owners within the required radius, newspaper publication and sign posting, with the fees passed through", unit: "fixed" },
      { item: "Neighborhood meeting: notice, venue, presentation, sign-in sheet and the meeting summary the ordinance requires filed with the application", unit: "hour", when: "the jurisdiction requires a neighborhood meeting or the case has organized opposition" },
      { item: "Staff coordination: completeness responses, staff-report review and negotiated conditions of approval", unit: "hour" },
      { item: "Board of zoning appeals or planning commission hearing: presentation, testimony and rebuttal", unit: "hour" },
      { item: "City council or county commission hearing on the rezoning ordinance, first and second reading", unit: "hour", when: "the request is a rezoning or map amendment" },
      { item: "Continuances, resubmittals and response to an appeal", unit: "hour", when: "the case is continued, tabled or appealed" },
      { item: "Recording of the approved ordinance, variance order or development agreement, and delivery of the closed file to the client", unit: "fixed" },
      { item: "Reimbursables: application fees, notice and publication costs, sign fabrication, printing and mileage", unit: "fixed" },
    ],
    avoid: [
      "'Variance' or 'Rezoning' as one lump line with no package, notice or hearing itemized",
      "'Hearing' with no body named and no preparation behind it",
      "the site plan, survey or architectural drawings priced as part of the support scope",
      "legal representation at the hearing — counsel is a separate engagement",
      "a fee that promises approval",
    ],
    notes: [
      "Approval rests with the board or council; the consultant prepares and presents the case and does not guarantee the outcome",
      "Application, notice, publication and recording fees are passed through at the jurisdiction's published rates",
      "Site plans, surveys and drawings required by the application are furnished by the client's design team",
      "Hearing hours assume one appearance per body; continuances are billed as they occur",
    ],
  },
  "traffic-impact-study": {
    basis: "fixed fee by the number of study intersections and analysis scenarios; counts per intersection or station; agency meetings, responses and hearings by the hour",
    steps: [
      { item: "Scoping meeting with the reviewing agency: study intersections, horizon years, background growth rate, peak periods and methodology agreed and confirmed in a scoping letter", unit: "hour" },
      { item: "Data collection: crash records, signal timing plans, approved-but-unbuilt developments, programmed roadway projects and prior counts obtained from the agency", unit: "fixed" },
      { item: "Peak-hour turning-movement count at each study intersection, weekday AM and PM peaks, with pedestrian and bicycle volumes and heavy-vehicle classification", unit: "unit" },
      { item: "24-hour or 48-hour tube count per station on the adjacent roadway segments for daily volume and speed", unit: "unit" },
      { item: "Trip generation for the proposed development by land use per the current ITE Trip Generation Manual, with pass-by and internal-capture reductions", unit: "fixed" },
      { item: "Trip distribution and assignment: directional distribution from the travel-demand model or existing patterns, new trips assigned to the network and the site driveways", unit: "fixed" },
      { item: "Capacity analysis per intersection and scenario (existing, background and build for each horizon year) in Synchro or HCS: delay, level of service, volume-to-capacity and 95th-percentile queues", unit: "unit" },
      { item: "Site access and circulation review: driveway locations against spacing standards, sight distance, turn-lane warrants and internal queuing at the entrance", unit: "fixed" },
      { item: "Signal warrant analysis per the MUTCD for an unsignalized study intersection or a proposed site signal", unit: "unit", when: "an unsignalized intersection fails or the site proposes a signal" },
      { item: "Mitigation analysis: turn lanes, signal retiming, roundabout or new signal tested at each deficient location with a proportionate-share cost", unit: "fixed" },
      { item: "Traffic impact study report: methodology, counts, analysis worksheets, figures and mitigation, sealed by the traffic engineer", unit: "fixed" },
      { item: "Agency review response and resubmittal after staff comments", unit: "hour" },
      { item: "Presentation of the study at the planning commission or council hearing", unit: "hour" },
      { item: "Reimbursables: video count subcontractor, signal timing data purchase, mileage and printing", unit: "fixed" },
    ],
    avoid: [
      "'Traffic study' as one lump line with no intersections, scenarios or counts itemized",
      "'Analysis' with no scenario or software named",
      "counts priced as fixed when the number of intersections is known",
      "roadway design, signal design or construction plans for the mitigation — a separate engineering scope",
      "a mitigation line with no location behind it",
    ],
    notes: [
      "The study area and scenarios follow the agency's scoping letter; intersections added by the agency after scoping are billed at the per-intersection rate",
      "Counts are taken on a typical weekday outside holidays and school breaks; weather delays move the count date, not the fee",
      "Trip generation uses the current ITE edition and agency-approved reductions; mitigation costs are planning-level",
      "Design of the recommended improvements is excluded",
    ],
  },
  "environmental-impact": {
    basis: "fixed fee per document phase by review level (IS/MND, EIR, EA or EIS) and the technical studies it requires; hearings, comment responses and monitoring by the hour",
    steps: [
      { item: "Kickoff with the lead agency and applicant: review level determined, project description confirmed, schedule set and the technical studies scoped", unit: "hour" },
      { item: "Project description and environmental setting: baseline conditions, site plans, construction assumptions and the regulatory setting written to the agency's format", unit: "fixed" },
      { item: "Initial study or environmental checklist under CEQA Appendix G or the NEPA scoping criteria, with a significance conclusion for each resource topic", unit: "fixed" },
      { item: "Technical study per resource: biological survey, cultural and tribal records search, air quality and greenhouse-gas modeling, noise measurement and modeling, hazards database review", unit: "unit" },
      { item: "Notice of preparation or notice of intent, scoping meeting and the scoping summary", unit: "fixed", when: "the review level is an EIR or an EIS" },
      { item: "Impact analysis and alternatives: each resource chapter with thresholds, impacts, mitigation and a reasonable range of alternatives compared", unit: "fixed" },
      { item: "Mitigation monitoring and reporting program: each measure with timing, responsible party and verification method", unit: "fixed" },
      { item: "Administrative draft to the lead agency and one round of agency screencheck edits", unit: "fixed" },
      { item: "Public draft document, notice of availability or completion, State Clearinghouse or Federal Register filing and management of the public review period", unit: "fixed" },
      { item: "Response to comments and the final document with errata", unit: "fixed" },
      { item: "Findings, statement of overriding considerations and the notice of determination or decision record", unit: "fixed" },
      { item: "Tribal consultation support under AB 52 or Section 106", unit: "hour", when: "a tribe requests consultation" },
      { item: "Public hearings and community meetings on the document", unit: "hour" },
      { item: "Mitigation monitoring during construction: site checks and compliance reports to the agency", unit: "hour", when: "the client retains the consultant for construction-phase monitoring" },
      { item: "Reimbursables: filing and fish-and-wildlife fees passed through, records-search fees, printing of hearing copies and travel", unit: "fixed" },
    ],
    avoid: [
      "'Environmental review' or 'CEQA' as one lump line",
      "'Studies' with no resource topic named",
      "a Phase I ESA or wetland delineation confused with the impact document",
      "engineering of the mitigation measures",
      "'Public process' as a bare line",
    ],
    notes: [
      "The review level is the lead agency's determination; a change from IS/MND to EIR after the initial study is a change in scope",
      "Technical studies are listed as scoped at kickoff; a study the agency adds later is billed per study",
      "Filing fees, fish-and-wildlife fees and notice costs are passed through at the published rate",
      "The schedule depends on agency review time and statutory comment periods",
    ],
  },
  "preconstruction-consulting": {
    basis: "fixed fee per design-milestone deliverable or a monthly preconstruction fee; workshops, coordination and meetings by the hour",
    steps: [
      { item: "Preconstruction kickoff with the owner and design team: budget, milestone dates, delivery method, and the review and estimate calendar set", unit: "hour" },
      { item: "Design-milestone review at schematic, design development and construction documents: coordination, constructability and scope-gap comments logged and tracked to closure", unit: "unit" },
      { item: "Milestone cost estimate at each design stage: quantity takeoff by CSI division, unit pricing, general conditions, contingency and escalation, reconciled to the previous estimate", unit: "unit" },
      { item: "Value-engineering workshop: alternatives proposed by system with cost, schedule and quality effect, accepted items tracked into the documents", unit: "fixed" },
      { item: "Master schedule: design, permitting, procurement and construction sequence with the critical path and long-lead items", unit: "fixed" },
      { item: "Site logistics plan: laydown, cranes and hoisting, access, fencing, phasing of occupied areas, traffic and neighbor protection", unit: "fixed" },
      { item: "Procurement strategy and long-lead log: early-release packages, equipment lead times and buyout dates against the schedule", unit: "fixed" },
      { item: "Bid packaging and subcontractor prequalification: scope packages defined, qualification questionnaires reviewed and the bid list set", unit: "fixed" },
      { item: "Bid solicitation, leveling and award recommendation per bid package: scope review with each bidder and a leveled tabulation", unit: "unit" },
      { item: "Guaranteed maximum price or final budget assembly: buyout results, allowances, clarifications and the assumptions log", unit: "fixed", when: "the delivery method carries a GMP" },
      { item: "Permit and utility coordination: submittal timing, utility service applications and an impact-fee estimate", unit: "hour" },
      { item: "Preconstruction meetings and design coordination sessions with the team", unit: "hour" },
      { item: "Reimbursables: estimating database subscription, printing, and travel to the site and design offices", unit: "fixed" },
    ],
    avoid: [
      "'Preconstruction services' as one lump line with no milestone, estimate or deliverable named",
      "'Estimating' or 'Scheduling' as bare lines",
      "construction-phase supervision or general conditions — a construction contract, not precon",
      "design fees or the drawings themselves",
    ],
    notes: [
      "Estimates carry the accuracy of the design stage they price and are reconciled at each milestone",
      "The number of milestone reviews and estimates follows the design schedule furnished at kickoff",
      "Bid results depend on market conditions on the bid date; the GMP is assembled from actual buyout",
      "Permit and impact fees are estimated for the budget and paid by the owner",
    ],
  },
  "conceptual-cost-estimating": {
    basis: "fixed fee per estimate by project size and design stage (AACE Class 5 or 4); reconciliation, updates and presentations by the hour",
    steps: [
      { item: "Kickoff and document intake: program, concept drawings, site data, target budget and the required accuracy class confirmed", unit: "hour" },
      { item: "Basis of estimate: design stage, documents relied on, assumptions, exclusions, pricing date and the accuracy range stated per AACE classification", unit: "fixed" },
      { item: "Parametric quantity development: gross floor area, footprint, exterior wall area, floor count, site acreage and system quantities inferred from the concept", unit: "fixed" },
      { item: "Elemental estimate in UniFormat: substructure, shell, interiors, services, equipment and site work, each priced from historical cost data and current unit rates", unit: "fixed" },
      { item: "Benchmarking against comparable completed projects: cost per square foot by system, adjusted for location index, size and time", unit: "fixed" },
      { item: "Soft-cost and owner-cost allowances: design fees, permits, testing, FF&E and owner contingency", unit: "fixed", when: "the client wants total project cost rather than construction cost only" },
      { item: "Location and escalation adjustment: regional cost index and escalation to the projected construction midpoint at a stated annual rate", unit: "fixed" },
      { item: "Design and estimating contingency recommendation tied to the accuracy class, presented as a range rather than a point figure", unit: "fixed" },
      { item: "Cost model per scenario: alternate program size, construction type or site, each estimated on the same basis for comparison", unit: "unit" },
      { item: "Estimate report: summary, elemental detail, benchmarks, assumptions and exclusions, and the risk items that move the number", unit: "fixed" },
      { item: "Reconciliation meeting with the contractor's or a second estimator's number, variances explained line by line", unit: "hour", when: "another estimate exists for the project" },
      { item: "Presentation to the owner and design team, and an update of the estimate for a revised concept", unit: "hour" },
      { item: "Reimbursables: cost database subscription, printing and travel", unit: "fixed" },
    ],
    avoid: [
      "'Cost estimate' as one line with no basis, class or format named",
      "a quantity takeoff by CSI division from concept sketches — that is a later-stage estimate",
      "'Contingency' as a bare line without the accuracy class it reflects",
      "a single point figure with no range",
    ],
    notes: [
      "The estimate reflects the design information available on the pricing date and carries the accuracy range of its AACE class",
      "Costs are in current dollars escalated to the stated midpoint; market conditions after the pricing date are not predicted",
      "Soft costs and owner costs are included only where the client asks for total project cost",
      "The estimate is an opinion of probable cost, not a bid or a guarantee",
    ],
  },
  "rom-estimating": {
    basis: "fixed fee per ROM estimate by project type and the number of options priced; scope interviews, site visits and updates by the hour",
    steps: [
      { item: "Scope interview with the client: what is being built, where, how big, when, and what decision the number supports", unit: "hour" },
      { item: "Assumptions and exclusions register: every parameter assumed in place of missing information, written down before pricing", unit: "fixed" },
      { item: "Walk-through of the existing facility to size the work and spot the conditions that swing the number", unit: "hour", when: "the ROM is for a renovation or an existing facility" },
      { item: "Capacity-factor or unit-rate estimate: cost per square foot, per unit, per bed, per lane-mile or per installed horsepower from published indexes and project history, scaled to the stated size", unit: "fixed" },
      { item: "Major-system allowances: site, structure, envelope, MEP and finishes as percentages of the base, adjusted for the project's known features", unit: "fixed" },
      { item: "Location, time and market adjustment: regional index, escalation to the expected construction date and the current bid-climate factor", unit: "fixed" },
      { item: "Contingency and accuracy range: AACE Class 5 range (as wide as -50 to +100 percent) applied and stated with the number", unit: "fixed" },
      { item: "Option pricing per alternate: each alternate size, site or program priced on the same basis", unit: "unit" },
      { item: "ROM memo: one-page summary with the number, the range, what is in and out, and what would tighten the estimate", unit: "fixed" },
      { item: "Review call with the client and one update for a changed size or scope", unit: "hour" },
      { item: "Reimbursables: cost index subscriptions and printing", unit: "fixed" },
    ],
    avoid: [
      "a detailed takeoff or trade-by-trade pricing — a ROM is top-down by design",
      "'Estimate' with no basis or range stated",
      "a number with no assumptions register behind it",
      "presenting the ROM as a budget the project can be held to",
    ],
    notes: [
      "The ROM is a screening number from parametric rates and stated assumptions; its range is as wide as the AACE Class 5 band and it is not a budget",
      "No drawings are required; where the client has them, only the size and system information is used",
      "One update is included; further options or a tighter class of estimate are a new engagement",
      "Escalation and market factors are stated in the memo and are not guaranteed",
    ],
  },
  "cost-engineering": {
    basis: "fixed fee for the setup deliverables and detailed estimate; cost control, change review and reporting per month for the construction duration; evaluations by the hour",
    steps: [
      { item: "Kickoff and cost management plan: reporting calendar, approval thresholds, code of accounts and the tools agreed with the owner", unit: "hour" },
      { item: "Work breakdown and cost breakdown structure: control accounts mapped to the drawings, the contract and the owner's accounting codes", unit: "fixed" },
      { item: "Detailed estimate at design completion: quantity takeoff by CSI division, crew and productivity rates, material quotes, equipment, general conditions, markups and escalation", unit: "fixed" },
      { item: "Control budget and cash-flow forecast: baseline budget by account loaded to the schedule for a monthly draw curve", unit: "fixed" },
      { item: "Value analysis: alternatives on the high-cost systems with life-cycle cost comparison and a decision log", unit: "fixed", when: "the estimate exceeds the owner's budget" },
      { item: "Bid and proposal evaluation: contractor pricing checked against the independent estimate, unbalanced bids and allowance exposure flagged", unit: "hour" },
      { item: "Monthly cost report per month: commitments, incurred cost, forecast at completion, variance to budget and contingency drawdown", unit: "unit" },
      { item: "Earned-value and productivity tracking per month: planned versus earned versus actual by account with performance indices", unit: "unit", when: "the owner or funding agency requires earned-value reporting" },
      { item: "Change order review per change: independent pricing, entitlement check and negotiation support", unit: "unit" },
      { item: "Pay application review per month: quantities in place verified, stored materials, retainage and lien releases checked before certification", unit: "unit" },
      { item: "Trend and forecast log: potential changes and risks priced before they become change orders", unit: "hour" },
      { item: "Cost close-out: final cost report, reconciliation of allowances and contingency, and the as-built cost data for the owner's benchmarks", unit: "fixed" },
      { item: "Reimbursables: estimating and cost-control software, printing and travel", unit: "fixed" },
    ],
    avoid: [
      "'Cost control' as one lump line with no report, review or cadence named",
      "'Estimating' with no design stage or format stated",
      "the contractor's own general conditions or overhead priced as consulting",
      "a change order line that does not say it is priced per change",
    ],
    notes: [
      "Monthly services run for the construction duration stated in the schedule; an extended duration extends the monthly fee",
      "The detailed estimate is priced from the completed design; a design still moving is estimated at its stage and updated",
      "Change order review is independent of the contractor's pricing and does not replace the owner's authority to approve",
      "Pay application review verifies quantities and backup; it is not a certification of the work's quality",
    ],
  },
  "constructability-review": {
    basis: "fixed fee per review milestone by drawing-set size and discipline count; workshops, comment resolution and back-checks by the hour",
    steps: [
      { item: "Review kickoff: drawing set, specifications, geotechnical report and schedule received; disciplines, review depth and the owner's known concerns set", unit: "hour" },
      { item: "Page-turn review per discipline: architectural, structural, civil, mechanical, electrical and plumbing sheets read against each other for conflicts, omissions and unbuildable details", unit: "unit" },
      { item: "Interdisciplinary coordination check: structure against ductwork and piping clearances, ceiling heights, foundations against utilities, penetrations and embeds", unit: "fixed" },
      { item: "Means, methods and sequencing review: crane access, formwork and shoring approach, erection sequence, temporary conditions and weather sensitivity", unit: "fixed" },
      { item: "Site logistics and access review: staging, haul routes, existing utilities, adjacent occupancy and the constraints the drawings do not show", unit: "fixed" },
      { item: "Specification and bid-document review: scope gaps between drawings and specs, unrealistic tolerances, proprietary items and unclear responsibility", unit: "fixed" },
      { item: "Schedule and phasing check: activities driven by the design, long-lead equipment and details that add duration or cost", unit: "fixed" },
      { item: "Site visit to check the documents against existing conditions", unit: "hour", when: "the project is a renovation, an addition or a tight urban site" },
      { item: "Comment log: each finding with sheet reference, category, cost or schedule effect, recommendation and priority", unit: "fixed" },
      { item: "Constructability workshop with the design team and owner to walk the log and agree resolutions", unit: "hour" },
      { item: "Constructability report: findings summary, high-value recommendations and the risk items left open", unit: "fixed" },
      { item: "Back-check of the revised documents and closure of the comment log", unit: "hour" },
      { item: "Reimbursables: model and drawing viewing software, printing and travel", unit: "fixed" },
    ],
    avoid: [
      "'Constructability review' as one lump line with no discipline, log or report named",
      "'Design review' with no criteria stated",
      "redesign or corrected drawings — the designer of record makes the changes",
      "a comment log with no cost or schedule effect assigned",
    ],
    notes: [
      "The review is advisory; the design professional of record remains responsible for the documents and their corrections",
      "Review depth matches the design stage of the set furnished; a set reissued after the review is a new milestone",
      "The site visit is included only where noted; existing conditions are otherwise taken from the documents",
      "Cost and schedule effects in the log are order-of-magnitude for prioritizing, not estimates",
    ],
  },
  "construction-phasing": {
    basis: "fixed fee per phasing plan by the number of phases and occupied areas; stakeholder workshops and updates by the hour",
    steps: [
      { item: "Kickoff and operations interview: occupancy schedule, areas that must stay open, blackout dates, noise and dust sensitivity, and the owner's move capacity", unit: "hour" },
      { item: "Existing-conditions review: floor plans, utility risers and shutoff points, egress paths, loading docks, elevators and parking documented for phasing", unit: "fixed" },
      { item: "Phase definition: work areas grouped by system, occupancy and access into phases, with duration and the trigger to start each", unit: "fixed" },
      { item: "Phase plan per phase: colored plan showing the work zone, temporary partitions, egress, dust and noise barriers, and the occupied areas protected", unit: "unit" },
      { item: "Swing space and relocation plan: temporary accommodation, move sequence and furniture or equipment handling for displaced occupants", unit: "fixed", when: "occupants are relocated during construction" },
      { item: "Utility shutdown and tie-in schedule: each electrical, mechanical, plumbing and data outage with duration, timing window and temporary service", unit: "fixed" },
      { item: "Infection control and interim life-safety measures: ICRA class, negative-air containment, ILSM and fire-watch requirements by phase", unit: "fixed", when: "the building is a hospital, laboratory, school or other regulated occupancy" },
      { item: "Logistics plan by phase: site access, deliveries, hoisting, laydown, parking displacement and construction traffic routes", unit: "fixed" },
      { item: "Schedule analysis: the phased sequence against a single-phase baseline, with the added duration and critical-path effects", unit: "fixed" },
      { item: "Cost premium analysis: temporary partitions, off-hours work, remobilizations, temporary utilities and general conditions added by phasing", unit: "fixed" },
      { item: "Stakeholder workshops with facilities, department heads and the design team to test each phase", unit: "hour" },
      { item: "Phasing narrative and specification language for the bid documents", unit: "fixed" },
      { item: "Updates to the phase plans for a changed occupancy or schedule", unit: "hour" },
      { item: "Reimbursables: plan printing at workshop size and travel", unit: "fixed" },
    ],
    avoid: [
      "'Phasing' as one lump line with no phase count, plan or schedule named",
      "the temporary partitions, barriers and moves themselves priced as consulting",
      "'Logistics' or 'Coordination' as bare lines",
      "a phase plan line that does not say how many phases it covers",
    ],
    notes: [
      "Phase count and areas follow the operations interview; phases added after the plan is issued are billed per phase",
      "Cost premiums are planning-level and are confirmed in the contractor's pricing",
      "Infection-control and life-safety measures are drafted for the owner's safety officer to approve",
      "Construction of the temporary measures and the moves are excluded",
    ],
  },
  "cpm-analysis": {
    basis: "fixed fee for the baseline schedule and each analysis deliverable; updates per month; reviews per submission; delay analysis, testimony and meetings by the hour",
    steps: [
      { item: "Kickoff and document review: contract schedule specification, milestones, scope, drawings, and the software and format the owner requires", unit: "hour" },
      { item: "Work breakdown structure and activity list: activities coded by phase, area, trade and responsibility to the contract's level of detail", unit: "fixed" },
      { item: "Baseline CPM schedule in Primavera P6 or Microsoft Project: logic ties, durations, calendars, constraints and resource or cost loading, with the critical and near-critical paths identified", unit: "fixed" },
      { item: "Baseline narrative: critical-path description, key assumptions, weather days, float ownership and the DCMA 14-point schedule health check results", unit: "fixed" },
      { item: "Schedule review per submission of a contractor baseline or update: logic, open ends, lags, constraints, float suppression and missing scope, with a comment memo", unit: "unit" },
      { item: "Schedule update per month: progress data collected, actuals and remaining durations entered, critical path re-evaluated and a variance report issued", unit: "unit" },
      { item: "Three-week look-ahead per month pulled from the update for the field", unit: "unit", when: "the contractor wants look-aheads produced by the scheduler" },
      { item: "Time impact analysis per change: fragnet inserted into the current update to show the change's effect on completion", unit: "unit" },
      { item: "Recovery or re-sequencing schedule with the acceleration options laid out for pricing", unit: "fixed", when: "an update shows the completion date slipping" },
      { item: "Forensic delay analysis: as-planned versus as-built or windows analysis, concurrent-delay evaluation and the delay apportionment report", unit: "fixed", when: "a delay claim or dispute exists" },
      { item: "Expert report and testimony in mediation, arbitration or litigation", unit: "hour", when: "the delay analysis goes to a formal dispute" },
      { item: "Schedule meetings with the owner, contractor and design team", unit: "hour" },
      { item: "Reimbursables: scheduling software license, plotting of schedule sheets and travel", unit: "fixed" },
    ],
    avoid: [
      "'Scheduling' as one lump line with no baseline, update or analysis named",
      "'Schedule updates' with no cadence stated",
      "a delay analysis line with no method named",
      "the contractor's own scheduling obligation billed as consulting",
    ],
    notes: [
      "The baseline is built from the contract documents and the contractor's plan; the scheduler does not set means and methods",
      "Monthly updates run for the stated duration; time impact analyses are billed per fragnet",
      "Forensic analysis and testimony are billed hourly with a retainer and follow the contract's chosen method",
      "Software licensing is passed through where the owner requires a specific platform",
    ],
  },
  "risk-contingency": {
    basis: "fixed fee per risk assessment by project size and analysis depth (qualitative or Monte Carlo); workshops, periodic reviews and presentations by the hour",
    steps: [
      { item: "Kickoff and document review: estimate, schedule, contracts, design status and prior risk registers received; the analysis method and confidence level agreed", unit: "hour" },
      { item: "Risk identification workshop with the owner, designer and contractor: threats and opportunities across scope, site, permits, market, design and execution", unit: "hour" },
      { item: "Risk register: each risk with cause, event, effect, owner, probability and cost and schedule impact ranges", unit: "fixed" },
      { item: "Qualitative scoring and heat map: probability-impact ranking to shortlist the risks that get quantified and mitigated", unit: "fixed" },
      { item: "Quantitative cost risk analysis: Monte Carlo simulation of the estimate with line-item uncertainty and discrete risk events, producing the cost distribution and P50 through P90 values", unit: "fixed" },
      { item: "Schedule risk analysis: duration uncertainty and risk events simulated on the CPM schedule for completion-date confidence", unit: "fixed", when: "the completion date is at risk or the funding agency requires it" },
      { item: "Contingency recommendation: contingency and management reserve at the chosen confidence level, allocated by phase or account, with drawdown rules", unit: "fixed" },
      { item: "Mitigation and response plan: actions, owners, cost of mitigation and the residual risk after each", unit: "fixed" },
      { item: "Risk management plan: register maintenance, review cadence, escalation and reporting agreed with the owner", unit: "fixed" },
      { item: "Risk report: method, register, distributions, contingency recommendation and the top risks with their mitigations", unit: "fixed" },
      { item: "Periodic register reviews and re-simulation as design and procurement progress", unit: "hour" },
      { item: "Presentation of the analysis to the board, lender or funding agency", unit: "hour" },
      { item: "Reimbursables: simulation software license, workshop facilities and travel", unit: "fixed" },
    ],
    avoid: [
      "'Risk analysis' as one lump line with no register, method or confidence level named",
      "'Contingency' as a bare line or a flat percentage with no analysis behind it",
      "insurance, bonding or a risk transfer product priced as consulting",
      "a Monte Carlo line with no estimate or schedule input identified",
    ],
    notes: [
      "The analysis uses the estimate and schedule furnished; their accuracy class bounds the result",
      "Contingency is recommended at the confidence level the owner selects; the owner sets the final amount",
      "Workshop attendance by the owner's team, designer and contractor is assumed; a second workshop is billed hourly",
      "Simulation software is licensed per project where the owner requires a specific tool",
    ],
  },
  "owners-representative": {
    basis: "monthly fee by project phase and required site presence; setup deliverables fixed; procurements, reviews and meetings by the hour or per item",
    steps: [
      { item: "Engagement kickoff: the owner's goals, budget, schedule, decision authority and the reporting they want, set in a project charter", unit: "hour" },
      { item: "Project management plan: roles, communication protocol, approval thresholds, document control, and the master project schedule and budget", unit: "fixed" },
      { item: "Consultant and contractor selection per procurement: RFQ or RFP drafting, interviews, scoring and a recommendation for the architect, engineers and builder", unit: "unit" },
      { item: "Contract review and negotiation support with counsel: scope, fee, insurance, schedule and change terms in the design and construction agreements", unit: "hour" },
      { item: "Design-phase review per milestone: program compliance, budget conformance, scope gaps and the owner decisions logged", unit: "unit" },
      { item: "Budget and schedule monitoring per month: master budget updated with commitments and forecasts, schedule variance tracked and reported", unit: "unit" },
      { item: "Bid or GMP evaluation: leveled comparison, exclusions and allowances reviewed and an award recommendation", unit: "fixed" },
      { item: "Construction-phase representation per month: weekly owner-architect-contractor meeting attendance and issue follow-up on the owner's behalf", unit: "unit" },
      { item: "Site walks: progress and quality observation against the documents, issues photographed and tracked to closure", unit: "hour" },
      { item: "Pay application and change order review per month: quantities, backup and entitlement checked, with a recommendation to the owner", unit: "unit" },
      { item: "Monthly owner's report per month: budget, schedule, risks, decisions needed and progress photographs", unit: "unit" },
      { item: "Closeout: punch list oversight, commissioning witnessed, O&M manuals, warranties and as-builts received, final accounting reconciled", unit: "fixed" },
      { item: "Move-in and occupancy coordination: FF&E, vendors, certificate of occupancy and the handoff to the owner's operations", unit: "hour", when: "the owner wants move-in managed by the representative" },
      { item: "Reimbursables: travel, printing and project document-management software", unit: "fixed" },
    ],
    avoid: [
      "'Owner's representation' as one lump line with no phase, cadence or deliverable named",
      "'Project management' or 'Oversight' as bare lines",
      "design, engineering or construction work — the representative manages it, others perform it",
      "a monthly line that does not say which months or phase it covers",
    ],
    notes: [
      "The monthly fee assumes the project duration and site presence stated; an extended schedule extends the fee",
      "The representative advises and recommends; the owner retains decision authority and signs contracts and pay applications",
      "Design and construction contracts are between the owner and those parties; the representative carries no design or construction liability",
      "Software and travel are passed through at cost",
    ],
  },
  "construction-manager": {
    basis: "preconstruction fee fixed; staff and general conditions per month; CM fee on the cost of work stated as a fixed sum; procurements per package",
    steps: [
      { item: "Preconstruction services: estimates at each design milestone, schedule, constructability and value engineering, bid packaging and buyout plan", unit: "fixed" },
      { item: "Project staffing per month: project manager, superintendent, project engineer and administrative support assigned to the job", unit: "unit" },
      { item: "Site general conditions per month: field office, temporary utilities, sanitation, dumpsters, fencing, signage and safety supplies", unit: "unit" },
      { item: "Site-specific safety plan: hazard analysis, orientation, toolbox talks, inspections and incident reporting per OSHA 29 CFR 1926", unit: "fixed" },
      { item: "Subcontractor procurement per bid package: prequalification, bid solicitation, leveling, award and subcontract execution", unit: "unit" },
      { item: "Quality control program: submittal and shop drawing review, mock-ups, inspection and testing coordination and the deficiency log", unit: "fixed" },
      { item: "Construction schedule per month: baseline CPM, monthly update, three-week look-aheads and recovery planning", unit: "unit" },
      { item: "Cost control and reporting per month: buyout log, commitments, change management, forecast at completion and contingency tracking", unit: "unit" },
      { item: "Coordination and meetings per month: weekly OAC meeting, subcontractor coordination meeting, and the RFI and submittal logs maintained", unit: "unit" },
      { item: "Permit and inspection management: building, trade and special inspections scheduled and passed", unit: "fixed" },
      { item: "Pay application assembly per month: schedule of values, subcontractor billings, lien waivers and stored-material backup", unit: "unit" },
      { item: "Construction manager fee on the cost of work, covering home-office overhead and profit", unit: "fixed" },
      { item: "Insurance and bonds: general liability, builder's risk and performance and payment bond premiums", unit: "fixed", when: "the CM holds the trade contracts (CM-at-Risk)" },
      { item: "Off-hours supervision for night or weekend work the owner's operations require", unit: "hour", when: "the owner's operations require night or weekend work" },
      { item: "Closeout: punch list, commissioning, O&M manuals, as-builts, warranties, final lien releases and the certificate of occupancy", unit: "fixed" },
      { item: "Warranty administration for the contract warranty period: warranty calls logged and coordinated with subcontractors", unit: "fixed" },
    ],
    avoid: [
      "'Construction management' as one lump line with no staff, general conditions or fee shown",
      "'General conditions' or 'Overhead' as bare lines with nothing itemized",
      "the trade work itself priced as CM services — trade contracts are the cost of work",
      "a CM fee hidden inside the monthly staff line",
      "'Contingency' as a line without saying whose it is and how it is drawn",
    ],
    notes: [
      "Staff and general conditions run for the construction duration in the schedule; an extended duration extends them monthly",
      "Under CM-Agency the owner holds the trade contracts and the cost of work is not in this proposal; under CM-at-Risk the GMP is set after buyout",
      "The CM fee is stated on the estimated cost of work and adjusts with approved changes",
      "Owner contingency and allowances are the owner's; the CM contingency, where the contract provides one, is drawn only with notice",
    ],
  },
};
