// Smart Proposal procedures — Engineering & design (architects, engineers, surveyors). See ./types.ts.
//
// Professional services: the "procedure" is the deliverables and phases the
// firm actually bills — kickoff and site visits by the hour, design phases and
// reports as fixed fees per deliverable, sheets / borings / monuments / Table A
// items each, agency responses and construction-phase services by the hour.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  "landscape-architect-pro": {
    basis: "phases billed as fixed fees per deliverable, with site analysis, meetings, agency reviews and construction observation by the hour; sheets counted per set",
    steps: [
      { item: "Kickoff meeting and site walk with the owner: program, budget, style references, existing trees and grades, sun and drainage observed and photographed", unit: "hour" },
      { item: "Base map assembly: boundary and topographic survey, utility locations, tree survey and soils report compiled into a CAD base; survey ordered where none exists", unit: "fixed" },
      { item: "Site analysis and inventory: sun and shade, slopes and drainage patterns, views, soils, existing vegetation to keep or remove, zoning setbacks, tree-protection and landscape ordinances", unit: "fixed" },
      { item: "Conceptual design: two or three plan alternatives with precedent imagery and a rough order-of-magnitude budget, presented for owner selection", unit: "fixed" },
      { item: "Schematic design: the selected concept developed into a site plan showing hardscape, planting zones, grading intent, water features and lighting; character sketches or 3D views", unit: "fixed" },
      { item: "Design development: dimensioned layout plan, preliminary grading and drainage plan, planting plan with species and sizes, materials board and outline specifications", unit: "fixed" },
      { item: "Construction documents: layout and materials plan, grading and drainage plan, planting plan and schedule, irrigation plan, landscape lighting plan, details of walls, steps, paving and edges, specifications", unit: "fixed" },
      { item: "Construction document sheets beyond the base set (sections, enlarged plans, additional details)", unit: "unit", when: "the project needs more sheets than the base set" },
      { item: "Structural engineering coordination for retaining walls over 4 ft, pergolas and pool or water-feature structures", unit: "fixed", when: "retaining walls over 4 ft, shade structures or a pool are in the design" },
      { item: "Irrigation design: hydrozoned plan, point of connection, backflow preventer, controller and schedule; water-budget compliance", unit: "fixed", when: "an irrigation system is in scope" },
      { item: "Agency submittals: landscape plan review, tree removal permit, stormwater or water-efficient landscape ordinance (WELO) compliance package, HOA or design review board; plan-check responses", unit: "fixed" },
      { item: "Bidding assistance: contractor list, bid set issue, pre-bid walk, answers to bidder questions and bid tabulation", unit: "hour" },
      { item: "Construction observation: layout review, grading review, plant material inspection at the nursery or on delivery, irrigation coverage test, substantial completion punch list", unit: "hour" },
      { item: "Design revisions beyond the included rounds, additional meetings and presentations", unit: "hour" },
      { item: "Reimbursables: printing, plotting, delivery, mileage and agency fees paid on the owner's behalf", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Design' or 'Plans' line with no phase or deliverable named",
      "one lump-sum 'Landscape design' line hiding the phases",
      "installing plants, irrigation or hardscape — the landscape contractor's work",
      "boundary or topographic survey priced as the architect's own work instead of a passed-through or coordinated item",
      "'Miscellaneous' or 'contingency' lines",
    ],
    notes: [
      "Fixed phase fees assume the program and budget set at kickoff; a change in program or site area after schematic approval is an additional service",
      "Two rounds of revisions are included in each phase; further revisions are hourly",
      "Survey, geotechnical, arborist and structural engineering are sub-consultant costs passed through or contracted separately",
      "Agency and permit fees are paid by the owner; the fee covers preparing and responding to the submittal",
      "Construction observation is billed at the hours actually spent; it is not full-time site supervision",
    ],
  },
  architect: {
    basis: "AIA phases billed as fixed fees per deliverable (SD, DD, CD, bidding), with pre-design, meetings, agency responses and construction administration by the hour",
    steps: [
      { item: "Kickoff and pre-design: owner interviews, program of spaces and areas, budget and schedule targets, site visit and photographs", unit: "hour" },
      { item: "Existing-conditions documentation: field measurement and photographs of the existing building, drawn into as-built plans, elevations and sections", unit: "hour", when: "the work is a renovation or addition" },
      { item: "Zoning and code analysis: setbacks, height, FAR, parking, occupancy classification, construction type, egress and accessibility requirements summarized on a code sheet", unit: "fixed" },
      { item: "Schematic design (SD): site plan, floor plans, exterior elevations, building sections and massing views; outline of structural and MEP systems; owner presentation and sign-off", unit: "fixed" },
      { item: "Design development (DD): dimensioned plans, elevations, sections, wall sections, window and door schedules, finish selections, outline specifications; consultant coordination", unit: "fixed" },
      { item: "Consultant coordination: structural, MEP, civil and landscape scopes defined, fee proposals gathered, drawings checked across disciplines at each phase", unit: "hour" },
      { item: "Construction documents (CD), the full permit and bid set: cover and code sheet, site plan, floor plans, roof plan, reflected ceiling plans, elevations, sections, details, schedules and project manual specifications", unit: "fixed" },
      { item: "Additional drawing sheets beyond the base set (enlarged plans, interior elevations, added details)", unit: "unit", when: "the project requires sheets beyond the base set" },
      { item: "Permit submittal: application, plan sets and forms filed with the building department; plan-check comments answered and revised sheets re-issued", unit: "fixed" },
      { item: "Bidding or negotiation: bid set issued, pre-bid meeting, addenda, bid review and contractor recommendation", unit: "hour" },
      { item: "Construction administration: shop drawing and submittal review, RFI responses, change-order review, pay-application certification", unit: "hour" },
      { item: "Site observation visits during construction with a field report each visit", unit: "unit" },
      { item: "Substantial completion punch list and final closeout documents: record drawings from contractor markups, warranties and O&M binders", unit: "fixed" },
      { item: "Renderings, 3D model views or a physical model beyond the phase deliverables", unit: "fixed", when: "the owner wants presentation renderings or a model" },
      { item: "Reimbursables: printing, plotting, courier, travel and agency fees advanced on the owner's behalf", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Design' or 'Drawings' line with no phase or sheet content",
      "one lump sum 'Architectural services' hiding SD, DD and CD",
      "structural, MEP or civil engineering priced as if it were the architect's own work — a sub-consultant line or an exclusion",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "construction cost or contractor work in an architect's fee proposal",
    ],
    notes: [
      "Phase fees are fixed for the program and area approved at the end of schematic design; a change in scope after approval is an additional service billed hourly",
      "Each phase includes one owner review and one round of revisions; further rounds are hourly",
      "Permit, plan-check and impact fees are paid directly by the owner",
      "Consultant engineering fees are quoted separately by each consultant and passed through or contracted directly",
      "Construction administration hours are estimated from the construction schedule and billed as spent",
    ],
  },
  "residential-architect": {
    basis: "the homeowner's project priced by phase: fixed fees for as-builts, concept, design development and the permit set, with site visits, revisions and construction visits by the hour",
    steps: [
      { item: "Kickoff at the house: wish list, rooms and sizes, style references, budget, how the family uses the home; existing conditions photographed", unit: "hour" },
      { item: "Field measurement of the existing house and drawing of as-built floor plans, elevations and a roof plan", unit: "fixed", when: "the project is a remodel or addition" },
      { item: "Zoning and setback check: lot coverage, height, setbacks, floor-area limits, ADU or historic-district rules; a survey ordered where the setbacks are tight", unit: "fixed" },
      { item: "Concept design: two or three floor-plan schemes with a massing sketch or 3D view, walked through with the owner and one selected", unit: "fixed" },
      { item: "Design development: the chosen scheme dimensioned into floor plans, exterior elevations, a building section, roof plan, window and door schedule, preliminary kitchen and bath layouts", unit: "fixed" },
      { item: "Selections assistance: windows, doors, exterior materials, roofing and trim chosen with the owner from samples; cabinetry and finish direction for the kitchen and baths", unit: "hour" },
      { item: "Structural engineering coordination: beam, header and foundation design by the licensed engineer, loads and framing plan exchanged and checked against the architectural set", unit: "fixed" },
      { item: "Energy-code compliance documents (Title 24, REScheck or the IECC prescriptive path) prepared for the permit set", unit: "fixed" },
      { item: "Permit and construction set: site plan, foundation and framing plans, floor plans, elevations, sections, details, electrical plan, schedules and general notes; stamped and signed", unit: "fixed" },
      { item: "Permit submittal to the building department and the HOA or design review board; plan-check corrections answered and revised sheets re-issued", unit: "fixed" },
      { item: "Contractor bidding help: drawings issued to two or three builders, questions answered, bids compared line by line with the owner", unit: "hour" },
      { item: "Construction visits: foundation, framing, rough-in and finish stages checked against the drawings; contractor questions answered; a short report each visit", unit: "hour" },
      { item: "Design changes requested after the permit set is issued, drawn and re-submitted", unit: "hour", when: "the owner changes the design after permit issue" },
      { item: "Reimbursables: plotting, printing, courier and permit application fees advanced for the owner", unit: "fixed" },
    ],
    avoid: [
      "'Plans' or 'Blueprints' as one line with no phase or sheet content",
      "one 'Design fee' lump sum hiding concept, DD and the permit set",
      "the builder's construction work or material costs in the architect's proposal",
      "structural engineering hidden inside the architectural fee — a separate coordinated line or an exclusion",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
    ],
    notes: [
      "Fees are fixed for the square footage and program agreed at concept sign-off; adding rooms or square footage afterwards is an additional service",
      "Two rounds of revisions are included at concept and design development; further changes are hourly",
      "Structural engineering, survey, soils report and energy consultant are quoted separately and passed through",
      "Permit, plan-check and school or impact fees are paid by the owner directly to the jurisdiction",
      "Interior design beyond kitchen and bath layouts and exterior selections is excluded",
    ],
  },
  "commercial-architect": {
    basis: "AIA phases as fixed fees per deliverable for the building type and gross area; code analysis, agency submittals, submittal review and construction administration by the hour",
    steps: [
      { item: "Kickoff and programming: stakeholder interviews, space program with net and gross areas, occupancy and use, phasing, budget and schedule; site visit", unit: "hour" },
      { item: "Existing-conditions survey of the building: field measurement, photographs, as-built plans and reflected ceiling plans; asbestos and structural conditions flagged for the owner", unit: "hour", when: "the project is a tenant improvement or renovation" },
      { item: "Code and zoning analysis: occupancy classification, construction type, allowable area and height, fire separations, egress, plumbing fixture counts, ADA and accessibility, energy code; summarized on a code sheet", unit: "fixed" },
      { item: "Entitlements and pre-application meetings with planning, fire and building officials; conditional-use or design-review submittals prepared", unit: "hour", when: "the project needs a use permit or design review" },
      { item: "Schematic design: site plan, floor plans, elevations, sections, massing views, preliminary structural and MEP system narratives, outline specs and a cost-consultant coordination set", unit: "fixed" },
      { item: "Design development: dimensioned plans, RCPs, building and wall sections, exterior envelope details, door and finish schedules, MEP and structural coordination, DD specifications", unit: "fixed" },
      { item: "Consultant coordination and clash review across structural, MEP, fire protection, civil and landscape at each phase", unit: "hour" },
      { item: "Sustainability documentation: LEED, WELL or local green-code checklist and credit tracking through the design phases", unit: "fixed", when: "the owner is pursuing LEED, WELL or a green-code certification" },
      { item: "Construction documents: full permit and bid set with cover, code and life-safety plans, site plan, floor and roof plans, RCPs, elevations, sections, details, schedules and a CSI-format project manual", unit: "fixed" },
      { item: "Accessibility review of the completed set against the ADA Standards and the state accessibility code before submittal", unit: "fixed" },
      { item: "Permit submittal and plan-check responses to building, fire, health and planning; revised sheets re-issued until permit issue", unit: "hour" },
      { item: "Bidding: bid set issue, pre-bid walk, addenda, bidder questions, bid evaluation and award recommendation", unit: "hour" },
      { item: "Construction administration: submittal and shop-drawing review, RFIs, ASIs, change-order review, pay-application certification", unit: "hour" },
      { item: "Site observation visits with a field report and photos each visit; substantial completion and final punch lists", unit: "unit" },
      { item: "Closeout: record drawings from contractor markups, warranties, O&M manuals and certificate-of-occupancy coordination", unit: "fixed" },
      { item: "Reimbursables: printing, plotting, courier, travel, presentation renderings and agency fees advanced on the owner's behalf", unit: "fixed" },
    ],
    avoid: [
      "'Design' or 'Plans' as a single line with no phase, sheet list or code content",
      "one lump-sum 'Architectural fee' hiding SD, DD, CD and CA",
      "engineering disciplines priced as the architect's own work instead of coordinated sub-consultant lines",
      "the contractor's construction cost or equipment inside the fee proposal",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
    ],
    notes: [
      "Fees are fixed for the gross area and program set at the end of schematic design; growth in area or a change in occupancy is an additional service",
      "One review cycle per phase is included; further revisions, re-designs for budget and value-engineering redraws are hourly",
      "Structural, MEP, civil, landscape and specialty consultants are contracted directly by the owner or passed through at cost plus the coordination fee shown",
      "Permit, plan-check, impact and utility connection fees are paid by the owner",
      "Construction administration is estimated from the contractor's schedule and billed as spent",
    ],
  },
  "interior-architect": {
    basis: "space-planning, DD and CD phases as fixed fees for the interior area, with existing-conditions survey, FF&E selections, MEP coordination and construction administration by the hour",
    steps: [
      { item: "Kickoff and program: headcount, departments or rooms, adjacencies, equipment, storage, brand and finish direction; site walk of the existing space", unit: "hour" },
      { item: "Existing-conditions survey: field measurement of the shell, columns, windows, doors, ceiling heights, sprinkler heads, HVAC and electrical points; drawn as a CAD base plan and RCP", unit: "hour" },
      { item: "Test fit and space plan: two or three plan options with furniture blocking, seat counts and egress checked; one selected with the owner or landlord", unit: "fixed" },
      { item: "Schematic design: the selected plan developed with ceiling concept, lighting intent, material palette boards and 3D views of key rooms", unit: "fixed" },
      { item: "Design development: dimensioned partition plan, reflected ceiling plan, finish plan, power and data plan, millwork elevations, door and hardware schedule, preliminary FF&E plan", unit: "fixed" },
      { item: "Finish and material selections: flooring, wall finishes, ceiling, millwork laminates and stone, tile, paint and window treatments chosen from samples and specified", unit: "hour" },
      { item: "FF&E specification: furniture, fixtures and equipment scheduled with manufacturer, model, finish and quantities; dealer quotes gathered and compared", unit: "hour", when: "furniture procurement is in scope" },
      { item: "Code and accessibility review: occupant load, egress, corridor widths, ADA clearances, restroom fixture counts, finish flame-spread ratings", unit: "fixed" },
      { item: "MEP, structural and fire-protection coordination: engineer scopes defined, loads and device locations exchanged, drawings overlaid and checked", unit: "hour" },
      { item: "Construction documents: demolition plan, partition plan, RCP, finish plan, power and data plan, millwork sections and details, door and finish schedules, specifications; stamped", unit: "fixed" },
      { item: "Landlord and building-department submittal: landlord review package, permit application and plan-check corrections", unit: "fixed" },
      { item: "Bidding assistance: contractor walk-through, questions answered, bids leveled and reviewed with the owner", unit: "hour" },
      { item: "Construction administration: submittal review, RFIs, site visits at demolition, framing, above-ceiling and finish stages, punch list and closeout", unit: "hour" },
      { item: "Move-in and FF&E installation coordination: delivery scheduling, installation supervision and the furniture punch list", unit: "hour", when: "furniture installation oversight is in scope" },
      { item: "Reimbursables: printing, samples, courier, travel and permit fees advanced for the owner", unit: "fixed" },
    ],
    avoid: [
      "'Interior design' as one lump-sum line with no phases or deliverables",
      "furniture, fixtures or finish material purchase costs mixed into the fee",
      "the contractor's demolition, framing or finish work",
      "MEP engineering priced as the interior architect's own work",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
    ],
    notes: [
      "Phase fees are fixed for the square footage and program approved at test-fit sign-off; changes in area or program afterwards are hourly",
      "Two rounds of revisions per phase are included; further rounds are hourly",
      "FF&E purchase cost is the owner's; the fee covers specification, procurement coordination and installation oversight where included",
      "Engineering consultants are contracted by the owner or passed through at cost",
      "Permit and landlord review fees are paid by the owner",
    ],
  },
  "architectural-drafting": {
    basis: "drawing sheets counted per set at the stated scale and detail level, with field measurement, redlines and revisions by the hour and file conversions fixed",
    steps: [
      { item: "Intake: markups, sketches, photos, survey and prior drawings received; drawing list, scales, sheet size, title block and CAD standards agreed", unit: "hour" },
      { item: "Field measurement of the existing building with a laser distance meter, photographs and dimensioned field sketches", unit: "hour", when: "no accurate existing drawings are available" },
      { item: "As-built drawings: existing floor plans, elevations, sections and roof plan drawn from field notes at the agreed scale", unit: "unit" },
      { item: "Proposed floor plans drawn from the designer's or owner's sketches: walls, doors, windows, fixtures, dimensions, room names and notes", unit: "unit" },
      { item: "Exterior elevations and building sections at the agreed scale, with materials, heights and grades labeled", unit: "unit" },
      { item: "Foundation, framing and roof-framing plans drawn from the engineer's layout and member sizes", unit: "unit", when: "structural sheets are part of the set" },
      { item: "Electrical, plumbing-fixture and reflected-ceiling plans with symbols and legends", unit: "unit", when: "MEP sheets are part of the set" },
      { item: "Details and wall sections: footing, wall, roof-edge, stair and window details drawn at 3/4 in. or 1-1/2 in. scale", unit: "unit" },
      { item: "Schedules and notes: door, window, finish and hardware schedules, general notes and the code sheet", unit: "fixed" },
      { item: "Site plan from the survey or plat: setbacks, easements, driveway, utilities and drainage arrows", unit: "unit", when: "a site plan is required for permit" },
      { item: "Redline pickup: designer, engineer or plan-check comments incorporated and clouded, revision block updated", unit: "hour" },
      { item: "3D model or rendering of the exterior or a key room built from the drawing set", unit: "fixed", when: "the client wants 3D views" },
      { item: "File delivery: DWG and PDF sets, DWG-to-Revit or PDF-to-CAD conversion, plotted sets to the client and the permit counter", unit: "fixed" },
      { item: "Coordination with the stamping architect or engineer who reviews and seals the set", unit: "hour", when: "the drawings need a licensed stamp" },
    ],
    avoid: [
      "'Drawings' or 'CAD work' as one line with no sheet list or scale",
      "a lump sum 'drafting' with the sheet count hidden",
      "design decisions or code compliance priced as the drafter's responsibility — the licensed professional's work",
      "construction cost or contractor work in a drafting proposal",
      "'Miscellaneous' or 'contingency' lines",
    ],
    notes: [
      "Sheets are priced at the stated scale and sheet size; a sheet added or a scale change after the drawing list is agreed is priced as an added sheet",
      "Two rounds of redlines are included; further revisions are hourly",
      "Drafting is not design or engineering; the set is stamped by the client's licensed architect or engineer where the jurisdiction requires it",
      "Files are delivered in DWG and PDF; Revit or other native formats are quoted where requested",
      "Turnaround is stated per sheet package from receipt of complete markups",
    ],
  },
  "bim-revit": {
    basis: "model scope priced by building area, disciplines and LOD per phase, with model authoring and coordination meetings by the hour, clash reports and deliverables fixed",
    steps: [
      { item: "Kickoff and BIM execution plan (BEP): model uses, LOD by element and phase, disciplines, file naming, shared coordinates, worksets, software versions and exchange schedule", unit: "fixed" },
      { item: "Existing-conditions model from a laser scan or measured survey: point cloud registered and modeled to LOD 200 for walls, floors, roof, structure and major MEP", unit: "fixed", when: "the project includes an existing building" },
      { item: "Revit template and project setup: levels, grids, shared coordinates, phases, view templates, sheet list and family library", unit: "fixed" },
      { item: "Architectural model authored to LOD 300: walls, floors, roofs, ceilings, doors, windows, stairs, curtain wall, rooms and areas", unit: "fixed" },
      { item: "Structural model to LOD 300: foundations, columns, beams, slabs and bracing with analytical alignment to the engineer's model", unit: "fixed", when: "structural is in the BIM scope" },
      { item: "MEP model to LOD 300: ductwork, piping, plumbing, conduit and cable tray, equipment with clearances, connected systems", unit: "fixed", when: "MEP is in the BIM scope" },
      { item: "Model enrichment to LOD 350 or 400 for fabrication and detailing: hangers, connections, sleeves, embeds and shop-level dimensions", unit: "fixed", when: "fabrication-level modeling is required" },
      { item: "Clash detection in Navisworks: discipline models federated, clash tests run by system pairs, report issued with clash IDs and screenshots", unit: "unit" },
      { item: "Coordination meetings: clashes walked through with the trades, resolutions assigned and tracked, models updated after each round", unit: "hour" },
      { item: "Sheet production and annotation: plans, sections, elevations, schedules and details cut from the model and placed on sheets", unit: "unit" },
      { item: "Quantity takeoff and schedules exported from the model for estimating", unit: "fixed", when: "model-based quantities are requested" },
      { item: "4D schedule linking or 5D cost linking of the model to the construction schedule or estimate", unit: "fixed", when: "4D or 5D deliverables are requested" },
      { item: "Renderings, walkthrough animation or VR export from the model", unit: "fixed", when: "visualization deliverables are requested" },
      { item: "Model updates from design changes, RFIs and ASIs during construction", unit: "hour" },
      { item: "As-built and record model updated from field verification and contractor markups; COBie or facility-management data populated", unit: "fixed" },
      { item: "Deliverables packaged: native RVT, NWD federated model, IFC export, PDF and DWG sheet sets, family library", unit: "fixed" },
    ],
    avoid: [
      "'BIM modeling' or 'Revit' as one line with no discipline, LOD or deliverable",
      "a fixed fee that does not name the LOD and disciplines it covers",
      "design or engineering decisions priced as the modeler's responsibility — the licensed professional's work",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "construction work or material cost in a BIM proposal",
    ],
    notes: [
      "Fees are fixed for the area, disciplines and LOD in the BIM execution plan; a change in LOD or added disciplines is a change order",
      "Clash detection is priced per coordination round; rounds beyond those listed are hourly",
      "The model is authored from the design team's drawings and does not replace their design responsibility or stamp",
      "Laser scanning is subcontracted and passed through at cost where an existing-conditions model is required",
      "Software licenses and cloud collaboration hub (BIM 360 or ACC) costs are billed as reimbursables where the client does not host",
    ],
  },
  "structural-engineer": {
    basis: "design fee fixed per deliverable for the structural system and building size, with site visits, coordination meetings, plan-check responses and construction-phase services by the hour",
    steps: [
      { item: "Kickoff and site visit: architectural drawings reviewed, structural system options discussed, existing framing and foundation observed and photographed", unit: "hour" },
      { item: "Existing-conditions assessment: existing framing, foundation and connections field-verified, member sizes and spans recorded, deficiencies noted for the design", unit: "hour", when: "the work is on an existing building" },
      { item: "Design criteria and load development: dead, live, roof, snow, wind and seismic loads per ASCE 7 and the adopted IBC or IRC, soil bearing values from the geotechnical report", unit: "fixed" },
      { item: "Schematic structural system: gravity and lateral system selection, preliminary member sizes, framing concept narrative for the architect", unit: "fixed" },
      { item: "Gravity analysis and design: beams, headers, joists, girders, columns and posts sized; deflection and vibration checked", unit: "fixed" },
      { item: "Lateral analysis and design: shear walls, moment frames or braced frames, diaphragms, hold-downs, anchors and drag struts designed for wind and seismic", unit: "fixed" },
      { item: "Foundation design: spread footings, continuous footings, grade beams, slab-on-grade or deep foundations sized to the geotechnical bearing values", unit: "fixed" },
      { item: "Stamped calculation package: load derivation, member and connection calcs, lateral analysis output, foundation calcs, sealed by the engineer of record", unit: "fixed" },
      { item: "Structural drawings: general notes, foundation plan, framing plans for each level and the roof, shear wall or frame schedule, typical and specific details; stamped and signed", unit: "fixed" },
      { item: "Additional drawing sheets beyond the base set (added framing levels, special details)", unit: "unit", when: "the building has more framing levels or special conditions than the base set" },
      { item: "Coordination with the architect and MEP: framing depths, openings, equipment supports and penetrations checked across disciplines", unit: "hour" },
      { item: "Plan-check responses: structural comments from the building department answered, calcs and sheets revised and re-issued", unit: "hour" },
      { item: "Deferred-submittal review: trusses, steel connections, pre-engineered stairs or cold-formed framing shop drawings checked and stamped as reviewed", unit: "unit", when: "the project has deferred submittals" },
      { item: "Construction-phase services: shop drawing and submittal review, RFI responses, site observation at footings, framing and anchor installation with a field report each visit", unit: "hour" },
      { item: "Structural observation letters: final observation and the engineer's letter to the building department at completion", unit: "fixed" },
    ],
    avoid: [
      "'Engineering' or 'Calcs' as one line with nothing named",
      "a lump-sum 'structural design' hiding gravity, lateral, foundation and drawings",
      "geotechnical investigation priced as the structural engineer's own work",
      "the contractor's steel, lumber or concrete cost in an engineering proposal",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
    ],
    notes: [
      "The fee is fixed for the structural system and building size on the architectural drawings received; a change in framing scheme or building footprint after design starts is an additional service",
      "Design assumes the geotechnical report's bearing values; without a report, a presumptive bearing value per the code is used and stated on the drawings",
      "One round of plan-check responses is included; further rounds and re-designs for contractor substitutions are hourly",
      "Special inspections and materials testing are performed by an independent agency hired by the owner",
      "Construction-phase hours are estimated and billed as spent",
    ],
  },
  "civil-engineer": {
    basis: "site-development design as fixed fees per plan sheet and report, with survey and geotechnical passed through, agency submittals fixed, meetings and construction services by the hour",
    steps: [
      { item: "Kickoff and site visit: project program, site constraints, existing drainage patterns, utility availability and access observed; jurisdiction requirements confirmed", unit: "hour" },
      { item: "Due diligence and records research: zoning, easements, floodplain (FEMA FIRM), wetlands, utility as-builts, prior plans and agency standards collected and summarized", unit: "fixed" },
      { item: "Base map preparation from the boundary and topographic survey, utility locates and geotechnical report; existing-conditions sheet", unit: "fixed" },
      { item: "Conceptual site plan: building pad, parking, access, fire lane, stormwater footprint and utility routing laid out for owner and pre-application review", unit: "fixed" },
      { item: "Pre-application meeting with planning, public works and the fire marshal; entitlement submittal packages", unit: "hour" },
      { item: "Grading and drainage plan: finished grades, pad elevations, retaining walls, spot elevations, cut and fill balance, ADA slopes at accessible routes", unit: "fixed" },
      { item: "Stormwater management design: detention or retention sizing, water-quality BMPs, outlet structures; drainage report with pre- and post-development calculations", unit: "fixed" },
      { item: "Erosion and sediment control plan and SWPPP: BMP layout, construction sequencing, NPDES notice of intent and inspection forms", unit: "fixed" },
      { item: "Site utility plan: water service and fire line with hydrants, sanitary sewer with profiles, storm drain with profiles, dry utility routing", unit: "fixed" },
      { item: "Paving, striping and site-detail sheets: pavement sections from the geotechnical report, curb, sidewalk, ADA ramps, signage and construction details", unit: "fixed" },
      { item: "Roadway, driveway and right-of-way improvement plans with profiles and cross sections", unit: "fixed", when: "work extends into the public right-of-way" },
      { item: "Agency submittals and plan-check responses: site plan, grading permit, public-works and utility-district reviews, revised sheets re-issued", unit: "fixed" },
      { item: "Engineer's cost estimate of the site improvements and the bonding or surety quantity estimate for the jurisdiction", unit: "fixed" },
      { item: "Construction-phase services: submittal review, RFIs, site observation at subgrade, utility installation and paving, as-built certification for the jurisdiction", unit: "hour" },
      { item: "Record drawings and final certification of the stormwater facility and grading for the certificate of occupancy", unit: "fixed" },
      { item: "Reimbursables: printing, agency fees, mileage and courier advanced on the owner's behalf", unit: "fixed" },
    ],
    avoid: [
      "'Civil design' or 'Site plans' as one line with no sheet or report named",
      "boundary and topographic survey or geotechnical borings priced as the civil engineer's own work",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "the contractor's grading, paving or pipe costs in an engineering proposal",
      "a stormwater report with no calculations or BMP sizing named",
    ],
    notes: [
      "Fees are fixed for the site area and program on the conceptual plan approved by the owner; a re-layout after grading design starts is an additional service",
      "Survey, geotechnical, environmental and traffic studies are sub-consultant costs passed through or contracted directly by the owner",
      "Two rounds of agency comments are included; further rounds are hourly",
      "Agency review, permit, impact and connection fees are paid by the owner",
      "Construction-phase services are billed at the hours spent",
    ],
  },
  "geotechnical-engineer": {
    basis: "borings and test pits priced each to the stated depth, lab tests each, the geotechnical report fixed, with reconnaissance, field logging and construction-phase testing by the hour",
    steps: [
      { item: "Site reconnaissance and records review: published geologic maps, prior reports, NRCS soils, groundwater records and a site walk to place the exploration points", unit: "hour" },
      { item: "Utility clearance: 811 one-call ticket, private locate at each boring location, access and permits for drilling in the right-of-way", unit: "fixed" },
      { item: "Drill-rig mobilization and site access: truck- or track-mounted rig, support truck and crew delivered; mats or a track rig where access is soft", unit: "fixed" },
      { item: "Soil borings with hollow-stem auger or mud rotary to the stated depth (typically 20-50 ft), Standard Penetration Test at 2.5-5 ft intervals, samples logged by the field engineer", unit: "unit" },
      { item: "Rock coring with an NQ or HQ core barrel below auger refusal, RQD and recovery logged", unit: "linear ft", when: "bedrock is encountered above the target depth" },
      { item: "Test pits excavated with a backhoe to 8-12 ft, logged, sampled and backfilled", unit: "unit", when: "shallow exploration or infiltration testing is specified" },
      { item: "Groundwater monitoring wells installed in completed borings with screen, sand pack, bentonite seal and flush-mount cover", unit: "unit", when: "groundwater monitoring is required" },
      { item: "Field infiltration or percolation tests at the stormwater facility or drainfield locations", unit: "unit", when: "infiltration BMPs or a septic system are planned" },
      { item: "Borehole abandonment with bentonite grout and a surface patch to match; test pits backfilled and compacted", unit: "unit" },
      { item: "Laboratory testing: moisture content, Atterberg limits, sieve and hydrometer, Proctor, consolidation, direct shear or unconfined compression, corrosivity and R-value per ASTM", unit: "unit" },
      { item: "Engineering analysis: bearing capacity, settlement, lateral earth pressures, liquefaction screening, slope stability, pavement section and seismic site class", unit: "fixed" },
      { item: "Geotechnical report: site and subsurface description, boring logs and location plan, lab results, groundwater, foundation and slab recommendations, earthwork and compaction specs, pavement sections, seismic parameters; sealed", unit: "fixed" },
      { item: "Plan review and consultation with the structural and civil engineers during design; plan-check responses to the building department", unit: "hour" },
      { item: "Construction-phase testing and observation: footing subgrade inspection, fill placement and compaction testing with a nuclear gauge, pile or pier observation, daily field reports", unit: "hour" },
      { item: "Final letter of geotechnical observation and the compaction test summary for the building department", unit: "fixed" },
    ],
    avoid: [
      "'Soil test' or 'Borings' as one line with no count or depth",
      "a lump-sum 'geotech report' with the field work hidden inside it",
      "lab testing with no test named",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "environmental Phase I or II sampling in a geotechnical proposal — a separate scope",
    ],
    notes: [
      "Boring count and depth are set from the building footprint and code minimums; refusal, caving or groundwater that needs mud rotary, extra footage or additional borings are priced as a change",
      "The client provides site access and marks any private utilities not covered by the one-call ticket; damage to unmarked private utilities is the owner's responsibility",
      "Lab testing quantities are estimated from the expected soils and adjusted to the samples recovered",
      "Recommendations apply to the project described; a change in building location, loads or grades after the report is issued may require a supplemental letter",
      "Construction-phase testing is billed at the hours spent and the tests run",
    ],
  },
  "environmental-engineer": {
    basis: "assessments and reports fixed per deliverable, sampling and lab analysis per sample, with site work, agency negotiation and remediation oversight by the hour",
    steps: [
      { item: "Kickoff and site reconnaissance: current and past uses, adjoining properties, storage tanks, drums, staining, drains and stressed vegetation observed and photographed", unit: "hour" },
      { item: "Phase I Environmental Site Assessment per ASTM E1527-21: records review, historical aerials, Sanborn maps, regulatory database search, interviews, site visit and the report with findings and RECs", unit: "fixed" },
      { item: "Sampling and analysis plan and health-and-safety plan for the Phase II investigation", unit: "fixed", when: "the Phase I identifies recognized environmental conditions" },
      { item: "Utility clearance and access agreements for the sampling locations; 811 ticket and private locate", unit: "fixed" },
      { item: "Soil borings with a direct-push (Geoprobe) rig to the stated depth, continuous cores screened with a PID and sampled at the intervals specified", unit: "unit" },
      { item: "Groundwater monitoring wells installed, developed and sampled; surveyed for elevation and gauged", unit: "unit", when: "groundwater is a potential pathway" },
      { item: "Soil, groundwater, soil-vapor or sediment samples collected and shipped under chain of custody", unit: "unit" },
      { item: "Laboratory analysis by a certified lab for VOCs, SVOCs, TPH, RCRA metals, PCBs or asbestos as specified, standard turnaround", unit: "unit" },
      { item: "Data validation and risk screening against state and EPA screening levels; conceptual site model", unit: "fixed" },
      { item: "Phase II report: methods, boring logs, well construction, lab results tabulated against screening levels, figures and recommendations", unit: "fixed" },
      { item: "Remedial action plan or corrective action design: alternatives evaluated, remedy selected, design drawings and specifications for excavation, SVE, in-situ treatment or capping", unit: "fixed", when: "contamination above action levels is confirmed" },
      { item: "Regulatory agency coordination: submittals to the state agency or local oversight program, no-further-action requests, meetings and responses", unit: "hour" },
      { item: "Permits and compliance documents: SWPPP, SPCC plan, air permit application, NPDES or industrial stormwater permit, hazardous-waste generator filings", unit: "fixed", when: "compliance permitting is in scope" },
      { item: "Remediation oversight: contractor observation, confirmation sampling, waste profiling and manifests, daily field reports", unit: "hour" },
      { item: "Closure or completion report with confirmation results, disposal manifests and the closure request to the agency", unit: "fixed" },
      { item: "Reimbursables: lab fees above the samples listed, database reports, drilling subcontractor, disposal fees and agency fees passed through", unit: "fixed" },
    ],
    avoid: [
      "'Environmental testing' or 'Assessment' as one line with no ASTM standard, samples or analytes named",
      "lab analysis with no analyte suite named",
      "the remediation contractor's excavation or disposal cost in the engineer's fee",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "geotechnical borings or foundation recommendations — a separate scope",
    ],
    notes: [
      "Sample counts and analyte suites are estimated from the Phase I findings; additional samples, step-outs or rush lab turnaround are priced as a change",
      "Drilling, lab, disposal and database subcontractors are passed through at cost plus the handling fee shown",
      "Agency review fees and oversight cost-recovery charges are paid by the owner",
      "Site access, marking of private utilities and a clear work area are provided by the owner",
      "Findings apply to the sampled locations on the dates sampled; conditions elsewhere on the site are not certified",
    ],
  },
  "mechanical-engineer": {
    basis: "HVAC design as fixed fees per deliverable for the building area and system type, with site visits, coordination, plan-check responses and construction-phase services by the hour",
    steps: [
      { item: "Kickoff and site visit: architectural drawings and program reviewed, existing equipment and ductwork surveyed, owner comfort and energy goals, utility availability", unit: "hour" },
      { item: "Basis of design: design conditions, ventilation rates per ASHRAE 62.1 or 62.2, system type options, zoning, controls approach and energy-code path documented for owner sign-off", unit: "fixed" },
      { item: "Load calculations: heating and cooling loads by room and zone (Manual J for residential; ASHRAE methods in Trane TRACE or Carrier HAP for commercial)", unit: "fixed" },
      { item: "Equipment selection and sizing: furnaces, heat pumps, air handlers, RTUs, chillers, boilers, VRF and ERV selected with Manual S or manufacturer data; schedules prepared", unit: "fixed" },
      { item: "Duct design: Manual D or equal-friction sizing, layout, static pressure calculation, register and diffuser selection, outside-air and exhaust paths", unit: "fixed" },
      { item: "Hydronic or refrigerant piping design: pipe sizing, pump selection, expansion, venting and refrigerant line lengths", unit: "fixed", when: "the system is hydronic or VRF" },
      { item: "Energy-code compliance: COMcheck, Title 24 or IECC mechanical forms, economizer, demand-control ventilation and fan-power checks", unit: "fixed" },
      { item: "Controls and sequences of operation: thermostat or BAS points list, sequences for each system, control diagrams", unit: "fixed" },
      { item: "Mechanical drawings: legend and notes, demolition plan, floor plans with ductwork and piping, roof plan, equipment schedules, details, sequences; stamped and signed", unit: "fixed" },
      { item: "Additional drawing sheets beyond the base set (enlarged mechanical rooms, added floors, sections)", unit: "unit", when: "the building has more floors or mechanical rooms than the base set" },
      { item: "Specifications: CSI Division 23 sections for equipment, ductwork, piping, insulation, controls and testing-and-balancing", unit: "fixed" },
      { item: "Coordination with the architect, structural, electrical and plumbing engineers: equipment weights, openings, electrical loads and clearances checked", unit: "hour" },
      { item: "Permit submittal support and plan-check responses to the building department and fire marshal; revised sheets re-issued", unit: "hour" },
      { item: "Construction-phase services: submittal and shop-drawing review, RFIs, site observation at rough-in and equipment set, TAB report review", unit: "hour" },
      { item: "Commissioning support: functional test procedures, startup witness, sequence verification and review of the final commissioning report", unit: "fixed", when: "commissioning is required by the code or the owner" },
    ],
    avoid: [
      "'HVAC design' or 'Mechanical' as one line with nothing named",
      "load calculations with no method (Manual J, ASHRAE) named",
      "the contractor's equipment, ductwork or installation cost in an engineering proposal",
      "plumbing or electrical design hidden inside the mechanical fee — separate disciplines",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
    ],
    notes: [
      "Fees are fixed for the building area and system type in the basis of design; a change of system after load calculations are complete is an additional service",
      "Design assumes the architectural background drawings received; changes to the architectural set after DD are re-drawn hourly",
      "One round of plan-check responses is included; further rounds are hourly",
      "Testing, adjusting and balancing and third-party commissioning are performed by the contractor or the owner's commissioning agent",
      "Construction-phase hours are estimated and billed as spent",
    ],
  },
  "electrical-engineer": {
    basis: "design fixed per deliverable for the service size and building area; field survey, utility coordination, studies, plan-check responses and construction-phase services by the hour",
    steps: [
      { item: "Kickoff and site visit: architectural plans and program reviewed, existing service, panels and feeders surveyed, utility contact made and available fault current requested", unit: "hour" },
      { item: "Basis of design: service voltage and size, distribution scheme, emergency and standby power, lighting levels per IES, controls approach and energy-code path for owner sign-off", unit: "fixed" },
      { item: "Load calculations per NEC Article 220: connected and demand loads by panel, service and feeder sizing, voltage-drop checks", unit: "fixed" },
      { item: "Utility coordination: service application, transformer location, metering and the utility's design requirements", unit: "hour" },
      { item: "Power distribution design: one-line diagram, switchgear, panelboards, transformers, feeders and branch circuits, panel schedules", unit: "fixed" },
      { item: "Lighting design: fixture selection and layout, photometric calculations for interior and site lighting, lighting-control design per ASHRAE 90.1 or Title 24, emergency egress lighting", unit: "fixed" },
      { item: "Fire alarm design: device layout, riser diagram, sequence of operation and battery calculations per NFPA 72", unit: "fixed", when: "a fire alarm system is required" },
      { item: "Low-voltage and special systems: telecom and data pathways, security, access control, AV and nurse-call infrastructure drawings", unit: "fixed", when: "low-voltage systems are in scope" },
      { item: "Generator, ATS and emergency power design: load bank, fuel, transfer scheme and NEC 700, 701 and 702 separation", unit: "fixed", when: "standby or emergency power is required" },
      { item: "Short-circuit, protective-device coordination and arc-flash study per NFPA 70E and IEEE 1584 with arc-flash labels", unit: "fixed", when: "the service exceeds 1,200 A or the owner requires an arc-flash study" },
      { item: "Electrical drawings: legend and notes, demolition plan, power plans, lighting plans, one-line, panel schedules, details, fixture schedule; stamped and signed", unit: "fixed" },
      { item: "Additional drawing sheets beyond the base set (added floors, enlarged electrical rooms, site plan)", unit: "unit", when: "the building has more floors or electrical rooms than the base set" },
      { item: "Specifications: CSI Division 26, 27 and 28 sections for distribution, lighting, wiring methods, fire alarm and communications", unit: "fixed" },
      { item: "Coordination with the mechanical and plumbing engineers on motor loads and with the architect on room layouts and ceilings; plan-check responses to the building department and fire marshal", unit: "hour" },
      { item: "Construction-phase services: submittal review, RFIs, site observation at rough-in and equipment, witnessing of generator and fire alarm acceptance tests", unit: "hour" },
    ],
    avoid: [
      "'Electrical design' as one line with nothing named",
      "a load calculation line with no NEC article or panel schedule named",
      "the contractor's gear, wire, fixtures or installation cost in an engineering proposal",
      "mechanical or plumbing design inside the electrical fee — separate disciplines",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
    ],
    notes: [
      "Fees are fixed for the service size and building area in the basis of design; a change in service or added systems after DD is an additional service",
      "Available fault current and utility requirements are taken from the utility; delays in the utility's response are outside the schedule",
      "One round of plan-check responses is included; further rounds are hourly",
      "Fire alarm and low-voltage shop drawings are prepared by the installing contractor's licensed designer and reviewed by the engineer",
      "Construction-phase hours are estimated and billed as spent",
    ],
  },
  "plumbing-engineer": {
    basis: "plumbing design as fixed fees per deliverable for the fixture count and building area, with site survey, coordination, plan-check responses and construction services by the hour",
    steps: [
      { item: "Kickoff and site visit: architectural plans and fixture layouts reviewed, existing water service, sewer, gas meter and piping surveyed, utility pressure and flow data requested", unit: "hour" },
      { item: "Fixture count and code analysis: minimum fixtures per the IPC or UPC and occupancy, accessibility fixture requirements, backflow and water-heater code rules", unit: "fixed" },
      { item: "Water supply design: fixture-unit and demand calculation, pipe sizing with pressure-loss calculation from the street to the highest fixture, booster pump selection where pressure is short", unit: "fixed" },
      { item: "Domestic hot water: water-heater or boiler sizing, recirculation loop, mixing valves, expansion tank; solar or heat-pump water heating where specified", unit: "fixed" },
      { item: "Sanitary waste and vent design: drainage fixture units, pipe sizing, slopes, vent sizing, cleanouts, grease interceptor or sand-oil separator sizing", unit: "fixed" },
      { item: "Storm drainage design: roof drain and overflow sizing, leaders and horizontal drains per the rainfall rate, storm connection", unit: "fixed", when: "roof drainage is piped inside the building" },
      { item: "Natural gas or propane piping design: appliance loads, pipe sizing per the fuel gas code, meter and regulator coordination with the utility", unit: "fixed", when: "gas appliances are in the project" },
      { item: "Specialty systems: medical gas, compressed air, vacuum, lab waste or process piping design per NFPA 99 or the applicable standard", unit: "fixed", when: "medical gas or process piping is in scope" },
      { item: "Plumbing drawings: legend and notes, demolition plan, floor plans with water, waste, vent and gas, riser diagrams, fixture and equipment schedules, details; stamped and signed", unit: "fixed" },
      { item: "Additional drawing sheets beyond the base set (added floors, enlarged toilet rooms, site utility plan)", unit: "unit", when: "the building has more floors or toilet rooms than the base set" },
      { item: "Specifications: CSI Division 22 sections for piping, insulation, fixtures, equipment and testing", unit: "fixed" },
      { item: "Coordination with the architect, mechanical, electrical and civil engineers: fixture locations, chases, equipment power, water and sewer connection points", unit: "hour" },
      { item: "Plan-check responses to the building department and health department; revised sheets re-issued", unit: "hour" },
      { item: "Construction-phase services: submittal review, RFIs, site observation at underground rough-in and above-ceiling piping, witnessing of pressure tests and backflow certification", unit: "hour" },
    ],
    avoid: [
      "'Plumbing design' as one line with nothing named",
      "pipe sizing with no fixture-unit or pressure-loss calculation named",
      "the contractor's fixtures, pipe or installation cost in an engineering proposal",
      "HVAC or fire sprinkler design inside the plumbing fee — separate disciplines",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
    ],
    notes: [
      "Fees are fixed for the fixture count and building area on the architectural plans received; added fixtures or a re-layout after DD is an additional service",
      "Street pressure and flow are taken from the utility's data or a hydrant flow test ordered by the owner",
      "One round of plan-check responses is included; further rounds are hourly",
      "Site utilities beyond 5 ft from the building are the civil engineer's scope",
      "Construction-phase hours are estimated and billed as spent",
    ],
  },
  "fire-protection-engineer": {
    basis: "code analysis, system design and hydraulic calculations as fixed fees per deliverable, with survey, agency coordination, shop-drawing review and acceptance-test witnessing by the hour",
    steps: [
      { item: "Kickoff and site survey: occupancy and use reviewed, existing sprinkler, standpipe, alarm and water supply observed, fire department connection and hydrant locations noted", unit: "hour" },
      { item: "Water supply evaluation: hydrant flow test arranged or witnessed, static and residual pressures recorded, supply curve plotted against the system demand", unit: "fixed" },
      { item: "Fire and life-safety code analysis: occupancy classification, construction type, required systems, hazard classification per NFPA 13, egress and separation summary; code letter for the AHJ", unit: "fixed" },
      { item: "Sprinkler system design: hazard and density-area selection, system type (wet, dry, pre-action, ESFR), zone layout, riser and FDC location, pipe routing and head layout", unit: "fixed" },
      { item: "Hydraulic calculations for the remote area per NFPA 13 against the water-supply curve, sealed by the engineer", unit: "fixed" },
      { item: "Fire pump and tank sizing with the pump-room layout, test header and controller", unit: "fixed", when: "the water supply cannot meet the system demand" },
      { item: "Standpipe system design per NFPA 14: class, hose-valve locations, riser sizing and pressure-regulating requirements", unit: "fixed", when: "the building height or the fire code requires standpipes" },
      { item: "Fire alarm and detection design per NFPA 72: initiating and notification device layout, riser diagram, sequence-of-operations matrix, battery and voltage-drop calculations", unit: "fixed" },
      { item: "Smoke control design: rational analysis, zone diagrams, pressurization or exhaust rates, sequences and the special-inspection test plan", unit: "fixed", when: "an atrium, high-rise or covered mall requires smoke control" },
      { item: "Special hazard suppression: clean agent, kitchen hood, CO2 or foam system design and calculations per the governing NFPA standard", unit: "fixed", when: "a server room, kitchen or hazardous occupancy needs special suppression" },
      { item: "Fire protection drawings: legend and notes, floor plans with piping and heads, riser diagrams, details, device schedules and the alarm matrix; stamped and signed", unit: "fixed" },
      { item: "Specifications: CSI Division 21 and 28 sections for suppression, alarm and testing", unit: "fixed" },
      { item: "Fire marshal and building-department submittal and plan-check responses; variance or alternative-means requests where the code cannot be met literally", unit: "hour" },
      { item: "Shop-drawing review of the sprinkler contractor's NFPA 13 layout and calculations and the alarm contractor's NFPA 72 submittal", unit: "hour" },
      { item: "Acceptance testing witnessed: hydrostatic test, main drain and flow-switch tests, alarm device tests, fire pump acceptance test, smoke-control functional test; final report to the AHJ", unit: "hour" },
    ],
    avoid: [
      "'Fire protection design' as one line with nothing named",
      "hydraulic calculations with no NFPA 13 remote area or water-supply test named",
      "the sprinkler contractor's pipe, heads and installation cost in an engineering proposal",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "fire alarm and sprinkler priced as one line",
    ],
    notes: [
      "Fees are fixed for the occupancy, building area and systems listed; a change in occupancy or added systems is an additional service",
      "The hydrant flow test is ordered from the water utility or fire department at the owner's cost",
      "Sprinkler and alarm shop drawings are prepared by the installing contractors' NICET-certified designers and reviewed by the engineer",
      "One round of AHJ comments is included; further rounds and variance hearings are hourly",
      "Acceptance testing is scheduled by the contractor; the engineer's witnessing is billed at the hours spent",
    ],
  },
  "transportation-engineer": {
    basis: "studies and design phases as fixed fees per deliverable, with data collection per count location, and meetings, agency reviews and public involvement by the hour",
    steps: [
      { item: "Kickoff and scoping meeting with the agency or developer: study area, analysis scenarios, horizon years, level-of-service standards and the agency's methodology agreed", unit: "hour" },
      { item: "Records and data collection: as-built roadway plans, crash records for the last 3-5 years, signal timing sheets, planned developments and transportation plans gathered", unit: "fixed" },
      { item: "Traffic counts: 48-hour machine tube counts and peak-hour turning-movement counts with pedestrian and bicycle volumes at each study intersection", unit: "unit" },
      { item: "Field review of the corridor: lane configurations, sight distance, signage, pavement condition, transit stops, pedestrian facilities and driveways inventoried and photographed", unit: "hour" },
      { item: "Traffic impact study (TIS/TIA): trip generation per the ITE Trip Generation Manual, distribution and assignment, capacity analysis in Synchro or HCS for existing, background and build scenarios, mitigation and the sealed report", unit: "fixed" },
      { item: "Safety analysis: crash rate and pattern analysis, HSM predictive methods, countermeasure recommendations and benefit-cost", unit: "fixed", when: "the study addresses crash history or a safety improvement" },
      { item: "Travel demand modeling or micro-simulation (VISSIM) for corridor or interchange alternatives", unit: "fixed", when: "the agency requires simulation or model runs" },
      { item: "Alternatives analysis and conceptual roadway plans: typical sections, horizontal and vertical alignment concepts, intersection or roundabout concepts, planning-level cost estimates", unit: "fixed" },
      { item: "Preliminary (30%) roadway design: plan and profile, typical sections, right-of-way needs, drainage concept and the design-exception request", unit: "fixed" },
      { item: "Final roadway design (60, 90 and 100%): plan and profile sheets, cross sections, grading, drainage, signing and striping, traffic control plans, quantities and specifications per the state DOT standards", unit: "fixed" },
      { item: "Roadway plan sheets beyond the base set (additional stations, cross sections, detail sheets)", unit: "unit", when: "the corridor length needs more sheets than the base set" },
      { item: "Environmental documentation support: NEPA categorical exclusion or CEQA transportation section, noise and air-quality coordination", unit: "fixed", when: "federal or state environmental review applies" },
      { item: "Agency review submittals and comment responses at each milestone; DOT encroachment or access permit application", unit: "hour" },
      { item: "Public involvement: open-house exhibits, stakeholder meetings and council presentations", unit: "hour", when: "the project requires public meetings" },
      { item: "Bid-phase and construction support: bidder questions, RFIs, plan revisions and record drawings", unit: "hour" },
      { item: "Reimbursables: count subcontractor, software runs, printing, mileage and agency fees advanced", unit: "fixed" },
    ],
    avoid: [
      "'Traffic study' as one line with no scenarios, intersections or method named",
      "traffic counts with no count type or location count",
      "the contractor's paving, signal or construction cost in an engineering proposal",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "survey or geotechnical work priced as the transportation engineer's own",
    ],
    notes: [
      "The fee is fixed for the study intersections, scenarios and horizon years scoped with the agency; added intersections or scenarios are priced as a change",
      "Traffic counts are collected on typical weekdays while school is in session; holiday or weather re-counts are an added cost",
      "Survey, geotechnical, environmental and right-of-way services are sub-consultant costs passed through or contracted directly",
      "One round of agency comments per milestone is included; further rounds are hourly",
      "Agency review and permit fees are paid by the owner",
    ],
  },
  "traffic-engineer": {
    basis: "signal, signing and striping design fixed per intersection or plan sheet; counts and timing per intersection; field work, agency reviews and construction support by the hour",
    steps: [
      { item: "Kickoff and field review: existing signal equipment, cabinet and controller type, detection, poles and conduit, striping and signing inventoried at each intersection", unit: "hour" },
      { item: "Records collection: as-built signal plans, timing sheets, signal warrant history, crash data and the agency's signal design standards and approved products list", unit: "fixed" },
      { item: "Turning-movement and pedestrian counts at each intersection for the AM and PM peaks, with 24-hour tube counts on the approaches", unit: "unit" },
      { item: "Signal warrant analysis per the MUTCD (Chapter 4C) with the warrant report and recommendation", unit: "fixed", when: "a new signal or a signal removal is proposed" },
      { item: "Capacity and operations analysis in Synchro or HCS for existing and proposed conditions, with level of service, queue lengths and phasing recommendations", unit: "fixed" },
      { item: "Signal timing and coordination: cycle lengths, splits, offsets and time-of-day plans developed and optimized; timing sheets prepared for the controller", unit: "unit" },
      { item: "Signal design plans: pole and mast-arm layout, signal heads, pedestrian signals and push buttons, detection (loops, video or radar), conduit and pull boxes, cabinet and service, wiring and phase diagrams per the agency standard", unit: "fixed" },
      { item: "Structural pole and mast-arm calculations or foundation design where the agency does not use standard plans", unit: "fixed", when: "non-standard poles or foundations are required" },
      { item: "Signing and striping plans: lane lines, crosswalks, arrows, legends, raised markers and signs per the MUTCD with removals and the sign schedule", unit: "fixed" },
      { item: "Temporary traffic control plans: staging, lane closures, detours, flagging and device layout per MUTCD Part 6 for the construction", unit: "fixed" },
      { item: "ITS and communications design: interconnect conduit and fiber, CCTV, emergency vehicle preemption, transit priority and the central system connection", unit: "fixed", when: "interconnect, CCTV or preemption is in scope" },
      { item: "Intersection lighting and photometric design where street lighting is part of the signal work", unit: "fixed", when: "intersection lighting is included" },
      { item: "Quantities, engineer's estimate and special provisions for the agency's bid package", unit: "fixed" },
      { item: "Agency and DOT submittal reviews at 60, 90 and 100% with comment responses; encroachment permit application", unit: "hour" },
      { item: "Construction support: submittal review, RFIs, signal turn-on attendance, timing implementation and fine-tuning in the field, record drawings", unit: "hour" },
    ],
    avoid: [
      "'Signal design' as one line with no intersection count or plan content",
      "signing and striping bundled into the signal line",
      "the contractor's poles, controller or installation cost in an engineering proposal",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "a traffic impact study — the transportation planner's scope, priced separately",
    ],
    notes: [
      "Fees are fixed per intersection for the agency standards named; added intersections or a change of agency standard after design starts is a change",
      "Signal timing assumes the agency's controller and software; on-street fine-tuning is billed at the hours spent",
      "Utility potholing, survey and geotechnical borings for pole foundations are passed through or contracted directly",
      "One round of comments per milestone is included; further rounds are hourly",
      "Agency permit and review fees are paid by the owner",
    ],
  },
  "hydrology-drainage-engineer": {
    basis: "hydrologic analysis and stormwater design as fixed fees per report and plan sheet, with field work, modeling runs, agency submittals and construction observation by the hour",
    steps: [
      { item: "Kickoff and site visit: drainage patterns, outfalls, existing culverts and channels, flooding history and downstream conditions observed and photographed", unit: "hour" },
      { item: "Records and data collection: FEMA FIRM and flood insurance study, NRCS soils, NOAA Atlas 14 rainfall, topographic mapping, as-built storm drains and the jurisdiction's drainage manual", unit: "fixed" },
      { item: "Watershed delineation and hydrologic analysis: sub-basins, time of concentration, curve numbers and peak flows for the design storms (2- through 100-year) by the Rational method or HEC-HMS", unit: "fixed" },
      { item: "Hydraulic analysis of existing and proposed conveyance: storm drain, culvert and channel capacity in HEC-RAS, StormCAD or HydraFlow with hydraulic grade lines", unit: "fixed" },
      { item: "Floodplain analysis and FEMA submittal: HEC-RAS model, no-rise certification, CLOMR or LOMR application package", unit: "fixed", when: "the site lies in or next to a mapped floodplain" },
      { item: "Stormwater management design: detention or retention basin, underground vault or infiltration system sized, outlet structure and emergency spillway designed", unit: "fixed" },
      { item: "Water-quality BMP selection and sizing: bioretention, permeable pavement, hydrodynamic separator or filter sized to the water-quality volume per the jurisdiction's manual", unit: "fixed" },
      { item: "Drainage report: methodology, pre- and post-development hydrology, hydraulic calculations, BMP sizing, maps and exhibits; sealed for the jurisdiction", unit: "fixed" },
      { item: "Storm drain plan and profile sheets: pipes, inlets, manholes, outfalls, grading of swales and basins, BMP details", unit: "fixed" },
      { item: "Drainage plan sheets beyond the base set (additional profiles, basin sections, added details)", unit: "unit", when: "the system needs more sheets than the base set" },
      { item: "Erosion and sediment control plan and SWPPP with the NPDES notice of intent", unit: "fixed", when: "land disturbance exceeds the permit threshold" },
      { item: "Culvert or bridge hydraulic design with scour analysis", unit: "fixed", when: "a road crossing of a stream or channel is in the project" },
      { item: "Stormwater operations and maintenance manual and the recorded maintenance agreement for the BMPs", unit: "fixed" },
      { item: "Agency submittals and comment responses: local stormwater review, state dam-safety or waterway permits, Corps or 401 coordination", unit: "hour" },
      { item: "Construction observation: basin and outlet-structure inspection, BMP installation checks, as-built survey review and the final stormwater certification", unit: "hour" },
    ],
    avoid: [
      "'Drainage design' or 'Stormwater' as one line with no report, model or BMP named",
      "a drainage report with no design storms or calculation method named",
      "the contractor's pipe, basin or grading cost in an engineering proposal",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "topographic survey or geotechnical infiltration testing priced as the hydrologist's own work",
    ],
    notes: [
      "The fee is fixed for the site area and drainage basins on the base map received; a re-grade or added basins after modeling starts is a change",
      "Topographic survey, infiltration testing and wetland delineation are provided by the owner or passed through",
      "FEMA, state and local review fees are paid by the owner",
      "One round of agency comments is included; further rounds and re-modeling for revised site plans are hourly",
      "Construction observation is billed at the hours spent; the final certification requires an as-built survey of the facility",
    ],
  },
  "land-surveyor": {
    basis: "survey types priced as fixed deliverables per parcel, with field crew time by the hour, monuments set each, and research, drafting and certification fixed",
    steps: [
      { item: "Records research: deeds, plats, recorded surveys, easements and right-of-way maps pulled from the county recorder and surveyor; adjoiner deeds abstracted", unit: "fixed" },
      { item: "Control and monument recovery: existing corners, section corners and benchmarks searched, found and tied by GPS/RTK or total station", unit: "hour" },
      { item: "Field survey crew: boundary evidence, improvements, fences, encroachments and features located with GPS/RTK and a robotic total station", unit: "hour" },
      { item: "Boundary analysis and computation: record calls reconciled with found evidence, lines and corners resolved, closures computed and the surveyor's opinion of the boundary formed", unit: "fixed" },
      { item: "Monuments set at unmonumented corners: iron rod with the surveyor's cap, or nail and disk in pavement, flagged and witnessed", unit: "unit" },
      { item: "Property line staking: lath and flagging set on line for fences, walls or construction", unit: "unit", when: "the owner needs the line marked on the ground" },
      { item: "Construction staking: building corners, offsets and grades set from the approved plans", unit: "hour", when: "construction layout is in scope" },
      { item: "Elevation certificate on the FEMA form with the survey of the lowest floor, adjacent grades and flood zone", unit: "fixed", when: "a flood elevation certificate is required" },
      { item: "Legal descriptions and exhibits: metes-and-bounds descriptions and sketches for easements, splits or dedications", unit: "unit", when: "new descriptions are needed" },
      { item: "Survey drawing: plat of survey or map at the stated scale with bearings, distances, monuments found and set, easements, encroachments, and the surveyor's certification and seal", unit: "fixed" },
      { item: "Record of survey or corner records filed with the county where the statute requires", unit: "fixed", when: "the state requires filing of a record of survey" },
      { item: "Delivery: signed and sealed PDF, DWG file and paper prints; recorded copy where filed", unit: "fixed" },
    ],
    avoid: [
      "'Survey' as one line with no survey type named",
      "field work with no crew hours or monument count",
      "title insurance or a title report priced as the surveyor's work",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "civil engineering or site design in a survey proposal",
    ],
    notes: [
      "The fee is fixed for the parcel described; heavy vegetation, missing monuments, conflicting records or adjoiner disputes that extend the field or research time are billed hourly with notice",
      "Access to the parcel and adjoiners is arranged by the owner; brush clearing for line of sight is excluded",
      "Recording fees and copies of record documents are passed through at cost",
      "Monuments set are described on the drawing; monuments disturbed after the survey are re-set at an added cost",
      "A survey is not a title opinion; encroachments and easements shown are those visible or of record furnished to the surveyor",
    ],
  },
  "boundary-topo-survey": {
    basis: "the parcel priced as a fixed deliverable by acreage and terrain, with research fixed, field crew by the hour, monuments each and the drawing fixed at the stated contour interval",
    steps: [
      { item: "Records research: deeds, plats, prior surveys, easements and right-of-way maps for the parcel and adjoiners; benchmark and control data collected", unit: "fixed" },
      { item: "Utility locate request (811) so that marked utilities can be picked up in the topographic survey", unit: "fixed" },
      { item: "Horizontal and vertical control: GPS/RTK ties to the state plane coordinate system and NAVD 88 benchmarks; site benchmark set", unit: "fixed" },
      { item: "Boundary field survey: existing monuments recovered, lines and corners measured with GPS/RTK and total station; encroachments and fences located", unit: "hour" },
      { item: "Boundary resolution: record and measured evidence reconciled, lines computed, closures checked and the surveyor's boundary determination made", unit: "fixed" },
      { item: "Corner monuments set: iron rod and cap or nail and disk at each unmonumented corner", unit: "unit" },
      { item: "Topographic field survey: ground shots on a grid and at breaks in grade, spot elevations, improvements, trees over the stated caliper, utilities, drainage features, edge of pavement and curbs", unit: "hour" },
      { item: "Drone or lidar mapping for large or open parcels with ground control checks", unit: "fixed", when: "the parcel is large enough that aerial mapping is faster than ground shots" },
      { item: "Tree survey: trees over the ordinance caliper located, tagged and identified by species and diameter", unit: "unit", when: "a tree survey is required by ordinance or design" },
      { item: "Utility survey of visible features: manholes, inverts and pipe sizes, valves, meters, poles and overhead lines", unit: "fixed" },
      { item: "Data processing and CAD drafting: point file reduced, digital terrain model built, contours at the stated interval (1 ft or 2 ft), planimetrics and boundary drawn to the client's layer standard", unit: "fixed" },
      { item: "Boundary and topographic survey drawing at the stated scale, with legend, north arrow, contours, features, easements and the surveyor's certification and seal", unit: "fixed" },
      { item: "Deliverables: sealed PDF, DWG with surface and point file (CSV), GIS shapefile where requested, paper prints", unit: "fixed" },
    ],
    avoid: [
      "'Topo' or 'Survey' as one line with no contour interval, acreage or deliverable",
      "boundary and topographic work priced as one line with no field hours or monument count",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "civil design or grading plans in a survey proposal",
      "underground utility designation (SUE) priced as part of a visible-feature topo",
    ],
    notes: [
      "The fee is fixed for the acreage, terrain and contour interval stated; dense vegetation, added area or a tighter interval is priced as a change",
      "Contours are generated from field shots and are accurate to half the interval; hard features are located to survey grade",
      "Underground utilities are shown only where marked by the one-call locate or visible at the surface; SUE designation is a separate service",
      "Access and vegetation clearing for line of sight are the owner's responsibility",
      "Recording and record-document fees are passed through",
    ],
  },
  "alta-survey": {
    basis: "the ALTA/NSPS survey priced as a fixed deliverable per parcel with title research, field crew by the hour, and each optional Table A item priced separately",
    steps: [
      { item: "Title commitment review: the current commitment, vesting deed and every Schedule B exception document obtained from the title company and abstracted for plotting", unit: "fixed" },
      { item: "Records research: adjoiner deeds, recorded plats, prior surveys, right-of-way maps and control data gathered", unit: "fixed" },
      { item: "Private utility locate coordinated for Table A item 11(b) and observed surface evidence of utilities noted for the plat", unit: "fixed", when: "Table A item 11 is requested" },
      { item: "Field survey crew: boundary monuments recovered, lines and corners measured, improvements, encroachments, access and evidence of use located with GPS/RTK and total station", unit: "hour" },
      { item: "Boundary resolution and closure: record calls, the title legal description and found evidence reconciled; discrepancies noted for the title company", unit: "fixed" },
      { item: "Monuments set at corners not found, with caps bearing the surveyor's registration", unit: "unit", when: "corners are unmonumented and Table A item 1 is requested" },
      { item: "Easements and Schedule B exceptions plotted on the survey with recording information, with unplottable items listed", unit: "fixed" },
      { item: "Table A optional items as requested, each priced separately: 2 address, 3 flood zone, 4 gross area, 6 zoning, 7 building dimensions, 8 substantial features, 9 parking count, 13 adjoiners, 16 earth moving, 18 wetlands markers, 19 offsite easements", unit: "unit" },
      { item: "Topographic contours or spot elevations for Table A item 5 at the stated interval", unit: "fixed", when: "Table A item 5 is requested" },
      { item: "Zoning report coordination for Table A items 6(a) and 6(b) with the zoning letter or report furnished by the client", unit: "fixed", when: "Table A item 6 is requested" },
      { item: "Survey drawing per the 2021 ALTA/NSPS Minimum Standard Detail Requirements: boundary, legal description, easements, improvements, encroachments, notes, vicinity map, legend and the surveyor's certification", unit: "fixed" },
      { item: "Certification to the owner, lender and title company as named, with the surveyor's seal", unit: "fixed" },
      { item: "Review comments from the title company, lender's counsel and buyer addressed and the survey re-issued", unit: "hour" },
      { item: "Delivery: sealed PDF, DWG and paper prints; the survey delivered to the title company for the policy", unit: "fixed" },
    ],
    avoid: [
      "'ALTA survey' as one lump line with no Table A items listed",
      "Table A items bundled into the base fee with no item numbers named",
      "a title commitment or zoning report priced as the surveyor's own deliverable",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "field work with no crew hours or parcel size",
    ],
    notes: [
      "The fee is fixed for the parcel and Table A items requested in writing; items added after the field work is complete are priced separately, some requiring a return trip",
      "A current title commitment with Schedule B documents is required before field work starts; research delays from the title company are outside the schedule",
      "Table A items 6(a) and 6(b) rely on a zoning report or letter furnished by the client; the surveyor does not render a zoning opinion",
      "The survey is certified to the parties named; adding parties after delivery is a re-certification at an added fee",
      "Turnaround is stated from receipt of the title commitment and site access",
    ],
  },
  "utility-survey": {
    basis: "SUE priced by quality level: records (D) and surface survey (C) by area, designation (B) by linear feet of utility, test holes (A) each, with mapping and deliverables fixed",
    steps: [
      { item: "Kickoff and scoping: project limits, utility types of interest, required ASCE 38-22 quality levels (A-D) and the deliverable format agreed with the engineer", unit: "hour" },
      { item: "Quality level D records research: utility owner as-builts, one-call member list, franchise maps, prior surveys and GIS layers collected and compiled", unit: "fixed" },
      { item: "811 one-call design ticket and coordination with utility owners for records and locate support", unit: "fixed" },
      { item: "Quality level C surface survey: manholes, valves, meters, pedestals, poles, hydrants and vaults located, inverts and pipe sizes measured", unit: "hour" },
      { item: "Quality level B designation: electromagnetic pipe and cable locating with a transmitter and receiver, sonde tracing of non-conductive lines, ground-penetrating radar sweeps, utilities painted and flagged in APWA colors", unit: "linear ft" },
      { item: "GPR grid sweep of the excavation footprint for unknown lines, tanks and vaults", unit: "sqft", when: "the engineer requires a grid sweep of a specific area" },
      { item: "Survey of the designated marks: paint and flags picked up by GPS/RTK or total station and tied to the project control and datum", unit: "hour" },
      { item: "Quality level A test holes: vacuum-excavated potholes to the top of the utility at the stated depth, with size, material, depth and coordinates recorded and the hole backfilled and patched", unit: "unit" },
      { item: "Manhole and inlet inspection with inverts, pipe sizes, materials and directions recorded; CCTV where the pipe condition is needed", unit: "unit", when: "gravity pipe data is required" },
      { item: "Utility conflict analysis: proposed design overlaid on the utility map and a conflict matrix with recommended resolutions", unit: "fixed", when: "the engineer requests a conflict analysis" },
      { item: "Utility mapping and drafting: CAD utility plan with each line labeled by owner, type, size, material, quality level and test-hole data; profiles where requested", unit: "fixed" },
      { item: "Utility survey report: methods, quality levels by segment, limitations, test-hole logs with photos, sealed by the professional in charge", unit: "fixed" },
      { item: "Deliverables: DWG, PDF, GIS geodatabase or shapefile and the test-hole data table; coordination meeting with the design team", unit: "fixed" },
    ],
    avoid: [
      "'Utility locate' as one line with no quality level, footage or test-hole count",
      "a lump-sum 'SUE' with quality levels A through D priced as one",
      "one-call marking by utility owners represented as level B designation",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "civil design or relocation engineering in a utility survey proposal",
    ],
    notes: [
      "Designation footage and test-hole counts are estimated from the records; utilities found beyond the estimate are billed at the unit rates shown",
      "Level B designation depends on the utility's signal response; non-conductive lines without tracer wire are mapped from records and marked as such",
      "Test holes are placed where the engineer directs; pavement patching matches the surface, and permits for potholing in the right-of-way are passed through",
      "Traffic control for work in the roadway is priced as a separate line where required by the agency",
      "Quality levels are reported per ASCE 38-22; the survey does not guarantee that every utility on the site has been found",
    ],
  },
};
