// Smart Proposal procedures — Exterior systems. See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  roofing: {
    basis: "roof area in squares (100 sqft) from the measured roof report, waste by pitch and cut-up; eaves, rakes, ridges, valleys and flashings in linear feet; penetrations each",
    steps: [
      { item: "Roof measurement report and pre-job inspection: aerial or on-roof measurement of area, pitch, eaves, rakes, ridges, hips and valleys; photos of the deck condition, flashings and every penetration", unit: "fixed" },
      { item: "Building permit, HOA approval where required, and final inspection scheduling", unit: "fixed" },
      { item: "Site protection: tarps over landscaping, AC units and the pool, plywood under the dumpster and along the drive, catch-all netting at the walls, satellite dish and gutter guards set aside", unit: "fixed" },
      { item: "Tear-off of the existing roofing to the bare deck, number of layers stated, old felt and flashings removed, nails pulled or driven flush, deck swept", unit: "sqft" },
      { item: "Disposal: roll-off dumpster delivered, hauled and dumped, landfill fees included", unit: "fixed" },
      { item: "Deck repair: rotted, soft or delaminated sheathing cut out and replaced with matching 1/2 in. CDX plywood or 7/16 in. OSB, nailed 6 in. o.c. at edges and 12 in. in the field", unit: "sqft", when: "the tear-off exposes rotted, soft or delaminated decking" },
      { item: "Ice and water shield: self-adhered SBS membrane at the eaves to 24 in. inside the warm wall, full width in valleys, and around chimneys, skylights and penetrations", unit: "sqft" },
      { item: "Synthetic underlayment over the remaining deck, cap-nailed, 4 in. side laps and 6 in. end laps, run up the walls 4 in.", unit: "sqft" },
      { item: "Drip edge at eaves and rakes: 26-gauge galvanized steel or aluminum F5 profile, under the underlayment at the eaves and over it at the rakes, color matched", unit: "linear ft" },
      { item: "Starter strip at eaves and rakes with the factory sealant strip set at the edge for wind hold-down", unit: "linear ft" },
      { item: "Shingles supplied: architectural laminated asphalt, Class A fire rating, 130 mph wind rating, or Class 4 impact-resistant where specified, in the chosen color, delivered and rooftop loaded", unit: "sq boards" },
      { item: "Shingle installation: 6 nails per shingle at the manufacturer's nail line, offsets per the wrapper, hand-sealed at rakes and on steep or cold-weather work, straight courses chalked off the eaves", unit: "sqft" },
      { item: "Valleys: closed-cut valleys over the ice and water shield, or open valleys with 24 in. W-profile painted steel where specified", unit: "linear ft" },
      { item: "Ridge and hip cap: matching high-profile cap shingles nailed and sealed per the manufacturer", unit: "linear ft" },
      { item: "Pipe boots and vents: new neoprene or lead flashing on every plumbing vent, new roof jacks on bath and kitchen exhaust vents, painted to match", unit: "unit" },
      { item: "Wall flashings: 4x4 in. pre-bent step flashing at sidewalls, apron flashing at headwalls, counter flashing let into the mortar joint or behind the siding and sealed", unit: "linear ft" },
      { item: "Chimney and skylight re-flashing: new base, step and counter flashing at the chimney with a cricket behind chimneys wider than 30 in.; new manufacturer flashing kit at each skylight", unit: "unit", when: "the roof has a chimney or skylights" },
      { item: "Ridge vent: shingle-over ridge vent cut into the ridge with a 1 in. slot each side, end plugs, with matching soffit intake confirmed open", unit: "linear ft" },
      { item: "Gutter apron flashing at the eaves, tucked into the existing gutters so runoff clears the fascia", unit: "linear ft", when: "the existing gutters stay in place" },
      { item: "Final cleanup: magnetic nail sweep of the lawn, beds and driveway, gutters cleared of tear-off grit, debris hauled, walk-through with the before-and-after photos", unit: "fixed" },
      { item: "Manufacturer system warranty registration (lifetime limited or enhanced system warranty as specified) and the workmanship warranty issued in writing", unit: "fixed" },
    ],
    avoid: [
      "a single 'Roofing' or 'New roof' line covering tear-off, materials and labor",
      "shingles priced as sqft — shingles are supplied per square (sq boards), labor per sqft",
      "'Materials' or 'Accessories' lines with no product named",
      "gutters and downspouts folded into the roof price — separate trade, separate line",
      "'Contingency' or 'unforeseen conditions' as a line — deck repair is its own conditional line",
      "a bare 'Cleanup' or 'Dumpster' line with no scope",
    ],
    notes: [
      "Roof area and edge lengths come from the measurement report or a site measure; waste is applied at the shingle line by pitch and cut-up",
      "Deck repair is priced per sqft and billed only as found once the tear-off exposes the deck; the first sheet or two is often included",
      "Layers beyond those stated, sagging framing or structural repair are priced as a change order",
      "Roof-mounted solar, satellite or antenna removal and reinstall is by the owner's provider unless listed",
      "Warranty terms follow the manufacturer's registration; the workmanship warranty is the contractor's own",
    ],
  },
  "residential-roof-repair": {
    basis: "each repair area by its size in sqft and its flashing in linear feet; diagnosis and access as fixed lines; boots, collars and vents each",
    steps: [
      { item: "Leak diagnosis: roof walk and attic inspection with a moisture meter, hose test where the entry point is not obvious, photo report marking each leak source and the repair proposed", unit: "fixed" },
      { item: "Access and safety: ladder staging, roof anchors and harness, tarps over the landscaping below the work area", unit: "fixed" },
      { item: "Temporary dry-in: tarp or peel-and-stick patch over the damaged area to stop active leaking until the repair date", unit: "fixed", when: "the roof is leaking before the repair can be scheduled" },
      { item: "Remove damaged shingles in the repair area, lift and un-seal the surrounding courses, pull nails and clear the deck", unit: "sqft" },
      { item: "Replace rotted or soft decking under the repair area with matching plywood, nailed to the rafters", unit: "sqft", when: "the decking under the repair is rotted or soft" },
      { item: "Ice and water membrane over the exposed deck at the repair area, lapped under the existing underlayment above", unit: "sqft" },
      { item: "Weave in new shingles matched to the existing profile and color, nailed at the nail line and hand-sealed under every lifted tab", unit: "sqft" },
      { item: "Re-flash plumbing vents: new neoprene or lead pipe boots, or a boot collar over a cracked boot, sealed and painted to match", unit: "unit", when: "a pipe boot is cracked, split or lifted" },
      { item: "Rebuild the wall or chimney flashing: new step flashing woven with the shingles, apron at the headwall, counter flashing let into the mortar joint or behind the siding and sealed", unit: "linear ft", when: "the leak is at a sidewall, headwall or chimney" },
      { item: "Valley repair: debris cleared, cracked valley metal replaced or the closed valley re-cut and sealed with new membrane under it", unit: "linear ft", when: "the leak is in a valley" },
      { item: "Reseal exposed fasteners, roof jacks, vent collars and skylight curbs with polyurethane roof sealant; cracked collars replaced", unit: "unit" },
      { item: "Roof tune-up over the rest of the roof: nail pops driven and sealed, lifted or slipped tabs re-fastened and hand-sealed, debris cleared from valleys and behind the chimney", unit: "fixed" },
      { item: "Haul-away of the removed material, magnetic sweep below the repair, photos of the finished repair", unit: "fixed" },
    ],
    avoid: [
      "a 'Roof repair' line with no location, size or method",
      "a full re-roof scope hidden in a repair estimate — a repair is a defined area",
      "interior ceiling drywall or paint — another trade, listed only as a referral",
      "'Sealant' or 'Caulking' as the whole repair for a flashing failure",
      "'Service call' plus 'Labor' with nothing repaired",
    ],
    notes: [
      "Repairs are scoped to the leak sources found at the diagnosis; a second source found once shingles are lifted is priced as an add",
      "Shingle color match is as close as current production allows; discontinued products are matched in profile, not exact color",
      "Decking replacement is per sqft as found; framing repair is a change order",
      "Workmanship warranty covers the repaired area only, for the stated term",
    ],
  },
  "commercial-roofing": {
    basis: "roof area in squares (100 sqft) for tear-off, insulation and membrane; perimeter edge, parapet and wall flashing in linear feet; drains, curbs and penetrations each",
    steps: [
      { item: "Pre-bid roof survey: core cuts to confirm the existing assembly and deck type, infrared or nuclear moisture scan for wet insulation, drain and edge inventory, roof plan with the findings", unit: "fixed" },
      { item: "Submittals and manufacturer pre-installation notice: product data, shop drawings, tapered layout, fastening pattern for the wind zone, and the system warranty application", unit: "fixed" },
      { item: "Asbestos survey of the existing roof before tear-off (NESHAP) by a licensed inspector, with abatement quoted separately if found", unit: "fixed", when: "the building predates 1990 or the jurisdiction requires the survey" },
      { item: "Permit, plan review and inspections at the jurisdiction's valuation-based fee", unit: "fixed" },
      { item: "Mobilization and safety: crane or hoist for material loading, debris chute, staging and laydown area, interior protection under the work, site-specific fall-protection plan with warning lines and edge guards", unit: "fixed" },
      { item: "Tear-off of the existing membrane and insulation to the deck, layers stated, gravel vacuumed on built-up roofs, wet insulation removed", unit: "sqft" },
      { item: "Haul and dispose of tear-off debris by the container, landfill fees included", unit: "cu yards" },
      { item: "Deck repair: deteriorated metal deck panels or rotted wood deck cut out and replaced, rusted deck wire-brushed and primed", unit: "sqft", when: "the survey or tear-off finds deteriorated deck" },
      { item: "Wood nailers: pressure-treated 2x stock at perimeter edges, curbs and expansion joints, anchored to the deck and built up flush with the insulation", unit: "linear ft" },
      { item: "Vapor retarder over the deck: self-adhered sheet or two-ply asphalt, sealed at walls and penetrations", unit: "sqft", when: "the building has high interior humidity or the specification calls for a vapor retarder" },
      { item: "Insulation: polyiso flat stock in two layers with staggered joints to the specified R-value (R-30 typical, LTTR rated), mechanically fastened or adhered in low-rise foam", unit: "sqft" },
      { item: "Tapered insulation and crickets to the drains at 1/4 in. per foot, laid per the approved tapered plan", unit: "sqft", when: "the roof ponds or the specification requires positive slope" },
      { item: "Cover board: 1/2 in. gypsum-fiber or high-density polyiso over the insulation, fastened or adhered", unit: "sqft" },
      { item: "Membrane supplied and laid: 60-mil TPO or PVC mechanically fastened or fully adhered, 60-mil EPDM adhered, or 2-ply SBS modified bitumen torch or cold-applied, sheets lapped per the manufacturer", unit: "sqft" },
      { item: "Seams: hot-air welded and probed on single-ply, or torch or cold-adhesive lapped on modified bitumen, with cut-edge sealant on reinforced sheets", unit: "linear ft" },
      { item: "Base flashing at parapets and walls: membrane flashing to the termination height, termination bar and sealant, surface-mount or reglet counterflashing", unit: "linear ft" },
      { item: "Perimeter edge metal: ANSI/SPRI ES-1 rated drip edge or gravel stop, or coping cap on parapets, 24-gauge Kynar steel or .050 aluminum with cleats and splice plates", unit: "linear ft" },
      { item: "Curbs and penetrations: rooftop unit and skylight curbs re-flashed, pipe boots, pourable sealer pockets replacing old pitch pans, flashing-grade sealant at every termination", unit: "unit" },
      { item: "Roof drains: new drain bodies, clamping rings and strainers, or retrofit drain inserts, plus overflow drains or scuppers where code requires", unit: "unit" },
      { item: "Walkway pads to and around rooftop units and at the access point, welded or adhered to the membrane", unit: "linear ft" },
      { item: "Manufacturer final inspection and issuance of the no-dollar-limit system warranty (15, 20 or 25-year as specified) plus the contractor's workmanship warranty", unit: "fixed" },
      { item: "Daily cleanup, debris chute takedown, magnetic sweep at grade, demobilization and close-out documents", unit: "fixed" },
    ],
    avoid: [
      "'Roof system' as one line — insulation, cover board, membrane and flashings are separate lines",
      "membrane thickness or attachment method left unstated",
      "'Flashing' with no location or linear footage — parapets, walls, curbs and edge metal are different lines",
      "'Mobilization' with no crane, chute or safety scope in it",
      "HVAC disconnect and reset of rooftop units folded into the roofing price — the mechanical contractor's line",
      "a 'contingency' line in place of the conditional deck and wet-insulation lines",
    ],
    notes: [
      "Roof area and edge lengths come from the survey and the tapered layout; the tear-off layer count is from the core cuts",
      "Deck replacement and wet insulation beyond the scanned area are priced per sqft as found and billed as a change order",
      "Disconnect, lift and reset of rooftop units, gas lines and electrical are by the owner's mechanical and electrical contractors unless listed",
      "The manufacturer warranty is issued after their final inspection; corrective items from that inspection are included",
      "Work is priced for day-shift open-shop labor unless prevailing wage, union scale or night work is stated",
    ],
  },
  "siding-installation": {
    basis: "wall area in sqft net of openings with waste by profile; trim, corners, J-channel, starter and soffit in linear feet; openings flashed, vents and blocks each",
    steps: [
      { item: "Site measure and material takeoff: every elevation measured net of openings, siding profile, exposure and color chosen from samples, photos of the existing conditions and trim details", unit: "fixed" },
      { item: "Building permit and inspections at the jurisdiction's fee", unit: "fixed", when: "the jurisdiction requires a permit for re-siding" },
      { item: "Site protection: landscaping tarped, windows and AC condenser covered, walkways and deck protected, dumpster set on plywood", unit: "fixed" },
      { item: "Remove the existing siding, trim and house wrap to the sheathing, fasteners pulled, shutters, lights and downspouts detached and set aside", unit: "sqft" },
      { item: "Disposal: roll-off dumpster and landfill fees; asbestos-cement siding removed by a licensed abatement contractor where present", unit: "fixed" },
      { item: "Sheathing repair: rotted or delaminated OSB or plywood cut out and replaced, rotted studs and rim sistered", unit: "sqft", when: "rotted or delaminated sheathing is found behind the old siding" },
      { item: "Weather-resistive barrier: house wrap lapped shingle-style, seams taped, sealed at the sill and every penetration, with rain-screen furring where the product or climate calls for it", unit: "sqft" },
      { item: "Opening flashing: self-adhered flashing tape at sills, jambs and heads of every window and door, sill pan formed, metal drip cap over the head trim integrated into the house wrap", unit: "unit" },
      { item: "Continuous exterior insulation: 1 in. rigid foam or mineral wool board over the house wrap with furring strips into the studs", unit: "sqft", when: "the energy code or the owner adds exterior insulation" },
      { item: "Starter strip and corners: level starter at the base, outside and inside corner posts or 5/4 x 4 corner boards, plumb and flashed", unit: "linear ft" },
      { item: "Siding installed: fiber-cement lap (5/16 in., 7 in. exposure) blind-nailed 16 in. o.c. into studs with joint flashing at butt ends, or vinyl double-4 hung loose with 1/4 in. expansion gaps, or engineered wood lap, per the manufacturer", unit: "sqft" },
      { item: "Window and door trim: 5/4 x 4 fiber-cement or PVC casing, or J-channel with drip cap on vinyl, mitered and back-caulked", unit: "linear ft" },
      { item: "Soffit and fascia: vented aluminum or fiber-cement soffit panels with F-channel, and fascia wrap or 1x8 fascia boards", unit: "linear ft", when: "soffit and fascia are included in the scope" },
      { item: "Accessories: gable vents, dryer and bath exhaust hoods, light and outlet mounting blocks, hose-bib blocks, all flashed into the siding", unit: "unit" },
      { item: "Sealant: paintable elastomeric caulk at trim-to-siding joints, butt joints and penetrations, color matched", unit: "linear ft" },
      { item: "Field paint: cut ends primed, two coats of 100% acrylic exterior paint on siding and trim", unit: "sqft", when: "the siding is primed rather than factory-finished" },
      { item: "Detach and reset: light fixtures, shutters, house numbers, downspouts and hose bibs re-hung on the new siding with sealed mounting blocks", unit: "unit" },
      { item: "Final cleanup: magnetic nail sweep, debris hauled, walk-through of every elevation, manufacturer warranty registration", unit: "fixed" },
    ],
    avoid: [
      "a single 'Siding' line covering tear-off, house wrap, siding and trim",
      "trim, corners and J-channel priced as sqft — they are linear feet",
      "'Materials' with no product, profile or exposure named",
      "window replacement folded into a siding price — its own trade and line",
      "'Miscellaneous' or 'contingency' lines in place of the conditional sheathing line",
    ],
    notes: [
      "Wall area is measured net of openings from the site measure; waste is applied at the siding line by profile",
      "Sheathing and framing repair is priced per sqft and billed as found once the old siding is off",
      "Factory-finished products carry the manufacturer's finish warranty; field paint carries the painter's",
      "Gutters, windows and electrical relocations are separate trades unless listed",
    ],
  },
  "residential-siding-repair": {
    basis: "each repair area by its size in sqft and its matched trim in linear feet; assessment and access fixed; blocks and accessory pieces each",
    steps: [
      { item: "Damage assessment: every elevation walked, soft sheathing probed, moisture readings at the suspect areas, existing product and profile identified, photo report with the repair plan", unit: "fixed" },
      { item: "Material matching: matching profile, texture and color sourced from the manufacturer, salvage or custom milling, or the closest current match with a paint plan approved by the owner", unit: "fixed" },
      { item: "Access: ladders, pump jacks or a lift for upper-storey repair areas", unit: "fixed", when: "the repair area is above the first storey" },
      { item: "Remove the damaged siding pieces and trim, unlocking or cutting the surrounding courses without damaging them", unit: "sqft" },
      { item: "Sheathing and framing repair behind the damaged siding: rotted OSB or plywood replaced, rotted studs or rim sistered", unit: "sqft", when: "sheathing or framing behind the siding is rotted" },
      { item: "Weather barrier restored: new house wrap patch lapped into the existing barrier, flashing tape at any opening inside the repair area", unit: "sqft" },
      { item: "Matching siding pieces installed and interlocked with the existing courses, blind or face-nailed per the product, joints flashed", unit: "sqft" },
      { item: "Rotted trim, corner boards or window casing replaced with matching PVC, wood or fiber-cement pieces", unit: "linear ft", when: "trim or corner boards in the repair area are rotted" },
      { item: "Damaged or missing accessory pieces replaced: vent hoods, mounting blocks, J-channel and corner caps", unit: "unit" },
      { item: "Re-caulk butt joints, trim and penetrations in the repair area with color-matched elastomeric sealant", unit: "linear ft" },
      { item: "Prime and paint the new pieces and feather the finish into the adjacent siding for a match", unit: "sqft" },
      { item: "Re-fasten loose, popped or wind-lifted panels across the elevation and re-lock unzipped vinyl seams", unit: "fixed" },
      { item: "Haul-off of removed material, magnetic sweep below the work, photos of the finished repair", unit: "fixed" },
    ],
    avoid: [
      "a 'Siding repair' line with no location, size or product",
      "a whole-elevation re-side scoped as a repair",
      "'Paint touch-up' with no area — the blend area is measured",
      "'Rot repair' as a lump sum with no sqft",
    ],
    notes: [
      "Repair areas are measured at the assessment; hidden sheathing damage found once pieces are off is priced per sqft as found",
      "Color match on weathered siding is as close as current product and paint allow; a full-elevation repaint is quoted separately",
      "Discontinued profiles are matched from salvage or custom milling where available; lead time is stated",
    ],
  },
  "gutter-installation": {
    basis: "gutters and downspouts in linear feet by profile and size; miters, outlets, elbows and hangers each; drain lines in linear feet",
    steps: [
      { item: "Measure and layout: fascia runs measured, downspout locations and discharge points set, fall of 1/4 in. per 10 ft toward the outlets, profile and color chosen from samples", unit: "fixed" },
      { item: "Remove the existing gutters and downspouts, hangers pulled, holes sealed, metal recycled", unit: "linear ft", when: "existing gutters are being replaced" },
      { item: "Fascia repair: rotted or split fascia replaced with primed 1x6 or 2x6 wood or PVC board before the new gutter goes up", unit: "linear ft", when: "the fascia is rotted or split behind the old gutters" },
      { item: "Fascia wrap: .019 in. aluminum coil bent on site over the fascia, color matched to the gutter", unit: "linear ft", when: "fascia wrap is included" },
      { item: "Seamless gutters: 5 in. or 6 in. K-style .032 in. aluminum (half-round, steel or copper where specified) roll-formed on site in continuous lengths and hung to the set fall", unit: "linear ft" },
      { item: "Hidden hangers with screws into the rafter tails every 24 in., every 16 in. in snow and ice regions", unit: "unit" },
      { item: "Miters and end caps: inside and outside box miters or strip miters, end caps sealed with gutter-grade sealant", unit: "unit" },
      { item: "Downspouts: 2x3 in. or 3x4 in. aluminum, strapped every 10 ft, routed to the discharge point", unit: "linear ft" },
      { item: "Outlets, elbows and straps: outlet tubes cut and sealed into the gutter, A and B elbows at the offsets and the discharge", unit: "unit" },
      { item: "Gutter apron flashing tucked under the shingles and into the gutter so runoff cannot run behind it", unit: "linear ft", when: "the roof has no drip edge or water has been running behind the gutter" },
      { item: "Gutter guards: stainless micro-mesh or perforated aluminum screens screwed to the gutter lip, or a reverse-curve system where specified", unit: "linear ft", when: "gutter guards are included" },
      { item: "Underground drain lines: 4 in. corrugated or SDR-35 PVC from the downspouts to daylight, trench cut and backfilled", unit: "linear ft", when: "downspouts are routed underground" },
      { item: "Pop-up emitters, catch basins or a dry well at the discharge, and splash blocks or extensions where lines stay above grade", unit: "unit", when: "the discharge needs an emitter, basin, dry well or extension" },
      { item: "Water test: every run flooded from the roof to confirm fall, flow and sealed joints, adjustments made", unit: "fixed" },
      { item: "Cleanup: debris and scrap hauled, metal recycled, walk-through of every run, workmanship warranty issued", unit: "fixed" },
    ],
    avoid: [
      "gutters priced as sqft — gutters and downspouts are linear feet",
      "'Gutters' as one line with no size, gauge or profile",
      "'Accessories' with no miters, outlets or elbows counted",
      "roof drip edge or shingle work folded into the gutter price",
      "'Drainage' with no pipe size, length or discharge named",
    ],
    notes: [
      "Gutter and downspout lengths are measured on site; sizes follow the roof area and the rainfall rate for the region",
      "Fascia repair is per linear ft as found once the old gutters are down",
      "Underground drain lines assume diggable soil; rock, roots or utility conflicts are priced as a change",
      "Guard performance depends on the tree cover; seasonal cleaning is not included",
    ],
  },
  "window-door": {
    basis: "windows and doors each by size, type and installation method; exterior and interior casing, jamb extensions and sealant in linear feet",
    steps: [
      { item: "Field measure: every opening measured at three points for width and height, rough opening and wall depth checked, egress, tempered-glass and U-factor requirements noted, product order confirmed against the schedule", unit: "fixed" },
      { item: "Permit and inspection at the jurisdiction's fee", unit: "fixed", when: "the jurisdiction requires a permit for window or door replacement" },
      { item: "Interior and exterior protection: floors, furniture and blinds covered, plants tarped, dust barriers at the work rooms", unit: "fixed" },
      { item: "Lead-safe work practices (EPA RRP): containment, HEPA cleanup and certified crew on a pre-1978 home", unit: "fixed", when: "the home was built before 1978" },
      { item: "Remove the existing windows and doors: sashes, frames, stops and trim pulled, opening cleaned to the framing", unit: "unit" },
      { item: "Rough-opening repair: rotted sill, jack studs or sheathing replaced and the opening re-squared", unit: "unit", when: "rot or damage is found at an opening" },
      { item: "Sill pan and flashing at every opening: sloped flexible or preformed sill pan, self-adhered jamb flashing, head flashing lapped under the house wrap", unit: "unit" },
      { item: "Windows supplied and set: vinyl, fiberglass or clad-wood units with double-pane low-E argon glass meeting the ENERGY STAR U-factor and SHGC for the climate zone, shimmed plumb and square, fins fastened per the manufacturer", unit: "unit" },
      { item: "Exterior doors supplied and hung: pre-hung fiberglass or steel entry, sliding or French patio door, threshold bedded in sealant, shimmed at hinges and strike, 3 in. screws into the framing", unit: "unit" },
      { item: "Insulate and seal each opening: low-expansion foam at the shim gap, backer rod and sealant at the interior line", unit: "unit" },
      { item: "Exterior trim: 5/4 PVC or fiber-cement casing, brickmould, or aluminum coil wrap over the existing trim, drip cap at the head", unit: "linear ft" },
      { item: "Interior finish carpentry: jamb extensions, stool and apron, casing to match the existing profile, nailed, filled and caulked", unit: "linear ft" },
      { item: "Hardware: locksets, deadbolts and handle sets on doors, sash locks, screens and window openers, keyed alike where asked", unit: "unit" },
      { item: "Exterior sealant: color-matched polyurethane at the trim-to-siding and trim-to-frame joints", unit: "linear ft" },
      { item: "Paint or stain of the new interior trim, two coats, to match the existing", unit: "linear ft", when: "finishing of the new trim is included" },
      { item: "Adjustment and test: doors swung and latched, windows tilted and locked, weatherstrip checked, screens fitted, owner shown the operation", unit: "fixed" },
      { item: "Haul-away of the old units and debris, cleanup of every opening, manufacturer warranty registration", unit: "fixed" },
    ],
    avoid: [
      "windows or doors priced as sqft — each unit is a count",
      "'Install' with no size, product or glass performance named",
      "trim and casing folded into the unit price — they are linear feet",
      "siding, stucco or drywall patching beyond the trim line without a line for it",
      "'Materials' or 'Hardware' with nothing counted",
    ],
    notes: [
      "Unit sizes and counts come from the field measure; custom units are ordered after the measure and the lead time is stated",
      "Rot at an opening is priced per opening as found once the old unit is out",
      "Egress and tempered-glass requirements are met at bedrooms, stairs and tubs per the building code",
      "Alarm sensors, blinds and smart locks are reinstalled where practical but not warranted",
    ],
  },
  "window-replacement": {
    basis: "windows each by size, style and installation method (insert or full-frame); exterior wrap and interior trim in linear feet",
    steps: [
      { item: "In-home measure and product specification: each opening measured, insert or full-frame decided per opening, glazing package chosen (double or triple pane, low-E, argon, NFRC U-factor 0.27 or better in cold zones), grids, colors, tempered locations", unit: "fixed" },
      { item: "Permit and energy-code inspection at the jurisdiction's fee", unit: "fixed", when: "the jurisdiction requires a permit for window replacement" },
      { item: "EPA lead-safe (RRP) containment, HEPA cleanup and certified crew", unit: "fixed", when: "the home was built before 1978" },
      { item: "Interior protection: blinds and treatments taken down, furniture moved and covered, floors protected at every window", unit: "fixed" },
      { item: "Insert removal: sashes, balances and stops removed leaving the sound existing frame, pocket cleaned and the sill checked for rot", unit: "unit", when: "the existing frames are sound and insert replacement is specified" },
      { item: "Full-frame removal: whole window, frame and exterior trim removed to the rough opening", unit: "unit", when: "full-frame replacement is specified" },
      { item: "Rough-opening repair: rotted sill, jamb studs or sheathing replaced before the new unit goes in", unit: "unit", when: "rot is found once the old window is out" },
      { item: "Full-frame flashing: sloped sill pan, self-adhered jamb flashing and head flashing lapped into the house wrap", unit: "unit", when: "full-frame replacement is specified" },
      { item: "Replacement windows supplied and set: welded vinyl or fiberglass frames, double-pane low-E argon glass, shimmed square, screwed through the jambs, NFRC labels left on for the inspection", unit: "unit" },
      { item: "Perimeter insulation and seal: low-expansion foam at the gap, backer rod and interior sealant", unit: "unit" },
      { item: "Exterior finish: aluminum coil wrap over the exterior frame and trim, or new PVC casing, sealed with color-matched polyurethane", unit: "linear ft" },
      { item: "Interior finish: stops, jamb extensions and casing re-set or replaced to match the existing, caulked and ready for paint", unit: "linear ft" },
      { item: "Screens, sash locks, grids and tilt-in operation checked on every unit, hardware adjusted", unit: "unit" },
      { item: "Haul-away of the old windows, glass and debris", unit: "fixed" },
      { item: "Final cleanup of every room, walk-through, manufacturer and glass-seal warranty registration", unit: "fixed" },
    ],
    avoid: [
      "windows priced as sqft or 'per opening' with no size or style",
      "insert and full-frame priced the same with the method unstated",
      "'Trim' or 'Wrap' with no linear footage",
      "a whole-house count hidden in one 'Windows' line — each size and style is its own line",
    ],
    notes: [
      "Insert replacement keeps the existing frame and loses a little glass area; full-frame restores the original opening and is priced per opening",
      "Rot found once the old window is out is priced per opening as found",
      "Custom sizes are ordered after the measure; the lead time is stated and the deposit covers the order",
      "Interior paint of new trim is excluded unless listed",
    ],
  },
  "garage-door": {
    basis: "doors, openers and hardware sets each by size and spec; jamb repair, trim and weather seal in linear feet",
    steps: [
      { item: "Site measure: opening width and height, headroom, side room and backroom, header and floor level checked, outlet location noted, door style, insulation R-value, windows and color chosen", unit: "fixed" },
      { item: "Remove the existing door, tracks, springs (torsion springs unwound with winding bars) and the old opener, all hauled away", unit: "unit" },
      { item: "Jamb and header repair: rotted jambs replaced with pressure-treated lumber or PVC-wrapped stock, a spring-anchor pad added where the header cannot hold the torsion bracket", unit: "linear ft", when: "the jambs or header are rotted or unsuitable for the spring anchor" },
      { item: "Door sections supplied: 25-gauge steel with 2 in. polyurethane insulation (R-16 or higher), or a 3-layer, carriage-style or full-view aluminum door as chosen, with windows and decorative hardware", unit: "unit" },
      { item: "Track and hardware: 2 in. galvanized vertical and horizontal tracks, 14-gauge hinges, ball-bearing nylon rollers, reinforcing struts on doors over 12 ft, perforated angle hangers", unit: "unit" },
      { item: "Torsion spring system: cycle-rated springs (10,000 or 25,000 cycles), cable drums, cables and bearing plates, wound to balance the door", unit: "unit" },
      { item: "Weather seal: bottom astragal in an aluminum retainer, PVC stop moulding with vinyl weatherstrip at the jambs and header", unit: "linear ft" },
      { item: "Opener supplied and installed: belt, chain or wall-mount jackshaft drive, 3/4 HP or 1-1/4 HP DC motor, battery backup where code requires, Wi-Fi control, two remotes, wall console and keypad", unit: "unit" },
      { item: "Safety setup per UL 325: photo eyes at 6 in. off the floor, auto-reverse force and travel limits set and tested, emergency release shown to the owner", unit: "unit" },
      { item: "Ceiling outlet: dedicated receptacle within 3 ft of the opener on a GFCI-protected circuit", unit: "unit", when: "no outlet is within reach of the opener" },
      { item: "Wind-rated door and bracing package per the local wind-load requirement", unit: "unit", when: "the jurisdiction requires a wind-rated garage door" },
      { item: "Exterior trim: PVC garage-door jamb wrap and header trim, sealed and color matched", unit: "linear ft", when: "new exterior trim is included" },
      { item: "Balance, adjustment, lubrication and a full operation test, owner instruction, cleanup and manufacturer warranty registration", unit: "fixed" },
    ],
    avoid: [
      "'Garage door' as one line with no size, gauge or insulation value",
      "the opener folded into the door price — it is its own line",
      "'Springs' or 'Hardware' with no cycle rating or spec",
      "electrical circuit work beyond the ceiling outlet — the electrician's line",
    ],
    notes: [
      "Door size and headroom are confirmed at the site measure; low-headroom tracks and jackshaft openers are specified where headroom is short",
      "Jamb and header repair is priced per linear ft as found when the old door comes down",
      "Springs are rated by cycles, not years; the workmanship warranty and the manufacturer's door and opener warranties are stated separately",
    ],
  },
  decking: {
    basis: "deck area in sqft for framing and decking; ledger, beams, railing, fascia and skirting in linear feet; footings, posts and stair risers each",
    steps: [
      { item: "Design, permit and layout: deck plan with the footing layout, framing plan and railing detail submitted for the building permit; footing, framing and final inspections; 811 utility locate before digging", unit: "fixed" },
      { item: "Demolition of the existing deck: decking, framing, railing and footings removed and hauled away", unit: "sqft", when: "an existing deck is being replaced" },
      { item: "Ground prep under the deck: grade sloped away from the house, landscape fabric and washed gravel for weed and moisture control", unit: "sqft" },
      { item: "Footings: dug to frost depth, 12 in. tube forms or bell footings, 3,000-psi concrete, galvanized standoff post bases set in the wet concrete", unit: "unit" },
      { item: "Helical piers driven to torque with brackets in place of dug footings", unit: "unit", when: "soil, water or access prevents dug footings" },
      { item: "Ledger: 2x10 pressure-treated ledger fastened to the rim with 1/2 in. structural screws or through-bolts staggered 16 in. o.c., self-adhered flashing and a metal ledger cap tucked behind the siding", unit: "linear ft" },
      { item: "Posts: 6x6 pressure-treated posts on the standoff bases, plumbed and braced, notched or capped for the beam", unit: "unit" },
      { item: "Beams: doubled or tripled 2x10 or 2x12 pressure-treated beams on post caps, spans per the plan", unit: "linear ft" },
      { item: "Joist framing: 2x8 or 2x10 pressure-treated joists at 16 in. o.c. (12 in. for diagonal or composite decking), galvanized hangers, rim joist, mid-span blocking, joist tape over every joist top", unit: "sqft" },
      { item: "Decking laid: capped composite or PVC boards (1 in. x 5.5 in.) with hidden fasteners and a picture-frame border, or 5/4 x 6 cedar or pressure-treated boards face-screwed with color-matched screws", unit: "sqft" },
      { item: "Stairs: pressure-treated stringers at 12 in. o.c., closed risers and matching treads, graspable handrail, concrete landing pad at grade", unit: "unit" },
      { item: "Railing: aluminum or composite railing 36 in. high with balusters under 4 in. apart, posts through-bolted to the rim with blocking, stair rail with returns", unit: "linear ft" },
      { item: "Fascia and skirting: composite fascia over the rim joists and beam ends, lattice or board skirting with an access panel", unit: "linear ft" },
      { item: "Deck lighting: low-voltage post-cap and riser lights, transformer and timer, wiring concealed in the framing", unit: "unit", when: "deck lighting is included" },
      { item: "Stain and seal: penetrating oil-based stain on all wood decking and railing, two coats", unit: "sqft", when: "the decking or railing is wood" },
      { item: "Under-deck drainage: membrane or trough system between the joists draining to a gutter for a dry patio below", unit: "sqft", when: "the area under an elevated deck is to stay dry" },
      { item: "Final inspection, cleanup, haul-off of cutoffs and packaging, manufacturer warranty registration for the decking and railing", unit: "fixed" },
    ],
    avoid: [
      "a single 'Deck' line covering framing, decking and railing",
      "railing priced as sqft — railing is linear feet; stairs are counted",
      "'Lumber' or 'Materials' with no sizes or species",
      "footings hidden inside the framing price — each footing is a line",
      "'Contingency' in place of the conditional demolition and pier lines",
    ],
    notes: [
      "Deck area, railing length and stair count come from the approved plan; footing depth follows the local frost line",
      "Ledger attachment assumes a sound rim joist; rot found at the rim is repaired as a change order",
      "Composite colors and railing styles are ordered after the deposit; the lead time is stated",
      "Permit and inspection fees are passed through at the jurisdiction's rate; engineering for spans beyond the code tables is extra",
    ],
  },
  "patio-cover": {
    basis: "cover area in sqft for the roof structure and roofing; ledger, beams, fascia and gutter in linear feet; posts, footings and fixtures each",
    steps: [
      { item: "Design and permit: engineered plan for post, footing and beam sizes at the local snow and wind loads, HOA approval, building permit and inspections", unit: "fixed" },
      { item: "Utility locate and layout: 811 ticket, post locations staked, overhead lines and setbacks checked", unit: "fixed" },
      { item: "Demolition of the existing cover or awning, hauled away", unit: "sqft", when: "an existing cover or awning is being replaced" },
      { item: "Footings: 18 to 24 in. diameter to frost depth with 3,000-psi concrete and post bases, or posts core-drilled and epoxy-anchored into the existing slab", unit: "unit" },
      { item: "House attachment: 2x8 or 2x10 ledger lagged to the rim, flashed with a metal cap into the siding or a cut reglet in stucco", unit: "linear ft", when: "the cover attaches to the house" },
      { item: "Posts: 6x6 cedar or pressure-treated posts, or 4x4 aluminum posts, plumbed on standoff bases", unit: "unit" },
      { item: "Beams: doubled 2x10 or 6x10 cedar or glulam beams, or aluminum box beams, on post caps or brackets", unit: "linear ft" },
      { item: "Roof structure: 2x6 rafters at 24 in. o.c. for a solid cover, or 2x8 rafters with 2x2 lattice at 4 in. o.c. for a pergola, with decorative rafter tails", unit: "sqft" },
      { item: "Solid roofing: plywood deck, synthetic underlayment and shingles matched to the house, or 3 in. insulated aluminum roof panels, or polycarbonate panels", unit: "sqft", when: "the cover is solid-roofed" },
      { item: "Roof tie-in flashing where the cover meets the house wall or roof, step and counter flashed", unit: "linear ft", when: "the cover attaches to the house" },
      { item: "Fascia, trim and a gutter with downspout along the cover's low edge", unit: "linear ft" },
      { item: "Electrical: fan and light boxes, switch and a GFCI outlet run in conduit from the house by a licensed electrician", unit: "unit", when: "lighting, fans or outlets are included" },
      { item: "Ceiling fans and light fixtures supplied and hung, wet or damp rated", unit: "unit", when: "fans or lights are included" },
      { item: "Stain, seal or paint of the wood structure, two coats", unit: "sqft", when: "the structure is wood" },
      { item: "Screens, shade cloth or privacy lattice walls between posts", unit: "sqft", when: "screening or privacy walls are included" },
      { item: "Final inspection, cleanup and haul-off of cutoffs and packaging", unit: "fixed" },
    ],
    avoid: [
      "'Pergola' or 'Patio cover' as one line with no size, material or roofing",
      "posts and footings folded into the beam price — they are counted",
      "electrical run and fixtures lumped as 'Electrical'",
      "paving or a new patio slab under the cover without its own line — another trade",
    ],
    notes: [
      "Cover size and post count follow the engineered plan; footings go below the frost line",
      "Attachment to the house assumes a sound rim and flashable wall; a stucco reglet or masonry anchors are priced as found",
      "Electrical work is by a licensed electrician and permitted separately where required",
      "Wood is stained after it dries to the manufacturer's moisture level; a return visit is included",
    ],
  },
  "carport-builder": {
    basis: "roof area in sqft for the frame and roofing; posts and footings each; beams, trim and gutter in linear feet; enclosure panels in sqft",
    steps: [
      { item: "Design and permit: size, vehicle count and clearance height set, engineered drawings for the local snow and wind loads and setbacks, HOA approval, permit and inspections", unit: "fixed" },
      { item: "Utility locate and layout: 811 ticket, post locations set, overhead clearance and drainage checked", unit: "fixed" },
      { item: "Demolition of the existing carport or awning, hauled away", unit: "sqft", when: "an existing carport or awning is being replaced" },
      { item: "Concrete pad: 4 in. 3,000-psi slab over compacted gravel with wire mesh or fiber, sloped to drain", unit: "sqft", when: "a new slab or pad is part of the scope" },
      { item: "Footings: 12 to 18 in. diameter to frost depth with 3,000-psi concrete and post bases or anchor bolts, or expansion anchors into an existing slab", unit: "unit" },
      { item: "Columns: 6x6 pressure-treated posts, or 2.5 in. square 14-gauge galvanized steel tube, plumbed and anchored", unit: "unit" },
      { item: "Headers and beams: steel C-channel or doubled 2x12 headers with knee braces for lateral stability", unit: "linear ft" },
      { item: "Roof frame: steel bows at 5 ft o.c. with hat-channel purlins, or 2x6 rafters at 24 in. o.c. with 2x4 purlins", unit: "sqft" },
      { item: "Roofing: 29-gauge or 26-gauge galvanized or painted metal panels screwed with neoprene-washer screws, ridge cap and closures, or plywood and shingles matched to the house", unit: "sqft" },
      { item: "Trim and gutter: eave and rake trim, gutter and downspouts on the low side", unit: "linear ft" },
      { item: "Enclosure panels: metal side or end panels, gable ends, or a storage lean-to with a door", unit: "sqft", when: "side panels, gable ends or a storage enclosure are included" },
      { item: "Lighting: LED fixture with motion sensor and a GFCI outlet by a licensed electrician", unit: "unit", when: "lighting or an outlet is included" },
      { item: "Paint or stain of the wood frame, two coats", unit: "sqft", when: "the structure is wood" },
      { item: "Final inspection, cleanup, haul-off of cutoffs and packaging", unit: "fixed" },
    ],
    avoid: [
      "'Carport kit' as one line with no size, gauge or roof panel spec",
      "footings and columns folded into the frame price",
      "a driveway or slab without its own line — flatwork is measured and priced",
      "'Electrical' with no fixture or outlet counted",
    ],
    notes: [
      "Size and clearance follow the vehicles named in the brief; the roof pitch and loads follow the engineered drawings",
      "Footings assume diggable soil; rock or a buried slab is priced as found",
      "Steel kits carry the manufacturer's panel warranty; installation carries the workmanship warranty",
    ],
  },
  "stucco-eifs": {
    basis: "wall area in sqft net of openings by system (three-coat, one-coat or EIFS); weep screed, casing beads, control joints, foam trim and sealant joints in linear feet",
    steps: [
      { item: "Substrate inspection and moisture testing, then a color and texture mockup on site for the owner's approval", unit: "fixed" },
      { item: "Permit and inspections at the jurisdiction's fee, including the lath inspection before the scratch coat", unit: "fixed" },
      { item: "Protection and staging: windows, doors, roofing, walkways and plants masked and tarped; scaffolding or staging set at every elevation", unit: "fixed" },
      { item: "Remove the existing stucco or siding to the sheathing, lath and fasteners pulled, debris hauled", unit: "sqft", when: "existing stucco or siding is being removed" },
      { item: "Sheathing repair: rotted or delaminated sheathing cut out and replaced, framing sistered where soft", unit: "sqft", when: "rotted sheathing is found under the old cladding" },
      { item: "Weather-resistive barrier: two layers of Grade D 60-minute paper, or house wrap with a paper bond break, lapped shingle-style; self-adhered flashing at openings, kickout flashing where a roof meets the wall", unit: "sqft" },
      { item: "Accessories: 26-gauge galvanized weep screed at the base (4 in. above grade, 2 in. above paving), casing beads at openings, corner aid, and control joints per ASTM C1063 panel limits", unit: "linear ft" },
      { item: "Lath: 2.5 lb self-furring galvanized expanded metal lath or 17-gauge woven wire, fastened 7 in. o.c. into the studs, lapped at joints", unit: "sqft", when: "the system is cement stucco rather than EIFS" },
      { item: "Scratch coat: 3/8 in. cement plaster pressed through the lath and scored horizontally, moist-cured 48 hours", unit: "sqft", when: "the system is cement stucco rather than EIFS" },
      { item: "Brown coat: 3/8 in. cement plaster rodded straight and floated, moist-cured 7 days before the finish", unit: "sqft", when: "the system is cement stucco rather than EIFS" },
      { item: "EIFS: EPS insulation board adhered or mechanically fastened over a drainage plane, rasped flat, fiberglass mesh embedded in the polymer base coat, per the manufacturer's drainage EIFS details", unit: "sqft", when: "the system is EIFS" },
      { item: "Finish coat: 1/8 in. acrylic elastomeric finish or integrally colored cement color coat in the approved texture (sand, lace, dash or smooth)", unit: "sqft" },
      { item: "Foam trim, bands and quoins: EPS shapes with base coat and mesh, finished to match the walls", unit: "linear ft", when: "foam trim, bands or quoins are included" },
      { item: "Sealant joints: backer rod and polyurethane or silicone sealant at windows, doors, penetrations and control joints", unit: "linear ft" },
      { item: "Elastomeric coating over the cement finish, two coats in the chosen color", unit: "sqft", when: "a painted finish is specified over the cement color coat" },
      { item: "Cleanup: masking removed, overspray cleaned from glass and paving, scaffold struck, debris hauled", unit: "fixed" },
    ],
    avoid: [
      "'Stucco' as one line — paper, lath, scratch, brown and finish are separate coats and lines",
      "control joints, screed and casing bead folded into the sqft price — they are linear feet",
      "'Prep' with no substrate or moisture work named",
      "windows, doors or gutters replaced inside a stucco price — other trades",
      "EIFS priced as stucco with the drainage plane and mesh unstated",
    ],
    notes: [
      "Wall area is measured net of openings; texture and color are per the approved mockup",
      "Hidden sheathing or framing damage is priced per sqft as found once the old cladding is off",
      "Cure times between coats are weather-dependent; the schedule states them",
      "Hairline checking in cement stucco is normal and not a defect; sealant joints are maintenance items",
    ],
  },
  fencing: {
    basis: "fence run in linear feet by style and height net of gate openings; posts, gates and slope steps each; post concrete in cu yards; tear-out in linear feet; stain in sqft",
    steps: [
      { item: "Layout: property pins located (a survey recommended where they are missing), 811 utility locate, HOA rules checked, the line staked and string-lined, gate openings and corner posts marked", unit: "fixed" },
      { item: "Fence permit and inspection at the jurisdiction's fee", unit: "fixed", when: "the jurisdiction or HOA requires a fence permit" },
      { item: "Tear-out of the existing fence: panels, posts and concrete footings pulled and hauled away", unit: "linear ft", when: "an existing fence is being replaced" },
      { item: "Clear the fence line: brush, vines and roots cleared 2 ft each side of the line", unit: "linear ft", when: "the line is overgrown" },
      { item: "Line posts: holes augered 8 to 12 in. in diameter to below frost depth (one third of the post height, 24 in. minimum), 4x4 pressure-treated, 5x5 vinyl or 2-3/8 in. steel posts set at 6 or 8 ft o.c.", unit: "unit" },
      { item: "Corner, end and gate posts: heavier stock (6x6 wood, 3 in. steel, aluminum-stiffened vinyl) set deeper with extra concrete", unit: "unit" },
      { item: "Concrete: 3,000-psi concrete around every post, crowned at grade to shed water", unit: "cu yards" },
      { item: "Rails and pickets: 2x4 pressure-treated rails (two or three per bay) with 1x6 cedar or pressure-treated pickets, dog-ear or flat top, ring-shank nailed or screwed, cap and trim boards where specified", unit: "linear ft", when: "the fence is stick-built wood" },
      { item: "Prefabricated panels: vinyl, composite, aluminum or ornamental steel panels set between the posts with brackets or routed posts", unit: "linear ft", when: "the fence is a panel system" },
      { item: "Chain link: 1-5/8 in. top rail, 9-gauge 2 in. mesh fabric stretched and tied, tension bars and bands at every terminal post, bottom tension wire", unit: "linear ft", when: "the fence is chain link" },
      { item: "Gates: 4 ft walk gates and 10 to 12 ft double drive gates, wood gates over 4 ft built on a welded steel frame, prefab panel gates on vinyl and metal systems", unit: "unit" },
      { item: "Gate hardware: heavy-duty hinges, latch, drop rod and center stop on doubles, self-closing pool-code hardware or a keypad operator where specified", unit: "unit" },
      { item: "Slope steps: extended posts with panels stepped or racked to follow the grade", unit: "unit", when: "the line runs across a slope" },
      { item: "Post caps: pyramid, flat or solar caps on every post, dome caps on terminal posts", unit: "unit" },
      { item: "Stain and seal: penetrating stain, two coats, both faces", unit: "sqft", when: "the wood fence is stained or sealed" },
      { item: "Cleanup: hole spoils spread or hauled, cutoffs and packaging removed, magnetic sweep along the line", unit: "fixed" },
    ],
    avoid: [
      "fence priced as sqft — a fence run is linear feet, posts and gates are counted",
      "'Fence' as one line with no style, height or post spacing",
      "gates and gate hardware folded into the per-foot price",
      "'Concrete' with no volume — post concrete is cu yards",
      "a retaining wall or grading under the fence without its own line — another trade",
    ],
    notes: [
      "The run is measured along the staked line net of gate openings; height and style are per the brief",
      "Property lines are the owner's responsibility; a survey is recommended where pins are missing",
      "Post depth follows the local frost line; rock or a buried obstruction at a hole is priced as found",
      "Wood is stained after it dries to the stain maker's moisture level; a return visit is included",
    ],
  },
  "residential-fence-repair": {
    basis: "each repair by its size: posts and gates each, rails and sections in linear feet, cleaning and stain in sqft",
    steps: [
      { item: "Inspection: every post rocked and probed at grade, rails and pickets checked, gate sag and latch checked, photo report listing each repair", unit: "fixed" },
      { item: "Rotted or leaning posts replaced: post cut out, old concrete footing broken out and removed, new 4x4 or 6x6 pressure-treated or steel post set plumb in fresh 3,000-psi concrete", unit: "unit" },
      { item: "Post stabilization with a galvanized steel repair bracket or sleeve driven beside the sound post", unit: "unit", when: "the post is sound above grade and a bracket repair is chosen over replacement" },
      { item: "Broken or sagging rails replaced with pressure-treated 2x4 rails on hangers or toe-screwed", unit: "linear ft" },
      { item: "Broken, warped or missing pickets replaced with matching species and profile, fastened with ring-shank nails or screws", unit: "linear ft" },
      { item: "Whole sections replaced: vinyl, composite or ornamental panels, or chain-link fabric, matched to the existing", unit: "linear ft", when: "a full section is beyond repair" },
      { item: "Gate repair: gate re-hung, sag corrected with an anti-sag kit or new hinges, latch replaced, gate rebuilt where the frame is rotted", unit: "unit" },
      { item: "Chain-link re-stretch: fabric re-tensioned, tension bands and ties replaced, bent top rail replaced", unit: "linear ft", when: "the fence is chain link" },
      { item: "Pressure wash and wood brightener before refinishing", unit: "sqft", when: "refinishing is included" },
      { item: "Stain or seal to match the existing color, two coats", unit: "sqft", when: "refinishing is included" },
      { item: "Haul-away of the removed posts, concrete and boards, cleanup along the line", unit: "fixed" },
    ],
    avoid: [
      "'Fence repair' with no post count or footage",
      "a full replacement scoped as a repair",
      "'Labor' and 'Materials' with nothing named",
      "a new gate priced as a 'repair' with no hardware listed",
    ],
    notes: [
      "Post and section counts come from the inspection; posts found rotted below grade during the work are priced per post",
      "Matching weathered wood is approximate; new pickets weather to match in a season",
      "The neighbor's side of a shared fence is worked from the owner's side unless access is arranged",
    ],
  },
  skylight: {
    basis: "skylights each by size, type and whether the opening is new or existing; light shaft framing and finishing in sqft; accessories each",
    steps: [
      { item: "Site survey: roof pitch and material, rafter spacing and layout, attic obstructions, unit size and type chosen (deck-mounted fixed, solar venting or curb-mounted), glazing and location marked on the roof and ceiling", unit: "fixed" },
      { item: "Building permit and inspection at the jurisdiction's fee", unit: "fixed", when: "the jurisdiction requires a permit for a new roof opening" },
      { item: "Interior protection: floors and furniture covered, dust barrier at the room, attic insulation pulled back and bagged", unit: "fixed" },
      { item: "Remove the existing skylight, flashing and cracked dome, opening cleaned to the curb or deck", unit: "unit", when: "an existing skylight is being replaced" },
      { item: "Roof opening cut: shingles cut back, deck cut to the template, rafter cut where the unit spans a bay", unit: "unit", when: "a new opening is being cut" },
      { item: "Opening framed: doubled headers hung on the rafters, rafters sistered, curb built from 2x6 where a curb-mounted unit is used", unit: "unit", when: "a new opening is being cut or the size changes" },
      { item: "Skylight supplied and set: deck-mounted fixed or solar-powered venting unit with laminated low-E glass and a rain sensor, 10-year no-leak warranty, fastened per the manufacturer", unit: "unit" },
      { item: "Flashing: manufacturer's step and head flashing kit for the roof type, self-adhered underlayment lapped around the opening, shingles re-woven and sealed", unit: "unit" },
      { item: "Light shaft: 2x4 framed shaft from the roof to the ceiling, splayed or straight, insulated with R-30 batts, drywalled and taped", unit: "sqft" },
      { item: "Shaft finish: corner bead, finish coats, primer and two coats of paint to match the ceiling, trim at the ceiling opening", unit: "sqft" },
      { item: "Accessories: solar-powered blinds, remote control and insect screen", unit: "unit", when: "blinds or a remote are included" },
      { item: "Hose test of the flashing, insulation restored, debris hauled and the room cleaned, warranty registration", unit: "fixed" },
    ],
    avoid: [
      "'Skylight' as one line with no size, type or flashing",
      "the light shaft folded into the unit price — it is framed, insulated and finished by the sqft",
      "'Roofing repair' with no re-woven shingle scope",
      "a whole-roof replacement scoped inside a skylight estimate",
    ],
    notes: [
      "Unit size follows the rafter spacing; a unit that spans a rafter needs the framing line",
      "Replacements reuse the existing opening; a size change is priced as a new opening",
      "Interior paint matching is to the shaft only; ceiling repainting beyond it is excluded",
    ],
  },
  "sun-tunnel": {
    basis: "tubular skylights each by tube diameter and roof type; extension tubing in linear feet; accessories each",
    steps: [
      { item: "Layout: ceiling location chosen for the room, attic checked for trusses, ducts and wiring on the route, 10 in. or 14 in. tube chosen by room size, roof pitch and material noted", unit: "fixed" },
      { item: "Interior protection: drop cloths under the ceiling cut, furniture covered, attic insulation pulled back at the route", unit: "fixed" },
      { item: "Ceiling opening: hole cut with the template between the joists, ceiling ring set and sealed", unit: "unit" },
      { item: "Roof opening: shingles or tiles lifted, deck cut to the template, self-adhered underlayment around the opening", unit: "unit" },
      { item: "Roof dome and flashing: acrylic dome on the manufacturer's flashing for the pitch and roof type (shingle, tile, metal or flat), sealed and the roofing re-laid around it", unit: "unit" },
      { item: "Tubing: rigid highly reflective tube sections joined and taped from the roof to the ceiling, extension tubes on runs over 4 ft, angle adapters at bends", unit: "linear ft" },
      { item: "Accessories: daylight dimmer, LED night-light kit or bath ventilation kit fitted in the tube", unit: "unit", when: "a dimmer, light kit or vent kit is included" },
      { item: "Ceiling diffuser: frosted or prismatic lens and trim ring snapped in and sealed, insulation restored around the tube", unit: "unit" },
      { item: "Hose test of the flashing, debris hauled, ceiling and floor cleaned", unit: "fixed" },
    ],
    avoid: [
      "'Solar tube' as one line with no diameter, run length or roof type",
      "tubing priced 'each' with no length — extension tube is linear feet",
      "electrical circuit work for a light kit without the electrician's line",
    ],
    notes: [
      "Tube diameter and run length are set at the layout; a run over 20 ft or with two bends loses light and is stated",
      "Tile and metal roofs need the matching flashing and are stated in the unit line",
      "The light kit is low-voltage; a new circuit is by a licensed electrician",
    ],
  },
  "attic-ventilation": {
    basis: "vents each by type and net free area; ridge and soffit vents in linear feet; baffles each; sealing, treatment and insulation in sqft",
    steps: [
      { item: "Attic assessment: attic floor measured, existing intake and exhaust net free area counted against the IRC 1:150 rule, moisture, frost, mold and blocked soffits photographed, vent plan written", unit: "fixed" },
      { item: "Soffit bays opened: insulation pulled back from the eaves and rafter baffles stapled in every bay to keep the intake path clear", unit: "unit" },
      { item: "Soffit intake: continuous aluminum or vinyl strip vent cut into the soffit, or 16x8 in. under-eave vents cut in and screened", unit: "linear ft" },
      { item: "Ridge vent: 1 in. slot cut each side of the ridge, shingle-over ridge vent with external baffle and end plugs, new cap shingles", unit: "linear ft" },
      { item: "Roof louvers or turbine vents cut in and flashed high on the slope", unit: "unit", when: "the roof has no continuous ridge to vent" },
      { item: "Gable vents cut in, framed and screened", unit: "unit", when: "gable venting is part of the plan" },
      { item: "Powered or solar attic fan with thermostat and humidistat, cut in and flashed, wired by a licensed electrician where hard-wired", unit: "unit", when: "a powered fan is specified" },
      { item: "Conflicting vents removed: old box vents capped and shingled over, gable vents closed when the ridge system goes in so exhaust does not short-circuit the intake", unit: "unit" },
      { item: "Exhaust fans re-ducted to the exterior with insulated duct and a roof or wall cap with a damper", unit: "unit", when: "bath or kitchen fans discharge into the attic" },
      { item: "Air sealing of the attic floor: top plates, wire and pipe penetrations foamed, IC-rated covers over can lights, the hatch weatherstripped", unit: "sqft", when: "air sealing is included" },
      { item: "Mold treatment of the sheathing and removal of wet insulation", unit: "sqft", when: "the assessment finds mold or wet insulation" },
      { item: "Blown insulation topped up to R-49 over the baffles", unit: "sqft", when: "insulation top-up is included" },
      { item: "Airflow check with smoke at the soffits, photos of every vent, cleanup and haul-off", unit: "fixed" },
    ],
    avoid: [
      "'Ventilation' as one line with no vent type or footage",
      "exhaust added with no intake line — an unbalanced system is not a fix",
      "a ridge vent priced 'each' — it is linear feet",
      "a full roof or insulation job hidden inside a vent estimate",
    ],
    notes: [
      "Vent counts and lengths follow the net free area in the assessment; the plan balances intake and exhaust",
      "Electrical for a powered fan is by a licensed electrician and permitted where required",
      "Mold treatment is a surface treatment; remediation of a structural problem is a separate scope",
    ],
  },
  "outdoor-kitchen": {
    basis: "island run in linear feet for the frame; veneer and countertop in sqft; appliances, doors, fixtures and utility circuits each; gas and water lines in linear feet",
    steps: [
      { item: "Design and permits: island layout with the appliance cutout sheet, clearances from combustibles, gas load and electrical load listed, gas, electrical and plumbing permits and inspections", unit: "fixed" },
      { item: "Slab under the island: 4 in. 3,000-psi reinforced concrete on compacted gravel, sleeves set for the utilities", unit: "sqft", when: "no slab or patio exists under the island" },
      { item: "Gas line: 3/4 in. black iron or CSST from the meter, or polyethylene from a propane tank, in a trench with tracer wire, shutoff valve at the island, pressure tested", unit: "linear ft" },
      { item: "Electrical circuits: dedicated 20 A GFCI circuits in conduit from the panel for the refrigerator, outlets and lighting, weatherproof in-use covers, by a licensed electrician", unit: "unit" },
      { item: "Water and drain: 1/2 in. PEX or copper supply with a frost-proof shutoff, 1-1/2 in. drain to the sewer or a dry well", unit: "linear ft", when: "a sink is included" },
      { item: "Island frame: galvanized steel stud frame skinned in cement board, or CMU block laid on the slab, appliance and door openings framed to the cutout sheet", unit: "linear ft" },
      { item: "Veneer: natural or manufactured stone, tile, brick or stucco over lath and scratch coat on every exposed face", unit: "sqft" },
      { item: "Countertop: 3 cm granite, quartzite or porcelain slab, or poured concrete, with appliance and sink cutouts, eased edge, sealed", unit: "sqft" },
      { item: "Appliances supplied and set: built-in 304 stainless grill with the stated burner output, side burner, outdoor-rated refrigerator, ice maker or kegerator as chosen", unit: "unit" },
      { item: "Grill insulated jacket, stainless access doors, drawers, trash pull-out and vent panels fitted to the openings", unit: "unit" },
      { item: "Outdoor sink and faucet set and connected", unit: "unit", when: "a sink is included" },
      { item: "Pizza oven: insulated dome oven on its stand, vented, with a chimney cap", unit: "unit", when: "a pizza oven is included" },
      { item: "Lighting: low-voltage task and under-counter LED with a transformer and timer", unit: "unit", when: "island lighting is included" },
      { item: "Bar overhang: 12 in. countertop overhang on steel or stone corbels for seating", unit: "linear ft", when: "bar seating is included" },
      { item: "Gas and appliance startup: flexible connectors, leak test with the meter, orifice conversion for propane, ignition and flame checked on every burner", unit: "unit" },
      { item: "Final inspections, stone and countertop sealing, cleanup, owner walkthrough and appliance warranty registration", unit: "fixed" },
    ],
    avoid: [
      "'Outdoor kitchen' as one line with no island length, appliances or utilities",
      "appliances folded into the island price — each is a line with its spec",
      "'Utilities' with no gas footage, circuits or water line named",
      "a patio or paver job hidden inside the kitchen price — another trade",
    ],
    notes: [
      "Island length, appliance list and cutouts follow the approved layout; appliance lead times are stated",
      "Gas, electrical and plumbing are by licensed trades and inspected; the meter or tank capacity is confirmed before the gas line",
      "Natural stone and concrete countertops are sealed at completion; resealing is owner maintenance",
    ],
  },
  "fire-pit-fireplace": {
    basis: "fire features each by fuel type and size; footing concrete in cu yards; firebrick, veneer and hearth in sqft; caps and gas line in linear feet",
    steps: [
      { item: "Design and code check: fuel type (wood, natural gas or propane), size, clearances from the house, fences and overhangs per local code, HOA approval, permit and gas or mechanical inspections", unit: "fixed" },
      { item: "Utility locate and excavation for the footing, spoils removed", unit: "fixed" },
      { item: "Footing: 3,000-psi reinforced concrete slab or footing below frost depth under the feature", unit: "cu yards" },
      { item: "Gas line: 3/4 in. black iron, CSST or polyethylene underground with tracer wire, a key valve at the feature, pressure tested", unit: "linear ft", when: "the feature is gas-fired" },
      { item: "Fire pit structure: CMU or concrete block ring or square, cores grouted, with a steel fire ring or a stainless burner pan opening", unit: "unit", when: "the feature is a fire pit" },
      { item: "Fireplace firebox: masonry firebox kit or firebrick-lined CMU firebox with a smoke shelf, damper and throat sized to the opening", unit: "unit", when: "the feature is an outdoor fireplace" },
      { item: "Chimney: CMU chimney or stainless Class A flue to the height the clearances require, with a spark-arrestor cap", unit: "linear ft", when: "the feature is an outdoor fireplace" },
      { item: "Firebrick lining set in refractory mortar on every fire-facing surface", unit: "sqft" },
      { item: "Burner system: CSA-listed stainless burner and pan, match-lit or electronic ignition with a remote, lava rock or fire glass", unit: "unit", when: "the feature is gas-fired" },
      { item: "Veneer: natural or manufactured stone, brick or stucco over lath and scratch coat on every exposed face", unit: "sqft" },
      { item: "Cap: bluestone, concrete or cast-stone cap set in mortar with a drip edge, or a seating ledge cap", unit: "linear ft" },
      { item: "Hearth: stone or concrete hearth slab in front of the firebox", unit: "sqft", when: "the feature is a fireplace with a hearth" },
      { item: "Wood-burning accessories: spark screen, grate and a cover", unit: "unit", when: "the feature is wood-burning" },
      { item: "Gas startup: burner connected, leak tested, flame height adjusted, ignition demonstrated", unit: "fixed", when: "the feature is gas-fired" },
      { item: "Cleanup, stone sealing, a supervised first burn after the mortar cures, owner instruction and inspection sign-off", unit: "fixed" },
    ],
    avoid: [
      "'Fire pit' as one line with no fuel, size or footing",
      "the gas line folded into the burner price — it is linear feet",
      "'Masonry' with no block, firebrick or veneer named",
      "a patio around the feature without its own line — another trade",
    ],
    notes: [
      "Clearances follow the local code and the burner listing; a wood feature needs the setback the code names",
      "Gas work is by a licensed installer and inspected; propane conversion is stated in the burner line",
      "Mortar cures before the first burn; the schedule allows for it",
    ],
  },
  "chimney-repair": {
    basis: "chimney faces in sqft for repointing, rebuild and waterproofing; flashing, liner and cap in linear feet or each; inspection and access fixed",
    steps: [
      { item: "Level 2 inspection: camera scan of the flue, exterior masonry, crown, cap and flashing photographed, moisture and spalling assessed, written report with the repair plan", unit: "fixed" },
      { item: "Access and protection: scaffolding, roof staging or a lift with fall protection, roof and landscaping below covered", unit: "fixed" },
      { item: "Tuckpointing: deteriorated mortar joints ground out 3/4 in. deep, dusted and repointed with Type N mortar matched in color and tooled to the original profile", unit: "sqft" },
      { item: "Rebuild: spalled or leaning brickwork taken down to sound courses and rebuilt with matching brick and Type N mortar", unit: "sqft", when: "the brick is spalled or the chimney above the roof is unsound" },
      { item: "Crown: cracked crown removed and a new 2 in. cast concrete crown poured with a drip edge and bond break, or a sound crown sealed with elastomeric crown coat", unit: "unit" },
      { item: "Flashing: new step flashing woven with the shingles and counter flashing let into a cut reglet in the mortar joints, cricket behind chimneys wider than 30 in.", unit: "linear ft" },
      { item: "Chimney cap: stainless steel cap with spark screen, single or multi-flue, fastened to the crown or flue tile", unit: "unit" },
      { item: "Flue liner: insulated 316Ti stainless liner or a cast-in-place liner, sized to the appliance, connected with a top plate and cap", unit: "linear ft", when: "the flue liner is cracked, missing or undersized" },
      { item: "Top-sealing damper with a cable control replacing a rusted throat damper", unit: "unit", when: "the throat damper is rusted or missing" },
      { item: "Firebox repair: loose firebrick reset and joints repointed with refractory mortar", unit: "sqft", when: "the firebox joints are open or bricks are loose" },
      { item: "Smoke chamber parged smooth with refractory mortar", unit: "sqft", when: "the smoke chamber is corbeled and unparged" },
      { item: "Waterproofing: breathable siloxane water repellent, two coats on every face", unit: "sqft" },
      { item: "Chase cover: rusted metal cover replaced with a stainless cover with a drip edge and storm collar", unit: "unit", when: "the chimney is a framed chase with a metal cover" },
      { item: "Cleanup: staging struck, debris hauled, roof and gutters cleared of mortar, after photos and the closing report", unit: "fixed" },
    ],
    avoid: [
      "'Chimney repair' with no face area, crown or flashing named",
      "repointing and rebuild priced as one line — a rebuild is its own sqft",
      "'Sealant' as the whole repair for a failed crown or flashing",
      "chimney sweeping billed as a repair line",
    ],
    notes: [
      "Face areas and flue length come from the inspection; hidden damage found once staging is up is priced as found",
      "Brick and mortar are matched as closely as current products allow; a weathered match is stated",
      "Liner sizing follows the appliance connected to the flue; a change of appliance changes the liner",
    ],
  },
};
