// Smart Proposal procedures — Fabrication / custom. See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  "metal-fabrication": {
    basis: "railings and guards by linear ft; stairs by flight; canopies, gates and custom pieces each; finish by sqft; installation by piece",
    steps: [
      { item: "Field measurement and templating: openings, floor-to-floor heights, mounting surfaces and embeds measured; templates made for curves and returns", unit: "fixed" },
      { item: "Shop drawings: elevations, sections, connection details and finish schedule; guard and stair design to the 200 lb concentrated and 50 lb/ft loads (IBC 1607), engineer's stamp where required", unit: "fixed" },
      { item: "Finish samples and a shop mockup section for the owner's approval before fabrication", unit: "fixed", when: "the finish or profile is custom" },
      { item: "Railings and guards: 1-1/2 in. square-tube steel posts at 4 ft o.c., top and bottom rails, 1/2 in. square pickets at 4 in. clear (or 6063 aluminum equivalents), shop-welded and ground smooth", unit: "linear ft" },
      { item: "Handrail: 1-1/2 in. round or pipe handrail at 34-38 in. with wall brackets at 4 ft o.c., returns to the wall and 12 in. extensions at the stair ends", unit: "linear ft" },
      { item: "Infill: 1/2 in. tempered or laminated glass panels in shoe or clip mounts, or 1/8 in. stainless cable at 3 in. o.c. with tensioners", unit: "linear ft", when: "glass or cable infill is specified" },
      { item: "Stairs: C12 channel stringers, concrete-filled pans or checker-plate treads, landings and closed risers, per flight", unit: "unit", when: "stairs are in the scope" },
      { item: "Canopies and awnings: HSS frame, outriggers and hangers, standing-seam or perforated panel roof, shop-assembled in sections", unit: "unit", when: "a canopy or awning is in the scope" },
      { item: "Gates, screens, brackets and custom pieces: cut, formed, welded and fit in the shop to the approved drawings", unit: "unit" },
      { item: "Finish: hot-dip galvanizing (ASTM A123), powder coat over zinc primer (AAMA 2604), or two-coat urethane; stainless passivated and brushed", unit: "sqft" },
      { item: "Delivery to the site and hoisting by forklift or crane", unit: "fixed" },
      { item: "Installation: posts core-drilled and grouted or surface-mounted on 1/2 in. epoxy or wedge anchors into concrete, lagged into blocking, or welded to embeds", unit: "unit" },
      { item: "Field welding and grinding by a certified welder, with fire watch", unit: "hour", when: "connections are field-welded" },
      { item: "Grout and sealant at post bases, escutcheons and touch-up of the finish at field connections", unit: "unit" },
      { item: "Load test and inspection: guards and handrails checked plumb and to the design load, welds inspected", unit: "fixed" },
      { item: "Cleanup and demobilization: protective wrap removed, cores and cutoffs hauled", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Railing' or 'Metal work' line with no profile, size or linear feet",
      "'Finish' with no product or standard",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "concrete stair fill, wood stairs or electrical — other trades",
      "pricing fabrication and installation as one line",
    ],
    notes: [
      "Railings and guards are measured along the top rail; posts are counted in the linear-foot price",
      "Fabrication starts after signed shop drawings; changes after release are priced as a change order",
      "Mounting substrate is assumed sound concrete or solid blocking; adding blocking or repairing a substrate is priced as a change",
      "Galvanizing and powder coating are priced at the coater's rate and lead time",
    ],
  },

  "prefab-modular": {
    basis: "modules or panels each by size and finish level; set crane by day; foundation, utilities and site close-up by their own units",
    steps: [
      { item: "Design and engineering: modular set drawings, factory plans and third-party or state modular program approval, stamped for the site's snow, wind and seismic loads", unit: "fixed" },
      { item: "Permits: local building permit for the foundation, site work and set; state modular insignia or label fees", unit: "fixed" },
      { item: "Site preparation: access route for carriers and the crane graded and matted, staging area cleared, crane pad compacted", unit: "fixed" },
      { item: "Foundation: crawl-space stem wall, basement or pier foundation to the set plan, with anchor bolts, sill plates and marriage-wall bearing", unit: "linear ft" },
      { item: "Utilities to the set point: water, sewer, gas and electrical service stubbed to the foundation", unit: "linear ft" },
      { item: "Factory-built modules or panels: framed, insulated, roughed-in and finished to the stated level in the plant, per module", unit: "unit" },
      { item: "Factory quality control and third-party inspection at rough-in and close-up, with the certificates", unit: "fixed" },
      { item: "Transportation: carriers, pilot cars and oversize permits from the factory to the site, per module", unit: "unit" },
      { item: "Crane: 100-300 ton hydraulic crane with operator, rigging and spreader bars, day rate, with the lift plan", unit: "fixed" },
      { item: "Set: modules lifted, landed, leveled and bolted to the foundation, married at the mate lines, wrap removed, per module", unit: "unit" },
      { item: "Marriage-line connections: structural bolts and straps, floor and ceiling seams closed, drywall and flooring at the mate lines", unit: "linear ft" },
      { item: "Roof close-up: hinged roof sections raised and braced, ridge and mate-line shingles, dormers and gables set", unit: "sqft" },
      { item: "Exterior close-up: siding, corners and trim at the mate lines and where sections meet, soffit and fascia closed", unit: "linear ft" },
      { item: "Utility cross-connections between modules: electrical panel and circuits, plumbing and drain connections, HVAC duct and line sets", unit: "fixed" },
      { item: "Site-built elements: stairs, decks, porches, garage or breezeway framed and finished on site", unit: "unit", when: "site-built additions are in the scope" },
      { item: "Interior finish at the mate lines: drywall tape and paint, flooring transitions, cabinets and trim completed", unit: "fixed" },
      { item: "Final inspections: state or local final, certificate of occupancy", unit: "fixed" },
      { item: "Cleanup and demobilization: shipping wrap, carriers and cribbing removed, site graded and debris hauled", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Module' or 'Prefab' line with no size, count or finish level",
      "'Crane' with no size or duration",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "well, septic or driveway — separate scopes",
      "pricing the modules and the set as one line",
    ],
    notes: [
      "Module count and size follow the approved set drawings; factory finish level is stated per module",
      "Foundation, utilities and site work are priced to the set plan; soil, rock or water conditions at the site are priced as a change order",
      "Crane and carrier access assumes a clear route; matting, tree removal or a larger crane for reach is priced as a change",
      "Factory lead time and delivery dates depend on the plant's schedule; weather delays at the set are billed at the day rate",
    ],
  },

  signage: {
    basis: "signs each by type, size and illumination; graphics and vinyl by sqft; permits, surveys, electrical and lifts by fixed",
    steps: [
      { item: "Site survey: wall and mounting conditions, dimensions, sightlines, photos, power location and the sign ordinance's size and height limits checked", unit: "fixed" },
      { item: "Design and proofs: artwork, dimensioned shop drawings, color matches and renderings for the owner's sign-off", unit: "fixed" },
      { item: "Sign permit application with engineering for wind load, landlord approval package and the fees", unit: "fixed", when: "the jurisdiction or landlord requires a permit or approval" },
      { item: "Channel letters: 5 in. deep .040 aluminum returns, 3/16 in. acrylic faces with trim cap, LED modules and UL-listed power supplies, mounted on a raceway or flush", unit: "unit", when: "channel letters are in the scope" },
      { item: "Cabinet signs: welded aluminum cabinet with polycarbonate or flex faces, LED illumination, retainer frames", unit: "unit", when: "a cabinet sign is in the scope" },
      { item: "Monument or pylon sign: steel pole or masonry base, cabinet and letters, on a concrete caisson footing to the engineer's design", unit: "unit", when: "a freestanding sign is in the scope" },
      { item: "Interior ADA and wayfinding signs: room signs with raised letters and Grade 2 Braille, directories and directionals, mounted with tape and silicone", unit: "unit", when: "interior signage is in the scope" },
      { item: "Vinyl graphics: cut vinyl or printed and laminated cast vinyl (3M IJ180 or equal) for windows, walls and vehicles, applied wet or dry", unit: "sqft", when: "vinyl graphics are in the scope" },
      { item: "Dimensional letters: cut acrylic, PVC or aluminum letters, stud-mounted flush or with spacers on a pattern", unit: "unit", when: "dimensional letters are in the scope" },
      { item: "Existing signs removed, wall patched and painted, old electrical made safe", unit: "unit", when: "old signs are replaced" },
      { item: "Delivery and lift equipment: signs crated and delivered; bucket truck, boom lift or scaffold for the installation height", unit: "fixed" },
      { item: "Installation: anchors into masonry, steel or blocking, raceway or letters set to the pattern, plumb and level", unit: "unit" },
      { item: "Electrical: primary circuit, disconnect switch and photocell or timer to the sign location by a licensed electrician", unit: "fixed", when: "the sign is illuminated" },
      { item: "Final hookup, UL labels, lighting checked for even illumination", unit: "fixed", when: "the sign is illuminated" },
      { item: "Sign inspection and permit close-out", unit: "fixed", when: "a permit was pulled" },
      { item: "Cleanup and maintenance: protective film removed, site cleaned, care instructions and warranty documents given to the owner", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Sign' or 'Graphics' line with no type, size or illumination",
      "'Install' with no mounting method or count",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "storefront glazing, awnings or building paint — other trades",
      "pricing fabrication, permit and installation as one sign line",
    ],
    notes: [
      "Sign sizes and counts follow the approved drawings; illuminated signs are UL-listed and carry the manufacturer's LED warranty",
      "Permit and landlord approval time is outside the installer's control; fees are passed through at cost",
      "Primary electrical to the sign location is by a licensed electrician and is included only when listed",
      "Mounting assumes a sound substrate; hidden conduit, steel or a failed wall behind the sign is priced as a change",
      "Vinyl on glass carries a 5-year exterior warranty; vehicle wraps depend on the paint condition",
    ],
  },

  "elevator-lift": {
    basis: "each elevator or lift by type, capacity, speed and number of stops; hoistway, pit and machine-room work by fixed; service by contract",
    steps: [
      { item: "Site survey and code review: hoistway plumb and dimensions, pit depth, overhead clearance, power and machine-room space checked against ASME A17.1 and the ADA", unit: "fixed" },
      { item: "Layout drawings and submittals: hoistway and pit layouts, rail bracket loads, electrical requirements and cab finishes for the engineer and owner", unit: "fixed" },
      { item: "State elevator permit, plan review and the inspection fees", unit: "fixed" },
      { item: "Hoistway and pit modifications: pit waterproofing and ladder, sump with pump, rail-bracket steel, overhead beam and hoistway walls to the fire rating", unit: "fixed", when: "the existing hoistway or pit does not meet the layout" },
      { item: "Elevator equipment: machine-room-less traction or hydraulic elevator, stated capacity (2,100-3,500 lb), speed (100-150 fpm) and number of stops, with controller and drive", unit: "unit" },
      { item: "Hydraulic jack: holeless twin jack, or in-ground cylinder in a drilled and cased hole with PVC liner", unit: "unit", when: "the elevator is hydraulic" },
      { item: "Residential elevator, platform lift, stairlift or dumbwaiter: unit type and capacity per the manufacturer's specification, with rails and drive", unit: "unit", when: "a residential or accessibility lift is specified instead of a commercial elevator" },
      { item: "Delivery, rigging and hoisting of the machine, rails, car sling and doors into the hoistway and machine space", unit: "fixed" },
      { item: "Guide rails, brackets, buffers and pit equipment set plumb and aligned in the hoistway", unit: "unit" },
      { item: "Hoistway entrances: doors, frames, sills, hall stations and lanterns at each landing, per stop", unit: "unit" },
      { item: "Car: sling and platform, cab with the selected finishes, door operator, car operating panel, lighting and handrail", unit: "unit" },
      { item: "Hoistway and machine-room wiring: traveling cable, controller connections, safety circuits, pit and hoistway lights", unit: "fixed" },
      { item: "Electrical by the licensed electrician: 3-phase fused disconnect, lighting circuit, GFCI outlets, sump pump circuit and the phone or monitoring line", unit: "fixed" },
      { item: "Fire service, emergency lighting, two-way communication and monitoring connections per the code", unit: "fixed" },
      { item: "Modernization: controller, machine, door operators, fixtures and cab interior replaced in the existing hoistway", unit: "unit", when: "an existing elevator is modernized instead of replaced" },
      { item: "Adjustment and testing: ride adjusted, safeties and brakes tested, full-load and overspeed tests witnessed", unit: "fixed" },
      { item: "State inspection and the certificate of operation", unit: "fixed" },
      { item: "Owner training and turnover: keys, manuals, wiring diagrams and the first-year warranty", unit: "fixed" },
      { item: "Maintenance agreement: monthly service visits, lubrication, adjustments and 24-hour callback", unit: "fixed", when: "a service contract is included" },
      { item: "Cleanup: crating and packaging removed, hoistway and machine room swept, protective coverings pulled", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Elevator' or 'Lift' line with no type, capacity, speed or stops",
      "'Installation' with no equipment named",
      "'Miscellaneous', 'contingency' or 'general labor' lines",
      "the hoistway structure, pit concrete or machine-room HVAC — the general contractor's work unless listed",
      "pricing equipment and installation as one line",
    ],
    notes: [
      "Equipment, capacity, speed and stops follow the layout drawings; cab finishes are selected from the manufacturer's standard line unless custom finishes are listed",
      "The hoistway, pit, machine space and power are provided by others to the layout drawings; corrections to an out-of-plumb hoistway are priced as a change order",
      "Delivery lead time is set by the manufacturer; state inspection scheduling depends on the inspector's availability",
      "Maintenance after the warranty period is under a separate service agreement",
    ],
  },
};
