// Smart Proposal procedures — Interior finishes. See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  painting: {
    basis: "wall and ceiling area in sqft; trim, base and crown by linear ft; doors, windows and shutters each; coats and sheen named",
    steps: [
      { item: "Protection and masking: canvas drop cloths on floors, plastic and paper masking over cabinets, counters, fixtures and furniture; switch plates, hardware and register covers removed and bagged", unit: "sqft" },
      { item: "Pressure wash siding and trim at low pressure with a mildewcide wash, rinsed and allowed to dry before coating", unit: "sqft", when: "the scope is exterior" },
      { item: "Surface prep: scrape and sand loose or failed paint to a feathered edge, dull glossy surfaces, fill nail holes and dents, re-caulk gaps at trim with paintable acrylic-latex caulk", unit: "sqft" },
      { item: "Drywall and plaster repair: cracks, dents and nail pops cut back, taped and filled with setting compound, sanded flush and spot-primed", unit: "hour", when: "walls or ceilings have damage beyond nail holes" },
      { item: "Lead-safe work practices under the EPA RRP rule: containment, HEPA cleanup and certified-renovator documentation", unit: "fixed", when: "the home was built before 1978 and existing coatings are disturbed" },
      { item: "Primer: stain-blocking or bonding primer on bare, patched and repaired areas; full prime coat on new drywall or a dark-to-light color change", unit: "sqft" },
      { item: "Walls: two finish coats of premium 100% acrylic-latex in the scheduled sheen, cut in by brush and rolled with a 1/2 in. nap roller", unit: "sqft" },
      { item: "Ceilings: two coats of flat ceiling paint, rolled with a 3/4 in. nap roller for a uniform texture", unit: "sqft" },
      { item: "Trim, baseboard, casing and crown: two coats of waterborne alkyd enamel in satin or semi-gloss, brushed or sprayed and back-brushed", unit: "linear ft" },
      { item: "Doors: both faces and edges, sanded between coats, two coats of waterborne enamel sprayed or brushed; hardware removed and reinstalled", unit: "unit" },
      { item: "Window sashes, frames and sills prepped and coated in two coats of enamel, glass cut in by hand and razor-cleaned", unit: "unit", when: "windows are in the scope" },
      { item: "Accent walls or additional colors: extra coat and separate cut-in for each scheduled color beyond the field color", unit: "sqft", when: "the color schedule has accent walls or more than one wall color" },
      { item: "Exterior siding and body: two coats of 100% acrylic exterior paint or solid stain, sprayed and back-rolled", unit: "sqft", when: "the scope is exterior" },
      { item: "Exterior trim, fascia, soffit, gutters and downspouts coated in two coats of exterior enamel", unit: "linear ft", when: "the scope is exterior" },
      { item: "Ladders, scaffolding or a lift staged and moved for ceilings, stairwells and walls above 12 ft", unit: "fixed", when: "any surface is above 12 ft or over a stairwell" },
      { item: "Walk-through with the client, touch-ups, masking removed, plates and hardware reinstalled, floors vacuumed and wiped; labeled leftover paint left for the owner", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Paint' or 'Painting' line with no surface, coats, sheen or product",
      "'labor' and 'materials' as two separate lines",
      "'prep' with no method — say scrape, sand, fill, caulk",
      "walls, ceilings and trim priced as one number",
      "drywall replacement, carpentry or window repair beyond patching — another trade",
      "'touch-up as needed' as an open-ended line",
    ],
    notes: [
      "Wall area is measured as room perimeter times ceiling height with openings not deducted; ceilings by floor area; trim by linear ft",
      "Colors and sheens follow the approved color schedule; one field color per room, each additional color is a change",
      "Furniture is moved to the center of the room and covered; pianos, electronics and full china cabinets are moved by the owner",
      "Wallpaper removal, lead abatement and rotten wood replacement are excluded unless listed",
      "Product line and colors are named on the proposal so the client can match later",
    ],
  },

  drywall: {
    basis: "board area in sqft hung and finished by board type and finish level; corner bead, framing and furring by linear ft; patches each",
    steps: [
      { item: "Dust control and protection: floors covered, doorways and HVAC registers sealed with plastic, zip-wall barriers at the work area", unit: "sqft" },
      { item: "Remove damaged drywall or plaster and lath to the framing, debris bagged and hauled, dump fees included", unit: "sqft", when: "existing wall or ceiling finish is being replaced" },
      { item: "Framing adjustments: new 2x4 or 25-gauge metal-stud partitions, furring over uneven masonry, shimming out-of-plane studs, blocking for grab bars and cabinets", unit: "linear ft", when: "partitions, furring or blocking are needed before hanging" },
      { item: "Board delivery and stocking to each room, 1/2 in. or 5/8 in. sheets staged flat", unit: "fixed" },
      { item: "Hang walls: 1/2 in. regular gypsum board, screwed 16 in. o.c. with 1-1/4 in. drywall screws, joints staggered and gaps at electrical boxes held tight", unit: "sqft" },
      { item: "Hang ceilings: 5/8 in. or 1/2 in. sag-resistant ceiling board across the joists, screwed 12 in. o.c. with adhesive at framing", unit: "sqft" },
      { item: "Moisture and mold-resistant board (purple or green board) at bathrooms, laundry and around tubs outside the wet zone", unit: "sqft", when: "the room is a bathroom, laundry or other damp area" },
      { item: "5/8 in. Type X fire-rated board at the garage-to-house wall and ceiling, or at any rated assembly the plans call out", unit: "sqft", when: "the assembly is fire-rated" },
      { item: "Corner bead: paper-faced metal or vinyl bead on outside corners, J-bead at exposed edges, arch bead at curved openings", unit: "linear ft" },
      { item: "Tape and finish to Level 4: paper tape bedded in all joints and inside corners, three coats of joint compound, screw heads spotted, sanded smooth", unit: "sqft" },
      { item: "Level 5 skim coat over the whole surface for gloss paint, dark colors or critical side lighting", unit: "sqft", when: "the paint spec or lighting calls for Level 5" },
      { item: "Texture: orange peel, knockdown or matched existing texture sprayed and knocked down, with a spot test to confirm the match", unit: "sqft", when: "walls or ceilings are textured" },
      { item: "Fire and smoke sealing at penetrations in rated walls with firestop sealant and putty pads at boxes", unit: "fixed", when: "the assembly is fire-rated" },
      { item: "Patch repairs: cut out to a square, add backing, new board, taped and finished to blend with the existing wall", unit: "unit", when: "there are individual holes or damaged spots" },
      { item: "Access panels set flush at valves, junction boxes and cleanouts", unit: "unit", when: "concealed valves or junctions need access" },
      { item: "PVA drywall primer rolled on all new board to seal the paper and compound before paint", unit: "sqft", when: "priming is in the scope" },
      { item: "Final sanding, dust vacuumed with HEPA, scrap board and compound buckets hauled to the dump", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Drywall' or 'Sheetrock' line with no thickness, board type or finish level",
      "'hang and finish' priced as one number — hanging and finishing are separate lines",
      "'tape and mud' with no finish level named",
      "painting beyond primer — the painter's work",
      "'framing' with no member size or spacing",
    ],
    notes: [
      "Board area is measured by wall and ceiling surface; openings under 25 sqft are not deducted",
      "Finish level follows GA-214 and the paint spec; Level 4 is assumed unless Level 5 is listed",
      "Framing is assumed straight and dry; shimming or replacing bad studs is a change",
      "Insulation, electrical box adjustments and vapor barrier are by others unless listed",
    ],
  },

  "flooring-installation": {
    basis: "finished floor area in sqft by product (carpet by the sq yard); transitions, nosing and base by linear ft; stairs and doors each",
    steps: [
      { item: "Move furniture and appliances out of the rooms and return them after installation", unit: "hour", when: "the rooms are occupied" },
      { item: "Remove existing flooring: carpet and pad with tack strip pulled, glued vinyl or wood scraped up, or tile broken out; staples pulled and debris bagged", unit: "sqft" },
      { item: "Subfloor prep: adhesive residue scraped, squeaks re-screwed, seams sanded, loose or water-damaged plywood replaced, floor vacuumed", unit: "sqft" },
      { item: "Concrete moisture test: in-situ RH probes (ASTM F2170) or calcium chloride (ASTM F1869) with results on file before glue-down or wood", unit: "fixed", when: "the substrate is concrete" },
      { item: "Moisture mitigation: two-part epoxy vapor barrier rolled over the slab where readings exceed the product limit", unit: "sqft", when: "the moisture test exceeds the manufacturer limit" },
      { item: "Floor flattening: self-leveling underlayment poured over primed substrate to bring the floor within 3/16 in. in 10 ft", unit: "sqft", when: "the floor is out of flat beyond the product tolerance" },
      { item: "Underlayment: 1/4 in. plywood, 1/4 in. cement board, or attached-pad foam or cork underlayment with seams taped", unit: "sqft" },
      { item: "Luxury vinyl plank or laminate: floating click-lock installation with 1/4 in. expansion gaps, end joints staggered 8 in. minimum, planks cut around jambs and cabinets", unit: "sqft", when: "the product is LVP, LVT or laminate" },
      { item: "Hardwood: 3/4 in. solid nailed 8 in. o.c. over 15 lb felt, or engineered plank glued down with urethane adhesive; racked and acclimated before install", unit: "sqft", when: "the product is solid or engineered hardwood" },
      { item: "Carpet: tack strip at the perimeter, 8 lb rebond pad, seams heat-taped, carpet power-stretched and tucked", unit: "sq yards", when: "the product is carpet" },
      { item: "Sheet vinyl or linoleum fully adhered with flash-cove or coved base, seams heat-welded", unit: "sqft", when: "the product is sheet goods" },
      { item: "Stairs: treads, risers and matching stair nosing installed and fastened per step", unit: "unit", when: "stairs are in the scope" },
      { item: "Transitions: T-molding, reducers, end caps and thresholds at doorways and material changes, color-matched to the floor", unit: "linear ft" },
      { item: "Baseboard and shoe molding removed and reinstalled, or new primed shoe nailed to the base after the floor is down", unit: "linear ft" },
      { item: "Doors undercut and door bottoms trimmed for the new floor height", unit: "unit", when: "the new floor is thicker than the old one" },
      { item: "Toilets and appliances pulled, reset on new wax rings or flex lines and reconnected", unit: "unit", when: "fixtures sit on the floor being replaced" },
      { item: "Old flooring and pad hauled to the dump; floor vacuumed and damp-mopped; leftover boxes and warranty registration left with the owner", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Flooring' or 'Install floor' line with no product, thickness or method",
      "'subfloor work' or 'floor prep' with no scope — say scrape, screw, level or replace",
      "carpet priced by the sqft instead of the sq yard",
      "transitions and underlayment buried in the flooring price",
      "tile showers or walls — the tile setter's work",
    ],
    notes: [
      "Area is measured from room dimensions plus a waste factor for the pattern; diagonal and herringbone layouts carry more waste",
      "Product, color and installation method are named on the proposal and follow the manufacturer's instructions for warranty",
      "Subfloor replacement beyond the listed area, rot and asbestos-containing flooring are priced as a change",
      "Material acclimates on site for the period the manufacturer requires before installation",
    ],
  },

  "kitchen-remodel": {
    basis: "the kitchen itemized by task: cabinets by linear ft, counters and finishes by sqft, plumbing, electrical and fixtures each, permits fixed",
    steps: [
      { item: "Permits and inspections: building, electrical and plumbing permits pulled, rough and final inspections scheduled", unit: "fixed" },
      { item: "Protection and dust control: Ram Board on floors in the path, plastic dust walls with zipper doors, HVAC registers sealed, temporary kitchen set up for the owner", unit: "fixed" },
      { item: "Demolition of cabinets, countertops, backsplash, sink and appliances: disconnected, removed and hauled", unit: "linear ft" },
      { item: "Removal of existing flooring and underlayment down to the subfloor", unit: "sqft", when: "the floor is being replaced" },
      { item: "Dumpster and disposal fees for demolition debris", unit: "fixed" },
      { item: "Wall removal: non-bearing wall taken out, or a bearing wall replaced with an engineered LVL header, posts and footings", unit: "linear ft", when: "the layout opens or moves a wall" },
      { item: "Framing changes: new partition or pony wall, soffit removal, furring, blocking for wall cabinets and the range hood", unit: "linear ft", when: "the layout changes or soffits come down" },
      { item: "Rough plumbing: sink supply and 1-1/2 in. drain relocated, dishwasher and ice-maker lines, pot filler, gas line to the range with shutoff", unit: "unit" },
      { item: "Rough electrical: dedicated 20A small-appliance circuits, 240V/50A range circuit, dishwasher and disposal circuits, microwave, GFCI protection, recessed LED cans, under-cabinet lighting wiring, island receptacle", unit: "unit" },
      { item: "Range hood venting: 6 in. or 8 in. rigid duct to the exterior with a backdraft damper and wall or roof cap", unit: "unit" },
      { item: "HVAC register relocated or toe-kick register added where cabinets cover the existing one", unit: "unit", when: "a register falls under new cabinets" },
      { item: "Insulation in opened exterior walls: R-15 batts or spray foam before the walls close", unit: "sqft", when: "exterior walls are opened" },
      { item: "Drywall and patching: new 1/2 in. board where walls were opened, patches at old boxes and holes, taped and finished to Level 4", unit: "sqft" },
      { item: "Flooring: tile, LVP or hardwood over the proper underlayment, run under the appliance openings", unit: "sqft" },
      { item: "Cabinets installed: wall, base and tall boxes leveled and screwed to studs, scribed to walls, fillers, toe kicks, end panels and crown", unit: "linear ft" },
      { item: "Countertops: 3 cm quartz or granite templated, fabricated with the chosen edge, undermount sink cutout and faucet holes, seams color-matched", unit: "sqft" },
      { item: "Backsplash tile set on modified thinset, grouted and caulked at the counter, with outlet extenders and trim profile", unit: "sqft" },
      { item: "Fixtures and appliances set and connected: sink, faucet, disposal, dishwasher, range, hood, refrigerator water line, microwave", unit: "unit" },
      { item: "Finish electrical: devices, plates, pendant and recessed trims, under-cabinet LED strips with driver and dimmer", unit: "unit" },
      { item: "Walls and ceiling primed and painted two coats in the scheduled sheen", unit: "sqft" },
      { item: "Trim: baseboard, casing and shoe molding installed, filled and caulked; floor transitions at doorways", unit: "linear ft" },
      { item: "Cabinet pulls and knobs drilled with a jig and installed; final clean, punch list walk-through and warranty paperwork", unit: "fixed" },
    ],
    avoid: [
      "'Kitchen remodel — lump sum' with the work hidden inside",
      "'demo' with no list of what comes out",
      "cabinets, countertops and backsplash priced as one line",
      "'electrical' or 'plumbing' with no fixture or circuit count",
      "appliances themselves as a line unless the contractor is supplying them",
    ],
    notes: [
      "Cabinets are measured by linear ft of wall and base run; countertops by sqft including the overhang; backsplash by sqft",
      "Appliances are supplied by the owner and set by the contractor unless the proposal lists them",
      "Hidden conditions behind walls (rot, out-of-code wiring, asbestos) are priced as a change",
      "Cabinet and countertop lead times set the schedule; the temporary kitchen stays until the sink is live",
    ],
  },

  "bathroom-remodel": {
    basis: "the bathroom itemized by task: tile, waterproofing and finishes by sqft, shower pan, fixtures and glass each, plumbing and electrical by fixture",
    steps: [
      { item: "Permits and inspections: building, plumbing and electrical permits, rough and final inspections", unit: "fixed" },
      { item: "Protection and dust containment: floor runners in the hallway, plastic on the door, exhaust fan or negative-air unit, a second bath kept available for the owner", unit: "fixed" },
      { item: "Fixtures removed: toilet, vanity, tub or shower, mirror, accessories and lighting disconnected and hauled", unit: "unit" },
      { item: "Tile, backer and flooring demolished to the studs and subfloor, debris bagged, carried out and disposed of", unit: "sqft" },
      { item: "Framing: shower curb and bench, recessed niche, blocking for grab bars, glass and the vanity, wall moved or furred to fit the new tub", unit: "linear ft", when: "the layout changes or the shower gets a curb, bench or niche" },
      { item: "Rough plumbing: supply and drain moved or replaced, 2 in. shower drain, pressure-balance or thermostatic valve with the trim set, tub overflow, toilet flange at finished floor", unit: "unit" },
      { item: "Rough electrical: 20A GFCI circuit, vanity light and sconce boxes, exhaust fan circuit, switch loops, heated-floor thermostat wiring", unit: "unit" },
      { item: "Exhaust fan: 80-110 CFM ENERGY STAR fan with a humidity sensor, ducted with rigid duct to a roof or wall cap", unit: "unit" },
      { item: "Subfloor replaced with 3/4 in. plywood where water damage is found, sistered joists", unit: "sqft", when: "the subfloor is soft or rotted" },
      { item: "Wall board: 1/2 in. cement board at the wet walls, moisture-resistant drywall elsewhere, ceiling board, taped and finished", unit: "sqft" },
      { item: "Shower pan: Schluter-KERDI foam tray or a hand-floated mud pan with a bonded drain, flood-tested for 24 hours before tile", unit: "unit" },
      { item: "Waterproofing: KERDI sheet membrane or RedGard liquid membrane on the shower walls, curb, niche and ceiling, seams banded and corners sealed", unit: "sqft" },
      { item: "Electric radiant floor heat: heating mat embedded in the thinset with a floor sensor and programmable thermostat", unit: "sqft", when: "heated floors are in the scope" },
      { item: "Floor tile: porcelain set on modified thinset with leveling clips, grouted with high-performance grout, sealed", unit: "sqft" },
      { item: "Shower and wall tile: set on modified thinset with a laid-out pattern, edge profiles or bullnose, grouted and silicone-caulked at every change of plane", unit: "sqft" },
      { item: "Vanity and top set and leveled, undermount sink, faucet and drain assembly connected", unit: "unit" },
      { item: "Fixtures set: toilet on a new wax ring, shower trim and head, tub filler, towel bars, paper holder and grab bars into blocking", unit: "unit" },
      { item: "Frameless 3/8 in. tempered glass shower door and panel, measured after tile and installed with a header or clamps", unit: "unit" },
      { item: "Walls and ceiling primed and painted two coats of moisture-resistant bath paint", unit: "sqft" },
      { item: "Trim and door: baseboard, casing and threshold installed, filled and caulked", unit: "linear ft" },
      { item: "Mirror, lighting, fan grille and accessories installed; final clean, silicone cure time observed, walk-through and warranty", unit: "fixed" },
    ],
    avoid: [
      "'Bathroom remodel' as one lump sum",
      "'tile' with no location, size or setting method",
      "waterproofing missing or hidden inside the tile line",
      "'plumbing' with no fixture count or valve named",
      "the shower glass forgotten or listed as an allowance with no size",
    ],
    notes: [
      "Tile is measured by the sqft of floor and wall surface with waste for the pattern; the shower pan, niche and glass are each",
      "Fixtures and tile are owner-selected within the listed allowances; substitutions are priced at the difference",
      "Rot, mold or out-of-code plumbing found behind the walls is priced as a change",
      "Glass is measured after tile and installs two weeks later; the shower is usable after grout and silicone cure",
    ],
  },

  "tile-stone": {
    basis: "installed area in sqft by material, size and setting method; edge profiles, trims and movement joints by linear ft; niches, benches and pans each",
    steps: [
      { item: "Protection and staging: floors and finished surfaces covered, wet saw set up outside or in containment, tile delivered and stacked by room", unit: "fixed" },
      { item: "Substrate prep: flatness checked to 1/8 in. in 10 ft for large-format tile, high spots ground, low spots filled with patch or self-leveler, dust vacuumed", unit: "sqft" },
      { item: "Underlayment: 1/4 in. cement board screwed and taped over thinset, or Schluter-DITRA uncoupling membrane bonded to the subfloor", unit: "sqft" },
      { item: "Crack-isolation membrane over slab cracks and control joints so movement does not telegraph through the tile", unit: "sqft", when: "the slab has cracks or control joints under the tile" },
      { item: "Waterproofing: sheet or liquid membrane rated to ANSI A118.10 on shower walls, floors, curbs and tub decks, seams banded", unit: "sqft", when: "the installation is in a shower, steam room or wet area" },
      { item: "Shower pan: pre-sloped mud bed with a bonded membrane and drain, or a foam tray system, flood-tested before tile", unit: "unit", when: "a shower floor is in the scope" },
      { item: "Layout: center lines snapped, pattern dry-laid to balance cuts at walls and doorways, grout joint width and pattern approved with the owner", unit: "fixed" },
      { item: "Floor tile set: porcelain or ceramic on modified thinset (ANSI A118.4 or A118.15), large-format back-buttered, leveling clips, 95% coverage in wet areas", unit: "sqft" },
      { item: "Wall tile set: field tile on thinset with spacers, cuts polished at exposed edges, outlets and valves cut clean", unit: "sqft" },
      { item: "Natural stone: marble, travertine or slate sealed before grouting and set in white thinset to avoid staining, edges honed where exposed", unit: "sqft", when: "the material is natural stone" },
      { item: "Mosaic and accent bands set on a mesh backing with a flat trowel, aligned with the field tile joints", unit: "sqft", when: "the design has mosaics or accent bands" },
      { item: "Edge profiles and trim: Schluter metal profiles, bullnose or pencil liner at exposed edges, curbs and niche returns", unit: "linear ft" },
      { item: "Recessed niche or shower bench tiled, sloped to drain, with mitered or profiled edges", unit: "unit", when: "a niche or bench is in the scope" },
      { item: "Grouting: high-performance cement grout or epoxy grout in the chosen color, joints packed, cleaned and haze removed", unit: "sqft" },
      { item: "Movement joints: color-matched 100% silicone at changes of plane, corners and perimeter per TCNA EJ171", unit: "linear ft" },
      { item: "Sealing: penetrating sealer on natural stone and cement grout after cure", unit: "sqft" },
      { item: "Cleanup: thinset and grout buckets hauled, floors washed, scraps and extra tile boxed and left for the owner", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Tile' line with no material, size, location or setting method",
      "grout, movement joints and trim buried in the tile price",
      "'waterproofing' with no membrane named",
      "plumbing valve or drain rough-in — the plumber's work",
      "demolition of the old tile hidden in the install price",
    ],
    notes: [
      "Area is measured by surface with a waste factor for the pattern; diagonal, herringbone and large-format tile carry more waste",
      "Installation follows the TCNA Handbook method for the assembly; tolerances and coverage are checked before grout",
      "Substrate flatness beyond the listed prep, structural deflection and rot are priced as a change",
      "Tile, stone and grout color are owner-selected; dye-lot variation in natural stone is expected",
    ],
  },

  "millwork-cabinet": {
    basis: "cabinets and closet systems by linear ft of run or by the box; panels, moldings and shelving by linear ft; hardware and accessories each",
    steps: [
      { item: "Field measurement of the rooms and shop drawings with elevations, sections and a hardware schedule for the owner's signature", unit: "fixed" },
      { item: "Door style, species, finish and hardware samples delivered for selection and approval", unit: "fixed" },
      { item: "Fabrication of cabinet boxes: 3/4 in. plywood carcasses with edge-banded interiors, dovetailed hardwood drawer boxes, doors and drawer fronts in the chosen style", unit: "linear ft" },
      { item: "Shop finish: sprayed catalyzed conversion varnish or lacquer over stain or a tinted primer and enamel, sanded between coats", unit: "linear ft" },
      { item: "Hardware: Blum or Salice soft-close hinges and full-extension undermount drawer slides fitted in the shop", unit: "unit" },
      { item: "Delivery and protection: cabinets blanketed and staged, floors covered along the carry path", unit: "fixed" },
      { item: "Removal of the existing cabinets, shelving or closet system and disposal", unit: "linear ft", when: "existing cabinetry is being replaced" },
      { item: "Installation of base, wall and tall cabinets: leveled on shims, screwed to studs with 2-1/2 in. cabinet screws, scribed to walls and ceilings", unit: "linear ft" },
      { item: "Closet system: adjustable shelving, double-hang and long-hang rods, drawer stacks and shoe shelves mounted to cleats and studs", unit: "linear ft", when: "closets are in the scope" },
      { item: "Finished end panels, fillers, toe kicks, crown, light rail and scribe molding fitted and fastened", unit: "linear ft" },
      { item: "Interior accessories: pull-out trash, lazy susan, tray dividers, spice pull-outs, hamper and valet rod", unit: "unit", when: "accessories are in the scope" },
      { item: "Pulls and knobs drilled with a jig and installed; doors and drawers aligned and gaps set", unit: "unit" },
      { item: "Field verification of countertop template readiness and coordination with the fabricator", unit: "fixed", when: "countertops are going on the cabinets" },
      { item: "Touch-up of the finish, punch-list adjustments and cleanup after the other trades are done", unit: "hour" },
    ],
    avoid: [
      "a bare 'Cabinets' line with no construction, finish or linear ft",
      "'custom millwork' with no drawings or elevations behind it",
      "countertops and installation of appliances — other trades",
      "hardware left off or listed as 'allowance' with no count",
      "shop finish and site touch-up priced as one line",
    ],
    notes: [
      "Linear ft is measured along the wall run at the base and upper cabinets separately; tall units count as their width",
      "Shop drawings are signed before fabrication; changes after sign-off are priced as a change",
      "Walls and floors are assumed within 1/4 in. of level and plumb; heavy scribing is extra",
      "Lead time from sign-off to delivery is stated on the proposal",
    ],
  },

  "countertop-installer": {
    basis: "finished top area in sqft by material and thickness; edge profile and backsplash by linear ft; cutouts, holes and waterfall legs each",
    steps: [
      { item: "Slab or sheet material supplied: 3 cm quartz, granite, marble, quartzite, solid surface or porcelain in the selected color, viewed and tagged at the yard", unit: "sqft" },
      { item: "Digital laser template of the cabinets after they are set, with sink, cooktop and faucet locations and overhangs confirmed with the owner", unit: "fixed" },
      { item: "Removal of the existing countertops and backsplash, plumbing disconnected, debris hauled", unit: "linear ft", when: "existing tops are being replaced" },
      { item: "CNC fabrication: slab cut to template, seams planned to minimize visible joints, vein-matched where the stone allows", unit: "sqft" },
      { item: "Edge profile: eased, bullnose, ogee or mitered edge polished on all exposed edges", unit: "linear ft" },
      { item: "Undermount sink cutout polished on the reveal, with sink clips and bead of silicone; drop-in cutouts rough-cut", unit: "unit" },
      { item: "Cooktop cutout with the burner clearances the appliance requires", unit: "unit", when: "a cooktop drops into the counter" },
      { item: "Faucet, soap dispenser and filtered-water holes drilled to the fixture spec", unit: "unit" },
      { item: "Delivery and installation: tops set on beads of silicone, leveled and shimmed, seams joined with color-matched epoxy and pulled tight with seam setters", unit: "sqft" },
      { item: "Backsplash: 4 in. matching splash, or full-height slab splash behind the range and sink", unit: "linear ft", when: "a matching backsplash is in the scope" },
      { item: "Waterfall end panel mitered and joined at the island or peninsula", unit: "unit", when: "the design has a waterfall edge" },
      { item: "Steel support brackets or corbels under overhangs beyond 10 in. on quartz and 6 in. on stone", unit: "unit", when: "an overhang exceeds the unsupported limit" },
      { item: "Penetrating sealer applied to natural stone and grout lines at the seam", unit: "sqft", when: "the material is natural stone" },
      { item: "Final polish, silicone at the wall joint, protective film removed, cleanup and care instructions", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Countertop' line with no material, thickness or edge",
      "sink cutout, faucet holes and edge polish hidden inside the sqft price",
      "plumbing reconnection or the sink itself unless the fabricator supplies it",
      "'seams as needed' with no seam layout shown",
      "the backsplash priced by the sqft when it is a 4 in. strip",
    ],
    notes: [
      "Area is measured from the template including overhangs; remnants and offcuts belong to the fabricator unless listed",
      "Cabinets must be set, level and screwed down before templating; plumbing is disconnected by the owner or plumber before install day",
      "Natural stone is a natural product; color and veining vary from the sample, and seam location is set by slab size",
      "Reconnection of the sink, faucet and disposal is by the plumber the day after install once the silicone cures",
    ],
  },

  "finish-carpentry": {
    basis: "trim by linear ft by profile and material; doors, hardware, stair parts and specialty features each",
    steps: [
      { item: "Site check: material acclimated on site, walls and floors checked for level, trim layout and reveals confirmed with the owner", unit: "fixed" },
      { item: "Interior doors: pre-hung solid-core or hollow-core doors hung plumb, shimmed at the hinges, latches aligned and swing checked", unit: "unit" },
      { item: "Door hardware: hinges, passage and privacy sets, ball catches, stops and dummy levers installed and adjusted", unit: "unit" },
      { item: "Door and window casing: primed MDF, poplar or stained hardwood in the chosen profile, mitered or with head casings and back band", unit: "linear ft" },
      { item: "Window stools, aprons and jamb extensions fitted to the drywall depth", unit: "unit", when: "windows get a stool and apron instead of picture-frame casing" },
      { item: "Baseboard: profile and height selected, coped inside corners, mitered outside corners, scarfed joints over studs", unit: "linear ft" },
      { item: "Shoe molding or quarter round at the base after finished floors are down", unit: "linear ft", when: "floors are hard surface with a gap at the base" },
      { item: "Crown molding: single or built-up profile with coped inside corners, nailed into blocking or the top plate", unit: "linear ft", when: "crown is in the trim package" },
      { item: "Closet shelving and rod: 1x12 shelf on cleats with a chrome rod and center support, or a wire system", unit: "linear ft", when: "closets are in the scope" },
      { item: "Stair trim: skirt boards, treads and risers capped, handrail with brackets, newels and balusters set to code spacing", unit: "unit", when: "a stair is in the scope" },
      { item: "Specialty features: window seat, box beams, coffered grid, mantel or built-up columns per the drawings", unit: "unit", when: "specialty features are in the drawings" },
      { item: "Fastening and finish prep: 15 and 18-gauge nails, glue at miters, nail holes filled, joints caulked and sanded ready for paint", unit: "linear ft" },
      { item: "Stain-grade work: species matched, joints tight and unfilled, no exposed fasteners, delivered ready for the finisher", unit: "linear ft", when: "the trim is stained rather than painted" },
      { item: "Scrap hauled, floors vacuumed, doors and hardware protected until paint", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Trim' or 'Millwork' line with no profile, material or linear ft",
      "'doors' with no count, type or hardware",
      "painting or staining — the painter's work unless listed",
      "framing or drywall repairs — another trade",
      "trim and doors priced as one package with no breakdown",
    ],
    notes: [
      "Trim is measured by linear ft installed by profile; doors and hardware by count",
      "Walls are assumed within 1/4 in. of plumb; out-of-square openings that need extra scribing are priced as a change",
      "Paint-grade trim is delivered filled and caulked; stain-grade is delivered sanded with no filler",
      "Door hardware finish and style are owner-selected within the allowance",
    ],
  },

  "insulation-weatherization": {
    basis: "insulated area in sqft by location, material and R-value; air sealing by the hour or by penetration; blower door tests fixed",
    steps: [
      { item: "Energy assessment: blower door pre-test (CFM50 recorded), infrared scan, existing insulation depth and R-value measured, combustion appliances checked", unit: "fixed" },
      { item: "Removal of old, wet or rodent-contaminated insulation by insulation vacuum into bags, disposed of, attic sanitized", unit: "sqft", when: "existing insulation is contaminated or wet" },
      { item: "Attic air sealing: top plates, wire and pipe penetrations, chase openings and dropped soffits sealed with one-part foam, fire-rated caulk and rigid foam caps", unit: "hour" },
      { item: "Rafter baffles at every soffit vent bay to keep the air path open, with a blown-in dam at the eave", unit: "unit" },
      { item: "Attic hatch or pull-down stair: rigid dam around the opening, insulated cover, weatherstripping", unit: "unit" },
      { item: "Blown-in attic insulation: loose-fill cellulose or fiberglass to the target R-value (R-49 or R-60), depth markers installed", unit: "sqft" },
      { item: "Dense-pack wall insulation: cellulose blown through 2 in. holes drilled from the exterior or interior, holes plugged and patched", unit: "sqft", when: "existing walls are uninsulated" },
      { item: "Crawlspace floor: R-19 or R-30 unfaced batts between joists held with insulation supports, or closed-cell foam at the rim joist", unit: "sqft", when: "the crawlspace floor is uninsulated" },
      { item: "Crawlspace ground vapor barrier: 6 mil to 12 mil polyethylene lapped 12 in., sealed to piers and the wall", unit: "sqft", when: "the crawlspace has bare ground" },
      { item: "Closed-cell spray foam at the rim joist or roof deck, 2 lb density, applied to the listed thickness and R-value", unit: "sqft", when: "spray foam is specified" },
      { item: "Weatherstripping on exterior doors, door sweeps, caulk at window trim and sill plates", unit: "unit" },
      { item: "Ductwork in the attic or crawl sealed with mastic and mesh at joints and boots", unit: "linear ft", when: "ducts run through unconditioned space" },
      { item: "Blower door post-test with the before-and-after CFM50 and a rebate or utility program report", unit: "fixed" },
      { item: "Cleanup: insulation vacuumed from the living space, bags and packaging hauled, work areas wiped down", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Insulation' line with no location, material or R-value",
      "air sealing skipped or folded into the blown-in line",
      "'weatherization' as one lump sum",
      "HVAC equipment or window replacement — other trades",
      "ventilation changes without the intake and exhaust named",
    ],
    notes: [
      "Attic area is measured by the floor of the attic; walls by net wall area; R-values follow the utility program or IECC target listed",
      "Knob-and-tube wiring must be removed or made safe by an electrician before insulation covers it",
      "Rebate paperwork is prepared for the owner; the incentive is the utility's to pay",
      "Roof leaks, mold remediation and structural repairs are excluded",
    ],
  },

  "acoustic-ceiling": {
    basis: "ceiling area in sqft by grid and panel system; perimeter angle and seismic trim by linear ft; light, diffuser and access cutouts each",
    steps: [
      { item: "Submittals: reflected ceiling plan, grid and panel data sheets, seismic calculations and samples for architect approval", unit: "fixed" },
      { item: "Lifts, scaffolding and floor protection staged; room cleared and furniture covered", unit: "fixed" },
      { item: "Existing ceiling grid and panels removed, hangers cut, material hauled and disposed", unit: "sqft", when: "an existing ceiling is being replaced" },
      { item: "Layout: finished height benchmarked with a laser, grid centered so border panels are equal and no less than half a panel", unit: "fixed" },
      { item: "Hanger wires: 12-gauge galvanized wire at 4 ft o.c. to structure, three tight turns, wrapped to the main tee", unit: "sqft" },
      { item: "Perimeter wall angle: 7/8 in. or 2 in. shadowline molding leveled and fastened 16 in. o.c. at the walls", unit: "linear ft" },
      { item: "Suspension grid: 15/16 in. or 9/16 in. hot-dipped galvanized mains and cross tees (Armstrong Prelude or equal) leveled to 1/8 in. in 12 ft", unit: "sqft" },
      { item: "Seismic bracing: compression struts and four-way 12-gauge splay wires at 12 ft o.c., 2 in. wall angle and stabilizer bars per ASTM E580", unit: "sqft", when: "the project is in Seismic Design Category C or higher" },
      { item: "Cutouts and independent support for light fixtures, diffusers, sprinkler drops, speakers and sensors, with fixture clips", unit: "unit" },
      { item: "Acoustical panels: 2x2 or 2x4 mineral fiber or fiberglass lay-in with the specified NRC and CAC, tegular or square edge", unit: "sqft" },
      { item: "Specialty panels: cleanroom vinyl-faced, high-humidity, gypsum lay-in or wood or metal panels where the plans call for them", unit: "sqft", when: "a specialty panel type is specified" },
      { item: "Access panels or hinged sections at valves, dampers and junction boxes", unit: "unit" },
      { item: "Attic stock of panels and tees left for the owner, protective film removed, lifts demobilized and floors cleaned", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Ceiling' or 'ACT' line with no grid size, panel type or rating",
      "grid and panels priced as one number",
      "light fixtures and diffusers themselves — the electrician and mechanical contractor",
      "seismic bracing missing where the jurisdiction requires it",
      "'MEP coordination' as a line with no cutouts counted",
    ],
    notes: [
      "Area is measured by the room footprint; border cuts and waste are included",
      "The grid is installed after the above-ceiling MEP rough-in and before fixtures drop in",
      "Panel NRC and CAC follow the spec; substitutions are submitted for approval",
      "Structure above the ceiling is assumed able to take hanger wires; added framing is a change",
    ],
  },

  "attic-insulation": {
    basis: "attic floor area in sqft to a stated target R-value; removal and vacuuming by sqft; baffles, dams, covers and hatch each",
    steps: [
      { item: "Attic inspection: existing depth and type measured, moisture and roof leaks noted, knob-and-tube wiring, bath fans and ventilation checked, photos taken", unit: "fixed" },
      { item: "Protection: drop cloths under the hatch and along the path, blower hose run outside through a window", unit: "fixed" },
      { item: "Existing insulation vacuumed out with an insulation vacuum and bagged for disposal", unit: "sqft", when: "the old insulation is wet, compressed or contaminated" },
      { item: "Rodent cleanup: droppings vacuumed with HEPA, attic sanitized and deodorized", unit: "sqft", when: "the attic shows rodent activity" },
      { item: "Penetrations sealed before insulating: top plates, wire and pipe holes, chases and the drywall seam foamed and caulked", unit: "hour" },
      { item: "Recessed light covers: fire-rated boxes over non-IC cans so insulation can cover them safely", unit: "unit", when: "the attic has recessed lights" },
      { item: "Soffit baffles stapled in every rafter bay at the eaves to keep the intake vents open", unit: "unit" },
      { item: "Attic hatch dam and insulated cover: rigid dam around the opening, R-10 or better foam cover, weatherstripped", unit: "unit" },
      { item: "Blown-in loose-fill fiberglass or cellulose installed to the target depth for R-49 or R-60, leveled evenly across the attic", unit: "sqft" },
      { item: "Faced or unfaced fiberglass batts laid between and across the joists where blown-in does not fit", unit: "sqft", when: "batts are specified instead of blown-in" },
      { item: "Open-cell spray foam on the underside of the roof deck to bring the attic inside the conditioned space", unit: "sqft", when: "the design calls for an unvented, conditioned attic" },
      { item: "Bath and kitchen exhaust ducts connected to a roof or wall cap so they do not dump into the insulation", unit: "unit", when: "exhaust fans terminate in the attic" },
      { item: "Depth rulers placed every 300 sqft and an attic card posted with the material, depth and R-value", unit: "fixed" },
      { item: "Cleanup and paperwork: living space vacuumed, bags hauled, rebate or utility program forms prepared for the owner", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Attic insulation' line with no material, depth or R-value",
      "the hatch, baffles and light covers left out of the estimate",
      "'air sealing' folded into the blown-in line",
      "roof or ventilation work beyond baffles — the roofer's job",
      "removal priced without disposal",
    ],
    notes: [
      "Attic floor area is measured from the house footprint; the target R-value follows the IECC zone or utility program listed",
      "Knob-and-tube wiring must be deactivated or replaced by an electrician before it is covered",
      "Depth settles over time; installed depth is stated and the settled depth meets the target R-value",
      "Roof leaks and wet decking are reported and excluded from this work",
    ],
  },

  "attic-air-sealing": {
    basis: "sealed penetrations and bypasses each or by the hour; blower door tests fixed; insulation moved and replaced by sqft",
    steps: [
      { item: "Blower door pre-test at 50 pascals with the CFM50 recorded, infrared camera and smoke pencil used to map the leaks from the attic side", unit: "fixed" },
      { item: "Combustion safety test on the furnace and water heater (draft, spillage, CO) before and after sealing", unit: "fixed" },
      { item: "Existing insulation raked back from the top plates and penetrations so the seal is made at the drywall plane", unit: "sqft" },
      { item: "Top plates and drywall seams sealed with one-part expanding foam or fire-rated caulk along every interior and exterior wall", unit: "linear ft" },
      { item: "Wire, plumbing, duct and vent penetrations foamed or caulked closed", unit: "unit" },
      { item: "Chase and soffit caps: rigid foam or sheet metal cut over plumbing chases, dropped soffits and open kneewall bays, foamed at the edges", unit: "unit" },
      { item: "Recessed light covers: fire-rated boxes set and sealed over each can light", unit: "unit", when: "the attic has recessed lights" },
      { item: "Flue and chimney: sheet-metal collar sealed with high-temperature caulk keeping the required clearance to combustibles", unit: "unit", when: "a flue or chimney passes through the attic floor" },
      { item: "Attic hatch or pull-down stair weatherstripped and fitted with an insulated, latched cover", unit: "unit" },
      { item: "Bath fan and kitchen exhaust ducts connected with rigid duct to a roof or wall cap and sealed at the collar", unit: "unit", when: "fans vent into the attic" },
      { item: "Attic ducts sealed with mastic and mesh at every joint, boot and plenum seam", unit: "linear ft", when: "HVAC ducts run through the attic" },
      { item: "Insulation raked back into place and topped up to the original depth over the sealed areas", unit: "sqft" },
      { item: "Blower door post-test and a report with before-and-after leakage and a photo log of the sealed points", unit: "fixed" },
      { item: "Work areas vacuumed, foam trimmings and packaging hauled, ladders and lights removed", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Air sealing' line with no count of penetrations or bypasses",
      "sealing priced without a blower door result",
      "adding insulation as the main line — this is the sealing trade",
      "the chimney or flue sealed with foam instead of metal and high-temperature caulk",
      "'weatherization' with no list of what is sealed",
    ],
    notes: [
      "Leakage is measured at 50 pascals; the target reduction follows the utility program or the owner's goal",
      "Combustion appliances are checked before tightening the house so that back-drafting is not created",
      "Insulation is moved and replaced, not added; new insulation is a separate scope",
      "Roof leaks, wiring hazards and vermiculite are reported and excluded",
    ],
  },

  "radiant-barrier": {
    basis: "roof deck or rafter area in sqft by product and mounting method; gable walls by sqft; vents and fans each",
    steps: [
      { item: "Attic survey: roof pitch and framing, existing insulation and ventilation checked, attic temperature and access noted, layout planned", unit: "fixed" },
      { item: "Access and safety: walk boards laid across the joists, temporary lighting, insulation protected from foot traffic", unit: "fixed" },
      { item: "Radiant barrier foil supplied and installed: perforated double-sided aluminum (ASTM C1313, emissivity 0.05 or less) stapled to the underside of the rafters or truss top chords, seams lapped 2 in., a 3 in. air gap left at the ridge and eaves", unit: "sqft" },
      { item: "Gable end walls covered with foil to block radiant gain through the end walls", unit: "sqft" },
      { item: "Openings cut and edges secured around roof vents, ridge vents, chimneys and recessed lights, keeping clearance from heat sources", unit: "unit" },
      { item: "Attic-floor lay-over: perforated foil laid loose over the existing insulation where the deck cannot be reached", unit: "sqft", when: "rafters are inaccessible and the owner accepts the dust trade-off" },
      { item: "Radiant barrier coating: low-emissivity paint sprayed on the underside of the roof deck", unit: "sqft", when: "a spray-on coating is chosen instead of foil" },
      { item: "Ventilation upgrade: additional soffit or ridge vents, or a solar attic fan wired and set", unit: "unit", when: "the attic does not meet the 1-to-150 or 1-to-300 vent ratio" },
      { item: "Cleanup and documentation: scraps and staples collected, product data and photos left for utility rebate or energy credit paperwork", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Radiant barrier' line with no product, emissivity or mounting method",
      "energy-savings promises as a line item",
      "insulation or air sealing folded in as if it were the same trade",
      "the ridge and eave air gap left out of the description",
    ],
    notes: [
      "Area is measured by the roof deck or rafter surface, larger than the attic floor by the pitch factor",
      "Savings depend on climate, duct location and the existing insulation; no fixed percentage is promised",
      "Existing ventilation is assumed adequate unless the survey shows otherwise",
      "Roof leaks and wet decking are reported and not covered with foil",
    ],
  },

  "hardwood-refinishing": {
    basis: "floor area in sqft by sanding, stain and finish system; stairs each; board repairs, thresholds and shoe molding by linear ft or each",
    steps: [
      { item: "Room cleared and protected: furniture moved by the crew, doorways and HVAC registers masked with plastic, dust containment on the sanders", unit: "fixed" },
      { item: "Shoe molding or quarter round pulled and set aside for reinstallation", unit: "linear ft", when: "the base has shoe or quarter round" },
      { item: "Board repairs: split, stained or pet-damaged boards cut out and replaced with matching species weaved into the field", unit: "unit", when: "boards are damaged beyond sanding" },
      { item: "Nails set below the surface, gaps and nail holes filled with matching wood filler after the first pass", unit: "sqft" },
      { item: "Sanding: three to four passes with a drum or belt sander from 36 to 100 grit, edger at the walls, hand-scraped corners, buffed with a screen for a uniform scratch pattern", unit: "sqft" },
      { item: "Water-popping the grain before stain for an even, deeper color", unit: "sqft", when: "the floor is being stained" },
      { item: "Stain: penetrating oil or waterborne stain in the approved color from an on-floor sample, hand-applied and wiped, dried overnight", unit: "sqft", when: "the owner wants a color other than natural" },
      { item: "Finish: three coats of two-component waterborne polyurethane (Bona Traffic HD or equal) or oil-modified polyurethane in the chosen sheen, abraded between coats", unit: "sqft" },
      { item: "Hardwax oil finish (Rubio Monocoat or equal) applied and buffed in one or two coats", unit: "sqft", when: "the owner chooses a hardwax oil over polyurethane" },
      { item: "Stairs: treads and risers sanded, stained and finished by hand to match the floor", unit: "unit", when: "stairs are in the scope" },
      { item: "Thresholds, reducers and stair nosing sanded and finished with the floor or replaced", unit: "linear ft" },
      { item: "Screen and recoat only: existing finish abraded with a maroon pad and one fresh coat of finish applied", unit: "sqft", when: "the floor needs a recoat instead of a full sand" },
      { item: "Shoe molding reinstalled and touched up after the final coat", unit: "linear ft", when: "shoe or quarter round was removed" },
      { item: "Final cleanup, dust removed from sills and ledges, cure schedule explained (foot traffic, furniture and rugs) and care kit left", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Refinish floors' line with no grit sequence, coats or finish product",
      "sanding and finishing priced as one number",
      "stain listed with no sample approval step",
      "carpet removal, subfloor repair or new flooring — the flooring installer's work",
      "'dust-free' promised without a containment system named",
    ],
    notes: [
      "Area is measured by the floor surface; closets and stair landings are included when listed",
      "Solid floors sand three to five times in their life; boards under 3/32 in. above the tongue are reported before sanding",
      "Stain color is approved from a sample on the actual floor; species and old finish affect the result",
      "Waterborne finish takes light traffic in 24 hours, furniture in 72 hours and rugs after 2 weeks",
    ],
  },

  "trim-molding": {
    basis: "molding by linear ft by profile and material; corner blocks, rosettes, medallions and beams each",
    steps: [
      { item: "Profile selection: samples of the crown, chair rail, casing and base profiles in MDF, primed finger-joint pine, poplar or PVC brought for approval", unit: "fixed" },
      { item: "Existing molding pried off, nails pulled, walls patched where the old profile was smaller", unit: "linear ft", when: "existing molding is being replaced" },
      { item: "Studs and ceiling joists located; continuous backing or a plywood nailer installed where the crown spans an unsupported ceiling", unit: "linear ft", when: "the crown runs parallel to the joists with nothing to nail into" },
      { item: "Crown molding: profile cut on a compound miter saw, inside corners coped, outside corners mitered, scarf joints glued over studs, nailed with 15-gauge finish nails", unit: "linear ft" },
      { item: "Built-up crown: two or three stacked pieces (base cap, cove and crown) assembled for a taller profile", unit: "linear ft", when: "the design calls for built-up crown" },
      { item: "Chair rail or picture rail set at the approved height, level around the room, coped at corners", unit: "linear ft" },
      { item: "Baseboard and base cap in the matching profile, coped inside corners, mitered outside corners", unit: "linear ft" },
      { item: "Casing upgrade: window and door casing with back band, head casing with crown and fillet, plinth blocks at the floor", unit: "linear ft" },
      { item: "Corner blocks, rosettes and plinth blocks at door and window corners", unit: "unit", when: "the style uses blocks instead of mitered corners" },
      { item: "Ceiling medallions, decorative brackets or corbels adhered and fastened to blocking", unit: "unit", when: "the design includes medallions or corbels" },
      { item: "Coffered ceiling grid: box beams built from MDF or poplar, wrapped and trimmed with crown inside each coffer", unit: "linear ft", when: "a coffered ceiling is in the scope" },
      { item: "Nail holes filled, joints and gaps caulked with paintable caulk, sanded and spot-primed ready for paint", unit: "linear ft" },
      { item: "Finish: two coats of enamel or stain and clear coat on the new molding", unit: "linear ft", when: "finishing is in the scope" },
      { item: "Offcuts hauled, floors vacuumed, walls touched up where the old molding was removed", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Molding' or 'Trim' line with no profile, size or material",
      "crown priced without stating whether corners are coped or mitered",
      "doors and door hardware — the finish carpenter's package",
      "drywall repair beyond patching the old trim line — another trade",
      "built-up profiles priced as a single piece",
    ],
    notes: [
      "Molding is measured by linear ft installed per profile; corners and returns add waste",
      "Profiles are stocked in 16 ft lengths; walls longer than a stick carry a scarf joint",
      "Walls and ceilings are assumed reasonably flat; bowed ceilings are scribed or caulked, not rebuilt",
      "Painting is by the painter unless the finish line is included",
    ],
  },

  wainscoting: {
    basis: "wall area in sqft by style, material and height; cap rail, chair rail, base and panel molding by linear ft; outlet extenders each",
    steps: [
      { item: "Layout: panel height (32 to 42 in.), stile spacing and panel widths drawn on the wall, outlets and switches located, a mock-up section approved", unit: "fixed" },
      { item: "Existing baseboard and chair rail removed, nails pulled and the wall patched", unit: "linear ft", when: "existing trim is in the way of the new paneling" },
      { item: "Wall prep: studs located and marked, high spots sanded, texture skimmed flat where panels will bear", unit: "sqft" },
      { item: "Beadboard: 4x8 MDF or PVC beadboard sheets or tongue-and-groove planks glued and nailed to the studs with the seams hidden behind stiles", unit: "sqft", when: "the style is beadboard" },
      { item: "Raised or flat-panel wainscoting: rails and stiles in 1x4 or 1x6 MDF or poplar with panel molding or applied raised panels", unit: "sqft", when: "the style is raised or flat panel" },
      { item: "Board and batten: 1x4 or 1x6 battens over a skim-flat wall or MDF backer at the approved spacing, glued and nailed", unit: "sqft", when: "the style is board and batten" },
      { item: "Shiplap or nickel-gap boards run level with the gap set by spacers, nailed to studs", unit: "sqft", when: "the style is shiplap" },
      { item: "Cap rail or chair rail with a cove or base cap under it, coped at corners", unit: "linear ft" },
      { item: "Baseboard or base shoe at the floor to finish the bottom edge", unit: "linear ft" },
      { item: "Outlet and switch boxes brought flush with box extenders and new plates", unit: "unit" },
      { item: "Nail holes filled, seams and edges caulked with paintable caulk, sanded and primed", unit: "sqft" },
      { item: "Two coats of enamel in the chosen sheen brushed and rolled on the paneling and trim", unit: "sqft", when: "painting is in the scope" },
      { item: "Scraps hauled, floors vacuumed and the room dusted", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Wainscoting' line with no style, material or height",
      "the cap rail and base priced inside the sqft",
      "outlet extenders forgotten",
      "electrical relocation — the electrician's work",
      "'paneling' with no note on how seams are hidden",
    ],
    notes: [
      "Area is measured by wall length times panel height; the cap and base by linear ft",
      "MDF is used for paint grade, poplar or oak for stain grade; PVC where moisture is a concern",
      "Wall texture heavier than orange peel is skimmed flat inside the panels or covered with a backer",
      "Painting is included only where the finish line is listed",
    ],
  },

  "built-in-cabinetry": {
    basis: "built-ins by linear ft of face or each unit; doors, drawers, shelves and hardware each; lighting and electrical by device",
    steps: [
      { item: "Design consultation and field measurement, then scaled drawings with elevations, a section and a hardware and finish schedule for sign-off", unit: "fixed" },
      { item: "Finish and hardware samples: paint color, stain on the chosen species, door style and pull samples delivered for approval", unit: "fixed" },
      { item: "Carcass fabrication: 3/4 in. hardwood plywood boxes with 1/4 in. backs, adjustable shelves on 32 mm pin holes, face frames in poplar or the stain species", unit: "linear ft" },
      { item: "Doors and drawer fronts: shaker, flat or beaded panel in MDF or hardwood, sized with 1/8 in. reveals", unit: "unit" },
      { item: "Drawer boxes: dovetailed 5/8 in. maple with full-extension soft-close undermount slides", unit: "unit" },
      { item: "Shop finish: sprayed lacquer, conversion varnish or enamel over primer, sanded between coats", unit: "linear ft" },
      { item: "Site prep: baseboard cut back, wall patched and the floor checked for level at the footprint", unit: "linear ft" },
      { item: "Installation: units leveled on a base platform, scribed to the walls and ceiling, screwed to studs, sections joined flush", unit: "linear ft" },
      { item: "Face trim: crown, light valance, base, fillers and scribe molding fitted so the unit reads as built into the wall", unit: "linear ft" },
      { item: "Electrical: receptacles inside the cabinet, LED puck or tape lighting with a driver and dimmer, switched at the unit", unit: "unit", when: "lighting or outlets are in the unit" },
      { item: "Media provisions: cable chases, grommets, ventilated equipment shelves and an infrared repeater", unit: "unit", when: "the built-in houses electronics" },
      { item: "Pulls and knobs installed, hinges and slides adjusted, doors and drawers aligned", unit: "unit" },
      { item: "Window seat cushion top, desk surface or a stone or wood countertop on the base unit", unit: "unit", when: "the built-in has a seat or counter surface" },
      { item: "Finish touch-up, hardware final check, protective covering removed and the area cleaned", unit: "fixed" },
    ],
    avoid: [
      "'Built-ins' as one lump line with no drawings or dimensions",
      "doors, drawers and shelves uncounted",
      "wiring the lighting circuit to the panel — the electrician's work",
      "the finish left unspecified",
      "site install and shop fabrication priced as one number",
    ],
    notes: [
      "Linear ft is measured across the face of the unit; height and depth are stated on the drawings",
      "Drawings are signed before fabrication; changes after sign-off are priced as a change",
      "Walls and floors are assumed within 1/4 in. of level; heavy scribing is extra",
      "A licensed electrician makes the final connection where a new circuit is needed",
    ],
  },

  "residential-soundproofing": {
    basis: "treated wall, ceiling or floor area in sqft by assembly and STC or IIC target; doors, windows, seals and penetrations each",
    steps: [
      { item: "Acoustic assessment: noise source and flanking paths identified, existing assembly opened at one spot, sound-level readings taken and the STC or IIC target set", unit: "fixed" },
      { item: "Protection and containment: floors covered, plastic on doorways, furniture moved and covered", unit: "fixed" },
      { item: "Existing drywall or ceiling removed to the framing and disposed of", unit: "sqft", when: "the assembly is being rebuilt rather than added to" },
      { item: "Cavity fill: 3 in. mineral wool batts (Rockwool Safe-n-Sound or equal) friction-fit between the studs or joists", unit: "sqft" },
      { item: "Decoupling: sound-isolation clips (Kinetics IsoMax or equal) and 25-gauge hat channel 24 in. o.c., or resilient channel on the framing", unit: "sqft" },
      { item: "Mass-loaded vinyl, 1 lb per sqft, hung over the framing and lapped and taped at the seams", unit: "sqft", when: "the target calls for added mass beyond double drywall" },
      { item: "Two layers of 5/8 in. Type X drywall with a damping compound (Green Glue) between the layers, joints staggered", unit: "sqft" },
      { item: "Acoustical sealant at the perimeter of every layer, at the floor and ceiling joints and around penetrations", unit: "linear ft" },
      { item: "Putty pads on the back of electrical boxes and backer boxes at recessed lights", unit: "unit" },
      { item: "Solid-core door with a perimeter gasket kit and an automatic door bottom, hung in a sealed frame", unit: "unit" },
      { item: "Floor: acoustic underlayment or a floating floor over rubber isolation mat for footfall noise", unit: "sqft", when: "impact noise from above is in the scope" },
      { item: "Window treatment: laminated acoustic interior insert panels over the existing windows", unit: "unit", when: "windows are a major noise path" },
      { item: "HVAC: flexible duct connectors, lined duct or an in-line silencer where ducts link the rooms", unit: "unit", when: "ducts connect the treated room to the noise source" },
      { item: "Drywall taped and finished to Level 4 and primed, trim reinstalled over the new wall thickness", unit: "sqft" },
      { item: "Post-treatment sound readings compared to the baseline, report given, dust cleaned and furniture returned", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Soundproofing' line with no assembly or target rating",
      "'acoustic foam' as if it stopped transmission",
      "double drywall listed without the damping compound or decoupling named",
      "flanking paths (doors, ducts, outlets) ignored",
      "the finished wall priced without the sealant and putty pads",
    ],
    notes: [
      "Area is measured by the wall, ceiling or floor surface treated; STC and IIC targets follow lab-tested assemblies, field results run lower",
      "Flanking through untreated walls, ducts and floors limits the result and is stated on the proposal",
      "Trim, outlets and door frames are extended for the thicker wall; painting is excluded unless listed",
      "Rooms are unusable during the work; the schedule states the days",
    ],
  },

  "interior-remodel": {
    basis: "the rooms in scope itemized by task: demolition and finishes by sqft, walls and trim by linear ft, openings, fixtures and devices each, permits fixed",
    steps: [
      { item: "Permits, plans and inspections: building permit with a floor plan, electrical and plumbing permits, rough and final inspections", unit: "fixed" },
      { item: "Protection and containment: floor protection along the path, plastic dust walls with zipper doors, HVAC returns sealed, a negative-air machine running", unit: "fixed" },
      { item: "Demolition of finishes: flooring, drywall, ceilings, trim and fixtures removed to the framing, debris carried out", unit: "sqft" },
      { item: "Dumpster rental and dump fees for the demolition debris", unit: "fixed" },
      { item: "Structural changes: bearing wall removed with a temporary shore, engineered LVL header, posts and pads set per the engineer's letter", unit: "linear ft", when: "a bearing wall is removed or an opening is enlarged" },
      { item: "Non-bearing walls removed or new 2x4 partitions framed 16 in. o.c. with door openings and blocking", unit: "linear ft" },
      { item: "Rough electrical: new circuits, receptacles to NEC spacing, switch loops, recessed LED cans, smoke and CO detectors interconnected", unit: "unit" },
      { item: "Rough plumbing: supply and drain lines moved or added for relocated fixtures", unit: "unit", when: "a fixture moves or is added" },
      { item: "HVAC: supply and return registers relocated, ducts extended or a mini-split head added to the changed rooms", unit: "unit", when: "the room layout changes the air distribution" },
      { item: "Insulation in exterior walls and ceilings opened during the work, R-15 walls and R-38 ceilings", unit: "sqft", when: "exterior walls or ceilings are opened" },
      { item: "Drywall: 1/2 in. board hung on new walls and patches, 5/8 in. on ceilings, taped and finished to Level 4 with texture matched to the existing", unit: "sqft" },
      { item: "Interior doors and windows: pre-hung doors hung and cased, replacement windows set and trimmed", unit: "unit" },
      { item: "Flooring: new floor over the proper underlayment, or existing hardwood patched and refinished", unit: "sqft" },
      { item: "Transitions and thresholds at doorways and material changes", unit: "linear ft" },
      { item: "Trim package: baseboard, casing, crown and closet shelving installed, filled and caulked", unit: "linear ft" },
      { item: "Paint: primer on new drywall, two coats on walls and ceilings, enamel on trim and doors", unit: "sqft" },
      { item: "Finish electrical and plumbing: devices, plates, light fixtures, fans and fixtures set and tested", unit: "unit" },
      { item: "Final clean, punch-list walk-through, final inspection sign-off and warranty paperwork", unit: "fixed" },
    ],
    avoid: [
      "'Interior remodel' as one lump sum",
      "'demo' with no rooms or surfaces listed",
      "'structural work' with no header size or engineer named",
      "electrical and plumbing with no device or fixture count",
      "kitchen and bathroom scopes buried inside a general remodel line",
    ],
    notes: [
      "Finishes are measured by the sqft of each room; walls and trim by linear ft; fixtures and devices by count",
      "Structural changes require an engineer's letter or stamped drawing before permit; the fee is passed through",
      "Hidden conditions behind walls and floors are priced as a change once exposed",
      "Kitchens and bathrooms in the scope are itemized under their own procedures",
    ],
  },

  "laundry-room-remodel": {
    basis: "the laundry room itemized by task: cabinets and shelving by linear ft, counters and finishes by sqft, plumbing, electrical and venting by fixture",
    steps: [
      { item: "Permit for the plumbing, electrical and dryer venting changes with the rough and final inspections", unit: "fixed", when: "the plumbing, electrical or vent route changes" },
      { item: "Protection and machine handling: washer and dryer disconnected, capped and moved out of the room, floors protected", unit: "unit" },
      { item: "Demolition of cabinets, shelving, flooring and damaged drywall, debris bagged and hauled", unit: "sqft" },
      { item: "Plumbing: recessed laundry box with quarter-turn valves and hammer arrestors, 2 in. standpipe and trap, supply and drain for a utility sink", unit: "unit" },
      { item: "Electrical: dedicated 20A laundry circuit, NEMA 14-30 dryer receptacle on a 30A/240V circuit, GFCI receptacles, lighting and a switch", unit: "unit" },
      { item: "Dryer vent: 4 in. rigid metal duct to the exterior with a backdraft damper hood, run under the 35 ft equivalent length limit", unit: "linear ft" },
      { item: "Gas line to the dryer in black iron or CSST with a shutoff valve and flex connector", unit: "unit", when: "the dryer is gas" },
      { item: "Floor drain or a washer drain pan piped to a drain to protect the floor below", unit: "unit", when: "the laundry is above a finished floor" },
      { item: "Drywall patched where lines were run, moisture-resistant board at the wet wall, finished and textured to match", unit: "sqft" },
      { item: "Flooring: waterproof LVP or porcelain tile over the proper underlayment", unit: "sqft" },
      { item: "Cabinets: wall cabinets over the machines, a tall broom or pantry cabinet, base cabinet at the sink", unit: "linear ft" },
      { item: "Countertop over the machines or the base cabinet in laminate or quartz with a sink cutout", unit: "sqft" },
      { item: "Utility sink and faucet set and connected", unit: "unit" },
      { item: "Hanging rod, folding station shelf and open shelving mounted to studs", unit: "linear ft" },
      { item: "Walls and ceiling painted two coats in a scrubbable satin", unit: "sqft" },
      { item: "Baseboard, casing and door trim installed and caulked", unit: "linear ft" },
      { item: "Washer and dryer set, leveled, connected and run through a test cycle, vent connection checked", unit: "unit" },
      { item: "Final clean and walk-through", unit: "fixed" },
    ],
    avoid: [
      "'Laundry remodel' as one lump sum",
      "the dryer vent left off or listed with no material or length",
      "the washer box, drain and dryer receptacle folded into one 'hookups' line",
      "the appliances themselves unless the contractor supplies them",
      "cabinets listed with no linear ft",
    ],
    notes: [
      "Cabinets and shelving are measured by linear ft; counters and finishes by sqft; each connection by count",
      "Appliances are owner-supplied and set by the contractor unless listed",
      "The dryer vent route is checked before the price is final; a run over the limit needs a booster fan priced as a change",
      "Water damage found under the old flooring is priced as a change",
    ],
  },

  "home-office-buildout": {
    basis: "the office itemized by task: partitions and trim by linear ft, electrical and data by drop or device, built-ins by linear ft, finishes by sqft",
    steps: [
      { item: "Permit and inspections for new walls, circuits and the closet or door changes", unit: "fixed", when: "walls are added or new circuits run" },
      { item: "Protection: floor covering, plastic on the doorway and dust control while the room is opened", unit: "fixed" },
      { item: "Removal of existing closet, carpet, shelving or a wall to make the room", unit: "sqft", when: "the space is a conversion" },
      { item: "Framing: new 2x4 partition 16 in. o.c. with a door opening, or a closet framed for equipment and storage", unit: "linear ft", when: "the plan adds a wall" },
      { item: "Sound insulation: mineral wool in the office walls and ceiling for privacy on calls", unit: "sqft" },
      { item: "Electrical: dedicated 20A circuit, receptacles at desk height and floor, USB-C outlets, a circuit for equipment, dimmable recessed LED lighting", unit: "unit" },
      { item: "Data and low voltage: Cat6 drops to a patch panel or the router, coax or fiber where needed, conduit for future cabling", unit: "unit" },
      { item: "Task and accent lighting: pendant or sconce boxes, under-shelf LED strips with a driver", unit: "unit" },
      { item: "HVAC: supply and return extended or a ductless mini-split added so the closed room holds temperature", unit: "unit", when: "the room lacks its own supply and return" },
      { item: "Drywall: new board on the partition, patches at boxes and drops, finished to Level 4", unit: "sqft" },
      { item: "Door: solid-core pre-hung door with a perimeter seal and privacy lock", unit: "unit" },
      { item: "Glass partition or French doors to borrow light", unit: "unit", when: "the design uses a glass wall or French doors" },
      { item: "Flooring: LVP, carpet tile or hardwood with transitions at the door", unit: "sqft" },
      { item: "Built-ins: desk with cable management, shelving, filing drawers and a credenza in plywood with a shop finish", unit: "linear ft" },
      { item: "Walls and ceiling painted two coats; an accent wall behind the camera position", unit: "sqft" },
      { item: "Baseboard, casing and shoe installed and caulked", unit: "linear ft" },
      { item: "Devices trimmed out, network tested, lighting scenes set, final clean and walk-through", unit: "fixed" },
    ],
    avoid: [
      "'Office build-out' as one lump sum",
      "electrical and data listed as one 'wiring' line",
      "built-ins with no linear ft or drawing",
      "furniture and monitors unless the contractor supplies them",
      "window replacement or exterior work — another trade",
    ],
    notes: [
      "Walls and trim by linear ft; devices and drops by count; built-ins by linear ft of face",
      "A bedroom converted to an office keeps its egress window and closet unless the owner accepts the change",
      "Network equipment and furniture are owner-supplied unless listed",
      "Hidden wiring or plumbing found in the walls is priced as a change",
    ],
  },

  "garage-conversion": {
    basis: "the converted space by sqft of floor with walls, insulation and finishes by sqft, openings and fixtures each, permits and structural fixed",
    steps: [
      { item: "Permits and plans: floor plan, energy compliance, zoning and parking review, ADU review where it applies, all inspections", unit: "fixed" },
      { item: "Protection and demolition: garage door and opener removed, shelving and hooks cleared, slab cleaned and inspected", unit: "fixed" },
      { item: "Garage door opening infilled: 2x6 wall framed on a curb, sheathed, wrapped, insulated and finished with siding and trim to match the house", unit: "unit" },
      { item: "Windows and exterior door: egress window and a weather-rated entry door set in the infill or side walls, flashed and trimmed", unit: "unit" },
      { item: "Floor: slab moisture-tested, 6 mil vapor barrier and pressure-treated sleepers with plywood or a floating subfloor to bring the floor level with the house", unit: "sqft" },
      { item: "Slab replaced or a raised framed floor built where the slab slopes to the door", unit: "sqft", when: "the slab slope or height cannot be leveled with sleepers" },
      { item: "Interior framing: partitions for a bedroom, bath or closet, furring on the masonry walls", unit: "linear ft", when: "the plan divides the space" },
      { item: "Insulation: R-15 in the walls, R-38 or R-49 in the ceiling, R-10 under the floor, air-sealed at the top plates", unit: "sqft" },
      { item: "Fire separation: 5/8 in. Type X drywall and a self-closing 20-minute door where the space still borders the house or a remaining garage", unit: "sqft", when: "part of the garage stays a garage or the wall is a rated separation" },
      { item: "Electrical: sub-panel or new circuits, receptacles to NEC spacing, lighting, smoke and CO detectors, bath and kitchen circuits", unit: "unit" },
      { item: "Plumbing rough-in for a bathroom or kitchenette: drains cut into the slab, supply lines and a water heater tie-in", unit: "unit", when: "a bathroom or kitchenette is in the plan" },
      { item: "HVAC: ductless mini-split heat pump sized for the room, or the house system extended with a supply and return", unit: "unit" },
      { item: "Drywall on walls and ceiling, taped and finished to Level 4", unit: "sqft" },
      { item: "Flooring over the new subfloor with transitions at the doors", unit: "sqft" },
      { item: "Interior doors, casing, baseboard and closet trim installed and caulked", unit: "linear ft" },
      { item: "Walls, ceiling and trim primed and painted two coats", unit: "sqft" },
      { item: "Exterior restoration: driveway apron and landscaping at the old door, gutters extended over the infill", unit: "sqft", when: "the driveway or grade meets the old door opening" },
      { item: "Final inspection, certificate of occupancy, final clean and walk-through", unit: "fixed" },
    ],
    avoid: [
      "'Garage conversion' as one lump sum",
      "the door opening infill left out or listed with no wall construction",
      "the slab and floor system skipped",
      "'HVAC' or 'electrical' with no unit or circuit count",
      "detached-structure foundation or roof replacement folded in as an assumption",
    ],
    notes: [
      "Floor and finishes are measured by the sqft of the garage; the infill opening, windows and doors by count",
      "Zoning may require replacement parking; the review fee and any survey are passed through",
      "The slab is assumed sound; cracks, settling or a slab below the flood elevation are priced as a change",
      "Energy code compliance follows the local IECC or Title 24 requirement",
    ],
  },

  fireplace: {
    basis: "the appliance each; venting and gas line by linear ft; hearth, surround and finishes by sqft; mantel and commissioning each or fixed",
    steps: [
      { item: "Site review and permit: clearances to combustibles, vent route and termination location checked, gas load confirmed, mechanical and gas permits pulled", unit: "fixed" },
      { item: "Protection: floors covered from the entry to the fireplace wall, furniture moved and covered, dust barrier at the opening", unit: "fixed" },
      { item: "Existing fireplace, insert or stove removed and hauled, chimney or wall opening prepared", unit: "unit", when: "an old unit is being replaced" },
      { item: "Chase or enclosure framed with the manufacturer's clearances, a header over the unit and blocking for the mantel and finish", unit: "linear ft" },
      { item: "Direct-vent gas fireplace (ANSI Z21.88 listed) set in the framing, leveled and secured, with the log set and burner installed", unit: "unit" },
      { item: "EPA-certified wood-burning fireplace or insert set with the firebox liner and damper", unit: "unit", when: "the unit burns wood" },
      { item: "Electric fireplace recessed in the wall with a dedicated receptacle", unit: "unit", when: "the unit is electric" },
      { item: "Venting: coaxial direct-vent pipe run through the wall or roof with firestops at each floor and a listed termination cap", unit: "linear ft" },
      { item: "Class A insulated chimney from the wood unit through the roof with a storm collar, cap and spark arrestor", unit: "linear ft", when: "the unit burns wood" },
      { item: "Roof or wall flashing at the vent penetration, sealed and counterflashed", unit: "unit" },
      { item: "Gas line: 1/2 in. or 3/4 in. black iron or CSST from the nearest supply with a shutoff, drip leg and flex connector, pressure-tested", unit: "linear ft" },
      { item: "Electrical: 120V receptacle inside the chase for the blower, ignition and a wall switch or remote receiver", unit: "unit" },
      { item: "Hearth: non-combustible hearth extension in tile or stone to the listed depth in front of the opening", unit: "sqft" },
      { item: "Surround: tile, stone veneer or slab facing set on cement board around the opening", unit: "sqft" },
      { item: "Mantel and legs in wood, stone or cast at the listed clearance above the opening", unit: "unit" },
      { item: "Drywall around the chase, taped, finished and painted to match the room", unit: "sqft" },
      { item: "Commissioning: gas leak test, manifold pressure set, ignition and flame check, CO test, blower and remote programmed, owner walk-through", unit: "fixed" },
      { item: "Final clean, packaging hauled and the warranty registered with the manufacturer", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Fireplace' line with no unit type, model or listing",
      "venting priced as 'included' with no route or length",
      "the gas line listed with no size or pressure test",
      "the hearth extension forgotten on a wood unit",
      "chimney relining for an existing masonry fireplace — the chimney sweep's scope",
    ],
    notes: [
      "The appliance is each; vent and gas line by linear ft measured along the route; hearth and surround by sqft",
      "Clearances and vent termination follow the manufacturer's listing and NFPA 211; the inspector's sign-off is required before the surround is closed",
      "The gas meter and house supply are assumed adequate; a meter upgrade is the utility's charge",
      "Finish selections (stone, tile, mantel) are owner-selected within the allowance",
    ],
  },
};
