// Smart Proposal procedures — MEP (mechanical, electrical, plumbing, fire and low voltage). See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  electrical: {
    basis: "devices, fixtures, panels and equipment connections each; feeder and branch raceway with wire by linear feet and size; service, testing and permits fixed",
    steps: [
      { item: "Electrical permit, plan review and inspections: load calculation submitted, rough-in, service and final inspections scheduled and fees paid", unit: "fixed" },
      { item: "Submittals and coordination: one-line diagram, panel schedules, fixture and gear cut sheets, lead times confirmed with the supplier before rough-in", unit: "fixed" },
      { item: "Utility coordination: service application, meter or CT cabinet specification, scheduled shutdown and reconnect with the utility", unit: "fixed", when: "the service is new or upgraded" },
      { item: "Lockout-tagout of affected feeders, temporary power and lighting kept live for the occupied areas, floor and finish protection in the work zone", unit: "fixed" },
      { item: "Demolition: existing devices, fixtures, raceway and wire removed back to the source, abandoned conductors pulled out, boxes blanked and made safe", unit: "unit", when: "existing devices, fixtures or circuits are removed" },
      { item: "Service entrance: meter base or CT cabinet, service disconnect, service-entrance conductors sized to the calculated load, grounding electrode system (two rods, Ufer and water bond, GEC by AWG)", unit: "fixed", when: "the service is new or upgraded" },
      { item: "Distribution gear: main distribution panel and branch panelboards by amperage, voltage and space count (for example 400 A, 208Y/120 V 3-phase, 42-space), mounted, bonded and labeled", unit: "unit" },
      { item: "Feeders: EMT, rigid or Schedule 40 PVC raceway by trade size with THHN/THWN-2 copper conductors by AWG or kcmil, pulled and terminated at both ends", unit: "linear ft" },
      { item: "Branch-circuit raceway and wire: 3/4 in. EMT with #12 or #10 THHN copper, boxes, fittings and supports every 10 ft, or MC cable where the specification allows", unit: "linear ft" },
      { item: "Wiring devices: 20 A specification-grade receptacles (GFCI in wet and kitchen locations, isolated-ground where scheduled), switches, cover plates", unit: "unit" },
      { item: "Lighting fixtures: LED troffers, high-bays, strips and downlights by lumen output and color temperature, hung, wired and lamped per the fixture schedule", unit: "unit" },
      { item: "Lighting controls: occupancy and vacancy sensors, daylight-harvesting photocells, 0-10 V dimming and time-clock control as the energy code (IECC) requires", unit: "unit" },
      { item: "Emergency and exit lighting: battery-backed exit signs and emergency heads on the life-safety circuit, 90-minute test", unit: "unit" },
      { item: "Equipment connections: fused or non-fused disconnects, motor starters and sealtite whips to HVAC units, kitchen equipment, pumps and owner-furnished machines", unit: "unit" },
      { item: "Firestopping of every raceway and cable penetration through rated walls and floors with a UL-listed system, labeled", unit: "unit" },
      { item: "Testing: insulation-resistance (megger) test on feeders, lug torque to the manufacturer's values, phase rotation on three-phase equipment, GFCI and AFCI trip test", unit: "fixed" },
      { item: "Typed panel schedules, circuit and device labeling, arc-flash warning labels and as-built drawings turned over to the owner", unit: "fixed" },
      { item: "Daily cleanup, packaging and scrap wire recycled, demolished fixtures and ballasts disposed of at a licensed facility", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Electrical' or 'Wiring' line with no circuit count, wire size or raceway type",
      "'Panel' with no amperage, voltage or space count",
      "the service upgrade, panels and branch circuits rolled into one line",
      "'Lighting' with no fixture type, lumen output or count",
      "fire alarm devices, structured cabling or HVAC control wiring — separate low-voltage scopes",
      "'Miscellaneous materials' or 'general labor' lines",
    ],
    notes: [
      "Device and fixture counts come from the plans or a walk-through; raceway lengths are measured along the routed path, not point to point",
      "Utility fees, gear lead times and service upgrades are subject to the utility's approval and schedule",
      "Concealed conditions (unsafe existing wiring, asbestos, wet or full raceways) are priced as a change order",
      "Patching and painting of walls and ceilings opened for wiring is by others unless a patch line is listed",
      "Owner-furnished fixtures are installed at the labor rate shown; the fixture package is per the schedule",
    ],
  },

  plumbing: {
    basis: "fixtures and equipment each; water, waste and vent and gas piping by linear feet, size and material; permits, tests and disinfection fixed",
    steps: [
      { item: "Plumbing permit, plan review and inspections: underground, rough-in and final inspections scheduled, backflow and medical-gas permits where the project needs them", unit: "fixed" },
      { item: "Submittals: fixture schedule with cut sheets, pipe and valve schedule, isometric riser drawings and coordination with the mechanical and electrical trades", unit: "fixed" },
      { item: "Utility coordination: water and sewer tap applications, meter sizing and a scheduled shutdown of the existing service", unit: "fixed", when: "the building service is new or upsized" },
      { item: "Demolition: existing fixtures, water heaters and piping disconnected, capped at the source and removed, waste lines plugged against sewer gas", unit: "unit", when: "existing fixtures or piping are removed" },
      { item: "Saw-cut and break out the slab along the underground pipe routes, trench to grade and haul the rubble", unit: "sqft", when: "underground piping runs below an existing slab" },
      { item: "Underground sanitary and storm drainage: Schedule 40 PVC, ABS or service-weight cast iron by diameter, bedded in sand, sloped 1/4 in. per ft (1/8 in. per ft at 4 in. and larger), backfilled and compacted", unit: "linear ft" },
      { item: "Above-ground drain, waste and vent rough-in: Schedule 40 PVC solvent-weld or no-hub cast iron with stainless couplings by diameter, hung on rod and clevis, vents through the roof with lead or neoprene flashings", unit: "linear ft" },
      { item: "Domestic hot and cold water rough-in: Type L copper with lead-free solder, or PEX-A with expansion fittings, by diameter, run in trunk-and-branch layout with dielectric unions at the equipment", unit: "linear ft" },
      { item: "Hot-water recirculation return line with an aquastat-controlled bronze circulator and check valve", unit: "linear ft", when: "the building has a recirculation loop" },
      { item: "Fuel gas piping: Schedule 40 black steel threaded or CSST (bonded per the manufacturer) by size, with drip legs, unions and a shutoff at every appliance", unit: "linear ft", when: "gas appliances or equipment are on the job" },
      { item: "Fixture rough-in: stub-outs, angle stops, water-hammer arrestors on quick-closing valves, and floor- or wall-mount carriers for wall-hung fixtures", unit: "unit" },
      { item: "Cleanouts, floor drains with trap primers, floor sinks and roof drains with overflow domes set to the drawings", unit: "unit" },
      { item: "Water heating equipment: commercial tank or tankless heaters, thermostatic mixing valve (ASSE 1017), expansion tank and pressure-reducing valve set and piped", unit: "unit" },
      { item: "Reduced-pressure backflow preventer at the service entrance with test cocks and an air-gap drain", unit: "unit", when: "the water purveyor requires containment backflow protection" },
      { item: "Fixture set: water closets, urinals, lavatories, sinks, faucets and flush valves per the schedule, ADA-compliant where scheduled, sealed and adjusted", unit: "unit" },
      { item: "Pipe insulation: 1 in. fiberglass with ASJ jacket on hot, recirculation and roof-drain piping, 1/2 in. on cold in unconditioned space", unit: "linear ft" },
      { item: "Firestopping every pipe penetration through rated walls and floors with a UL-listed sleeve or collar system, labeled", unit: "unit" },
      { item: "Testing: DWV water or 5-psi air test, domestic water hydrostatic test at 100 psi for one hour, gas test at 1.5 times working pressure, all witnessed by the inspector", unit: "fixed" },
      { item: "Disinfection: potable system chlorinated and flushed per AWWA C651 with a bacteriological sample sent to the lab", unit: "fixed" },
      { item: "Startup, valve tags and pipe labels, as-built drawings and the O&M binder turned over; construction debris hauled off", unit: "fixed" },
    ],
    avoid: [
      "'Plumbing rough-in' or 'Piping' as one line with no system, size or material",
      "'Fixtures' with no count, type or model",
      "the water, DWV and gas systems priced together on one line",
      "site sewer and water more than 5 ft outside the building — a site-utility scope",
      "hydronic or HVAC condensate piping unless the brief includes it",
      "'Miscellaneous' or 'contingency' lines",
    ],
    notes: [
      "Pipe quantities are measured along the routed path from the drawings; fixture counts come from the fixture schedule",
      "Tap fees, meter charges and impact fees are passed through at the utility's published rate",
      "Rock, groundwater or contaminated soil under the slab is priced as a change order",
      "Slab, wall and ceiling patching after the underground work is by others unless a patch line is listed",
      "Fixtures are per the schedule; owner-furnished fixtures are installed at the labor rate shown",
    ],
  },

  hvac: {
    basis: "equipment and air terminals each by capacity; ductwork, refrigerant and condensate piping by linear feet and size; design, balancing and commissioning fixed",
    steps: [
      { item: "Design and submittals: block load per ASHRAE or Manual N, equipment selections, duct sizing, sequence of operations and stamped drawings submitted to the building department", unit: "fixed" },
      { item: "Mechanical permit, plan review and inspections scheduled, rebate and utility incentive paperwork filed", unit: "fixed" },
      { item: "Demolition: EPA 608 refrigerant recovery, existing units disconnected and removed, old duct and hangers taken down, all hauled and recycled", unit: "unit", when: "existing equipment is removed" },
      { item: "Crane or lift: rooftop units set with a certified rigger, lift plan, street or parking closure and flag crew for the pick day", unit: "fixed", when: "equipment is set on a roof or elevated pad" },
      { item: "Roof curbs and curb adapters matched to the new unit footprint, set level and flashed into the roof by the roofing contractor", unit: "unit", when: "equipment is set on a roof" },
      { item: "Equipment: packaged rooftop units, split systems, heat pumps or VRF outdoor units by tonnage, SEER2 or IEER rating and gas heating input (MBH), set, leveled and anchored", unit: "unit" },
      { item: "Air handlers, fan coils or indoor VRF units by CFM and cooling capacity, hung or set on isolation pads with service clearance", unit: "unit" },
      { item: "Supply and return ductwork: galvanized rectangular and spiral round by size, gauge per SMACNA, joints sealed to Seal Class A with mastic, hung on strap or trapeze", unit: "linear ft" },
      { item: "Duct insulation: R-6 or R-8 foil-faced wrap on ducts outside the conditioned space, or 1 in. acoustic liner where specified", unit: "sqft" },
      { item: "Air terminals: diffusers, grilles, registers, VAV terminal units, balancing dampers and fire or smoke dampers at rated walls, set to the drawings", unit: "unit" },
      { item: "Refrigerant piping: ACR copper by size, brazed under a nitrogen purge, insulated with closed-cell foam and UV-protected outdoors", unit: "linear ft" },
      { item: "Condensate drains: Schedule 40 PVC with a trap sized to the unit's static pressure, secondary pan and float switch at each indoor unit", unit: "linear ft" },
      { item: "Gas piping and flue venting to gas-fired units: black steel or CSST with drip leg and shutoff, Category IV PVC or stainless vent terminated per the manufacturer", unit: "linear ft", when: "units are gas-fired" },
      { item: "Exhaust fans, make-up air and energy-recovery ventilators by CFM with roof or wall hoods and backdraft dampers", unit: "unit", when: "the design includes exhaust or ventilation air" },
      { item: "Controls: thermostats or DDC controllers, economizer and CO2 demand-ventilation sensors, control wiring and points tied to the building automation system", unit: "unit" },
      { item: "Evacuation to 500 microns, refrigerant charge weighed in and verified by subcooling and superheat, startup and manufacturer start-up sheet on each system", unit: "unit" },
      { item: "Test, adjust and balance: every terminal balanced to design CFM, static pressure profile, with a NEBB or AABC report", unit: "fixed" },
      { item: "Commissioning: sequence of operations verified point by point, O&M manuals, warranty registration and owner training", unit: "fixed" },
      { item: "Cleanup, protective wrap and packaging removed, construction filters replaced with new at turnover", unit: "fixed" },
    ],
    avoid: [
      "'HVAC system' or 'Equipment' as one line with no tonnage, efficiency rating or count",
      "'Ductwork' with no size, gauge or seal class",
      "the crane, curb and unit priced as one line",
      "line-voltage electrical feeders and disconnects — the electrical scope",
      "roofing repairs around the curbs — the roofing scope",
      "'Miscellaneous' or 'general labor' lines",
    ],
    notes: [
      "Equipment capacities come from the load calculation; duct quantities are measured along the routed path from the drawings",
      "Structural reinforcement of the roof or pad for heavier equipment is by others unless listed",
      "Electrical power to the disconnect is by the electrical contractor; low-voltage control wiring is included here",
      "Balancing assumes the ductwork is complete and the building is enclosed",
      "Utility rebates are applied for on the owner's behalf but are not guaranteed",
    ],
  },

  "fire-protection": {
    basis: "sprinkler heads each; pipe by linear feet, size and schedule; riser, backflow, fire pump, design and tests fixed",
    steps: [
      { item: "Hydraulic design: hydrant flow test (static and residual), hazard classification per NFPA 13, density and design area, stamped drawings and hydraulic calculations submitted to the AHJ and the owner's insurer", unit: "fixed" },
      { item: "Fire sprinkler permit, plan review, rough-in and final inspections with the fire marshal witnessing the tests", unit: "fixed" },
      { item: "Impairment plan and fire watch while the existing system is out of service, tags posted and the monitoring company notified", unit: "fixed", when: "an existing sprinkler system is taken down during the work" },
      { item: "Underground fire service: C900 PVC or ductile iron by size from the tap to the riser room, thrust blocks, flushed per NFPA 24 before connection", unit: "linear ft", when: "a new fire service is brought to the building" },
      { item: "Riser assembly: OS&Y or butterfly control valve with tamper switch, alarm check or riser check valve, waterflow switch, pressure gauges, main drain and inspector's test connection", unit: "unit" },
      { item: "Double-check or reduced-pressure detector assembly at the fire service as the water purveyor requires, with test cocks and drain", unit: "unit", when: "the purveyor requires backflow protection on the fire line" },
      { item: "Fire department connection with check valve, ball drip and sign, piped to the riser", unit: "unit" },
      { item: "Fire pump and jockey pump with controllers, test header and flow meter, sized to the demand", unit: "fixed", when: "the water supply cannot meet the hydraulic demand" },
      { item: "Feed and cross mains: Schedule 10 black steel with grooved couplings or Schedule 40 threaded, by size, hung per NFPA 13", unit: "linear ft" },
      { item: "Branch lines: 1 in. to 1-1/4 in. Schedule 40 threaded steel, or listed CPVC in light-hazard areas, with armovers and drops to each head", unit: "linear ft" },
      { item: "Sprinkler heads: pendent, upright, sidewall or concealed by K-factor and temperature rating, with escutcheons or cover plates", unit: "unit" },
      { item: "Seismic sway bracing and flexible couplings at the riser and across seismic joints", unit: "unit", when: "the jurisdiction requires seismic bracing" },
      { item: "Dry-pipe or preaction valve with air compressor or nitrogen generator and low-point drains", unit: "fixed", when: "piping serves an unheated area" },
      { item: "Standpipe hose valves and connections at each floor landing", unit: "unit", when: "the building requires a standpipe" },
      { item: "Firestopping at every pipe penetration through rated walls and floors with a listed system", unit: "unit" },
      { item: "Hydrostatic test at 200 psi for two hours, system flush, main drain test, waterflow alarm test and the contractor's material and test certificate", unit: "fixed" },
      { item: "Waterflow and tamper switches wired to the fire alarm panel or a dedicated communicator for monitoring", unit: "fixed" },
      { item: "Hydraulic placard, valve signs, spare head cabinet with wrench, and as-built drawings turned over", unit: "fixed" },
      { item: "Cleanup, cutting oil wiped from the piping and scrap hauled off", unit: "fixed" },
    ],
    avoid: [
      "'Sprinkler system' or 'Piping' as one line with no size, schedule or head count",
      "'Design' with no flow test, hazard classification or calculation deliverable",
      "the riser, backflow and fire pump priced as one line",
      "the fire alarm panel and notification devices — a separate scope",
      "ceiling repair around the heads — a finish scope unless listed",
      "'Miscellaneous' or 'contingency' lines",
    ],
    notes: [
      "Pipe quantities are measured from the stamped drawings; head count is from the layout at the stated coverage",
      "Water supply is assumed adequate per the flow test; a fire pump or tank is priced as a change if the calculation fails",
      "Tap fees, purveyor charges and fire marshal fees are passed through at the published rate",
      "Ceiling patching around heads and access openings is by others unless listed",
    ],
  },

  "security-lowvoltage": {
    basis: "cable drops and devices each; pathways and backbone by linear feet; head-end, programming and commissioning fixed",
    steps: [
      { item: "Site survey and design: device locations, camera fields of view, door hardware schedule, riser diagram and IT coordination on switch ports, VLANs and IP addressing", unit: "fixed" },
      { item: "Low-voltage permit and inspection where the jurisdiction requires one", unit: "fixed", when: "the jurisdiction permits low-voltage work" },
      { item: "Pathways: J-hooks, bridle rings, conduit sleeves and core drills through walls and floors, surface raceway in finished spaces, firestopped where rated", unit: "linear ft" },
      { item: "Structured cabling: Category 6 or 6A plenum-rated cable per drop, terminated to keystone jacks and patch panels, labeled to the drawings", unit: "unit" },
      { item: "Fiber backbone: OM4 multimode or OS2 single-mode by strand count, terminated LC and tested end to end", unit: "linear ft", when: "buildings or floors are linked by fiber" },
      { item: "Telecom rack or wall cabinet with patch panels, cable management, PDU, UPS and grounding busbar", unit: "unit" },
      { item: "Device cabling: 18/2, 22/4 and composite reader cable, siamese coax or Cat 6 for PoE, pulled from the head-end to each device", unit: "linear ft" },
      { item: "Access control per door: controller, reader, electric strike or mag lock, request-to-exit sensor, door contact and power supply", unit: "unit" },
      { item: "Video surveillance: IP cameras by resolution and lens (dome, bullet, turret, PTZ), network video recorder with storage sized to the retention period, monitors", unit: "unit" },
      { item: "Intrusion detection: control panel, keypads, door and window contacts, motion and glass-break detectors, siren and cellular or IP communicator", unit: "unit" },
      { item: "Intercom or video entry stations at the entrances tied to the access system", unit: "unit", when: "the design includes intercom or video entry" },
      { item: "PoE network switches sized to the device count and power budget, configured on the security VLAN", unit: "unit" },
      { item: "Head-end build-out: enclosures, power supplies, battery backup and grounding at the equipment room", unit: "fixed" },
      { item: "Programming: credentials and schedules, camera views and recording rules, alarm partitions, notifications and the mobile app", unit: "fixed" },
      { item: "Testing and certification: every drop certified to TIA-568 with a printed test report, camera focus and walk test of every device", unit: "fixed" },
      { item: "Monitoring account activation with the central station and signal test", unit: "fixed", when: "the system is centrally monitored" },
      { item: "Owner training, as-built drawings and device schedule; packaging and cable scrap hauled off", unit: "fixed" },
    ],
    avoid: [
      "'Cabling' or 'Wiring' with no category, count or termination",
      "'Cameras' or 'Security system' with no device type or count",
      "line-voltage circuits and outlets — the electrical scope",
      "door hardware replacement (closers, hinges, frames) — the door hardware scope",
      "'Miscellaneous' or 'programming and labor' lines with nothing in them",
    ],
    notes: [
      "Drop and device counts come from the survey; pathway lengths are measured along the routed path",
      "Network switch ports, internet service and static IP addresses are provided by the owner's IT unless listed",
      "Monitoring and cloud video fees are recurring and quoted separately",
      "Patching and painting of walls opened for cabling is by others unless listed",
    ],
  },

  "residential-electrical": {
    basis: "outlets, switches, fixtures and circuits each; homerun wire by linear feet; service, panel and permits fixed",
    steps: [
      { item: "Electrical permit with rough-in and final inspections scheduled with the building department", unit: "fixed" },
      { item: "Utility coordination: meter pull and reconnect scheduled with the power company", unit: "fixed", when: "the service or meter is replaced" },
      { item: "Floors, furniture and finishes protected, power shut off and locked out for the work areas", unit: "fixed" },
      { item: "Old fixtures, devices and abandoned wiring removed, dead wires terminated in accessible junction boxes, materials hauled away", unit: "unit", when: "existing fixtures or devices are replaced" },
      { item: "Service upgrade: 200 A meter-main or meter base, service-entrance conductors, two 8-ft ground rods, #4 copper grounding electrode conductor, water and gas bonding", unit: "fixed", when: "the service is upgraded" },
      { item: "Panel replacement: 200 A 40-space main breaker panel, existing circuits landed on new breakers with AFCI and GFCI protection where the code requires, directory typed", unit: "fixed", when: "the panel is replaced" },
      { item: "Subpanel: 100 A or 125 A panel fed with 2-2-2-4 aluminum SER or copper feeder, separate ground and neutral bars, for the garage, addition or shop", unit: "unit", when: "a subpanel is added" },
      { item: "New branch-circuit homerun: 14-2 or 12-2 NM-B (Romex) from the panel to the first box on a 15 A or 20 A breaker, stapled and protected", unit: "linear ft" },
      { item: "Wire fished through finished walls and ceilings, with access holes cut and blocks drilled", unit: "unit", when: "the wiring runs through finished walls or ceilings" },
      { item: "Receptacles and switches: tamper-resistant 15 A or 20 A, GFCI in kitchen, bath, garage and outdoor locations, dimmers and 3-way switches, boxes and plates", unit: "unit" },
      { item: "Light fixtures: 4 in. or 6 in. LED recessed wafers, surface fixtures, ceiling fans on fan-rated braced boxes, exterior fixtures", unit: "unit" },
      { item: "Interconnected smoke and carbon monoxide alarms in bedrooms, hallways and on each floor", unit: "unit" },
      { item: "Dedicated appliance circuit: range, dryer, EV charger or hot tub on 30 A to 60 A, 10-3 or 6-3 NM-B, with the NEMA receptacle or hardwired connection", unit: "unit", when: "a major appliance or EV charger is added" },
      { item: "Exterior weather-resistant GFCI receptacles with in-use covers", unit: "unit", when: "outdoor outlets are added" },
      { item: "Code corrections: ungrounded outlets replaced with GFCI-protected devices, open splices boxed, double-tapped breakers corrected, missing bonding added", unit: "unit", when: "the inspection or brief lists code violations" },
      { item: "Drywall patch of access holes, taped and textured ready for paint", unit: "sqft", when: "walls or ceilings were opened for wiring" },
      { item: "Circuit testing: every outlet checked for polarity and ground, GFCI and AFCI trip test, breaker torque, panel directory filled in", unit: "fixed" },
      { item: "Cleanup and haul-away of old panels, fixtures and packaging; final walk-through with the homeowner", unit: "fixed" },
    ],
    avoid: [
      "'Electrical work' or 'Wiring' with no outlet, circuit or fixture count",
      "'Panel' with no amperage or space count",
      "'Service upgrade' priced together with the branch-circuit work",
      "a whole-house surge protector or generator interlock without naming the device",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Counts come from the walk-through or brief; homerun lengths are measured along the path the wire actually takes",
      "Utility meter fees and inspection fees are passed through at the published rate",
      "Knob-and-tube, aluminum wiring or hidden damage found once walls are open is priced as a change order",
      "Painting of patched areas is by the homeowner unless listed",
    ],
  },

  "surge-protection": {
    basis: "surge protective devices each by type and location; grounding corrections and panel work fixed",
    steps: [
      { item: "Site assessment: service size and type, panel make and available spaces, condition of the grounding electrode system, sensitive equipment inventory", unit: "fixed" },
      { item: "Electrical permit and inspection where the jurisdiction requires one for panel work", unit: "fixed", when: "the jurisdiction permits SPD installation" },
      { item: "Grounding correction: missing or loose ground rod, water-pipe bond or grounding electrode conductor added or reterminated so the SPD has a low-impedance path", unit: "fixed", when: "the grounding electrode system is deficient" },
      { item: "Type 1 surge protective device at the meter socket or service entrance, utility-approved meter-collar or enclosure model", unit: "unit", when: "meter-side protection is chosen" },
      { item: "Type 2 whole-home surge protective device at the main panel, UL 1449 listed, 80 kA to 100 kA per phase, on a dedicated 2-pole breaker with leads kept under 18 in.", unit: "unit" },
      { item: "Type 2 surge protective device at each subpanel (garage, shop, ADU) fed from the main", unit: "unit", when: "the home has subpanels" },
      { item: "Type 3 point-of-use surge protection: receptacle-style or plug-in units at the AV system, computers and network gear", unit: "unit", when: "point-of-use protection is included" },
      { item: "HVAC condenser surge protector wired at the outdoor disconnect", unit: "unit", when: "the condenser is protected" },
      { item: "Coax, telephone and Ethernet line protectors at the service entrance, bonded to the grounding system", unit: "unit", when: "signal lines enter the home" },
      { item: "Panel work: dead front removed, device mounted and wired, breaker labeled, panel closed and directory updated", unit: "fixed" },
      { item: "Verification: status indicators checked, breaker torque, ground resistance reading logged, homeowner shown what the indicator lights mean", unit: "fixed" },
      { item: "Warranty registration for the device and the connected-equipment coverage, documentation left with the homeowner", unit: "fixed" },
    ],
    avoid: [
      "'Surge protector' with no type, kA rating or listing",
      "a device listed with no breaker or panel work behind it",
      "a full panel replacement or service upgrade — the residential electrical scope",
      "power-strip surge protectors counted as whole-home protection",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Device ratings are selected for the service size and the equipment being protected; kA rating is stated per phase",
      "Connected-equipment warranties are the manufacturer's and subject to their claim terms",
      "A panel with no available spaces is priced for a tandem breaker or a change order to add one",
      "Protection requires a sound grounding electrode system; corrections found on site beyond the listed line are priced as a change",
    ],
  },

  "residential-plumbing": {
    basis: "fixtures and repairs each; replacement pipe by linear feet and size; diagnosis by the hour; permits and tests fixed",
    steps: [
      { item: "Diagnosis: static pressure reading at the hose bib, fixture-by-fixture check for leaks, slow drains and failed valves, findings explained before work starts", unit: "hour" },
      { item: "Plumbing permit and inspection for fixture relocations, water heater or repipe work", unit: "fixed", when: "the work requires a permit" },
      { item: "Floors and cabinets protected, water shut off at the main and the lines drained down", unit: "fixed" },
      { item: "Old fixtures, faucets, valves and failed pipe sections removed and hauled away", unit: "unit", when: "existing fixtures or pipe are replaced" },
      { item: "Water line repair or replacement: PEX-A with expansion fittings or Type L copper by size, spliced to the existing with push-fit or sweat transitions", unit: "linear ft" },
      { item: "Drain line repair or replacement: Schedule 40 ABS or PVC by size with shielded couplings to the existing, sloped 1/4 in. per ft", unit: "linear ft" },
      { item: "Quarter-turn angle stops and braided stainless supply lines at each fixture served", unit: "unit" },
      { item: "Toilet set: new wax ring or waxless seal, closet bolts, supply and shutoff, caulked at the floor", unit: "unit", when: "toilets are set or replaced" },
      { item: "Faucet, sink, garbage disposal or dishwasher connection: mounted, plumbed with a P-trap and air gap, tested", unit: "unit", when: "kitchen or bath fixtures are replaced" },
      { item: "Tub and shower valve: pressure-balance or thermostatic valve set behind the wall with trim, spout and shower head", unit: "unit", when: "a tub or shower valve is replaced" },
      { item: "Frost-free hose bib with vacuum breaker, through-wall and sealed", unit: "unit", when: "hose bibs are replaced or added" },
      { item: "Pressure-reducing valve set to 60 psi and a thermal expansion tank at the water heater", unit: "unit", when: "house pressure is over 80 psi or a PRV is missing" },
      { item: "Stoppage cleared by cable machine through the cleanout or trap arm with the right cutter for the line size", unit: "unit", when: "a drain is stopped" },
      { item: "Access openings cut in drywall or tile for concealed pipe, then patched, taped and textured ready for paint", unit: "sqft", when: "the repair is inside a finished wall or ceiling" },
      { item: "Pressure test of the repaired lines at house pressure, every joint checked dry, inspector sign-off where permitted", unit: "fixed" },
      { item: "Cleanup, old parts hauled off, aerators flushed, warranty on the labor and installed parts explained to the homeowner", unit: "fixed" },
    ],
    avoid: [
      "'Plumbing repair' or 'Service call' as one line with no fixture, pipe size or method",
      "'Parts and materials' with nothing named",
      "a water heater or whole-house repipe hidden inside a repair estimate — its own scope",
      "sewer replacement or excavation outside the house — a sewer scope",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Fixtures are per the brief; owner-furnished fixtures are installed at the labor rate shown",
      "Hidden damage behind walls (rot, mold, additional failed pipe) is priced as a change order",
      "Tile and stone repair after an access opening is by others unless listed",
      "Drain clearing is a service, not a warranty against recurrence; a camera inspection is recommended for repeat stoppages",
    ],
  },

  "gas-line": {
    basis: "gas pipe by linear feet, size and material; appliance connections, valves and regulators each; sizing, testing and permits fixed",
    steps: [
      { item: "Load calculation and sizing: total BTU/hr demand of every appliance, pipe sized by the longest-run method per NFPA 54 / IFGC tables, sizing schematic prepared", unit: "fixed" },
      { item: "Gas permit, pressure-test inspection and final inspection scheduled with the building department", unit: "fixed" },
      { item: "Utility coordination: meter upsizing or elevated-pressure service requested from the gas company", unit: "fixed", when: "the existing meter cannot carry the added load" },
      { item: "811 utility locate and trench for the exterior yard line at 18 in. minimum cover, spoils stockpiled", unit: "linear ft", when: "the line runs underground outside the building" },
      { item: "Underground gas line: yellow polyethylene (MDPE) with heat-fused or mechanical fittings, tracer wire, warning tape and anodeless risers at each end", unit: "linear ft", when: "the line runs underground outside the building" },
      { item: "Interior gas piping: Schedule 40 black steel, threaded with pipe dope rated for gas, sized per the schematic, supported every 6 to 10 ft", unit: "linear ft" },
      { item: "CSST runs with arc-resistant jacket, listed fittings and bonding to the electrical grounding system with #6 copper", unit: "linear ft", when: "CSST is used for the runs" },
      { item: "Shutoff valve, drip leg (sediment trap) and union at each appliance, plus the system shutoff at the entry", unit: "unit" },
      { item: "Appliance connection with a listed flexible connector and startup of the range, dryer, furnace, water heater, fireplace or grill", unit: "unit" },
      { item: "Line regulator at each appliance and the 2-psi entry regulator for a pounds-to-inches system", unit: "unit", when: "the system runs at elevated pressure" },
      { item: "Propane: tank set and first- and second-stage regulators with the propane supplier's tie-in", unit: "unit", when: "the fuel is propane" },
      { item: "Wall and foundation penetrations sleeved, sealed and protected with nail plates where the pipe passes through framing", unit: "unit" },
      { item: "Pressure test at 1.5 times working pressure and not less than 3 psi for 10 minutes, or as the jurisdiction requires, on a gauge witnessed by the inspector", unit: "fixed" },
      { item: "Purge of the new line, every joint leak-checked with solution or electronic detector under gas, appliances lit and adjusted", unit: "fixed" },
      { item: "Trench backfilled in compacted lifts and the lawn or surface restored", unit: "cu yards", when: "the line runs underground outside the building" },
      { item: "Pipe labeled at the shutoffs and an as-built sketch of the routing left with the owner", unit: "fixed" },
    ],
    avoid: [
      "'Gas line' with no size, material or length",
      "'Hookup' with no appliance, valve or drip leg named",
      "the trench and the pipe priced as one line",
      "appliance installation itself (the range, furnace, water heater) — another scope",
      "'Miscellaneous fittings' or 'labor' lines",
    ],
    notes: [
      "Pipe sizes come from the load calculation; lengths are measured along the routed path",
      "Utility meter upgrades and fees are on the gas company's schedule and passed through",
      "Existing piping is assumed sound; leaks found on the old system during the test are priced as a change",
      "Restoration matches the existing surface; concrete or paver replacement is extra unless listed",
    ],
  },

  "water-heater-replacement": {
    basis: "the heater by gallons, fuel and vent type each; venting and pipe by linear feet; connections, safety devices and startup each or fixed",
    steps: [
      { item: "Plumbing and mechanical permit with the final inspection scheduled", unit: "fixed" },
      { item: "Old heater shut off, drained, disconnected from gas or power, water and vent, removed and hauled for recycling", unit: "unit" },
      { item: "New storage water heater by capacity and fuel (40-, 50- or 75-gallon gas atmospheric, power-vent or electric) with its UEF rating and warranty term, set level on a stand where the code requires", unit: "unit" },
      { item: "Water connections: new 3/4 in. ball-valve shutoff, dielectric nipples, braided stainless or copper flex connectors", unit: "unit" },
      { item: "Gas connection: new flexible connector, sediment trap and shutoff, leak-checked under pressure", unit: "unit", when: "the heater is gas-fired" },
      { item: "Electrical connection: new 10-2 whip and disconnect on the existing 30 A circuit, verified", unit: "unit", when: "the heater is electric" },
      { item: "Venting: draft hood and B-vent by diameter to the existing chimney or flue, or Schedule 40 PVC intake and exhaust for a power-vent model, terminated per the manufacturer", unit: "linear ft", when: "the heater is gas-fired" },
      { item: "Thermal expansion tank sized to the heater, teed into the cold side and pre-charged to house pressure", unit: "unit" },
      { item: "Drain pan under the heater with a 3/4 in. drain piped to the exterior or a floor drain", unit: "unit", when: "the heater sits over finished space or the code requires a pan" },
      { item: "Seismic strapping: two 22-gauge straps at the upper and lower third, lagged into studs", unit: "unit", when: "the jurisdiction requires seismic strapping" },
      { item: "Temperature and pressure relief valve discharge line in 3/4 in. copper or CPVC to an approved termination with an air gap", unit: "unit" },
      { item: "Condensate neutralizer and drain for a condensing power-vent heater", unit: "unit", when: "the heater is a condensing model" },
      { item: "Pipe insulation on the first 6 ft of hot and cold lines at the heater", unit: "linear ft" },
      { item: "Startup: tank filled and purged of air, burner lit or elements energized, thermostat set to 120 F, draft and combustion checked, every joint tested", unit: "fixed" },
      { item: "Haul-away and cleanup, manufacturer warranty registered, operation and maintenance explained to the homeowner", unit: "fixed" },
    ],
    avoid: [
      "'Water heater' with no capacity, fuel, vent type or efficiency rating",
      "'Install' with no connections, safety devices or venting listed",
      "the heater and its installation priced as one line",
      "a tankless conversion inside a tank replacement estimate — its own scope",
      "'Miscellaneous parts' or 'labor' lines",
    ],
    notes: [
      "Capacity and fuel are per the brief; the existing venting, gas line and circuit are assumed serviceable until inspected",
      "Corroded shutoffs, undersized gas piping or a failed chimney liner found at removal are priced as a change order",
      "Permit fees are passed through at the building department's rate",
      "The manufacturer's tank warranty applies as registered; labor warranty is as stated on the proposal",
    ],
  },

  "tankless-water-heater": {
    basis: "the unit by BTU input and flow rate each; gas, venting and water piping by linear feet; sizing, startup and permits fixed",
    steps: [
      { item: "Sizing survey: peak flow in GPM at the required temperature rise, gas meter and line capacity, electrical service, vent route and condensate path confirmed", unit: "fixed" },
      { item: "Plumbing, mechanical and gas permits with the final inspection scheduled", unit: "fixed" },
      { item: "Existing tank heater drained, disconnected, removed and hauled for recycling", unit: "unit", when: "a tank heater is being replaced" },
      { item: "Condensing tankless heater by input and flow (for example 199,000 BTU, 9 to 11 GPM, UEF 0.93 or better) mounted on its bracket with service clearance", unit: "unit" },
      { item: "Gas line upsized to 3/4 in. or 1 in. black steel or CSST from the meter to the unit with sediment trap and shutoff, sized for the full input", unit: "linear ft", when: "the existing gas line is undersized for the unit" },
      { item: "Gas meter upgrade requested from the utility to carry the added input", unit: "fixed", when: "the meter cannot supply the unit's BTU load" },
      { item: "Venting: 2 in. or 3 in. PVC or polypropylene, twin-pipe or concentric, with the termination kit through the wall or roof", unit: "linear ft" },
      { item: "Condensate neutralizer cartridge and 1/2 in. drain line to an approved termination", unit: "unit" },
      { item: "Isolation service-valve kit with purge ports, 3/4 in. water connections and a pressure relief valve piped to an approved point", unit: "unit" },
      { item: "Electrical: 120 V receptacle or hardwired circuit for the controls and fan, or dedicated 240 V circuits for an electric tankless unit", unit: "unit", when: "a new circuit or receptacle is needed" },
      { item: "Recirculation kit or dedicated return line with the unit's onboard pump for faster hot water at distant fixtures", unit: "unit", when: "recirculation is included" },
      { item: "Scale prevention: sediment pre-filter and a template-assisted crystallization (TAC) or softener treatment ahead of the unit", unit: "unit", when: "the water hardness is over 7 grains per gallon" },
      { item: "Wall or roof penetrations for the vent and condensate, flashed and weather-sealed", unit: "unit" },
      { item: "Startup: lines purged, temperature set to 120 F, dip switches set for altitude and gas type, combustion analysis and flow verified at the farthest fixture", unit: "fixed" },
      { item: "Annual descaling procedure shown to the homeowner, warranty registered, packaging and old unit hauled off", unit: "fixed" },
    ],
    avoid: [
      "'Tankless unit' with no BTU input, flow rate or efficiency",
      "'Gas work' with no pipe size or length",
      "the unit, venting and gas priced as one line",
      "a tank-style replacement — its own scope",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "The unit is sized from the fixture count and the winter inlet water temperature stated in the brief",
      "Gas meter upgrades are on the utility's schedule; utility fees are passed through",
      "Existing venting and gas piping are assumed unusable for a tankless unit unless the survey shows otherwise",
      "Manufacturer warranty requires annual descaling; the warranty is void without it",
    ],
  },

  "whole-house-repiping": {
    basis: "new pipe by linear feet, size and material; fixture stub-outs each; access openings and drywall patch by square feet; tests and permits fixed",
    steps: [
      { item: "Walk-through and layout: fixture count, existing pipe material, routing through attic, crawlspace and walls, manifold and shutoff locations marked", unit: "fixed" },
      { item: "Plumbing permit with rough-in pressure test and final inspections scheduled", unit: "fixed" },
      { item: "Floor protection, plastic dust barriers on doorways and furniture covered in every room where walls are opened", unit: "fixed" },
      { item: "Access openings cut in drywall or plaster at fixtures, chases and ceilings, sized for the work and marked for patching", unit: "unit" },
      { item: "Old galvanized, polybutylene or failed copper drained, cut and abandoned in place; exposed sections in the crawlspace, basement or attic removed and hauled", unit: "linear ft" },
      { item: "New water main from the meter or entry to the house: 1 in. PEX-A or Type L copper, with a new full-port main shutoff and pressure-reducing valve", unit: "linear ft" },
      { item: "Trunk lines: 3/4 in. PEX-A with expansion fittings or Type L copper, run through the attic or crawlspace and supported per code", unit: "linear ft" },
      { item: "Branch lines: 1/2 in. PEX-A or Type L copper from the trunk or manifold to each fixture, sleeved through framing with nail plates", unit: "linear ft" },
      { item: "PEX manifold with individual quarter-turn shutoffs for each fixture, mounted in an accessible location", unit: "unit", when: "a home-run manifold layout is chosen" },
      { item: "Fixture stub-outs: drop-ear elbows or copper stub-outs, new quarter-turn angle stops and braided supply lines at each fixture", unit: "unit" },
      { item: "Frost-free hose bibs with vacuum breakers replaced and connected to the new system", unit: "unit" },
      { item: "Water heater reconnected with new flex connectors, dielectric unions and a thermal expansion tank", unit: "unit" },
      { item: "Hot-water recirculation return line and pump for fast hot water", unit: "linear ft", when: "recirculation is included" },
      { item: "Pipe insulation on lines in the attic, crawlspace or garage and fire blocking restored at every penetration", unit: "linear ft" },
      { item: "Rough-in pressure test at 100 psi held for the inspector, every joint checked", unit: "fixed" },
      { item: "Drywall patch: openings closed, taped, mudded and textured to match, ready for paint", unit: "sqft" },
      { item: "System flushed, aerators cleaned, every fixture run and checked for leaks and pressure", unit: "fixed" },
      { item: "Final cleanup, old pipe and debris hauled off, warranty documents delivered", unit: "fixed" },
    ],
    avoid: [
      "'Repipe' as one line with no pipe size, material or length",
      "'Drywall' with no square footage of patch",
      "the pipe and the drywall repair priced as one line",
      "drain, waste and vent replacement hidden inside a water repipe — its own scope unless the brief includes it",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Pipe lengths are measured along the routed path; the fixture count is from the walk-through",
      "Paint after the drywall patch is by the homeowner unless a paint line is listed",
      "Hidden damage found when walls are opened (rot, mold, asbestos) is priced as a change order",
      "The water heater and existing fixtures are reconnected, not replaced",
    ],
  },

  "leak-detection": {
    basis: "on-site detection by the hour; system tests, camera runs and located leaks each; the written report fixed",
    steps: [
      { item: "Intake and walk-through: water bill history, meter reading with all fixtures off, visible staining, warm spots and sound of running water noted", unit: "fixed" },
      { item: "Meter and static pressure test: the house isolated at the main, meter low-flow indicator watched, pressure held on a gauge to confirm a loss", unit: "fixed" },
      { item: "Isolation pressure test of each system separately: hot, cold, irrigation, pool or spa lines, to narrow the leak to one system", unit: "unit" },
      { item: "Electronic acoustic detection: ground microphone and correlator on slabs, walls and yard lines with the system pressurized", unit: "hour" },
      { item: "Thermal imaging of floors, walls and ceilings to trace a hot-water slab leak or hidden moisture", unit: "hour", when: "the loss is on the hot side or shows as staining" },
      { item: "Tracer gas test: nitrogen-hydrogen mix introduced into the line and traced with a gas detector", unit: "fixed", when: "acoustic listening is inconclusive" },
      { item: "Camera inspection of drain lines with a self-leveling camera and locator, recorded", unit: "linear ft", when: "the leak may be on a drain or sewer line" },
      { item: "Dye test of tubs, showers, toilets and drains to separate a fixture leak from a pipe leak", unit: "unit", when: "a fixture or shower pan is suspected" },
      { item: "Pool and spa pressure test of the plumbing lines and dye test of the shell and fittings", unit: "unit", when: "a pool or spa is losing water" },
      { item: "Moisture mapping with a pin and pinless meter of the affected floors and walls", unit: "sqft" },
      { item: "Leak location marked on the floor or ground with paint and depth noted for the repair crew", unit: "unit" },
      { item: "Written report with photos, thermal images, the located points and the recommended repair method", unit: "fixed" },
      { item: "Small access opening cut to confirm the leak before the report", unit: "unit", when: "confirmation by sight is needed" },
    ],
    avoid: [
      "'Leak detection' as one line with no method or hours",
      "the repair itself buried inside the detection estimate — quoted separately once located",
      "'Service call' with nothing in it",
      "'Miscellaneous' or 'equipment fee' lines with nothing named",
    ],
    notes: [
      "Detection is billed by the hour on site plus the listed tests; the repair is quoted separately from the report",
      "Location accuracy is stated in the report; a second visit is included if the first repair opening misses the leak within the stated distance",
      "Access openings are cut only with the owner's approval and are patched by others unless listed",
      "Water and power must be on at the property for the tests to run",
    ],
  },

  "drain-cleaning": {
    basis: "lines cabled each; hydro-jetting by the hour; camera inspection and descaling by linear feet; cleanouts and treatments each",
    steps: [
      { item: "Assessment: which fixtures back up, cleanout located, line size and material identified, method chosen with the customer", unit: "fixed" },
      { item: "Work area protected with drop cloths and the floor sanitized after the work", unit: "fixed" },
      { item: "Cable a fixture or branch line (1-1/4 in. to 2 in.) through the trap arm or cleanout with a drum machine and the right cutter head", unit: "unit", when: "a sink, tub or branch line is stopped" },
      { item: "Cable the main sewer line (3 in. to 4 in.) from the cleanout with a sectional machine and a cutter sized to the pipe", unit: "unit", when: "the main line is stopped" },
      { item: "Toilet pulled to reach the line and reset with a new wax ring and bolts", unit: "unit", when: "the line has no accessible cleanout" },
      { item: "Hydro-jetting with a 4,000-psi, 18-gpm jetter and rotating nozzles to scour grease, sludge and roots from the full pipe wall", unit: "hour", when: "the line is grease-bound, root-choked or cabling did not hold" },
      { item: "Root cutting with a chain-flail or root-saw head on the cable or jetter", unit: "unit", when: "roots are found in the line" },
      { item: "Descaling of cast-iron pipe with a chain knocker to restore the full diameter", unit: "linear ft", when: "the line is scaled cast iron" },
      { item: "Camera inspection of the cleared line with a self-leveling camera, recorded and shown to the customer", unit: "linear ft" },
      { item: "Line located with a sonde and marked on the surface with depth for any future repair", unit: "unit", when: "a defect is found on camera" },
      { item: "Two-way cleanout installed on the main line at the house", unit: "unit", when: "the house has no cleanout" },
      { item: "Foaming root inhibitor treatment applied to the line after clearing", unit: "unit", when: "roots are found in the line" },
      { item: "Report with the video file, findings and any recommended repair", unit: "fixed" },
      { item: "Equipment cleaned, debris bagged and removed, work area sanitized", unit: "fixed" },
    ],
    avoid: [
      "'Drain cleaning' as one line with no line, method or size",
      "'Camera' with no length or recording",
      "the pipe repair or replacement inside the cleaning estimate — quoted separately from the video",
      "'Miscellaneous' or 'service fee' lines",
    ],
    notes: [
      "Cabling and jetting clear the stoppage; they do not repair a broken, bellied or offset pipe, which the camera would show",
      "A line that cannot be cleared because of a collapse is reported with the location for a repair quote",
      "Pulling a toilet includes the reset; a cracked toilet or flange found during removal is priced as a change",
      "Root treatments slow regrowth and are not a permanent fix",
    ],
  },

  "backflow-preventer": {
    basis: "the assembly each by type and size; piping by linear feet; enclosure, pad, testing and certification fixed or each",
    steps: [
      { item: "Hazard assessment and device selection: reduced-pressure assembly (ASSE 1013) for high hazard, double-check (ASSE 1015) for low hazard, pressure vacuum breaker (ASSE 1020) for irrigation, per the water purveyor's cross-connection rules", unit: "fixed" },
      { item: "Plumbing permit and the purveyor's installation application with the approved-assembly list", unit: "fixed" },
      { item: "Water shutdown scheduled with the occupants or the purveyor for the tie-in", unit: "fixed" },
      { item: "Existing assembly or non-compliant device removed and hauled off", unit: "unit", when: "an existing device is replaced" },
      { item: "Excavation and concrete pad for an exterior above-ground assembly, or setting of a below-grade vault", unit: "unit", when: "the assembly is installed outdoors" },
      { item: "Backflow assembly supplied and installed by size (3/4 in. to 2 in. threaded, 2-1/2 in. and larger flanged) with full-port shutoffs, unions, strainer and test cocks, 12 in. minimum above grade or floor", unit: "unit" },
      { item: "Piping modifications to fit the assembly: Type L copper, brass or Schedule 80 PVC by size, with the required straight runs and supports", unit: "linear ft" },
      { item: "Support stand and bracing for larger assemblies", unit: "unit", when: "the assembly is 2 in. or larger" },
      { item: "Insulated enclosure (ASSE 1060) with heat trace for freeze protection", unit: "unit", when: "the assembly is outdoors in a freezing climate" },
      { item: "Air-gap drain sized to the relief-valve discharge and run to a floor drain or outdoors", unit: "unit", when: "a reduced-pressure assembly is installed indoors" },
      { item: "Thermal expansion tank on the domestic system now closed by the check valves", unit: "unit", when: "the assembly is on the domestic water service" },
      { item: "Initial certification test by a certified tester with a calibrated gauge, forms filed with the purveyor and the tag attached", unit: "fixed" },
      { item: "Backfill, surface restoration and cleanup", unit: "fixed", when: "the assembly is installed outdoors" },
      { item: "Annual test reminder set and the test report copy left with the owner", unit: "fixed" },
    ],
    avoid: [
      "'Backflow device' with no type, size or ASSE standard",
      "'Install' with no piping, shutoffs or test cocks listed",
      "the assembly and the enclosure or pad priced as one line",
      "an irrigation system or fire line beyond the assembly — other scopes",
      "'Miscellaneous fittings' or 'labor' lines",
    ],
    notes: [
      "The device type is set by the purveyor's hazard rating; a different type required at plan review is priced as a change",
      "The initial test is included; annual recertification is a separate service",
      "Purveyor fees and permit fees are passed through at the published rate",
      "Landscaping and irrigation around an exterior assembly are restored to grade only",
    ],
  },

  "sump-pump": {
    basis: "pump, basin and backup each; discharge piping by linear feet; pit cut, floor patch and testing each or by square feet",
    steps: [
      { item: "Assessment: water table and seepage pattern, existing basin and pump condition, required capacity in GPH at the lift head, discharge route checked", unit: "fixed" },
      { item: "Plumbing or building permit where the jurisdiction requires one for a new pit or exterior discharge", unit: "fixed", when: "the jurisdiction permits sump work" },
      { item: "Old pump, check valve and failed basin removed and disposed of", unit: "unit", when: "an existing pump or basin is replaced" },
      { item: "Slab saw-cut and broken out, pit excavated for the basin and the spoils hauled off", unit: "unit", when: "a new pit is cut in the floor" },
      { item: "Perforated polyethylene basin (18 in. by 22 in. to 30 in.) set in washed gravel with a gasketed lid", unit: "unit" },
      { item: "Interior perimeter drain tile tied into the basin", unit: "linear ft", when: "drain tile is added or reconnected" },
      { item: "Primary pump: 1/3 or 1/2 HP cast-iron submersible with vertical float, rated GPH at 10 ft of head, set on a stand in the basin", unit: "unit" },
      { item: "Battery backup pump with 12 V deep-cycle battery, smart charger and high-water alarm", unit: "unit", when: "battery backup is included" },
      { item: "Water-powered backup ejector on the domestic supply with a backflow preventer", unit: "unit", when: "water-powered backup is included" },
      { item: "Discharge piping: 1-1/2 in. Schedule 40 PVC with a silent check valve and union, through the rim joist or wall and sealed", unit: "linear ft" },
      { item: "Exterior discharge: buried 4 in. line to daylight or a pop-up emitter at least 10 ft from the foundation, sloped to drain", unit: "linear ft" },
      { item: "Dedicated GFCI-protected receptacle within reach of the basin", unit: "unit", when: "no dedicated outlet is at the pit" },
      { item: "Sealed lid with pipe and cord grommets to keep radon and moisture out of the basement", unit: "unit" },
      { item: "Concrete floor patched around the basin and finished flush", unit: "sqft" },
      { item: "Test: basin filled and pumped through several cycles, float and check valve checked, alarm and backup tested", unit: "fixed" },
      { item: "Wi-Fi water alarm or monitor at the pit", unit: "unit", when: "remote monitoring is included" },
      { item: "Cleanup, old parts hauled off and pump operation explained to the homeowner", unit: "fixed" },
    ],
    avoid: [
      "'Sump pump' with no horsepower, capacity or float type",
      "'Discharge' with no pipe size or route",
      "the pump and the basin priced as one line",
      "exterior foundation waterproofing or grading — the waterproofing scope",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Pump capacity is set by the assessment; a higher water table found when the pit is cut is priced as a change",
      "Discharge to the sanitary sewer is not allowed in most jurisdictions; the line runs to daylight or a storm connection",
      "The electrical receptacle is included only where listed; a new circuit is by the electrical scope",
      "Battery backup runtime depends on the battery size stated",
    ],
  },

  "residential-hvac": {
    basis: "equipment each by tonnage, BTU and efficiency rating; line set, venting and duct changes by linear feet; load calc, commissioning and permits fixed",
    steps: [
      { item: "Manual J room-by-room load calculation, Manual S equipment selection and a duct check, report given to the homeowner", unit: "fixed" },
      { item: "Mechanical permit with the final inspection scheduled; utility rebate and manufacturer promotion paperwork filed", unit: "fixed" },
      { item: "Refrigerant recovered per EPA 608, old furnace, condenser, coil and pad disconnected and removed, hauled for recycling", unit: "unit" },
      { item: "Gas furnace by input and efficiency (80% or 96% AFUE, single-stage, two-stage or modulating, ECM blower), set on the platform with a new return drop", unit: "unit", when: "the system includes a furnace" },
      { item: "Air conditioner or heat pump condenser by tonnage and SEER2 or HSPF2 rating, set level on a new composite pad with service clearance", unit: "unit" },
      { item: "Matched cased evaporator coil with TXV, or a variable-speed air handler with electric heat strips by kW", unit: "unit" },
      { item: "Refrigerant line set: 3/8 in. and 3/4 in. ACR copper, brazed under nitrogen, suction line insulated with 3/4 in. closed-cell foam, UV-wrapped outdoors", unit: "linear ft" },
      { item: "Electrical: weatherproof disconnect and sealtite whip at the condenser, breaker sized to the nameplate, 18/8 thermostat wire", unit: "unit" },
      { item: "Condensate: 3/4 in. PVC primary drain with trap and cleanout, secondary pan under attic or closet units, float switch wired to shut the system down", unit: "unit" },
      { item: "Gas connection with flex, drip leg and shutoff, and 2 in. or 3 in. PVC intake and exhaust venting for a condensing furnace through the wall or roof", unit: "linear ft", when: "the system includes a gas furnace" },
      { item: "Sheet-metal supply and return plenums, transitions to the existing trunk and a 4 in. media filter rack", unit: "unit" },
      { item: "Duct modifications: new supply or return runs in R-8 flex or sheet metal, sealed with mastic", unit: "linear ft", when: "the duct check calls for changes" },
      { item: "Thermostat: programmable or smart communicating thermostat mounted, wired and set up on the homeowner's app", unit: "unit" },
      { item: "Evacuation to 500 microns, refrigerant charge weighed in and verified by subcooling and superheat, startup sheet completed", unit: "unit" },
      { item: "Commissioning: static pressure, temperature split, gas pressure and combustion check, airflow at every register verified", unit: "fixed" },
      { item: "Manufacturer warranty registered, homeowner walk-through on filters and thermostat, cleanup and packaging hauled off", unit: "fixed" },
    ],
    avoid: [
      "'HVAC system' or 'AC unit' with no tonnage, efficiency rating or model class",
      "'Install' with no line set, electrical, condensate or venting listed",
      "the condenser, coil and furnace priced as one line",
      "a whole-house duct replacement inside an equipment changeout — its own scope",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Equipment is sized from the Manual J, not the old unit's nameplate",
      "The existing ductwork is assumed serviceable per the duct check; leakage repairs beyond the listed line are priced as a change",
      "An electrical panel upgrade for a heat pump or added strips is by the electrical scope",
      "Rebates are filed on the homeowner's behalf but paid by the utility on its own terms",
    ],
  },

  "whole-house-fan": {
    basis: "the fan and grille each by CFM; attic vents and controls each; wiring by linear feet; sizing and testing fixed",
    steps: [
      { item: "Sizing and attic check: fan CFM at 2 to 3 CFM per square foot of living area, attic net free vent area verified at 1 square foot per 750 CFM, combustion appliances noted", unit: "fixed" },
      { item: "Building and electrical permit where the jurisdiction requires one", unit: "fixed", when: "the jurisdiction permits fan installation" },
      { item: "Roof, gable or soffit vents added to reach the required net free area for the fan", unit: "unit", when: "the attic venting is short of the requirement" },
      { item: "Ceiling opening located between joists, cut and framed for the intake grille", unit: "unit" },
      { item: "Whole-house fan by CFM (1,500 to 4,500) with an insulated, self-closing damper box (R-38 or better) and brushless motor, hung from the rafters on its isolation straps", unit: "unit" },
      { item: "Insulated flexible duct from the fan to the damper box, sized to the fan and kept straight", unit: "linear ft" },
      { item: "Intake grille and damper box set flush in the ceiling and sealed to the drywall", unit: "unit" },
      { item: "Dedicated 15 A circuit run from the panel to the fan with a disconnect switch in the attic", unit: "linear ft" },
      { item: "Controls: wall switch with countdown timer, two-speed control, wireless remote or app module", unit: "unit" },
      { item: "Attic insulation moved back around the box and air-sealed so the fan does not short-circuit through the ceiling", unit: "fixed" },
      { item: "Test at full speed with windows open, ceiling grille checked for closure and back-draft test at gas appliances", unit: "fixed" },
      { item: "Drywall touch-up around the grille", unit: "sqft", when: "the ceiling was cut oversize or damaged" },
      { item: "Cleanup, packaging removed and operation explained to the homeowner", unit: "fixed" },
    ],
    avoid: [
      "'Attic fan' with no CFM or damper insulation rating",
      "'Electrical' with no circuit or switch named",
      "a powered attic ventilator counted as a whole-house fan",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Fan size is set by the living area and the attic venting; venting short of the requirement is added as listed",
      "Combustion appliances in the home require the back-draft test before the fan is left in service",
      "Painting of any drywall touch-up is by the homeowner",
      "The fan is a ventilation appliance, not an air conditioner; results depend on outdoor temperatures",
    ],
  },

  "iaq-specialist": {
    basis: "testing by the hour and lab samples each; filtration, ventilation, humidity and purification equipment each; duct by linear feet; commissioning fixed",
    steps: [
      { item: "On-site assessment: walk-through, particulate, CO2, VOC, humidity and CO readings logged, HVAC filtration and ventilation inspected", unit: "hour" },
      { item: "Laboratory samples: mold spore, radon, formaldehyde or allergen samples sent to an accredited lab", unit: "unit", when: "lab testing is included" },
      { item: "Written report with readings, lab results and prioritized recommendations", unit: "fixed" },
      { item: "Media filter cabinet with a 4 in. or 5 in. MERV 13 filter installed at the return with a new filter rack and sealed transitions", unit: "unit" },
      { item: "UV-C germicidal lamp at the evaporator coil to control biological growth", unit: "unit", when: "coil UV is included" },
      { item: "Whole-home air purifier (HEPA bypass, electronic or photocatalytic) ducted to the air handler", unit: "unit", when: "a purifier is included" },
      { item: "Energy- or heat-recovery ventilator by CFM with balanced intake and exhaust, hoods and dampers", unit: "unit", when: "mechanical ventilation is included" },
      { item: "Insulated duct for the ventilator or purifier, sealed with mastic", unit: "linear ft", when: "new ducted equipment is added" },
      { item: "Whole-house humidifier (bypass, fan-powered or steam) with humidistat and drain", unit: "unit", when: "winter humidity is below the target" },
      { item: "Whole-house dehumidifier ducted to the return with a condensate drain", unit: "unit", when: "summer humidity is above the target" },
      { item: "Source-removal duct cleaning with a negative-air machine and agitation, registers cleaned", unit: "unit", when: "the ducts are contaminated" },
      { item: "IAQ controls: sensor-integrated thermostat or standalone monitor with humidity, CO2 and particulate readouts", unit: "unit" },
      { item: "Bath and kitchen exhaust fan upgrades by CFM with timers and exterior terminations", unit: "unit", when: "spot ventilation is inadequate" },
      { item: "Combustion safety: CO monitors and a spillage test at gas appliances", unit: "unit" },
      { item: "Commissioning: airflow and static pressure verified, ventilation balanced, post-installation readings compared with the assessment", unit: "fixed" },
      { item: "Maintenance schedule and filter sizes left with the homeowner, warranties registered", unit: "fixed" },
    ],
    avoid: [
      "'Air quality system' with no equipment type or rating",
      "'Testing' with no parameter, method or sample count",
      "mold remediation or asbestos abatement — separate licensed scopes",
      "a new furnace or air conditioner — the HVAC scope",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Recommendations follow the assessment readings; equipment is sized to the home's air handler",
      "Lab fees are passed through at the laboratory's rate",
      "Remediation of mold, asbestos or radon mitigation systems is quoted separately by the licensed contractor",
      "Results are verified by the post-installation readings, not guaranteed against outdoor conditions",
    ],
  },

  "duct-sealing": {
    basis: "duct leakage tests and aerosol sealing per system fixed; hand sealing and insulation by linear feet; repairs each",
    steps: [
      { item: "Pre-test: duct leakage test with a calibrated fan at 25 Pa, total leakage and leakage to outside recorded in CFM25", unit: "fixed" },
      { item: "Visual inspection of accessible ducts in the attic, crawlspace or basement: disconnected runs, crushed flex and open boots noted with photos", unit: "fixed" },
      { item: "Preparation: registers removed and openings plugged with foam blocks, the furnace, coil and filter protected", unit: "fixed" },
      { item: "Disconnected or crushed runs reconnected or replaced with R-8 flex and strapped", unit: "unit", when: "the inspection finds broken runs" },
      { item: "Hand sealing of accessible joints, seams, takeoffs and plenums with UL 181 water-based mastic and fiber mesh", unit: "linear ft" },
      { item: "Aerosol sealing: computer-controlled sealant injected at 25 Pa from inside the ducts with real-time leakage readout until the target is reached", unit: "fixed", when: "aerosol sealing is chosen for the system" },
      { item: "Boots sealed to the drywall or subfloor at every register with mastic or foam", unit: "unit" },
      { item: "Air handler cabinet, filter rack and plenum seams sealed with foil tape and mastic", unit: "unit" },
      { item: "Duct insulation: R-8 wrap on ducts in unconditioned space", unit: "linear ft", when: "ducts are bare or under-insulated" },
      { item: "Registers reinstalled, plugs removed, a new filter installed", unit: "fixed" },
      { item: "Post-test at 25 Pa with a before-and-after certificate showing the leakage reduction", unit: "fixed" },
      { item: "Static pressure and airflow check to confirm the system is not over-restricted after sealing", unit: "fixed" },
      { item: "Utility rebate paperwork filed with the test certificate", unit: "fixed", when: "a utility rebate applies" },
    ],
    avoid: [
      "'Duct sealing' as one line with no method or test",
      "'Testing' with no pressure or result named",
      "duct replacement or a new system — the HVAC scope",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Results are measured by the before-and-after test, not estimated",
      "Aerosol sealing seals leaks up to about 5/8 in.; larger openings are hand-sealed or repaired as listed",
      "Ducts in inaccessible walls are sealed only by the aerosol method",
      "Rebates are filed on the homeowner's behalf on the utility's terms",
    ],
  },

  "radiant-floor-heating": {
    basis: "heated floor area by square feet; manifolds, circulators and thermostats each; boiler or heat source each; design, testing and startup fixed",
    steps: [
      { item: "Heat-loss calculation room by room, tubing layout with loop lengths and spacing (6 in. to 12 in. on center), zoning and supply-temperature design", unit: "fixed" },
      { item: "Mechanical, plumbing and electrical permits with rough-in and final inspections", unit: "fixed" },
      { item: "Floor preparation: subfloor cleaned or 2 in. XPS insulation (R-10) and vapor barrier under a slab, edge insulation at the perimeter", unit: "sqft" },
      { item: "Hydronic tubing: 1/2 in. oxygen-barrier PEX stapled to foam, tied to wire mesh, or in aluminum transfer plates under the subfloor, looped per the layout", unit: "sqft", when: "the system is hydronic" },
      { item: "Electric radiant mat or cable (120 V or 240 V, 12 to 15 W per square foot) embedded in self-leveling underlayment or thinset", unit: "sqft", when: "the system is electric" },
      { item: "Stainless manifold with flow meters, balancing valves and zone actuators, mounted in a recessed cabinet", unit: "unit", when: "the system is hydronic" },
      { item: "Heat source: condensing boiler (95% AFUE) by MBH, or air-to-water heat pump, with venting and gas connection", unit: "unit", when: "a new boiler or heat source is included" },
      { item: "Near-boiler piping: circulator pumps, mixing valve, expansion tank, air separator, fill valve and relief valve, one set per zone group", unit: "unit", when: "the system is hydronic" },
      { item: "Gypsum overpour or concrete topping over the tubing (1-1/2 in. typical), poured and cured", unit: "sqft", when: "the tubing is embedded in a topping" },
      { item: "Thermostats with floor sensors, one per zone, wired to the zone controller", unit: "unit" },
      { item: "Electrical: circuit for the boiler and pumps, or GFCI-protected dedicated circuits for the electric mats", unit: "unit" },
      { item: "Pressure test: tubing at 60 to 100 psi air before the pour and held through it, or resistance and megger test of the electric cable, logged", unit: "fixed" },
      { item: "Fill, purge, glycol where specified and flow balancing at the manifold", unit: "fixed", when: "the system is hydronic" },
      { item: "Startup and commissioning: supply temperatures, outdoor reset and floor sensors set, homeowner walk-through", unit: "fixed" },
    ],
    avoid: [
      "'Radiant heat' with no area, tubing size or spacing",
      "'Boiler' with no BTU rating or efficiency",
      "the tubing and the pour priced as one line",
      "the finished floor (tile, wood) — the flooring scope",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Heated area is measured from the layout; loop lengths are set by the design",
      "The finished floor is by others and must be rated for radiant heat",
      "Slab or subfloor repairs found during preparation are priced as a change",
      "Gas piping to a new boiler is included only where listed",
    ],
  },

  "fire-alarm": {
    basis: "devices and appliances each; cable and raceway by linear feet; panel, design, programming and acceptance testing fixed",
    steps: [
      { item: "Design and shop drawings: device layout, battery and voltage-drop calculations, NFPA 72 submittal stamped and filed with the fire marshal", unit: "fixed" },
      { item: "Fire alarm permit, plan review and the AHJ acceptance test scheduled", unit: "fixed" },
      { item: "Existing panel and devices decommissioned and removed with the monitoring company notified", unit: "unit", when: "an existing system is replaced" },
      { item: "Addressable fire alarm control panel by loop and NAC capacity, with enclosure, power supply and standby batteries sized to the calculation", unit: "unit" },
      { item: "Fire alarm cable: FPL, FPLR or FPLP by gauge, run in raceway or open where the code allows, supported and marked", unit: "linear ft" },
      { item: "Raceway: 3/4 in. EMT with boxes and fittings for exposed or protected runs", unit: "linear ft", when: "the cable runs exposed or the specification requires conduit" },
      { item: "Initiating devices: smoke and heat detectors, duct detectors, manual pull stations, waterflow and tamper monitor modules", unit: "unit" },
      { item: "Notification appliances: horn-strobes, strobes and speakers set to the candela and coverage on the drawings", unit: "unit" },
      { item: "Remote annunciator at the fire department entrance", unit: "unit", when: "the AHJ requires an annunciator" },
      { item: "Dual-path communicator (cellular and IP) to the central station", unit: "unit" },
      { item: "Interfaces: elevator recall, HVAC shutdown, door holder release, sprinkler monitoring and other relay outputs", unit: "unit" },
      { item: "Firestopping at every cable and raceway penetration through rated walls and floors", unit: "unit" },
      { item: "Programming: device addressing, zone mapping, sequence of operations, labels and the device map at the panel", unit: "fixed" },
      { item: "Pre-test of every device, then the AHJ acceptance test with the NFPA 72 record of completion", unit: "fixed" },
      { item: "Monitoring account set up with the central station and signal test", unit: "fixed", when: "the system is centrally monitored" },
      { item: "Owner training, as-built drawings, O&M and inspection log turned over; packaging hauled off", unit: "fixed" },
    ],
    avoid: [
      "'Fire alarm system' as one line with no panel, device or appliance count",
      "'Wiring' with no cable type or length",
      "the panel and every device priced as one line",
      "sprinkler piping and heads — the fire protection scope",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Device and appliance counts are from the stamped drawings; cable lengths are measured along the routed path",
      "Monitoring fees are recurring and quoted separately",
      "Line-voltage power to the panel is by the electrical scope",
      "Patching around devices and raceway is by others unless listed",
    ],
  },

  "residential-sprinkler-retrofit": {
    basis: "sprinkler heads each; pipe by linear feet and material; ceiling openings and drywall patch each or by square feet; riser, design, tests and permits fixed",
    steps: [
      { item: "Water supply evaluation: flow and pressure test at the meter or hose bib, meter size and service line checked against the NFPA 13D demand", unit: "fixed" },
      { item: "NFPA 13D design: head layout, hydraulic calculations and plans submitted to the fire marshal and building department", unit: "fixed" },
      { item: "Fire sprinkler permit with rough-in and final inspections scheduled", unit: "fixed" },
      { item: "Water service upgrade: 1 in. or larger service line from the meter and meter upsizing with the purveyor", unit: "linear ft", when: "the supply cannot meet the demand" },
      { item: "Stored-water tank and pump sized to the two-head demand", unit: "fixed", when: "the supply is a well or is too small even after upsizing" },
      { item: "Riser: control valve, check valve, pressure gauge, drain and waterflow switch in an accessible location", unit: "unit" },
      { item: "Backflow preventer at the sprinkler connection as the purveyor requires", unit: "unit", when: "the purveyor requires backflow protection" },
      { item: "Ceiling and wall openings cut for the pipe runs and heads, marked for patching", unit: "unit" },
      { item: "Sprinkler piping: listed CPVC or PEX by size run through the attic, joists and walls with hangers per the listing", unit: "linear ft" },
      { item: "Freeze protection: insulation tented over pipe in the attic and at exterior walls", unit: "linear ft", when: "pipe runs through unheated space" },
      { item: "Residential concealed pendent and sidewall heads by K-factor and temperature rating, with white cover plates", unit: "unit" },
      { item: "Tie-in to the domestic plumbing for a multipurpose network", unit: "unit", when: "the system is a multipurpose network" },
      { item: "Waterflow switch wired to an exterior bell or the home alarm panel", unit: "unit" },
      { item: "Drywall patch: openings closed, taped and textured to match, ready for paint", unit: "sqft" },
      { item: "Hydrostatic test and flush, flow test at the inspector's test connection, final inspection", unit: "fixed" },
      { item: "Owner documents: as-built plan, insurance certificate, maintenance instructions; cleanup and debris hauled off", unit: "fixed" },
    ],
    avoid: [
      "'Sprinkler system' with no head count or pipe material",
      "'Drywall' with no square footage",
      "the pipe and the drywall repair priced as one line",
      "a commercial NFPA 13 system in a home — a different design standard",
      "'Miscellaneous' or 'labor' lines",
    ],
    notes: [
      "Head count and pipe lengths are from the NFPA 13D layout; a design change at plan review is priced as a change",
      "Paint after the drywall patch is by the homeowner unless listed",
      "Purveyor and permit fees are passed through at the published rate",
      "Concealed heads are used where ceilings allow; exposed heads in unfinished areas",
    ],
  },
};
