// Smart Proposal procedures — Roadway & Transportation. See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  "roadway-highway": {
    basis: "earthwork by the cubic yard; subgrade, base and hot-mix lifts by the square yard at a stated depth with tonnage named; pipe, curb and guardrail by the foot; structures each",
    steps: [
      { item: "Pre-construction: survey control and construction staking from the DOT plans, utility coordination meeting, NPDES permit and SWPPP posted, and submittals approved (mix designs, aggregate sources, QC plan)", unit: "fixed" },
      { item: "Maintenance of traffic through the project: DOT-standard temporary traffic control plan with advance signs, drums, arrow boards, changeable message signs, temporary barrier and the lane-closure phasing", unit: "fixed" },
      { item: "Clearing and grubbing inside the construction limits: trees, stumps and brush removed, debris chipped or hauled off", unit: "sqft" },
      { item: "Erosion and sediment control per the SWPPP: silt fence, inlet protection, stabilized entrances and slope seeding, maintained weekly and after rain", unit: "linear ft" },
      { item: "Removal of the existing pavement, curb and drainage structures: saw-cut, broken out, loaded and hauled to a recycler", unit: "sq yards", when: "an existing roadway is being reconstructed" },
      { item: "Roadway excavation and embankment: cut to grade, fill placed in 8 in. lifts and compacted to 95% standard Proctor, borrow imported where the cut is short", unit: "cu yards" },
      { item: "Storm drainage pipe: reinforced concrete (Class III) or HDPE at the stated diameter laid on stone bedding to grade, trench backfilled in compacted lifts", unit: "linear ft" },
      { item: "Drainage structures: precast catch basins, manholes, curb inlets and headwalls set on stone, frames and grates raised to finished grade", unit: "unit" },
      { item: "Utility crossings and relocations: steel or PVC casings bored or trenched under the roadway for water, sewer and conduit", unit: "linear ft", when: "utilities cross the alignment or are relocated" },
      { item: "Subgrade preparation: scarify, moisture-condition and compact the top 12 in. to 95%, proof-roll with a loaded tandem, undercut soft areas and rebuild with geotextile and stone", unit: "sq yards" },
      { item: "Aggregate base course: DOT-spec dense-graded crushed stone spread and compacted in lifts to the stated depth (typically 8-12 in.), tonnage named", unit: "cu yards" },
      { item: "Prime coat: MC-30 or emulsified asphalt prime on the finished base before the first lift", unit: "sq yards" },
      { item: "Hot-mix asphalt binder course at the stated compacted depth (typically 3-4 in.): Superpave mix named, paver-laid with tonnage named, tack coat between lifts", unit: "sq yards" },
      { item: "Hot-mix asphalt surface course at the stated compacted depth (typically 1.5-2 in.): mix and tonnage named, rolled to the specified density with longitudinal joints staggered", unit: "sq yards" },
      { item: "Portland cement concrete pavement: slipformed at the stated thickness with dowel baskets, tie bars, sawed joints sealed and a sprayed curing compound", unit: "sq yards", when: "a concrete pavement section is specified" },
      { item: "Concrete curb and gutter or barrier curb at the DOT standard profile, slipformed with expansion joints and the driveway aprons", unit: "linear ft" },
      { item: "Shoulders: aggregate or paved shoulders graded and compacted at the stated width and slope", unit: "sq yards" },
      { item: "Guardrail with MASH terminals and delineators at the plan locations", unit: "linear ft", when: "guardrail is on the plans" },
      { item: "Permanent pavement markings: thermoplastic or epoxy lines, symbols and raised markers at the plan spacing", unit: "linear ft" },
      { item: "Signs and posts, plus signal and lighting foundations and conduit", unit: "unit", when: "signs, signals or lighting are on the plans" },
      { item: "Quality control testing at the DOT frequency: nuclear density and cores on base and asphalt, gradation and asphalt content, concrete cylinders and air", unit: "fixed" },
      { item: "Final: topsoil, seed and mulch on the slopes, cleanup, punch-list walk with the inspector and the as-built drawings", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Paving' or 'Asphalt' line with no lift, depth, mix or tonnage",
      "'Earthwork' or 'Grading' with no cut and fill yardage",
      "'Traffic control' with no plan, devices or phasing named",
      "structures and pipe priced as one drainage lump sum",
      "a 'general conditions' or 'contingency' line",
    ],
    notes: [
      "Quantities are plan quantities by station; paid quantities follow the field measurement and the DOT unit-price schedule",
      "Hot-mix tonnage is named per lift from the plan area, depth and mix density; asphalt cement price adjustments follow the index in the contract",
      "Rock excavation, unsuitable subgrade beyond the plan undercut and unmarked utilities are priced as a change",
      "Testing follows the DOT frequency; failing density or thickness is corrected at the contractor's cost",
    ],
  },
  "road-construction": {
    basis: "road by the foot of centerline at the stated width; earthwork by the cubic yard; base and asphalt by the square yard at a stated depth, tonnage named; curb and pipe by the foot",
    steps: [
      { item: "Construction staking: centerline, offsets, curb lines and grade stakes set from the civil plans, right-of-way and easements flagged", unit: "fixed" },
      { item: "Permits and agency: grading and right-of-way permits, pre-construction meeting with the city or county inspector, haul route and work hours approved", unit: "fixed" },
      { item: "Traffic control and detour at the tie-in: signs, barricades and flaggers, with resident and emergency access kept open", unit: "fixed", when: "the road ties into a public street or serves occupied lots" },
      { item: "Clearing, grubbing and topsoil strip: vegetation removed, topsoil stockpiled for the shoulders and swales", unit: "sqft" },
      { item: "Pulverize or remove the old road: full-depth reclamation of the asphalt and base as new sub-base, or excavation and haul-off", unit: "sq yards", when: "an existing road is being reconstructed" },
      { item: "Mass excavation and fill: cut to subgrade, embankment placed in 8 in. lifts compacted to 95%, ditch lines and shoulders shaped", unit: "cu yards" },
      { item: "Underground utilities in the road: water main, sanitary sewer, storm sewer and dry-utility conduit set before the base, trenches backfilled in compacted lifts", unit: "linear ft", when: "utilities are installed under the road" },
      { item: "Storm structures: catch basins, curb inlets and junction boxes set on stone and raised to grade", unit: "unit" },
      { item: "Culverts at driveways and cross-drains: RCP or HDPE at the stated diameter with flared ends and riprap at the outlets", unit: "linear ft", when: "the road crosses a ditch or drainage way" },
      { item: "Subgrade: top 12 in. moisture-conditioned and compacted to 95%, proof-rolled, soft areas undercut and replaced, geogrid where the soils report requires it", unit: "sq yards" },
      { item: "Sub-base: 3 in. minus crushed rock spread and compacted at the stated depth", unit: "cu yards", when: "the pavement section carries a sub-base" },
      { item: "Aggregate base: dense-graded crushed stone at the stated depth (typically 6-10 in.) compacted to 98%, tonnage named", unit: "cu yards" },
      { item: "Concrete curb and gutter: 6 in. barrier or roll curb slipformed to the standard detail, expansion joints at the stated spacing", unit: "linear ft" },
      { item: "Prime coat on the base, or tack coat on the reclaimed surface, before the first asphalt lift", unit: "sq yards" },
      { item: "Hot-mix binder course at the stated compacted depth (typically 2-3 in.), mix type and tonnage named, paver-laid and rolled", unit: "sq yards" },
      { item: "Hot-mix surface course at the stated compacted depth (typically 1.5-2 in.), mix type and tonnage named, joints staggered from the binder", unit: "sq yards" },
      { item: "Sidewalk: 4 in. concrete at the plan width with ADA curb ramps at each corner", unit: "sqft", when: "sidewalk is on the plans" },
      { item: "Street signs, stop signs and street-light conduit and bases", unit: "unit", when: "signs or lighting are on the plans" },
      { item: "Striping: centerline, edge lines and stop bars in paint or thermoplastic", unit: "linear ft", when: "the road is striped" },
      { item: "Shoulder and swale finish: topsoil, seed and mulch, and driveway tie-ins matched to the existing", unit: "sqft" },
      { item: "Density and thickness testing: nuclear density on subgrade, base and asphalt, cores where required, and the inspector's sign-off", unit: "fixed" },
      { item: "Final sweep, punch list, as-builts and the maintenance bond for acceptance", unit: "fixed" },
    ],
    avoid: [
      "'Road construction' as one lump line with no section, lifts or lengths",
      "'Base' with no depth, gradation or compaction",
      "utilities under the road hidden in the earthwork price",
      "'Grading' with no cut and fill yardage or subgrade compaction stated",
    ],
    notes: [
      "The pavement section (sub-base, base and asphalt lifts) follows the civil plans or the jurisdiction's standard for the road classification",
      "Earthwork is balanced on site where the plan allows; imported borrow or exported spoils are priced per yard",
      "Unsuitable subgrade, rock and groundwater beyond the plan quantities are priced as a change",
      "Acceptance and the maintenance bond follow the jurisdiction's inspection and testing results",
    ],
  },
  "road-milling": {
    basis: "milled area by the square yard at a stated depth; edge and butt joints by the foot; millings hauled by the cubic yard; structures each",
    steps: [
      { item: "Pre-milling survey: depth confirmed against cores or the existing section, manholes, valves, monuments and detector loops marked and photographed, milling limits painted", unit: "fixed" },
      { item: "Traffic control for the milling train: lane closure with signs, cones and an arrow board, flaggers at intersections and driveways", unit: "fixed" },
      { item: "Utility structures plated or ramped ahead of the mill so the drum clears them", unit: "unit" },
      { item: "Cold milling of the asphalt surface at the stated depth (typically 1.5-2 in. for an overlay, full depth for a rebuild) in continuous passes, grade and slope held by sonic ski or string line", unit: "sq yards" },
      { item: "Edge milling along the curb line and gutter lip so the new overlay meets the gutter flush", unit: "linear ft", when: "the road is curbed" },
      { item: "Butt joints and tapers milled at the project limits, intersections and driveways so the overlay ties in without a bump", unit: "linear ft" },
      { item: "Fine milling around manholes, valve boxes and inlets and in tight radii with a small (2-4 ft) mill", unit: "unit" },
      { item: "Millings loaded from the mill conveyor into trucks and hauled to the recycling yard or the owner's stockpile", unit: "cu yards" },
      { item: "Milled surface swept with a pickup broom and the joints and gutters blown clean before it opens to traffic or is tacked", unit: "sq yards" },
      { item: "Temporary asphalt wedges at the open milled edges and driveways so traffic can cross before paving", unit: "unit", when: "the milled surface stays open to traffic before the overlay" },
      { item: "Manhole and valve-box frames raised to the overlay grade with riser rings or rebuilt frames", unit: "unit", when: "structures are reset for the overlay" },
      { item: "Tack coat: SS-1h emulsion at the stated rate on the milled surface ahead of the paver", unit: "sq yards", when: "the milling crew also tacks for the paving crew" },
      { item: "Milled surface check: depth measured with a straight edge and gauge every 100 ft, scabs and loose material corrected", unit: "fixed" },
      { item: "Cleanup: spilled millings swept at the load-out, dust controlled with a water truck, milling machine and trucks removed", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Milling' line with no depth or square yardage",
      "'Haul' with no millings volume or destination stated",
      "the paving overlay priced inside the milling line",
      "'Mobilization' with no machine named",
    ],
    notes: [
      "Milling depth is the average stated depth; variable-depth or profile milling is priced separately",
      "Millings belong to the owner or the contractor as the contract states; hauling is priced per yard to the stated destination",
      "Concrete, brick or buried rail found under the asphalt stops the mill and is priced as a change",
      "The milled surface should be paved within the days stated; longer exposure requires temporary ramps and maintenance",
    ],
  },
  "chip-seal": {
    basis: "treated area by the square yard with the emulsion and chip rates stated per square yard; crack and patch prep by the foot and square yard",
    steps: [
      { item: "Pavement condition walk: cracks, potholes, edge failures and bleeding mapped, and the emulsion and chip rates set from the surface texture and traffic", unit: "fixed" },
      { item: "Traffic control: pilot car, flaggers and signs for one-lane operation, loose-chip and reduced-speed signs posted through the cure", unit: "fixed" },
      { item: "Crack sealing of cracks over 1/4 in. with hot-pour rubberized sealant, blotted with sand", unit: "linear ft", when: "cracks over 1/4 in. are present" },
      { item: "Patching of potholes and failed areas with hot-mix asphalt, compacted flush and cured before the seal", unit: "sq yards", when: "potholes or failed areas are present" },
      { item: "Surface cleaning: power broom and blower to remove dust, vegetation and debris; manholes and valves covered, gutters and driveways masked", unit: "sq yards" },
      { item: "Asphalt emulsion (CRS-2P or HFRS-2P polymer-modified) sprayed at the stated rate (typically 0.35-0.45 gal per sq yard) by a computer-controlled distributor at the spray temperature", unit: "sq yards" },
      { item: "Cover aggregate: clean, dry 3/8 in. or 1/2 in. chips (pre-coated where specified) spread by a self-propelled chip spreader immediately behind the distributor at the stated rate, tonnage named", unit: "sq yards" },
      { item: "Rolling with pneumatic rubber-tire rollers in three passes within minutes of the chip spread to seat the aggregate", unit: "sq yards" },
      { item: "Second course: a second emulsion shot and 1/4 in. chips over the first course", unit: "sq yards", when: "a double chip seal is specified" },
      { item: "Initial sweep of loose chips after cure (next morning), and a second sweep after 2-3 days of traffic, sweepings hauled off", unit: "sq yards" },
      { item: "Fog seal: diluted CSS-1h emulsion sprayed at about 0.10 gal per sq yard over the swept chips to lock the surface and darken it", unit: "sq yards", when: "a fog seal is specified" },
      { item: "Manholes and valves uncovered, masking pulled, gutters and driveway aprons cleaned of emulsion and chips", unit: "unit" },
      { item: "Pavement markings: temporary tabs through the cure, then paint or thermoplastic lines replaced", unit: "linear ft", when: "the road is striped" },
      { item: "Cleanup: excess chips swept from driveways, sidewalks and shoulders, signs pulled and the lanes opened at speed", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Chip seal' line with no emulsion, chip size or rates",
      "'Prep' with no cracks sealed, patches or cleaning named",
      "sweeping or fog seal left off and the loose-chip problem left to the owner",
      "an asphalt overlay priced as if it were a chip seal",
    ],
    notes: [
      "Chip seal is placed in dry weather with pavement over 60 deg F; the schedule moves with the forecast",
      "Emulsion and chip rates are stated per square yard and adjusted in the field to the surface texture",
      "Loose chips are normal for the first days; the sweeps listed remove them and windshield claims are not covered",
      "Failed areas beyond the listed patches are priced per square yard as a change",
    ],
  },
  "slurry-seal": {
    basis: "treated area by the square yard at the ISSA type and application rate stated; crack and patch prep by the foot and square yard; markings by the foot",
    steps: [
      { item: "Surface evaluation and mix design: ISSA A105 Type I, II or III chosen for the traffic, mix design submitted with the aggregate source, emulsion (CQS-1h or polymer-modified) and additives", unit: "fixed" },
      { item: "Notices and traffic control: residents and tenants notified 48 hours ahead, no-parking signs posted, lanes closed with cones and flaggers through placement and cure", unit: "fixed" },
      { item: "Crack sealing of cracks over 1/4 in. with hot-applied sealant at least a week ahead of the slurry", unit: "linear ft", when: "cracks over 1/4 in. are present" },
      { item: "Patching of failed areas and potholes with hot-mix asphalt, compacted flush", unit: "sq yards", when: "failed areas or potholes are present" },
      { item: "Cleaning: power broom, blower and hand work, oil spots scrubbed and primed, vegetation removed from cracks and edges", unit: "sq yards" },
      { item: "Manholes, valve covers, monuments and inlets masked with roofing felt or covers so they lift clean", unit: "unit" },
      { item: "Tack of oxidized or absorbent surfaces with diluted emulsion before the slurry", unit: "sq yards", when: "the surface is dry, raveled or oxidized" },
      { item: "Slurry seal placed by a continuous-flow slurry machine: Type II at 15-18 lb or Type III at 18-22 lb of dry aggregate per sq yard, spread with a rubber strike-off box, hand-squeegeed at edges and around structures", unit: "sq yards" },
      { item: "Second course placed after the first cures", unit: "sq yards", when: "a two-course application is specified" },
      { item: "Joints, radii, intersections and driveway approaches worked with hand squeegees so there are no ridges or drop-offs", unit: "linear ft" },
      { item: "Rolling with a pneumatic roller once the mat has set", unit: "sq yards", when: "the surface is a parking lot or the specification requires rolling" },
      { item: "Cure and uncover: surface closed 2-4 hours until it takes traffic, covers pulled and structures cleaned", unit: "unit" },
      { item: "Pavement markings replaced after 24 hours of cure: paint or thermoplastic stripes, stalls and legends", unit: "linear ft", when: "the surface is striped" },
      { item: "Cleanup: drips and tracking cleaned off curbs and driveways, loose material swept after 24-48 hours, lanes opened", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Slurry seal' line with no ISSA type or rate",
      "'Cleaning' with no oil-spot treatment or vegetation removal named",
      "crack sealing the same day as the slurry, priced as one line",
      "a micro-surfacing or overlay priced under the slurry name",
    ],
    notes: [
      "Slurry is placed with pavement and air over 50 deg F and rising, no rain forecast for 24 hours; the schedule moves with the weather",
      "Application rate is stated per square yard of dry aggregate and verified by the mix design",
      "The cure and the parking closure are stated per phase; cars left in the lot are worked around and the missed area is not resealed",
      "Failed areas beyond the listed patches are priced per square yard as a change",
    ],
  },
  "crack-sealing": {
    basis: "cracks by the linear foot by width class; routing by the foot; sealant type stated; blotting by the square yard",
    steps: [
      { item: "Crack survey: cracks walked and measured by width (1/4-1/2 in., 1/2-1 in., over 1 in.), working cracks noted, alligatored areas excluded and marked for patching", unit: "fixed" },
      { item: "Traffic control: cones, signs and a lane closure with a flagger for the crew and the melter", unit: "fixed" },
      { item: "Routing: cracks 1/4-3/4 in. routed with a random-crack router to a 1/2 in. by 1/2 in. reservoir (or the stated dimensions) for a full sealant band", unit: "linear ft", when: "the specification calls for a routed reservoir" },
      { item: "Cleaning: compressed air and a hot-air lance to dry the crack and blow out dust, vegetation and moisture", unit: "linear ft" },
      { item: "Hot-pour sealant: rubberized asphalt meeting ASTM D6690 Type II (Type IV in cold climates) melted in an oil-jacketed melter and applied with a wand at about 380 deg F", unit: "linear ft" },
      { item: "Overband: sealant squeegeed in a 2-3 in. band over the crack, or struck flush where the specification calls for flush fill", unit: "linear ft" },
      { item: "Wide cracks and joints over 1 in. filled with a polymer-modified mastic with aggregate, placed in lifts", unit: "linear ft", when: "cracks or joints wider than 1 in. are present" },
      { item: "Pavement-to-gutter and curb joints sealed along the concrete edge", unit: "linear ft", when: "the surface meets a concrete gutter or curb" },
      { item: "Blotting: sand or a detackifier over the fresh sealant so traffic does not track it before it cools", unit: "sq yards" },
      { item: "Cure and open: sealant cooled 30-60 minutes before traffic, tracking checked", unit: "fixed" },
      { item: "Cleanup: routing dust swept, sealant spills scraped, signs and cones removed", unit: "fixed" },
      { item: "Sealed-footage map by section, delivered with the invoice", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Crack sealing' line with no footage, width class or sealant type",
      "sealing alligatored areas as if they were cracks — those are patches",
      "'Cleaning' with no hot-air lance or air named",
      "cold-pour crack filler sold as hot-pour sealant",
    ],
    notes: [
      "Footage is measured on site by width class; cracks under 1/4 in. are not sealed unless the specification requires it",
      "Sealing is done in dry conditions with pavement over 40 deg F and the crack free of moisture",
      "Alligatored and heaved areas are excluded from the sealing footage and priced as patches",
      "Sealant tracking in hot weather is controlled by blotting; tire pickup after the cure is not a defect",
    ],
  },
  sealcoating: {
    basis: "sealed area by the square foot with coats and material stated; crack fill by the foot; striping by the foot; stencils and stalls each",
    steps: [
      { item: "Site walk and scheduling: area measured, oil spots, alligatored areas and drainage noted, two dry days over 50 deg F scheduled, tenants notified to move cars", unit: "fixed" },
      { item: "Barricades and no-parking: cones, tape and signs at every entrance, lot closed in phases so the tenants keep access", unit: "fixed", when: "the lot stays in use during the work" },
      { item: "Cleaning: power broom and blower, wire brush at the edges and cracks, weeds pulled, caked dirt pressure-washed", unit: "sqft" },
      { item: "Oil spots scrubbed and coated with an oil-spot primer so the sealer bonds", unit: "unit" },
      { item: "Hot rubberized crack filling of cracks 1/4 in. to 1 in. wide", unit: "linear ft" },
      { item: "Alligatored areas skim-patched with a trowel-grade patch mix, or cut out and patched with hot-mix", unit: "sqft", when: "failed areas are present" },
      { item: "First coat: asphalt-emulsion sealer (or refined coal-tar where allowed) mixed with 2-4 lb of sand per gallon and a latex additive, spray or squeegee applied at the stated rate", unit: "sqft" },
      { item: "Second coat applied in the cross direction after the first cures (2-4 hours)", unit: "sqft" },
      { item: "Third coat on drive lanes and entrances", unit: "sqft", when: "the lot carries heavy traffic" },
      { item: "Edges cut in by hand brush at curbs, sidewalks, buildings and structures, masked for a clean line", unit: "linear ft" },
      { item: "Cure: lot closed 24-48 hours (longer in cool weather) before it opens to traffic", unit: "fixed" },
      { item: "Re-striping: stalls, ADA stalls and hatching, fire lane, arrows and stop bars in traffic paint on the cured sealer", unit: "linear ft", when: "the lot is striped" },
      { item: "Stencils and curb paint: ADA symbols, arrows, stall numbers, NO PARKING and painted curbs", unit: "unit", when: "stencils or curb paint are included" },
      { item: "Barricades removed, lot edges swept, spills washed off the concrete", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Sealcoat' line with no coats, material or square footage",
      "crack filling folded into the sealcoat price with no footage",
      "one coat sold as a full seal on a lot",
      "an asphalt patch priced inside the sealcoat line",
      "striping on a proposal with no layout or line count stated",
    ],
    notes: [
      "Sealcoat is applied at 50 deg F and rising with no rain for 24 hours; the schedule moves with the weather",
      "New asphalt is sealed no sooner than 90 days after paving; a badly failed lot is patched before sealing",
      "Cars left in the lot are worked around and the missed area is not resealed",
      "Sealer wears in drive lanes first; a two-coat lot is resealed every 2-4 years",
    ],
  },
  "pothole-repair": {
    basis: "patches each by size class or by the square foot of repair area, with the method and depth stated; saw cuts by the foot",
    steps: [
      { item: "Pothole survey: each hole measured for area and depth, photographed and numbered, and the method chosen per hole (hot-mix cutout, infrared or cold patch)", unit: "fixed" },
      { item: "Traffic control: cones, signs and a flagger while the crew and truck occupy the lane", unit: "fixed" },
      { item: "Saw-cut or mill the patch edges 12 in. beyond the failed area into sound pavement, faces vertical and squared", unit: "linear ft" },
      { item: "Remove the failed asphalt and loose base to sound material, base recompacted and crushed stone added where it is soft", unit: "sqft" },
      { item: "Tack coat sprayed on the vertical faces and floor of the cutout", unit: "unit" },
      { item: "Hot-mix asphalt patch (surface mix at 3 in. compacted or matched to the existing) placed hot from a hot box and compacted with a vibratory plate or roller, crowned 1/4 in.", unit: "sqft" },
      { item: "Infrared repair: the existing asphalt heated 8-10 minutes, raked, rejuvenator added, new hot-mix blended in and compacted to a seamless patch", unit: "sqft", when: "the infrared method is chosen" },
      { item: "Cold patch: high-performance cold mix compacted in lifts as a temporary or winter repair", unit: "unit", when: "the weather is too cold for hot-mix or the repair is temporary" },
      { item: "Patch seams sealed with a hot-pour sealant band", unit: "linear ft" },
      { item: "Removed asphalt hauled to a recycler", unit: "cu yards" },
      { item: "Cleanup: patch area swept, cones pulled, patches opened to traffic once cooled", unit: "fixed" },
      { item: "Patch log with locations and photos, and the warranty on the hot-mix cutout patches", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Pothole' or 'Patching' line with no count, size or method",
      "throw-and-go cold patch sold as a permanent repair",
      "'Materials' separate from the patch line",
      "a resurfacing or overlay priced as pothole repair",
    ],
    notes: [
      "Patches are priced per hole by size class or per square foot of the cut area; the cut is 12 in. into sound pavement on every side",
      "Hot-mix availability sets the schedule; plants close in winter and cold patch is the interim repair",
      "Base failure under a pothole beyond the listed depth is priced as a change",
      "The warranty covers hot-mix cutout and infrared patches; cold patch is temporary and not warranted",
    ],
  },
  "concrete-curb-gutter": {
    basis: "curb and gutter by the linear foot at the stated profile; removal by the foot; base by the cubic yard; driveway aprons, inlet throats and radii each",
    steps: [
      { item: "Layout: line and grade from the plan or matched to the existing curb, string line and stakes set, radii and driveway openings marked", unit: "fixed" },
      { item: "Traffic and pedestrian control: cones, signs, and barricades at the open trench and fresh concrete", unit: "fixed" },
      { item: "Saw-cut and remove the existing curb and gutter, broken out and hauled to a recycler, with the asphalt cut back 12-18 in. from the gutter lip", unit: "linear ft", when: "existing curb is being replaced" },
      { item: "Excavate to the section, compact the subgrade and place 4-6 in. of compacted crushed stone base", unit: "cu yards" },
      { item: "Forms set to line and grade with radius forms, or a slipform curb machine on string line, at the stated profile (6 in. vertical, roll or mountable curb with an 18-30 in. gutter pan)", unit: "linear ft" },
      { item: "Tie-in dowels drilled and epoxied into the existing curb ends, #4 by 18 in.", unit: "unit" },
      { item: "Concrete: 4,000 psi air-entrained (5-7% air) mix placed, consolidated and finished to the profile with the pan sloped to drain, broom finish and tooled edges", unit: "linear ft" },
      { item: "Joints: contraction joints tooled or sawed at 10 ft, 1/2 in. expansion joints with preformed filler at 50-100 ft, at radius points and at every structure", unit: "unit" },
      { item: "Driveway aprons and depressed curb cuts formed at the openings with the drop and transitions per the standard detail", unit: "unit", when: "driveways open onto the curb line" },
      { item: "Curb inlet and catch basin throats formed into the curb line", unit: "unit", when: "inlets sit in the run" },
      { item: "Curing compound sprayed or wet cure; forms stripped after 24 hours and honeycomb patched", unit: "linear ft" },
      { item: "Backfill: topsoil behind the curb, compacted stone in front so the gutter lip meets the pavement", unit: "linear ft" },
      { item: "Asphalt patch along the gutter lip where the pavement was cut back", unit: "sqft", when: "existing pavement was cut for the removal" },
      { item: "Cleanup: washout contained, forms and spoils removed, sweep, and the curb opened to traffic after 7 days", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Curb' line with no profile, footage or mix",
      "'Concrete' priced by the yard with no curb footage",
      "removal, base and pour as one lump line",
      "sidewalk or driveway flatwork hidden in the curb price",
    ],
    notes: [
      "Curb profile follows the jurisdiction's standard detail; the footage is measured along the face including radii",
      "Concrete is placed at 40 deg F and rising with blankets in cold weather; hot-weather pours are retarded and wet-cured",
      "Unsuitable subgrade, utilities in the curb line and inlet rebuilds beyond the listed throats are priced as a change",
      "The curb carries no vehicle load for 7 days; damage from early traffic is not warranted",
    ],
  },
  sidewalk: {
    basis: "sidewalk by the square foot at the stated width and thickness; removal by the square foot; base by the cubic yard; forms and edges by the foot; ramps each",
    steps: [
      { item: "Layout and grade: walk staked for width and alignment, cross slope held to 2% max and running slope to 5% max, driveway crossings and ramp locations marked", unit: "fixed" },
      { item: "Right-of-way or encroachment permit, inspection scheduling and the 811 utility locate", unit: "fixed" },
      { item: "Pedestrian and traffic control: detour signs, barricades and a covered walkway where the route stays open", unit: "fixed", when: "the walk is in the public right-of-way" },
      { item: "Demolition of the existing sidewalk: saw-cut at the joints, broken out and hauled to a recycler", unit: "sqft", when: "existing sidewalk is being replaced" },
      { item: "Tree root pruning under the walk by hand or air spade with an arborist's direction, and a root barrier along the walk", unit: "linear ft", when: "tree roots have lifted the walk" },
      { item: "Excavation to grade and subgrade compacted to 95%", unit: "sqft" },
      { item: "Aggregate base: 4 in. of crushed stone compacted under the walk", unit: "cu yards" },
      { item: "Forms set to line and grade with 1/2 in. expansion joints at 20-30 ft and at every structure, driveway and building", unit: "linear ft" },
      { item: "Reinforcement: 6x6 W1.4 welded wire mesh or synthetic fibers, and #4 rebar at driveway crossings", unit: "sqft", when: "the specification or a driveway crossing calls for reinforcement" },
      { item: "Concrete: 4 in. (6 in. at driveway crossings) of 4,000 psi air-entrained concrete screeded, floated and broom-finished, tooled edges and contraction joints at 5 ft", unit: "sqft" },
      { item: "ADA curb ramps at intersections with detectable warning panels", unit: "unit", when: "the walk meets a street crossing" },
      { item: "Curing compound or wet cure, kept clear of foot traffic 24 hours and vehicles 7 days", unit: "sqft" },
      { item: "Edges backfilled with topsoil and seeded or sodded, asphalt wedge at driveway aprons", unit: "linear ft" },
      { item: "Cleanup: spoils and forms hauled off, sweep, and the city inspection sign-off", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Sidewalk' line with no width, thickness or square footage",
      "'Concrete' with no psi, air content or finish",
      "removal, base and pour as one line",
      "a driveway approach or curb priced inside the sidewalk line",
    ],
    notes: [
      "Width, thickness and slopes follow the jurisdiction's standard and the ADA; the panel length is measured on site",
      "Lifted panels from tree roots are replaced only after root pruning; the tree's survival is not guaranteed",
      "Unsuitable subgrade, utilities in the line and driveway thickening beyond the listed crossings are priced as a change",
      "The walk is closed to foot traffic 24 hours and to vehicles 7 days",
    ],
  },
  "ada-ramp": {
    basis: "ramps each by type (perpendicular, parallel or blended transition); detectable warning panels each; removal and flatwork by the square foot; depressed curb by the foot",
    steps: [
      { item: "Survey and ramp design: existing grades shot at the corner, the ramp type chosen to hold a 1:12 (8.33%) running slope, 2% cross slope, a 4 ft by 4 ft landing and 1:10 flares, drawn for the inspector", unit: "unit" },
      { item: "Permits and coordination: right-of-way permit, the PROWAG or state standard drawing, and conflicts with signal poles, push-buttons and utilities resolved", unit: "fixed" },
      { item: "Pedestrian detour and traffic control at the corner: signs, barricades and a temporary accessible walkway", unit: "fixed" },
      { item: "Saw-cut and remove the existing curb, gutter and sidewalk in the ramp footprint, hauled off", unit: "sqft" },
      { item: "Valve boxes, pull boxes, sign posts and pedestrian push-buttons adjusted or relocated out of the ramp", unit: "unit", when: "structures or posts conflict with the ramp" },
      { item: "Subgrade compacted and 4 in. of crushed stone base placed under the ramp and landing", unit: "sqft" },
      { item: "Forms set to the surveyed elevations for the ramp, landing and flares or returned curbs, slopes checked with a smart level before the pour", unit: "unit" },
      { item: "Concrete: 6 in. of 4,000 psi air-entrained concrete on the ramp and landing, broom finish across the direction of travel, no lip over 1/4 in. at the gutter", unit: "sqft" },
      { item: "Depressed curb and gutter transitions with the gutter counter-slope held to 5% max", unit: "linear ft" },
      { item: "Detectable warning surface: cast-in-place or surface-applied truncated dome panels 24 in. deep across the full ramp width at the back of curb, contrasting color", unit: "unit" },
      { item: "Cure and slope verification: every running and cross slope read with a smart level after cure and recorded", unit: "unit" },
      { item: "Adjacent sidewalk, asphalt and lawn restored, signs reset", unit: "sqft" },
      { item: "Cleanup and the inspection sign-off with the as-built slope form", unit: "fixed" },
    ],
    avoid: [
      "a bare 'ADA ramp' line with no type, slope or dome panel",
      "domes listed by the square foot with no panel count or width",
      "sidewalk replacement priced as a ramp",
      "a ramp poured with no slope survey or verification line",
    ],
    notes: [
      "Ramps are built to the current PROWAG or state standard; where the existing corner cannot meet full compliance, the maximum-extent-feasible design is documented",
      "Ramp count and type come from the plan or the corner survey; a corner needing two ramps is two units",
      "Signal and utility relocation beyond the listed adjustments is priced as a change or by the utility",
      "A ramp that fails the slope verification is removed and re-poured at the contractor's cost",
    ],
  },
  "parking-lot-construction": {
    basis: "lot by the square yard of pavement at the stated section; earthwork and base by the cubic yard; curb and striping by the foot; islands, structures, signs and wheel stops each",
    steps: [
      { item: "Construction staking from the civil site plan: lot limits, curb lines, islands, drainage structures and finished grades set", unit: "fixed" },
      { item: "Permits and coordination: grading permit, stormwater and SWPPP filing, inspection scheduling and the 811 locate", unit: "fixed" },
      { item: "Erosion control: silt fence, inlet protection and a stabilized construction entrance", unit: "linear ft" },
      { item: "Demolition of the existing pavement, slabs or structures in the footprint, hauled to a recycler", unit: "sq yards", when: "the site is already built on" },
      { item: "Mass grading: cut and fill to subgrade with the lot pitched 1-2% to the inlets, fill compacted to 95%", unit: "cu yards" },
      { item: "Storm drainage: RCP or HDPE pipe at the stated diameter from the inlets to the outfall or detention system", unit: "linear ft" },
      { item: "Drainage structures: catch basins, curb inlets, junction boxes and the outlet control structure set to grade", unit: "unit" },
      { item: "Conduit and concrete bases for site lighting, with sleeves for irrigation and signage", unit: "unit", when: "site lighting or sleeves are on the plan" },
      { item: "Subgrade preparation: proof-roll, undercut soft spots and rebuild with stone over geotextile", unit: "sq yards" },
      { item: "Aggregate base at the stated depth (typically 6-8 in.) compacted to 98%, tonnage named", unit: "cu yards" },
      { item: "Concrete curb and gutter and island curbs (6 in. vertical or the plan profile) slipformed or formed", unit: "linear ft" },
      { item: "Concrete pads at the dumpster enclosure and heavy-duty drive lanes: 6-8 in. reinforced 4,000 psi", unit: "sqft", when: "dumpster pads or heavy-duty lanes are on the plan" },
      { item: "Prime coat on the base before the first asphalt lift", unit: "sq yards" },
      { item: "Hot-mix binder course at the stated compacted depth (typically 2-3 in.), mix and tonnage named", unit: "sq yards" },
      { item: "Hot-mix surface course at the stated compacted depth (typically 1.5 in.), mix and tonnage named, rolled to density", unit: "sq yards" },
      { item: "Sidewalks, ADA ramps and the accessible route from the stalls to the entrance", unit: "sqft", when: "walks or an accessible route are on the plan" },
      { item: "Striping: stalls, ADA stalls with access aisles and hatching, fire lane, arrows and stop bars in traffic paint", unit: "linear ft" },
      { item: "Signs, posts, bollards and wheel stops set", unit: "unit" },
      { item: "Islands and perimeter: topsoil, seed or sod and tree wells", unit: "sqft" },
      { item: "Density testing on base and asphalt and concrete cylinders on the curb and pads", unit: "fixed" },
      { item: "Final sweep, as-builts and the stormwater inspection sign-off", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Parking lot' or 'Paving' lump line with no section, lifts or area",
      "drainage pipe and structures priced as one line",
      "'Grading' with no yardage or compaction stated",
      "ADA stalls, signs or the access aisle left off the striping",
    ],
    notes: [
      "The pavement section follows the civil plan or the geotechnical recommendation; a heavy-duty section is priced where trucks travel",
      "Stall count and ADA count follow the plan and the local code; the accessible route is part of the lot",
      "Unsuitable subgrade, rock and utilities not on the plan are priced as a change",
      "Landscaping beyond the island topsoil and seed, and lighting fixtures and poles, are other trades",
    ],
  },
  "parking-lot-maintenance": {
    basis: "repairs by the square foot or each; crack seal by the foot; sealcoat by the square foot; striping by the foot; stencils, signs and bollards each",
    steps: [
      { item: "Condition survey: lot walked and mapped by section for cracks, alligatored areas, potholes, drainage and structure condition and faded markings, with a phasing plan so tenants keep parking", unit: "fixed" },
      { item: "Tenant notices and phasing barricades: cones, tape and signs sectioning the lot so half stays open", unit: "fixed" },
      { item: "Sweeping and blowing the lot, weeds pulled from cracks and edges", unit: "sqft" },
      { item: "Full-depth asphalt patches: saw-cut, remove, base recompacted, hot-mix at 3-4 in. compacted", unit: "sqft", when: "potholes or base failures are present" },
      { item: "Infrared or skin patches on alligatored areas", unit: "sqft", when: "alligatored areas are present" },
      { item: "Crack sealing of cracks over 1/4 in. with hot-pour rubberized sealant", unit: "linear ft" },
      { item: "Catch basin and drain repairs: frame reset, throat re-mortared, grate replaced", unit: "unit", when: "drainage structures are damaged" },
      { item: "Curb repair: broken sections replaced and wheel stops reset or replaced", unit: "linear ft", when: "curbs or wheel stops are damaged" },
      { item: "Sealcoat: two coats of asphalt-emulsion sealer with sand, spray or squeegee applied", unit: "sqft" },
      { item: "Cure and phase change: each section closed 24 hours before the next section starts", unit: "fixed" },
      { item: "Re-striping matched to the existing layout or the new plan: stalls, drive aisles, arrows and stop bars", unit: "linear ft" },
      { item: "ADA compliance: van stall, access aisles with hatching, signs at 60 in. and the stall count brought to code", unit: "unit", when: "ADA stalls are missing or non-compliant" },
      { item: "Stencils and curb painting: symbols, numbers, fire lane and painted curbs", unit: "unit" },
      { item: "Bollards, signs and speed bumps replaced or added", unit: "unit", when: "bollards, signs or speed bumps are included" },
      { item: "Cleanup and a maintenance schedule left with the owner: crack seal yearly, sealcoat every 2-4 years", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Repairs' or 'Maintenance' lump line with no patch area, footage or count",
      "sealcoat priced over alligatored areas that were never patched",
      "striping with no ADA stall or aisle stated",
      "a full overlay priced as maintenance",
    ],
    notes: [
      "Patch areas and crack footage are measured on the survey; hidden base failure under a patch is priced as a change",
      "Sealcoat and striping wait for dry weather over 50 deg F; the phasing keeps part of the lot open at every stage",
      "Cars left in a closed section are worked around and the missed area is not repaired",
      "ADA stall count and signage follow the current code for the lot size",
    ],
  },
  "traffic-control": {
    basis: "plan and setup fixed; signs, devices, arrow boards and message signs each; flaggers, pilot cars, attenuator trucks and the supervisor by the hour",
    steps: [
      { item: "Temporary traffic control plan: MUTCD Part 6 typical application or a site-specific plan drawn, permitted with the DOT or city, and the closure schedule approved", unit: "fixed" },
      { item: "Site review: traffic volumes, speed, sight distance, pedestrian and bus routes and business access noted; taper lengths and buffer space computed for the posted speed", unit: "fixed" },
      { item: "Public notice: portable message signs placed a week ahead and notices to police, fire, transit and schools", unit: "fixed", when: "the closure affects a major route or a transit line" },
      { item: "Advance warning signs: 48 in. orange diamond signs (ROAD WORK AHEAD, LANE CLOSED, FLAGGER AHEAD) on portable stands at the spacing for the speed", unit: "unit" },
      { item: "Channelizing devices: 28 in. or 36 in. cones, drums with retroreflective bands and warning lights, Type III barricades, set at the taper and tangent spacing", unit: "unit" },
      { item: "Arrow board at the closure taper and portable changeable message signs", unit: "unit" },
      { item: "Truck-mounted attenuator shadow vehicle protecting the crew", unit: "hour", when: "the road is high-speed or the operation is mobile" },
      { item: "Certified flaggers with STOP and SLOW paddles, Class 2 or Class 3 high-visibility apparel and radios at each flagger station", unit: "hour" },
      { item: "Pilot car for one-lane two-way operation", unit: "hour", when: "traffic is held to one lane in both directions" },
      { item: "Pedestrian accommodation: accessible temporary walkway, pedestrian barricades and detour signs", unit: "linear ft", when: "a sidewalk or crosswalk is closed" },
      { item: "Temporary pavement markings and covering of conflicting permanent signs", unit: "linear ft", when: "lanes are shifted" },
      { item: "Daily setup, walk-through and pickup: devices placed at the start of the shift, reset through the shift, and picked up or dropped to the overnight layout, logged", unit: "fixed" },
      { item: "Night operations: lighted devices, portable light towers and the night-shift crew", unit: "hour", when: "work runs at night" },
      { item: "Certified traffic control supervisor on site with daily inspection reports and the traffic control diary", unit: "hour" },
      { item: "Emergency call-out and replacement of struck or stolen devices", unit: "unit", when: "the contract covers device replacement" },
      { item: "Demobilization: every device removed, permanent signs uncovered, and the closure log delivered for the permit close-out", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Traffic control' line with no plan, devices or hours",
      "flaggers priced as a fixed sum with no hours or shifts",
      "devices with no count or day rate",
      "a plan line with no MUTCD or agency reference",
    ],
    notes: [
      "Device counts follow the typical application for the road speed and closure type; the plan is the contract document",
      "Flaggers and equipment are billed by the hour with a 4-hour minimum per call-out; shifts over 8 hours are billed at the overtime rate",
      "Devices struck or stolen are replaced at the unit rate; the traffic control diary records every setup and change",
      "Police details required by the agency are passed through at the agency's rate",
    ],
  },
  "road-striping": {
    basis: "lines by the linear foot by width and material; symbols, legends and raised markers each; removal by the foot; layout fixed",
    steps: [
      { item: "Layout: control points taken from the striping plan or the existing markings, offsets measured and spotted with paint every 25-50 ft", unit: "fixed" },
      { item: "Traffic control for a moving operation: shadow vehicle with an arrow board, cones behind the striper through the dry time", unit: "fixed" },
      { item: "Removal of conflicting or old markings by waterblasting or grinding, debris vacuumed", unit: "linear ft", when: "existing markings conflict with the new layout" },
      { item: "Surface preparation: sweep and blow the line path; new asphalt cured and new concrete cured 30 days with the curing compound removed", unit: "linear ft" },
      { item: "Primer or sealer on new concrete, or on aged asphalt ahead of thermoplastic", unit: "linear ft", when: "the surface is concrete or the material requires a primer" },
      { item: "Waterborne traffic paint lines (4 in. white or yellow at 15 mil wet) with glass beads dropped at 6-8 lb per gallon", unit: "linear ft" },
      { item: "Thermoplastic lines (90-125 mil extruded, or 60 mil sprayed) meeting AASHTO M249, with intermix and drop-on beads", unit: "linear ft", when: "thermoplastic is specified" },
      { item: "Preformed tape or epoxy lines set per the manufacturer at the plan locations", unit: "linear ft", when: "tape or epoxy is specified" },
      { item: "Symbols and legends: arrows, ONLY, crosswalk bars, stop bars and railroad crossings hand-applied in thermoplastic or stenciled paint", unit: "unit" },
      { item: "Raised pavement markers set in bituminous or epoxy adhesive at the plan spacing, snowplowable castings where required", unit: "unit", when: "raised markers are on the plan" },
      { item: "Retroreflectivity readings with a handheld retroreflectometer (ASTM E1710) and the report per the specification", unit: "fixed" },
      { item: "Curb painting: fire lane red, no-parking yellow and the stall ends", unit: "linear ft", when: "curbs are painted" },
      { item: "Cleanup: overspray removed, cones pulled and the lanes opened once the lines are dry", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Striping' line with no width, material or footage",
      "symbols counted by the foot instead of each",
      "'Paint' with no bead application stated",
      "thermoplastic and paint priced at one rate",
    ],
    notes: [
      "Footage is measured by line, not by lane mile; skip lines are measured by the painted length",
      "Markings go down on a dry surface over 50 deg F; new asphalt is striped in paint until it cures for thermoplastic",
      "Retroreflectivity minimums follow the specification; readings below the minimum are restriped at the contractor's cost",
      "Removal by grinding leaves a scar; waterblasting is priced where the scar is not acceptable",
    ],
  },
  guardrail: {
    basis: "guardrail by the linear foot by system type; terminals, transitions, posts and delineators each; removal by the foot; grading by the square foot",
    steps: [
      { item: "Layout: post spacing (6 ft 3 in. standard) and rail height (31 in. for MGS) staked, terminal locations and runout grading checked, 811 locate for the post line", unit: "fixed" },
      { item: "Traffic control: shoulder or lane closure with signs, drums and a truck-mounted attenuator", unit: "fixed" },
      { item: "Removal of the existing guardrail, posts and terminals, salvaged or hauled to scrap", unit: "linear ft", when: "existing rail is being replaced" },
      { item: "Grading behind the rail and at the terminal runout area to the standard slope", unit: "sqft", when: "the terminal or post line needs regrading" },
      { item: "Posts: W6x8.5 steel or 6x8 treated timber posts, 6 ft long, driven with a post driver at the spacing; drilled and backfilled where rock is met", unit: "unit" },
      { item: "Blockouts: 8 in. or 12 in. composite, timber or steel blockouts bolted to the posts", unit: "unit" },
      { item: "W-beam rail: 12-gauge galvanized W-beam (AASHTO M180) lapped in the direction of traffic, splice bolts torqued, mid-span splices for MGS", unit: "linear ft" },
      { item: "Thrie-beam transitions with nested rail and the connection to the bridge rail or concrete barrier", unit: "linear ft", when: "the rail meets a bridge or barrier" },
      { item: "End terminals: MASH TL-3 energy-absorbing tangent terminals, with the anchor, grading and offset per the manufacturer", unit: "unit" },
      { item: "Trailing-end anchors or buried-in-backslope terminals", unit: "unit", when: "the run ends away from traffic or against a backslope" },
      { item: "Delineators with reflective sheeting on the posts at the plan spacing", unit: "unit" },
      { item: "Cable barrier: driven posts and tensioned cables to the manufacturer's tension", unit: "linear ft", when: "a cable barrier section is specified" },
      { item: "Height and torque check, bolt tightening, and the certified installer's inspection report", unit: "fixed" },
      { item: "Cleanup: post holes backfilled, disturbed shoulder seeded, traffic control removed", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Guardrail' line with no system type, height or footage",
      "terminals priced by the foot instead of each",
      "'Posts' with no size or spacing",
      "a non-MASH terminal on a new installation",
    ],
    notes: [
      "The system (MGS, strong-post W-beam, thrie-beam or cable) and the terminal follow the DOT standard and the MASH crash-test level",
      "Post driving assumes soil; rock, utilities or concrete in the post line are priced per post as a change",
      "Footage is measured along the rail; terminals and transitions are counted each and not included in the rail footage",
      "The installer's certification and the manufacturer's inspection form are delivered with the invoice",
    ],
  },
  "road-sign": {
    basis: "signs each by size and sheeting; posts and foundations each; removals each; layout and MUTCD review fixed",
    steps: [
      { item: "Sign inventory and MUTCD review: locations, messages, sizes and mounting heights per the MUTCD and the state supplement, placement staked and the 811 locate", unit: "fixed" },
      { item: "Traffic control for the installation crew: cones, signs and a shadow vehicle on the shoulder", unit: "fixed" },
      { item: "Sign fabrication: 0.080 in. or 0.100 in. aluminum blanks with ASTM D4956 Type XI prismatic sheeting (Type IX where specified), digitally printed or cut legend, anti-graffiti overlay where required", unit: "unit" },
      { item: "Removal of the existing signs and posts, salvaged to the owner or recycled", unit: "unit", when: "signs are being replaced" },
      { item: "Post foundations: driven anchor sleeves or concrete footings sized for the sign area and wind load", unit: "unit" },
      { item: "Breakaway posts: 2 in. square perforated steel telescoping posts or U-channel with a breakaway coupler, or 4x4 timber in the anchor", unit: "unit" },
      { item: "Multi-post and large-sign supports: 3 in. or 4 in. square tube or W-beam posts in concrete foundations with slip bases", unit: "unit", when: "signs over 12 sq ft or multi-post assemblies are specified" },
      { item: "Sign mounting: signs bolted with theft-resistant hardware at 7 ft clearance (5 ft rural) and the lateral offset, stacked assemblies per the MUTCD", unit: "unit" },
      { item: "Overhead, mast-arm or bridge-mounted signs with the brackets and the lift", unit: "unit", when: "overhead or structure-mounted signs are specified" },
      { item: "Street name signs and post-mounted delineators", unit: "unit", when: "street name signs or delineators are on the list" },
      { item: "Retroreflectivity verification and a night drive inspection of every new sign", unit: "fixed" },
      { item: "Sign inventory log with GPS location, photo and install date for the owner's asset system", unit: "fixed" },
      { item: "Cleanup: footings backfilled and seeded, spoils removed, traffic control pulled", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Signs' line with no size, sheeting or count",
      "posts and signs priced as one unit with no post type named",
      "non-breakaway posts inside the clear zone",
      "sheeting with no ASTM D4956 type stated",
    ],
    notes: [
      "Signs are fabricated to the MUTCD and the state standard sign catalog; custom legends are priced per sign",
      "Foundations assume soil; rock, utilities and pavement cores for a post are priced per post as a change",
      "Overhead sign structures and their engineering are priced separately",
      "Sheeting warranty follows the manufacturer (typically 10-12 years); the inventory log records every install",
    ],
  },
};
