// Smart Proposal procedures — Site & Landscape. See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  landscaping: {
    basis: "planting beds and lawn by square foot; plants each by container size; soil, mulch and stone by the cubic yard; edging by the foot",
    steps: [
      { item: "Utility locate (811 ticket) and flagging of irrigation lines, lighting wire and drain pipe before any digging; planting plan staked and paint-marked on the ground for the owner's walk-through", unit: "fixed" },
      { item: "Protect existing trees, hardscape, siding and the driveway: fencing at the drip line, plywood over pavers and mats under equipment traffic", unit: "fixed" },
      { item: "Remove existing lawn, overgrown shrubs, groundcover and weeds by sod cutter and hand, roots included; green waste hauled to a composting facility", unit: "sqft", when: "existing planting or turf is being replaced" },
      { item: "Rough grade the planting areas to drain away from the foundation (minimum 2% for the first 10 ft) with a skid steer and hand raking", unit: "sqft" },
      { item: "Soil amendment: till 2-3 in. of screened compost into the top 6-8 in. of the beds and lawn areas, or import screened topsoil where the native soil is unworkable", unit: "cu yards" },
      { item: "Steel or aluminum bed edging, 4 in. tall, pinned in place with stakes every 30 in., or a spade-cut natural edge along the bed lines", unit: "linear ft" },
      { item: "Trees supplied and planted: caliper or container size stated, root flare set at grade, pit dug two to three times the root ball, backfilled with native soil, water basin formed, staked and guyed for the first season", unit: "unit" },
      { item: "Shrubs supplied and planted by container size (1, 3, 5 or 15 gal) as scheduled on the plan, spaced for mature size, with a slow-release starter fertilizer", unit: "unit" },
      { item: "Perennials, ornamental grasses and groundcover supplied and planted from 1 gal or 4 in. pots at the plan spacing, bed watered in the day of planting", unit: "unit" },
      { item: "Weed barrier fabric under stone or bark areas only (not under planted beds), overlapped 6 in. and pinned", unit: "sqft", when: "decorative stone or a bark-only area is specified" },
      { item: "Mulch: 3 in. of shredded hardwood or bark supplied and spread in every bed, pulled back from trunks and stems, or decorative stone at the stated size and depth", unit: "cu yards" },
      { item: "Lawn: finish-grade, rake and roll the soil, then sod laid in staggered rows with tight seams and rolled, or hydroseed or drill-seed at the stated blend with straw or paper mulch cover", unit: "sqft" },
      { item: "Irrigation coordination: drip lines and emitters run to every new tree and shrub, spray heads adjusted to the new lawn line, controller schedule set for establishment watering", unit: "unit", when: "the property has an irrigation system or one is being installed" },
      { item: "Boulders or landscape accent stone placed by mini-excavator, buried one-third for a natural set", unit: "unit", when: "boulders or accent stone are on the plan" },
      { item: "Low-voltage landscape lighting: transformer, wire, path and uplight fixtures placed and aimed at night", unit: "unit", when: "landscape lighting is included" },
      { item: "Initial watering-in of all plantings and sod, a written establishment watering schedule and a walk-through with the owner", unit: "fixed" },
      { item: "Final cleanup: hardscape blown and washed, excess soil and green waste hauled off, pots and stakes removed, protection taken down", unit: "fixed" },
      { item: "Establishment maintenance: weekly visits for the first 30-90 days covering watering checks, weeding, mowing the new lawn and replacing plants that fail under the warranty", unit: "fixed", when: "a maintenance or establishment period is included" },
    ],
    avoid: [
      "a bare 'Plants' or 'Landscaping' line with no species, size or count",
      "'Soil' or 'Mulch' with no depth, material or yardage",
      "lumping sod, beds and plantings into one lump sum",
      "a paver patio, retaining wall or drainage system inside the planting proposal — hardscape is priced separately",
      "'labor' lines separate from the planted item — the plant line includes the planting",
    ],
    notes: [
      "Plant sizes are container or caliper sizes at planting; the schedule names species, size and count and substitutions follow nursery availability",
      "Plant warranty is one year on trees and shrubs when the owner follows the watering schedule; sod, seed, perennials and annuals are not warranted",
      "Bed and lawn areas are measured from the plan or on site; rock, buried debris or contaminated soil found during excavation is priced as a change",
      "Existing irrigation is assumed to be working; repairs to it beyond head adjustment are priced separately",
    ],
  },
  hardscape: {
    basis: "paver and wall areas by square foot; retaining walls by face square foot with height stated; base and backfill by the cubic yard; edging and drains by the foot",
    steps: [
      { item: "Layout and grade shots: string lines and stakes set from the plan, finished elevations shot with a laser to confirm slope away from the house (1/8 to 1/4 in. per ft) and step rises", unit: "fixed" },
      { item: "Utility locate (811) and marking of irrigation, lighting and drain lines; lawn, driveway and neighboring surfaces protected with plywood and mats", unit: "fixed" },
      { item: "Demolition and haul-away of the existing concrete, pavers, deck or lawn in the footprint, broken up by skid steer and jackhammer and hauled to a recycler", unit: "sqft", when: "an existing surface occupies the footprint" },
      { item: "Excavation of the footprint to the full base depth (typically 7-9 in. for patios, 12 in. or more for driveways) plus 6 in. beyond the edges, spoils stockpiled or hauled off", unit: "cu yards" },
      { item: "Subgrade compacted with a plate compactor and non-woven geotextile separation fabric laid over the soil, overlapped 12 in.", unit: "sqft" },
      { item: "Crushed aggregate base (3/4-minus with fines) supplied, placed and compacted in 3-4 in. lifts to the stated total depth, screeded to the finished slope", unit: "cu yards" },
      { item: "Retaining wall: leveling pad of compacted 3/4 crushed stone, segmental block courses set level and glued, 4 in. perforated drain pipe behind the base course, 12 in. of clean drainage stone backfill wrapped in fabric, geogrid at the layers the height requires", unit: "sqft", when: "a retaining wall over 12 in. is in the design" },
      { item: "Seat wall, pillar or step block units set on the base and glued with a masonry adhesive, wall caps cut and adhered", unit: "linear ft", when: "seat walls, pillars or steps are in the design" },
      { item: "Bedding layer: 1 in. of concrete sand or 1/4 in. chip screeded over the base", unit: "sqft" },
      { item: "Pavers supplied and laid in the stated pattern and color (manufacturer, style and thickness stated), soldier-course border, cuts made with a wet saw", unit: "sqft" },
      { item: "Edge restraint: rigid PVC or aluminum paver edging spiked every 8-12 in. along every unsupported edge, or a concrete toe", unit: "linear ft" },
      { item: "Polymeric sand swept into the joints, plate-compacted through a pad, misted and set", unit: "sqft" },
      { item: "Surface drainage: channel drain, catch basin and solid 4 in. PVC pipe run to daylight, a dry well or the storm connection", unit: "linear ft", when: "runoff cannot leave the surface by slope alone" },
      { item: "Conduit sleeves under the pavers for future lighting, gas or irrigation lines", unit: "unit", when: "lighting, a gas line or irrigation crosses the footprint" },
      { item: "Fire pit, outdoor kitchen base or built-in grill enclosure built from wall block or CMU with the cap and vent stated", unit: "unit", when: "a fire feature or kitchen base is in the design" },
      { item: "Low-voltage lighting in the wall caps, step risers and along the path, transformer and wire included", unit: "unit", when: "hardscape lighting is included" },
      { item: "Backfill and restoration of the lawn and beds disturbed at the edges with topsoil and sod or seed", unit: "sqft" },
      { item: "Final cleanup: surface washed, excess base and spoils hauled off, equipment removed, walk-through and the manufacturer's paver warranty registered", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Pavers' or 'Patio' line with no product, pattern or base depth",
      "'Base' with no material, depth or compaction stated",
      "pricing the wall and the patio as one lump sum",
      "'Excavation' with no depth or yardage",
      "a paver sealer line the client did not ask for, listed as if it were required",
    ],
    notes: [
      "Base depth is set for the use: 6-8 in. under patios and walks, 10-12 in. under driveways, deeper in frost-prone or clay soils",
      "Walls over 4 ft, walls carrying a surcharge or walls needing a permit require an engineered design priced separately",
      "Quantities are taken from the plan; rock, unsuitable soil or buried debris is priced as a change",
      "Paver color and texture vary by production lot; the sample approved by the owner is the reference",
    ],
  },
  "irrigation-contractor": {
    basis: "zones each, heads and drip emitters each, pipe and wire by the foot; controller, backflow and valves each",
    steps: [
      { item: "Site walk and water test: static and working pressure measured at the hose bib or meter, flow available in gallons per minute, soil type noted and the property sketched into a zone map by plant type and sun exposure", unit: "fixed" },
      { item: "Utility locate (811) and marking of gas, electric, phone and cable before trenching; lawn and beds photographed for restoration", unit: "fixed" },
      { item: "Permit and backflow registration with the water purveyor, and the inspection scheduled", unit: "fixed" },
      { item: "Point of connection: tee into the main after the meter or off the house supply with a brass ball valve and a Schedule 80 PVC riser", unit: "unit" },
      { item: "Backflow preventer supplied and installed at the stated type (pressure vacuum breaker or reduced-pressure assembly per the local code), with unions, a stainless enclosure and initial certification test", unit: "unit" },
      { item: "Trenching with a vibratory plow or trencher to 12 in. for laterals and 18 in. for the mainline, lawn seams closed behind the plow", unit: "linear ft" },
      { item: "Mainline: Schedule 40 PVC or 1 in. HDPE poly pipe from the backflow to each valve manifold, solvent-welded or barbed-and-clamped", unit: "linear ft" },
      { item: "Zone valves in a valve box: 1 in. electric solenoid valves with flow control, manifold assembly, gravel sump and a box lid at grade", unit: "unit" },
      { item: "Lateral lines: Class 200 PVC or poly pipe from each valve to the heads, sized so the zone runs within the available flow", unit: "linear ft" },
      { item: "Spray and rotor heads: 4 in. or 6 in. pop-up bodies on swing joints, matched-precipitation nozzles set head-to-head for the lawn areas", unit: "unit" },
      { item: "Drip zones for beds and trees: pressure regulator and filter at the valve, 1/2 in. drip tubing, inline emitter tubing or point emitters at every plant, ending in flush caps", unit: "unit" },
      { item: "Wire: multi-strand direct-burial valve wire in the mainline trench, waterproof connectors at every valve", unit: "linear ft" },
      { item: "Controller: weather-based smart controller (WaterSense listed) mounted and wired, or the owner's existing controller connected, with a wireless rain or soil-moisture sensor", unit: "unit" },
      { item: "Master valve and flow sensor at the point of connection so the controller shuts the system down on a break", unit: "unit", when: "a master valve or flow monitoring is specified" },
      { item: "Sleeving under walks and driveways: Schedule 40 PVC sleeves bored or trenched across the pavement", unit: "linear ft", when: "pipe or wire crosses a walk or driveway" },
      { item: "Flush every line before heads go on, pressure-test the mainline, adjust every head's arc and radius, program run times by zone and teach the owner the controller", unit: "fixed" },
      { item: "Trench restoration: settle and tamp the seams, topsoil where needed, sod or seed patches where the plow lifted the lawn", unit: "fixed" },
      { item: "As-built zone map with valve locations left with the owner, plus the first-season winterization or spring startup", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Sprinkler system' or 'Irrigation' lump line with no zone, head or valve count",
      "'Pipe' with no size, class or footage",
      "heads listed without the body height, type or nozzle",
      "a backflow line with no assembly type — the code decides the type and the client should see it",
      "planting, sod or lawn repair beyond the trench line — that is landscape work",
    ],
    notes: [
      "Zone count is set by the available flow measured at the site; a low-flow supply means more zones, not fewer heads",
      "Backflow type follows the water purveyor's requirement; the annual certification after the first is the owner's",
      "Pipe and wire footages are taken from the zone map; boring under pavement is priced per foot when it is needed",
      "Coverage is designed head-to-head for the lawn; plantings later added by others are not covered by the design",
    ],
  },
  "asphalt-paving": {
    basis: "paved area by square foot for driveways and by square yard for lots, at a stated compacted depth with the hot-mix tonnage named; base by the cubic yard; edging and striping by the foot",
    steps: [
      { item: "Site measure and grade check: area shot with a wheel and laser, drainage direction confirmed to the street or a catch basin, soft spots probed and marked", unit: "fixed" },
      { item: "Utility locate (811) and marking of gas, water and sprinkler lines in the paving footprint; garage, walks and lawn edges protected", unit: "fixed" },
      { item: "Traffic control and phasing: cones, barricades and signs so the lot stays partly open, or the driveway blocked for the cure period", unit: "fixed", when: "the lot must stay in use or the drive fronts a street" },
      { item: "Remove the existing asphalt or concrete to full depth with a skid steer and breaker, loaded and hauled to an asphalt recycler (thickness stated)", unit: "sqft", when: "an existing pavement is being replaced" },
      { item: "Milling the existing asphalt surface at the stated depth with millings hauled off or left for the owner", unit: "sqft", when: "the job is an overlay rather than full-depth replacement" },
      { item: "Subgrade preparation: cut or fill to the design grade, proof-roll with a loaded truck, and undercut and replace soft areas with crushed stone", unit: "sqft" },
      { item: "Aggregate base: 3/4-minus crushed stone supplied, spread and compacted in lifts to the stated depth (typically 6-8 in. for driveways, 8-12 in. for lots; tonnage named)", unit: "cu yards" },
      { item: "Fine grading and compaction of the base to a smooth, tight surface at the finished slope, with a vibratory roller", unit: "sqft" },
      { item: "Tack coat: SS-1h emulsion sprayed on the milled or existing surface and against every joint, curb and gutter edge before paving", unit: "sqft", when: "paving over an existing surface or against existing pavement" },
      { item: "Binder (base) course: hot-mix asphalt at the stated compacted depth (typically 2-2.5 in.), machine-laid with a paver and the tonnage named", unit: "sqft", when: "a two-lift section is specified" },
      { item: "Surface course: hot-mix asphalt at the stated compacted depth (typically 1.5-2 in.) with the mix type and tonnage named, laid by paver at 275-300 deg F", unit: "sqft" },
      { item: "Compaction: steel-drum breakdown and finish rolling plus a rubber-tire roller on lots, hand-tamped at edges and around structures", unit: "sqft" },
      { item: "Edging: 45-degree cut and tamped asphalt edge, or a hand-laid asphalt curb along the drive", unit: "linear ft" },
      { item: "Transitions: saw-cut butt joints at the street, garage apron and walks, matched to the existing elevation", unit: "linear ft" },
      { item: "Manholes, valve boxes and catch-basin frames raised to the new grade with riser rings", unit: "unit", when: "structures sit inside the paved area" },
      { item: "Striping: stalls, ADA spaces, arrows and stop bars in traffic paint after the surface cures", unit: "linear ft", when: "the lot is striped" },
      { item: "Sealcoat option: two coats of asphalt-emulsion sealer applied after the new asphalt cures 90 days or more", unit: "sqft", when: "the owner elects a sealcoat" },
      { item: "Cleanup, backfill of the edges with topsoil, seed where the lawn was disturbed, and the cure and use instructions left with the owner", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Asphalt' or 'Paving' line with no depth, tonnage or area",
      "'Base' with no depth, material or compaction",
      "pricing base, binder and surface as one lump line",
      "sealcoat listed as part of the paving price — it is a separate, later service",
      "'Mobilization' with no equipment named",
    ],
    notes: [
      "Depths are compacted depths; hot-mix tonnage is named per lift from the area and depth at the mix's density",
      "The base is priced on the existing subgrade proving firm at proof-roll; undercut and stone for soft areas is priced per yard as a change",
      "New asphalt is kept clear of vehicles for 3-5 days and of turning wheels for two weeks; sealcoat waits 90 days or more",
      "Drainage follows the existing grade unless a regrade is priced; standing water in a low spot the design cannot drain is excluded",
    ],
  },
  "pool-spa": {
    basis: "pool by perimeter and surface area; excavation by the cubic yard; shell, tile, coping and plaster by the foot or square foot; equipment each",
    steps: [
      { item: "Layout and permits: pool outlined on the ground from the engineered plan, setbacks and utility easements checked, building, electrical, plumbing and barrier permits pulled and the HOA approval filed", unit: "fixed" },
      { item: "Utility locate (811), access route protection with plywood and mats, temporary fence, and a soils report or bore where the jurisdiction requires it", unit: "fixed" },
      { item: "Excavation of the pool shape and depths with an excavator, over-dig for the shell and plumbing, spoils hauled off or spread on site", unit: "cu yards" },
      { item: "Steel: #3 and #4 rebar grid at the engineered spacing (typically 12 in. o.c. walls, 6 in. o.c. in beams and steps) tied and held off the soil on dobies", unit: "sqft" },
      { item: "Plumbing loops: Schedule 40 PVC suction, return and skimmer lines, main drains with VGB-compliant covers, spa jets and air lines, pressure-tested and held under pressure through the shell work", unit: "linear ft" },
      { item: "Electrical rough and bonding: #8 bare copper bonding grid tied to the steel, conduit for lights and the equipment feed, panel or subpanel per NEC 680", unit: "fixed" },
      { item: "Shotcrete or gunite shell shot to the engineered thickness (typically 6 in. floors, 8 in. walls, 12 in. beam), troweled to shape and water-cured 7 days", unit: "sqft" },
      { item: "Equipment pad and equipment set: variable-speed pump, cartridge or DE filter, gas or heat-pump heater, salt chlorine generator and automation panel, plumbed on a concrete pad", unit: "unit" },
      { item: "Waterline tile: 6 in. glass or porcelain tile set in thinset over the beam, grouted, with the spa spillway and step markers tiled", unit: "linear ft" },
      { item: "Coping: precast, travertine or poured-in-place bullnose at the stated material, set on the beam with a mastic expansion joint at the deck", unit: "linear ft" },
      { item: "Deck: broom-finish concrete, pavers or travertine at the stated area with a 1/4 in. per ft slope away from the pool", unit: "sqft" },
      { item: "Backfill around the shell with the excavated soil in lifts and compacted; utility trenches to the equipment pad closed", unit: "cu yards" },
      { item: "Pool lights, water features, deck jets and the spa blower installed and wired", unit: "unit", when: "lighting, water features or a spa are in the design" },
      { item: "Plaster or pebble interior finish applied over the cured shell at the stated product and color, brushed and acid-washed as the product requires", unit: "sqft" },
      { item: "Safety barrier: 4 ft fence with self-closing, self-latching gates, door alarms or a safety cover to the pool barrier code", unit: "linear ft" },
      { item: "Fill and startup: water delivered or hose-filled, chemistry balanced daily during the 28-day plaster cure, pump and filter started, automation programmed", unit: "fixed" },
      { item: "Inspections at pre-gunite steel, bonding and rough plumbing, pre-plaster and final, with the barrier inspection signed off", unit: "fixed" },
      { item: "Pool school: owner walked through the equipment, chemistry and cleaning, manufacturer warranties registered, site cleaned and access route restored", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Pool' or 'Shell' line with no dimensions, shell thickness or finish",
      "'Equipment' with no pump, filter or heater named",
      "excavation with no yardage or with the haul-off hidden in it",
      "pricing tile, coping and plaster as one line",
      "the fence, deck or landscaping left out and the barrier requirement unmentioned",
    ],
    notes: [
      "The pool is built to the engineered drawing; rock, groundwater or caving soil found at excavation is priced as a change",
      "Utility fees, water for the fill and the gas line to the heater from the meter are priced when the site is confirmed or passed through",
      "Deck, fence and landscape restoration beyond the areas listed are separate work",
      "Plaster cure requires daily brushing and chemistry for 28 days; the owner or a startup service performs it after the first week",
    ],
  },
  "snow-removal": {
    basis: "plowed lots by square foot, walks by the linear foot, de-icing per application, loaders and hauling by the hour, per event or by the seasonal contract",
    steps: [
      { item: "Pre-season site walk and mapped plan: plow routes, snow stacking zones, priority areas (entrances, fire lanes, ADA stalls), curb and island hazards and the trigger depth and response time written up", unit: "fixed" },
      { item: "Marker stakes at curbs, islands, hydrants, drains and landscape edges before the first freeze, pulled in spring", unit: "unit" },
      { item: "Pre-treatment: liquid brine or salt applied to the lot and walks ahead of a forecast event so ice does not bond", unit: "sqft", when: "pre-treatment is in the service level" },
      { item: "Lot plowing at the stated trigger depth (typically 2 in.) with trucks or a loader with a pusher box, snow stacked in the mapped zones, per push", unit: "sqft" },
      { item: "Drive lanes, entrances and fire lanes plowed open on the priority pass and reopened during the event at the stated interval", unit: "sqft", when: "the site must stay open during the storm" },
      { item: "Sidewalks, entrances and steps cleared with a walk-behind blower and shovels, to the stated width and within the response time", unit: "linear ft" },
      { item: "Bulk rock salt applied to the lot and drive lanes with a spreader after plowing, per application", unit: "sqft" },
      { item: "Calcium chloride or a treated ice melt applied to walks, steps and entrances, per application", unit: "linear ft" },
      { item: "Loader relocation of stacked snow within the site when the stacking zones fill", unit: "hour", when: "stacking zones are limited" },
      { item: "Off-site hauling: snow loaded into dump trucks and hauled to an approved disposal site", unit: "hour", when: "the site has no room to stack snow" },
      { item: "Return visits for drifting and refreeze, and clearing behind the plow at drive-lane ends after the municipal plow passes", unit: "hour", when: "the contract covers drifting or refreeze calls" },
      { item: "Per-event service log: start and end times, depths, materials used and photos, delivered after every event", unit: "fixed" },
      { item: "Spring cleanup: salt residue swept, stakes pulled, turf and curb damage from plowing repaired", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Snow removal' seasonal price with no trigger depth, areas or response time stated",
      "'Salt' with no area or application count",
      "plowing and de-icing priced as one line — they are separate services and separate triggers",
      "hauling included in the plow price without an hourly or per-load rate",
      "lawn care or sweeping bundled into the snow contract",
    ],
    notes: [
      "Per-push, per-event or seasonal pricing is stated; seasonal contracts cap the number of events or inches before overage rates apply",
      "Areas are measured from the site map; response time runs from the trigger depth being reached, not from the start of snowfall",
      "De-icing material is applied at the stated rate per application; ice storms and refreeze cycles beyond the plan are billed per application",
      "The contractor is not responsible for slip-and-fall conditions outside the service windows or for ice under standing water",
    ],
  },
  "tree-removal": {
    basis: "trees each by trunk diameter (DBH) class, height and access; pruning per tree; stumps each; crane and chipper by the hour or as a fixed day",
    steps: [
      { item: "Arborist assessment: each tree tagged, species, DBH, height, lean, decay and target hazards noted, and the removal or pruning method chosen per tree", unit: "unit" },
      { item: "Tree removal permit or heritage-tree application with the city, and the notice to neighbors where a tree overhangs the line", unit: "fixed", when: "the jurisdiction regulates removal of the tree's size or species" },
      { item: "Utility clearance: 811 locate for the drop zone and the power company's line drop or de-energizing scheduled", unit: "fixed", when: "the tree is within 10 ft of power lines" },
      { item: "Site protection: plywood on the lawn and driveway under the drop zone, fencing and roof, gutter and neighbor's property shielded", unit: "fixed" },
      { item: "Traffic control on the street: cones, signs and a flagger while the crane, chipper or drop zone is in the road", unit: "fixed", when: "the work reaches into a public street or sidewalk" },
      { item: "Small tree removal (under 12 in. DBH): felled or dismantled from the ground and chipped on site", unit: "unit", when: "trees in the small class are on the list" },
      { item: "Medium tree removal (12-24 in. DBH): climbed and dismantled in sections with rigging, limbs lowered to the drop zone", unit: "unit", when: "trees in the medium class are on the list" },
      { item: "Large tree removal (over 24 in. DBH): climbed or bucket-truck dismantled with rigging blocks and a lowering line, trunk cut in rounds", unit: "unit", when: "trees in the large class are on the list" },
      { item: "Crane-assisted removal: sections picked over the house or a tight yard by a crane sized to the picks, with a certified operator and signal person", unit: "hour", when: "there is no drop zone or the tree is over a structure" },
      { item: "Pruning: crown cleaning, deadwood removal, raising or thinning per ANSI A300 with no topping, cuts made outside the branch collar", unit: "unit", when: "trees are being pruned rather than removed" },
      { item: "Brush and limbs chipped through a drum chipper and hauled off, or chips left on site at the owner's request", unit: "fixed" },
      { item: "Logs bucked to length and hauled to a recycler or mill, or cut to firewood length and stacked on site", unit: "fixed" },
      { item: "Stump grinding to 6-8 in. below grade with a self-propelled grinder, grindings raked into the hole", unit: "unit", when: "stumps are being ground" },
      { item: "Rake and blow the site, repair ruts in the lawn from the equipment, remove the protection", unit: "fixed" },
      { item: "Certificate of insurance for the owner, and the permit's replacement-tree condition met with a new tree planted", unit: "unit", when: "the permit requires a replacement tree" },
    ],
    avoid: [
      "a bare 'Tree removal' line with no diameter, height or method",
      "'Cleanup' or 'Haul' with no chipping or log disposal named",
      "the stump grinding folded into the removal price without saying so",
      "topping listed as pruning",
      "a crane line with no hours or day rate",
    ],
    notes: [
      "Trees are priced per tree by DBH class, height and what is under and around them; a tree that cannot be dropped whole costs more to dismantle",
      "Stumps are left flush unless grinding is listed; grindings stay in the hole unless removal and topsoil are listed",
      "Power-line clearance is scheduled with the utility and its cost is passed through; the utility trims its own high-voltage lines",
      "Hidden metal in the trunk, hollow trunks that change the rigging plan and hazardous trees that must be dismantled by crane are priced as a change",
    ],
  },
  "stump-grinding": {
    basis: "stumps each by diameter at ground level; surface roots by the foot; grindings and fill by the cubic yard; restoration by square foot",
    steps: [
      { item: "Stump count and measure: diameter taken at ground level with the flare, species and height above grade noted, and access route confirmed for the grinder width", unit: "fixed" },
      { item: "Utility locate (811) and a private locate for irrigation, lighting and drain lines around each stump before grinding", unit: "fixed" },
      { item: "Access protection: plywood or mats over the lawn, walk and driveway on the grinder's route; fence panel removed and reset", unit: "fixed", when: "the route crosses a lawn, walk or a fenced gate" },
      { item: "Cut the stump flush to the ground with a chainsaw where it stands above 6 in.", unit: "unit", when: "stumps stand above grade" },
      { item: "Grinding of stumps up to 12 in. across, to 6-8 in. below grade with a self-propelled grinder", unit: "unit", when: "small stumps are on the list" },
      { item: "Grinding of stumps 12-24 in. across, to 8-12 in. below grade with a track grinder", unit: "unit", when: "medium stumps are on the list" },
      { item: "Grinding of stumps over 24 in. across, to 12 in. or more below grade, in passes with the grinder repositioned around the flare", unit: "unit", when: "large stumps are on the list" },
      { item: "Surface roots chased and ground beyond the stump to the stated distance for a replanting or a lawn", unit: "linear ft", when: "roots must be removed for planting, paving or lawn" },
      { item: "Grindings raked back into the hole and mounded to settle, or loaded and hauled off", unit: "cu yards" },
      { item: "Screened topsoil supplied and placed in the hole after the grindings are removed, tamped and graded to match the lawn", unit: "cu yards", when: "the hole is being filled for lawn or planting" },
      { item: "Seed and straw or a sod patch over the filled hole, watered in", unit: "sqft", when: "restoration to lawn is included" },
      { item: "Site raked and blown, rut repair on the access route and the protection removed", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Stump removal' line with no diameter or depth",
      "the grindings haul-off hidden in the grinding price",
      "tree felling or limbing on a stump-grinding proposal — the tree must be down and flush first",
      "'labor' or 'equipment' lines separate from the per-stump price",
    ],
    notes: [
      "Stumps are priced per stump by diameter at ground level including the flare; grinding depth is stated per size class",
      "Grindings are left in the hole unless removal and fill are listed; a mounded hole settles over a season",
      "Rocks, buried concrete, metal or an unmarked line found in the stump change the method and are priced as a change",
      "The grinder needs a 36 in. clear path; hand-carried grinding where it cannot pass is priced per stump as a change",
    ],
  },
  "erosion-control": {
    basis: "silt fence, wattles and diversion by the linear foot; blankets and seeding by square yard or square foot; inlet protection and entrances each; inspections and SWPPP by fixed or hour",
    steps: [
      { item: "SWPPP or erosion and sediment control plan review: BMP locations confirmed on site, disturbed area and discharge points walked, and the NOI or grading-permit conditions noted", unit: "fixed" },
      { item: "Stabilized construction entrance: geotextile under 6 in. of 2-3 in. clean crushed rock, 50 ft long by the drive width, with a rumble plate or wash rack where the permit requires", unit: "unit" },
      { item: "Silt fence: woven geotextile fabric trenched 6 in. into the ground, backfilled and compacted, wire-backed on steel posts at 6 ft or hardwood stakes at 4 ft, ends turned uphill", unit: "linear ft" },
      { item: "Fiber wattles or compost socks (9-12 in.) staked on contour at the slope toe and on the face at the stated spacing, ends overlapped", unit: "linear ft" },
      { item: "Storm-drain inlet protection: gravel bags, a filter sack or a stone-and-fabric barrier at every downstream inlet", unit: "unit" },
      { item: "Diversion berm or swale cut and shaped above the work area to carry clean runoff around the disturbance", unit: "linear ft", when: "run-on from above the site must be diverted" },
      { item: "Sediment trap or basin excavated to the plan volume with a rock outfall and dewatering skimmer", unit: "cu yards", when: "the disturbed area drains to one low point" },
      { item: "Rock check dams in the swales: 3-6 in. stone, 2 ft high, keyed into the banks", unit: "unit", when: "channels or swales carry flow through the site" },
      { item: "Erosion control blanket (straw, straw-coconut or turf reinforcement mat) stapled on the slopes over seed, edges trenched in at the top", unit: "sq yards", when: "slopes steeper than 3:1 or channels are being stabilized" },
      { item: "Temporary seeding and straw mulch, or hydroseed with tackifier, over the disturbed area at the stated seed mix and rate", unit: "sqft" },
      { item: "Concrete washout: lined pit or a portable container with signage, pumped and disposed of when full", unit: "unit", when: "concrete is poured on the project" },
      { item: "Dust control: water truck passes on the haul roads and exposed soil", unit: "hour", when: "the permit or dry weather requires it" },
      { item: "Weekly and post-storm inspections with a written report, corrections logged and the SWPPP binder kept current", unit: "hour" },
      { item: "Maintenance: sediment removed from behind the fence and out of the traps when it reaches half the height, damaged sections replaced, entrance rock topped up", unit: "hour" },
      { item: "Final stabilization and removal: permanent seed or sod established at 70% cover, BMPs pulled, fence trench filled and the NOT filed", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Erosion control' or 'BMPs' lump line with no fence footage, inlet count or blanket area",
      "'Silt fence' with no fabric, post or trenching stated",
      "inspection and maintenance folded into the installation price with no visit count or rate",
      "mass grading or the storm sewer itself — that is the earthwork contractor's line",
    ],
    notes: [
      "Quantities follow the approved erosion and sediment control plan; BMPs added by the inspector are priced per the unit rates",
      "Inspection frequency follows the permit (typically weekly and within 24 hours of a half-inch rain); reports are kept in the SWPPP binder on site",
      "Sediment removal and fence replacement are maintenance billed at the hourly rate unless a fixed maintenance term is listed",
      "Final stabilization is judged by the inspector's cover requirement; reseeding a failed area is priced as a change",
    ],
  },
};
