// Smart Proposal procedures — Specialty surface & decor. See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  "epoxy-flooring": {
    basis: "square feet of floor by coating system and mil build; cracks, joints, cove base and stem walls by the linear foot; slab repairs by the area repaired",
    steps: [
      { item: "Moisture testing before the system is ordered: in-situ relative-humidity probes (ASTM F2170) or calcium-chloride tests (ASTM F1869) at the stated number of points, readings recorded on the proposal", unit: "fixed", when: "the brief asks for a moisture test or names a new, damp or below-grade slab" },
      { item: "Mobilization and protection: planetary grinder, HEPA dust extractor, mixing station and generator brought in; walls, door frames, floor drains, equipment legs and adjacent finishes masked to the coating line", unit: "fixed" },
      { item: "Removal of the existing coating, sealer or adhesive residue with PCD tooling before profiling, spent material bagged for disposal", unit: "sqft", when: "the slab carries an old coating, sealer or adhesive" },
      { item: "Diamond grinding (or shot blasting on large open floors) to a CSP 2-3 profile under HEPA extraction, edges and columns hand-ground to the wall, floor vacuumed and wiped clean", unit: "sqft" },
      { item: "Crack and control-joint repair: cracks chased with a crack-chasing blade, joints cleaned out, both filled with a two-part polyurea or epoxy joint filler and ground flush", unit: "linear ft" },
      { item: "Spall, pit and pop-out repair with a 100% solids epoxy mortar, troweled and ground flush before the primer goes down", unit: "sqft", when: "the slab surface is pitted, spalled or gouged" },
      { item: "Moisture-mitigating epoxy primer at 16 mils (rated to 100% RH or 20 lb MVER) in place of the standard primer", unit: "sqft", when: "readings exceed 75% RH or 3 lb MVER, or the slab has no vapor retarder" },
      { item: "Epoxy primer: low-viscosity 100% solids epoxy rolled into the profile at 4-6 mils to seal the slab and anchor the base coat", unit: "sqft" },
      { item: "Base coat: 100% solids pigmented epoxy at 10-12 mils, squeegee-applied and back-rolled, color per the selected blend", unit: "sqft" },
      { item: "Full flake broadcast: 1/4 in. vinyl flake blend broadcast to rejection into the wet base coat, then scraped, sanded and vacuumed to a uniform texture after cure", unit: "sqft", when: "the system is a flake broadcast" },
      { item: "Quartz double broadcast: colored quartz aggregate broadcast to rejection into two consecutive 100% solids epoxy body coats, scraped and vacuumed between coats", unit: "sqft", when: "the system is decorative quartz" },
      { item: "Metallic epoxy body coat: 100% solids clear epoxy with metallic pigment at 20-25 mils, manipulated for the effect and left to self-level", unit: "sqft", when: "the system is metallic epoxy" },
      { item: "Grout coat: clear 100% solids epoxy at 8-10 mils to lock the broadcast and fill the texture to the specified smoothness", unit: "sqft", when: "the broadcast system calls for a smooth or orange-peel finish" },
      { item: "Top coat: clear aliphatic polyaspartic at 8-10 mils, or two-component aliphatic urethane at 3-4 mils, UV-stable and chemical-resistant, roller-applied with slip-resistant aggregate broadcast into the wet coat where specified", unit: "sqft" },
      { item: "Cove base: 4-6 in. epoxy cove troweled at the wall-to-floor junction with a 1 in. radius, then coated in the same system as the floor", unit: "linear ft", when: "the brief calls for cove base or the room is washed down" },
      { item: "Stem walls, curbs and equipment pads coated 4-8 in. high in the floor system with a masked, straight cut line", unit: "linear ft", when: "exposed stem walls, curbs or pads adjoin the floor" },
      { item: "Line striping and safety markings: pigmented polyaspartic stripes 4 in. wide masked and applied over the finished floor", unit: "linear ft", when: "the floor needs aisle, bay or safety striping" },
      { item: "Cure and return to service: foot traffic and rolling loads allowed at the stated hours for the top coat, masking removed, final inspection under raking light with any holidays or debris inclusions corrected", unit: "fixed" },
      { item: "Final cleanup: grinding dust, spent flake and empty containers hauled off, floor wiped, and the care sheet and warranty documents handed over", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Floor prep' or 'Epoxy' line — name the profile, the coat and its mil thickness",
      "pricing the primer, base coat, broadcast and top coat as one 'coating system' line",
      "'Materials' or 'labor' lines separate from the coats they belong to",
      "concrete slab replacement or leveling — a concrete contractor's work, priced as a change",
      "a top coat with no product family or mil thickness stated",
    ],
    notes: [
      "Floor area is the net coated area from the brief or a field measure; stem walls, cove and stripes are measured by the foot",
      "The slab is assumed sound, cured at least 28 days and free of a vapor problem until the moisture test says otherwise; mitigation is a change order",
      "Coat thicknesses are wet-film targets from the manufacturer's data sheet; colors and flake blends come from the sample board the client signs",
      "Return-to-service times assume a 60-85 F slab and the stated ventilation; vehicles and heavy equipment wait for the full cure",
      "Slab replacement, leveling and floor drains are excluded",
    ],
  },
  "concrete-resurfacing": {
    basis: "square feet of floor by grind level, gloss and decorative system; joints, cracks and scored lines by the linear foot; sealers and dyes by the area covered",
    steps: [
      { item: "Test area and mock-up: a 4 x 4 ft panel ground and finished to the proposed exposure, color and gloss for the client to approve before production", unit: "fixed" },
      { item: "Protection and setup: walls, cabinets, door frames and drains masked, dust walls hung at open doorways, propane or electric planetary grinder and auto-scrubber brought in", unit: "fixed" },
      { item: "Removal of carpet, tile, vinyl or mastic and any old coating with PCD and carbide tooling, residue vacuumed and hauled off", unit: "sqft", when: "the slab is covered by flooring, adhesive or a coating" },
      { item: "Crack chasing and control-joint filling with a semi-rigid polyurea joint filler, shaved flush after cure so the joints polish with the floor", unit: "linear ft" },
      { item: "Spall, pit and pop-out patching with a polishable cementitious repair mortar color-matched to the slab", unit: "sqft", when: "the surface has spalls, pits or lifted aggregate" },
      { item: "Metal-bond grinding in stages (30/40, then 80, then 150 grit) to the specified aggregate exposure: cream, salt-and-pepper, medium or large aggregate", unit: "sqft" },
      { item: "Lithium-silicate densifier flooded onto the slab and worked in to harden and dust-proof the surface before honing", unit: "sqft", when: "the finish is polished concrete" },
      { item: "Resin-bond honing at 100, 200 and 400 grit to close the surface and remove the grinding scratch pattern", unit: "sqft", when: "the finish is polished concrete" },
      { item: "Concrete dye (water- or acetone-based) or reactive acid stain in the selected color applied between honing steps, acid stain neutralized and rinsed", unit: "sqft", when: "the finish calls for integral color" },
      { item: "Polishing at 800, 1,500 and 3,000 grit to the specified gloss level (Level 1 flat through Level 4 high gloss)", unit: "sqft", when: "the finish is polished concrete" },
      { item: "Polymer-modified cementitious overlay: microtopping at 1/16 in., stamped overlay at 1/4-3/8 in. or self-leveling at 1/4-1/2 in., primed, poured or troweled and cured", unit: "sqft", when: "the finish is an overlay rather than the bare slab" },
      { item: "Stamped or hand-troweled texture in the overlay with release agent and the selected pattern mats", unit: "sqft", when: "the overlay is stamped or textured" },
      { item: "Decorative saw-cut scoring in the selected layout (tile, diamond or border pattern) with a 1/8 in. blade, edges eased", unit: "linear ft", when: "the design shows scored lines" },
      { item: "Sealer or stain guard: penetrating stain protector burnished into polished concrete, or acrylic, urethane or epoxy sealer at the stated coats over overlays and stains, slip-resistant additive where specified", unit: "sqft" },
      { item: "High-speed burnishing with a diamond-impregnated pad to bring up the final sheen and set the guard", unit: "sqft", when: "the finish is polished concrete" },
      { item: "Slurry management: grinding slurry collected, solidified and disposed of at a licensed facility; floor auto-scrubbed between steps", unit: "fixed" },
      { item: "Final cleanup, masking removed, walkthrough with gloss and exposure checked against the approved mock-up, and a written care sheet with the recommended cleaner and re-burnish schedule", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Grinding' or 'Polish' line with no grit sequence, exposure or gloss level",
      "'Sealer' with no product type, coat count or slip rating",
      "pricing grinding, densifying, honing and polishing as one 'polished concrete' line",
      "new slab pours, self-leveling underlayment for other flooring or floor drains — another trade's work",
      "'Cleanup' with no mention of slurry disposal",
    ],
    notes: [
      "Floor area is measured wall to wall less fixed obstructions; grinding exposure follows the approved mock-up, and the slab's aggregate and color are what they are",
      "Existing cracks and joints are filled and remain visible in a polished floor; overlays hide them until the slab moves",
      "Acid stain and dye color varies with the slab's chemistry; the mock-up is the color reference, not a chart",
      "Slab replacement, leveling of more than 1/4 in. and moisture mitigation are excluded",
    ],
  },
  "wallcovering": {
    basis: "square feet of wall hung by covering type; material by the roll, bolt or panel; cut-outs, borders and specialty panels each",
    steps: [
      { item: "Field measure and takeoff: each wall measured, openings deducted, pattern repeat and match type read from the roll label, roll or bolt count with a 10-15% waste allowance and one dye lot confirmed", unit: "fixed" },
      { item: "Wallcovering material supplied in the client's selection: single or double rolls of paper or non-woven, 54 in. Type II commercial vinyl by the bolt, or printed mural panels, all from one dye lot", unit: "unit" },
      { item: "Room protection: furniture moved and covered, floors and baseboards masked, switch and outlet covers removed and bagged, ladders and drops set", unit: "fixed" },
      { item: "Stripping existing wallcovering: face layer scored and peeled, backing softened with steam or enzyme stripper and removed, old paste washed off and the wall rinsed", unit: "sqft", when: "the walls carry old wallcovering" },
      { item: "Wall repair: nail holes, dents and seams filled, damaged paper face sealed, textured walls skim-coated with joint compound and sanded to a Level 5 finish", unit: "sqft", when: "the walls are textured, damaged or freshly patched" },
      { item: "Priming with a pigmented acrylic wallcovering primer-sealer so the covering adheres evenly and strips cleanly later", unit: "sqft" },
      { item: "Layout: plumb line snapped at the starting corner, pattern centered on the focal wall, drop or straight match plotted so the kill seam lands in the least visible corner", unit: "fixed" },
      { item: "Hanging: strips cut with the pattern matched, pasted or pre-pasted per the product (clay, clear strippable or heavy-duty vinyl adhesive), booked, hung, smoothed, seams butted and rolled, trimmed at ceiling and base", unit: "sqft" },
      { item: "Commercial vinyl: 54 in. Type II strips hung with heavy-duty clay adhesive, seams double-cut and rolled, corners wrapped 6 in. and overlapped", unit: "sqft", when: "the covering is commercial vinyl" },
      { item: "Mural or panel installation: numbered panels dry-fitted to the wall, hung in sequence with the image aligned across seams and trimmed to the opening", unit: "unit", when: "the covering is a mural or paneled graphic" },
      { item: "Grasscloth, silk or textured natural covering: strips reverse-hung where the product calls for it, paste kept off the face, seams left visible as the material intends", unit: "sqft", when: "the covering is a natural or textured material" },
      { item: "Cut-outs at outlets, switches, sconces, thermostats and vents, covering trimmed tight and cover plates reinstalled", unit: "unit" },
      { item: "Borders and chair-rail bands hung level at the stated height with mitered corners", unit: "linear ft", when: "the design includes a border" },
      { item: "Ceiling installation with a second installer and platform, strips hung across the short dimension", unit: "sqft", when: "the ceiling is papered" },
      { item: "Scaffold or platform for stairwells and walls over 10 ft, set and moved as the work advances", unit: "fixed", when: "the walls are in a stairwell or over 10 ft high" },
      { item: "Seam and surface inspection under raking light after the paste dries, lifted edges re-pasted and paste residue wiped from trim and ceilings", unit: "fixed" },
      { item: "Cleanup: masking removed, stripped paper and trimmings bagged and hauled, leftover rolls labeled with the dye lot and left for the owner", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Wallpaper install' line priced by the room with no wall area or roll count",
      "'Prep' with no priming, stripping or skim coat named",
      "pricing material and hanging as one line when the client supplies the paper",
      "painting the trim or ceiling — a painter's line",
      "'Extra rolls' or 'waste' as their own lines — waste lives in the roll count",
    ],
    notes: [
      "Wall area is measured wall by wall with openings over 20 sqft deducted; rolls are ordered by the repeat, not the area alone",
      "Walls are assumed sound, primed and free of texture unless the brief says otherwise; skim coating and stripping are priced when found",
      "Client-supplied material is checked for dye lot and run on delivery; short or mismatched lots are not the installer's warranty",
      "Pattern match and seam placement follow the layout the client approves at the plumb-line stage",
    ],
  },
  "glass-glazing": {
    basis: "lites of glass each by size, thickness and make-up; glazing perimeter and sealant by the linear foot; film by the square foot; access and board-up stated",
    steps: [
      { item: "Site survey and field measurement of every opening: daylight opening and glass size, thickness, edge bite, setting-block positions, frame condition and the existing glazing method (stops, gaskets, tape or wet seal)", unit: "fixed" },
      { item: "Temporary board-up or plywood closure of broken openings, glass swept and bagged for disposal", unit: "unit", when: "an opening is broken or open to weather" },
      { item: "Shop drawings and submittals: glazing details, glass make-up, hardware and finish samples for approval before fabrication", unit: "fixed", when: "the project is commercial or has an architect" },
      { item: "Insulated glass units fabricated to size: 1 in. overall with 1/4 in. low-E over 1/4 in. clear, argon fill and a warm-edge spacer, tempered or laminated where safety glazing is required (CPSC 16 CFR 1201 Cat II)", unit: "unit" },
      { item: "Monolithic glass fabricated to size: 1/4 in. to 1/2 in. tempered, laminated or annealed, edges seamed or polished as the frame requires", unit: "unit", when: "an opening takes single glazing" },
      { item: "Removal of the failed unit or broken glass: sealant cut, stops or pressure plates pulled, glass lifted out with cups, old glazing tape and gaskets stripped from the rabbet", unit: "unit", when: "an existing lite is being replaced" },
      { item: "Frame preparation: rabbet cleaned and dried, weep holes cleared, new setting and edge blocks placed, glazing tape or wet-glaze bead laid to the frame type", unit: "linear ft" },
      { item: "Glass set: lite lifted and set on the blocks, stops or gaskets reinstalled, pressure plates torqued or wet cap bead applied to the full perimeter", unit: "unit" },
      { item: "Perimeter weather seal: backer rod and structural or weatherseal silicone (ASTM C920 Class 50) at the frame-to-substrate joint inside and out, tooled and color-matched", unit: "linear ft" },
      { item: "Interior glass partitions and office fronts: 1/2 in. tempered lites in aluminum U-channel at head and sill, joints butt-glazed with clear silicone, patch fittings and door hardware", unit: "linear ft", when: "the scope includes interior glass walls" },
      { item: "Glass railing panels: 1/2 in. tempered or laminated lites in a base shoe or standoff system with a top cap where required", unit: "linear ft", when: "the scope includes glass railings" },
      { item: "Commercial door glass: 1/4 in. tempered lites in aluminum stile-and-rail doors, glazing beads and gaskets replaced, closer and pivots adjusted", unit: "unit", when: "an entrance door is reglazed" },
      { item: "Window film: solar-control, safety or privacy film applied to the cleaned interior face and squeegeed to the edge", unit: "sqft", when: "the brief asks for film" },
      { item: "Access equipment: boom or scissor lift, or a glazing robot and vacuum lifter for lites over 150 lb, delivered for the days of the work", unit: "fixed", when: "openings are above the second floor or the lites are oversize" },
      { item: "Cleanup and disposal: old glass and framing scrap recycled, labels and protective film removed, both faces of the new glass cleaned", unit: "fixed" },
      { item: "Warranty and closeout: the fabricator's insulated-glass seal warranty (10 years against fogging) and the glazing labor warranty issued in writing", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Glass' line with no size, thickness or make-up",
      "'Glazing' priced per opening with no perimeter, seal or block detail",
      "storefront framing, curtain wall or shower enclosures priced here — their own specialties",
      "a 'Labor' line separate from the set-and-seal steps",
      "'Misc. hardware' — name the stops, gaskets and blocks",
    ],
    notes: [
      "Glass sizes come from field measurement after the order is approved; fabrication lead time (2-4 weeks for insulated units, longer for laminated or oversize) is stated on the proposal",
      "Frames are assumed sound and square; rotted, corroded or racked frames are repaired or replaced as a change",
      "Safety glazing follows the code hazardous-location rules at doors, tubs, stairs and low sills whether or not the old glass was tempered",
      "Manufacturer defects in glass fall under the fabricator's warranty; the glazing labor warranty covers the set and the seal",
    ],
  },
  "shower-mirror": {
    basis: "shower panels and doors each by size and glass thickness; mirrors by the square foot; hardware sets, seals and silicone runs by the unit or the foot",
    steps: [
      { item: "Field measurement after tile is set and grouted: each panel dimension, out-of-plumb and out-of-level readings, curb pitch, ceiling height and notches, hinge side and swing agreed and marked on the tile", unit: "fixed" },
      { item: "Removal of the existing shower door, frame or curtain rod, screw holes filled and the tile cleaned of old silicone", unit: "unit", when: "an old enclosure or rod is in place" },
      { item: "Shower glass fabricated to the measurements: 3/8 in. or 1/2 in. clear or low-iron tempered with polished edges, hinge and handle cut-outs, out-of-plumb angles and notches, and the factory water-repellent coating where selected", unit: "unit" },
      { item: "Frameless hardware set in the selected finish: wall-mount or pivot hinges, glass-to-glass and wall clamps, header or support bar, handle or towel bar, U-channel where a panel sits in channel", unit: "unit" },
      { item: "Enclosure installation: hinge and clamp holes drilled into tile or stone with diamond bits, anchors set into the blocking, panels plumbed on shims, door hung and adjusted for even reveals and self-close", unit: "unit" },
      { item: "Door seals: polycarbonate sweep with drip rail, side and jamb seals, and a header seal where the door meets the ceiling or a transom", unit: "unit" },
      { item: "Silicone sealing: 100% silicone at the wall and curb on the outside of the enclosure only, inside left open at the curb to weep, tooled in the matching color", unit: "linear ft" },
      { item: "Steam-shower enclosure: transom or full-height door with a header and vent, seals rated for steam", unit: "unit", when: "the shower is a steam room" },
      { item: "Mirror supplied and installed: 1/4 in. mirror cut to size with a polished or 1 in. beveled edge, safety backing, hung on mirror mastic with a J-channel or clips and a top cleat", unit: "sqft" },
      { item: "Mirror cut-outs and holes for outlets, switches, sconces and faucets, edges polished", unit: "unit", when: "a mirror carries fixtures or outlets" },
      { item: "Removal of an existing mirror: face taped, cut free of the mastic with wire, wall skimmed where the mastic tore the drywall", unit: "unit", when: "an old mirror is being replaced" },
      { item: "Interior glass accessories: shelves, shower niches, vanity tops, table tops, backsplash and cabinet-door glass cut to size with polished edges and hardware", unit: "unit", when: "the brief lists shelves, tops or other glass pieces" },
      { item: "Protective film removed, glass cleaned on both faces, hardware finish wiped, and the 24-hour silicone cure explained before the shower is used", unit: "fixed" },
      { item: "Care instructions and warranty: squeegee and cleaner guidance, coating warranty registered and the hardware and labor warranty issued in writing", unit: "fixed" },
    ],
    avoid: [
      "'Shower door' priced as one word with no glass thickness, panel count or hardware finish",
      "'Glass' and 'Hardware' as bare lines with no size, finish or count",
      "tile, plumbing, blocking or drywall repair — the tile setter's and carpenter's work",
      "a 'Measure fee' as its own line when it is part of the enclosure price",
      "'Caulking' with no location or color",
    ],
    notes: [
      "Panels are measured only after tile is complete; walls out of plumb over 1/4 in. or curbs without pitch are handled with angled edges and reported before fabrication",
      "Solid blocking behind the hinge wall and the header is assumed in place; hollow walls take a change order for backing",
      "Fabrication lead time is 7-14 days from approved measurements; low-iron, coated or patterned glass may run longer",
      "Silicone cures 24 hours before the first use; the coating warranty follows the manufacturer's care rules",
    ],
  },
  "storefront-curtain-wall": {
    basis: "square feet of glazed elevation by system depth, glass make-up and finish; entrance doors, anchors and hardware each; perimeter sealant and flashing by the linear foot",
    steps: [
      { item: "Field verification: rough openings, slab edges, embeds and anchor substrates surveyed with a laser, out-of-tolerance conditions reported to the general contractor before fabrication", unit: "fixed" },
      { item: "Shop drawings, engineering and submittals: stamped calculations for wind load (ASCE 7), deflection and thermal movement, anchor design, elevations and details, finish and glass samples", unit: "fixed" },
      { item: "Storefront framing fabricated and installed: thermally broken extruded aluminum (2 in. x 4-1/2 in. center- or front-set), clear anodized Class I or two-coat PVDF finish, cut, notched, assembled and shimmed plumb and level to the lines", unit: "sqft" },
      { item: "Curtain wall framing fabricated and installed: 2-1/2 in. x 7-1/2 in. (or deeper) pressure-plate stick system or unitized panels, thermally broken, hung from floor anchors with dead-load and wind-load connections", unit: "sqft", when: "the elevation is curtain wall rather than storefront" },
      { item: "Anchors and attachments: sill, jamb and head anchors, F-clips or T-anchors, embeds or post-installed anchors into concrete and steel, shims and isolation at dissimilar metals", unit: "unit" },
      { item: "Sill flashing: sill pan or subsill with end dams and a back leg, set in sealant and screwed to the substrate, weeps left open", unit: "linear ft" },
      { item: "Glazing: 1 in. insulated units (1/4 in. low-E tempered, 1/2 in. argon airspace, 1/4 in. clear tempered) set on blocks with EPDM gaskets in storefront or pressure plates and snap caps in curtain wall", unit: "sqft" },
      { item: "Spandrel and opaque infill: ceramic-frit or opacified spandrel glass, insulated metal panels or aluminum plate in the same frame", unit: "sqft", when: "the elevation has spandrel or panel areas" },
      { item: "Entrance doors: medium- or wide-stile aluminum doors with 1/4 in. tempered glass, offset pivots or continuous hinge, surface closer, push/pull or panic hardware, threshold and weatherstrip, keyed cylinder", unit: "unit" },
      { item: "Automatic door operators: low-energy swing or full-power sliding operator with actuators and safety sensors, wired to the electrician's circuit", unit: "unit", when: "the entrance is automatic" },
      { item: "Sunshades, canopies or column covers fabricated in the matching finish and attached to the framing", unit: "linear ft", when: "the elevation carries sunshades or covers" },
      { item: "Perimeter sealant: backer rod and silicone at the frame-to-substrate joint inside and out, splice and end-dam seals, interior insulation stuffed at the shim space", unit: "linear ft" },
      { item: "Field water test to AAMA 501.2 on the first installed bay, with the architect or owner's representative present and any leak corrected before the rest is closed in", unit: "fixed", when: "the specification requires field testing" },
      { item: "Crane or lift for framing and glass: boom lift, scissor lift or crane with a glazing manipulator, rented for the installation days", unit: "fixed" },
      { item: "Final cleaning and protection: protective film removed, glass and aluminum washed, temporary labels removed, elevations protected until turnover", unit: "fixed" },
      { item: "Closeout: finish warranty (10-20 years PVDF), insulated-glass seal warranty, hardware keying and maintenance instructions delivered", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Storefront' line priced per opening with no system depth, finish or glass make-up",
      "framing and glass rolled into one 'glazing' line",
      "'Engineering' with no stamped calcs or submittals named",
      "structural steel, concrete curbs or rough openings — the general contractor's work",
      "'Hardware' with no closer, pivot or panic device named",
    ],
    notes: [
      "Elevation area is measured from the shop drawings; openings are assumed within 1/4 in. of plumb and the slab edge as shown on the structural drawings",
      "Lead time is 6-10 weeks from approved shop drawings; finish and glass changes after approval are priced as a change",
      "Electrical for operators, security and lighting is by others and stubbed to the frame",
      "Field testing beyond the first bay and any third-party testing agency fees are passed through",
    ],
  },
  "garage-flooring": {
    basis: "square feet of garage slab by coating or tile system; stem walls, threshold edge and joints by the linear foot; steps and repairs each",
    steps: [
      { item: "Slab moisture check: plastic-sheet test (ASTM D4263) or calcium-chloride test at two points, with a look at the slab age, drains and any vapor barrier before the day is booked", unit: "fixed", when: "the brief asks for a moisture check or names a new, damp or below-grade slab" },
      { item: "Garage clear-out and protection: vehicles out, shelving, water heater and door tracks masked with plastic, walls and cabinets taped to the coating line, the house door and the driveway apron protected", unit: "fixed" },
      { item: "Stripping an old coating or peeling paint with PCD tooling until bare concrete shows across the whole floor", unit: "sqft", when: "the slab was coated or painted before" },
      { item: "Degreasing of oil, transmission-fluid and tire stains with an alkaline cleaner and hot-water extraction so the coating can bond", unit: "sqft", when: "the slab is oil-stained" },
      { item: "Diamond grinding to a CSP 2 profile with a HEPA-vacuum grinder, edges and corners hand-ground, floor vacuumed twice and tack-wiped", unit: "sqft" },
      { item: "Control joints and cracks filled with a flexible polyurea joint filler and shaved flush so the finished floor reads as one plane (joints left open on request)", unit: "linear ft" },
      { item: "Pitting and spall repair with a fast-set polyurea or epoxy patch, feathered flush before the base coat", unit: "sqft", when: "the slab is pitted, spalled or has popped stones" },
      { item: "Pigmented base coat: polyaspartic or 100% solids epoxy at 6-8 mils, rolled to the masked line in the selected base color", unit: "sqft" },
      { item: "Full flake broadcast: 1/4 in. flake blend thrown to rejection into the wet base coat, scraped and vacuumed after cure for a uniform texture that hides dust and tire marks", unit: "sqft" },
      { item: "Clear polyaspartic top coat at 8-10 mils, UV-stable so it will not yellow at the door, hot-tire and road-salt resistant, with fine anti-slip aggregate mixed in where selected", unit: "sqft" },
      { item: "Stem walls coated 4-6 in. high in the same flake system with a masked, level cut line", unit: "linear ft", when: "the garage has exposed stem walls" },
      { item: "Steps and landings into the house coated in the flake system with the nosing wrapped", unit: "unit", when: "steps lead from the garage into the house" },
      { item: "Threshold edge at the garage door: coating keyed into a saw-cut groove or terminated at an aluminum threshold so the edge will not lift", unit: "linear ft" },
      { item: "Interlocking garage tile: PVC or polypropylene tiles laid loose over the cleaned slab with edge ramps at the door and cut around posts", unit: "sqft", when: "the client chooses tile over a coating" },
      { item: "Cure and return: walk on the floor after 6-8 hours, park on it after 24-48 hours, masking pulled and contents moved back, with the times written on the invoice", unit: "fixed" },
      { item: "Cleanup and closeout: grinding dust and flake sweepings hauled off, driveway rinsed, care sheet and the coating warranty (lifetime against peeling where offered) handed over", unit: "fixed" },
    ],
    avoid: [
      "'Garage floor epoxy' as one line — the base coat, flake and top coat are separate lines with their mils",
      "'Prep' with no grinding profile, joint fill or crack repair named",
      "a quote by the car count (2-car, 3-car) with no measured area",
      "concrete pouring, lifting or drainage — a concrete contractor's work",
      "'Extra colors' or 'upgrade' lines with nothing measurable",
    ],
    notes: [
      "Area is the measured slab, wall to wall; stem walls, steps and the threshold edge are priced by the foot or each",
      "The slab is assumed cured 28 days, unsealed and dry at the test spots; a wet slab takes a moisture-mitigation primer as a change",
      "Flake blends and base colors are chosen from the sample board; the finished texture varies slightly from the sample",
      "Return-to-service times assume 50-90 F; cold or damp weather stretches them",
      "Slab lifting, drains and lighting are excluded",
    ],
  },
};
