// Smart Proposal procedures — Specialty systems. See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  "solar": {
    basis: "system size in kilowatts DC by module count; attachments, modules, inverters and electrical devices each; conduit and wire by the linear foot; permits, interconnection and PTO fixed",
    steps: [
      { item: "Site survey and shade study: roof measured and photographed, pitch and azimuth recorded, shade analysis at each array location, attic framing and rafter spacing checked, main service panel and meter photographed", unit: "fixed" },
      { item: "Engineering and plan set: array layout, single-line diagram, structural letter (stamped where the jurisdiction requires), string sizing and NEC 690 calculations", unit: "fixed" },
      { item: "Building and electrical permits and plan check, and the HOA application where the community requires one", unit: "fixed" },
      { item: "Utility interconnection application and net-metering agreement filed before the install", unit: "fixed" },
      { item: "Roof attachments: flashed, lag-bolted mounts into the rafters with the penetrations sealed", unit: "unit" },
      { item: "Racking: aluminum rail, mid and end clamps, splices and grounding lugs set level across the attachments", unit: "linear ft" },
      { item: "Solar modules: monocrystalline panels of the stated wattage (400-450 W class) with the manufacturer's 25-year product and performance warranty", unit: "unit" },
      { item: "Inverter: string inverter with power optimizers, or microinverters at each module, sized to the array with the AC rating stated", unit: "unit" },
      { item: "Rapid shutdown: module-level device or initiator per NEC 690.12 with the roof-level labeling", unit: "unit" },
      { item: "Roof junction box or transition box at the array edge, and the DC or AC home run in EMT or PVC conduit to the inverter and panel, wire size stated", unit: "linear ft" },
      { item: "AC disconnect, PV breaker and production meter socket where the utility requires one, and any load-side or line-side tap hardware", unit: "unit" },
      { item: "Main panel work: PV breaker under the 120% rule or a main-breaker derate; panel upgrade to 200 A where the existing service cannot carry the backfeed", unit: "unit", when: "the existing panel cannot accept the PV breaker" },
      { item: "Ground-mount structure: driven piles or concrete footings and racking, with the trench and conduit run to the house", unit: "unit", when: "the array is ground-mounted" },
      { item: "Grounding and labeling: equipment grounding, bonding and the NEC 690 placards and directory at the meter and disconnects", unit: "fixed" },
      { item: "Monitoring: gateway or consumption meter wired and set up with the owner's app and the manufacturer's warranty registration", unit: "unit" },
      { item: "AHJ inspection: building and electrical final with the inspector on site, corrections closed out", unit: "fixed" },
      { item: "Permission to operate: utility inspection, meter swap and PTO letter, then the system is energized and the owner walked through the app and the shutdown procedure", unit: "fixed" },
      { item: "Cleanup, packaging recycled, and the incentive paperwork (federal credit documentation and local rebate applications) delivered", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Solar system' line with no kW, module count or inverter",
      "'Electrical' with no conduit run, breaker or panel work named",
      "modules and racking rolled into one line",
      "battery storage or an EV charger priced here — their own specialties",
      "'Permits' with no jurisdiction fee, HOA or utility step named",
    ],
    notes: [
      "System size is the module count times the module wattage in DC; the AC rating is the inverter's",
      "The roof is assumed to have 10+ years of life and framing that carries the array; re-roofing or reinforcement is a change",
      "Interconnection and PTO timing is the utility's; production starts after the PTO letter",
      "Incentives are the owner's to claim; the estimate lists the documents, not the credit",
    ],
  },
  "smart-home": {
    basis: "devices, keypads, speakers, cameras and control points each; cable runs by the linear foot; programming and integration by the hour; design and documentation fixed",
    steps: [
      { item: "Discovery and system design: rooms walked, subsystems chosen (lighting, shades, AV, climate, security), device schedule and wiring plan drawn, equipment list and platform confirmed", unit: "fixed" },
      { item: "Low-voltage prewire: Cat6 or Cat6A to each TV, access point, keypad, camera and touch panel location, home-run to the equipment rack", unit: "linear ft" },
      { item: "Speaker and shade wiring: 16/2 or 16/4 speaker cable to each speaker location and power or control cable to each motorized shade pocket", unit: "linear ft" },
      { item: "Backboxes, brackets and conduit: low-voltage brackets, keypad backboxes, in-wall speaker brackets and 1-2 in. conduit to the rack for future pulls", unit: "unit" },
      { item: "Network: rack-mount router with firewall, managed PoE switch, wireless access points (Wi-Fi 6E or 7) ceiling-mounted for whole-house coverage, and a UPS", unit: "unit" },
      { item: "Equipment rack: enclosed or open rack with patch panel, power conditioner, cooling fan and cable management at the head-end", unit: "unit" },
      { item: "Control system: processor and interfaces (touch panels, handheld remotes, wall keypads) for the chosen platform", unit: "unit" },
      { item: "Lighting control: smart dimmers and keypads, or a panelized lighting system with a load center, per the device schedule", unit: "unit" },
      { item: "Motorized shades: roller or honeycomb shades in the selected fabric with quiet motors on power or battery", unit: "unit", when: "the scope includes shades" },
      { item: "Climate integration: smart thermostats or an HVAC gateway tied to the control system", unit: "unit", when: "climate control is part of the system" },
      { item: "Distributed audio: in-ceiling or in-wall speakers, multi-zone amplifier and streaming sources", unit: "unit" },
      { item: "Video: displays mounted, video distribution over HDBaseT or IP, sources and a surround or soundbar system", unit: "unit", when: "the scope includes TVs or a media room" },
      { item: "Security and cameras: PoE cameras, network video recorder, video doorbell and smart locks tied to the control system", unit: "unit", when: "the scope includes cameras or locks" },
      { item: "Programming and integration: scenes, schedules, voice control, remote access and each subsystem brought into the single app", unit: "hour" },
      { item: "Commissioning: every device tested from every interface, network load and coverage checked, firmware updated", unit: "hour" },
      { item: "Owner training and a walk-through of the app, keypads and remotes with a quick-reference card", unit: "fixed" },
      { item: "Documentation: network map, IP and credential schedule, device list and as-built wiring drawings", unit: "fixed" },
      { item: "Cleanup and closeout: packaging recycled, wall penetrations patched, and the service plan and warranty issued", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Smart home system' line with no device count or platform",
      "'Wiring' with no cable type or run length",
      "programming buried inside device prices",
      "line-voltage electrical, drywall or HVAC equipment — other trades",
      "'Misc. equipment' — name each device",
    ],
    notes: [
      "Device counts follow the schedule the client approves; each added device carries its own programming time",
      "Line-voltage circuits for racks, shades and displays are by the electrician",
      "Internet service and the client's subscriptions are excluded",
      "Programming is billed by the hour against the scope; post-handover changes are service calls",
    ],
  },
  "ev-charger": {
    basis: "chargers each by amperage and type; branch circuit and trench by the linear foot; panel work each; permits and commissioning fixed",
    steps: [
      { item: "Site evaluation and load calculation: service size and panel capacity checked, an NEC 220.83/220.87 load calc run, the charger location and the shortest safe circuit route set", unit: "fixed" },
      { item: "Electrical permit and inspection scheduling with the jurisdiction", unit: "fixed" },
      { item: "Panel work: 2-pole 40, 50 or 60 A breaker in the main panel, or a subpanel or 200 A panel upgrade where the load calc shows the service is full", unit: "unit" },
      { item: "Load management device to share the available capacity so the charger runs without a service upgrade", unit: "unit", when: "the load calc shows the service is at its limit" },
      { item: "Branch circuit: 6 AWG THHN copper in 3/4 in. EMT on a 60 A breaker for a 48 A charger, or 6-3 NM-B on a 50 A breaker for a 40 A charger, run from the panel to the charger location at the 125% continuous-load rating of NEC 625", unit: "linear ft" },
      { item: "Trenching and underground conduit: 18-24 in. trench, Schedule 40 PVC, backfilled and the surface restored for a detached garage or carport", unit: "linear ft", when: "the charger is in a detached building or in the drive" },
      { item: "Wall or slab penetration: core-drilled or bored, sleeved and fire-stopped at the exterior or rated wall", unit: "unit", when: "the circuit passes through masonry or a rated wall" },
      { item: "NEMA 14-50 receptacle on a GFCI breaker with a weatherproof in-use cover for a plug-in charger", unit: "unit", when: "the charger plugs in rather than hardwires" },
      { item: "Level 2 charger: 40-48 A EVSE (Wi-Fi, app-scheduled) mounted at the marked height, hardwired, with a cable hook or retractor", unit: "unit" },
      { item: "Pedestal or bollard mount with concrete base for a parking-lot or driveway charger", unit: "unit", when: "no wall is available at the parking spot" },
      { item: "Networked commercial stations: OCPP-capable Level 2 stations with payment, signage, wheel stops and accessible-stall striping", unit: "unit", when: "the site is a commercial or multi-unit installation" },
      { item: "Commissioning: circuit energized, ground-fault and polarity tested, charger paired to Wi-Fi and the app, a charge session run on the vehicle and the owner walked through scheduling", unit: "fixed" },
      { item: "Utility rebate and EV-rate paperwork filed with the installation photos", unit: "fixed", when: "the utility or state offers a rebate" },
      { item: "Patching and cleanup: drywall or siding penetrations patched, conduit painted to match, packaging removed and the charger warranty registered", unit: "fixed" },
    ],
    avoid: [
      "a bare 'EV charger install' line with no amperage, circuit length or panel work",
      "'Electrical' with no wire gauge, breaker or conduit",
      "the charger and the circuit priced as one line",
      "solar or battery storage priced here — their own specialties",
      "'Upgrade' with no panel amperage named",
    ],
    notes: [
      "Circuit length is measured along the route from the panel; the shortest route inside a finished wall may need drywall repair",
      "The service is assumed to have capacity per the load calc; a utility service upgrade is the utility's and the owner's",
      "The charger is the owner's choice; the estimate names the model and amperage",
      "Permit and inspection fees are passed through at the jurisdiction's rate",
    ],
  },
  "data-cabling": {
    basis: "cable drops each by category; cable and pathway by the linear foot; racks, panels, fiber terminations and access points each; certification testing per link",
    steps: [
      { item: "Site survey and design: drop locations counted room by room, telecom room and rack placement set, pathways routed, a cable schedule and drawing produced", unit: "fixed" },
      { item: "Pathways: J-hooks or cable tray above the ceiling, sleeves and firestop at rated walls and floors, surface raceway where walls are finished", unit: "linear ft" },
      { item: "Horizontal cabling: Cat6 or Cat6A plenum (CMP) or riser (CMR) cable pulled from the patch panel to each outlet location, under 295 ft per TIA-568", unit: "linear ft" },
      { item: "Drop terminations: keystone jack at the work area with a faceplate or surface box, matching port on the patch panel, both ends labeled", unit: "unit" },
      { item: "Backbone fiber: OM4 multimode or OS2 single-mode strands, indoor or indoor/outdoor rated, pulled between telecom rooms or buildings", unit: "linear ft", when: "the design links telecom rooms or buildings" },
      { item: "Fiber terminations: fusion-spliced LC pigtails or field-polished connectors in a rack-mount enclosure with adapter panels", unit: "unit", when: "fiber is in the scope" },
      { item: "Rack or cabinet: 2- or 4-post rack or enclosed cabinet with vertical managers, rack PDU and a grounding bus bar bonded per TIA-607", unit: "unit" },
      { item: "Patch panels and horizontal managers: 24- or 48-port Cat6A panels with wire managers above and below", unit: "unit" },
      { item: "Patch cords: factory-terminated cords at the panel and the work area in the stated lengths and colors", unit: "unit" },
      { item: "Wireless access point drops: ceiling-mounted with a PoE drop and a mounting bracket at the surveyed location", unit: "unit", when: "the design includes access points" },
      { item: "Wall and floor penetrations: core drilling, fishing finished walls and hard-lid ceiling access with patch and paint", unit: "unit", when: "walls are finished or ceilings are hard-lid" },
      { item: "Certification testing: every copper link tested to the TIA-568 Cat6 or Cat6A permanent-link standard with a certified tester, fiber tested by OLTS or OTDR, reports delivered", unit: "unit" },
      { item: "Labeling and as-builts: cables, panels and faceplates labeled to TIA-606, with the drawing updated to the installed locations", unit: "fixed" },
      { item: "Cleanup: ceiling tiles reset, debris removed and the 25-year system warranty registered where the manufacturer offers one", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Data drops' line with no category, cable rating or count",
      "'Cabling' priced by the building with no run length or drop count",
      "testing folded into the drop price with no standard named",
      "switches, servers, phones or software — the IT vendor's line",
      "'Materials' separate from the drops they belong to",
    ],
    notes: [
      "Drop count and average run length are from the survey; walls found without a path or ceilings without access are a change",
      "Plenum cable is used wherever the ceiling is a return-air plenum, at the plenum price",
      "Active equipment (switches, access points beyond the drop, servers) is by the IT provider unless listed",
      "The manufacturer's system warranty needs a certified installer and the test reports above",
    ],
  },
  "residential-generator": {
    basis: "generator, transfer switch and pad each by kW and amperage; feeder, control wiring and gas line by the linear foot; permits, startup and inspections fixed",
    steps: [
      { item: "Site assessment and sizing: whole-house or essential-circuit load survey, kW selected, fuel supply and meter capacity checked, pad location set to the clearances (18 in. from the house, 60 in. from openings) and the noise ordinance", unit: "fixed" },
      { item: "Permits: electrical, gas or mechanical, and zoning or HOA approval for the outdoor unit", unit: "fixed" },
      { item: "Standby generator: air-cooled 18-26 kW (or liquid-cooled 30-60 kW) natural-gas or propane unit in a weather-rated, sound-attenuated enclosure with the manufacturer's warranty", unit: "unit" },
      { item: "Generator pad: composite pad or 4 in. reinforced concrete pad on compacted gravel, level, with the unit bolted down", unit: "unit" },
      { item: "Automatic transfer switch: 200 A service-entrance-rated ATS for whole-house, or a 100-200 A ATS with load-shedding modules for managed loads, mounted beside the main panel", unit: "unit" },
      { item: "Feeder: conductors from the ATS to the generator in conduit, sized to the transfer switch (3 AWG copper or 1 AWG aluminum for 100 A), buried 18-24 in. or run along the wall", unit: "linear ft" },
      { item: "Control wiring: 2-conductor or 4-conductor low-voltage cable from the ATS to the generator controller in its own conduit", unit: "linear ft" },
      { item: "Trenching for the feeder and gas line, backfilled and the lawn or hardscape restored", unit: "linear ft", when: "the generator sits away from the panel or meter" },
      { item: "Gas line: 3/4 to 1-1/4 in. black iron or CSST from the meter to the generator with a shut-off, sediment trap, regulator and flexible connector, pressure-tested", unit: "linear ft" },
      { item: "Utility gas meter upgrade requested for the added load, with the utility's fee passed through", unit: "fixed", when: "the meter cannot supply the generator with the house" },
      { item: "Propane supply: tank set, regulator and line sized for the generator's BTU rating", unit: "unit", when: "the fuel is propane" },
      { item: "Battery, cold-weather kit and block heater installed for reliable starts", unit: "unit" },
      { item: "Manufacturer-certified startup: fuel pressure, oil, voltage and frequency checked, exercise schedule set, a transfer test under load run", unit: "fixed" },
      { item: "Remote monitoring: Wi-Fi or cellular module paired to the owner's app with alerts", unit: "unit" },
      { item: "Electrical and gas inspections with the inspector on site, corrections closed out", unit: "fixed" },
      { item: "Cleanup, warranty registration (5-10 years) and the owner walk-through of the exercise cycle and the maintenance schedule", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Generator' line with no kW, fuel or transfer switch",
      "'Electrical' or 'Gas' with no size, run length or fitting named",
      "the generator and the ATS priced as one line",
      "a service-entrance upgrade or gas meter set — the utility's or the electrician's line unless listed",
      "'Startup' with no test named",
    ],
    notes: [
      "Feeder and gas runs are measured along the route from the panel and the meter; every added 10 ft is priced by the foot",
      "The gas meter is assumed to have capacity for the generator plus the house; a utility meter upgrade is passed through",
      "The pad location follows the manufacturer's clearances and local setbacks; a change of location after the survey is a change",
      "Annual maintenance is a separate service plan",
    ],
  },
  "battery-backup": {
    basis: "battery units each by kWh and inverter kW; gateway, subpanel and disconnects each; conduit and conductors by the linear foot; permits, inspection and PTO fixed",
    steps: [
      { item: "Backup-load assessment: critical loads listed and metered, backup hours and battery count set, the mounting location checked for clearances, temperature and the fire-code rules (NFPA 855, IRC R328)", unit: "fixed" },
      { item: "Design and permits: single-line diagram, equipment listing (UL 9540) and placards, building and electrical permit and plan check", unit: "fixed" },
      { item: "Utility energy-storage interconnection application and the export or non-export agreement", unit: "fixed" },
      { item: "Battery units: lithium iron-phosphate or NMC modules of the stated kWh (5-15 kWh each) wall- or floor-mounted on the manufacturer's bracket with vehicle-impact protection in a garage", unit: "unit" },
      { item: "Hybrid or battery inverter for DC-coupled or retrofit AC-coupled storage, sized to the battery kW", unit: "unit", when: "the battery does not carry its own inverter" },
      { item: "Backup gateway or microgrid interconnection device: islands the home from the grid in an outage and meters the site", unit: "unit" },
      { item: "Critical-loads subpanel: 100-125 A panel with the backed-up circuits relocated from the main panel", unit: "unit", when: "the whole panel is not backed up" },
      { item: "Conductors and conduit: AC circuit from the gateway to the panel and DC or AC wiring between the batteries and the inverter, in EMT or PVC with the wire size stated", unit: "linear ft" },
      { item: "Main panel modifications: breakers, a bus-bar tap or a main-breaker derate, and the panel upgrade where the service cannot accept the storage feed", unit: "unit" },
      { item: "Solar integration: existing PV tied through the gateway so the array charges the battery in an outage", unit: "unit", when: "the home has or is adding solar" },
      { item: "Generator integration: automatic transfer input with the generator locked out from backfeeding the battery inverter", unit: "unit", when: "the home has a standby generator" },
      { item: "Fire and code items: 5/8 in. Type X gypsum at the mounting wall where required, heat or smoke detection in the room, spacing between units and the placards", unit: "fixed" },
      { item: "Commissioning: firmware updated, backup transfer test with the grid disconnected, operating mode set (self-consumption, time-of-use or backup reserve), app configured", unit: "fixed" },
      { item: "Inspection and permission to operate: AHJ final and the utility's approval before the system exports", unit: "fixed" },
      { item: "Monitoring and owner training: app access, alerts, the outage behavior explained and the incentive paperwork delivered", unit: "fixed" },
      { item: "Cleanup, packaging recycled and the 10-year battery warranty registered", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Battery' line with no kWh, count or inverter",
      "'Electrical' with no gateway, subpanel or conductor run named",
      "the battery and the gateway priced as one line",
      "solar modules or a generator priced here — their own specialties",
      "'Permits' with no utility interconnection step",
    ],
    notes: [
      "Backup duration is an estimate from the metered loads; heavy loads (HVAC, ranges, dryers) are excluded from the backed-up circuits unless listed",
      "The mounting wall is assumed to meet the clearance and fire-separation rules; a different location is a change",
      "PTO timing is the utility's; the system runs in backup mode only until the export approval",
      "Incentives are the owner's to claim; the estimate lists the documents, not the credit",
    ],
  },
  "greywater-system": {
    basis: "diverters, filters, pumps and outlets each; drain and distribution piping by the linear foot; mulch basins each or irrigated beds by the square foot; permits and commissioning fixed",
    steps: [
      { item: "Site and feasibility assessment: greywater sources (laundry, showers, lavatories) and their daily volume, drain access, soil percolation, slope, setbacks from wells and property lines, and the plants to be irrigated", unit: "fixed" },
      { item: "Plumbing permit and drawings for the reuse system, or the permit-exempt laundry-to-landscape path where the state allows it", unit: "fixed", when: "the system goes beyond a permit-exempt laundry-to-landscape install" },
      { item: "Fixture-drain separation: greywater drains rerouted from the blackwater stack, with a labeled 3-way diverter valve and an accessible handle so flow returns to the sewer on demand", unit: "unit" },
      { item: "Collection piping: 1-1/2 to 2 in. ABS or PVC DWV drain pipe sloped 1/4 in. per ft from the diverter to the surge tank or filter, with cleanouts", unit: "linear ft" },
      { item: "Surge tank: vented, screened tank sized for one laundry or shower load, with an overflow to the sewer and a drain-down at the bottom", unit: "unit", when: "the system is pumped or the flow needs to be buffered" },
      { item: "Filtration: screen or basket filter (or a self-cleaning filter on larger systems) ahead of the distribution line, with a service access", unit: "unit" },
      { item: "Effluent pump and controller: submersible pump sized for the head and the distribution zone, float switch and an alarm", unit: "unit", when: "the landscape is above the source or too far for gravity" },
      { item: "Distribution main: 1 in. HDPE or purple-marked PVC from the filter to the irrigation zones, buried 12 in., with a vacuum breaker and drain valve", unit: "linear ft" },
      { item: "Mulch basins: excavated basins with a mulch shield and an outlet at each tree or shrub, sized to the plant and the soil", unit: "unit" },
      { item: "Subsurface drip or branched drain zone: purple 1/2 in. drip tubing with greywater-rated emitters, or branched drain outlets, under 2 in. of mulch across the irrigated bed", unit: "sqft", when: "beds rather than trees are irrigated" },
      { item: "Trenching for the distribution line and outlets, backfilled and the landscape restored", unit: "linear ft" },
      { item: "Indoor reuse treatment: tank, filtration, disinfection (UV or chlorine), dye injection and purple-pipe supply to toilets, with the backflow protection the code requires", unit: "unit", when: "greywater is reused indoors for flushing" },
      { item: "Labeling and signage: purple pipe, valve tags and the greywater warning label at each outlet and the diverter", unit: "fixed" },
      { item: "Inspection and commissioning: the jurisdiction's inspection, a flow test with the diverter in each position, outlets balanced and the owner shown the valve and filter cleaning", unit: "fixed" },
      { item: "Cleanup, restoration of the trench line, and the owner's manual with the soap and detergent guidance and the maintenance schedule", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Greywater system' line with no sources, valve or outlet count",
      "'Piping' with no size, material or run length",
      "kitchen sink or toilet water counted as greywater — it is blackwater under the code",
      "landscape planting or a full irrigation system — the landscaper's lines",
      "'Permit' where the state exempts the system, or none where it does not",
    ],
    notes: [
      "Volume is estimated from the fixtures and the household; the landscape must be able to take it, and the surplus goes to the sewer through the diverter",
      "Soil percolation and setbacks are checked on the assessment; poor soil or a setback conflict is a change in scope",
      "Greywater is not stored more than 24 hours; the system is designed to drain, not to hold",
      "Plant-safe soaps are the owner's responsibility; the manual lists what to avoid",
    ],
  },
  "gate-access-control": {
    basis: "operators, access devices, safety sensors and loops each; trench, conduit and control wiring by the linear foot; gate fabrication and pads each; commissioning fixed",
    steps: [
      { item: "Site survey: gate type (swing or slide), width, weight and hardware condition, power source and distance, grade and drainage at the gate line, sight lines, vehicle stopping distance and the UL 325 usage class", unit: "fixed" },
      { item: "Utility locate ticket and any permit or HOA approval for the automated gate and its posts", unit: "fixed" },
      { item: "Trench and underground conduit: 18-24 in. trench with Schedule 40 PVC for power and a second conduit for control and data, backfilled and restored", unit: "linear ft" },
      { item: "Power circuit: 120 or 240 V dedicated circuit from the panel to the operator disconnect, wire size stated, by the electrician where the jurisdiction requires", unit: "linear ft" },
      { item: "Operator pad: reinforced concrete pad with anchor bolts set to the gate line, or the post mount for a swing operator", unit: "unit" },
      { item: "Gate operator: slide-gate operator (chain or rack-and-pinion, 1/2-1 HP) or swing-arm or underground operator, UL 325 listed, with the control board, limit settings and a manual release", unit: "unit" },
      { item: "Gate hardware and fabrication: new gate or repair of the existing one, hinges, wheels, track, chain or rack, catch post and posts set in concrete", unit: "unit", when: "the gate is new, undersized for automation or in poor condition" },
      { item: "Entrapment protection: monitored photo-eyes and wireless edge sensors at each entrapment zone, warning signs on both faces, per UL 325 and ASTM F2200", unit: "unit" },
      { item: "Vehicle detection loops: saw-cut loops with sealant for free exit, safety and shadow, with loop detectors in the operator", unit: "unit" },
      { item: "Access control device: keypad, cellular or wired video intercom, proximity or RFID reader and remotes, on a pedestal or the post at the driver's reach", unit: "unit" },
      { item: "Exit device: free-exit wand, push button or a second reader on the inside", unit: "unit" },
      { item: "Battery back-up or solar power kit so the gate opens through an outage", unit: "unit", when: "the client wants outage operation or the site has no power" },
      { item: "Network connection: Ethernet or cellular link for cloud management, app control and delivery codes", unit: "unit", when: "the access device manages users remotely" },
      { item: "Barrier-arm operators and pedestals for a commercial lane, with arm, loops and signage", unit: "unit", when: "the site is a commercial lane or parking facility" },
      { item: "Programming and commissioning: limits, force and speed set, entrapment tests run on every device, codes and credentials loaded, the owner trained on the release and the app", unit: "fixed" },
      { item: "Cleanup and closeout: trench line restored, packaging removed, and the operator warranty (typically 2-5 years) and the maintenance schedule issued", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Gate opener' line with no operator type, horsepower or safety devices",
      "'Electrical' with no trench, circuit or run length",
      "the operator and the access device priced as one line",
      "fencing, columns or paving — the fence and masonry lines",
      "'Safety' with no photo-eye, edge or loop count",
    ],
    notes: [
      "The gate is assumed plumb, square and free-swinging; a dragging or overweight gate is repaired or replaced as a change",
      "Power runs are measured from the nearest panel; a long run or a subpanel is priced by the foot",
      "Entrapment protection follows the current UL 325 edition and is not optional; a client who declines it is not offered automation",
      "Cellular service and cloud subscriptions are the owner's monthly cost",
    ],
  },
};
