// Smart Proposal procedures — Waterproofing & envelope. See ./types.ts.
import type { ProcedureMap } from "./types";

export const PROCEDURES: ProcedureMap = {
  "waterproofing": {
    basis: "square feet of membrane by system and mil thickness; corners, terminations, flashings and drains by the linear foot or each; excavation and backfill by the cubic yard",
    steps: [
      { item: "Pre-installation survey and submittals: substrate condition, moisture and cure of the concrete, tie-in points to existing membranes, drainage outlets, and the manufacturer's product data, details and warranty application", unit: "fixed" },
      { item: "Excavation along the foundation wall to the top of the footing with a 3 ft working width, shored or benched, spoils stockpiled clear of the edge", unit: "cu yards", when: "the wall is an existing foundation that has to be exposed" },
      { item: "Substrate preparation: pressure washing or grinding, form-tie holes and honeycomb patched with non-shrink grout, fins and ridges ground off, a cant or fillet at the footing-to-wall joint", unit: "sqft" },
      { item: "Crack and cold-joint treatment: cracks over 1/16 in. routed and sealed, then covered with a 12 in. detail strip of the membrane", unit: "linear ft" },
      { item: "Primer or surface conditioner rolled or sprayed at the manufacturer's rate onto the dry, clean substrate", unit: "sqft" },
      { item: "Sheet membrane: 60-mil self-adhered rubberized-asphalt sheet, or 40-mil HDPE-faced blindside sheet, shingle-lapped 2-1/2 in. at side laps and 3 in. at end laps, rolled with a hand roller", unit: "sqft" },
      { item: "Fluid-applied membrane: two-component polyurethane or single-component modified-asphalt coating spray- or roller-applied to 60 mils dry with reinforcing fabric at joints", unit: "sqft", when: "the specification calls for a fluid-applied system" },
      { item: "Hot rubberized asphalt: 215-mil monolithic membrane with reinforcing fabric under a plaza deck or green roof, over a primed and dry deck", unit: "sqft", when: "the area is a plaza, podium or green-roof deck" },
      { item: "Detailing: inside and outside corners, footing-to-wall joint and construction joints reinforced with a second ply or liquid detailing membrane", unit: "linear ft" },
      { item: "Penetration flashing: pipes, conduits, sleeves and tie-backs wrapped with a liquid membrane boot or a target-patch sheet", unit: "unit" },
      { item: "Termination: top edge clamped under an aluminum termination bar with a sealant cap bead, or turned into a reglet with counterflashing", unit: "linear ft" },
      { item: "Tie-in to the existing membrane or roofing: old surface cleaned and primed, new membrane lapped 6 in. onto it and sealed with a compatible liquid flashing", unit: "linear ft", when: "the new work meets an existing membrane" },
      { item: "Protection board: 1/4 in. asphaltic board or 1/8 in. HDPE sheet adhered over the membrane before backfill or topping", unit: "sqft" },
      { item: "Drainage composite: dimpled drainage board with filter fabric hung over the membrane, bottom edge into the footing drain, laps shingle-fashion", unit: "sqft" },
      { item: "Footing drain: 4 in. perforated pipe in washed stone wrapped in filter fabric at the footing, run to the sump or daylight", unit: "linear ft", when: "the design includes a footing drain" },
      { item: "Deck drains and scuppers: clamping-ring drains or scupper flashings set into the membrane with the flashing collar sealed", unit: "unit", when: "the deck drains through the membrane" },
      { item: "Traffic-bearing deck coating: two-coat polyurethane deck system (base and aggregate top coat) to 30-40 mils dry over balconies and walkways", unit: "sqft", when: "the area is an exposed balcony, walkway or parking deck" },
      { item: "Flood test of horizontal membranes for 24-48 hours at 2 in. depth (ASTM D5957) or electronic leak detection, and a holiday check of walls before they are covered, with any breach repaired and retested", unit: "fixed" },
      { item: "Backfill with free-draining granular fill placed in 12 in. lifts and compacted away from the wall so the membrane and board are not dragged", unit: "cu yards", when: "the wall was excavated" },
      { item: "Cleanup, disposal of release liners and scrap, and the manufacturer's final inspection for the system warranty", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Waterproofing' line priced by the wall with no membrane type or thickness",
      "'Membrane' and 'protection board' as one line",
      "'Prep' with no patching, grinding or priming named",
      "interior finishes, landscaping or sump pumps — other trades' lines",
      "'Testing' with no method, duration or standard",
    ],
    notes: [
      "Membrane area is the net substrate area with corners and terminations added by the foot; the substrate is assumed cured 7-28 days and free of standing water",
      "Rock, groundwater or a soft trench bottom in the excavation is priced as a change",
      "The system warranty is the manufacturer's on the membrane and the applicator's on the workmanship; both need the inspection line above",
      "Existing membranes met at a tie-in are assumed sound; failed existing work is repaired as a change",
    ],
  },
  "sealant-caulking": {
    basis: "linear feet of joint by width, substrate and sealant type; penetrations and repairs each; access equipment and testing stated",
    steps: [
      { item: "Joint survey and adhesion testing: every joint type inventoried with its width, depth, movement and substrates, and a field adhesion test of the proposed sealant on each substrate before the order", unit: "fixed" },
      { item: "Access equipment: boom lift, scissor lift or swing stage set for the elevations, with ground protection and barricades", unit: "fixed", when: "joints are above ladder height" },
      { item: "Removal of the failed sealant: old bead cut out with a knife and grinder, remaining film abraded off both joint faces, loose backer rod pulled", unit: "linear ft", when: "the joints carry old sealant" },
      { item: "Joint cleaning: solvent wipe by the two-cloth method (or oil-free blow-down on porous stone) so the faces are dry and dust-free", unit: "linear ft" },
      { item: "Backer rod: closed-cell polyethylene rod 25% wider than the joint set to the depth that gives an hourglass bead, or bond-breaker tape at shallow joints", unit: "linear ft" },
      { item: "Primer brushed onto the joint faces where the manufacturer's adhesion test calls for it, and always on masonry, stone and precast", unit: "linear ft", when: "the adhesion test or the substrate requires primer" },
      { item: "Masking of the finish on both sides of the joint to keep the bead lines crisp on stone, precast and metal panels", unit: "linear ft" },
      { item: "Vertical joint sealant: silicone (ASTM C920 Class 50, type S or M) or polyurethane (Class 25) in the matched color, gunned into the joint and tooled concave to the backer rod for full wetting", unit: "linear ft" },
      { item: "Horizontal joint sealant: self-leveling polyurethane or traffic-grade silicone in saw-cut, expansion and isolation joints in sidewalks, plazas and parking decks", unit: "linear ft", when: "the scope includes joints in paving or decks" },
      { item: "Glazing seals: wet seal or cap bead of silicone at the glass-to-metal edge on window and curtain-wall units", unit: "linear ft", when: "the scope includes glass-to-frame seals" },
      { item: "Penetration and dissimilar-material seals: pipes, louvers, signs, conduits and lintels sealed with the compatible sealant", unit: "unit" },
      { item: "Expansion-joint systems: pre-compressed foam or extruded silicone joint systems set into the joint with the manufacturer's epoxy or adhesive", unit: "linear ft", when: "the building has structural expansion joints over 1 in." },
      { item: "Field adhesion test on the cured sealant (ASTM C1521 hand-pull) at the stated frequency, results logged for the warranty", unit: "fixed" },
      { item: "Water test of representative joints with a hose or spray rack, with any leak resealed", unit: "fixed", when: "the specification requires water testing" },
      { item: "Cleanup: masking removed, smears cleaned off the finish, cartridges and old sealant disposed of, and the applicator and manufacturer warranties issued", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Caulking' line priced by the building with no footage or sealant type",
      "'Sealant' with no ASTM class, color or joint named",
      "backer rod, primer and sealant as one line",
      "window replacement, masonry repointing or panel repair — other trades",
      "'Lift' with no equipment named",
    ],
    notes: [
      "Joint footage is taken from the survey; joints found wider than 1 in. or with failed substrates are priced as a change",
      "Sealant colors are matched from the manufacturer's chart or a custom match with lead time",
      "Application needs a dry substrate above 40 F; weather days move the schedule, not the price",
      "The sealant warranty is the manufacturer's on the material and the applicator's on the workmanship (typically 5 years)",
    ],
  },
  "metal-cladding": {
    basis: "square feet of wall by panel system, gauge and finish; subframing, trims, flashings and copings by the linear foot; insulation and barrier by the area covered",
    steps: [
      { item: "Laser survey of the wall substrate and structure, then shop drawings and engineering: panel layout, attachment calcs for wind load, thermal movement, submittals and finish samples", unit: "fixed" },
      { item: "Field mock-up: one bay of the full assembly (barrier, insulation, clips, panel and trims) built for approval and testing", unit: "fixed", when: "the specification calls for a mock-up" },
      { item: "Removal of the existing siding or cladding, fasteners pulled, sheathing exposed and inspected, debris hauled off", unit: "sqft", when: "existing cladding is being replaced" },
      { item: "Air and water-resistive barrier: fluid-applied or self-adhered membrane over the sheathing, openings and penetrations flashed, laps sealed", unit: "sqft", when: "the barrier is in the cladding scope" },
      { item: "Continuous exterior insulation: mineral wool or polyiso boards at the stated thickness and R-value, fastened with plastic or metal washers", unit: "sqft" },
      { item: "Subframing: thermally isolated clips and Z- or hat-girts at 16-24 in. o.c. set plumb to a laser plane, fastened to the studs or structure", unit: "linear ft" },
      { item: "Aluminum composite panels: 4 mm ACM routed and returned into pans with stiffeners, rear-ventilated rain-screen installation with the joints as detailed", unit: "sqft", when: "the panel is aluminum composite" },
      { item: "Single-skin metal panels: 22-24 ga. steel or 0.040 aluminum, preformed flush, corrugated or box-rib profile, concealed or exposed fastening", unit: "sqft", when: "the panel is single-skin metal" },
      { item: "Insulated metal panels: 2-4 in. foam-core panels with tongue-and-groove joints, set in sealant, clipped to the girts, panel joints gasketed", unit: "sqft", when: "the panel is an insulated metal panel" },
      { item: "Extruded trims and flashings: base, head, jamb, sill, inside and outside corners and reveals in the matching finish", unit: "linear ft" },
      { item: "Window and door surrounds: returns and receivers formed around each opening, end-dammed sill flashing sealed to the barrier", unit: "linear ft" },
      { item: "Parapet coping: formed or extruded coping with splice plates and cleats, matched to the panel finish", unit: "linear ft", when: "the wall ends at a parapet" },
      { item: "Joint sealing: backer rod and silicone at face-sealed panel joints and at every termination against dissimilar materials", unit: "linear ft" },
      { item: "Crane or lift for panels: boom lift, scissor lift or crane with panel clamps for the installation days", unit: "fixed" },
      { item: "Field water test on the mock-up or first bay to the specification, with any leak corrected before production", unit: "fixed", when: "the specification requires field testing" },
      { item: "Cleanup and closeout: protective film removed, panels washed, scrap recycled, and the PVDF finish warranty (20 years) and weathertightness warranty issued", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Metal panels' line with no system, gauge or finish",
      "clips, girts and panels as one 'siding' line",
      "'Flashing' with no location or profile",
      "structural steel, sheathing or windows — other trades' work",
      "'Engineering' with no calcs or shop drawings named",
    ],
    notes: [
      "Wall area is the net panel area from the shop drawings; trims and flashings are by the foot from the elevations",
      "The substrate is assumed within 1/4 in. in 10 ft; out-of-plane walls take extra shimming as a change",
      "Panel lead time is 6-12 weeks from approved shop drawings; custom colors add time",
      "Water testing beyond the first bay and any testing agency fees are passed through",
    ],
  },
  "crawlspace-repair": {
    basis: "square feet of crawlspace floor and wall by liner and insulation; joists, drains and liner terminations by the linear foot; posts, pumps, vents and equipment each",
    steps: [
      { item: "Crawlspace inspection: wood moisture readings at joists and subfloor, relative humidity, standing water and grade, sagging or rotted framing, pest and fungal evidence, vents and access mapped", unit: "fixed" },
      { item: "Debris removal: old vapor barrier, fallen insulation, wood scrap and trash bagged, carried out and hauled off", unit: "cu yards" },
      { item: "Fungal and mold treatment: joists and subfloor HEPA-vacuumed, scrubbed and treated with an EPA-registered antimicrobial and a borate wood treatment", unit: "sqft", when: "fungal growth or rot is found on the framing" },
      { item: "Joist sistering: new joists of the same depth glued and bolted alongside the damaged joists for their full length, bearing on the sill and girder", unit: "linear ft", when: "joists are cracked, rotted or over-notched" },
      { item: "Girder and sill repair: rotted sections cut out and replaced with pressure-treated lumber, sill plate anchored, temporary shoring during the swap", unit: "linear ft", when: "sills or girders are rotted" },
      { item: "Adjustable steel jack posts on new 24 x 24 x 12 in. concrete footings under the girder, plumbed and loaded to lift the floor to level", unit: "unit", when: "the floor sags or the piers have failed" },
      { item: "Grading and interior drainage: floor graded to a low corner, perforated drain in washed stone along the perimeter to the sump basin", unit: "linear ft", when: "water stands in the crawlspace" },
      { item: "Sump basin and pump: sealed basin with an airtight lid, 1/3-1/2 HP submersible pump, check valve and a discharge line to daylight", unit: "unit", when: "the drainage needs a sump" },
      { item: "Vent sealing: foundation vents closed with rigid foam plugs and sealed, outside vent covers installed", unit: "unit" },
      { item: "Foundation wall insulation: 2 in. closed-cell spray foam (R-13) or foil-faced rigid foam board sealed at the sill and rim joist, with the code-required 3 in. termite inspection gap", unit: "sqft" },
      { item: "Floor liner: 12-20 mil reinforced polyethylene liner over the whole floor, seams overlapped 12 in. and taped, wrapped and sealed around every pier and column", unit: "sqft" },
      { item: "Wall liner and termination: liner run up the foundation walls and piers, mechanically fastened with a termination bar and sealed with the manufacturer's tape", unit: "linear ft" },
      { item: "Crawlspace dehumidifier: 70-100 pint per day crawlspace-rated unit hung or set on a stand with the condensate piped to the sump or outside", unit: "unit" },
      { item: "Conditioning air: a supply register from the house duct or an exhaust fan sized at 1 cfm per 50 sqft per IRC R408.3", unit: "unit", when: "the space is conditioned instead of dehumidified" },
      { item: "GFCI outlet and circuit for the dehumidifier and pump, run from the panel by the electrician", unit: "unit", when: "no outlet exists in the crawlspace" },
      { item: "Insulated, airtight access door or well cover at the crawlspace entry", unit: "unit" },
      { item: "Cleanup, final moisture and humidity readings recorded, and the liner and workmanship warranty (typically 25 years on the liner) issued", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Encapsulation' line priced by the house with no liner mil, area or wall height",
      "'Vapor barrier' with no thickness, seam overlap or termination",
      "'Structural repair' with no joist count, footage or post count",
      "termite treatment, HVAC ductwork or plumbing leaks — other trades' work",
      "'Cleanup' with no debris volume",
    ],
    notes: [
      "Floor and wall areas are measured on the inspection; hidden rot found after demolition is priced as a change",
      "A 3 in. inspection strip is left at the top of the wall insulation where termites are a concern",
      "Standing water at the time of the inspection sets the drainage line; seasonal water found later is a change",
      "Pest treatment and radon mitigation are excluded",
    ],
  },
  "basement-waterproofing": {
    basis: "linear feet of interior drain or exterior wall by depth; wall membrane by the square foot; sump systems, pumps and window wells each; excavation and backfill by the cubic yard",
    steps: [
      { item: "Water-intrusion assessment: source and path traced (cove joint, wall cracks, tie holes, window wells or hydrostatic floor seepage), wall type and floor thickness noted, sump location and discharge route set", unit: "fixed" },
      { item: "Removal and reset of finishes at the perimeter: baseboard, drywall and framing cut back 12-24 in. from the wall and set aside", unit: "linear ft", when: "the basement is finished" },
      { item: "Interior perimeter cut: slab saw-cut 12 in. from the wall, concrete broken out and removed, trench dug to the footing and spoils carried out", unit: "linear ft" },
      { item: "Interior drain tile: 4 in. perforated corrugated or rigid PVC drain laid beside the footing on washed stone, with a wall-drainage flange to catch the cove joint and weep holes drilled in block walls", unit: "linear ft" },
      { item: "Wall vapor barrier: dimpled membrane or 20-mil poly hung 4-8 ft up the wall, sealed at the top and tucked into the drain so wall water runs to the tile", unit: "sqft" },
      { item: "Sump basin and pump: 18 x 24 in. basin with a sealed, radon-ready lid, 1/3-1/2 HP cast-iron submersible pump with a float switch and check valve", unit: "unit" },
      { item: "Battery back-up pump on the same basin with a charger and alarm for outages", unit: "unit", when: "the client wants outage protection" },
      { item: "Discharge line: 1-1/2 in. PVC through the rim or wall, buried 10-20 ft to daylight, a pop-up emitter or the storm connection, with a freeze guard", unit: "linear ft" },
      { item: "Concrete restoration: trench re-poured with 3,000-psi concrete troweled flush to the slab", unit: "linear ft" },
      { item: "Wall-crack injection: poured-wall cracks ported and injected with expanding polyurethane, surface-sealed with epoxy paste", unit: "linear ft", when: "poured-wall cracks are a water source" },
      { item: "Exterior excavation to the footing along the leaking wall, shored, spoils stockpiled, deck or steps removed and reset as needed", unit: "cu yards", when: "the exterior system is chosen" },
      { item: "Exterior wall waterproofing: wall cleaned and parged, 60-mil membrane or elastomeric coating applied, drainage board hung and a new footing drain laid to the sump or daylight", unit: "sqft", when: "the exterior system is chosen" },
      { item: "Backfill in lifts with free-draining stone and soil, grade sloped 6 in. in 10 ft away from the house, lawn and plantings restored", unit: "cu yards", when: "the exterior system is chosen" },
      { item: "Window wells and well drains: galvanized or composite well set at each below-grade window with a drain to the footing tile and a clear cover", unit: "unit", when: "window wells leak or are missing" },
      { item: "Basement dehumidifier plumbed to the sump to hold humidity under 50% after the water is stopped", unit: "unit", when: "the client wants humidity control" },
      { item: "Cleanup: dust walls removed, concrete rubble hauled off, floor swept and washed, pump run-tested with water in the basin", unit: "fixed" },
      { item: "Warranty: the transferable drainage-system warranty (lifetime where offered) and the pump warranty issued in writing with the maintenance schedule", unit: "fixed" },
    ],
    avoid: [
      "a bare 'Waterproofing' or 'French drain' line with no footage, pipe size or sump named",
      "'Sump pump' with no horsepower, basin size or discharge run",
      "the cut, the drain and the concrete patch as one line",
      "foundation underpinning, wall straightening or plumbing leaks — other specialties",
      "'Sealer' painted on the inside wall sold as waterproofing",
    ],
    notes: [
      "Perimeter footage is measured on the assessment; footings found deeper than 12 in. below the slab or a slab over 6 in. thick are a change",
      "The discharge point is assumed to be on the client's property and downhill of the house; a pumped or long run is priced by the foot",
      "Finishes are cut back and reset to a paint-ready state; painting and trim replacement are excluded",
      "The drainage warranty covers water at the floor and cove; wall cracks above the system are covered only where injected",
    ],
  },
  "house-wrap": {
    basis: "square feet of wall by barrier product; seams, sill plate and transitions by the linear foot; windows, doors and penetrations each",
    steps: [
      { item: "Sheathing walkthrough: sheathing gaps, popped fasteners and damaged panels flagged and fixed, and the barrier product and flashing sequence confirmed with the window installer", unit: "fixed" },
      { item: "Sheathing seam tape: every panel joint and corner taped with the manufacturer's acrylic tape and rolled", unit: "linear ft", when: "the air barrier is a taped-sheathing system" },
      { item: "Mechanically fastened wrap: spun-bonded polyolefin housewrap or a drainable wrap with a 1 mm drainage gap, run horizontally, lower course first, laps 6 in. horizontal and 12 in. vertical, cap nails or cap staples every 12-18 in.", unit: "sqft" },
      { item: "Fluid-applied barrier: spray- or roller-applied membrane at the stated wet-mil thickness over sheathing and joints, with joint treatment first", unit: "sqft", when: "the specification calls for a fluid-applied barrier" },
      { item: "Sill pans: wrap cut at each window and door opening and folded in, then a self-adhered or formed sill pan with back dam and end dams set over the sill flap before the unit goes in", unit: "unit" },
      { item: "Seam taping: all horizontal and vertical laps sealed with the wrap manufacturer's tape and rolled for adhesion", unit: "linear ft" },
      { item: "Window and door flashing: wrap cut in a modified I, jamb flashing tape 4-6 in. over the fins, head flashing over that, the head flap dropped over the head flashing and taped at the corners (ASTM E2112)", unit: "unit" },
      { item: "Penetration flashing: pipes, hose bibs, vents, electrical boxes, light blocks and deck ledger bolts flashed with self-adhered patches or preformed boots", unit: "unit" },
      { item: "Bottom-of-wall transition: wrap lapped over the sill plate and sealed to the foundation with a transition strip or fluid flashing", unit: "linear ft" },
      { item: "Roof-to-wall and deck transitions: step and kick-out flashing zones lapped into the wrap, ledger flashing integrated", unit: "linear ft", when: "walls meet a lower roof or a deck ledger" },
      { item: "Rain-screen furring or drainage mat: 3/8 in. furring strips or an entangled-mesh mat over the barrier for a ventilated siding cavity", unit: "sqft", when: "the wall assembly calls for a rain screen" },
      { item: "Repair of tears and staple-outs and a final walk with the siding contractor so nothing is covered before it is sealed", unit: "fixed" },
      { item: "Blower-door air-leakage test to the stated ACH50 with a report", unit: "fixed", when: "the project is tested for air tightness" },
      { item: "Third-party or building inspection of the barrier before siding, with the pass documented", unit: "fixed" },
      { item: "Cleanup: wrap trimmings, tape backing and packaging removed and the barrier warranty registered", unit: "fixed" },
    ],
    avoid: [
      "a bare 'House wrap' line with no product, lap or fastening",
      "windows and doors flashed as one 'flashing' line with no count",
      "wrap and tape as one line",
      "siding, windows or sheathing replacement — other trades' work",
      "'Inspection' with no inspector or pass named",
    ],
    notes: [
      "Wall area is the gross wall less openings over 20 sqft; openings and penetrations are counted from the plans",
      "Sheathing is assumed sound and nailed off; rotten or missing sheathing is a change",
      "The barrier is left exposed no longer than the manufacturer's UV limit (typically 90-120 days) before siding covers it",
      "Testing to a tightness target needs the whole air barrier (attic, foundation) by others to be complete",
    ],
  },
};
