// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "concrete-contractor": {
    op: 0.2,
    opNote: "concrete subcontractor, residential and light commercial",
    benchmark: {
      unit: "sqft",
      measures: "slab area placed, with its footings",
      price: [8, 15],
      typicalQty: [1500, 5000],
      jobQty: 3250,
      minJob: 3000,
      sources: ["HomeGuide 2026: concrete slab foundation $6-$14/sqft installed", "Estimators.us 2026: standard residential slab $6-$12/sqft installed", "HomeGuide 2026: slab installer labor $3-$5/sqft"],
    },
    steps: {
      "Layout from the plans: slab edges, footing lines, column pads and top-of-concrete elevations set with a transit or laser, pinned and string-lined; embeds and blockouts located": { price: [700, 1800], labor: 0.9, basis: "est", q: 1, note: "laser layout by the crew; scales with the number of footings and pads" },
      "Building permit for the structural concrete, pre-pour footing and reinforcing inspections scheduled, inspection fees": { price: [250, 1000], labor: 0, fee: true, basis: "est", q: 1, note: "city permit and inspection fees for the concrete scope" },
      "Mobilization and protection: forms, screeds, power trowels and a skid steer delivered; truck and pump access laid out; wash-out pit set; adjacent surfaces covered": { price: [700, 2200], labor: 0.4, basis: "est", q: 1, note: "equipment delivery and set-up; grows with slab size" },
      "Saw-cut, break out and haul away the existing slab or footings (thickness stated), rubble to a recycler": { price: [2.5, 6], labor: 0.55, basis: "src", note: "4 in. slab; thicker or reinforced slab toward the high end" },
      "Excavation to subgrade for the slab, footings and column pads, spoils stockpiled on site or hauled to a licensed fill site": { price: [25, 55], labor: 0.45, basis: "derived", q: 70 },
      "Subgrade preparation: native soil scarified, moisture-conditioned and compacted to 95% Standard Proctor, proof-rolled; soft spots dug out and replaced with crushed stone": { price: [0.3, 0.7], labor: 0.55, basis: "est", q: 3250 },
      "Aggregate base: 4-6 in. of 3/4-minus crushed stone placed, graded to the slab elevation and compacted in lifts with a plate or roller compactor": { price: [65, 110], labor: 0.4, basis: "derived", q: 42, note: "installed and compacted; HomeGuide pad base $1-$3/sqft" },
      "Footings and thickened edges: 2x lumber forms set to line and grade, staked and braced; continuous #5 bars with corner bars, standees and dowels bent up into the walls or slab": { price: [12, 24], labor: 0.6, basis: "derived", q: 240, note: "forms and rebar only; footing concrete is its own line" },
      "Slab edge forms: steel or 2x lumber set to grade with keyways, blockouts and screed rails at the pour breaks": { price: [3.5, 7.5], labor: 0.7, basis: "derived", q: 240 },
      "Vapor retarder: 15-mil polyethylene (ASTM E1745 Class A) over the base, seams lapped 6 in. and taped, penetrations and edges sealed": { price: [0.45, 0.9], labor: 0.35, basis: "derived" },
      "Slab reinforcing: #4 bars at 18 in. o.c. each way (or 6x6 W2.9xW2.9 welded wire) on chairs at mid-depth, laps tied, dowels drilled and epoxied into existing concrete": { price: [1, 1.9], labor: 0.35, basis: "derived", q: 3250, note: "#4 at 18 in. each way; welded wire toward the low end" },
      "Anchor bolts, hold-downs, column-base templates, sleeves and embed plates set to the plan before the pour": { price: [15, 40], labor: 0.6, basis: "est", q: 36 },
      "Concrete pump with operator and line for placements the truck chute cannot reach": { price: [1300, 2800], labor: 0, basis: "src", note: "boom pump per pour day; add $3-$10 per cu yard pumped" },
      "Footings placed: 3,000-psi concrete, vibrated, struck level at the wall or slab elevation with the dowels set": { price: [220, 290], labor: 0.2, basis: "derived", q: 12 },
      "Slab placed: 4,000-psi concrete at a 4 in. slump, air-entrained where exposed to freezing, placed to the stated thickness, laser-screeded or wet-screeded and bull-floated": { price: [235, 310], labor: 0.25, basis: "derived", q: 42 },
      "Finishing: power-trowel hard-trowel finish on interior slabs (FF 35 / FL 25 flatness), medium broom on exterior slabs, edges and joints tooled": { price: [0.75, 1.5], labor: 0.85, basis: "derived", q: 3250 },
      "Control joints saw-cut to one-quarter of the slab depth within 6-12 hours of finishing, spaced at 24-36 times the thickness each way, or tooled in at the pour": { price: [0.9, 2], labor: 0.7, basis: "est", q: 480 },
      "Curing: liquid membrane curing compound (ASTM C309) sprayed at the finish, or wet-cured 7 days under sheeting; insulated blankets and heat below 40\u00b0F": { price: [0.1, 0.25], labor: 0.5, basis: "est", q: 3250 },
      "Concrete testing by an accredited lab: slump, air content and cylinder sets cast on site and broken at 7 and 28 days": { price: [800, 2500], labor: 0, fee: true, basis: "est", note: "lab field tests and cylinder breaks for 2-3 pours" },
      "Forms stripped, tie holes and honeycombing patched, footings and slab edges backfilled in compacted lifts": { price: [1.5, 3.5], labor: 0.85, basis: "est", q: 240 },
      "Penetrating siloxane sealer applied to exterior flatwork after 28 days of cure": { price: [0.6, 1.4], labor: 0.55, basis: "est" },
      "Final cleanup: form lumber and stakes removed, wash-out pit dug out and disposed of, site raked and swept": { price: [350, 1000], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "framing-contractor": {
    op: 0.2,
    opNote: "framing subcontractor to builders",
    benchmark: {
      unit: "sqft",
      measures: "building floor area framed (all floors)",
      price: [16, 30],
      typicalQty: [1800, 3200],
      jobQty: 2500,
      minJob: 5000,
      sources: ["HomeGuide 2026: frame a house $11-$30/sqft, labor and materials", "HomeGuide 2026: roof trusses $5-$14/sqft installed; wall framing $11-$32/linear ft", "HomeAdvisor 2025: framing $7-$16/sqft (older lumber prices)"],
    },
    steps: {
      "Layout: foundation checked for square, level and anchor-bolt placement; wall lines, openings and bearing points snapped on the slab or deck from the plans": { price: [400, 1000], labor: 0.95, basis: "est", q: 1 },
      "Engineered lumber and truss submittals: I-joist, beam and truss layouts reviewed against the plan, bearing points and hardware confirmed before the packages are ordered": { price: [250, 750], labor: 0.95, basis: "est", q: 1 },
      "Sill plates: pressure-treated 2x6 sills on foam sill seal, drilled to the anchor bolts and set with 3x3 plate washers and nuts": { price: [4.5, 8], labor: 0.55, basis: "derived", q: 144 },
      "Floor framing: 11-7/8 in. I-joists or 2x10 sawn joists at 16 in. o.c. with rim board, joist hangers at the girders, mid-span blocking and squash blocks under bearing walls": { price: [3.5, 5.5], labor: 0.35, basis: "derived", q: 2500, note: "I-joists; sawn 2x10 toward the low end" },
      "Beams, girders and posts: LVL, PSL or glulam beams and built-up or solid posts set to the plan on post bases and caps, bearing verified": { price: [250, 750], labor: 0.35, basis: "est", q: 10, note: "average of beams ($400-$1,200) and posts ($100-$300)" },
      "Subfloor: 3/4 in. tongue-and-groove OSB or plywood glued to the joists with subfloor adhesive and screwed or ring-shank nailed at 6 in. edge and 12 in. field": { price: [1.5, 2.4], labor: 0.4, basis: "derived", q: 2500 },
      "Exterior walls: 2x6 studs at 16 in. o.c. with double top plates, corners, jack and king studs, cripples and sills at the rough openings, built flat, raised plumb and braced": { price: [2.4, 4], labor: 0.55, basis: "derived", q: 2600, note: "per sqft of wall area" },
      "Interior partitions: 2x4 studs at 16 in. o.c. with plates, backers at intersections, door rough openings and 2x6 plumbing walls where the drawings call for them": { price: [12, 20], labor: 0.6, basis: "derived", q: 280, note: "8-9 ft partition; HomeGuide wall framing $11-$32/linear ft" },
      "Headers: LVL or built-up 2x10 and 2x12 headers with flat 2x fillers over each window and door opening, bearing on jack studs per the header schedule": { price: [60, 200], labor: 0.45, basis: "est", q: 28 },
      "Shear walls: rated panels nailed per the schedule (8d at 4 in. edge, 12 in. field), hold-downs on anchor bolts or threaded rods, straps and blocking at the panel edges": { price: [15, 40], labor: 0.55, basis: "est" },
      "Light-gauge steel framing: 20-ga studs at 16 in. o.c. in top and bottom track, screwed and bridged, with boxed headers": { price: [4.5, 9], labor: 0.55, basis: "est", note: "per sqft of wall" },
      "Wall sheathing: 7/16 in. OSB or 1/2 in. CDX plywood (or ZIP panels with taped seams) nailed 6 in. at edges and 12 in. in the field, edges blocked": { price: [0.9, 1.6], labor: 0.5, basis: "derived", q: 2600, note: "OSB; ZIP panels add about $0.70/sqft" },
      "Blocking and backing: fire blocking at draft openings and soffits, mid-height blocking, and backing for cabinets, grab bars, handrails and drywall edges": { price: [1.75, 3.5], labor: 0.7, basis: "est", q: 500 },
      "Roof framing: engineered trusses set at 24 in. o.c. with hurricane ties and permanent bracing per BCSI, or stick-framed rafters, ridge, valleys and collar ties": { price: [4.75, 7.75], labor: 0.35, basis: "src", q: 1600, note: "per sqft of roof area, trusses supplied and set" },
      "Crane or telehandler with operator for setting trusses, beams and wall panels": { price: [900, 2500], labor: 0, basis: "est", note: "crane with operator for one truss and beam set day" },
      "Roof sheathing: 5/8 in. or 1/2 in. OSB or CDX with H-clips at the unsupported edges, nailed 6 in. at edges and 12 in. in the field": { price: [1.1, 1.9], labor: 0.5, basis: "derived", q: 1600 },
      "Structural hardware: joist hangers, hurricane ties, straps, post bases and caps per the plan hardware schedule, fastened with the specified nails": { price: [6, 18], labor: 0.5, basis: "est", q: 130 },
      "Stairs: rough stringers cut from 2x12, treads and risers, landings framed and headed off": { price: [700, 1800], labor: 0.65, basis: "est", note: "per flight" },
      "Windows and exterior doors set plumb, level and square in the rough openings, shimmed and fastened to the manufacturer's instructions": { price: [80, 220], labor: 0.9, basis: "est", note: "setting labor; windows and doors supplied by others" },
      "Temporary bracing and weather protection: wall braces, guardrails at openings and edges, tarps over open floors and roof between stages": { price: [700, 2000], labor: 0.7, basis: "est", q: 1, note: "grows with floor area and stories" },
      "Framing inspection: walk-through with the inspector, engineer's field corrections and the punch list closed out": { price: [300, 900], labor: 0.9, basis: "est", q: 1 },
      "Cleanup: cutoffs and packaging to the dumpster, floors swept and nails pulled, dumpster and haul fees": { price: [800, 1800], labor: 0.4, basis: "est", q: 1, note: "includes a 30-yard dumpster; grows with house size" },
    },
  },
  "masonry": {
    op: 0.2,
    opNote: "masonry subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "masonry wall face area laid (block plus veneer)",
      price: [18, 32],
      typicalQty: [800, 2500],
      jobQty: 1650,
      minJob: 2500,
      sources: ["Homewyse 2026: concrete block wall $15.11-$19.61/sqft basic install", "NEDES 2026: cinder block wall $15-$35/sqft installed", "Homewyse 2026: brick veneer $14.99-$24.05/sqft installed"],
    },
    steps: {
      "Layout and coursing: wall lines and corners set from the plans, brick ledge and footing checked for level, coursing rods made so bed joints land at heads and sills": { price: [400, 1200], labor: 0.95, basis: "est", q: 1 },
      "Mortar station and stocking: mixer, mortar tubs, sand and cement delivered; masonry units stacked at the wall or on the scaffold by forklift": { price: [800, 2500], labor: 0.4, basis: "est", q: 1, note: "forklift and mixer for the job; grows with wall area" },
      "Frame scaffold with planks, guardrails, toe boards and ladder access set up, raised as the wall goes up and taken down": { price: [1500, 5000], labor: 0.5, basis: "est", note: "rental plus erect and strike; scales with wall length and height" },
      "Existing masonry removed: brick, block or stone cut out, salvageable units cleaned for reuse, debris to a dumpster": { price: [6, 14], labor: 0.75, basis: "est" },
      "CMU walls: 8 in. or 12 in. hollow block (ASTM C90) laid in running bond in Type S mortar, joints tooled concave, 9-ga ladder joint reinforcement every 16 in.": { price: [13, 22], labor: 0.65, basis: "src", q: 950, note: "block laid with ladder wire; rebar and grout are their own lines" },
      "Vertical reinforcing: #5 bars in the cells at 32-48 in. o.c. and each side of openings, lapped to the footing dowels, cells cleaned out at the base": { price: [2.25, 4.25], labor: 0.55, basis: "derived", q: 400 },
      "Grout: 2,000-psi coarse grout placed in the reinforced cells and bond beams in lifts, consolidated by vibrator, with cleanouts at high lifts": { price: [400, 750], labor: 0.5, basis: "derived", q: 5 },
      "Bond beams and lintels: bond-beam block with two #5 bars at floor and top-of-wall, precast or steel-angle lintels over each opening with 8 in. bearing": { price: [150, 500], labor: 0.5, basis: "est", q: 8, note: "per lintel or bond-beam run" },
      "Brick veneer: modular clay brick (ASTM C216 Grade SW) in running bond, Type N mortar, 1 in. air space, adjustable ties at 16 in. o.c. each way, weeps at 24 in. above the flashing": { price: [14, 24], labor: 0.6, basis: "src", q: 700 },
      "Through-wall flashing at the base, heads and sills: flexible membrane or stainless with a drip edge and end dams, lapped over the weep course": { price: [6, 14], labor: 0.55, basis: "est", q: 120 },
      "Stone veneer: natural or manufactured stone (adhered over lath and scratch coat, or anchored) set in a mortar bed, joints raked or grouted": { price: [18, 32], labor: 0.55, basis: "est", note: "manufactured or thin natural stone; full-bed natural stone runs higher" },
      "Sills, caps and copings: precast, cast-stone or limestone units set in mortar with a drip and washed joints": { price: [35, 75], labor: 0.45, basis: "est", q: 40 },
      "Control and expansion joints: vertical control joints in CMU at 25 ft o.c. and at openings, expansion joints in brick with backer rod and sealant": { price: [5, 11], labor: 0.7, basis: "est", q: 110 },
      "Repointing for restoration: deteriorated joints ground out 3/4 in. deep, dampened and repointed in lifts with a mortar matched to the original in color and strength": { price: [8, 18], labor: 0.9, basis: "est" },
      "Cold- and hot-weather protection: walls covered at the end of each day, heated enclosures or admixtures below 40\u00b0F, damp curing above 100\u00b0F": { price: [800, 3000], labor: 0.4, basis: "est", note: "grows with the number of cold days" },
      "Cleaning: new masonry washed with a masonry detergent approved by the brick manufacturer, pre-wetted and rinsed, mortar smears removed": { price: [0.5, 1.25], labor: 0.85, basis: "est", q: 1650 },
      "Water repellent: penetrating siloxane sealer applied to the finished wall after cleaning": { price: [0.75, 1.75], labor: 0.6, basis: "est" },
      "Cleanup and demobilization: scaffold struck, mixer washed out, broken units and mortar waste hauled away": { price: [500, 1500], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "excavation-grading": {
    op: 0.18,
    opNote: "private site-work subcontractor",
    benchmark: {
      unit: "cu yards",
      measures: "earthwork cut (bank cu yards), whole site package",
      price: [20, 50],
      typicalQty: [1000, 5000],
      jobQty: 3000,
      minJob: 2500,
      sources: ["HomeGuide 2026: excavation $2.50-$15/cu yard digging only; grading $0.40-$2.00/sqft", "WisDOT 2025 average bids: common excavation $8.65-$14.47/cu yard, borrow $7.39-$9.11/cu yard", "Angi 2026: cut-and-fill excavation $60-$200/cu yard on small residential jobs"],
    },
    steps: {
      "Utility locate (811 one-call ticket) and a private-utility scan of the work area, marks maintained through the job": { price: [500, 1500], labor: 0.9, basis: "est", q: 1, note: "811 is free; this is the private locator" },
      "Grading permit, stormwater (SWPPP or erosion-control) permit and inspections, with the fees": { price: [800, 3500], labor: 0, fee: true, basis: "est", q: 1, note: "grading permit plus state stormwater NOI; grading fees scale with cu yards" },
      "Construction staking: cut and fill stakes, grade stakes and offsets set by the surveyor; GPS machine-control model built from the grading plan": { price: [2000, 5500], labor: 0.85, basis: "est", q: 1, note: "grows with site area" },
      "Mobilization: excavator, dozer, wheel loader, vibratory roller and water truck delivered by lowboy, fuel and service on site": { price: [2500, 7500], labor: 0.3, basis: "est", q: 1, note: "lowboy moves for 4-5 machines" },
      "Silt fence, fiber rolls and inlet protection installed at the downhill limits and around stockpiles": { price: [2.25, 4.5], labor: 0.55, basis: "derived", q: 800, note: "WisDOT 2025 silt fence $1.99-$2.15/linear ft on large public jobs" },
      "Stabilized construction entrance: 50 ft rock pad of 3-6 in. stone over geotextile at the site access": { price: [1500, 3500], labor: 0.35, basis: "derived", q: 1 },
      "Clearing and grubbing: brush, trees under 6 in., stumps and roots removed and chipped or hauled": { price: [0.1, 0.35], labor: 0.35, basis: "derived", note: "WisDOT 2025 clearing plus grubbing about $7,000/acre" },
      "Topsoil stripped 6-12 in. and stockpiled on site for reuse": { price: [3.5, 8], labor: 0.35, basis: "derived", q: 900 },
      "Mass excavation: cut to design subgrade with GPS-guided excavator and dozer, material stockpiled or loaded out": { price: [6, 14], labor: 0.35, basis: "src", q: 3000 },
      "Rock excavation: hoe-ram breaking or drilling and blasting of rock above subgrade": { price: [45, 125], labor: 0.35, basis: "src", note: "hoe-ram; blasting and hard ledge run higher" },
      "Haul-off of excess cut to a licensed fill site or recycler, including trucking and dump fees": { price: [15, 38], labor: 0.25, basis: "est", note: "trucking under about 15 miles plus tipping fees" },
      "Imported structural fill: clean granular or select fill delivered from an approved pit": { price: [18, 40], labor: 0.1, basis: "derived", note: "delivered material only; placing is its own line" },
      "Fill placed and compacted in 8 in. lifts to 95% Modified Proctor (ASTM D1557), moisture-conditioned to the geotech's window": { price: [4.5, 10], labor: 0.35, basis: "derived", q: 2000 },
      "Compaction testing: nuclear density tests by the geotechnical lab at each lift and at subgrade": { price: [35, 75], labor: 0, fee: true, basis: "est", q: 40, note: "per nuclear density test billed by the lab" },
      "Building-pad and subgrade fine grading to plus or minus 0.1 ft, proof-rolled with a loaded truck, soft spots removed and replaced": { price: [0.2, 0.55], labor: 0.4, basis: "derived", q: 25000 },
      "Utility trenching to laser grade at the stated depth, spoils windrowed, trench box or benching in trenches deeper than 5 ft": { price: [12, 35], labor: 0.4, basis: "derived", note: "repo utility bid data: trench and backfill 0-5 ft $15-$40/linear ft" },
      "Dewatering: sump pumps or well points with a settling tank and discharge control": { price: [2500, 12000], labor: 0.2, basis: "derived", note: "repo utility bid data: $300-$2,500 per day; typical 5-10 days" },
      "Water truck for dust control on haul roads and open cuts": { price: [90, 150], labor: 0.35, basis: "est", q: 40 },
      "Slope stabilization: hydroseed or straw and tackifier on cut and fill slopes as they are finished": { price: [0.08, 0.22], labor: 0.4, basis: "est" },
      "Final grading and topsoil respread to finished grade, drainage swales shaped to the plan": { price: [0.25, 0.65], labor: 0.4, basis: "derived", q: 30000 },
      "Demobilization: equipment hauled off, erosion controls removed after the site is stabilized, entrance rock left in place": { price: [1500, 4500], labor: 0.35, basis: "est", q: 1 },
    },
  },
  "foundation-retaining": {
    op: 0.25,
    opNote: "residential and light-commercial concrete specialty",
    benchmark: {
      unit: "linear ft",
      measures: "wall length, 4-6 ft cast-in-place wall with its footing",
      price: [240, 450],
      typicalQty: [60, 200],
      jobQty: 120,
      minJob: 5000,
      sources: ["HomeAdvisor 2025: poured concrete retaining wall $60-$270/linear ft (3-6 ft) plus $30-$100/linear ft for footings", "WisDOT 2025 average bids: concrete masonry retaining walls $1,238/cu yard (FY2024), rebar $1.36/lb", "Angi 2026: stem walls about $45-$55/linear ft on top of the slab price"],
    },
    steps: {
      "Layout: footing and wall lines, corners and elevations set from the plans with a transit or laser, batter boards and offsets pinned": { price: [350, 1000], labor: 0.95, basis: "est", q: 1 },
      "Engineering and permit: stamped design for retaining walls over 4 ft or surcharged walls, building permit and the footing and wall inspections": { price: [1000, 4000], labor: 0, fee: true, basis: "est", q: 1, note: "stamped wall design plus permit, passed through; grows with wall height" },
      "Utility locate (811) and a private scan along the footing line before digging": { price: [200, 700], labor: 0.9, basis: "est", q: 1 },
      "Excavation for the footings and walls with working room, spoils stockpiled, banks benched or shored per OSHA; existing wall or slab cut back where needed": { price: [25, 55], labor: 0.45, basis: "derived", q: 120 },
      "Footing subgrade leveled, compacted and checked for the design bearing; over-dig replaced with compacted crushed stone": { price: [0.75, 1.75], labor: 0.7, basis: "est", q: 300 },
      "Footings: 2x forms set to line and grade, continuous #5 bars (three, top and bottom where drawn), corner bars and vertical dowels at the wall spacing, 3,000-psi concrete": { price: [35, 60], labor: 0.45, basis: "derived", q: 120, note: "24-30 in. footing including its concrete" },
      "Cast-in-place walls: two-sided panel forms with snap ties, #5 verticals at 12-16 in. o.c. and #4 horizontals at 12 in. o.c., keyway and step-downs formed, forms stripped and tie holes patched": { price: [80, 135], labor: 0.65, basis: "derived", q: 120, note: "forms and rebar for a 4-6 ft wall, about $20/sqft of wall face; wall concrete is its own line" },
      "Anchor bolts, hold-downs, beam pockets, sleeves and embeds set to the plan before the wall pour": { price: [15, 40], labor: 0.6, basis: "est", q: 20 },
      "Concrete pump with operator for the footing and wall placements": { price: [1300, 3500], labor: 0, basis: "src", note: "boom pump $1,300-$2,800 per pour day; footing and wall are usually two pours" },
      "Wall concrete: 4,000-psi placed in 2-4 ft lifts and vibrated, top struck to elevation, cured 7 days before backfill": { price: [250, 330], labor: 0.2, basis: "derived", q: 16 },
      "Segmental block retaining wall: units on a 6 in. compacted crushed base, first course leveled, geogrid layers at the design spacing, 12 in. of drainage stone behind the face, caps glued": { price: [25, 50], labor: 0.5, basis: "est", note: "per sqft of wall face" },
      "CMU stem wall: 8 in. block (ASTM C90) on the footing, cells with #5 bars grouted solid, bond beam at the top with anchor bolts": { price: [50, 90], labor: 0.6, basis: "derived", note: "2-3 ft stem wall" },
      "Underpinning: sequential 3-4 ft pits under the existing footing, dry-packed to bearing, or push piers with brackets driven to refusal": { price: [1500, 3500], labor: 0.55, basis: "derived", note: "HomeGuide 2026 pier installation $2,000-$4,000 per pier" },
      "Waterproofing: fluid-applied membrane at 60 mil dry (or peel-and-stick sheet) on the earth side of the wall, with dimple drainage board or protection board": { price: [4, 8], labor: 0.5, basis: "est" },
      "Damp-proofing: asphalt emulsion sprayed on the earth side of the stem wall": { price: [0.75, 1.75], labor: 0.55, basis: "est" },
      "Footing drain: 4 in. perforated PVC or corrugated HDPE in washed stone wrapped in filter fabric, run to daylight or a sump": { price: [12, 22], labor: 0.45, basis: "derived", q: 130 },
      "Backfill: free-draining gravel against the wall, then native or imported fill compacted in 12 in. lifts, held off the wall until the concrete has cured": { price: [22, 45], labor: 0.4, basis: "derived", q: 100, note: "blend of drain gravel against the wall and compacted native" },
      "Excess spoils hauled to a licensed fill site, including trucking and dump fees": { price: [20, 45], labor: 0.25, basis: "est" },
      "Inspections: footing and reinforcing inspection before each pour, special inspection of reinforcing and concrete where the engineer requires it": { price: [250, 1000], labor: 0.8, basis: "est", q: 1, note: "crew time for inspections; special inspection by the owner's agency is extra" },
      "Cleanup and demobilization: forms and ties hauled off, wash-out removed, disturbed grade raked": { price: [350, 1000], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "structural-steel": {
    op: 0.18,
    opNote: "commercial steel fabricator-erector",
    benchmark: {
      unit: "sqft",
      measures: "building floor area framed in steel (about 6-10 lb of steel per sqft)",
      price: [15, 30],
      typicalQty: [4000, 15000],
      jobQty: 9500,
      minJob: 15000,
      sources: ["SteelFlo 2026: moderately complex structural steel $4,000-$6,500/ton installed", "SteelFlo 2026: fabricated and erected $2,100-$4,000+/ton; W-shapes $1,100-$1,400/ton from service centers", "SteelFlo 2026: erection labor $300-$700/ton; shop drawings $100-$300/ton"],
    },
    steps: {
      "Shop drawings and erection drawings: connection design by the fabricator's engineer, piece marks and bolt lists, submitted for the engineer of record's review": { price: [6000, 18000], labor: 0.9, basis: "derived", q: 1, note: "about $150-$450 per ton of steel; scales with tonnage and connection count" },
      "Anchor-bolt survey: column lines, bolt projections and base-plate elevations checked against the plan before fabrication is released": { price: [800, 2000], labor: 0.9, basis: "est", q: 1 },
      "Material: A992 wide-flange, A500 Gr. B HSS, A36 plate and angle, A325 or A490 bolts, with mill certifications, per piece with the weight stated": { price: [450, 750], labor: 0, basis: "derived", q: 110, note: "average piece about 0.35 ton; $1,300-$2,100 per ton of the stated weight" },
      "Shop fabrication: members cut to length, coped, drilled and punched, stiffeners and connection plates welded to AWS D1.1, fit-up checked": { price: [350, 750], labor: 0.7, basis: "derived", q: 110, note: "average piece about 0.35 ton; $1,000-$2,100 per ton" },
      "Shop coating: SSPC-SP6 blast and shop primer (or hot-dip galvanizing to ASTM A123 for exterior steel)": { price: [0.6, 1.6], labor: 0.5, basis: "derived", q: 9500, note: "per sqft of steel surface (about 250 sqft per ton); galvanizing about 2-3x" },
      "Delivery: flatbed loads sequenced to the erection plan, unloaded and shaken out at the site": { price: [2000, 6000], labor: 0.2, basis: "derived", q: 1, note: "2-4 flatbed loads; SteelFlo freight $80-$200/ton" },
      "Hydraulic crane with operator, rigger and rigging, sized for the heaviest pick and the reach, day rate": { price: [6000, 16000], labor: 0.15, basis: "est", q: 1, note: "day rate $1,600-$3,000 with operator; typical job 4-6 days" },
      "Erection: columns set on leveling nuts or shims, plumbed and temporarily guyed; beams and girders set and connected": { price: [150, 320], labor: 0.85, basis: "derived", q: 110, note: "per piece; crane and bolting are their own lines" },
      "Base plates grouted with non-shrink grout after the frame is plumbed and bolted": { price: [90, 220], labor: 0.6, basis: "est", q: 24 },
      "Bolted connections: A325 bolts installed snug-tight or pretensioned by turn-of-nut or tension-control bolts per the connection schedule": { price: [30, 80], labor: 0.85, basis: "est", q: 220, note: "per connection of 4-8 bolts" },
      "Field welding: moment connections and CJP welds by AWS-certified welders with preheat, backing bars and weld access holes per the drawings": { price: [300, 900], labor: 0.8, basis: "est", note: "per moment connection or CJP joint" },
      "Metal deck: 1-1/2 in. 20-ga galvanized composite or roof deck, puddle-welded or screwed at 12 in. o.c., side laps fastened, pour stop and closures": { price: [3, 5.5], labor: 0.35, basis: "est" },
      "Shear studs: 3/4 in. x 4-7/8 in. headed studs welded through the deck at the spacing on the framing plan": { price: [3, 7], labor: 0.6, basis: "est" },
      "Miscellaneous metals: stair stringers and pans, ledger angles, embed plates, lintels, bollards and pipe supports": { price: [250, 1200], labor: 0.45, basis: "est", note: "average misc. item; stair sets run $3,000+" },
      "Special inspection coordination: third-party bolt and weld inspection, ultrasonic testing of CJP welds, inspection reports to the engineer": { price: [800, 3000], labor: 0.85, basis: "est", q: 1, note: "coordination and access only; the owner pays the inspection agency" },
      "Field touch-up: zinc-rich primer on field welds, bolt heads and damaged shop coating": { price: [800, 2500], labor: 0.75, basis: "est", q: 1 },
      "Safety: site-specific erection and fall-protection plan, perimeter cable, controlled decking zone, daily crane and rigging inspections": { price: [1500, 5000], labor: 0.6, basis: "est", q: 1 },
      "Cleanup and demobilization: shake-out area cleared, scrap and cribbing hauled, crane demobilized": { price: [800, 2500], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "concrete-flatwork": {
    op: 0.18,
    opNote: "commercial flatwork subcontractor, bid work",
    benchmark: {
      unit: "sqft",
      measures: "flatwork area placed (walks, drives, pads)",
      price: [9, 16],
      typicalQty: [1500, 6000],
      jobQty: 3750,
      minJob: 3500,
      sources: ["WisDOT 2025 average bids: concrete sidewalk 4 in. $7.63/sqft, 6 in. $12.43/sqft (base and excavation separate)", "WisDOT 2025 average bids: concrete driveway 6 in. $65.55/sq yard", "HomeGuide 2026: concrete driveway $6-$15/sqft installed"],
    },
    steps: {
      "Layout and grades: edges, flow lines and spot elevations set from the plan, slopes checked (cross slope under 2% on walks, 1/8 in. per ft minimum for drainage)": { price: [600, 1800], labor: 0.9, basis: "est", q: 1 },
      "Right-of-way or encroachment permit and inspection for public sidewalk, curb and driveway apron work": { price: [150, 800], labor: 0, fee: true, basis: "est", note: "right-of-way permit and inspection fee" },
      "Traffic and pedestrian control: signs, barricades, cones and a closed-walk detour": { price: [800, 3500], labor: 0.5, basis: "est", note: "signs and barricades for a short job; flaggers and longer closures run higher" },
      "Saw-cut, break out and haul away existing concrete or asphalt (thickness stated), rubble to a recycler": { price: [1.75, 4.5], labor: 0.5, basis: "derived", note: "WisDOT 2025 removing sidewalk $7.01/sq yard on large public jobs; HomeGuide $2-$6/sqft" },
      "Excavation to subgrade for the slab and base, spoils loaded and hauled": { price: [30, 60], labor: 0.4, basis: "derived", q: 100 },
      "Subgrade compacted to 95% and proof-rolled, soft spots dug out and replaced": { price: [0.25, 0.6], labor: 0.5, basis: "est", q: 3750 },
      "Aggregate base: 4 in. of 3/4-minus crushed stone (6 in. under heavy-duty pads) placed and compacted": { price: [55, 95], labor: 0.35, basis: "derived", q: 55, note: "WisDOT 2025 base aggregate dense 3/4 in. $22.56/ton on large public jobs" },
      "Forms: 2x4 and 2x6 lumber or steel forms set to line and grade, flexible forms at curves, pinned and braced": { price: [3.5, 7], labor: 0.7, basis: "derived", q: 950 },
      "Reinforcing: 6x6 W1.4xW1.4 welded wire on chairs or #4 bars at 18 in. o.c. each way; #5 at 12 in. o.c. in dumpster pads and truck aprons": { price: [0.7, 1.5], labor: 0.4, basis: "derived", q: 3750 },
      "Isolation joints: 1/2 in. expansion material against buildings, columns, curbs and existing slabs, with smooth dowels at truck-traffic joints": { price: [3, 8], labor: 0.55, basis: "est", q: 200 },
      "Concrete placed: 4,000-psi air-entrained mix at the stated thickness (4 in. walks, 6 in. drives, 8 in. heavy-duty pads), screeded and bull-floated": { price: [240, 320], labor: 0.2, basis: "derived", q: 61 },
      "Curb and gutter: machine-extruded or hand-formed 6 in. curb with 18-24 in. gutter, 3,500-psi concrete, expansion joints at 10 ft": { price: [30, 60], labor: 0.5, basis: "src" },
      "ADA curb ramps: ramps at 1:12 with flared sides, landings and cast-in-place detectable warning surfaces to the current PROWAG or state standard": { price: [2000, 4500], labor: 0.5, basis: "src", note: "per ramp with detectable warning panel" },
      "Finish: medium broom perpendicular to traffic, edges and joints tooled with a 1/4 in. radius": { price: [0.7, 1.4], labor: 0.85, basis: "derived", q: 3750 },
      "Control joints saw-cut to one-quarter of the slab depth at a spacing of 24-30 times the thickness, or tooled at the pour": { price: [0.9, 2], labor: 0.75, basis: "est", q: 700 },
      "Curing: membrane curing compound (ASTM C309) sprayed at the finish, insulated blankets below 40\u00b0F": { price: [0.1, 0.25], labor: 0.5, basis: "est", q: 3750 },
      "Concrete testing by the lab: slump, air and cylinder sets per the specification": { price: [600, 2000], labor: 0, fee: true, basis: "est", note: "lab tests for the job's pours" },
      "Forms stripped, edges backfilled and compacted, adjoining asphalt or landscape restored": { price: [2, 5], labor: 0.75, basis: "est", q: 950 },
      "Penetrating sealer applied after 28 days": { price: [0.45, 1.1], labor: 0.5, basis: "est" },
      "Cleanup: form material hauled off, wash-out removed, site swept and traffic control pulled": { price: [500, 1500], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "residential-concrete-flatwork": {
    op: 0.3,
    opNote: "residential specialty trade, small jobs",
    benchmark: {
      unit: "sqft",
      measures: "driveway, walk or patio area poured",
      price: [8, 14],
      typicalQty: [400, 1000],
      jobQty: 700,
      minJob: 2000,
      sources: ["HomeGuide 2026: concrete driveway $6-$15/sqft; standard gray $6-$10/sqft", "HomeGuide 2026: stamped driveway $8-$26/sqft; removing the old one adds $2-$6/sqft", "HomeGuide 2026: slab installer labor $3-$5/sqft"],
    },
    steps: {
      "Site walk and layout: driveway, walk or patio outline painted with the owner, slope set away from the house (1/4 in. per ft), downspouts, meters and door thresholds located": { price: [100, 400], labor: 0.95, basis: "est", q: 1 },
      "Utility locate (811) plus sprinkler heads, low-voltage lighting and drain lines flagged by hand": { price: [50, 200], labor: 1, basis: "est", q: 1, note: "811 is free; hand-flagging private lines" },
      "City driveway-approach or sidewalk permit and the inspection": { price: [75, 350], labor: 0, fee: true, basis: "est", note: "city driveway-approach or sidewalk permit fee" },
      "Break out, load and haul away the old driveway, walk or patio (thickness stated), including dump fees": { price: [2.25, 5.5], labor: 0.55, basis: "src", note: "4 in. unreinforced; includes dump fees" },
      "Protection: plywood over the lawn for the truck and skid steer, siding and doors masked from splatter, plants tied back": { price: [100, 400], labor: 0.6, basis: "est", q: 1 },
      "Excavate and grade the subgrade to depth, spoils hauled off": { price: [45, 90], labor: 0.45, basis: "derived", q: 10 },
      "Crushed-stone base: 4 in. of 3/4-minus placed and compacted with a plate compactor": { price: [70, 120], labor: 0.45, basis: "derived", q: 9, note: "installed and compacted; Estimators.us 2026 compacted base $0.80-$1.50/sqft" },
      "Forms: 2x4 and 2x6 lumber staked to line and grade, bender board at curves, thickened edge at the driveway": { price: [3.5, 7], labor: 0.7, basis: "derived", q: 100 },
      "Reinforcing: #3 bars at 24 in. o.c. each way on chairs (or 6x6 welded wire) with fiber in the mix": { price: [0.7, 1.3], labor: 0.45, basis: "derived", q: 700 },
      "Expansion joints: 1/2 in. fiber board against the house, garage slab, stoop and existing walks": { price: [1.5, 3.5], labor: 0.6, basis: "est", q: 30 },
      "Drainage: channel drain at the garage door or catch basin at the low spot, piped 4 in. to daylight or a dry well": { price: [45, 95], labor: 0.55, basis: "est" },
      "Concrete placed: 4,000-psi air-entrained mix, 4 in. at walks and patios and 5-6 in. at the driveway, screeded and floated": { price: [250, 350], labor: 0.25, basis: "derived", q: 10, note: "includes short-load fees on small pours" },
      "Finish: broom, or exposed aggregate washed with a surface retarder, edges tooled": { price: [0.8, 1.6], labor: 0.9, basis: "derived", q: 700 },
      "Decorative finish: integral color, release agent and stamped pattern, or hand-troweled borders": { price: [4, 9], labor: 0.7, basis: "derived", note: "added over the plain finish; HomeGuide stamped $8-$26/sqft all-in" },
      "Control joints tooled at the pour at 8-10 ft spacing (sawn on stamped work)": { price: [0.75, 2], labor: 0.85, basis: "est", q: 90 },
      "Curing compound sprayed at the finish; plastic and blankets in cold weather": { price: [0.1, 0.25], labor: 0.5, basis: "est", q: 700 },
      "Sealer: acrylic or penetrating sealer after 28 days (two coats on stamped or colored concrete)": { price: [0.75, 1.75], labor: 0.6, basis: "est", note: "two coats on stamped or colored work" },
      "Forms stripped, edges backfilled with topsoil and seeded, lawn ruts repaired": { price: [1.5, 4], labor: 0.75, basis: "est", q: 100 },
      "Cleanup: stakes and forms hauled, wash-out taken off site, driveway swept; keep-off tape until the concrete can take weight": { price: [150, 400], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "residential-foundation-repair": {
    op: 0.35,
    opNote: "residential specialty, sales and lifetime-warranty overhead",
    benchmark: {
      unit: "unit",
      measures: "piers installed (per pier, whole job)",
      price: [2000, 3500],
      typicalQty: [6, 14],
      jobQty: 10,
      minJob: 4500,
      sources: ["HomeGuide 2026: pier installation $2,000-$4,000 per pier; jobs $8,000-$30,000+", "Dalinghaus 2025: helical or push pier underpinning $2,000-$3,000 per pier location, about 10 per job", "FoundationQHub 2025: push piers $1,200-$3,000 per pier installed"],
    },
    steps: {
      "Foundation assessment: floor elevation survey with a manometer or Zip Level, crack mapping with photos, drainage and grading review, written repair plan": { price: [250, 750], labor: 0.9, basis: "est", q: 1, note: "many firms waive it when they get the job" },
      "Structural engineer's stamped repair plan and letter": { price: [500, 1500], labor: 0, fee: true, basis: "est", note: "engineer's letter and stamped plan, passed through" },
      "Building permit and the inspection, with the fees": { price: [150, 600], labor: 0, fee: true, basis: "est", q: 1, note: "city permit and inspection fee" },
      "Utility locate (811) and hand-probing at each pier location for drains, gas and sprinkler lines": { price: [150, 400], labor: 1, basis: "est", q: 1 },
      "Access pits: 3 x 3 ft pits hand-dug to the footing at each pier location, concrete or landscaping removed and set aside, flooring protected inside": { price: [150, 400], labor: 0.9, basis: "derived", q: 10, note: "per-location all-in $2,000-$3,000 (Dalinghaus 2025) less the pier" },
      "Push piers: 2-7/8 in. or 3-1/2 in. galvanized steel pier sections driven hydraulically to refusal on bedrock or load-bearing strata, foundation bracket bolted to the footing, load-tested": { price: [1200, 2200], labor: 0.5, basis: "src", q: 10 },
      "Helical piers: 2-7/8 in. shaft with 8/10/12 in. helix plates screwed to design torque, bracket set to the footing": { price: [1300, 2500], labor: 0.45, basis: "src", note: "Forbes/Today's Homeowner 2025: $900-$2,500 per helical pier" },
      "Synchronized hydraulic lift: the settled section raised toward original elevation, brackets locked and shimmed, lift stopped where cracking risk outweighs the gain": { price: [800, 2500], labor: 0.8, basis: "est", q: 1 },
      "Slab lifting: 5/8 in. injection holes drilled through the sunken slab, high-density polyurethane foam injected to lift and fill voids, holes patched": { price: [8, 20], labor: 0.5, basis: "src", note: "HomeGuide 2026 polyurethane foam jacking $8-$25/sqft" },
      "Crack injection: epoxy or polyurethane injected through surface ports into foundation wall cracks, ports removed and the face ground smooth": { price: [40, 90], labor: 0.65, basis: "est" },
      "Carbon-fiber straps: 12 in. wide straps epoxied to a bowing wall at 4 ft o.c. with top anchors": { price: [450, 900], labor: 0.5, basis: "derived", note: "HomeGuide 2026 carbon fiber $900-$2,000+ per crack (2-3 straps)" },
      "Wall anchors or steel I-beam braces: plate anchors set in the yard or beams bolted to the floor and joists at 5-6 ft o.c.": { price: [550, 1100], labor: 0.5, basis: "src", note: "HomeGuide 2026 wall anchors $500-$1,000 each" },
      "Drainage correction: downspout extensions, regrading against the house or an interior perimeter drain to a sump pump": { price: [30, 85], labor: 0.6, basis: "est" },
      "Pits backfilled and tamped, concrete patched, sod and landscaping put back": { price: [100, 300], labor: 0.8, basis: "derived", q: 10, note: "per pit; part of the per-location all-in price" },
      "Post-repair elevation survey and a report with before and after readings and pier depths": { price: [200, 500], labor: 1, basis: "est", q: 1 },
      "Warranty registration: transferable lifetime pier warranty and the annual monitoring visit": { price: [150, 500], labor: 0.3, basis: "est", q: 1 },
      "Final cleanup: interior floors cleaned, spoils hauled, walk-through with the owner": { price: [150, 450], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "house-lifting": {
    op: 0.3,
    opNote: "residential structural specialty, high risk",
    benchmark: {
      unit: "sqft",
      measures: "house footprint lifted (new foundation on its own line)",
      price: [20, 40],
      typicalQty: [1000, 2000],
      jobQty: 1400,
      minJob: 15000,
      sources: ["Fixr 2025: raising only $10-$35/sqft; with foundation work $14-$60/sqft", "HomeGuide 2026: raise a house $10,000-$40,000; lift and replace foundation $20,000-$100,000", "Fixr 2025: supporting $2-$4/sqft, jacking $3-$5/sqft, permit $4,000-$6,000"],
    },
    steps: {
      "Structural engineering: lift plan, needle-beam and main-beam design, new foundation design to the target elevation, stamped drawings": { price: [2000, 5000], labor: 0.9, basis: "derived", q: 1, note: "Fixr 2025 structural engineer $100-$500/hr" },
      "Permits: building permit, floodplain development permit and the FEMA elevation certificate before and after": { price: [1000, 3500], labor: 0, fee: true, basis: "derived", q: 1, note: "building and floodplain permits plus the pre-lift elevation certificate, passed through" },
      "Utility disconnects: electric meter pulled, gas capped at the meter, water and sewer cut and capped, HVAC lines and ducts detached": { price: [600, 2000], labor: 0.85, basis: "derived", q: 1, note: "electrician, plumber and HVAC tech; Fixr $40-$150/hr" },
      "Prep: porches, decks, steps, chimney bracing and interior contents secured or removed; fragile finishes photographed": { price: [700, 2500], labor: 0.85, basis: "est", q: 1 },
      "Beam pockets opened through the foundation wall or skirting for steel insertion": { price: [120, 350], labor: 0.85, basis: "est", q: 14 },
      "Steel: W12 to W18 main beams and cross needles inserted under the floor framing, shimmed tight to the joists, cribbing towers built under each beam end": { price: [500, 1100], labor: 0.6, basis: "derived", q: 8, note: "per main beam or needle with its cribbing; Fixr supporting $2-$4/sqft" },
      "Unified hydraulic jacking system: synchronized jacks under each beam, the house lifted in 8-12 in. increments and blocked at each stage": { price: [3000, 7000], labor: 0.6, basis: "derived", q: 1, note: "Fixr jacking $3-$5/sqft of footprint; scales with footprint and lift height" },
      "Temporary shoring at the lifted height: cribbing, cross-bracing and wind tie-downs, house held level while foundation work goes on": { price: [1200, 3500], labor: 0.5, basis: "est", q: 1, note: "grows with the weeks the house stays up" },
      "Old foundation demolished and hauled off (concrete, block or piers)": { price: [80, 180], labor: 0.55, basis: "est" },
      "New foundation: footings and stem walls, CMU piers or a full-height wall with reinforcing, anchor bolts and flood vents to the engineered height": { price: [140, 300], labor: 0.5, basis: "derived", note: "Fixr new stem-wall foundation $5-$16/sqft; taller flood walls toward the high end" },
      "House lowered onto the new foundation, sill plates and anchor bolts set and tightened, hold-downs connected": { price: [1500, 4000], labor: 0.75, basis: "est", q: 1 },
      "Steel and cribbing removed, beam pockets closed": { price: [800, 2500], labor: 0.75, basis: "est", q: 1 },
      "Utilities reconnected and extended to the new elevation: water, sewer, gas, electric, HVAC": { price: [2000, 6000], labor: 0.6, basis: "est", q: 1, note: "grows with lift height and the number of services" },
      "New stairs, landings and porch framing to the raised entries, with guardrails": { price: [1800, 4500], labor: 0.55, basis: "derived", q: 2, note: "per entry; Fixr stairs or ramp $1,500-$2,000 before landings and guards" },
      "Backfill, grading and settling of the site around the new foundation": { price: [30, 60], labor: 0.45, basis: "est", q: 40 },
      "Inspections and the final elevation certificate": { price: [500, 1500], labor: 0, fee: true, basis: "est", q: 1, note: "surveyor's final elevation certificate, passed through" },
      "Cleanup and demobilization: debris hauled, cribbing trucked off, walk-through with the owner": { price: [800, 2000], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "seismic-retrofit": {
    op: 0.3,
    opNote: "residential specialty trade, small jobs",
    benchmark: {
      unit: "sqft",
      measures: "house floor area over the crawl space",
      price: [3.5, 7],
      typicalQty: [1000, 2000],
      jobQty: 1500,
      minJob: 2500,
      sources: ["HomeGuide 2026: earthquake retrofit $3-$5/sqft; $3,000-$10,000 per house", "Fixr 2025: $3-$7/sqft; average $7,000 for bolting and cripple-wall bracing", "Custom Home 2026: Bay Area bolt-and-brace $3,000-$7,000"],
    },
    steps: {
      "Retrofit assessment: crawl-space inspection of the foundation type and condition, existing bolts, cripple-wall height and floor framing, photographed and written up": { price: [200, 500], labor: 0.95, basis: "src", q: 1, note: "Fixr 2025 seismic review $200-$500" },
      "Retrofit plan: prescriptive Standard Plan A or IEBC Chapter A3 plan set, or an engineer's stamped plan where the house does not fit the standard plan": { price: [300, 1200], labor: 0.9, basis: "est", q: 1, note: "prescriptive plan; an engineer's stamped plan runs $1,500-$4,000" },
      "Building permit and the rough and final inspections": { price: [200, 700], labor: 0, fee: true, basis: "est", q: 1, note: "city permit and inspection fee" },
      "Crawl-space access: hatch enlarged, debris cleared, ducts and wiring moved aside, vapor barrier and work lighting set": { price: [250, 750], labor: 0.9, basis: "est", q: 1 },
      "Foundation bolting: 5/8 in. anchor bolts at 4-6 ft o.c. drilled into the concrete, set in epoxy (Simpson SET-3G or equal) with 3 x 3 in. plate washers": { price: [60, 120], labor: 0.7, basis: "derived", q: 25, note: "HomeGuide 2026 mudsill anchoring $1,000-$2,500 per house" },
      "Foundation plates (Simpson UFP10 or equal) where there is no room to drill through the sill": { price: [90, 180], labor: 0.6, basis: "est" },
      "Cripple-wall bracing: 15/32 in. Structural I plywood nailed to the studs with 8d at 4 in. o.c. at edges, blocking at panel edges, ventilation holes cut": { price: [18, 36], labor: 0.7, basis: "derived", q: 64, note: "HomeGuide 2026 cripple-wall bracing $1,000-$3,000 per house" },
      "Framing anchors: Simpson L90 or A35 clips connecting the floor joists and rim to the cripple-wall top plate": { price: [10, 22], labor: 0.75, basis: "est", q: 40 },
      "Hold-downs: HDU hold-downs on threaded rods epoxied into the foundation at the ends of braced wall lines": { price: [250, 500], labor: 0.65, basis: "est" },
      "Post-to-beam and post-to-pier connections: post caps, bases and straps at interior piers and girders": { price: [35, 85], labor: 0.7, basis: "est", q: 10 },
      "Water heater strapped with a seismic bracing kit at the upper and lower third": { price: [175, 400], labor: 0.6, basis: "src", q: 1, note: "Fixr 2025 water heater bracing $250-$400" },
      "Automatic seismic gas shutoff valve at the meter": { price: [250, 550], labor: 0.5, basis: "src", note: "Fixr 2025 gas shutoff valve $200-$500" },
      "Chimney bracing or removal of the unreinforced masonry above the roofline": { price: [2500, 7500], labor: 0.7, basis: "src", note: "Fixr 2025 chimney reinforcement $2,000-$8,000" },
      "Soft-story steel moment frame or shear walls at the garage or ground-floor opening": { price: [12000, 30000], labor: 0.5, basis: "est", note: "per frame or braced opening" },
      "Inspections walked with the inspector, corrections closed out": { price: [150, 500], labor: 0.95, basis: "est", q: 1 },
      "Cleanup: crawl-space debris hauled, vents and hatch restored, retrofit documentation and photos for the insurer or Earthquake Brace + Bolt program": { price: [200, 600], labor: 0.85, basis: "est", q: 1 },
    },
  },
};
