// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "land-development-analysis": {
    op: 0.2,
    opNote: "land planning / civil consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one parcel analysis with 2-3 development scenarios",
      price: [12000, 35000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 5000,
      sources: ["OGS Capital 2026: pre-feasibility / initial screening study $5,000-$15,000; consultants $150-$500/hr", "OGS Capital 2026: standard feasibility study $15,000-$50,000; real estate development $20,000-$75,000+; consultants $150-$500/hr"],
    },
    steps: {
      "Kickoff meeting and data request: client objectives, target product, acquisition terms, prior reports, survey and title commitment collected": { price: [150, 225], labor: 1, basis: "derived", q: 3, note: "principal/PM blended rate" },
      "Site reconnaissance: walk the parcel, photograph frontage, access, drainage patterns, existing structures and neighboring uses; note visible wetlands, slopes and utilities": { price: [120, 175], labor: 0.95, basis: "derived", q: 6, note: "planner rate incl. travel time" },
      "Records research: county assessor, recorded plat and deed, title exceptions and easements, FEMA flood map, NWI wetlands, NRCS soils, GIS parcel data and aerial history": { price: [600, 1500], labor: 0.9, basis: "est", q: 1 },
      "Zoning and comprehensive-plan review memo: district, permitted uses, density, setbacks, height, parking, overlay districts and the approval path the intended use triggers": { price: [1000, 2500], labor: 1, basis: "est", q: 1 },
      "Site constraints exhibit: net developable acreage after floodplain, wetland buffers, steep slopes, easements and required open space, drawn over the survey or GIS base": { price: [1200, 3500], labor: 1, basis: "derived", q: 1, note: "10-25 hrs GIS/CAD and planner" },
      "Conceptual yield plan per scenario: lot or unit layout with road network, stormwater pond footprint and open space, yield stated for each scenario": { price: [1500, 4000], labor: 1, basis: "derived", q: 2, note: "per scenario; 12-25 hrs each" },
      "Infrastructure and utility assessment: sewer and water availability or will-serve inquiries, capacity, offsite extension routes, storm outfall, roadway access and turn-lane triggers": { price: [1200, 3500], labor: 1, basis: "derived", q: 1 },
      "Preliminary site development cost opinion by scenario: clearing, grading, roads, utilities, stormwater, offsite extensions, impact and connection fees": { price: [1500, 4000], labor: 1, basis: "derived", q: 1, note: "all scenarios" },
      "Market and absorption inputs: comparable lot or unit pricing, absorption pace and competing supply in the submarket": { price: [800, 2500], labor: 0.85, basis: "est", q: 1 },
      "Development pro forma per scenario: land basis, hard and soft costs, financing, revenue by phase, residual land value, unleveraged IRR and equity multiple with a sensitivity table": { price: [1000, 2500], labor: 1, basis: "derived", q: 2, note: "per scenario" },
      "Land development analysis report: constraints, yield, cost, pro forma and a go/no-go recommendation with the risks that move the number": { price: [1200, 3500], labor: 1, basis: "derived", q: 1 },
      "Presentation of findings to the client, partners or investment committee": { price: [175, 250], labor: 1, basis: "derived", q: 3 },
      "Pre-application meeting with the planning department to confirm the approval path and known issues before closing": { price: [150, 225], labor: 1, basis: "derived" },
      "Revisions to the yield plan or pro forma for a changed program, pricing or acquisition terms": { price: [125, 185], labor: 1, basis: "derived", q: 6 },
      "Reimbursables: GIS data, recorded document copies, title and survey copies, printing and mileage": { price: [200, 750], labor: 0.05, basis: "est", q: 1, note: "billed near cost" },
    },
  },
  "feasibility-study": {
    op: 0.2,
    opNote: "real estate consulting firm, hourly-rate professional services",
    benchmark: {
      unit: "fixed",
      measures: "one development feasibility study, 2 scenarios",
      price: [18000, 55000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 7500,
      sources: ["OGS Capital 2026: standard feasibility study $15,000-$50,000; real estate development $20,000-$75,000+; consultants $150-$500/hr", "Vertex 2018: market feasibility study $6,000-$15,000 per project (California, market portion only)"],
    },
    steps: {
      "Kickoff workshop: project objectives, decision criteria, scenarios to test, data the client already holds and the study schedule": { price: [175, 250], labor: 1, basis: "derived", q: 4 },
      "Site and regulatory screening: location, access, zoning fit, utility availability, environmental flags and the approvals each scenario would need": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Market analysis: trade-area definition, demographics and employment, competitive supply inventory, rent or sales comparables, absorption history and the development pipeline": { price: [4000, 10000], labor: 0.9, basis: "derived", q: 1, note: "30-60 hrs; data subscriptions in reimbursables" },
      "Demand estimate and positioning: capture rate, target segment, unit mix or program size and a pricing recommendation": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Development program per scenario: massing, unit count or square footage, parking and phasing for each alternative studied": { price: [1200, 3000], labor: 1, basis: "derived", q: 2, note: "per scenario" },
      "Order-of-magnitude cost estimate per scenario: hard costs by building system, site work, soft costs, fees, contingency and escalation to the construction midpoint": { price: [1200, 3500], labor: 1, basis: "derived", q: 2, note: "per scenario" },
      "Operating and financial projections per scenario: 10-year cash flow, stabilized NOI, debt sizing and returns (IRR, cash-on-cash, DSCR)": { price: [1500, 4000], labor: 1, basis: "derived", q: 2, note: "per scenario" },
      "Sensitivity and break-even analysis: rent, cost, cap rate and absorption ranges, and the threshold at which the project stops working": { price: [1200, 3000], labor: 1, basis: "est", q: 1 },
      "Feasibility report: findings, scenario comparison matrix, recommendation and the assumptions register": { price: [2000, 5000], labor: 1, basis: "derived", q: 1 },
      "Executive summary and lender or investor package version of the report": { price: [1500, 4000], labor: 1, basis: "est" },
      "Interviews with brokers, lenders, operators and local officials to test the market findings": { price: [150, 225], labor: 1, basis: "src", q: 8 },
      "Presentation of findings to the client, board or lender, with questions taken": { price: [175, 275], labor: 1, basis: "src", q: 4 },
      "Revisions for a changed program, an added scenario or updated assumptions after the draft": { price: [135, 195], labor: 1, basis: "derived", q: 8 },
      "Reimbursables: market data subscriptions, demographic reports, travel and printing": { price: [500, 2000], labor: 0.05, basis: "est", q: 1, note: "market data and demographic reports at cost" },
    },
  },
  "highest-best-use": {
    op: 0.2,
    opNote: "appraisal / valuation consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one HBU analysis testing 3 candidate uses",
      price: [8000, 25000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 3500,
      sources: ["OGS Capital 2026: pre-feasibility / initial screening study $5,000-$15,000; consultants $150-$500/hr", "Archiwise 2025: land-use / zoning consultants $150-$350/hr; California zoning consultant fees $20,000-$100,000+ on complex projects"],
    },
    steps: {
      "Engagement kickoff: intended use of the analysis, effective date, property rights considered, candidate uses the client wants tested and records collected": { price: [175, 275], labor: 1, basis: "derived", q: 2 },
      "Property inspection: site size and shape, frontage, topography, access, visibility, improvements and their condition, surrounding uses photographed": { price: [150, 225], labor: 0.95, basis: "derived", q: 3 },
      "Legal permissibility test: zoning district and permitted uses, overlays, deed restrictions and covenants, easements, and the realistic path for a use that needs a change": { price: [600, 1500], labor: 1, basis: "est", q: 1 },
      "Physical possibility test: usable area after setbacks and easements, soils and drainage flags, utility availability and the building footprint each use requires": { price: [600, 1500], labor: 1, basis: "est", q: 1 },
      "Market study per candidate use: supply, demand, rents or sale prices, absorption and vacancy in the competitive area": { price: [1000, 2500], labor: 0.9, basis: "derived", q: 3, note: "per candidate use; 7-15 hrs incl. data" },
      "Financial feasibility test per candidate use: development cost, stabilized value or sale proceeds, and residual land value at the returns the market requires": { price: [800, 2000], labor: 1, basis: "derived", q: 3, note: "per candidate use" },
      "Maximally productive conclusion: ranked uses, timing (develop now, hold or interim use) and the ideal improvement described": { price: [600, 1500], labor: 1, basis: "est", q: 1 },
      "As-improved analysis: whether the existing improvements contribute value, renovation versus demolition, and the interim use conclusion": { price: [1000, 2500], labor: 1, basis: "est" },
      "Highest and best use report: four-test narrative, exhibits, market data and the conclusion, USPAP-compliant where written by a certified appraiser": { price: [1500, 3500], labor: 1, basis: "derived", q: 1, note: "USPAP narrative report" },
      "Review of the draft with the client and their counsel or lender": { price: [175, 275], labor: 1, basis: "derived", q: 3 },
      "Deposition or testimony support in litigation, condemnation or an assessment appeal": { price: [300, 450], labor: 1, basis: "derived", note: "expert testimony rate, retainer typical" },
      "Revisions for a changed effective date, an added candidate use or new market evidence": { price: [150, 225], labor: 1, basis: "derived", q: 3 },
      "Reimbursables: comparable data services, public records, travel and printing": { price: [200, 800], labor: 0.05, basis: "est", q: 1, note: "comp data services and records at cost" },
    },
  },
  "zoning-code-analysis": {
    op: 0.2,
    opNote: "planning / code consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one parcel zoning and building-code analysis for a proposed use",
      price: [4000, 14000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 1500,
      sources: ["Archiwise 2025: land-use / zoning consultants $150-$350/hr; California zoning consultant fees $20,000-$100,000+ on complex projects", "City of Pittsburgh fee schedule 2026: ZBA variance $400, zone change petition $1,500, posted notice $450, property certification $100"],
    },
    steps: {
      "Kickoff: proposed use and program, site survey, existing plans and any prior approvals or open violations collected": { price: [150, 225], labor: 1, basis: "derived", q: 2 },
      "Zoning verification: district map, ordinance text, overlay districts, pending amendments, and a zoning verification letter requested from the municipality": { price: [500, 1200], labor: 0.9, basis: "derived", q: 1, note: "letter fee itself in reimbursables" },
      "Records pull: prior certificates of occupancy, variances, special permits, site plan approvals, open violations and recorded conditions on the parcel": { price: [400, 1000], labor: 0.9, basis: "est", q: 1 },
      "Zoning compliance matrix: permitted and conditional uses, lot area and width, setbacks, height, FAR, lot coverage, open space, parking and loading counts, landscaping and signage against the proposed program": { price: [1200, 3000], labor: 1, basis: "derived", q: 1, note: "8-18 hrs" },
      "Setback and buildable envelope diagram drawn over the survey: required yards, height planes, easements and the proposed footprint": { price: [800, 2200], labor: 1, basis: "derived", q: 1 },
      "Building code analysis: occupancy classification, construction type, allowable height and area, fire separation, egress, sprinklers and accessibility under the adopted IBC or IRC edition and local amendments": { price: [1500, 4000], labor: 1, basis: "derived", q: 1, note: "architect / code consultant 10-20 hrs" },
      "Nonconformity and change-of-use review: legal nonconforming rights, expansion limits and the triggers a change of occupancy sets off": { price: [800, 2000], labor: 1, basis: "est" },
      "Approvals memo: every discretionary and ministerial approval the program needs, the deciding body, notice requirements and estimated timeline": { price: [800, 2000], labor: 1, basis: "derived", q: 1 },
      "Variance and special-permit exposure: each standard not met, the findings the board must make and the strength of the case": { price: [600, 1500], labor: 1, basis: "est" },
      "Pre-application meeting with planning and building officials to confirm the interpretation": { price: [150, 225], labor: 1, basis: "derived", q: 3 },
      "Written code interpretation or determination request to the zoning administrator or building official": { price: [600, 1500], labor: 1, basis: "est", note: "plus any determination fee the city charges" },
      "Revisions to the matrix and memo for a revised program or footprint": { price: [125, 185], labor: 1, basis: "derived", q: 4 },
      "Reimbursables: municipal document fees, zoning verification letter fee, records copies and mileage": { price: [100, 500], labor: 0, fee: true, basis: "src", q: 1, note: "zoning letter / certification ~$100 plus records copies, at cost" },
    },
  },
  "far-density-study": {
    op: 0.2,
    opNote: "architect / planner billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one parcel FAR and density study, 3 massing scenarios",
      price: [8000, 28000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 3500,
      sources: ["OGS Capital 2026: pre-feasibility / initial screening study $5,000-$15,000; consultants $150-$500/hr", "Archiwise 2025: land-use / zoning consultants $150-$350/hr; California zoning consultant fees $20,000-$100,000+ on complex projects"],
    },
    steps: {
      "Kickoff and program brief: target use mix, unit sizes, parking approach, survey and zoning designation collected": { price: [150, 225], labor: 1, basis: "derived", q: 2 },
      "Zoning parameter research: base FAR and density, height and stepback rules, lot coverage, open space, parking ratios, and every bonus or transfer program the site qualifies for": { price: [800, 2000], labor: 1, basis: "est", q: 1 },
      "Lot area verification: gross lot area from the survey, street dedications, easements and any area the ordinance excludes from the FAR calculation": { price: [400, 1000], labor: 1, basis: "est", q: 1 },
      "FAR tabulation: allowable floor area, exempt areas (below-grade parking, mechanical, balconies), bonus floor area with its conditions, and net sellable or leasable area": { price: [800, 2000], labor: 1, basis: "est", q: 1 },
      "Density and unit-yield calculation: maximum units by the density cap, by FAR at the target unit mix and by parking, with the binding constraint identified": { price: [800, 2000], labor: 1, basis: "est", q: 1 },
      "Zoning envelope model in 3D: setbacks, height limits, sky-exposure planes, stepbacks and view corridors": { price: [1200, 3000], labor: 1, basis: "derived", q: 1, note: "8-20 hrs 3D modeling" },
      "Massing scenario: building form, floor plates and floor count fit to the envelope, with FAR, unit count, parking and open space tabulated for that scenario": { price: [1500, 3500], labor: 1, basis: "derived", q: 3, note: "per scenario; 10-22 hrs each" },
      "Bonus and incentive analysis: inclusionary housing, transfer of development rights, green-building or public-plaza bonuses and what each costs to earn": { price: [1000, 3000], labor: 1, basis: "est" },
      "Parking and loading fit test: required stalls against the podium or below-grade footprint, ramp geometry and loading berths": { price: [800, 2000], labor: 1, basis: "est", q: 1 },
      "Study report and exhibit set: zoning summary, tabulations, massing diagrams and the recommended scenario": { price: [1200, 3500], labor: 1, basis: "derived", q: 1 },
      "Presentation to the client, architect and investment partners": { price: [175, 250], labor: 1, basis: "derived", q: 3 },
      "Confirmation meeting with the planning department on FAR interpretation and bonus eligibility": { price: [150, 225], labor: 1, basis: "derived" },
      "Revisions for a changed unit mix, height or parking approach": { price: [130, 190], labor: 1, basis: "derived", q: 6 },
      "Reimbursables: survey and GIS data, 3D base model purchase and printing": { price: [200, 1000], labor: 0.05, basis: "est", q: 1, note: "GIS / 3D base model purchase at cost" },
    },
  },
  "buildable-area-calc": {
    op: 0.2,
    opNote: "civil / planning consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one parcel net buildable area exhibit and capacity calculation",
      price: [3000, 10000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 1200,
      sources: ["OGS Capital 2026: pre-feasibility / initial screening study $5,000-$15,000; consultants $150-$500/hr", "Archiwise 2025: land-use / zoning consultants $150-$350/hr; California zoning consultant fees $20,000-$100,000+ on complex projects"],
    },
    steps: {
      "Kickoff: intended use, survey or plat, title commitment with easement documents, and any prior wetland, flood or soils reports collected": { price: [140, 200], labor: 1, basis: "derived", q: 2 },
      "Base map assembly: boundary and topography from the survey, or GIS parcel lines, LiDAR contours and aerial imagery where no survey exists": { price: [500, 1500], labor: 1, basis: "derived", q: 1, note: "4-10 hrs CAD/GIS" },
      "Regulatory setback mapping: front, side and rear yards, corner-lot and accessory rules, street-widening lines and required buffers to adjacent districts": { price: [400, 1000], labor: 1, basis: "est", q: 1 },
      "Easement and right-of-way plotting: recorded utility, access, drainage and conservation easements located from the title exceptions and drawn to their deeded widths": { price: [400, 1200], labor: 1, basis: "est", q: 1 },
      "Environmental constraint overlay: FEMA flood zone and floodway, NWI or delineated wetlands with buffers, stream and shoreline setbacks, slopes above the ordinance threshold and protected trees": { price: [500, 1500], labor: 1, basis: "derived", q: 1 },
      "Site walk to verify constraints on the ground: flagged wetlands, drainage ways, slope breaks, encroachments and existing structures": { price: [120, 175], labor: 0.95, basis: "derived", q: 4 },
      "Septic reserve and well setback allocation: primary and reserve drainfield area and separation distances taken out of the buildable area": { price: [400, 1000], labor: 1, basis: "est" },
      "Stormwater and open-space set-aside: detention footprint, required open space or landscape percentage deducted": { price: [300, 900], labor: 1, basis: "est", q: 1 },
      "Net buildable area exhibit: gross area, each deduction tabulated and the net envelope drawn with dimensions and acreage": { price: [600, 1500], labor: 1, basis: "derived", q: 1 },
      "Development capacity calculation: maximum footprint, floor area, units or lots the envelope supports under the density and coverage rules": { price: [400, 1000], labor: 1, basis: "est", q: 1 },
      "Confirmation of setback and buffer interpretation with the zoning administrator": { price: [140, 200], labor: 1, basis: "derived" },
      "Revisions for a corrected survey, a new wetland delineation or a changed program": { price: [115, 170], labor: 1, basis: "derived", q: 3 },
      "Reimbursables: GIS and LiDAR data, recorded easement copies and printing": { price: [100, 500], labor: 0.05, basis: "est", q: 1, note: "GIS/LiDAR data and easement copies at cost" },
    },
  },
  "lot-split-analysis": {
    op: 0.2,
    opNote: "land planning / civil consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one parent parcel split analysis, 2 lot configurations",
      price: [4000, 12000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 1500,
      sources: ["OGS Capital 2026: pre-feasibility / initial screening study $5,000-$15,000; consultants $150-$500/hr", "Archiwise 2025: land-use / zoning consultants $150-$350/hr; California zoning consultant fees $20,000-$100,000+ on complex projects", "City of Pittsburgh fee schedule 2026: ZBA variance $400, zone change petition $1,500, posted notice $450, property certification $100"],
    },
    steps: {
      "Kickoff: parent parcel deed and plat, survey, target lot count and product, and the client's timing collected": { price: [140, 200], labor: 1, basis: "derived", q: 2 },
      "Subdivision ordinance research: minimum lot area and width, frontage, minor versus major subdivision thresholds, flag-lot and private-road rules, dedication and improvement standards": { price: [400, 1000], labor: 1, basis: "est", q: 1 },
      "Title and plat review: existing lot lines, prior splits, easements, deed restrictions and any plat notes limiting further division": { price: [400, 1000], labor: 1, basis: "est", q: 1 },
      "Conceptual lot layout per configuration: lot lines, frontages, access points and any new road or shared drive drawn, each lot checked against the standards": { price: [700, 1800], labor: 1, basis: "derived", q: 2, note: "per configuration; 5-12 hrs each" },
      "Access and road review: driveway spacing and sight distance, private road or cul-de-sac standards, fire apparatus access and turnaround": { price: [400, 1200], labor: 1, basis: "est", q: 1 },
      "Utility extension review: sewer and water main proximity, extension length and route, septic and well feasibility per lot where mains are absent, stormwater requirement per lot": { price: [400, 1200], labor: 1, basis: "derived", q: 1 },
      "Environmental and site screen: floodplain, wetlands, slopes and tree preservation as they land on each proposed lot": { price: [400, 1000], labor: 1, basis: "est", q: 1 },
      "Approval roadmap: minor plat or full preliminary-and-final plat process, deciding bodies, notice, plat recording and the estimated timeline": { price: [400, 1000], labor: 1, basis: "est", q: 1 },
      "Cost and fee summary: survey and plat preparation, engineering, road and utility improvements, park and impact fees and recording fees": { price: [400, 1000], labor: 1, basis: "est", q: 1 },
      "Pre-application meeting with planning and public works on the preferred configuration": { price: [140, 200], labor: 1, basis: "derived", q: 3 },
      "Site walk with the surveyor to confirm access, drainage and existing improvements against the layout": { price: [120, 175], labor: 0.95, basis: "derived", q: 3 },
      "Neighbor and homeowner-association outreach on the split": { price: [140, 200], labor: 1, basis: "derived" },
      "Revisions to the layout and roadmap for a changed lot count or access plan": { price: [115, 170], labor: 1, basis: "derived", q: 3 },
      "Reimbursables: recorded document copies, GIS data, application pre-screen fees and mileage": { price: [100, 500], labor: 0, fee: true, basis: "src", q: 1, note: "copies, GIS data and pre-screen fees at cost (plat application ~$175-$200 in Pittsburgh 2026)" },
    },
  },
  "entitlement-strategy": {
    op: 0.2,
    opNote: "entitlement / land-use consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one project entitlement strategy engagement incl. about 9 months of retainer",
      price: [45000, 140000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 15000,
      sources: ["OGS Capital 2026: development consultants $150-$500/hr", "Highspire 2025: consulting retainer example $4,000/month; senior experts $200+/hr", "City of Pittsburgh fee schedule 2026: ZBA variance $400, zone change petition $1,500, posted notice $450, property certification $100"],
    },
    steps: {
      "Strategy kickoff: project program, deal timing, prior contact with the jurisdiction and known opposition reviewed": { price: [200, 300], labor: 1, basis: "derived", q: 4 },
      "Regulatory mapping: every entitlement the project needs (general plan amendment, rezoning, PUD, site plan, conditional use, plat, environmental clearance), the deciding body for each and how they sequence": { price: [2500, 6000], labor: 1, basis: "derived", q: 1, note: "15-30 hrs principal/senior" },
      "Stakeholder map: elected officials, planning staff, neighborhood groups, business associations, tribes and agencies with a say, each rated by influence and likely position": { price: [2000, 5000], labor: 1, basis: "est", q: 1 },
      "Political and precedent analysis: recent comparable approvals and denials, council voting patterns, the election calendar and staff turnover that affect timing": { price: [2000, 5000], labor: 1, basis: "est", q: 1 },
      "Entitlement roadmap and critical-path timeline: submittals, review cycles, hearings and appeal windows on a month-by-month schedule with decision points": { price: [3000, 7500], labor: 1, basis: "derived", q: 1 },
      "Consultant team plan: the studies the approval path requires (traffic, environmental, civil, legal) with scope and sequence for each": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Pre-application and staff meetings with the planning director, city manager and reviewing departments": { price: [175, 275], labor: 1, basis: "derived", q: 16 },
      "Elected-official briefings: one-on-one meetings with council or commission members before the hearing cycle": { price: [200, 300], labor: 1, basis: "derived", q: 12 },
      "Community outreach program: neighborhood meetings, community-benefits discussion, materials and follow-up": { price: [150, 225], labor: 0.9, basis: "derived", q: 40, note: "materials and venue small share" },
      "Application and submittal coordination: completeness review of the consultant team's packages before filing": { price: [150, 225], labor: 1, basis: "derived", q: 20 },
      "Hearing preparation and testimony: staff-report response, presentation deck, witness preparation and appearance before the commission and council": { price: [200, 300], labor: 1, basis: "derived", q: 24 },
      "Ongoing strategy retainer per month: weekly team calls, monitoring of agendas and ordinance changes, and issue response": { price: [3000, 7500], labor: 1, basis: "derived", q: 9, note: "per month; 15-35 hrs of calls, monitoring and issue response" },
      "Reimbursables: application and notice fees passed through, meeting venues, printing and travel": { price: [2500, 10000], labor: 0, fee: true, basis: "est", q: 1, note: "application and notice fees for the package passed through; venues, printing, travel at cost" },
    },
  },
  "rezoning-variance": {
    op: 0.2,
    opNote: "land-use consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one variance or rezoning case through one board hearing cycle",
      price: [6000, 20000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 2500,
      sources: ["City of Pittsburgh fee schedule 2026: ZBA variance $400, zone change petition $1,500, posted notice $450, property certification $100", "OGS Capital 2026: development consultants $150-$500/hr"],
    },
    steps: {
      "Kickoff and case assessment: the relief sought, the ordinance criteria the board must find, site facts, prior denials and a candid read of the odds": { price: [175, 275], labor: 1, basis: "derived", q: 3 },
      "Site and neighborhood documentation: photographs, existing conditions, adjacent zoning and uses, and the physical conditions that support the request": { price: [125, 175], labor: 0.95, basis: "derived", q: 5 },
      "Application package: forms, ownership affidavit, legal description, site plan and elevation coordination, assembled and filed with the jurisdiction": { price: [1200, 3500], labor: 1, basis: "derived", q: 1 },
      "Justification statement: point-by-point response to the variance hardship criteria or the rezoning consistency-and-compatibility findings, with supporting exhibits": { price: [1500, 4000], labor: 1, basis: "derived", q: 1, note: "10-20 hrs" },
      "Hearing exhibits: zoning map excerpt, aerial with context, setback diagram and rendering board sized for the hearing room": { price: [800, 2500], labor: 0.85, basis: "est", q: 1, note: "boards printed" },
      "Public notice: mailed notice to owners within the required radius, newspaper publication and sign posting, with the fees passed through": { price: [400, 1200], labor: 0.6, basis: "est", q: 1, note: "radius list, mailing and affidavits; publication and sign cost in reimbursables" },
      "Neighborhood meeting: notice, venue, presentation, sign-in sheet and the meeting summary the ordinance requires filed with the application": { price: [150, 225], labor: 0.9, basis: "derived" },
      "Staff coordination: completeness responses, staff-report review and negotiated conditions of approval": { price: [150, 225], labor: 1, basis: "derived", q: 8 },
      "Board of zoning appeals or planning commission hearing: presentation, testimony and rebuttal": { price: [175, 275], labor: 1, basis: "derived", q: 5 },
      "City council or county commission hearing on the rezoning ordinance, first and second reading": { price: [175, 275], labor: 1, basis: "derived" },
      "Continuances, resubmittals and response to an appeal": { price: [150, 225], labor: 1, basis: "derived" },
      "Recording of the approved ordinance, variance order or development agreement, and delivery of the closed file to the client": { price: [250, 750], labor: 0.7, basis: "est", q: 1, note: "recording fee passed through" },
      "Reimbursables: application fees, notice and publication costs, sign fabrication, printing and mileage": { price: [600, 3000], labor: 0, fee: true, basis: "src", q: 1, note: "application fee (variance ~$400, zone change ~$1,500 in Pittsburgh 2026) plus publication and sign" },
    },
  },
  "traffic-impact-study": {
    op: 0.2,
    opNote: "traffic engineering firm billing hourly rates",
    benchmark: {
      unit: "unit",
      measures: "study intersections",
      price: [3000, 6000],
      typicalQty: [4, 8],
      jobQty: 6,
      minJob: 3000,
      sources: ["Greenlight Traffic Engineering 2024: about $3,500 per intersection, $2,500-$5,000 per intersection for 3+ intersections", "LatestCost 2026: traffic engineers $100-$180/hr; TIA $5,000-$9,000 suburban, $6,500-$12,000 large metro", "Mike on Traffic 2010: peak-hour counts $200-$400 per intersection per peak (escalated)"],
    },
    steps: {
      "Scoping meeting with the reviewing agency: study intersections, horizon years, background growth rate, peak periods and methodology agreed and confirmed in a scoping letter": { price: [160, 225], labor: 1, basis: "derived", q: 4 },
      "Data collection: crash records, signal timing plans, approved-but-unbuilt developments, programmed roadway projects and prior counts obtained from the agency": { price: [600, 1500], labor: 0.9, basis: "est", q: 1 },
      "Peak-hour turning-movement count at each study intersection, weekday AM and PM peaks, with pedestrian and bicycle volumes and heavy-vehicle classification": { price: [450, 900], labor: 0.25, basis: "derived", q: 6, note: "AM + PM video count by count vendor" },
      "24-hour or 48-hour tube count per station on the adjacent roadway segments for daily volume and speed": { price: [250, 500], labor: 0.3, basis: "derived", q: 3, note: "per station, count vendor" },
      "Trip generation for the proposed development by land use per the current ITE Trip Generation Manual, with pass-by and internal-capture reductions": { price: [600, 1500], labor: 1, basis: "est", q: 1 },
      "Trip distribution and assignment: directional distribution from the travel-demand model or existing patterns, new trips assigned to the network and the site driveways": { price: [1000, 2500], labor: 1, basis: "derived", q: 1 },
      "Capacity analysis per intersection and scenario (existing, background and build for each horizon year) in Synchro or HCS: delay, level of service, volume-to-capacity and 95th-percentile queues": { price: [250, 500], labor: 1, basis: "derived", q: 18, note: "per intersection per scenario, AM and PM peaks" },
      "Site access and circulation review: driveway locations against spacing standards, sight distance, turn-lane warrants and internal queuing at the entrance": { price: [800, 2000], labor: 1, basis: "est", q: 1 },
      "Signal warrant analysis per the MUTCD for an unsignalized study intersection or a proposed site signal": { price: [800, 1800], labor: 1, basis: "est", note: "per intersection" },
      "Mitigation analysis: turn lanes, signal retiming, roundabout or new signal tested at each deficient location with a proportionate-share cost": { price: [1500, 4000], labor: 1, basis: "derived", q: 1 },
      "Traffic impact study report: methodology, counts, analysis worksheets, figures and mitigation, sealed by the traffic engineer": { price: [2500, 6000], labor: 1, basis: "derived", q: 1, note: "sealed report" },
      "Agency review response and resubmittal after staff comments": { price: [140, 200], labor: 1, basis: "derived", q: 12 },
      "Presentation of the study at the planning commission or council hearing": { price: [175, 250], labor: 1, basis: "derived", q: 4 },
      "Reimbursables: video count subcontractor, signal timing data purchase, mileage and printing": { price: [150, 600], labor: 0.05, basis: "est", q: 1, note: "counts are priced in the count lines" },
    },
  },
  "environmental-impact": {
    op: 0.2,
    opNote: "environmental consulting firm billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one IS/MND or EA-level document with about 5 technical studies",
      price: [40000, 150000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 12000,
      sources: ["CDFW 2025: environmental filing fee $2,968.75 for an ND/MND, $4,123.50 for an EIR", "MRCA 2019: EIR consultant contract about $150,000-$300,000 by milestone (EIR level, above this benchmark)", "CPUC Res. T-17517 via Rinehart 2022: MND $399,853 for a linear broadband project (upper outlier)"],
    },
    steps: {
      "Kickoff with the lead agency and applicant: review level determined, project description confirmed, schedule set and the technical studies scoped": { price: [175, 250], labor: 1, basis: "derived", q: 6 },
      "Project description and environmental setting: baseline conditions, site plans, construction assumptions and the regulatory setting written to the agency's format": { price: [3000, 8000], labor: 1, basis: "derived", q: 1 },
      "Initial study or environmental checklist under CEQA Appendix G or the NEPA scoping criteria, with a significance conclusion for each resource topic": { price: [6000, 15000], labor: 1, basis: "derived", q: 1, note: "40-80 hrs" },
      "Technical study per resource: biological survey, cultural and tribal records search, air quality and greenhouse-gas modeling, noise measurement and modeling, hazards database review": { price: [4000, 12000], labor: 0.85, basis: "derived", q: 5, note: "per study; bio, cultural, air/GHG, noise, hazards" },
      "Notice of preparation or notice of intent, scoping meeting and the scoping summary": { price: [4000, 10000], labor: 1, basis: "est" },
      "Impact analysis and alternatives: each resource chapter with thresholds, impacts, mitigation and a reasonable range of alternatives compared": { price: [8000, 25000], labor: 1, basis: "derived", q: 1, note: "scales with resource chapters" },
      "Mitigation monitoring and reporting program: each measure with timing, responsible party and verification method": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Administrative draft to the lead agency and one round of agency screencheck edits": { price: [2500, 6000], labor: 1, basis: "est", q: 1 },
      "Public draft document, notice of availability or completion, State Clearinghouse or Federal Register filing and management of the public review period": { price: [2500, 6000], labor: 0.9, basis: "est", q: 1 },
      "Response to comments and the final document with errata": { price: [4000, 12000], labor: 1, basis: "derived", q: 1, note: "scales with comment volume" },
      "Findings, statement of overriding considerations and the notice of determination or decision record": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Tribal consultation support under AB 52 or Section 106": { price: [150, 225], labor: 1, basis: "derived" },
      "Public hearings and community meetings on the document": { price: [175, 250], labor: 1, basis: "derived", q: 8 },
      "Mitigation monitoring during construction: site checks and compliance reports to the agency": { price: [110, 160], labor: 0.95, basis: "derived" },
      "Reimbursables: filing and fish-and-wildlife fees passed through, records-search fees, printing of hearing copies and travel": { price: [3300, 6000], labor: 0, fee: true, basis: "src", q: 1, note: "CDFW MND fee $2,968.75 (EIR $4,123.50) + county clerk + records search + printing" },
    },
  },
  "preconstruction-consulting": {
    op: 0.2,
    opNote: "CM / cost consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one preconstruction engagement, ~$10M building, 3 design milestones",
      price: [40000, 130000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 15000,
      sources: ["Highspire 2025: construction management consultants $100-$200/hr typical, $200+ senior; $800-$2,500/day; $40,000 flat fee for a six-month phase", "GSA CALC 2026: construction manager ceiling rates $99-$135/hr (IQR), median $120 (federal-discounted)"],
    },
    steps: {
      "Preconstruction kickoff with the owner and design team: budget, milestone dates, delivery method, and the review and estimate calendar set": { price: [175, 250], labor: 1, basis: "derived", q: 8 },
      "Design-milestone review at schematic, design development and construction documents: coordination, constructability and scope-gap comments logged and tracked to closure": { price: [3000, 7000], labor: 1, basis: "derived", q: 3, note: "per milestone; 20-40 hrs" },
      "Milestone cost estimate at each design stage: quantity takeoff by CSI division, unit pricing, general conditions, contingency and escalation, reconciled to the previous estimate": { price: [5000, 12000], labor: 1, basis: "derived", q: 3, note: "per design stage; 35-70 hrs estimator time" },
      "Value-engineering workshop: alternatives proposed by system with cost, schedule and quality effect, accepted items tracked into the documents": { price: [4000, 10000], labor: 1, basis: "derived", q: 1 },
      "Master schedule: design, permitting, procurement and construction sequence with the critical path and long-lead items": { price: [3000, 8000], labor: 1, basis: "derived", q: 1 },
      "Site logistics plan: laydown, cranes and hoisting, access, fencing, phasing of occupied areas, traffic and neighbor protection": { price: [2500, 6000], labor: 1, basis: "est", q: 1 },
      "Procurement strategy and long-lead log: early-release packages, equipment lead times and buyout dates against the schedule": { price: [2000, 5000], labor: 1, basis: "est", q: 1 },
      "Bid packaging and subcontractor prequalification: scope packages defined, qualification questionnaires reviewed and the bid list set": { price: [3000, 8000], labor: 1, basis: "est", q: 1 },
      "Bid solicitation, leveling and award recommendation per bid package: scope review with each bidder and a leveled tabulation": { price: [800, 2000], labor: 1, basis: "derived", q: 12, note: "per bid package" },
      "Guaranteed maximum price or final budget assembly: buyout results, allowances, clarifications and the assumptions log": { price: [6000, 15000], labor: 1, basis: "est" },
      "Permit and utility coordination: submittal timing, utility service applications and an impact-fee estimate": { price: [140, 200], labor: 1, basis: "src", q: 16 },
      "Preconstruction meetings and design coordination sessions with the team": { price: [160, 230], labor: 1, basis: "src", q: 30 },
      "Reimbursables: estimating database subscription, printing, and travel to the site and design offices": { price: [1000, 4000], labor: 0.05, basis: "est", q: 1, note: "estimating database, printing and travel at cost" },
    },
  },
  "conceptual-cost-estimating": {
    op: 0.2,
    opNote: "independent cost consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one Class 5/4 conceptual estimate, ~$5-20M building, 2 scenarios",
      price: [8000, 25000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 4000,
      sources: ["Highspire 2025: construction management consultants $100-$200/hr typical, $200+ senior; $800-$2,500/day; $40,000 flat fee for a six-month phase", "GSA CALC 2026: cost estimator ceiling rates $73-$95/hr (IQR, federal-discounted)"],
    },
    steps: {
      "Kickoff and document intake: program, concept drawings, site data, target budget and the required accuracy class confirmed": { price: [150, 220], labor: 1, basis: "derived", q: 4 },
      "Basis of estimate: design stage, documents relied on, assumptions, exclusions, pricing date and the accuracy range stated per AACE classification": { price: [800, 2000], labor: 1, basis: "est", q: 1 },
      "Parametric quantity development: gross floor area, footprint, exterior wall area, floor count, site acreage and system quantities inferred from the concept": { price: [1200, 3000], labor: 1, basis: "derived", q: 1 },
      "Elemental estimate in UniFormat: substructure, shell, interiors, services, equipment and site work, each priced from historical cost data and current unit rates": { price: [2500, 6500], labor: 1, basis: "derived", q: 1, note: "20-40 hrs estimator" },
      "Benchmarking against comparable completed projects: cost per square foot by system, adjusted for location index, size and time": { price: [1000, 2500], labor: 1, basis: "derived", q: 1 },
      "Soft-cost and owner-cost allowances: design fees, permits, testing, FF&E and owner contingency": { price: [800, 2000], labor: 1, basis: "est" },
      "Location and escalation adjustment: regional cost index and escalation to the projected construction midpoint at a stated annual rate": { price: [500, 1200], labor: 1, basis: "est", q: 1 },
      "Design and estimating contingency recommendation tied to the accuracy class, presented as a range rather than a point figure": { price: [500, 1200], labor: 1, basis: "est", q: 1 },
      "Cost model per scenario: alternate program size, construction type or site, each estimated on the same basis for comparison": { price: [1200, 3000], labor: 1, basis: "derived", q: 2, note: "per scenario" },
      "Estimate report: summary, elemental detail, benchmarks, assumptions and exclusions, and the risk items that move the number": { price: [1000, 2500], labor: 1, basis: "derived", q: 1 },
      "Reconciliation meeting with the contractor's or a second estimator's number, variances explained line by line": { price: [150, 220], labor: 1, basis: "derived" },
      "Presentation to the owner and design team, and an update of the estimate for a revised concept": { price: [150, 220], labor: 1, basis: "derived", q: 6 },
      "Reimbursables: cost database subscription, printing and travel": { price: [200, 800], labor: 0.05, basis: "est", q: 1, note: "cost database subscription and printing at cost" },
    },
  },
  "rom-estimating": {
    op: 0.2,
    opNote: "cost consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one ROM estimate with 2 options",
      price: [2500, 8000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 1500,
      sources: ["Highspire 2025: construction management consultants $100-$200/hr typical, $200+ senior; $800-$2,500/day; $40,000 flat fee for a six-month phase", "GSA CALC 2026: cost estimator ceiling rates $73-$95/hr (IQR, federal-discounted)"],
    },
    steps: {
      "Scope interview with the client: what is being built, where, how big, when, and what decision the number supports": { price: [150, 220], labor: 1, basis: "derived", q: 2 },
      "Assumptions and exclusions register: every parameter assumed in place of missing information, written down before pricing": { price: [300, 800], labor: 1, basis: "est", q: 1 },
      "Walk-through of the existing facility to size the work and spot the conditions that swing the number": { price: [140, 200], labor: 1, basis: "derived" },
      "Capacity-factor or unit-rate estimate: cost per square foot, per unit, per bed, per lane-mile or per installed horsepower from published indexes and project history, scaled to the stated size": { price: [600, 1500], labor: 1, basis: "derived", q: 1, note: "4-8 hrs" },
      "Major-system allowances: site, structure, envelope, MEP and finishes as percentages of the base, adjusted for the project's known features": { price: [400, 1000], labor: 1, basis: "derived", q: 1 },
      "Location, time and market adjustment: regional index, escalation to the expected construction date and the current bid-climate factor": { price: [300, 700], labor: 1, basis: "est", q: 1 },
      "Contingency and accuracy range: AACE Class 5 range (as wide as -50 to +100 percent) applied and stated with the number": { price: [200, 500], labor: 1, basis: "est", q: 1 },
      "Option pricing per alternate: each alternate size, site or program priced on the same basis": { price: [300, 800], labor: 1, basis: "derived", q: 2, note: "per alternate" },
      "ROM memo: one-page summary with the number, the range, what is in and out, and what would tighten the estimate": { price: [300, 800], labor: 1, basis: "derived", q: 1 },
      "Review call with the client and one update for a changed size or scope": { price: [150, 220], labor: 1, basis: "derived", q: 3 },
      "Reimbursables: cost index subscriptions and printing": { price: [50, 300], labor: 0.05, basis: "est", q: 1 },
    },
  },
  "cost-engineering": {
    op: 0.2,
    opNote: "cost engineering consultant billing hourly rates",
    benchmark: {
      unit: "unit",
      measures: "months of construction-phase cost management (setup amortized)",
      price: [9000, 16000],
      typicalQty: [10, 18],
      jobQty: 14,
      minJob: 25000,
      sources: ["Highspire 2025: construction management consultants $100-$200/hr typical, $200+ senior; $800-$2,500/day; $40,000 flat fee for a six-month phase", "Highspire 2025: CM consulting 2%-8% of project cost", "GSA CALC 2026: cost estimator ceiling rates $73-$95/hr (IQR, federal-discounted)"],
    },
    steps: {
      "Kickoff and cost management plan: reporting calendar, approval thresholds, code of accounts and the tools agreed with the owner": { price: [160, 230], labor: 1, basis: "derived", q: 12 },
      "Work breakdown and cost breakdown structure: control accounts mapped to the drawings, the contract and the owner's accounting codes": { price: [3000, 8000], labor: 1, basis: "est", q: 1 },
      "Detailed estimate at design completion: quantity takeoff by CSI division, crew and productivity rates, material quotes, equipment, general conditions, markups and escalation": { price: [20000, 50000], labor: 1, basis: "derived", q: 1, note: "~$10-20M project; 120-280 hrs estimator; scales with size" },
      "Control budget and cash-flow forecast: baseline budget by account loaded to the schedule for a monthly draw curve": { price: [4000, 10000], labor: 1, basis: "derived", q: 1 },
      "Value analysis: alternatives on the high-cost systems with life-cycle cost comparison and a decision log": { price: [5000, 12000], labor: 1, basis: "est" },
      "Bid and proposal evaluation: contractor pricing checked against the independent estimate, unbalanced bids and allowance exposure flagged": { price: [150, 210], labor: 1, basis: "derived", q: 24 },
      "Monthly cost report per month: commitments, incurred cost, forecast at completion, variance to budget and contingency drawdown": { price: [2000, 4000], labor: 1, basis: "derived", q: 14, note: "per month; 12-22 hrs" },
      "Earned-value and productivity tracking per month: planned versus earned versus actual by account with performance indices": { price: [1500, 3500], labor: 1, basis: "est", note: "per month" },
      "Change order review per change: independent pricing, entitlement check and negotiation support": { price: [500, 1200], labor: 1, basis: "derived", q: 24, note: "per change; 3-6 hrs" },
      "Pay application review per month: quantities in place verified, stored materials, retainage and lien releases checked before certification": { price: [1200, 2500], labor: 1, basis: "derived", q: 14, note: "per month" },
      "Trend and forecast log: potential changes and risks priced before they become change orders": { price: [150, 210], labor: 1, basis: "derived", q: 56, note: "about 4 hrs per month" },
      "Cost close-out: final cost report, reconciliation of allowances and contingency, and the as-built cost data for the owner's benchmarks": { price: [4000, 10000], labor: 1, basis: "est", q: 1 },
      "Reimbursables: estimating and cost-control software, printing and travel": { price: [1500, 5000], labor: 0.05, basis: "est", q: 1, note: "software, printing and travel at cost" },
    },
  },
  "constructability-review": {
    op: 0.2,
    opNote: "CM / construction consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one review milestone of a mid-size building set, 6 disciplines",
      price: [10000, 35000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 5000,
      sources: ["Highspire 2025: construction management consultants $100-$200/hr typical, $200+ senior; $800-$2,500/day; $40,000 flat fee for a six-month phase", "GSA CALC 2026: construction manager ceiling rates $99-$135/hr (IQR), median $120 (federal-discounted)"],
    },
    steps: {
      "Review kickoff: drawing set, specifications, geotechnical report and schedule received; disciplines, review depth and the owner's known concerns set": { price: [160, 230], labor: 1, basis: "derived", q: 3 },
      "Page-turn review per discipline: architectural, structural, civil, mechanical, electrical and plumbing sheets read against each other for conflicts, omissions and unbuildable details": { price: [1200, 3000], labor: 1, basis: "derived", q: 6, note: "per discipline; 8-16 hrs senior reviewer" },
      "Interdisciplinary coordination check: structure against ductwork and piping clearances, ceiling heights, foundations against utilities, penetrations and embeds": { price: [1200, 3000], labor: 1, basis: "derived", q: 1 },
      "Means, methods and sequencing review: crane access, formwork and shoring approach, erection sequence, temporary conditions and weather sensitivity": { price: [1000, 3000], labor: 1, basis: "est", q: 1 },
      "Site logistics and access review: staging, haul routes, existing utilities, adjacent occupancy and the constraints the drawings do not show": { price: [800, 2000], labor: 1, basis: "est", q: 1 },
      "Specification and bid-document review: scope gaps between drawings and specs, unrealistic tolerances, proprietary items and unclear responsibility": { price: [1000, 2500], labor: 1, basis: "derived", q: 1 },
      "Schedule and phasing check: activities driven by the design, long-lead equipment and details that add duration or cost": { price: [800, 2000], labor: 1, basis: "est", q: 1 },
      "Site visit to check the documents against existing conditions": { price: [140, 200], labor: 0.95, basis: "derived" },
      "Comment log: each finding with sheet reference, category, cost or schedule effect, recommendation and priority": { price: [600, 1500], labor: 1, basis: "est", q: 1 },
      "Constructability workshop with the design team and owner to walk the log and agree resolutions": { price: [175, 250], labor: 1, basis: "derived", q: 8, note: "reviewer hours at the workshop" },
      "Constructability report: findings summary, high-value recommendations and the risk items left open": { price: [1200, 3000], labor: 1, basis: "derived", q: 1 },
      "Back-check of the revised documents and closure of the comment log": { price: [140, 200], labor: 1, basis: "derived", q: 8 },
      "Reimbursables: model and drawing viewing software, printing and travel": { price: [200, 800], labor: 0.05, basis: "est", q: 1 },
    },
  },
  "construction-phasing": {
    op: 0.2,
    opNote: "CM / construction consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one phasing plan for an occupied building, 4 phases",
      price: [12000, 40000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 6000,
      sources: ["Highspire 2025: construction management consultants $100-$200/hr typical, $200+ senior; $800-$2,500/day; $40,000 flat fee for a six-month phase", "GSA CALC 2026: construction manager ceiling rates $99-$135/hr (IQR), median $120 (federal-discounted)"],
    },
    steps: {
      "Kickoff and operations interview: occupancy schedule, areas that must stay open, blackout dates, noise and dust sensitivity, and the owner's move capacity": { price: [160, 230], labor: 1, basis: "derived", q: 6 },
      "Existing-conditions review: floor plans, utility risers and shutoff points, egress paths, loading docks, elevators and parking documented for phasing": { price: [1200, 3000], labor: 1, basis: "est", q: 1 },
      "Phase definition: work areas grouped by system, occupancy and access into phases, with duration and the trigger to start each": { price: [1200, 3000], labor: 1, basis: "derived", q: 1 },
      "Phase plan per phase: colored plan showing the work zone, temporary partitions, egress, dust and noise barriers, and the occupied areas protected": { price: [1000, 2500], labor: 1, basis: "derived", q: 4, note: "per phase; 7-15 hrs plans" },
      "Swing space and relocation plan: temporary accommodation, move sequence and furniture or equipment handling for displaced occupants": { price: [2000, 6000], labor: 1, basis: "est" },
      "Utility shutdown and tie-in schedule: each electrical, mechanical, plumbing and data outage with duration, timing window and temporary service": { price: [1200, 3000], labor: 1, basis: "est", q: 1 },
      "Infection control and interim life-safety measures: ICRA class, negative-air containment, ILSM and fire-watch requirements by phase": { price: [1500, 4000], labor: 1, basis: "est" },
      "Logistics plan by phase: site access, deliveries, hoisting, laydown, parking displacement and construction traffic routes": { price: [1200, 3000], labor: 1, basis: "derived", q: 1 },
      "Schedule analysis: the phased sequence against a single-phase baseline, with the added duration and critical-path effects": { price: [1200, 3000], labor: 1, basis: "derived", q: 1 },
      "Cost premium analysis: temporary partitions, off-hours work, remobilizations, temporary utilities and general conditions added by phasing": { price: [1200, 3000], labor: 1, basis: "derived", q: 1 },
      "Stakeholder workshops with facilities, department heads and the design team to test each phase": { price: [160, 230], labor: 1, basis: "derived", q: 12 },
      "Phasing narrative and specification language for the bid documents": { price: [1000, 2500], labor: 1, basis: "est", q: 1 },
      "Updates to the phase plans for a changed occupancy or schedule": { price: [130, 190], labor: 1, basis: "derived", q: 8 },
      "Reimbursables: plan printing at workshop size and travel": { price: [200, 800], labor: 0.1, basis: "est", q: 1 },
    },
  },
  "cpm-analysis": {
    op: 0.2,
    opNote: "scheduling consultant billing hourly rates",
    benchmark: {
      unit: "unit",
      measures: "months of scheduling service (baseline amortized)",
      price: [4000, 8000],
      typicalQty: [12, 24],
      jobQty: 18,
      minJob: 5000,
      sources: ["GSA CALC 2026: project scheduler ceiling rates $94-$155/hr (IQR), median $119 (federal-discounted)", "Highspire 2025: construction management consultants $100-$200/hr typical, $200+ senior; $800-$2,500/day; $40,000 flat fee for a six-month phase"],
    },
    steps: {
      "Kickoff and document review: contract schedule specification, milestones, scope, drawings, and the software and format the owner requires": { price: [150, 210], labor: 1, basis: "derived", q: 6 },
      "Work breakdown structure and activity list: activities coded by phase, area, trade and responsibility to the contract's level of detail": { price: [2000, 5000], labor: 1, basis: "derived", q: 1 },
      "Baseline CPM schedule in Primavera P6 or Microsoft Project: logic ties, durations, calendars, constraints and resource or cost loading, with the critical and near-critical paths identified": { price: [6000, 15000], labor: 1, basis: "derived", q: 1, note: "40-90 hrs P6 scheduler; scales with activity count" },
      "Baseline narrative: critical-path description, key assumptions, weather days, float ownership and the DCMA 14-point schedule health check results": { price: [1500, 3500], labor: 1, basis: "est", q: 1 },
      "Schedule review per submission of a contractor baseline or update: logic, open ends, lags, constraints, float suppression and missing scope, with a comment memo": { price: [1200, 2500], labor: 1, basis: "derived", q: 4, note: "per submission; 8-16 hrs" },
      "Schedule update per month: progress data collected, actuals and remaining durations entered, critical path re-evaluated and a variance report issued": { price: [1800, 3500], labor: 1, basis: "derived", q: 18, note: "per month; 12-22 hrs" },
      "Three-week look-ahead per month pulled from the update for the field": { price: [300, 700], labor: 1, basis: "est", note: "per month" },
      "Time impact analysis per change: fragnet inserted into the current update to show the change's effect on completion": { price: [2000, 5000], labor: 1, basis: "derived", q: 3, note: "per fragnet" },
      "Recovery or re-sequencing schedule with the acceleration options laid out for pricing": { price: [3000, 8000], labor: 1, basis: "est" },
      "Forensic delay analysis: as-planned versus as-built or windows analysis, concurrent-delay evaluation and the delay apportionment report": { price: [25000, 75000], labor: 1, basis: "est", note: "claim-dependent; retainer typical" },
      "Expert report and testimony in mediation, arbitration or litigation": { price: [300, 450], labor: 1, basis: "est", note: "expert rate" },
      "Schedule meetings with the owner, contractor and design team": { price: [150, 210], labor: 1, basis: "derived", q: 36, note: "about 2 hrs per month" },
      "Reimbursables: scheduling software license, plotting of schedule sheets and travel": { price: [1000, 3500], labor: 0.05, basis: "est", q: 1, note: "P6 license share, plotting and travel at cost" },
    },
  },
  "risk-contingency": {
    op: 0.2,
    opNote: "risk / cost consultant billing hourly rates",
    benchmark: {
      unit: "fixed",
      measures: "one quantitative (Monte Carlo) risk assessment, ~$10-50M project",
      price: [15000, 60000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 8000,
      sources: ["Highspire 2025: construction management consultants $100-$200/hr typical, $200+ senior; $800-$2,500/day; $40,000 flat fee for a six-month phase", "OGS Capital 2026: consultants $150-$500/hr"],
    },
    steps: {
      "Kickoff and document review: estimate, schedule, contracts, design status and prior risk registers received; the analysis method and confidence level agreed": { price: [175, 250], labor: 1, basis: "derived", q: 8 },
      "Risk identification workshop with the owner, designer and contractor: threats and opportunities across scope, site, permits, market, design and execution": { price: [175, 250], labor: 1, basis: "derived", q: 16, note: "two facilitators, prep and one-day session" },
      "Risk register: each risk with cause, event, effect, owner, probability and cost and schedule impact ranges": { price: [2500, 6000], labor: 1, basis: "derived", q: 1 },
      "Qualitative scoring and heat map: probability-impact ranking to shortlist the risks that get quantified and mitigated": { price: [1500, 3500], labor: 1, basis: "est", q: 1 },
      "Quantitative cost risk analysis: Monte Carlo simulation of the estimate with line-item uncertainty and discrete risk events, producing the cost distribution and P50 through P90 values": { price: [5000, 15000], labor: 1, basis: "derived", q: 1, note: "30-70 hrs incl. model build" },
      "Schedule risk analysis: duration uncertainty and risk events simulated on the CPM schedule for completion-date confidence": { price: [5000, 12000], labor: 1, basis: "est" },
      "Contingency recommendation: contingency and management reserve at the chosen confidence level, allocated by phase or account, with drawdown rules": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Mitigation and response plan: actions, owners, cost of mitigation and the residual risk after each": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Risk management plan: register maintenance, review cadence, escalation and reporting agreed with the owner": { price: [1500, 3500], labor: 1, basis: "est", q: 1 },
      "Risk report: method, register, distributions, contingency recommendation and the top risks with their mitigations": { price: [2500, 6000], labor: 1, basis: "derived", q: 1 },
      "Periodic register reviews and re-simulation as design and procurement progress": { price: [160, 230], labor: 1, basis: "derived", q: 16 },
      "Presentation of the analysis to the board, lender or funding agency": { price: [200, 275], labor: 1, basis: "derived", q: 4 },
      "Reimbursables: simulation software license, workshop facilities and travel": { price: [500, 2500], labor: 0.05, basis: "est", q: 1, note: "simulation license and facilities at cost" },
    },
  },
  "owners-representative": {
    op: 0.2,
    opNote: "owner's rep firm billing hourly / monthly rates",
    benchmark: {
      unit: "unit",
      measures: "months of engagement (design through closeout)",
      price: [9000, 18000],
      typicalQty: [12, 24],
      jobQty: 18,
      minJob: 10000,
      sources: ["Terrapin 2026: owner's rep 2%-4% of cost on a $5M project; retainers $5,000-$25,000+/mo; $150-$300/hr", "Mastt 2025: owner's rep $150-$250+/hr senior; lump sums $10,000-$50,000+ small to mid-size"],
    },
    steps: {
      "Engagement kickoff: the owner's goals, budget, schedule, decision authority and the reporting they want, set in a project charter": { price: [175, 250], labor: 1, basis: "src", q: 8 },
      "Project management plan: roles, communication protocol, approval thresholds, document control, and the master project schedule and budget": { price: [3000, 8000], labor: 1, basis: "derived", q: 1 },
      "Consultant and contractor selection per procurement: RFQ or RFP drafting, interviews, scoring and a recommendation for the architect, engineers and builder": { price: [4000, 10000], labor: 1, basis: "derived", q: 3, note: "per procurement; 25-50 hrs" },
      "Contract review and negotiation support with counsel: scope, fee, insurance, schedule and change terms in the design and construction agreements": { price: [175, 250], labor: 1, basis: "src", q: 20 },
      "Design-phase review per milestone: program compliance, budget conformance, scope gaps and the owner decisions logged": { price: [2500, 6000], labor: 1, basis: "derived", q: 3, note: "per milestone" },
      "Budget and schedule monitoring per month: master budget updated with commitments and forecasts, schedule variance tracked and reported": { price: [1200, 2500], labor: 1, basis: "derived", q: 18, note: "per month" },
      "Bid or GMP evaluation: leveled comparison, exclusions and allowances reviewed and an award recommendation": { price: [4000, 10000], labor: 1, basis: "derived", q: 1 },
      "Construction-phase representation per month: weekly owner-architect-contractor meeting attendance and issue follow-up on the owner's behalf": { price: [4000, 8000], labor: 1, basis: "derived", q: 12, note: "per construction month; 25-45 hrs" },
      "Site walks: progress and quality observation against the documents, issues photographed and tracked to closure": { price: [150, 210], labor: 0.95, basis: "src", q: 72, note: "about 6 hrs per construction month" },
      "Pay application and change order review per month: quantities, backup and entitlement checked, with a recommendation to the owner": { price: [800, 2000], labor: 1, basis: "derived", q: 12, note: "per month" },
      "Monthly owner's report per month: budget, schedule, risks, decisions needed and progress photographs": { price: [800, 1800], labor: 1, basis: "derived", q: 18, note: "per month" },
      "Closeout: punch list oversight, commissioning witnessed, O&M manuals, warranties and as-builts received, final accounting reconciled": { price: [4000, 10000], labor: 1, basis: "derived", q: 1 },
      "Move-in and occupancy coordination: FF&E, vendors, certificate of occupancy and the handoff to the owner's operations": { price: [140, 200], labor: 1, basis: "derived" },
      "Reimbursables: travel, printing and project document-management software": { price: [1500, 6000], labor: 0.05, basis: "est", q: 1, note: "travel, printing, software at cost" },
    },
  },
  "construction-manager": {
    op: 0.15,
    opNote: "commercial CM; the CM fee line carries home-office OH&P",
    benchmark: {
      unit: "unit",
      measures: "months of construction (CM services, cost of work excluded)",
      price: [50000, 90000],
      typicalQty: [9, 15],
      jobQty: 12,
      minJob: 20000,
      sources: ["Northspyre 2023: CM fees 3%-5% on office and medical office, 5%+ multifamily, 2%-3% industrial", "HomeAdvisor 2026: construction management 5%-9% of cost on $1M-$10M projects", "GSA CALC 2026: construction manager ceiling rates $99-$135/hr (IQR), median $120 (federal-discounted)"],
    },
    steps: {
      "Preconstruction services: estimates at each design milestone, schedule, constructability and value engineering, bid packaging and buyout plan": { price: [20000, 50000], labor: 1, basis: "derived", q: 1, note: "~$5M project; scales with size" },
      "Project staffing per month: project manager, superintendent, project engineer and administrative support assigned to the job": { price: [24000, 36000], labor: 1, basis: "derived", q: 12, note: "per month: full-time super, PM ~50%, PE ~25%, admin ~15% at burdened rates" },
      "Site general conditions per month: field office, temporary utilities, sanitation, dumpsters, fencing, signage and safety supplies": { price: [5000, 10000], labor: 0.2, basis: "est", q: 12, note: "per month: trailer, temp utilities, sanitation, dumpsters, fence rental" },
      "Site-specific safety plan: hazard analysis, orientation, toolbox talks, inspections and incident reporting per OSHA 29 CFR 1926": { price: [2500, 6000], labor: 0.9, basis: "est", q: 1 },
      "Subcontractor procurement per bid package: prequalification, bid solicitation, leveling, award and subcontract execution": { price: [800, 2200], labor: 1, basis: "derived", q: 15, note: "per bid package" },
      "Quality control program: submittal and shop drawing review, mock-ups, inspection and testing coordination and the deficiency log": { price: [6000, 15000], labor: 0.9, basis: "est", q: 1 },
      "Construction schedule per month: baseline CPM, monthly update, three-week look-aheads and recovery planning": { price: [500, 1200], labor: 1, basis: "est", q: 12, note: "per month, scheduler support beyond base staff" },
      "Cost control and reporting per month: buyout log, commitments, change management, forecast at completion and contingency tracking": { price: [500, 1200], labor: 1, basis: "est", q: 12, note: "per month, beyond base staff" },
      "Coordination and meetings per month: weekly OAC meeting, subcontractor coordination meeting, and the RFI and submittal logs maintained": { price: [600, 1500], labor: 1, basis: "est", q: 12, note: "per month, beyond base staff" },
      "Permit and inspection management: building, trade and special inspections scheduled and passed": { price: [3000, 9000], labor: 0.95, basis: "est", q: 1, note: "permit fees paid by owner" },
      "Pay application assembly per month: schedule of values, subcontractor billings, lien waivers and stored-material backup": { price: [300, 800], labor: 1, basis: "est", q: 12, note: "per month" },
      "Construction manager fee on the cost of work, covering home-office overhead and profit": { price: [150000, 250000], labor: 0.7, basis: "src", q: 1, note: "3%-5% of cost of work, shown for ~$5M; scales with cost of work" },
      "Insurance and bonds: general liability, builder's risk and performance and payment bond premiums": { price: [75000, 140000], labor: 0, basis: "derived", note: "1.5%-2.8% of cost of work (GL, builder's risk, P&P bond) on ~$5M; scales" },
      "Off-hours supervision for night or weekend work the owner's operations require": { price: [110, 160], labor: 1, basis: "derived", note: "superintendent burdened rate with premium" },
      "Closeout: punch list, commissioning, O&M manuals, as-builts, warranties, final lien releases and the certificate of occupancy": { price: [6000, 15000], labor: 0.95, basis: "est", q: 1 },
      "Warranty administration for the contract warranty period: warranty calls logged and coordinated with subcontractors": { price: [2500, 7500], labor: 1, basis: "est", q: 1 },
    },
  },
};
