// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "landscape-architect-pro": {
    op: 0.2,
    opNote: "landscape architecture firm billing rates; ~20% profit over loaded cost",
    benchmark: {
      unit: "fixed",
      measures: "one full-service landscape design, concept through construction observation (residential estate or small commercial site)",
      price: [18000, 45000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 2500,
      sources: ["GSA CALC 2026: landscape architect ceiling rate median $127/hr (70 rates), principal landscape architect $250-$321/hr", "BLS OEWS May 2025: landscape architects median wage $38.40/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff meeting and site walk with the owner: program, budget, style references, existing trees and grades, sun and drainage observed and photographed": { price: [125, 185], labor: 1, basis: "derived", q: 3, note: "principal landscape architect rate" },
      "Base map assembly: boundary and topographic survey, utility locations, tree survey and soils report compiled into a CAD base; survey ordered where none exists": { price: [800, 2000], labor: 1, basis: "est", q: 1, note: "CAD base from the furnished survey; the survey itself is a pass-through or separate contract" },
      "Site analysis and inventory: sun and shade, slopes and drainage patterns, views, soils, existing vegetation to keep or remove, zoning setbacks, tree-protection and landscape ordinances": { price: [1000, 2500], labor: 1, basis: "est", q: 1 },
      "Conceptual design: two or three plan alternatives with precedent imagery and a rough order-of-magnitude budget, presented for owner selection": { price: [2000, 5000], labor: 1, basis: "derived", q: 1, note: "about 15-35 hours at $115-$150/hr" },
      "Schematic design: the selected concept developed into a site plan showing hardscape, planting zones, grading intent, water features and lighting; character sketches or 3D views": { price: [2500, 6000], labor: 1, basis: "derived", q: 1, note: "about 20-40 hours; scales with site size" },
      "Design development: dimensioned layout plan, preliminary grading and drainage plan, planting plan with species and sizes, materials board and outline specifications": { price: [3000, 7000], labor: 1, basis: "derived", q: 1, note: "about 25-50 hours; scales with site size" },
      "Construction documents: layout and materials plan, grading and drainage plan, planting plan and schedule, irrigation plan, landscape lighting plan, details of walls, steps, paving and edges, specifications": { price: [5500, 13000], labor: 1, basis: "derived", q: 1, note: "largest phase, about 30-35% of the design fee; scales with site size" },
      "Construction document sheets beyond the base set (sections, enlarged plans, additional details)": { price: [600, 1400], labor: 1, basis: "est", note: "per added sheet" },
      "Structural engineering coordination for retaining walls over 4 ft, pergolas and pool or water-feature structures": { price: [800, 2500], labor: 1, basis: "est", note: "coordination only; the structural engineer's own fee is separate" },
      "Irrigation design: hydrozoned plan, point of connection, backflow preventer, controller and schedule; water-budget compliance": { price: [1500, 4500], labor: 1, basis: "est" },
      "Agency submittals: landscape plan review, tree removal permit, stormwater or water-efficient landscape ordinance (WELO) compliance package, HOA or design review board; plan-check responses": { price: [1200, 3500], labor: 1, basis: "est", q: 1, note: "preparation and responses; agency and permit fees are paid by the owner" },
      "Bidding assistance: contractor list, bid set issue, pre-bid walk, answers to bidder questions and bid tabulation": { price: [115, 170], labor: 1, basis: "derived", q: 6 },
      "Construction observation: layout review, grading review, plant material inspection at the nursery or on delivery, irrigation coverage test, substantial completion punch list": { price: [120, 180], labor: 1, basis: "derived", q: 14 },
      "Design revisions beyond the included rounds, additional meetings and presentations": { price: [115, 170], labor: 1, basis: "derived", q: 4 },
      "Reimbursables: printing, plotting, delivery, mileage and agency fees paid on the owner's behalf": { price: [250, 1000], labor: 0, basis: "est", q: 1, note: "printing, plotting, mileage at cost plus 10-15%" },
    },
  },
  "architect": {
    op: 0.2,
    opNote: "architecture firm; billing rates carry overhead, ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "building gross area designed",
      price: [9, 20],
      typicalQty: [2500, 8000],
      jobQty: 5250,
      minJob: 5000,
      sources: ["Fixr 2022: architect $2-$15/sqft or 5%-20% of construction; new construction with oversight $20,000-$150,000", "GSA CALC 2026: principal architect ceiling rate median $220/hr, senior architect $170/hr", "BLS OEWS May 2025: architects median wage $47.73/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and pre-design: owner interviews, program of spaces and areas, budget and schedule targets, site visit and photographs": { price: [175, 250], labor: 1, basis: "derived", q: 12, note: "principal or project architect rate" },
      "Existing-conditions documentation: field measurement and photographs of the existing building, drawn into as-built plans, elevations and sections": { price: [100, 150], labor: 1, basis: "derived", note: "architect with CAD technician" },
      "Zoning and code analysis: setbacks, height, FAR, parking, occupancy classification, construction type, egress and accessibility requirements summarized on a code sheet": { price: [1200, 3500], labor: 1, basis: "est", q: 1 },
      "Schematic design (SD): site plan, floor plans, exterior elevations, building sections and massing views; outline of structural and MEP systems; owner presentation and sign-off": { price: [7000, 14000], labor: 1, basis: "derived", q: 1, note: "about 15% of the basic fee; scales with building area" },
      "Design development (DD): dimensioned plans, elevations, sections, wall sections, window and door schedules, finish selections, outline specifications; consultant coordination": { price: [9000, 18000], labor: 1, basis: "derived", q: 1, note: "about 20% of the basic fee; scales with building area" },
      "Consultant coordination: structural, MEP, civil and landscape scopes defined, fee proposals gathered, drawings checked across disciplines at each phase": { price: [140, 190], labor: 1, basis: "derived", q: 24 },
      "Construction documents (CD), the full permit and bid set: cover and code sheet, site plan, floor plans, roof plan, reflected ceiling plans, elevations, sections, details, schedules and project manual specifications": { price: [16000, 30000], labor: 1, basis: "derived", q: 1, note: "about 35-40% of the basic fee; scales with building area" },
      "Additional drawing sheets beyond the base set (enlarged plans, interior elevations, added details)": { price: [700, 1500], labor: 1, basis: "est", note: "per added sheet" },
      "Permit submittal: application, plan sets and forms filed with the building department; plan-check comments answered and revised sheets re-issued": { price: [1500, 4000], labor: 1, basis: "est", q: 1, note: "preparation and responses; plan-check fees are paid by the owner" },
      "Bidding or negotiation: bid set issued, pre-bid meeting, addenda, bid review and contractor recommendation": { price: [135, 185], labor: 1, basis: "derived", q: 16 },
      "Construction administration: shop drawing and submittal review, RFI responses, change-order review, pay-application certification": { price: [140, 190], labor: 1, basis: "derived", q: 50 },
      "Site observation visits during construction with a field report each visit": { price: [450, 900], labor: 0.95, basis: "derived", q: 8, note: "per visit: 3-5 hours with travel and a field report" },
      "Substantial completion punch list and final closeout documents: record drawings from contractor markups, warranties and O&M binders": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Renderings, 3D model views or a physical model beyond the phase deliverables": { price: [1500, 6000], labor: 1, basis: "est", note: "Fixr 2022: renderings $150-$1,000 each; a set of views or a model runs more" },
      "Reimbursables: printing, plotting, courier, travel and agency fees advanced on the owner's behalf": { price: [600, 2000], labor: 0, basis: "est", q: 1, note: "at cost plus 10-15%" },
    },
  },
  "residential-architect": {
    op: 0.2,
    opNote: "residential architecture firm billing hourly; ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "home or addition area designed (conditioned sqft)",
      price: [9, 22],
      typicalQty: [1500, 3500],
      jobQty: 2500,
      minJob: 3000,
      sources: ["Fixr 2022: architect $2-$15/sqft or 5%-20% of construction; new construction with oversight $20,000-$150,000", "Fixr 2022: new home drawings only $10,000-$30,000; addition $8,000-$20,000 and remodel $16,000-$40,000 with oversight", "BLS OEWS May 2025: architects median wage $47.73/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff at the house: wish list, rooms and sizes, style references, budget, how the family uses the home; existing conditions photographed": { price: [150, 225], labor: 1, basis: "derived", q: 3 },
      "Field measurement of the existing house and drawing of as-built floor plans, elevations and a roof plan": { price: [1200, 3500], labor: 1, basis: "est", note: "as-built measure of a 1,500-3,000 sqft house" },
      "Zoning and setback check: lot coverage, height, setbacks, floor-area limits, ADU or historic-district rules; a survey ordered where the setbacks are tight": { price: [500, 1500], labor: 1, basis: "est", q: 1 },
      "Concept design: two or three floor-plan schemes with a massing sketch or 3D view, walked through with the owner and one selected": { price: [3000, 7000], labor: 1, basis: "derived", q: 1, note: "about 15% of the fee; scales with area" },
      "Design development: the chosen scheme dimensioned into floor plans, exterior elevations, a building section, roof plan, window and door schedule, preliminary kitchen and bath layouts": { price: [4500, 10000], labor: 1, basis: "derived", q: 1, note: "about 20% of the fee; scales with area" },
      "Selections assistance: windows, doors, exterior materials, roofing and trim chosen with the owner from samples; cabinetry and finish direction for the kitchen and baths": { price: [125, 185], labor: 1, basis: "derived", q: 10 },
      "Structural engineering coordination: beam, header and foundation design by the licensed engineer, loads and framing plan exchanged and checked against the architectural set": { price: [600, 1800], labor: 1, basis: "est", q: 1, note: "coordination only; the engineer's own fee is separate" },
      "Energy-code compliance documents (Title 24, REScheck or the IECC prescriptive path) prepared for the permit set": { price: [400, 1200], labor: 1, basis: "est", q: 1 },
      "Permit and construction set: site plan, foundation and framing plans, floor plans, elevations, sections, details, electrical plan, schedules and general notes; stamped and signed": { price: [7000, 16000], labor: 1, basis: "derived", q: 1, note: "largest phase, about 35-40% of the fee; scales with area" },
      "Permit submittal to the building department and the HOA or design review board; plan-check corrections answered and revised sheets re-issued": { price: [800, 2500], labor: 1, basis: "est", q: 1, note: "preparation and responses; permit fees are paid by the owner" },
      "Contractor bidding help: drawings issued to two or three builders, questions answered, bids compared line by line with the owner": { price: [125, 185], labor: 1, basis: "derived", q: 8 },
      "Construction visits: foundation, framing, rough-in and finish stages checked against the drawings; contractor questions answered; a short report each visit": { price: [130, 195], labor: 1, basis: "derived", q: 16 },
      "Design changes requested after the permit set is issued, drawn and re-submitted": { price: [125, 185], labor: 1, basis: "derived" },
      "Reimbursables: plotting, printing, courier and permit application fees advanced for the owner": { price: [300, 1200], labor: 0, basis: "est", q: 1, note: "at cost plus 10-15%" },
    },
  },
  "commercial-architect": {
    op: 0.2,
    opNote: "commercial A/E firm; billing multiplier covers overhead, ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "building gross area (architecture only; consultants separate)",
      price: [8, 18],
      typicalQty: [8000, 30000],
      jobQty: 19000,
      minJob: 15000,
      sources: ["Fixr 2022: architects charge 5%-20% of construction cost, $100-$200/hr most common", "GSA CALC 2026: principal architect ceiling rate median $220/hr, senior architect $170/hr; project architect $130/hr", "BLS OEWS May 2025: architects median wage $47.73/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and programming: stakeholder interviews, space program with net and gross areas, occupancy and use, phasing, budget and schedule; site visit": { price: [165, 240], labor: 1, basis: "derived", q: 40 },
      "Existing-conditions survey of the building: field measurement, photographs, as-built plans and reflected ceiling plans; asbestos and structural conditions flagged for the owner": { price: [110, 160], labor: 1, basis: "derived" },
      "Code and zoning analysis: occupancy classification, construction type, allowable area and height, fire separations, egress, plumbing fixture counts, ADA and accessibility, energy code; summarized on a code sheet": { price: [3000, 8000], labor: 1, basis: "est", q: 1 },
      "Entitlements and pre-application meetings with planning, fire and building officials; conditional-use or design-review submittals prepared": { price: [160, 230], labor: 1, basis: "derived" },
      "Schematic design: site plan, floor plans, elevations, sections, massing views, preliminary structural and MEP system narratives, outline specs and a cost-consultant coordination set": { price: [25000, 50000], labor: 1, basis: "derived", q: 1, note: "about 15% of the architectural fee; scales with gross area" },
      "Design development: dimensioned plans, RCPs, building and wall sections, exterior envelope details, door and finish schedules, MEP and structural coordination, DD specifications": { price: [35000, 65000], labor: 1, basis: "derived", q: 1, note: "about 20% of the architectural fee; scales with gross area" },
      "Consultant coordination and clash review across structural, MEP, fire protection, civil and landscape at each phase": { price: [140, 195], labor: 1, basis: "derived", q: 80 },
      "Sustainability documentation: LEED, WELL or local green-code checklist and credit tracking through the design phases": { price: [15000, 45000], labor: 1, basis: "est", note: "documentation only; GBCI or IWBI certification fees are separate" },
      "Construction documents: full permit and bid set with cover, code and life-safety plans, site plan, floor and roof plans, RCPs, elevations, sections, details, schedules and a CSI-format project manual": { price: [60000, 110000], labor: 1, basis: "derived", q: 1, note: "about 35-40% of the architectural fee; scales with gross area" },
      "Accessibility review of the completed set against the ADA Standards and the state accessibility code before submittal": { price: [1500, 4500], labor: 1, basis: "est", q: 1 },
      "Permit submittal and plan-check responses to building, fire, health and planning; revised sheets re-issued until permit issue": { price: [130, 185], labor: 1, basis: "derived", q: 40 },
      "Bidding: bid set issue, pre-bid walk, addenda, bidder questions, bid evaluation and award recommendation": { price: [130, 185], labor: 1, basis: "derived", q: 40 },
      "Construction administration: submittal and shop-drawing review, RFIs, ASIs, change-order review, pay-application certification": { price: [140, 195], labor: 1, basis: "derived", q: 160 },
      "Site observation visits with a field report and photos each visit; substantial completion and final punch lists": { price: [600, 1100], labor: 0.95, basis: "derived", q: 16, note: "per visit with report and photos" },
      "Closeout: record drawings from contractor markups, warranties, O&M manuals and certificate-of-occupancy coordination": { price: [3500, 9000], labor: 1, basis: "est", q: 1 },
      "Reimbursables: printing, plotting, courier, travel, presentation renderings and agency fees advanced on the owner's behalf": { price: [2000, 7000], labor: 0, basis: "est", q: 1, note: "at cost plus 10-15%" },
    },
  },
  "interior-architect": {
    op: 0.2,
    opNote: "interior architecture firm billing hourly; ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "interior area planned (usable sqft)",
      price: [4, 10],
      typicalQty: [4000, 15000],
      jobQty: 9500,
      minJob: 5000,
      sources: ["Fixr 2025: interior designer $5-$17/sqft (average $10); mid-level designer $125-$200/hr", "GSA CALC 2026: interior designer ceiling rate median $101/hr, senior architect $170/hr", "BLS OEWS May 2025: architects median wage $47.73/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and program: headcount, departments or rooms, adjacencies, equipment, storage, brand and finish direction; site walk of the existing space": { price: [140, 210], labor: 1, basis: "derived", q: 12 },
      "Existing-conditions survey: field measurement of the shell, columns, windows, doors, ceiling heights, sprinkler heads, HVAC and electrical points; drawn as a CAD base plan and RCP": { price: [95, 140], labor: 1, basis: "derived", q: 16, note: "field measure plus CAD; roughly 600 sqft per hour" },
      "Test fit and space plan: two or three plan options with furniture blocking, seat counts and egress checked; one selected with the owner or landlord": { price: [3000, 7000], labor: 1, basis: "derived", q: 1, note: "about $0.30-$0.75/sqft; scales with area" },
      "Schematic design: the selected plan developed with ceiling concept, lighting intent, material palette boards and 3D views of key rooms": { price: [5000, 11000], labor: 1, basis: "derived", q: 1, note: "scales with area" },
      "Design development: dimensioned partition plan, reflected ceiling plan, finish plan, power and data plan, millwork elevations, door and hardware schedule, preliminary FF&E plan": { price: [7000, 15000], labor: 1, basis: "derived", q: 1, note: "scales with area" },
      "Finish and material selections: flooring, wall finishes, ceiling, millwork laminates and stone, tile, paint and window treatments chosen from samples and specified": { price: [120, 175], labor: 1, basis: "derived", q: 24 },
      "FF&E specification: furniture, fixtures and equipment scheduled with manufacturer, model, finish and quantities; dealer quotes gathered and compared": { price: [110, 165], labor: 1, basis: "derived" },
      "Code and accessibility review: occupant load, egress, corridor widths, ADA clearances, restroom fixture counts, finish flame-spread ratings": { price: [1200, 3500], labor: 1, basis: "est", q: 1 },
      "MEP, structural and fire-protection coordination: engineer scopes defined, loads and device locations exchanged, drawings overlaid and checked": { price: [130, 185], labor: 1, basis: "derived", q: 20 },
      "Construction documents: demolition plan, partition plan, RCP, finish plan, power and data plan, millwork sections and details, door and finish schedules, specifications; stamped": { price: [12000, 25000], labor: 1, basis: "derived", q: 1, note: "about $1.25-$2.60/sqft; scales with area" },
      "Landlord and building-department submittal: landlord review package, permit application and plan-check corrections": { price: [1500, 4000], labor: 1, basis: "est", q: 1, note: "preparation and responses; landlord and permit fees are paid by the owner" },
      "Bidding assistance: contractor walk-through, questions answered, bids leveled and reviewed with the owner": { price: [125, 180], labor: 1, basis: "derived", q: 12 },
      "Construction administration: submittal review, RFIs, site visits at demolition, framing, above-ceiling and finish stages, punch list and closeout": { price: [130, 185], labor: 1, basis: "derived", q: 40 },
      "Move-in and FF&E installation coordination: delivery scheduling, installation supervision and the furniture punch list": { price: [100, 150], labor: 1, basis: "derived" },
      "Reimbursables: printing, samples, courier, travel and permit fees advanced for the owner": { price: [500, 2000], labor: 0, basis: "est", q: 1, note: "at cost plus 10-15%" },
    },
  },
  "architectural-drafting": {
    op: 0.2,
    opNote: "drafting service billing hourly; ~20% over loaded cost",
    benchmark: {
      unit: "unit",
      measures: "drawing sheets in the set",
      price: [300, 650],
      typicalQty: [5, 12],
      jobQty: 8.5,
      minJob: 500,
      sources: ["Fixr 2025: draftsman $50-$130/hr, CAD services $75-$135/hr; new building drawings $1,000-$6,000", "Fixr 2025: custom plans for a 2,000 sqft home $2,000-$20,000; change requests $50-$60 per sheet", "BLS OEWS May 2025: architectural and civil drafters median wage $31.80/hr"],
    },
    steps: {
      "Intake: markups, sketches, photos, survey and prior drawings received; drawing list, scales, sheet size, title block and CAD standards agreed": { price: [75, 115], labor: 1, basis: "src", q: 2, note: "Fixr 2025 draftsman and CAD rates" },
      "Field measurement of the existing building with a laser distance meter, photographs and dimensioned field sketches": { price: [70, 110], labor: 1, basis: "src", note: "Fixr 2025 draftsman rate" },
      "As-built drawings: existing floor plans, elevations, sections and roof plan drawn from field notes at the agreed scale": { price: [200, 450], labor: 1, basis: "derived", q: 2, note: "per sheet: 3-5 CAD hours" },
      "Proposed floor plans drawn from the designer's or owner's sketches: walls, doors, windows, fixtures, dimensions, room names and notes": { price: [250, 550], labor: 1, basis: "derived", q: 2, note: "per sheet: 3-6 CAD hours" },
      "Exterior elevations and building sections at the agreed scale, with materials, heights and grades labeled": { price: [250, 500], labor: 1, basis: "derived", q: 3, note: "per sheet" },
      "Foundation, framing and roof-framing plans drawn from the engineer's layout and member sizes": { price: [250, 550], labor: 1, basis: "derived", note: "per sheet" },
      "Electrical, plumbing-fixture and reflected-ceiling plans with symbols and legends": { price: [175, 400], labor: 1, basis: "derived", note: "per sheet" },
      "Details and wall sections: footing, wall, roof-edge, stair and window details drawn at 3/4 in. or 1-1/2 in. scale": { price: [250, 550], labor: 1, basis: "derived", q: 1, note: "per sheet" },
      "Schedules and notes: door, window, finish and hardware schedules, general notes and the code sheet": { price: [200, 600], labor: 1, basis: "est", q: 1 },
      "Site plan from the survey or plat: setbacks, easements, driveway, utilities and drainage arrows": { price: [200, 450], labor: 1, basis: "derived", note: "per sheet" },
      "Redline pickup: designer, engineer or plan-check comments incorporated and clouded, revision block updated": { price: [70, 110], labor: 1, basis: "src", q: 5, note: "Fixr 2025 draftsman and CAD rates" },
      "3D model or rendering of the exterior or a key room built from the drawing set": { price: [400, 1500], labor: 1, basis: "est" },
      "File delivery: DWG and PDF sets, DWG-to-Revit or PDF-to-CAD conversion, plotted sets to the client and the permit counter": { price: [75, 300], labor: 0.6, basis: "est", q: 1, note: "plots and file conversion; a large PDF-to-CAD conversion runs more" },
      "Coordination with the stamping architect or engineer who reviews and seals the set": { price: [75, 120], labor: 1, basis: "derived" },
    },
  },
  "bim-revit": {
    op: 0.2,
    opNote: "BIM services firm billing hourly; ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "building area modeled",
      price: [1, 2.6],
      typicalQty: [20000, 60000],
      jobQty: 40000,
      minJob: 3000,
      sources: ["GSA CALC 2026: BIM labor categories ceiling rate median $117/hr (37 rates); CAD technician $66/hr", "BLS OEWS May 2025: architectural and civil drafters median wage $31.80/hr"],
    },
    steps: {
      "Kickoff and BIM execution plan (BEP): model uses, LOD by element and phase, disciplines, file naming, shared coordinates, worksets, software versions and exchange schedule": { price: [2000, 5000], labor: 1, basis: "est", q: 1 },
      "Existing-conditions model from a laser scan or measured survey: point cloud registered and modeled to LOD 200 for walls, floors, roof, structure and major MEP": { price: [6000, 16000], labor: 0.75, basis: "est", note: "scan and model about $0.15-$0.40/sqft; scales with area" },
      "Revit template and project setup: levels, grids, shared coordinates, phases, view templates, sheet list and family library": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Architectural model authored to LOD 300: walls, floors, roofs, ceilings, doors, windows, stairs, curtain wall, rooms and areas": { price: [12000, 24000], labor: 1, basis: "derived", q: 1, note: "about $0.30-$0.60/sqft at LOD 300; scales with area" },
      "Structural model to LOD 300: foundations, columns, beams, slabs and bracing with analytical alignment to the engineer's model": { price: [6000, 14000], labor: 1, basis: "derived", note: "about $0.15-$0.35/sqft; scales with area" },
      "MEP model to LOD 300: ductwork, piping, plumbing, conduit and cable tray, equipment with clearances, connected systems": { price: [10000, 24000], labor: 1, basis: "derived", note: "about $0.25-$0.60/sqft; scales with area" },
      "Model enrichment to LOD 350 or 400 for fabrication and detailing: hangers, connections, sleeves, embeds and shop-level dimensions": { price: [8000, 24000], labor: 1, basis: "est", note: "scales with area and trades" },
      "Clash detection in Navisworks: discipline models federated, clash tests run by system pairs, report issued with clash IDs and screenshots": { price: [1200, 3000], labor: 1, basis: "est", q: 6, note: "per coordination round" },
      "Coordination meetings: clashes walked through with the trades, resolutions assigned and tracked, models updated after each round": { price: [100, 150], labor: 1, basis: "derived", q: 24 },
      "Sheet production and annotation: plans, sections, elevations, schedules and details cut from the model and placed on sheets": { price: [250, 550], labor: 1, basis: "est", q: 40, note: "per sheet" },
      "Quantity takeoff and schedules exported from the model for estimating": { price: [2000, 6000], labor: 1, basis: "est" },
      "4D schedule linking or 5D cost linking of the model to the construction schedule or estimate": { price: [5000, 15000], labor: 1, basis: "est" },
      "Renderings, walkthrough animation or VR export from the model": { price: [1500, 6000], labor: 1, basis: "est" },
      "Model updates from design changes, RFIs and ASIs during construction": { price: [90, 135], labor: 1, basis: "derived", q: 40 },
      "As-built and record model updated from field verification and contractor markups; COBie or facility-management data populated": { price: [4000, 12000], labor: 1, basis: "est", q: 1, note: "scales with area" },
      "Deliverables packaged: native RVT, NWD federated model, IFC export, PDF and DWG sheet sets, family library": { price: [800, 2500], labor: 1, basis: "est", q: 1 },
    },
  },
  "structural-engineer": {
    op: 0.2,
    opNote: "structural engineering firm billing hourly; ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "building area engineered",
      price: [1.5, 4],
      typicalQty: [2000, 10000],
      jobQty: 6000,
      minJob: 500,
      sources: ["Fixr 2025: structural engineer $0.50-$2/sqft, $100-$500/hr; typical consult $500-$2,000", "GSA CALC 2026: structural engineer ceiling rate median $159/hr (97 rates)", "BLS OEWS May 2025: civil engineers median wage $48.48/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and site visit: architectural drawings reviewed, structural system options discussed, existing framing and foundation observed and photographed": { price: [150, 225], labor: 1, basis: "derived", q: 3 },
      "Existing-conditions assessment: existing framing, foundation and connections field-verified, member sizes and spans recorded, deficiencies noted for the design": { price: [140, 200], labor: 1, basis: "derived" },
      "Design criteria and load development: dead, live, roof, snow, wind and seismic loads per ASCE 7 and the adopted IBC or IRC, soil bearing values from the geotechnical report": { price: [500, 1500], labor: 1, basis: "est", q: 1 },
      "Schematic structural system: gravity and lateral system selection, preliminary member sizes, framing concept narrative for the architect": { price: [700, 2000], labor: 1, basis: "est", q: 1 },
      "Gravity analysis and design: beams, headers, joists, girders, columns and posts sized; deflection and vibration checked": { price: [1800, 4500], labor: 1, basis: "derived", q: 1, note: "scales with building area and levels" },
      "Lateral analysis and design: shear walls, moment frames or braced frames, diaphragms, hold-downs, anchors and drag struts designed for wind and seismic": { price: [1800, 4500], labor: 1, basis: "derived", q: 1, note: "scales with building area and levels" },
      "Foundation design: spread footings, continuous footings, grade beams, slab-on-grade or deep foundations sized to the geotechnical bearing values": { price: [1000, 3000], labor: 1, basis: "derived", q: 1, note: "scales with footprint" },
      "Stamped calculation package: load derivation, member and connection calcs, lateral analysis output, foundation calcs, sealed by the engineer of record": { price: [400, 1200], labor: 1, basis: "est", q: 1 },
      "Structural drawings: general notes, foundation plan, framing plans for each level and the roof, shear wall or frame schedule, typical and specific details; stamped and signed": { price: [2000, 5500], labor: 1, basis: "derived", q: 1, note: "scales with building area" },
      "Additional drawing sheets beyond the base set (added framing levels, special details)": { price: [800, 1800], labor: 1, basis: "est", note: "per added sheet" },
      "Coordination with the architect and MEP: framing depths, openings, equipment supports and penetrations checked across disciplines": { price: [140, 195], labor: 1, basis: "derived", q: 6 },
      "Plan-check responses: structural comments from the building department answered, calcs and sheets revised and re-issued": { price: [140, 195], labor: 1, basis: "derived", q: 4 },
      "Deferred-submittal review: trusses, steel connections, pre-engineered stairs or cold-formed framing shop drawings checked and stamped as reviewed": { price: [300, 900], labor: 1, basis: "est", note: "per deferred-submittal package" },
      "Construction-phase services: shop drawing and submittal review, RFI responses, site observation at footings, framing and anchor installation with a field report each visit": { price: [140, 200], labor: 1, basis: "derived", q: 8 },
      "Structural observation letters: final observation and the engineer's letter to the building department at completion": { price: [300, 900], labor: 1, basis: "est", q: 1 },
    },
  },
  "civil-engineer": {
    op: 0.18,
    opNote: "civil engineering firm; billing multiplier covers overhead, ~15-20% profit",
    benchmark: {
      unit: "sqft",
      measures: "site area developed (1 acre = 43,560 sqft)",
      price: [0.4, 0.95],
      typicalQty: [43560, 174240],
      jobQty: 108900,
      minJob: 3000,
      sources: ["GSA CALC 2026: civil engineer ceiling rate median $112/hr ($130 at contractor site), principal engineer $197/hr", "BLS OEWS May 2025: civil engineers median wage $48.48/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and site visit: project program, site constraints, existing drainage patterns, utility availability and access observed; jurisdiction requirements confirmed": { price: [150, 225], labor: 1, basis: "derived", q: 6 },
      "Due diligence and records research: zoning, easements, floodplain (FEMA FIRM), wetlands, utility as-builts, prior plans and agency standards collected and summarized": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Base map preparation from the boundary and topographic survey, utility locates and geotechnical report; existing-conditions sheet": { price: [1200, 3500], labor: 1, basis: "est", q: 1, note: "base drawn from the furnished survey; survey and geotech are passed through" },
      "Conceptual site plan: building pad, parking, access, fire lane, stormwater footprint and utility routing laid out for owner and pre-application review": { price: [2500, 6500], labor: 1, basis: "est", q: 1 },
      "Pre-application meeting with planning, public works and the fire marshal; entitlement submittal packages": { price: [150, 220], labor: 1, basis: "derived", q: 12 },
      "Grading and drainage plan: finished grades, pad elevations, retaining walls, spot elevations, cut and fill balance, ADA slopes at accessible routes": { price: [6500, 15000], labor: 1, basis: "derived", q: 1, note: "about $2,500-$6,000 per acre; scales with site area" },
      "Stormwater management design: detention or retention sizing, water-quality BMPs, outlet structures; drainage report with pre- and post-development calculations": { price: [5000, 12000], labor: 1, basis: "derived", q: 1, note: "scales with site area and basins" },
      "Erosion and sediment control plan and SWPPP: BMP layout, construction sequencing, NPDES notice of intent and inspection forms": { price: [2000, 5000], labor: 1, basis: "est", q: 1 },
      "Site utility plan: water service and fire line with hydrants, sanitary sewer with profiles, storm drain with profiles, dry utility routing": { price: [5000, 12000], labor: 1, basis: "derived", q: 1, note: "scales with site area and utility runs" },
      "Paving, striping and site-detail sheets: pavement sections from the geotechnical report, curb, sidewalk, ADA ramps, signage and construction details": { price: [3000, 7000], labor: 1, basis: "est", q: 1 },
      "Roadway, driveway and right-of-way improvement plans with profiles and cross sections": { price: [8000, 30000], labor: 1, basis: "est", note: "scales with frontage length" },
      "Agency submittals and plan-check responses: site plan, grading permit, public-works and utility-district reviews, revised sheets re-issued": { price: [3000, 8000], labor: 1, basis: "est", q: 1, note: "preparation and responses; agency fees are paid by the owner" },
      "Engineer's cost estimate of the site improvements and the bonding or surety quantity estimate for the jurisdiction": { price: [1000, 3000], labor: 1, basis: "est", q: 1 },
      "Construction-phase services: submittal review, RFIs, site observation at subgrade, utility installation and paving, as-built certification for the jurisdiction": { price: [140, 200], labor: 1, basis: "derived", q: 32 },
      "Record drawings and final certification of the stormwater facility and grading for the certificate of occupancy": { price: [2000, 5000], labor: 1, basis: "est", q: 1, note: "the as-built survey itself is a separate survey cost" },
      "Reimbursables: printing, agency fees, mileage and courier advanced on the owner's behalf": { price: [700, 2500], labor: 0, basis: "est", q: 1, note: "at cost plus 10-15%" },
    },
  },
  "geotechnical-engineer": {
    op: 0.18,
    opNote: "geotechnical firm with drilling and lab at thinner margins; ~18%",
    benchmark: {
      unit: "unit",
      measures: "soil borings drilled (the job's size)",
      price: [2200, 5000],
      typicalQty: [3, 9],
      jobQty: 6,
      minJob: 1500,
      sources: ["Fixr 2025: soil boring (15 ft) $1,000-$1,200; two 15-ft borings with report $1,400-$1,600; commercial $3,000-$5,000", "Fixr 2025: compaction test $100-$125 per location; geotechnical engineer $65-$300/hr", "GSA CALC 2026: geotechnical engineer ceiling rate median $139/hr (25 rates)"],
    },
    steps: {
      "Site reconnaissance and records review: published geologic maps, prior reports, NRCS soils, groundwater records and a site walk to place the exploration points": { price: [120, 180], labor: 1, basis: "derived", q: 4 },
      "Utility clearance: 811 one-call ticket, private locate at each boring location, access and permits for drilling in the right-of-way": { price: [300, 900], labor: 0.8, basis: "est", q: 1, note: "private locator at each boring; right-of-way permit fees extra" },
      "Drill-rig mobilization and site access: truck- or track-mounted rig, support truck and crew delivered; mats or a track rig where access is soft": { price: [500, 1500], labor: 0.35, basis: "est", q: 1, note: "rig and crew mobilization; a track rig or mats add $500-$1,500" },
      "Soil borings with hollow-stem auger or mud rotary to the stated depth (typically 20-50 ft), Standard Penetration Test at 2.5-5 ft intervals, samples logged by the field engineer": { price: [700, 1500], labor: 0.45, basis: "derived", q: 6, note: "per boring to about 25 ft at $20-$40/ft with SPT samples and logging; deeper borings scale by depth" },
      "Rock coring with an NQ or HQ core barrel below auger refusal, RQD and recovery logged": { price: [45, 90], labor: 0.4, basis: "est" },
      "Test pits excavated with a backhoe to 8-12 ft, logged, sampled and backfilled": { price: [350, 800], labor: 0.5, basis: "est", note: "backhoe and operator plus logging, per pit" },
      "Groundwater monitoring wells installed in completed borings with screen, sand pack, bentonite seal and flush-mount cover": { price: [1200, 3000], labor: 0.4, basis: "est", note: "per well" },
      "Field infiltration or percolation tests at the stormwater facility or drainfield locations": { price: [400, 1000], labor: 0.8, basis: "src", note: "Fixr 2025: perc test $600-$800" },
      "Borehole abandonment with bentonite grout and a surface patch to match; test pits backfilled and compacted": { price: [80, 250], labor: 0.55, basis: "est", q: 6 },
      "Laboratory testing: moisture content, Atterberg limits, sieve and hydrometer, Proctor, consolidation, direct shear or unconfined compression, corrosivity and R-value per ASTM": { price: [60, 180], labor: 0.5, basis: "derived", q: 16, note: "per test: moisture ~$25, Atterberg or sieve $90-$150, Proctor $200-$300, consolidation or direct shear $400-$800" },
      "Engineering analysis: bearing capacity, settlement, lateral earth pressures, liquefaction screening, slope stability, pavement section and seismic site class": { price: [1200, 3000], labor: 1, basis: "est", q: 1 },
      "Geotechnical report: site and subsurface description, boring logs and location plan, lab results, groundwater, foundation and slab recommendations, earthwork and compaction specs, pavement sections, seismic parameters; sealed": { price: [2000, 4500], labor: 1, basis: "derived", q: 1 },
      "Plan review and consultation with the structural and civil engineers during design; plan-check responses to the building department": { price: [150, 210], labor: 1, basis: "derived", q: 4 },
      "Construction-phase testing and observation: footing subgrade inspection, fill placement and compaction testing with a nuclear gauge, pile or pier observation, daily field reports": { price: [70, 110], labor: 0.85, basis: "derived", q: 24, note: "field technician with nuclear gauge (Fixr 2025: compaction test $100-$125 per location); engineer visits $150-$210/hr" },
      "Final letter of geotechnical observation and the compaction test summary for the building department": { price: [300, 900], labor: 1, basis: "est", q: 1 },
    },
  },
  "environmental-engineer": {
    op: 0.18,
    opNote: "environmental consultant; subs passed through with handling fee",
    benchmark: {
      unit: "fixed",
      measures: "one site: Phase I ESA, limited Phase II (about 8 borings) and closure",
      price: [25000, 60000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 2000,
      sources: ["GSA CALC 2026: environmental engineer ceiling rate median $139/hr (322 rates); geologist $112/hr", "BLS OEWS May 2025: environmental engineers median wage $51.50/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and site reconnaissance: current and past uses, adjoining properties, storage tanks, drums, staining, drains and stressed vegetation observed and photographed": { price: [120, 180], labor: 1, basis: "derived", q: 4 },
      "Phase I Environmental Site Assessment per ASTM E1527-21: records review, historical aerials, Sanborn maps, regulatory database search, interviews, site visit and the report with findings and RECs": { price: [2200, 4500], labor: 0.95, basis: "est", q: 1, note: "ASTM E1527-21 Phase I for a typical commercial parcel; complex or large sites $5,000-$10,000" },
      "Sampling and analysis plan and health-and-safety plan for the Phase II investigation": { price: [1500, 4000], labor: 1, basis: "est" },
      "Utility clearance and access agreements for the sampling locations; 811 ticket and private locate": { price: [400, 1200], labor: 0.8, basis: "est", q: 1 },
      "Soil borings with a direct-push (Geoprobe) rig to the stated depth, continuous cores screened with a PID and sampled at the intervals specified": { price: [450, 1000], labor: 0.4, basis: "est", q: 8, note: "direct-push day rate ($2,000-$3,000) spread over 6-10 borings plus the field scientist" },
      "Groundwater monitoring wells installed, developed and sampled; surveyed for elevation and gauged": { price: [2500, 6000], labor: 0.4, basis: "est", note: "per 2-inch well to about 20 ft, developed and sampled" },
      "Soil, groundwater, soil-vapor or sediment samples collected and shipped under chain of custody": { price: [60, 150], labor: 0.8, basis: "est", q: 16 },
      "Laboratory analysis by a certified lab for VOCs, SVOCs, TPH, RCRA metals, PCBs or asbestos as specified, standard turnaround": { price: [200, 500], labor: 0.1, basis: "est", q: 16, note: "per sample for the specified suite (VOCs, metals, TPH typical); rush turnaround extra" },
      "Data validation and risk screening against state and EPA screening levels; conceptual site model": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Phase II report: methods, boring logs, well construction, lab results tabulated against screening levels, figures and recommendations": { price: [3500, 8000], labor: 1, basis: "est", q: 1 },
      "Remedial action plan or corrective action design: alternatives evaluated, remedy selected, design drawings and specifications for excavation, SVE, in-situ treatment or capping": { price: [10000, 35000], labor: 1, basis: "est", note: "scales with the remedy and site size" },
      "Regulatory agency coordination: submittals to the state agency or local oversight program, no-further-action requests, meetings and responses": { price: [130, 190], labor: 1, basis: "derived", q: 16 },
      "Permits and compliance documents: SWPPP, SPCC plan, air permit application, NPDES or industrial stormwater permit, hazardous-waste generator filings": { price: [3000, 12000], labor: 1, basis: "est", note: "per permit package" },
      "Remediation oversight: contractor observation, confirmation sampling, waste profiling and manifests, daily field reports": { price: [100, 150], labor: 0.9, basis: "derived", q: 40, note: "field scientist rate; PID and sampling gear included" },
      "Closure or completion report with confirmation results, disposal manifests and the closure request to the agency": { price: [3000, 8000], labor: 1, basis: "est", q: 1 },
      "Reimbursables: lab fees above the samples listed, database reports, drilling subcontractor, disposal fees and agency fees passed through": { price: [800, 3000], labor: 0, basis: "est", q: 1, note: "database report, waste disposal, shipping and supplies at cost plus handling" },
    },
  },
  "mechanical-engineer": {
    op: 0.2,
    opNote: "MEP engineering firm billing hourly; ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "building area served",
      price: [1.25, 3.25],
      typicalQty: [8000, 30000],
      jobQty: 19000,
      minJob: 2500,
      sources: ["GSA CALC 2026: mechanical engineer ceiling rate median $136/hr (333 rates), principal engineer $197/hr", "BLS OEWS May 2025: mechanical engineers median wage $50.05/hr (billed at about 3x salary)", "Fixr 2025: mechanical engineer $90-$200/hr"],
    },
    steps: {
      "Kickoff and site visit: architectural drawings and program reviewed, existing equipment and ductwork surveyed, owner comfort and energy goals, utility availability": { price: [150, 215], labor: 1, basis: "derived", q: 6 },
      "Basis of design: design conditions, ventilation rates per ASHRAE 62.1 or 62.2, system type options, zoning, controls approach and energy-code path documented for owner sign-off": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Load calculations: heating and cooling loads by room and zone (Manual J for residential; ASHRAE methods in Trane TRACE or Carrier HAP for commercial)": { price: [2000, 5000], labor: 1, basis: "derived", q: 1, note: "scales with zones and area" },
      "Equipment selection and sizing: furnaces, heat pumps, air handlers, RTUs, chillers, boilers, VRF and ERV selected with Manual S or manufacturer data; schedules prepared": { price: [2000, 5000], labor: 1, basis: "derived", q: 1 },
      "Duct design: Manual D or equal-friction sizing, layout, static pressure calculation, register and diffuser selection, outside-air and exhaust paths": { price: [3500, 8500], labor: 1, basis: "derived", q: 1, note: "scales with area" },
      "Hydronic or refrigerant piping design: pipe sizing, pump selection, expansion, venting and refrigerant line lengths": { price: [3000, 9000], labor: 1, basis: "est" },
      "Energy-code compliance: COMcheck, Title 24 or IECC mechanical forms, economizer, demand-control ventilation and fan-power checks": { price: [800, 2500], labor: 1, basis: "est", q: 1 },
      "Controls and sequences of operation: thermostat or BAS points list, sequences for each system, control diagrams": { price: [1500, 4500], labor: 1, basis: "est", q: 1 },
      "Mechanical drawings: legend and notes, demolition plan, floor plans with ductwork and piping, roof plan, equipment schedules, details, sequences; stamped and signed": { price: [7000, 16000], labor: 1, basis: "derived", q: 1, note: "about $0.40-$0.85/sqft; scales with area" },
      "Additional drawing sheets beyond the base set (enlarged mechanical rooms, added floors, sections)": { price: [1000, 2200], labor: 1, basis: "est", note: "per added sheet" },
      "Specifications: CSI Division 23 sections for equipment, ductwork, piping, insulation, controls and testing-and-balancing": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Coordination with the architect, structural, electrical and plumbing engineers: equipment weights, openings, electrical loads and clearances checked": { price: [135, 190], labor: 1, basis: "derived", q: 12 },
      "Permit submittal support and plan-check responses to the building department and fire marshal; revised sheets re-issued": { price: [135, 190], labor: 1, basis: "derived", q: 6 },
      "Construction-phase services: submittal and shop-drawing review, RFIs, site observation at rough-in and equipment set, TAB report review": { price: [135, 195], labor: 1, basis: "derived", q: 24 },
      "Commissioning support: functional test procedures, startup witness, sequence verification and review of the final commissioning report": { price: [4000, 12000], labor: 1, basis: "est" },
    },
  },
  "electrical-engineer": {
    op: 0.2,
    opNote: "MEP engineering firm billing hourly; ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "building area served",
      price: [1.1, 3],
      typicalQty: [8000, 30000],
      jobQty: 19000,
      minJob: 2500,
      sources: ["GSA CALC 2026: electrical engineer ceiling rate median $137/hr (394 rates), principal engineer $197/hr", "BLS OEWS May 2025: electrical engineers median wage $58.00/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and site visit: architectural plans and program reviewed, existing service, panels and feeders surveyed, utility contact made and available fault current requested": { price: [150, 215], labor: 1, basis: "derived", q: 6 },
      "Basis of design: service voltage and size, distribution scheme, emergency and standby power, lighting levels per IES, controls approach and energy-code path for owner sign-off": { price: [1200, 3500], labor: 1, basis: "est", q: 1 },
      "Load calculations per NEC Article 220: connected and demand loads by panel, service and feeder sizing, voltage-drop checks": { price: [1200, 3500], labor: 1, basis: "derived", q: 1 },
      "Utility coordination: service application, transformer location, metering and the utility's design requirements": { price: [135, 190], labor: 1, basis: "derived", q: 8 },
      "Power distribution design: one-line diagram, switchgear, panelboards, transformers, feeders and branch circuits, panel schedules": { price: [4000, 10000], labor: 1, basis: "derived", q: 1, note: "scales with service size and area" },
      "Lighting design: fixture selection and layout, photometric calculations for interior and site lighting, lighting-control design per ASHRAE 90.1 or Title 24, emergency egress lighting": { price: [3500, 9000], labor: 1, basis: "derived", q: 1, note: "scales with area" },
      "Fire alarm design: device layout, riser diagram, sequence of operation and battery calculations per NFPA 72": { price: [2500, 7000], labor: 1, basis: "est" },
      "Low-voltage and special systems: telecom and data pathways, security, access control, AV and nurse-call infrastructure drawings": { price: [3000, 9000], labor: 1, basis: "est" },
      "Generator, ATS and emergency power design: load bank, fuel, transfer scheme and NEC 700, 701 and 702 separation": { price: [3000, 8000], labor: 1, basis: "est" },
      "Short-circuit, protective-device coordination and arc-flash study per NFPA 70E and IEEE 1584 with arc-flash labels": { price: [3500, 10000], labor: 1, basis: "est", note: "large services with many devices $10,000-$25,000" },
      "Electrical drawings: legend and notes, demolition plan, power plans, lighting plans, one-line, panel schedules, details, fixture schedule; stamped and signed": { price: [6000, 14000], labor: 1, basis: "derived", q: 1, note: "about $0.30-$0.75/sqft; scales with area" },
      "Additional drawing sheets beyond the base set (added floors, enlarged electrical rooms, site plan)": { price: [900, 2000], labor: 1, basis: "est", note: "per added sheet" },
      "Specifications: CSI Division 26, 27 and 28 sections for distribution, lighting, wiring methods, fire alarm and communications": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Coordination with the mechanical and plumbing engineers on motor loads and with the architect on room layouts and ceilings; plan-check responses to the building department and fire marshal": { price: [135, 190], labor: 1, basis: "derived", q: 12 },
      "Construction-phase services: submittal review, RFIs, site observation at rough-in and equipment, witnessing of generator and fire alarm acceptance tests": { price: [135, 195], labor: 1, basis: "derived", q: 24 },
    },
  },
  "plumbing-engineer": {
    op: 0.2,
    opNote: "MEP engineering firm billing hourly; ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "building area served",
      price: [0.7, 1.9],
      typicalQty: [8000, 30000],
      jobQty: 19000,
      minJob: 2000,
      sources: ["GSA CALC 2026: mechanical engineer ceiling rate median $136/hr (plumbing billed at the same rates)", "BLS OEWS May 2025: mechanical engineers median wage $50.05/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and site visit: architectural plans and fixture layouts reviewed, existing water service, sewer, gas meter and piping surveyed, utility pressure and flow data requested": { price: [150, 215], labor: 1, basis: "derived", q: 4 },
      "Fixture count and code analysis: minimum fixtures per the IPC or UPC and occupancy, accessibility fixture requirements, backflow and water-heater code rules": { price: [800, 2200], labor: 1, basis: "est", q: 1 },
      "Water supply design: fixture-unit and demand calculation, pipe sizing with pressure-loss calculation from the street to the highest fixture, booster pump selection where pressure is short": { price: [2000, 5000], labor: 1, basis: "derived", q: 1, note: "scales with fixture count" },
      "Domestic hot water: water-heater or boiler sizing, recirculation loop, mixing valves, expansion tank; solar or heat-pump water heating where specified": { price: [1200, 3500], labor: 1, basis: "derived", q: 1 },
      "Sanitary waste and vent design: drainage fixture units, pipe sizing, slopes, vent sizing, cleanouts, grease interceptor or sand-oil separator sizing": { price: [2000, 5000], labor: 1, basis: "derived", q: 1, note: "scales with fixture count" },
      "Storm drainage design: roof drain and overflow sizing, leaders and horizontal drains per the rainfall rate, storm connection": { price: [1500, 4000], labor: 1, basis: "est" },
      "Natural gas or propane piping design: appliance loads, pipe sizing per the fuel gas code, meter and regulator coordination with the utility": { price: [1000, 3000], labor: 1, basis: "est" },
      "Specialty systems: medical gas, compressed air, vacuum, lab waste or process piping design per NFPA 99 or the applicable standard": { price: [4000, 12000], labor: 1, basis: "est" },
      "Plumbing drawings: legend and notes, demolition plan, floor plans with water, waste, vent and gas, riser diagrams, fixture and equipment schedules, details; stamped and signed": { price: [4000, 10000], labor: 1, basis: "derived", q: 1, note: "about $0.20-$0.50/sqft; scales with area" },
      "Additional drawing sheets beyond the base set (added floors, enlarged toilet rooms, site utility plan)": { price: [800, 1800], labor: 1, basis: "est", note: "per added sheet" },
      "Specifications: CSI Division 22 sections for piping, insulation, fixtures, equipment and testing": { price: [1000, 3000], labor: 1, basis: "est", q: 1 },
      "Coordination with the architect, mechanical, electrical and civil engineers: fixture locations, chases, equipment power, water and sewer connection points": { price: [135, 190], labor: 1, basis: "derived", q: 8 },
      "Plan-check responses to the building department and health department; revised sheets re-issued": { price: [135, 190], labor: 1, basis: "derived", q: 4 },
      "Construction-phase services: submittal review, RFIs, site observation at underground rough-in and above-ceiling piping, witnessing of pressure tests and backflow certification": { price: [135, 195], labor: 1, basis: "derived", q: 16 },
    },
  },
  "fire-protection-engineer": {
    op: 0.2,
    opNote: "fire protection engineering firm billing hourly; ~20% profit",
    benchmark: {
      unit: "sqft",
      measures: "building area protected",
      price: [0.6, 1.6],
      typicalQty: [10000, 50000],
      jobQty: 30000,
      minJob: 2500,
      sources: ["GSA CALC 2026: fire protection engineer ceiling rate median $142/hr (85 rates)", "BLS OEWS May 2025: mechanical engineers median wage $50.05/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and site survey: occupancy and use reviewed, existing sprinkler, standpipe, alarm and water supply observed, fire department connection and hydrant locations noted": { price: [150, 215], labor: 1, basis: "derived", q: 6 },
      "Water supply evaluation: hydrant flow test arranged or witnessed, static and residual pressures recorded, supply curve plotted against the system demand": { price: [800, 2500], labor: 1, basis: "est", q: 1, note: "evaluation and witnessing; the utility's flow-test fee is paid by the owner" },
      "Fire and life-safety code analysis: occupancy classification, construction type, required systems, hazard classification per NFPA 13, egress and separation summary; code letter for the AHJ": { price: [2500, 6500], labor: 1, basis: "est", q: 1 },
      "Sprinkler system design: hazard and density-area selection, system type (wet, dry, pre-action, ESFR), zone layout, riser and FDC location, pipe routing and head layout": { price: [3500, 9000], labor: 1, basis: "derived", q: 1, note: "scales with area and system count" },
      "Hydraulic calculations for the remote area per NFPA 13 against the water-supply curve, sealed by the engineer": { price: [1200, 3500], labor: 1, basis: "derived", q: 1 },
      "Fire pump and tank sizing with the pump-room layout, test header and controller": { price: [3500, 10000], labor: 1, basis: "est" },
      "Standpipe system design per NFPA 14: class, hose-valve locations, riser sizing and pressure-regulating requirements": { price: [2000, 6000], labor: 1, basis: "est" },
      "Fire alarm and detection design per NFPA 72: initiating and notification device layout, riser diagram, sequence-of-operations matrix, battery and voltage-drop calculations": { price: [3000, 8000], labor: 1, basis: "derived", q: 1, note: "scales with area" },
      "Smoke control design: rational analysis, zone diagrams, pressurization or exhaust rates, sequences and the special-inspection test plan": { price: [15000, 50000], labor: 1, basis: "est" },
      "Special hazard suppression: clean agent, kitchen hood, CO2 or foam system design and calculations per the governing NFPA standard": { price: [2500, 8000], labor: 1, basis: "est", note: "per protected room or system" },
      "Fire protection drawings: legend and notes, floor plans with piping and heads, riser diagrams, details, device schedules and the alarm matrix; stamped and signed": { price: [3500, 9000], labor: 1, basis: "derived", q: 1, note: "scales with area" },
      "Specifications: CSI Division 21 and 28 sections for suppression, alarm and testing": { price: [1000, 3000], labor: 1, basis: "est", q: 1 },
      "Fire marshal and building-department submittal and plan-check responses; variance or alternative-means requests where the code cannot be met literally": { price: [140, 200], labor: 1, basis: "derived", q: 8 },
      "Shop-drawing review of the sprinkler contractor's NFPA 13 layout and calculations and the alarm contractor's NFPA 72 submittal": { price: [140, 200], labor: 1, basis: "derived", q: 10 },
      "Acceptance testing witnessed: hydrostatic test, main drain and flow-switch tests, alarm device tests, fire pump acceptance test, smoke-control functional test; final report to the AHJ": { price: [135, 195], labor: 1, basis: "derived", q: 10 },
    },
  },
  "transportation-engineer": {
    op: 0.15,
    opNote: "public-agency consultant work; negotiated profit ~10-15% over loaded cost",
    benchmark: {
      unit: "linear ft",
      measures: "roadway corridor length studied and designed",
      price: [70, 170],
      typicalQty: [1000, 4000],
      jobQty: 2500,
      minJob: 8000,
      sources: ["GSA CALC 2026: transportation engineer ceiling rate median $151/hr, traffic engineer $148/hr, principal engineer $197/hr", "BLS OEWS May 2025: civil engineers median wage $48.48/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and scoping meeting with the agency or developer: study area, analysis scenarios, horizon years, level-of-service standards and the agency's methodology agreed": { price: [160, 230], labor: 1, basis: "derived", q: 12 },
      "Records and data collection: as-built roadway plans, crash records for the last 3-5 years, signal timing sheets, planned developments and transportation plans gathered": { price: [2000, 5000], labor: 1, basis: "est", q: 1 },
      "Traffic counts: 48-hour machine tube counts and peak-hour turning-movement counts with pedestrian and bicycle volumes at each study intersection": { price: [600, 1300], labor: 0.6, basis: "est", q: 6, note: "per intersection: AM and PM video turning-movement counts plus a 48-hour tube count" },
      "Field review of the corridor: lane configurations, sight distance, signage, pavement condition, transit stops, pedestrian facilities and driveways inventoried and photographed": { price: [130, 185], labor: 1, basis: "derived", q: 12 },
      "Traffic impact study (TIS/TIA): trip generation per the ITE Trip Generation Manual, distribution and assignment, capacity analysis in Synchro or HCS for existing, background and build scenarios, mitigation and the sealed report": { price: [15000, 35000], labor: 1, basis: "est", q: 1, note: "4-8 study intersections; scales with intersections and scenarios" },
      "Safety analysis: crash rate and pattern analysis, HSM predictive methods, countermeasure recommendations and benefit-cost": { price: [8000, 25000], labor: 1, basis: "est" },
      "Travel demand modeling or micro-simulation (VISSIM) for corridor or interchange alternatives": { price: [20000, 60000], labor: 1, basis: "est" },
      "Alternatives analysis and conceptual roadway plans: typical sections, horizontal and vertical alignment concepts, intersection or roundabout concepts, planning-level cost estimates": { price: [15000, 40000], labor: 1, basis: "est", q: 1, note: "scales with corridor length" },
      "Preliminary (30%) roadway design: plan and profile, typical sections, right-of-way needs, drainage concept and the design-exception request": { price: [35000, 80000], labor: 1, basis: "derived", q: 1, note: "about 20-25% of the roadway design fee; scales with corridor length" },
      "Final roadway design (60, 90 and 100%): plan and profile sheets, cross sections, grading, drainage, signing and striping, traffic control plans, quantities and specifications per the state DOT standards": { price: [90000, 200000], labor: 1, basis: "derived", q: 1, note: "about 55-65% of the roadway design fee, roughly $35-$80 per linear ft; scales with corridor length" },
      "Roadway plan sheets beyond the base set (additional stations, cross sections, detail sheets)": { price: [2500, 5000], labor: 1, basis: "est", note: "per added sheet" },
      "Environmental documentation support: NEPA categorical exclusion or CEQA transportation section, noise and air-quality coordination": { price: [15000, 50000], labor: 1, basis: "est" },
      "Agency review submittals and comment responses at each milestone; DOT encroachment or access permit application": { price: [140, 200], labor: 1, basis: "derived", q: 40 },
      "Public involvement: open-house exhibits, stakeholder meetings and council presentations": { price: [140, 200], labor: 1, basis: "derived" },
      "Bid-phase and construction support: bidder questions, RFIs, plan revisions and record drawings": { price: [140, 200], labor: 1, basis: "derived", q: 60 },
      "Reimbursables: count subcontractor, software runs, printing, mileage and agency fees advanced": { price: [1500, 5000], labor: 0, basis: "est", q: 1, note: "counts, software, printing at cost plus handling" },
    },
  },
  "traffic-engineer": {
    op: 0.15,
    opNote: "public-agency consultant work; negotiated profit ~10-15% over loaded cost",
    benchmark: {
      unit: "unit",
      measures: "signalized intersections designed",
      price: [30000, 70000],
      typicalQty: [1, 3],
      jobQty: 2,
      minJob: 5000,
      sources: ["GSA CALC 2026: traffic engineer ceiling rate $148/hr, transportation engineer median $151/hr", "BLS OEWS May 2025: civil engineers median wage $48.48/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and field review: existing signal equipment, cabinet and controller type, detection, poles and conduit, striping and signing inventoried at each intersection": { price: [130, 190], labor: 1, basis: "derived", q: 10 },
      "Records collection: as-built signal plans, timing sheets, signal warrant history, crash data and the agency's signal design standards and approved products list": { price: [800, 2500], labor: 1, basis: "est", q: 1 },
      "Turning-movement and pedestrian counts at each intersection for the AM and PM peaks, with 24-hour tube counts on the approaches": { price: [700, 1400], labor: 0.6, basis: "est", q: 2, note: "per intersection: AM and PM turning-movement counts plus approach tube counts" },
      "Signal warrant analysis per the MUTCD (Chapter 4C) with the warrant report and recommendation": { price: [3000, 8000], labor: 1, basis: "est", note: "per intersection studied" },
      "Capacity and operations analysis in Synchro or HCS for existing and proposed conditions, with level of service, queue lengths and phasing recommendations": { price: [3500, 9000], labor: 1, basis: "est", q: 1, note: "scales with intersection count" },
      "Signal timing and coordination: cycle lengths, splits, offsets and time-of-day plans developed and optimized; timing sheets prepared for the controller": { price: [1500, 3500], labor: 1, basis: "est", q: 2, note: "per intersection" },
      "Signal design plans: pole and mast-arm layout, signal heads, pedestrian signals and push buttons, detection (loops, video or radar), conduit and pull boxes, cabinet and service, wiring and phase diagrams per the agency standard": { price: [35000, 75000], labor: 1, basis: "est", q: 1, note: "for about two intersections, $18,000-$40,000 per intersection; scales with intersection count" },
      "Structural pole and mast-arm calculations or foundation design where the agency does not use standard plans": { price: [3000, 10000], labor: 1, basis: "est" },
      "Signing and striping plans: lane lines, crosswalks, arrows, legends, raised markers and signs per the MUTCD with removals and the sign schedule": { price: [4000, 11000], labor: 1, basis: "est", q: 1, note: "scales with intersection count" },
      "Temporary traffic control plans: staging, lane closures, detours, flagging and device layout per MUTCD Part 6 for the construction": { price: [3500, 10000], labor: 1, basis: "est", q: 1, note: "scales with staging and intersection count" },
      "ITS and communications design: interconnect conduit and fiber, CCTV, emergency vehicle preemption, transit priority and the central system connection": { price: [10000, 35000], labor: 1, basis: "est" },
      "Intersection lighting and photometric design where street lighting is part of the signal work": { price: [3000, 9000], labor: 1, basis: "est" },
      "Quantities, engineer's estimate and special provisions for the agency's bid package": { price: [2500, 7000], labor: 1, basis: "est", q: 1 },
      "Agency and DOT submittal reviews at 60, 90 and 100% with comment responses; encroachment permit application": { price: [140, 200], labor: 1, basis: "derived", q: 20 },
      "Construction support: submittal review, RFIs, signal turn-on attendance, timing implementation and fine-tuning in the field, record drawings": { price: [140, 200], labor: 1, basis: "derived", q: 24 },
    },
  },
  "hydrology-drainage-engineer": {
    op: 0.18,
    opNote: "water-resources engineering firm; ~15-20% profit",
    benchmark: {
      unit: "sqft",
      measures: "site area draining to the design (1 acre = 43,560 sqft)",
      price: [0.14, 0.32],
      typicalQty: [87120, 348480],
      jobQty: 217800,
      minJob: 2500,
      sources: ["GSA CALC 2026: hydrologist ceiling rate median $120/hr, civil engineer $112/hr, principal engineer $197/hr", "BLS OEWS May 2025: civil engineers median wage $48.48/hr (billed at about 3x salary)"],
    },
    steps: {
      "Kickoff and site visit: drainage patterns, outfalls, existing culverts and channels, flooding history and downstream conditions observed and photographed": { price: [140, 200], labor: 1, basis: "derived", q: 6 },
      "Records and data collection: FEMA FIRM and flood insurance study, NRCS soils, NOAA Atlas 14 rainfall, topographic mapping, as-built storm drains and the jurisdiction's drainage manual": { price: [1200, 3000], labor: 1, basis: "est", q: 1 },
      "Watershed delineation and hydrologic analysis: sub-basins, time of concentration, curve numbers and peak flows for the design storms (2- through 100-year) by the Rational method or HEC-HMS": { price: [3500, 9000], labor: 1, basis: "derived", q: 1, note: "scales with the number of sub-basins" },
      "Hydraulic analysis of existing and proposed conveyance: storm drain, culvert and channel capacity in HEC-RAS, StormCAD or HydraFlow with hydraulic grade lines": { price: [3500, 9000], labor: 1, basis: "derived", q: 1, note: "scales with the conveyance system" },
      "Floodplain analysis and FEMA submittal: HEC-RAS model, no-rise certification, CLOMR or LOMR application package": { price: [10000, 35000], labor: 1, basis: "est", note: "no-rise certification alone $5,000-$15,000; CLOMR or LOMR package at the high end, FEMA review fees extra" },
      "Stormwater management design: detention or retention basin, underground vault or infiltration system sized, outlet structure and emergency spillway designed": { price: [5000, 12000], labor: 1, basis: "derived", q: 1, note: "scales with the number of facilities" },
      "Water-quality BMP selection and sizing: bioretention, permeable pavement, hydrodynamic separator or filter sized to the water-quality volume per the jurisdiction's manual": { price: [2500, 6500], labor: 1, basis: "est", q: 1 },
      "Drainage report: methodology, pre- and post-development hydrology, hydraulic calculations, BMP sizing, maps and exhibits; sealed for the jurisdiction": { price: [3000, 8000], labor: 1, basis: "derived", q: 1 },
      "Storm drain plan and profile sheets: pipes, inlets, manholes, outfalls, grading of swales and basins, BMP details": { price: [5000, 12000], labor: 1, basis: "derived", q: 1, note: "scales with pipe length and sheets" },
      "Drainage plan sheets beyond the base set (additional profiles, basin sections, added details)": { price: [1200, 2500], labor: 1, basis: "est", note: "per added sheet" },
      "Erosion and sediment control plan and SWPPP with the NPDES notice of intent": { price: [2500, 6500], labor: 1, basis: "est" },
      "Culvert or bridge hydraulic design with scour analysis": { price: [8000, 25000], labor: 1, basis: "est", note: "per crossing" },
      "Stormwater operations and maintenance manual and the recorded maintenance agreement for the BMPs": { price: [1000, 3000], labor: 1, basis: "est", q: 1 },
      "Agency submittals and comment responses: local stormwater review, state dam-safety or waterway permits, Corps or 401 coordination": { price: [140, 200], labor: 1, basis: "derived", q: 16 },
      "Construction observation: basin and outlet-structure inspection, BMP installation checks, as-built survey review and the final stormwater certification": { price: [130, 190], labor: 1, basis: "derived", q: 16 },
    },
  },
  "land-surveyor": {
    op: 0.22,
    opNote: "small survey firm; crew rates include truck and GNSS gear",
    benchmark: {
      unit: "fixed",
      measures: "one residential parcel boundary survey with corners set (up to about 1 acre)",
      price: [900, 2500],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 500,
      sources: ["Fixr 2025: land survey average $600 ($400-$1,000); boundary $200-$2,000; surveyor $175-$250/hr", "Bob Vila 2023: land survey average $526 ($376-$745); fence survey $250-$1,000; new construction $1,000-$2,000", "BLS OEWS May 2025: surveyors median wage $36.27/hr, surveying technicians $26.08/hr"],
    },
    steps: {
      "Records research: deeds, plats, recorded surveys, easements and right-of-way maps pulled from the county recorder and surveyor; adjoiner deeds abstracted": { price: [100, 300], labor: 0.9, basis: "est", q: 1, note: "copy fees for record documents included" },
      "Control and monument recovery: existing corners, section corners and benchmarks searched, found and tied by GPS/RTK or total station": { price: [160, 240], labor: 0.85, basis: "src", q: 1, note: "survey crew rate, Fixr 2025: surveyor $175-$250/hr" },
      "Field survey crew: boundary evidence, improvements, fences, encroachments and features located with GPS/RTK and a robotic total station": { price: [160, 240], labor: 0.85, basis: "src", q: 2, note: "survey crew rate, Fixr 2025: surveyor $175-$250/hr" },
      "Boundary analysis and computation: record calls reconciled with found evidence, lines and corners resolved, closures computed and the surveyor's opinion of the boundary formed": { price: [150, 450], labor: 1, basis: "est", q: 1 },
      "Monuments set at unmonumented corners: iron rod with the surveyor's cap, or nail and disk in pavement, flagged and witnessed": { price: [40, 100], labor: 0.8, basis: "est", q: 2, note: "per monument set" },
      "Property line staking: lath and flagging set on line for fences, walls or construction": { price: [30, 75], labor: 0.9, basis: "est", note: "per lath on line; a separate staking trip runs $300-$800" },
      "Construction staking: building corners, offsets and grades set from the approved plans": { price: [160, 240], labor: 0.85, basis: "src", note: "survey crew rate" },
      "Elevation certificate on the FEMA form with the survey of the lowest floor, adjacent grades and flood zone": { price: [600, 1600], labor: 0.95, basis: "src", note: "Fixr 2025: elevation certificate $600-$2,000" },
      "Legal descriptions and exhibits: metes-and-bounds descriptions and sketches for easements, splits or dedications": { price: [400, 1200], labor: 1, basis: "est", note: "per description with exhibit" },
      "Survey drawing: plat of survey or map at the stated scale with bearings, distances, monuments found and set, easements, encroachments, and the surveyor's certification and seal": { price: [200, 550], labor: 1, basis: "est", q: 1 },
      "Record of survey or corner records filed with the county where the statute requires": { price: [400, 1500], labor: 0.7, basis: "est", note: "includes county filing and map-check fees" },
      "Delivery: signed and sealed PDF, DWG file and paper prints; recorded copy where filed": { price: [25, 100], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "boundary-topo-survey": {
    op: 0.22,
    opNote: "survey firm; crew rates include truck and GNSS gear",
    benchmark: {
      unit: "fixed",
      measures: "one parcel boundary and topographic survey (about 0.5-2 acres, 1-ft contours)",
      price: [2500, 6500],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 1200,
      sources: ["Fixr 2025: topographic survey $500-$1,200; boundary $200-$2,000; 5 acres $1,500-$2,000; surveyor $175-$250/hr", "Bob Vila 2023: topographic survey $500-$1,200; $0.15-$0.70 per sqft of lot"],
    },
    steps: {
      "Records research: deeds, plats, prior surveys, easements and right-of-way maps for the parcel and adjoiners; benchmark and control data collected": { price: [150, 450], labor: 0.9, basis: "est", q: 1 },
      "Utility locate request (811) so that marked utilities can be picked up in the topographic survey": { price: [40, 150], labor: 1, basis: "est", q: 1, note: "811 is free; this is the office time to file and track the ticket" },
      "Horizontal and vertical control: GPS/RTK ties to the state plane coordinate system and NAVD 88 benchmarks; site benchmark set": { price: [250, 700], labor: 0.85, basis: "est", q: 1 },
      "Boundary field survey: existing monuments recovered, lines and corners measured with GPS/RTK and total station; encroachments and fences located": { price: [160, 240], labor: 0.85, basis: "src", q: 2.5, note: "survey crew rate, Fixr 2025: surveyor $175-$250/hr" },
      "Boundary resolution: record and measured evidence reconciled, lines computed, closures checked and the surveyor's boundary determination made": { price: [250, 700], labor: 1, basis: "est", q: 1 },
      "Corner monuments set: iron rod and cap or nail and disk at each unmonumented corner": { price: [50, 125], labor: 0.8, basis: "est", q: 2, note: "per monument set" },
      "Topographic field survey: ground shots on a grid and at breaks in grade, spot elevations, improvements, trees over the stated caliper, utilities, drainage features, edge of pavement and curbs": { price: [160, 240], labor: 0.85, basis: "src", q: 5, note: "survey crew rate; hours scale with acreage and terrain" },
      "Drone or lidar mapping for large or open parcels with ground control checks": { price: [1500, 5000], labor: 0.6, basis: "est", note: "drone or lidar with ground control; per-acre cost falls on large parcels" },
      "Tree survey: trees over the ordinance caliper located, tagged and identified by species and diameter": { price: [8, 25], labor: 0.95, basis: "est", note: "per tree tagged and identified" },
      "Utility survey of visible features: manholes, inverts and pipe sizes, valves, meters, poles and overhead lines": { price: [250, 700], labor: 0.9, basis: "est", q: 1 },
      "Data processing and CAD drafting: point file reduced, digital terrain model built, contours at the stated interval (1 ft or 2 ft), planimetrics and boundary drawn to the client's layer standard": { price: [450, 1200], labor: 1, basis: "est", q: 1, note: "scales with acreage" },
      "Boundary and topographic survey drawing at the stated scale, with legend, north arrow, contours, features, easements and the surveyor's certification and seal": { price: [250, 700], labor: 1, basis: "est", q: 1 },
      "Deliverables: sealed PDF, DWG with surface and point file (CSV), GIS shapefile where requested, paper prints": { price: [40, 150], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "alta-survey": {
    op: 0.22,
    opNote: "survey firm; crew rates include truck and GNSS gear",
    benchmark: {
      unit: "fixed",
      measures: "one commercial parcel ALTA/NSPS survey with common Table A items (about 1-3 acres)",
      price: [2800, 7500],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 2000,
      sources: ["Fixr 2025: ALTA survey $2,000-$3,000; surveyor $175-$250/hr", "Bob Vila 2023: ALTA survey $2,000-$3,000"],
    },
    steps: {
      "Title commitment review: the current commitment, vesting deed and every Schedule B exception document obtained from the title company and abstracted for plotting": { price: [250, 700], labor: 1, basis: "est", q: 1 },
      "Records research: adjoiner deeds, recorded plats, prior surveys, right-of-way maps and control data gathered": { price: [200, 600], labor: 0.9, basis: "est", q: 1 },
      "Private utility locate coordinated for Table A item 11(b) and observed surface evidence of utilities noted for the plat": { price: [500, 1500], labor: 0.9, basis: "est", note: "private locator for Table A item 11(b)" },
      "Field survey crew: boundary monuments recovered, lines and corners measured, improvements, encroachments, access and evidence of use located with GPS/RTK and total station": { price: [160, 240], labor: 0.85, basis: "src", q: 7, note: "survey crew rate, Fixr 2025: surveyor $175-$250/hr; hours scale with parcel size" },
      "Boundary resolution and closure: record calls, the title legal description and found evidence reconciled; discrepancies noted for the title company": { price: [350, 900], labor: 1, basis: "est", q: 1 },
      "Monuments set at corners not found, with caps bearing the surveyor's registration": { price: [50, 150], labor: 0.8, basis: "est", note: "per monument set" },
      "Easements and Schedule B exceptions plotted on the survey with recording information, with unplottable items listed": { price: [250, 750], labor: 1, basis: "est", q: 1, note: "scales with the number of Schedule B items" },
      "Table A optional items as requested, each priced separately: 2 address, 3 flood zone, 4 gross area, 6 zoning, 7 building dimensions, 8 substantial features, 9 parking count, 13 adjoiners, 16 earth moving, 18 wetlands markers, 19 offsite easements": { price: [80, 300], labor: 1, basis: "est", q: 5, note: "per Table A item; items needing field work (7, 8, 9) at the high end" },
      "Topographic contours or spot elevations for Table A item 5 at the stated interval": { price: [800, 2500], labor: 0.9, basis: "est" },
      "Zoning report coordination for Table A items 6(a) and 6(b) with the zoning letter or report furnished by the client": { price: [150, 500], labor: 1, basis: "est" },
      "Survey drawing per the 2021 ALTA/NSPS Minimum Standard Detail Requirements: boundary, legal description, easements, improvements, encroachments, notes, vicinity map, legend and the surveyor's certification": { price: [500, 1300], labor: 1, basis: "est", q: 1 },
      "Certification to the owner, lender and title company as named, with the surveyor's seal": { price: [75, 250], labor: 1, basis: "est", q: 1 },
      "Review comments from the title company, lender's counsel and buyer addressed and the survey re-issued": { price: [130, 185], labor: 1, basis: "derived", q: 2 },
      "Delivery: sealed PDF, DWG and paper prints; the survey delivered to the title company for the policy": { price: [40, 150], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "utility-survey": {
    op: 0.18,
    opNote: "SUE and survey firm; equipment-heavy field work",
    benchmark: {
      unit: "linear ft",
      measures: "utility length designated (quality level B)",
      price: [4.5, 11],
      typicalQty: [2000, 8000],
      jobQty: 5000,
      minJob: 1500,
      sources: ["GSA CALC 2026: subsurface utility field technician $125-$135/hr; land surveyor median $134/hr", "BLS OEWS May 2025: surveying technicians median wage $26.08/hr"],
    },
    steps: {
      "Kickoff and scoping: project limits, utility types of interest, required ASCE 38-22 quality levels (A-D) and the deliverable format agreed with the engineer": { price: [140, 200], labor: 1, basis: "derived", q: 3 },
      "Quality level D records research: utility owner as-builts, one-call member list, franchise maps, prior surveys and GIS layers collected and compiled": { price: [1500, 4000], labor: 1, basis: "est", q: 1, note: "scales with project limits and utility owners" },
      "811 one-call design ticket and coordination with utility owners for records and locate support": { price: [100, 400], labor: 1, basis: "est", q: 1 },
      "Quality level C surface survey: manholes, valves, meters, pedestals, poles, hydrants and vaults located, inverts and pipe sizes measured": { price: [160, 240], labor: 0.85, basis: "derived", q: 8, note: "survey crew rate" },
      "Quality level B designation: electromagnetic pipe and cable locating with a transmitter and receiver, sonde tracing of non-conductive lines, ground-penetrating radar sweeps, utilities painted and flagged in APWA colors": { price: [1.5, 4], labor: 0.8, basis: "est", q: 5000, note: "EM locators and GPR; dense urban corridors at the high end" },
      "GPR grid sweep of the excavation footprint for unknown lines, tanks and vaults": { price: [0.15, 0.45], labor: 0.8, basis: "est", note: "GPR grid; half-day minimum about $1,200-$1,800" },
      "Survey of the designated marks: paint and flags picked up by GPS/RTK or total station and tied to the project control and datum": { price: [160, 240], labor: 0.85, basis: "derived", q: 10, note: "survey crew rate" },
      "Quality level A test holes: vacuum-excavated potholes to the top of the utility at the stated depth, with size, material, depth and coordinates recorded and the hole backfilled and patched": { price: [1000, 2400], labor: 0.5, basis: "est", q: 6, note: "vacuum-excavated test hole with patch; deep holes or concrete pavement at the high end; right-of-way permits extra" },
      "Manhole and inlet inspection with inverts, pipe sizes, materials and directions recorded; CCTV where the pipe condition is needed": { price: [150, 450], labor: 0.85, basis: "est", note: "per structure; CCTV of a run adds $1-$3 per linear ft" },
      "Utility conflict analysis: proposed design overlaid on the utility map and a conflict matrix with recommended resolutions": { price: [2500, 8000], labor: 1, basis: "est" },
      "Utility mapping and drafting: CAD utility plan with each line labeled by owner, type, size, material, quality level and test-hole data; profiles where requested": { price: [2500, 6500], labor: 1, basis: "est", q: 1, note: "scales with the length mapped" },
      "Utility survey report: methods, quality levels by segment, limitations, test-hole logs with photos, sealed by the professional in charge": { price: [1500, 4000], labor: 1, basis: "est", q: 1 },
      "Deliverables: DWG, PDF, GIS geodatabase or shapefile and the test-hole data table; coordination meeting with the design team": { price: [500, 1500], labor: 1, basis: "est", q: 1 },
    },
  },
};
