// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "carport-builder": {
    op: 0.3,
    opNote: "residential specialty builder (site-built carports)",
    benchmark: {
      unit: "sqft",
      measures: "roof area covered",
      price: [16, 34],
      typicalQty: [300, 600],
      jobQty: 450,
      minJob: 3000,
      sources: ["HomeAdvisor 2026: metal carport $20-$40/sqft, wood $15-$35/sqft installed; two-car $4,000-$14,000", "Angi 2026: carport installation $12-$40/sqft; most pay $3,145-$9,693", "HomeAdvisor 2026: carport slab $4-$8/sqft; permits $60-$800"],
    },
    steps: {
      "Design and permit: size, vehicle count and clearance height set, engineered drawings for the local snow and wind loads and setbacks, HOA approval, permit and inspections": { price: [500, 1400], labor: 0.5, basis: "derived", q: 1, note: "engineered drawings plus the permit (HomeAdvisor 2026 permits $60-$800)" },
      "Utility locate and layout: 811 ticket, post locations set, overhead clearance and drainage checked": { price: [150, 350], labor: 0.9, basis: "est", q: 1 },
      "Demolition of the existing carport or awning, hauled away": { price: [2, 5], labor: 0.75, basis: "est", note: "tear-down and haul-off per sqft of old roof" },
      "Concrete pad: 4 in. 3,000-psi slab over compacted gravel with wire mesh or fiber, sloped to drain": { price: [6, 10], labor: 0.45, basis: "src", note: "HomeAdvisor 2026 carport slab $4-$8/sqft; 4 in. slab with gravel and mesh" },
      "Footings: 12 to 18 in. diameter to frost depth with 3,000-psi concrete and post bases or anchor bolts, or expansion anchors into an existing slab": { price: [150, 325], labor: 0.55, basis: "est", q: 6, note: "per footing; rock or a buried slab priced as found" },
      "Columns: 6x6 pressure-treated posts, or 2.5 in. square 14-gauge galvanized steel tube, plumbed and anchored": { price: [120, 260], labor: 0.4, basis: "derived", q: 6, note: "per column: 6x6 PT or 14-ga steel tube, set and plumbed" },
      "Headers and beams: steel C-channel or doubled 2x12 headers with knee braces for lateral stability": { price: [20, 38], labor: 0.5, basis: "est", q: 50 },
      "Roof frame: steel bows at 5 ft o.c. with hat-channel purlins, or 2x6 rafters at 24 in. o.c. with 2x4 purlins": { price: [4, 8], labor: 0.5, basis: "derived", q: 450, note: "share of the $15-$40/sqft all-in guides" },
      "Roofing: 29-gauge or 26-gauge galvanized or painted metal panels screwed with neoprene-washer screws, ridge cap and closures, or plywood and shingles matched to the house": { price: [3.5, 7], labor: 0.45, basis: "derived", q: 450, note: "metal panels low end, plywood and shingles high end" },
      "Trim and gutter: eave and rake trim, gutter and downspouts on the low side": { price: [6, 12], labor: 0.5, basis: "est", q: 85 },
      "Enclosure panels: metal side or end panels, gable ends, or a storage lean-to with a door": { price: [4, 8], labor: 0.4, basis: "est" },
      "Lighting: LED fixture with motion sensor and a GFCI outlet by a licensed electrician": { price: [350, 900], labor: 0.6, basis: "est", note: "per fixture or outlet including the circuit run" },
      "Paint or stain of the wood frame, two coats": { price: [1.5, 3.5], labor: 0.8, basis: "est", note: "per sqft of roof area covered" },
      "Final inspection, cleanup, haul-off of cutoffs and packaging": { price: [200, 450], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "stucco-eifs": {
    op: 0.25,
    opNote: "residential plastering subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "wall area net of openings",
      price: [9, 16],
      typicalQty: [1500, 3000],
      jobQty: 2250,
      minJob: 2500,
      sources: ["Homewyse 2026: three-coat stucco with paper and lath $10.69-$17.33/sqft installed", "HomeAdvisor 2026: hard-coat stucco $6-$9/sqft, EIFS $8-$12/sqft; 2,000 sqft home $10,200-$18,700", "Fixr 2025: stucco $6-$8/sqft installed; painting stucco $2-$5/sqft"],
    },
    steps: {
      "Substrate inspection and moisture testing, then a color and texture mockup on site for the owner's approval": { price: [300, 800], labor: 0.85, basis: "est", q: 1 },
      "Permit and inspections at the jurisdiction's fee, including the lath inspection before the scratch coat": { price: [150, 600], labor: 0, fee: true, basis: "est", q: 1, note: "valuation-based permit; varies by city" },
      "Protection and staging: windows, doors, roofing, walkways and plants masked and tarped; scaffolding or staging set at every elevation": { price: [1200, 3500], labor: 0.45, basis: "derived", q: 1, note: "scaffold rental and setup; scales with the perimeter and stories" },
      "Remove the existing stucco or siding to the sheathing, lath and fasteners pulled, debris hauled": { price: [1.5, 3.5], labor: 0.8, basis: "derived", note: "Fixr 2025 siding removal ~$1/sqft; stucco tear-off is heavier" },
      "Sheathing repair: rotted or delaminated sheathing cut out and replaced, framing sistered where soft": { price: [4, 9], labor: 0.6, basis: "est" },
      "Weather-resistive barrier: two layers of Grade D 60-minute paper, or house wrap with a paper bond break, lapped shingle-style; self-adhered flashing at openings, kickout flashing where a roof meets the wall": { price: [0.8, 1.5], labor: 0.5, basis: "derived", q: 2250 },
      "Accessories: 26-gauge galvanized weep screed at the base (4 in. above grade, 2 in. above paving), casing beads at openings, corner aid, and control joints per ASTM C1063 panel limits": { price: [3, 6], labor: 0.6, basis: "est", q: 700 },
      "Lath: 2.5 lb self-furring galvanized expanded metal lath or 17-gauge woven wire, fastened 7 in. o.c. into the studs, lapped at joints": { price: [1.4, 2.4], labor: 0.55, basis: "derived", q: 2250, note: "share of the Homewyse three-coat system price" },
      "Scratch coat: 3/8 in. cement plaster pressed through the lath and scored horizontally, moist-cured 48 hours": { price: [1.6, 2.8], labor: 0.7, basis: "derived", q: 2250, note: "share of the Homewyse three-coat system price" },
      "Brown coat: 3/8 in. cement plaster rodded straight and floated, moist-cured 7 days before the finish": { price: [1.6, 2.8], labor: 0.7, basis: "derived", q: 2250, note: "share of the Homewyse three-coat system price" },
      "EIFS: EPS insulation board adhered or mechanically fastened over a drainage plane, rasped flat, fiberglass mesh embedded in the polymer base coat, per the manufacturer's drainage EIFS details": { price: [6, 10], labor: 0.55, basis: "derived", note: "HomeAdvisor 2026 EIFS $8-$12/sqft all-in; finish coat is its own line" },
      "Finish coat: 1/8 in. acrylic elastomeric finish or integrally colored cement color coat in the approved texture (sand, lace, dash or smooth)": { price: [1.6, 3], labor: 0.6, basis: "derived", q: 2250 },
      "Foam trim, bands and quoins: EPS shapes with base coat and mesh, finished to match the walls": { price: [10, 22], labor: 0.5, basis: "est" },
      "Sealant joints: backer rod and polyurethane or silicone sealant at windows, doors, penetrations and control joints": { price: [2.5, 5], labor: 0.75, basis: "est", q: 350 },
      "Elastomeric coating over the cement finish, two coats in the chosen color": { price: [1.8, 3.5], labor: 0.7, basis: "src", note: "Fixr 2025 painting stucco $2-$5/sqft" },
      "Cleanup: masking removed, overspray cleaned from glass and paving, scaffold struck, debris hauled": { price: [400, 1000], labor: 0.8, basis: "est", q: 1, note: "scales with house size" },
    },
  },
  "fencing": {
    op: 0.3,
    opNote: "residential fence contractor; FenceScan default markup 30-38%",
    benchmark: {
      unit: "linear ft",
      measures: "fence length",
      price: [32, 60],
      typicalQty: [100, 250],
      jobQty: 175,
      minJob: 600,
      sources: ["Homewyse 2026: 6 ft wood privacy fence $33-$53/linear ft installed", "HomeGuide 2026: cedar privacy fence $35-$40/linear ft installed on average; vinyl $30-$60", "HomeAdvisor 2026: fence installation avg $3,277 ($1,860-$4,843); removal $3-$5/linear ft"],
    },
    steps: {
      "Layout: property pins located (a survey recommended where they are missing), 811 utility locate, HOA rules checked, the line staked and string-lined, gate openings and corner posts marked": { price: [120, 250], labor: 0.9, basis: "est", q: 1, note: "survey not included" },
      "Fence permit and inspection at the jurisdiction's fee": { price: [30, 150], labor: 0, fee: true, basis: "derived", note: "HomeAdvisor 2026 lists $20-$60; many cities charge $50-$150" },
      "Tear-out of the existing fence: panels, posts and concrete footings pulled and hauled away": { price: [4, 6.5], labor: 0.75, basis: "src", note: "catalog REMOVAL_PER_LF $4 at cost; HomeAdvisor 2026 $3-$5/linear ft; dump fee included" },
      "Clear the fence line: brush, vines and roots cleared 2 ft each side of the line": { price: [2, 5], labor: 0.9, basis: "est" },
      "Line posts: holes augered 8 to 12 in. in diameter to below frost depth (one third of the post height, 24 in. minimum), 4x4 pressure-treated, 5x5 vinyl or 2-3/8 in. steel posts set at 6 or 8 ft o.c.": { price: [48, 72], labor: 0.55, basis: "derived", q: 21, note: "post, hole and setting; concrete is its own line; catalog puts 25% of material and 30% of labor per LF in the posts" },
      "Corner, end and gate posts: heavier stock (6x6 wood, 3 in. steel, aluminum-stiffened vinyl) set deeper with extra concrete": { price: [85, 125], labor: 0.45, basis: "derived", q: 6, note: "heavier stock and deeper hole; concrete is its own line" },
      "Concrete: 3,000-psi concrete around every post, crowned at grade to shed water": { price: [460, 640], labor: 0.2, basis: "derived", q: 1.2, note: "bagged 3,000-psi mix, ~60 x 60-lb bags per cu yd; ~0.045 cu yd per 4x4 hole (catalog takeoff)" },
      "Rails and pickets: 2x4 pressure-treated rails (two or three per bay) with 1x6 cedar or pressure-treated pickets, dog-ear or flat top, ring-shank nailed or screwed, cap and trim boards where specified": { price: [27, 39], labor: 0.33, basis: "derived", q: 175, note: "6 ft cedar from the catalog ($22 material + $14 labor/LF at cost, 10% waste, less the post share); PT pine ~25% less, 8 ft ~33% more" },
      "Prefabricated panels: vinyl, composite, aluminum or ornamental steel panels set between the posts with brackets or routed posts": { price: [34, 50], labor: 0.25, basis: "derived", note: "6 ft vinyl privacy or 4 ft aluminum panels from the catalog, posts separate" },
      "Chain link: 1-5/8 in. top rail, 9-gauge 2 in. mesh fabric stretched and tied, tension bars and bands at every terminal post, bottom tension wire": { price: [13, 22], labor: 0.4, basis: "derived", note: "4 ft galvanized low end, 6 ft or black vinyl high end (catalog), posts separate" },
      "Gates: 4 ft walk gates and 10 to 12 ft double drive gates, wood gates over 4 ft built on a welded steel frame, prefab panel gates on vinyl and metal systems": { price: [300, 460], labor: 0.35, basis: "derived", q: 1, note: "4 ft walk gate from the catalog gateSingle, hardware separate; a 10-12 ft double drive gate is ~2.4x" },
      "Gate hardware: heavy-duty hinges, latch, drop rod and center stop on doubles, self-closing pool-code hardware or a keypad operator where specified": { price: [80, 170], labor: 0.3, basis: "est", q: 1, note: "hinges and latch; drop rod and center stop sets or pool self-closers $150-$300; keypad operators extra" },
      "Slope steps: extended posts with panels stepped or racked to follow the grade": { price: [30, 45], labor: 0.7, basis: "derived", note: "catalog STEP_EACH $28 at cost" },
      "Post caps: pyramid, flat or solar caps on every post, dome caps on terminal posts": { price: [7, 14], labor: 0.2, basis: "est", q: 27, note: "pyramid or flat caps; solar caps $25-$45" },
      "Stain and seal: penetrating stain, two coats, both faces": { price: [1.1, 1.75], labor: 0.65, basis: "derived", note: "catalog STAIN_PER_SQFT $1.10 at cost; sqft = length x height x 2 faces" },
      "Cleanup: hole spoils spread or hauled, cutoffs and packaging removed, magnetic sweep along the line": { price: [100, 200], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "residential-fence-repair": {
    op: 0.4,
    opNote: "small repair and service-call jobs",
    benchmark: {
      unit: "fixed",
      measures: "one fence repair job (post, rail, pickets, gate)",
      price: [600, 1500],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 250,
      sources: ["Fixr 2025: fence repair avg $500 ($200-$850); post replacement $200-$500; gate repair $150-$500", "Fixr 2025: picket replacement $150-$350; panel replacement $200-$750; pressure washing $125-$235"],
    },
    steps: {
      "Inspection: every post rocked and probed at grade, rails and pickets checked, gate sag and latch checked, photo report listing each repair": { price: [75, 150], labor: 1, basis: "derived", q: 1, note: "Fixr 2025 minimum call-out $75-$100; often credited to the job" },
      "Rotted or leaning posts replaced: post cut out, old concrete footing broken out and removed, new 4x4 or 6x6 pressure-treated or steel post set plumb in fresh 3,000-psi concrete": { price: [200, 450], labor: 0.7, basis: "src", q: 1, note: "Fixr 2025 post replacement $200-$500" },
      "Post stabilization with a galvanized steel repair bracket or sleeve driven beside the sound post": { price: [90, 175], labor: 0.6, basis: "est" },
      "Broken or sagging rails replaced with pressure-treated 2x4 rails on hangers or toe-screwed": { price: [8, 15], labor: 0.7, basis: "est", q: 8, note: "per linear ft of rail replaced" },
      "Broken, warped or missing pickets replaced with matching species and profile, fastened with ring-shank nails or screws": { price: [14, 28], labor: 0.55, basis: "derived", q: 8, note: "per linear ft of fence re-picketed; Fixr 2025 picket replacement $150-$350 per repair" },
      "Whole sections replaced: vinyl, composite or ornamental panels, or chain-link fabric, matched to the existing": { price: [30, 65], labor: 0.45, basis: "derived", note: "Fixr 2025 panel replacement $200-$750 per panel" },
      "Gate repair: gate re-hung, sag corrected with an anti-sag kit or new hinges, latch replaced, gate rebuilt where the frame is rotted": { price: [150, 400], labor: 0.6, basis: "src", q: 1, note: "Fixr 2025 gate repair $150-$500" },
      "Chain-link re-stretch: fabric re-tensioned, tension bands and ties replaced, bent top rail replaced": { price: [4, 9], labor: 0.8, basis: "derived", note: "Fixr 2025 chain-link repair $300-$600 per job" },
      "Pressure wash and wood brightener before refinishing": { price: [0.25, 0.55], labor: 0.8, basis: "derived", note: "Fixr 2025 pressure washing $125-$235 per fence" },
      "Stain or seal to match the existing color, two coats": { price: [0.75, 1.5], labor: 0.65, basis: "derived", note: "sqft of face; fence catalog stain $1.10/sqft at cost" },
      "Haul-away of the removed posts, concrete and boards, cleanup along the line": { price: [75, 175], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "skylight": {
    op: 0.3,
    opNote: "residential roofing and skylight installer",
    benchmark: {
      unit: "unit",
      measures: "skylights installed",
      price: [2500, 5500],
      typicalQty: [1, 3],
      jobQty: 2,
      minJob: 1200,
      sources: ["Bill Ragan Roofing 2026: skylight installed $3,000-$7,300 (fixed $3,000-$5,000, solar venting $4,250-$7,150)", "HomeAdvisor 2026: skylight installation avg $1,920 ($1,014-$2,828); ventilating unit $400-$2,000", "Fixr 2025: fixed skylight $295-$537, venting $574-$1,044 (unit only)"],
    },
    steps: {
      "Site survey: roof pitch and material, rafter spacing and layout, attic obstructions, unit size and type chosen (deck-mounted fixed, solar venting or curb-mounted), glazing and location marked on the roof and ceiling": { price: [150, 350], labor: 1, basis: "est", q: 1 },
      "Building permit and inspection at the jurisdiction's fee": { price: [100, 400], labor: 0, fee: true, basis: "est", q: 1 },
      "Interior protection: floors and furniture covered, dust barrier at the room, attic insulation pulled back and bagged": { price: [150, 350], labor: 0.85, basis: "est", q: 1 },
      "Remove the existing skylight, flashing and cracked dome, opening cleaned to the curb or deck": { price: [150, 350], labor: 0.85, basis: "derived", note: "Fixr 2025 replacement labor $176-$320" },
      "Roof opening cut: shingles cut back, deck cut to the template, rafter cut where the unit spans a bay": { price: [250, 500], labor: 0.9, basis: "est", q: 2 },
      "Opening framed: doubled headers hung on the rafters, rafters sistered, curb built from 2x6 where a curb-mounted unit is used": { price: [350, 800], labor: 0.7, basis: "est", q: 2 },
      "Skylight supplied and set: deck-mounted fixed or solar-powered venting unit with laminated low-E glass and a rain sensor, 10-year no-leak warranty, fastened per the manufacturer": { price: [800, 2000], labor: 0.2, basis: "derived", q: 2, note: "fixed deck-mount low end, solar venting high end; Fixr 2025 unit $295-$1,044, HomeAdvisor 2026 ventilating $400-$2,000" },
      "Flashing: manufacturer's step and head flashing kit for the roof type, self-adhered underlayment lapped around the opening, shingles re-woven and sealed": { price: [300, 600], labor: 0.6, basis: "derived", q: 2 },
      "Light shaft: 2x4 framed shaft from the roof to the ceiling, splayed or straight, insulated with R-30 batts, drywalled and taped": { price: [12, 22], labor: 0.7, basis: "est", q: 80, note: "per sqft of shaft wall" },
      "Shaft finish: corner bead, finish coats, primer and two coats of paint to match the ceiling, trim at the ceiling opening": { price: [5, 10], labor: 0.8, basis: "est", q: 80, note: "per sqft of shaft wall" },
      "Accessories: solar-powered blinds, remote control and insect screen": { price: [300, 650], labor: 0.15, basis: "est" },
      "Hose test of the flashing, insulation restored, debris hauled and the room cleaned, warranty registration": { price: [150, 350], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "sun-tunnel": {
    op: 0.3,
    opNote: "residential specialty installer",
    benchmark: {
      unit: "unit",
      measures: "tubular skylights installed",
      price: [750, 1400],
      typicalQty: [1, 3],
      jobQty: 2,
      minJob: 700,
      sources: ["Litespeed Construction 2025: 14 in. VELUX Sun Tunnel $1,100-$1,400 installed up to 6 ft; 10 in. ~$100 less", "GoGreen Daylight Systems 2025: sun tunnel $700-$1,200 professionally installed; labor $300-$800", "HomeAdvisor 2026: tubular skylight unit $200-$500"],
    },
    steps: {
      "Layout: ceiling location chosen for the room, attic checked for trusses, ducts and wiring on the route, 10 in. or 14 in. tube chosen by room size, roof pitch and material noted": { price: [75, 200], labor: 1, basis: "est", q: 1 },
      "Interior protection: drop cloths under the ceiling cut, furniture covered, attic insulation pulled back at the route": { price: [50, 150], labor: 0.9, basis: "est", q: 1 },
      "Ceiling opening: hole cut with the template between the joists, ceiling ring set and sealed": { price: [60, 150], labor: 0.85, basis: "est", q: 2 },
      "Roof opening: shingles or tiles lifted, deck cut to the template, self-adhered underlayment around the opening": { price: [100, 250], labor: 0.85, basis: "est", q: 2 },
      "Roof dome and flashing: acrylic dome on the manufacturer's flashing for the pitch and roof type (shingle, tile, metal or flat), sealed and the roofing re-laid around it": { price: [250, 450], labor: 0.35, basis: "derived", q: 2, note: "GoGreen 2025: kit $200-$500, flashing kit $50-$150; tile or metal flashing at the high end" },
      "Tubing: rigid highly reflective tube sections joined and taped from the roof to the ceiling, extension tubes on runs over 4 ft, angle adapters at bends": { price: [25, 45], labor: 0.3, basis: "derived", q: 10, note: "GoGreen 2025 extensions $30-$50 per section; Litespeed ~$90 each" },
      "Accessories: daylight dimmer, LED night-light kit or bath ventilation kit fitted in the tube": { price: [150, 350], labor: 0.35, basis: "derived", note: "GoGreen 2025: LED light kit +$100-$200, night light +$50-$150" },
      "Ceiling diffuser: frosted or prismatic lens and trim ring snapped in and sealed, insulation restored around the tube": { price: [90, 180], labor: 0.35, basis: "est", q: 2 },
      "Hose test of the flashing, debris hauled, ceiling and floor cleaned": { price: [75, 175], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "attic-ventilation": {
    op: 0.3,
    opNote: "residential roofing and insulation trade",
    benchmark: {
      unit: "sqft",
      measures: "attic floor area vented",
      price: [1.1, 2.4],
      typicalQty: [1200, 2000],
      jobQty: 1600,
      minJob: 400,
      sources: ["HomeAdvisor 2026: ridge vent $300-$650 installed (avg $500); soffit vents $315-$465; gable vents $60-$150 each", "RoofMedic 2026: ridge vent $7-$15/linear ft installed, $300-$750 for a 40-50 ft ridge"],
    },
    steps: {
      "Attic assessment: attic floor measured, existing intake and exhaust net free area counted against the IRC 1:150 rule, moisture, frost, mold and blocked soffits photographed, vent plan written": { price: [150, 350], labor: 1, basis: "est", q: 1 },
      "Soffit bays opened: insulation pulled back from the eaves and rafter baffles stapled in every bay to keep the intake path clear": { price: [10, 22], labor: 0.75, basis: "est", q: 50, note: "per rafter bay" },
      "Soffit intake: continuous aluminum or vinyl strip vent cut into the soffit, or 16x8 in. under-eave vents cut in and screened": { price: [5, 11], labor: 0.65, basis: "derived", q: 100, note: "continuous strip vent; cut-in rectangular vents cost about the same per foot of eave served" },
      "Ridge vent: 1 in. slot cut each side of the ridge, shingle-over ridge vent with external baffle and end plugs, new cap shingles": { price: [7, 14], labor: 0.6, basis: "src", q: 45, note: "RoofMedic 2026 $7-$15/linear ft; HomeAdvisor 2026 $300-$650 per roof" },
      "Roof louvers or turbine vents cut in and flashed high on the slope": { price: [150, 350], labor: 0.55, basis: "derived", note: "HomeAdvisor 2026 turbines $65-$250 each for a swap; new cut-in and flashing adds" },
      "Gable vents cut in, framed and screened": { price: [175, 400], labor: 0.7, basis: "derived", note: "HomeAdvisor 2026 gable vents $60-$150 each for a swap; a new framed opening is more" },
      "Powered or solar attic fan with thermostat and humidistat, cut in and flashed, wired by a licensed electrician where hard-wired": { price: [450, 1000], labor: 0.4, basis: "est", note: "electrician's circuit extra where none is near" },
      "Conflicting vents removed: old box vents capped and shingled over, gable vents closed when the ridge system goes in so exhaust does not short-circuit the intake": { price: [75, 175], labor: 0.8, basis: "est", q: 4 },
      "Exhaust fans re-ducted to the exterior with insulated duct and a roof or wall cap with a damper": { price: [250, 550], labor: 0.6, basis: "est" },
      "Air sealing of the attic floor: top plates, wire and pipe penetrations foamed, IC-rated covers over can lights, the hatch weatherstripped": { price: [0.75, 1.75], labor: 0.7, basis: "est" },
      "Mold treatment of the sheathing and removal of wet insulation": { price: [2, 5], labor: 0.75, basis: "est" },
      "Blown insulation topped up to R-49 over the baffles": { price: [1, 2], labor: 0.45, basis: "est" },
      "Airflow check with smoke at the soffits, photos of every vent, cleanup and haul-off": { price: [100, 250], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "outdoor-kitchen": {
    op: 0.35,
    opNote: "residential design-build remodeler",
    benchmark: {
      unit: "linear ft",
      measures: "island length",
      price: [900, 1900],
      typicalQty: [10, 16],
      jobQty: 13,
      minJob: 6000,
      sources: ["Fixr 2025: outdoor kitchen avg $16,000 ($6,000-$30,000); framing $100-$300/linear ft; stone veneer $15-$25/sqft", "HomeAdvisor 2026: outdoor kitchen avg $16,533 ($6,269-$27,087); permits $250-$2,000"],
    },
    steps: {
      "Design and permits: island layout with the appliance cutout sheet, clearances from combustibles, gas load and electrical load listed, gas, electrical and plumbing permits and inspections": { price: [700, 1800], labor: 0.55, basis: "derived", q: 1, note: "design plus gas, electrical and plumbing permits (HomeAdvisor 2026 permits $250-$2,000)" },
      "Slab under the island: 4 in. 3,000-psi reinforced concrete on compacted gravel, sleeves set for the utilities": { price: [7, 12], labor: 0.45, basis: "est" },
      "Gas line: 3/4 in. black iron or CSST from the meter, or polyethylene from a propane tank, in a trench with tracer wire, shutoff valve at the island, pressure tested": { price: [16, 32], labor: 0.6, basis: "src", q: 30, note: "Fixr 2025 gas line $15-$25/linear ft plus the trench" },
      "Electrical circuits: dedicated 20 A GFCI circuits in conduit from the panel for the refrigerator, outlets and lighting, weatherproof in-use covers, by a licensed electrician": { price: [450, 1000], labor: 0.65, basis: "derived", q: 2, note: "Fixr 2025 electrical ~$500 average, over $1,500 on long runs" },
      "Water and drain: 1/2 in. PEX or copper supply with a frost-proof shutoff, 1-1/2 in. drain to the sewer or a dry well": { price: [25, 50], labor: 0.6, basis: "est" },
      "Island frame: galvanized steel stud frame skinned in cement board, or CMU block laid on the slab, appliance and door openings framed to the cutout sheet": { price: [160, 320], labor: 0.55, basis: "src", q: 13, note: "Fixr 2025 framing $100-$300/linear ft" },
      "Veneer: natural or manufactured stone, tile, brick or stucco over lath and scratch coat on every exposed face": { price: [20, 36], labor: 0.55, basis: "src", q: 90, note: "Fixr 2025 stone veneer $15-$25/sqft, natural stone $25-$50" },
      "Countertop: 3 cm granite, quartzite or porcelain slab, or poured concrete, with appliance and sink cutouts, eased edge, sealed": { price: [55, 100], labor: 0.35, basis: "src", q: 33, note: "Fixr 2025 granite $70-$140/sqft, concrete $50-$140" },
      "Appliances supplied and set: built-in 304 stainless grill with the stated burner output, side burner, outdoor-rated refrigerator, ice maker or kegerator as chosen": { price: [1100, 2800], labor: 0.1, basis: "derived", q: 3, note: "per appliance: side burner low, built-in grill high (HomeAdvisor 2026 grill $100-$5,000, refrigerator $400-$4,000)" },
      "Grill insulated jacket, stainless access doors, drawers, trash pull-out and vent panels fitted to the openings": { price: [200, 550], labor: 0.15, basis: "est", q: 4, note: "per piece: door, drawer bank, jacket or trash pull-out" },
      "Outdoor sink and faucet set and connected": { price: [400, 900], labor: 0.35, basis: "derived", note: "HomeAdvisor 2026 sink $215-$630" },
      "Pizza oven: insulated dome oven on its stand, vented, with a chimney cap": { price: [2500, 6000], labor: 0.2, basis: "derived", note: "HomeAdvisor 2026 $800-$2,000 unit only; Fixr 2025 $2,000-$14,000" },
      "Lighting: low-voltage task and under-counter LED with a transformer and timer": { price: [180, 350], labor: 0.5, basis: "src", note: "HomeAdvisor 2026 ~$260 per fixture" },
      "Bar overhang: 12 in. countertop overhang on steel or stone corbels for seating": { price: [90, 180], labor: 0.4, basis: "est" },
      "Gas and appliance startup: flexible connectors, leak test with the meter, orifice conversion for propane, ignition and flame checked on every burner": { price: [90, 200], labor: 0.9, basis: "est", q: 3, note: "per appliance" },
      "Final inspections, stone and countertop sealing, cleanup, owner walkthrough and appliance warranty registration": { price: [350, 800], labor: 0.75, basis: "est", q: 1 },
    },
  },
  "fire-pit-fireplace": {
    op: 0.3,
    opNote: "residential masonry and hardscape trade",
    benchmark: {
      unit: "unit",
      measures: "fire features built (masonry fire pit or outdoor fireplace)",
      price: [3500, 12000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 2000,
      sources: ["HomeAdvisor 2026: built-in masonry fire pit $1,000-$3,000+; natural-gas fire pit $400-$3,000; gas line $15-$25/linear ft", "Fixr 2025: 36 in. natural-gas burner kit $1,300-$2,000; stone fire pit $350-$3,010"],
    },
    steps: {
      "Design and code check: fuel type (wood, natural gas or propane), size, clearances from the house, fences and overhangs per local code, HOA approval, permit and gas or mechanical inspections": { price: [250, 650], labor: 0.6, basis: "est", q: 1, note: "includes the permit and gas inspection fees" },
      "Utility locate and excavation for the footing, spoils removed": { price: [200, 500], labor: 0.75, basis: "est", q: 1 },
      "Footing: 3,000-psi reinforced concrete slab or footing below frost depth under the feature": { price: [350, 650], labor: 0.45, basis: "est", q: 0.5, note: "small pours; ~0.5 cu yd under a fire pit, 1-2 under a fireplace" },
      "Gas line: 3/4 in. black iron, CSST or polyethylene underground with tracer wire, a key valve at the feature, pressure tested": { price: [18, 32], labor: 0.6, basis: "src", q: 25, note: "HomeAdvisor 2026 / Fixr 2025 gas line $15-$25/linear ft plus the trench" },
      "Fire pit structure: CMU or concrete block ring or square, cores grouted, with a steel fire ring or a stainless burner pan opening": { price: [600, 1300], labor: 0.55, basis: "derived", q: 1, note: "HomeAdvisor 2026 built-in masonry fire pit $1,000-$3,000+ all-in" },
      "Fireplace firebox: masonry firebox kit or firebrick-lined CMU firebox with a smoke shelf, damper and throat sized to the opening": { price: [3000, 6500], labor: 0.45, basis: "est" },
      "Chimney: CMU chimney or stainless Class A flue to the height the clearances require, with a spark-arrestor cap": { price: [150, 350], labor: 0.5, basis: "est" },
      "Firebrick lining set in refractory mortar on every fire-facing surface": { price: [25, 45], labor: 0.6, basis: "est", q: 12 },
      "Burner system: CSA-listed stainless burner and pan, match-lit or electronic ignition with a remote, lava rock or fire glass": { price: [900, 2000], labor: 0.2, basis: "src", q: 1, note: "Fixr 2025 burner kits: natural gas $1,300-$2,000, propane $400-$1,700" },
      "Veneer: natural or manufactured stone, brick or stucco over lath and scratch coat on every exposed face": { price: [22, 42], labor: 0.55, basis: "derived", q: 20, note: "Fixr 2025 stone veneer $15-$25/sqft material-heavy, natural stone $25-$50" },
      "Cap: bluestone, concrete or cast-stone cap set in mortar with a drip edge, or a seating ledge cap": { price: [40, 80], labor: 0.45, basis: "est", q: 12 },
      "Hearth: stone or concrete hearth slab in front of the firebox": { price: [30, 60], labor: 0.5, basis: "est" },
      "Wood-burning accessories: spark screen, grate and a cover": { price: [150, 400], labor: 0.1, basis: "est" },
      "Gas startup: burner connected, leak tested, flame height adjusted, ignition demonstrated": { price: [125, 300], labor: 0.9, basis: "est", q: 1 },
      "Cleanup, stone sealing, a supervised first burn after the mortar cures, owner instruction and inspection sign-off": { price: [175, 400], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "chimney-repair": {
    op: 0.3,
    opNote: "residential masonry and chimney trade",
    benchmark: {
      unit: "unit",
      measures: "chimneys repaired (repoint, crown, flashing, cap, waterproof)",
      price: [2800, 6500],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 350,
      sources: ["Fixr 2025: chimney crown replacement $1,000-$3,000; repointing $500-$2,500; flashing replacement $300-$800; cap $300-$600", "Fixr 2025: stainless liner avg $2,500 ($1,800-$4,000); chase cover $300-$700; sealing $150-$500"],
    },
    steps: {
      "Level 2 inspection: camera scan of the flue, exterior masonry, crown, cap and flashing photographed, moisture and spalling assessed, written report with the repair plan": { price: [250, 550], labor: 0.9, basis: "est", q: 1, note: "Fixr 2025: Level 1 under $100; Level 2 with a camera costs more" },
      "Access and protection: scaffolding, roof staging or a lift with fall protection, roof and landscaping below covered": { price: [250, 700], labor: 0.6, basis: "est", q: 1, note: "roof staging; full scaffold on a tall exterior chimney runs more" },
      "Tuckpointing: deteriorated mortar joints ground out 3/4 in. deep, dusted and repointed with Type N mortar matched in color and tooled to the original profile": { price: [10, 20], labor: 0.85, basis: "derived", q: 80, note: "Fixr 2025 repointing $500-$2,500 per chimney" },
      "Rebuild: spalled or leaning brickwork taken down to sound courses and rebuilt with matching brick and Type N mortar": { price: [45, 90], labor: 0.7, basis: "est" },
      "Crown: cracked crown removed and a new 2 in. cast concrete crown poured with a drip edge and bond break, or a sound crown sealed with elastomeric crown coat": { price: [700, 2000], labor: 0.7, basis: "src", q: 1, note: "Fixr 2025 crown replacement $1,000-$3,000; a sound crown sealed runs $300-$600" },
      "Flashing: new step flashing woven with the shingles and counter flashing let into a cut reglet in the mortar joints, cricket behind chimneys wider than 30 in.": { price: [25, 55], labor: 0.75, basis: "derived", q: 13, note: "Fixr 2025 flashing replacement $300-$800 per chimney" },
      "Chimney cap: stainless steel cap with spark screen, single or multi-flue, fastened to the crown or flue tile": { price: [300, 600], labor: 0.35, basis: "src", q: 1, note: "Fixr 2025 cap replacement $300-$600" },
      "Flue liner: insulated 316Ti stainless liner or a cast-in-place liner, sized to the appliance, connected with a top plate and cap": { price: [75, 140], labor: 0.4, basis: "derived", note: "Fixr 2025 stainless liner avg $2,500 ($1,800-$4,000) for a ~25 ft flue" },
      "Top-sealing damper with a cable control replacing a rusted throat damper": { price: [450, 850], labor: 0.35, basis: "est" },
      "Firebox repair: loose firebrick reset and joints repointed with refractory mortar": { price: [30, 60], labor: 0.75, basis: "est" },
      "Smoke chamber parged smooth with refractory mortar": { price: [40, 80], labor: 0.75, basis: "est" },
      "Waterproofing: breathable siloxane water repellent, two coats on every face": { price: [1.5, 3.5], labor: 0.7, basis: "derived", q: 80, note: "Fixr 2025 sealing $150-$500 per chimney" },
      "Chase cover: rusted metal cover replaced with a stainless cover with a drip edge and storm collar": { price: [350, 750], labor: 0.3, basis: "src", note: "Fixr 2025 chase cover $300-$700" },
      "Cleanup: staging struck, debris hauled, roof and gutters cleared of mortar, after photos and the closing report": { price: [150, 350], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "roofing": {
    op: 0.3,
    opNote: "residential re-roof contractor; sales and warranty overhead",
    benchmark: {
      unit: "sq boards",
      measures: "roof area in squares (measured, before waste)",
      price: [450, 700],
      typicalQty: [20, 30],
      jobQty: 25,
      minJob: 3500,
      sources: ["HomeGuide 2026: architectural shingles $400-$600 per square installed, $7,500-$16,000 average roof", "Roof tear-off guides 2026 (SquareDash, RoofingCalculatorHQ): tear-off $1.00-$2.40/sqft incl. dumpster; permit $100-$500", "JobFlex roofPackage catalog 2026: architectural $125 mat + $200 labor/sq; tear-off $55 + disposal $28/sq/layer (sell)"],
    },
    steps: {
      "Roof measurement report and pre-job inspection: aerial or on-roof measurement of area, pitch, eaves, rakes, ridges, hips and valleys; photos of the deck condition, flashings and every penetration": { price: [75, 250], labor: 0.6, basis: "est", q: 1, note: "aerial report ($20-$90) plus a 1-2 hr estimator visit; often absorbed as a sales cost" },
      "Building permit, HOA approval where required, and final inspection scheduling": { price: [150, 450], labor: 0, fee: true, basis: "src", q: 1, note: "residential re-roof permit; 2026 guides $100-$500; HOA fees extra where charged" },
      "Site protection: tarps over landscaping, AC units and the pool, plywood under the dumpster and along the drive, catch-all netting at the walls, satellite dish and gutter guards set aside": { price: [150, 350], labor: 0.8, basis: "est", q: 1 },
      "Tear-off of the existing roofing to the bare deck, number of layers stated, old felt and flashings removed, nails pulled or driven flush, deck swept": { price: [0.65, 1], labor: 0.95, basis: "derived", q: 2500, note: "one layer; add $0.40-$0.60/sqft per extra layer. Repo tear-off $55/sq/layer is the low end; guides bill $1.00-$2.40/sqft incl. dumpster" },
      "Disposal: roll-off dumpster delivered, hauled and dumped, landfill fees included": { price: [400, 750], labor: 0.1, basis: "derived", q: 1, note: "20-yd roll-off for about 25 squares, one layer; scales about $25-$35 per square per layer (repo $28/sq/layer)" },
      "Deck repair: rotted, soft or delaminated sheathing cut out and replaced with matching 1/2 in. CDX plywood or 7/16 in. OSB, nailed 6 in. o.c. at edges and 12 in. in the field": { price: [2.4, 3.75], labor: 0.5, basis: "derived", note: "repo $42 sheet + $35 labor per 32 sqft sheet; roofers bill $75-$120 per sheet" },
      "Ice and water shield: self-adhered SBS membrane at the eaves to 24 in. inside the warm wall, full width in valleys, and around chimneys, skylights and penetrations": { price: [0.95, 1.5], labor: 0.3, basis: "derived", q: 600, note: "repo membrane $0.60/sqft material plus install" },
      "Synthetic underlayment over the remaining deck, cap-nailed, 4 in. side laps and 6 in. end laps, run up the walls 4 in.": { price: [0.28, 0.45], labor: 0.4, basis: "derived", q: 1900, note: "repo synthetic $32/sq" },
      "Drip edge at eaves and rakes: 26-gauge galvanized steel or aluminum F5 profile, under the underlayment at the eaves and over it at the rakes, color matched": { price: [1.5, 2.6], labor: 0.35, basis: "derived", q: 250, note: "repo F-profile $1.50/lf material plus install" },
      "Starter strip at eaves and rakes with the factory sealant strip set at the edge for wind hold-down": { price: [0.85, 1.5], labor: 0.35, basis: "derived", q: 250, note: "repo starter $0.80/lf material plus install" },
      "Shingles supplied: architectural laminated asphalt, Class A fire rating, 130 mph wind rating, or Class 4 impact-resistant where specified, in the chosen color, delivered and rooftop loaded": { price: [125, 165], labor: 0.05, basis: "derived", q: 28, note: "per square supplied incl. 10-15% waste; repo architectural $125/sq; Class 4 impact-resistant about $175-$230/sq" },
      "Shingle installation: 6 nails per shingle at the manufacturer's nail line, offsets per the wrapper, hand-sealed at rakes and on steep or cold-weather work, straight courses chalked off the eaves": { price: [1.5, 2.1], labor: 0.95, basis: "derived", q: 2500, note: "field shingles only (underlayment, edges, cap and flashings carry their own labor); repo $200/sq install; 8/12+ pitch or 2 storeys adds 10-45%" },
      "Valleys: closed-cut valleys over the ice and water shield, or open valleys with 24 in. W-profile painted steel where specified": { price: [2.5, 4.5], labor: 0.8, basis: "derived", q: 30, note: "repo closed-cut $2.50/lf labor; open W-valley metal about $6.50/lf" },
      "Ridge and hip cap: matching high-profile cap shingles nailed and sealed per the manufacturer": { price: [4.5, 7.5], labor: 0.3, basis: "derived", q: 75, note: "high-profile cap $3-$4/lf material; repo standard cap $2.10/lf" },
      "Pipe boots and vents: new neoprene or lead flashing on every plumbing vent, new roof jacks on bath and kitchen exhaust vents, painted to match": { price: [45, 100], labor: 0.45, basis: "derived", q: 5, note: "repo boot $14-$28 + $25-$30 labor; lead boots and exhaust roof jacks at the high end" },
      "Wall flashings: 4x4 in. pre-bent step flashing at sidewalls, apron flashing at headwalls, counter flashing let into the mortar joint or behind the siding and sealed": { price: [6, 12], labor: 0.65, basis: "derived", q: 20, note: "repo step flashing $1.81 + $4 labor/lf, apron $6.20/lf, counter $10.50/lf" },
      "Chimney and skylight re-flashing: new base, step and counter flashing at the chimney with a cricket behind chimneys wider than 30 in.; new manufacturer flashing kit at each skylight": { price: [400, 900], labor: 0.6, basis: "derived", note: "per chimney or skylight; repo chimney kit $180-$380 + $250-$450 labor, skylight curb $270; cricket at the high end" },
      "Ridge vent: shingle-over ridge vent cut into the ridge with a 1 in. slot each side, end plugs, with matching soffit intake confirmed open": { price: [6, 10], labor: 0.35, basis: "derived", q: 40, note: "repo ridge vent $4.50 + $3 labor/lf" },
      "Gutter apron flashing at the eaves, tucked into the existing gutters so runoff clears the fascia": { price: [2.5, 4], labor: 0.35, basis: "derived", note: "repo gutter apron $2.20/lf material plus install" },
      "Final cleanup: magnetic nail sweep of the lawn, beds and driveway, gutters cleared of tear-off grit, debris hauled, walk-through with the before-and-after photos": { price: [250, 450], labor: 0.9, basis: "derived", q: 1, note: "repo cleanup lump $250" },
      "Manufacturer system warranty registration (lifetime limited or enhanced system warranty as specified) and the workmanship warranty issued in writing": { price: [50, 300], labor: 0.4, basis: "est", q: 1, note: "standard registration costs little; an enhanced system warranty fee sits at the high end" },
    },
  },
  "residential-roof-repair": {
    op: 0.4,
    opNote: "small service calls; trip, minimums, low crew utilization",
    benchmark: {
      unit: "sqft",
      measures: "repair area in sqft (shingles removed and rewoven), visit costs included",
      price: [20, 40],
      typicalQty: [20, 80],
      jobQty: 50,
      minJob: 350,
      sources: ["HomeGuide 2026: roof leak repair $150-$2,000 depending on the source", "HomeGuide 2026: flashing repair $200-$500 minor, $500-$1,500 major", "HomeGuide 2026: cracked pipe boot replacement $250-$550"],
    },
    steps: {
      "Leak diagnosis: roof walk and attic inspection with a moisture meter, hose test where the entry point is not obvious, photo report marking each leak source and the repair proposed": { price: [125, 350], labor: 0.9, basis: "est", q: 1 },
      "Access and safety: ladder staging, roof anchors and harness, tarps over the landscaping below the work area": { price: [75, 250], labor: 0.8, basis: "est", q: 1 },
      "Temporary dry-in: tarp or peel-and-stick patch over the damaged area to stop active leaking until the repair date": { price: [250, 700], labor: 0.6, basis: "est", note: "emergency tarp or peel-and-stick patch; after-hours calls at the high end" },
      "Remove damaged shingles in the repair area, lift and un-seal the surrounding courses, pull nails and clear the deck": { price: [1.5, 3], labor: 1, basis: "derived", q: 50, note: "hand removal on a small area, about 3x the repo's $55/sq tear-off rate" },
      "Replace rotted or soft decking under the repair area with matching plywood, nailed to the rafters": { price: [4, 8], labor: 0.6, basis: "derived", note: "repo $77 per sheet installed with a small-quantity factor" },
      "Ice and water membrane over the exposed deck at the repair area, lapped under the existing underlayment above": { price: [1.5, 2.5], labor: 0.5, basis: "derived", q: 50, note: "patch-scale of the $0.95-$1.50/sqft reroof rate" },
      "Weave in new shingles matched to the existing profile and color, nailed at the nail line and hand-sealed under every lifted tab": { price: [6, 11], labor: 0.75, basis: "derived", q: 50, note: "hand-woven repair about $600-$1,100 per square vs about $330 per square in a full reroof" },
      "Re-flash plumbing vents: new neoprene or lead pipe boots, or a boot collar over a cracked boot, sealed and painted to match": { price: [150, 350], labor: 0.65, basis: "src", note: "HomeGuide 2026: cracked pipe boot replacement $250-$550 as a stand-alone call" },
      "Rebuild the wall or chimney flashing: new step flashing woven with the shingles, apron at the headwall, counter flashing let into the mortar joint or behind the siding and sealed": { price: [25, 50], labor: 0.7, basis: "derived", note: "HomeGuide 2026: flashing repair $200-$500 minor, $500-$1,500 major, over 10-30 lf" },
      "Valley repair: debris cleared, cracked valley metal replaced or the closed valley re-cut and sealed with new membrane under it": { price: [15, 35], labor: 0.7, basis: "est" },
      "Reseal exposed fasteners, roof jacks, vent collars and skylight curbs with polyurethane roof sealant; cracked collars replaced": { price: [15, 35], labor: 0.85, basis: "est", q: 4, note: "per fastener group, jack, collar or curb sealed" },
      "Roof tune-up over the rest of the roof: nail pops driven and sealed, lifted or slipped tabs re-fastened and hand-sealed, debris cleared from valleys and behind the chimney": { price: [125, 350], labor: 0.9, basis: "est", q: 1 },
      "Haul-away of the removed material, magnetic sweep below the repair, photos of the finished repair": { price: [50, 150], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "commercial-roofing": {
    op: 0.2,
    opNote: "commercial specialty subcontractor",
    benchmark: {
      unit: "sq boards",
      measures: "roof area in squares (low-slope, tear-off to deck)",
      price: [850, 1450],
      typicalQty: [100, 300],
      jobQty: 200,
      minJob: 12000,
      sources: ["Commercial TPO guides 2025-26 (Angi, HomeGuide, Schoenherr): full replacement with tear-off and insulation $8.50-$15.50/sqft; TPO alone $6.50-$11.50/sqft", "HomeGuide 2026: polyiso insulation adds $0.50-$3.00/sqft; tear-off adds $1-$2/sqft", "JobFlex lowSlope/commercial catalogs 2026: TPO 60-mil $290/sq, R-30 polyiso $293/sq, tear-off $95 + disposal $45/sq/layer, GC + insurance 10.5%"],
    },
    steps: {
      "Pre-bid roof survey: core cuts to confirm the existing assembly and deck type, infrared or nuclear moisture scan for wet insulation, drain and edge inventory, roof plan with the findings": { price: [1500, 3500], labor: 0.7, basis: "derived", q: 1, note: "repo core cut $190 each (4-8 cores) plus an infrared or nuclear scan; scales with roof size" },
      "Submittals and manufacturer pre-installation notice: product data, shop drawings, tapered layout, fastening pattern for the wind zone, and the system warranty application": { price: [750, 2000], labor: 0.9, basis: "est", q: 1 },
      "Asbestos survey of the existing roof before tear-off (NESHAP) by a licensed inspector, with abatement quoted separately if found": { price: [1000, 2500], labor: 0, fee: true, basis: "derived", note: "repo asbestos survey $1,650, billed at cost (licensed inspector + lab)" },
      "Permit, plan review and inspections at the jurisdiction's valuation-based fee": { price: [1500, 4500], labor: 0, fee: true, basis: "derived", q: 1, note: "valuation-based: about $275 + 1.2% of the contract, $450 minimum (repo); scales with job value" },
      "Mobilization and safety: crane or hoist for material loading, debris chute, staging and laydown area, interior protection under the work, site-specific fall-protection plan with warning lines and edge guards": { price: [5000, 10000], labor: 0.5, basis: "derived", q: 1, note: "repo mobilization $2,400 + safety plan $950 + crane $650 mob and $340/hr + hoist $350 + warning lines; scales with roof size" },
      "Tear-off of the existing membrane and insulation to the deck, layers stated, gravel vacuumed on built-up roofs, wet insulation removed": { price: [1, 1.75], labor: 0.9, basis: "derived", q: 20000, note: "repo single-ply + insulation $95/sq/layer, mod bit $110, gravel BUR $195 + $75 vacuum; plus general conditions" },
      "Haul and dispose of tear-off debris by the container, landfill fees included": { price: [30, 50], labor: 0.15, basis: "derived", q: 240, note: "repo disposal $45/sq/layer at about 1-1.5 cu yd per square; 30-yd roll-off $700-$1,100 with landfill" },
      "Deck repair: deteriorated metal deck panels or rotted wood deck cut out and replaced, rusted deck wire-brushed and primed": { price: [5, 12], labor: 0.55, basis: "est", note: "metal deck panels $6-$12/sqft, wood deck $5-$8/sqft" },
      "Wood nailers: pressure-treated 2x stock at perimeter edges, curbs and expansion joints, anchored to the deck and built up flush with the insulation": { price: [6, 12], labor: 0.65, basis: "derived", q: 600, note: "repo nailer $2 + $4.20 labor/lf per 2x course, stacked to the insulation height" },
      "Vapor retarder over the deck: self-adhered sheet or two-ply asphalt, sealed at walls and penetrations": { price: [0.8, 1.5], labor: 0.4, basis: "est" },
      "Insulation: polyiso flat stock in two layers with staggered joints to the specified R-value (R-30 typical, LTTR rated), mechanically fastened or adhered in low-rise foam": { price: [2.6, 3.8], labor: 0.2, basis: "derived", q: 20000, note: "repo polyiso R-30 two layers $235 + $58/sq plus $13/sq plates; plus general conditions" },
      "Tapered insulation and crickets to the drains at 1/4 in. per foot, laid per the approved tapered plan": { price: [3.5, 5.5], labor: 0.28, basis: "derived", note: "repo tapered $3.25 + $1.25 labor/sqft" },
      "Cover board: 1/2 in. gypsum-fiber or high-density polyiso over the insulation, fastened or adhered": { price: [0.85, 1.5], labor: 0.3, basis: "derived", q: 20000, note: "repo 1/2 in HD polyiso $86/sq, 1/2 in gypsum $145/sq" },
      "Membrane supplied and laid: 60-mil TPO or PVC mechanically fastened or fully adhered, 60-mil EPDM adhered, or 2-ply SBS modified bitumen torch or cold-applied, sheets lapped per the manufacturer": { price: [2.4, 3.75], labor: 0.5, basis: "derived", q: 20000, note: "repo 60-mil TPO mech $290/sq, adhered $335 + $75 adhesive, EPDM adhered $350 + adhesive, mod bit torch $470; seams itemized separately" },
      "Seams: hot-air welded and probed on single-ply, or torch or cold-adhesive lapped on modified bitumen, with cut-edge sealant on reinforced sheets": { price: [0.75, 1.5], labor: 0.85, basis: "est", q: 2200, note: "welding and probing; about 0.11 lf of seam per sqft of roof" },
      "Base flashing at parapets and walls: membrane flashing to the termination height, termination bar and sealant, surface-mount or reglet counterflashing": { price: [18, 34], labor: 0.55, basis: "derived", q: 400, note: "repo base flashing $17/lf + term bar $5.60/lf + counterflashing $11/lf" },
      "Perimeter edge metal: ANSI/SPRI ES-1 rated drip edge or gravel stop, or coping cap on parapets, 24-gauge Kynar steel or .050 aluminum with cleats and splice plates": { price: [15, 32], labor: 0.4, basis: "derived", q: 566, note: "repo edge metal $15/lf, coping $31/lf" },
      "Curbs and penetrations: rooftop unit and skylight curbs re-flashed, pipe boots, pourable sealer pockets replacing old pitch pans, flashing-grade sealant at every termination": { price: [150, 450], labor: 0.6, basis: "derived", q: 12, note: "repo pipe boot $100, pitch pocket $143, curb $355, RTU curb $575" },
      "Roof drains: new drain bodies, clamping rings and strainers, or retrofit drain inserts, plus overflow drains or scuppers where code requires": { price: [500, 1000], labor: 0.55, basis: "derived", q: 4, note: "repo drain insert $515, new drain $905, overflow drain $980" },
      "Walkway pads to and around rooftop units and at the access point, welded or adhered to the membrane": { price: [10, 16], labor: 0.4, basis: "derived", q: 150, note: "repo walkway $8 + $5 labor/lf" },
      "Manufacturer final inspection and issuance of the no-dollar-limit system warranty (15, 20 or 25-year as specified) plus the contractor's workmanship warranty": { price: [4000, 7000], labor: 0.1, fee: true, basis: "derived", q: 1, note: "manufacturer NDL fee about $18-$45 per square plus the $850 inspection, billed at cost (repo); scales with roof size" },
      "Daily cleanup, debris chute takedown, magnetic sweep at grade, demobilization and close-out documents": { price: [1500, 3500], labor: 0.8, basis: "est", q: 1, note: "scales with job duration" },
    },
  },
  "siding-installation": {
    op: 0.3,
    opNote: "residential specialty trade",
    benchmark: {
      unit: "sqft",
      measures: "wall area sided, net of openings",
      price: [7, 14],
      typicalQty: [1500, 2500],
      jobQty: 2000,
      minJob: 2500,
      sources: ["HomeGuide 2026: fiber-cement siding $6-$15/sqft installed, labor $4-$9/sqft", "HomeGuide/This Old House 2026: vinyl siding $4-$8/sqft installed", "Modernize/Dropcurb 2026: siding removal $0.25-$1.50/sqft"],
    },
    steps: {
      "Site measure and material takeoff: every elevation measured net of openings, siding profile, exposure and color chosen from samples, photos of the existing conditions and trim details": { price: [150, 400], labor: 0.9, basis: "est", q: 1 },
      "Building permit and inspections at the jurisdiction's fee": { price: [100, 400], labor: 0, fee: true, basis: "est", note: "residential re-siding permit where required" },
      "Site protection: landscaping tarped, windows and AC condenser covered, walkways and deck protected, dumpster set on plywood": { price: [200, 500], labor: 0.8, basis: "est", q: 1 },
      "Remove the existing siding, trim and house wrap to the sheathing, fasteners pulled, shutters, lights and downspouts detached and set aside": { price: [0.6, 1.4], labor: 0.95, basis: "src", q: 2000, note: "Modernize/Dropcurb 2026: removal $0.25-$1.50/sqft (vinyl low, wood high); asbestos-cement $7-$10/sqft by abatement" },
      "Disposal: roll-off dumpster and landfill fees; asbestos-cement siding removed by a licensed abatement contractor where present": { price: [450, 900], labor: 0.1, basis: "est", q: 1, note: "20-30 yd roll-off; scales with wall area; asbestos abatement priced separately" },
      "Sheathing repair: rotted or delaminated OSB or plywood cut out and replaced, rotted studs and rim sistered": { price: [3.5, 7], labor: 0.6, basis: "est", note: "OSB or plywood replaced at $110-$225 per sheet incl. stud or rim sistering" },
      "Weather-resistive barrier: house wrap lapped shingle-style, seams taped, sealed at the sill and every penetration, with rain-screen furring where the product or climate calls for it": { price: [0.45, 0.85], labor: 0.6, basis: "src", q: 2000, note: "R-Value Associates 2026: house wrap installed $0.30-$0.70/sqft; Homewyse $0.70-$0.86/sqft" },
      "Opening flashing: self-adhered flashing tape at sills, jambs and heads of every window and door, sill pan formed, metal drip cap over the head trim integrated into the house wrap": { price: [50, 130], labor: 0.6, basis: "est", q: 16 },
      "Continuous exterior insulation: 1 in. rigid foam or mineral wool board over the house wrap with furring strips into the studs": { price: [1.75, 3.5], labor: 0.45, basis: "est" },
      "Starter strip and corners: level starter at the base, outside and inside corner posts or 5/4 x 4 corner boards, plumb and flashed": { price: [3.5, 8], labor: 0.5, basis: "est", q: 290 },
      "Siding installed: fiber-cement lap (5/16 in., 7 in. exposure) blind-nailed 16 in. o.c. into studs with joint flashing at butt ends, or vinyl double-4 hung loose with 1/4 in. expansion gaps, or engineered wood lap, per the manufacturer": { price: [4.5, 8.5], labor: 0.55, basis: "src", q: 2000, note: "HomeGuide 2026: fiber-cement $6-$15/sqft and vinyl $4-$8/sqft installed; siding-only share (vinyl $3.50-$5.50, fiber-cement $6-$10)" },
      "Window and door trim: 5/4 x 4 fiber-cement or PVC casing, or J-channel with drip cap on vinyl, mitered and back-caulked": { price: [5, 11], labor: 0.55, basis: "est", q: 256 },
      "Soffit and fascia: vented aluminum or fiber-cement soffit panels with F-channel, and fascia wrap or 1x8 fascia boards": { price: [10, 22], labor: 0.5, basis: "est" },
      "Accessories: gable vents, dryer and bath exhaust hoods, light and outlet mounting blocks, hose-bib blocks, all flashed into the siding": { price: [45, 120], labor: 0.5, basis: "est", q: 8 },
      "Sealant: paintable elastomeric caulk at trim-to-siding joints, butt joints and penetrations, color matched": { price: [0.75, 1.75], labor: 0.7, basis: "est", q: 400 },
      "Field paint: cut ends primed, two coats of 100% acrylic exterior paint on siding and trim": { price: [1.5, 3], labor: 0.8, basis: "est" },
      "Detach and reset: light fixtures, shutters, house numbers, downspouts and hose bibs re-hung on the new siding with sealed mounting blocks": { price: [35, 90], labor: 0.9, basis: "est", q: 10 },
      "Final cleanup: magnetic nail sweep, debris hauled, walk-through of every elevation, manufacturer warranty registration": { price: [200, 500], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "residential-siding-repair": {
    op: 0.4,
    opNote: "small repair calls; trip and minimum-charge overhead",
    benchmark: {
      unit: "sqft",
      measures: "repair area in sqft, visit costs included",
      price: [18, 40],
      typicalQty: [30, 100],
      jobQty: 65,
      minJob: 250,
      sources: ["HomeGuide 2026: siding repair $2-$14/sqft, $200-$1,100 on average", "HomeGuide 2026: extensive section replacement $4-$16/sqft; repair labor $40-$80/hr"],
    },
    steps: {
      "Damage assessment: every elevation walked, soft sheathing probed, moisture readings at the suspect areas, existing product and profile identified, photo report with the repair plan": { price: [100, 250], labor: 0.9, basis: "est", q: 1 },
      "Material matching: matching profile, texture and color sourced from the manufacturer, salvage or custom milling, or the closest current match with a paint plan approved by the owner": { price: [50, 200], labor: 0.6, basis: "est", q: 1, note: "sourcing time plus the salvage or custom-milled stock premium" },
      "Access: ladders, pump jacks or a lift for upper-storey repair areas": { price: [150, 450], labor: 0.4, basis: "est", note: "pump jacks or a lift for a day" },
      "Remove the damaged siding pieces and trim, unlocking or cutting the surrounding courses without damaging them": { price: [1, 2.5], labor: 1, basis: "derived", q: 65, note: "careful unlocking of the surrounding courses; about 2x the $0.25-$1.50/sqft full-removal rate" },
      "Sheathing and framing repair behind the damaged siding: rotted OSB or plywood replaced, rotted studs or rim sistered": { price: [5, 10], labor: 0.65, basis: "est" },
      "Weather barrier restored: new house wrap patch lapped into the existing barrier, flashing tape at any opening inside the repair area": { price: [0.75, 1.5], labor: 0.6, basis: "derived", q: 65, note: "patch-scale of the $0.30-$0.86/sqft house-wrap rate" },
      "Matching siding pieces installed and interlocked with the existing courses, blind or face-nailed per the product, joints flashed": { price: [6, 12], labor: 0.65, basis: "src", q: 65, note: "HomeGuide 2026: siding repair $2-$14/sqft; section replacement $4-$16/sqft" },
      "Rotted trim, corner boards or window casing replaced with matching PVC, wood or fiber-cement pieces": { price: [8, 18], labor: 0.65, basis: "est" },
      "Damaged or missing accessory pieces replaced: vent hoods, mounting blocks, J-channel and corner caps": { price: [40, 110], labor: 0.5, basis: "est", q: 2 },
      "Re-caulk butt joints, trim and penetrations in the repair area with color-matched elastomeric sealant": { price: [1, 2.5], labor: 0.8, basis: "est", q: 50 },
      "Prime and paint the new pieces and feather the finish into the adjacent siding for a match": { price: [2, 4], labor: 0.8, basis: "est", q: 65 },
      "Re-fasten loose, popped or wind-lifted panels across the elevation and re-lock unzipped vinyl seams": { price: [75, 250], labor: 0.9, basis: "est", q: 1 },
      "Haul-off of removed material, magnetic sweep below the work, photos of the finished repair": { price: [50, 150], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "gutter-installation": {
    op: 0.3,
    opNote: "residential specialty trade",
    benchmark: {
      unit: "linear ft",
      measures: "gutter length along the eaves (downspouts and fittings in the rate)",
      price: [10, 18],
      typicalQty: [120, 200],
      jobQty: 160,
      minJob: 400,
      sources: ["HomeGuide 2026: seamless gutters $6-$20/lf installed; aluminum $900-$2,400 average job", "HomeGuide 2026: seamless downspouts $5-$16/lf; old gutter removal $1-$2/lf", "This Old House 2026: micro-mesh guards about $9/lf installed"],
    },
    steps: {
      "Measure and layout: fascia runs measured, downspout locations and discharge points set, fall of 1/4 in. per 10 ft toward the outlets, profile and color chosen from samples": { price: [50, 150], labor: 0.9, basis: "est", q: 1 },
      "Remove the existing gutters and downspouts, hangers pulled, holes sealed, metal recycled": { price: [1, 2], labor: 0.9, basis: "src", note: "HomeGuide 2026: old gutter removal $1-$2/lf" },
      "Fascia repair: rotted or split fascia replaced with primed 1x6 or 2x6 wood or PVC board before the new gutter goes up": { price: [10, 20], labor: 0.65, basis: "est", note: "primed 1x6/2x6 wood or PVC fascia replaced" },
      "Fascia wrap: .019 in. aluminum coil bent on site over the fascia, color matched to the gutter": { price: [4, 8], labor: 0.6, basis: "est" },
      "Seamless gutters: 5 in. or 6 in. K-style .032 in. aluminum (half-round, steel or copper where specified) roll-formed on site in continuous lengths and hung to the set fall": { price: [5, 8.5], labor: 0.55, basis: "src", q: 160, note: "HomeGuide 2026: seamless aluminum $6-$12/lf installed (labor $3-$7/lf) with hangers and fittings, which are itemized here; 6 in about +25%" },
      "Hidden hangers with screws into the rafter tails every 24 in., every 16 in. in snow and ice regions": { price: [2, 3.5], labor: 0.5, basis: "est", q: 80 },
      "Miters and end caps: inside and outside box miters or strip miters, end caps sealed with gutter-grade sealant": { price: [15, 35], labor: 0.5, basis: "est", q: 8, note: "box miters at the high end, end caps at the low end" },
      "Downspouts: 2x3 in. or 3x4 in. aluminum, strapped every 10 ft, routed to the discharge point": { price: [5.5, 10], labor: 0.5, basis: "src", q: 60, note: "HomeGuide 2026: seamless downspouts $5-$16/lf installed" },
      "Outlets, elbows and straps: outlet tubes cut and sealed into the gutter, A and B elbows at the offsets and the discharge": { price: [8, 18], labor: 0.5, basis: "est", q: 16 },
      "Gutter apron flashing tucked under the shingles and into the gutter so runoff cannot run behind it": { price: [2.5, 4.5], labor: 0.4, basis: "derived", note: "roofing repo gutter apron $2.20/lf material plus install" },
      "Gutter guards: stainless micro-mesh or perforated aluminum screens screwed to the gutter lip, or a reverse-curve system where specified": { price: [7, 16], labor: 0.4, basis: "src", note: "This Old House/HomeAdvisor 2025-26: micro-mesh about $9/lf installed, $5-$15/lf" },
      "Underground drain lines: 4 in. corrugated or SDR-35 PVC from the downspouts to daylight, trench cut and backfilled": { price: [12, 25], labor: 0.7, basis: "est", note: "trenched 4 in pipe to daylight in diggable soil" },
      "Pop-up emitters, catch basins or a dry well at the discharge, and splash blocks or extensions where lines stay above grade": { price: [60, 200], labor: 0.4, basis: "est", note: "pop-up emitter or catch basin; a dry well runs $800-$2,500" },
      "Water test: every run flooded from the roof to confirm fall, flow and sealed joints, adjustments made": { price: [40, 120], labor: 1, basis: "est", q: 1 },
      "Cleanup: debris and scrap hauled, metal recycled, walk-through of every run, workmanship warranty issued": { price: [50, 150], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "window-door": {
    op: 0.3,
    opNote: "residential specialty installer",
    benchmark: {
      unit: "unit",
      measures: "openings replaced (windows and exterior doors), full-frame",
      price: [900, 1700],
      typicalQty: [6, 14],
      jobQty: 10,
      minJob: 500,
      sources: ["HomeGuide 2026: vinyl windows $350-$1,500 per window installed", "Window replacement guides 2025: full-frame $1,300-$1,800 per window, retrofit $700-$1,100", "HomeGuide 2026: front door replacement $505-$1,898; sliding glass door $900-$3,500 installed"],
    },
    steps: {
      "Field measure: every opening measured at three points for width and height, rough opening and wall depth checked, egress, tempered-glass and U-factor requirements noted, product order confirmed against the schedule": { price: [100, 300], labor: 0.9, basis: "est", q: 1 },
      "Permit and inspection at the jurisdiction's fee": { price: [75, 300], labor: 0, fee: true, basis: "est", note: "window/door permit where required" },
      "Interior and exterior protection: floors, furniture and blinds covered, plants tarped, dust barriers at the work rooms": { price: [100, 300], labor: 0.85, basis: "est", q: 1 },
      "Lead-safe work practices (EPA RRP): containment, HEPA cleanup and certified crew on a pre-1978 home": { price: [300, 900], labor: 0.7, basis: "est", note: "RRP containment and cleaning adds about $50-$150 per opening" },
      "Remove the existing windows and doors: sashes, frames, stops and trim pulled, opening cleaned to the framing": { price: [60, 150], labor: 0.9, basis: "est", q: 10 },
      "Rough-opening repair: rotted sill, jack studs or sheathing replaced and the opening re-squared": { price: [150, 450], labor: 0.65, basis: "est" },
      "Sill pan and flashing at every opening: sloped flexible or preformed sill pan, self-adhered jamb flashing, head flashing lapped under the house wrap": { price: [40, 100], labor: 0.6, basis: "est", q: 10 },
      "Windows supplied and set: vinyl, fiberglass or clad-wood units with double-pane low-E argon glass meeting the ENERGY STAR U-factor and SHGC for the climate zone, shimmed plumb and square, fins fastened per the manufacturer": { price: [500, 950], labor: 0.3, basis: "src", q: 9, note: "HomeGuide 2026: vinyl windows $350-$1,500 installed, labor $100-$500; this line is unit + setting only" },
      "Exterior doors supplied and hung: pre-hung fiberglass or steel entry, sliding or French patio door, threshold bedded in sealant, shimmed at hinges and strike, 3 in. screws into the framing": { price: [1000, 2500], labor: 0.28, basis: "src", q: 1, note: "HomeGuide 2026: exterior door installed $420-$1,688, fiberglass entry $400-$2,800, sliding glass door $900-$3,500" },
      "Insulate and seal each opening: low-expansion foam at the shim gap, backer rod and sealant at the interior line": { price: [20, 50], labor: 0.75, basis: "est", q: 10 },
      "Exterior trim: 5/4 PVC or fiber-cement casing, brickmould, or aluminum coil wrap over the existing trim, drip cap at the head": { price: [5, 11], labor: 0.55, basis: "est", q: 153 },
      "Interior finish carpentry: jamb extensions, stool and apron, casing to match the existing profile, nailed, filled and caulked": { price: [5, 12], labor: 0.7, basis: "est", q: 160 },
      "Hardware: locksets, deadbolts and handle sets on doors, sash locks, screens and window openers, keyed alike where asked": { price: [50, 200], labor: 0.3, basis: "est", q: 2, note: "per lockset or handleset; window locks and screens come with the units" },
      "Exterior sealant: color-matched polyurethane at the trim-to-siding and trim-to-frame joints": { price: [1, 2.5], labor: 0.65, basis: "est", q: 250 },
      "Paint or stain of the new interior trim, two coats, to match the existing": { price: [1.5, 3.5], labor: 0.85, basis: "est" },
      "Adjustment and test: doors swung and latched, windows tilted and locked, weatherstrip checked, screens fitted, owner shown the operation": { price: [75, 200], labor: 1, basis: "est", q: 1 },
      "Haul-away of the old units and debris, cleanup of every opening, manufacturer warranty registration": { price: [150, 400], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "window-replacement": {
    op: 0.35,
    opNote: "in-home-sales replacement firm; heavy marketing overhead",
    benchmark: {
      unit: "unit",
      measures: "windows replaced",
      price: [750, 1400],
      typicalQty: [6, 14],
      jobQty: 10,
      minJob: 600,
      sources: ["HomeGuide 2026: vinyl windows $350-$1,500 per window installed, labor $100-$500", "Window replacement guides 2025: retrofit $700-$1,100, full-frame $1,300-$1,800 per window installed"],
    },
    steps: {
      "In-home measure and product specification: each opening measured, insert or full-frame decided per opening, glazing package chosen (double or triple pane, low-E, argon, NFRC U-factor 0.27 or better in cold zones), grids, colors, tempered locations": { price: [100, 300], labor: 0.9, basis: "est", q: 1 },
      "Permit and energy-code inspection at the jurisdiction's fee": { price: [75, 300], labor: 0, fee: true, basis: "est", note: "window permit where required" },
      "EPA lead-safe (RRP) containment, HEPA cleanup and certified crew": { price: [300, 900], labor: 0.7, basis: "est" },
      "Interior protection: blinds and treatments taken down, furniture moved and covered, floors protected at every window": { price: [100, 250], labor: 0.9, basis: "est", q: 1 },
      "Insert removal: sashes, balances and stops removed leaving the sound existing frame, pocket cleaned and the sill checked for rot": { price: [40, 90], labor: 0.95, basis: "derived", note: "removal share of the $150-$350 retrofit labor per window (2025 guides)" },
      "Full-frame removal: whole window, frame and exterior trim removed to the rough opening": { price: [90, 200], labor: 0.9, basis: "derived", note: "removal share of the $300-$700 full-frame labor per window (2025 guides)" },
      "Rough-opening repair: rotted sill, jamb studs or sheathing replaced before the new unit goes in": { price: [150, 450], labor: 0.65, basis: "est" },
      "Full-frame flashing: sloped sill pan, self-adhered jamb flashing and head flashing lapped into the house wrap": { price: [50, 110], labor: 0.6, basis: "est" },
      "Replacement windows supplied and set: welded vinyl or fiberglass frames, double-pane low-E argon glass, shimmed square, screwed through the jambs, NFRC labels left on for the inspection": { price: [450, 900], labor: 0.25, basis: "src", q: 10, note: "HomeGuide 2026: vinyl windows $350-$1,500 installed; retrofit materials $200-$700 + labor $150-$350" },
      "Perimeter insulation and seal: low-expansion foam at the gap, backer rod and interior sealant": { price: [20, 50], labor: 0.75, basis: "est", q: 10 },
      "Exterior finish: aluminum coil wrap over the exterior frame and trim, or new PVC casing, sealed with color-matched polyurethane": { price: [5, 11], labor: 0.55, basis: "est", q: 150, note: "aluminum coil capping about $75-$150 per window" },
      "Interior finish: stops, jamb extensions and casing re-set or replaced to match the existing, caulked and ready for paint": { price: [3, 8], labor: 0.75, basis: "est", q: 140 },
      "Screens, sash locks, grids and tilt-in operation checked on every unit, hardware adjusted": { price: [10, 30], labor: 1, basis: "est", q: 10 },
      "Haul-away of the old windows, glass and debris": { price: [100, 300], labor: 0.4, basis: "est", q: 1 },
      "Final cleanup of every room, walk-through, manufacturer and glass-seal warranty registration": { price: [100, 250], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "garage-door": {
    op: 0.3,
    opNote: "residential specialty trade",
    benchmark: {
      unit: "unit",
      measures: "garage doors replaced with opener (16x7 double; a single door runs about 60%)",
      price: [2000, 3800],
      typicalQty: [1, 2],
      jobQty: 1.5,
      minJob: 400,
      sources: ["HomeGuide 2026: 16x7 insulated garage door $1,200-$2,500 installed; R-18+ $3,000-$4,000", "HomeGuide 2026: garage door opener installed $300-$900", "HomeGuide 2026: insulated door install labor $150-$500 single, $300-$700 double"],
    },
    steps: {
      "Site measure: opening width and height, headroom, side room and backroom, header and floor level checked, outlet location noted, door style, insulation R-value, windows and color chosen": { price: [50, 150], labor: 0.9, basis: "est", q: 1, note: "often folded into the sale" },
      "Remove the existing door, tracks, springs (torsion springs unwound with winding bars) and the old opener, all hauled away": { price: [100, 225], labor: 0.8, basis: "est", q: 1.5, note: "tear-down of door, tracks, springs and opener with haul-away" },
      "Jamb and header repair: rotted jambs replaced with pressure-treated lumber or PVC-wrapped stock, a spring-anchor pad added where the header cannot hold the torsion bracket": { price: [15, 35], labor: 0.6, basis: "est" },
      "Door sections supplied: 25-gauge steel with 2 in. polyurethane insulation (R-16 or higher), or a 3-layer, carriage-style or full-view aluminum door as chosen, with windows and decorative hardware": { price: [900, 1900], labor: 0.05, basis: "derived", q: 1.5, note: "16x7 two-inch polyurethane steel; HomeGuide 2026 insulated 16x7 $1,200-$2,500 installed; single doors about 55-65% of this" },
      "Track and hardware: 2 in. galvanized vertical and horizontal tracks, 14-gauge hinges, ball-bearing nylon rollers, reinforcing struts on doors over 12 ft, perforated angle hangers": { price: [250, 550], labor: 0.6, basis: "derived", q: 1.5, note: "hardware plus hanging the sections; HomeGuide 2026 install labor $300-$700 for a double door" },
      "Torsion spring system: cycle-rated springs (10,000 or 25,000 cycles), cable drums, cables and bearing plates, wound to balance the door": { price: [150, 350], labor: 0.45, basis: "est", q: 1.5 },
      "Weather seal: bottom astragal in an aluminum retainer, PVC stop moulding with vinyl weatherstrip at the jambs and header": { price: [2.5, 6], labor: 0.45, basis: "est", q: 69 },
      "Opener supplied and installed: belt, chain or wall-mount jackshaft drive, 3/4 HP or 1-1/4 HP DC motor, battery backup where code requires, Wi-Fi control, two remotes, wall console and keypad": { price: [450, 850], labor: 0.35, basis: "src", q: 1.5, note: "HomeGuide 2026: opener installed $300-$900; belt drive with battery backup and Wi-Fi mid-to-high" },
      "Safety setup per UL 325: photo eyes at 6 in. off the floor, auto-reverse force and travel limits set and tested, emergency release shown to the owner": { price: [50, 125], labor: 0.9, basis: "est", q: 1.5 },
      "Ceiling outlet: dedicated receptacle within 3 ft of the opener on a GFCI-protected circuit": { price: [150, 350], labor: 0.7, basis: "est" },
      "Wind-rated door and bracing package per the local wind-load requirement": { price: [300, 800], labor: 0.3, basis: "est" },
      "Exterior trim: PVC garage-door jamb wrap and header trim, sealed and color matched": { price: [8, 16], labor: 0.5, basis: "est" },
      "Balance, adjustment, lubrication and a full operation test, owner instruction, cleanup and manufacturer warranty registration": { price: [75, 200], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "decking": {
    op: 0.3,
    opNote: "residential specialty builder",
    benchmark: {
      unit: "sqft",
      measures: "deck surface area",
      price: [30, 60],
      typicalQty: [240, 400],
      jobQty: 320,
      minJob: 4000,
      sources: ["HomeGuide 2026: pressure-treated deck $25-$50/sqft installed, labor $15-$30/sqft", "Ergeon 2026: composite deck $30-$60/sqft installed", "HomeGuide 2026: composite railing $25-$60/lf, aluminum $50-$200/lf installed"],
    },
    steps: {
      "Design, permit and layout: deck plan with the footing layout, framing plan and railing detail submitted for the building permit; footing, framing and final inspections; 811 utility locate before digging": { price: [500, 1500], labor: 0.45, basis: "est", q: 1, note: "drawings $300-$1,000 plus permit $200-$500 and inspections; the permit is passed through at cost" },
      "Demolition of the existing deck: decking, framing, railing and footings removed and hauled away": { price: [4, 9], labor: 0.8, basis: "est" },
      "Ground prep under the deck: grade sloped away from the house, landscape fabric and washed gravel for weed and moisture control": { price: [1, 2.5], labor: 0.5, basis: "est", q: 320 },
      "Footings: dug to frost depth, 12 in. tube forms or bell footings, 3,000-psi concrete, galvanized standoff post bases set in the wet concrete": { price: [150, 300], labor: 0.55, basis: "derived", q: 4, note: "tube form, 0.15 cu yd concrete, standoff base; about 1.5 labor-hr each" },
      "Helical piers driven to torque with brackets in place of dug footings": { price: [450, 900], labor: 0.4, basis: "est" },
      "Ledger: 2x10 pressure-treated ledger fastened to the rim with 1/2 in. structural screws or through-bolts staggered 16 in. o.c., self-adhered flashing and a metal ledger cap tucked behind the siding": { price: [18, 35], labor: 0.6, basis: "est", q: 20, note: "includes cutting back the siding, flashing and the ledger cap" },
      "Posts: 6x6 pressure-treated posts on the standoff bases, plumbed and braced, notched or capped for the beam": { price: [100, 200], labor: 0.5, basis: "derived", q: 4, note: "6x6 PT post $45-$75 + cap and hardware; about 1 labor-hr" },
      "Beams: doubled or tripled 2x10 or 2x12 pressure-treated beams on post caps, spans per the plan": { price: [18, 35], labor: 0.45, basis: "est", q: 20 },
      "Joist framing: 2x8 or 2x10 pressure-treated joists at 16 in. o.c. (12 in. for diagonal or composite decking), galvanized hangers, rim joist, mid-span blocking, joist tape over every joist top": { price: [6.5, 11], labor: 0.5, basis: "derived", q: 320, note: "1-1.3 lf of 2x8/2x10 PT per sqft at $1.40-$2.10/lf plus hangers and joist tape; 2 carpenters about 1 day per 150 sqft" },
      "Decking laid: capped composite or PVC boards (1 in. x 5.5 in.) with hidden fasteners and a picture-frame border, or 5/4 x 6 cedar or pressure-treated boards face-screwed with color-matched screws": { price: [7, 16], labor: 0.35, basis: "derived", q: 320, note: "PT or cedar $6-$9/sqft; capped composite with hidden fasteners and picture frame $12-$18/sqft (composite boards $5-$8/sqft material)" },
      "Stairs: pressure-treated stringers at 12 in. o.c., closed risers and matching treads, graspable handrail, concrete landing pad at grade": { price: [175, 350], labor: 0.55, basis: "src", q: 4, note: "2026 guides: deck stairs $150-$600 per step all-in; basic wood $150-$300 per step" },
      "Railing: aluminum or composite railing 36 in. high with balusters under 4 in. apart, posts through-bolted to the rim with blocking, stair rail with returns": { price: [55, 95], labor: 0.38, basis: "derived", q: 50, note: "composite or aluminum rail kits with post sleeves about $35-$48/lf material plus blocking and install" },
      "Fascia and skirting: composite fascia over the rim joists and beam ends, lattice or board skirting with an access panel": { price: [10, 24], labor: 0.45, basis: "est", q: 52 },
      "Deck lighting: low-voltage post-cap and riser lights, transformer and timer, wiring concealed in the framing": { price: [100, 200], labor: 0.4, basis: "est", note: "per fixture with a share of the transformer" },
      "Stain and seal: penetrating oil-based stain on all wood decking and railing, two coats": { price: [1.5, 3.5], labor: 0.75, basis: "est" },
      "Under-deck drainage: membrane or trough system between the joists draining to a gutter for a dry patio below": { price: [8, 16], labor: 0.4, basis: "est" },
      "Final inspection, cleanup, haul-off of cutoffs and packaging, manufacturer warranty registration for the decking and railing": { price: [200, 500], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "patio-cover": {
    op: 0.3,
    opNote: "residential specialty builder",
    benchmark: {
      unit: "sqft",
      measures: "cover area (roofed or shaded footprint)",
      price: [25, 60],
      typicalQty: [180, 360],
      jobQty: 270,
      minJob: 3000,
      sources: ["HomeGuide 2026: patio cover $20-$60/sqft installed over an existing patio", "HomeGuide 2026: Alumawood patio cover $18-$55/sqft installed", "HomeGuide 2026: covered patio $10,000-$22,500 installed on average"],
    },
    steps: {
      "Design and permit: engineered plan for post, footing and beam sizes at the local snow and wind loads, HOA approval, building permit and inspections": { price: [800, 2000], labor: 0.4, basis: "est", q: 1, note: "engineered plan $300-$800 + permit $300-$900 + HOA; the permit is passed through at cost" },
      "Utility locate and layout: 811 ticket, post locations staked, overhead lines and setbacks checked": { price: [100, 250], labor: 0.9, basis: "est", q: 1, note: "the 811 locate is free; this is layout labor" },
      "Demolition of the existing cover or awning, hauled away": { price: [3, 7], labor: 0.8, basis: "est" },
      "Footings: 18 to 24 in. diameter to frost depth with 3,000-psi concrete and post bases, or posts core-drilled and epoxy-anchored into the existing slab": { price: [250, 500], labor: 0.5, basis: "est", q: 4 },
      "House attachment: 2x8 or 2x10 ledger lagged to the rim, flashed with a metal cap into the siding or a cut reglet in stucco": { price: [25, 50], labor: 0.6, basis: "est" },
      "Posts: 6x6 cedar or pressure-treated posts, or 4x4 aluminum posts, plumbed on standoff bases": { price: [150, 350], labor: 0.45, basis: "est", q: 4 },
      "Beams: doubled 2x10 or 6x10 cedar or glulam beams, or aluminum box beams, on post caps or brackets": { price: [25, 50], labor: 0.45, basis: "est", q: 24 },
      "Roof structure: 2x6 rafters at 24 in. o.c. for a solid cover, or 2x8 rafters with 2x2 lattice at 4 in. o.c. for a pergola, with decorative rafter tails": { price: [8, 15], labor: 0.5, basis: "est", q: 270 },
      "Solid roofing: plywood deck, synthetic underlayment and shingles matched to the house, or 3 in. insulated aluminum roof panels, or polycarbonate panels": { price: [6, 12], labor: 0.5, basis: "derived", note: "plywood + underlayment + shingles about $5-$8/sqft at the roofing repo rates; insulated aluminum panels $10-$20/sqft" },
      "Roof tie-in flashing where the cover meets the house wall or roof, step and counter flashed": { price: [12, 25], labor: 0.65, basis: "derived", note: "roofing repo step + counter flashing about $10.50/lf plus the tie-in" },
      "Fascia, trim and a gutter with downspout along the cover's low edge": { price: [15, 30], labor: 0.5, basis: "est", q: 24 },
      "Electrical: fan and light boxes, switch and a GFCI outlet run in conduit from the house by a licensed electrician": { price: [250, 600], labor: 0.65, basis: "est" },
      "Ceiling fans and light fixtures supplied and hung, wet or damp rated": { price: [200, 450], labor: 0.4, basis: "est" },
      "Stain, seal or paint of the wood structure, two coats": { price: [2, 4.5], labor: 0.8, basis: "est" },
      "Screens, shade cloth or privacy lattice walls between posts": { price: [8, 18], labor: 0.45, basis: "est" },
      "Final inspection, cleanup and haul-off of cutoffs and packaging": { price: [200, 450], labor: 0.8, basis: "est", q: 1 },
    },
  },
};
