// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "metal-fabrication": {
    op: 0.25,
    opNote: "specialty fabricator-erector, residential and light commercial",
    benchmark: {
      unit: "linear ft",
      measures: "railing length along the top rail (guards plus handrails)",
      price: [150, 325],
      typicalQty: [40, 120],
      jobQty: 80,
      minJob: 1200,
      sources: ["Handrail Cost Estimator 2026: custom mild-steel railing from about $250/linear ft installed for straight runs"],
    },
    steps: {
      "Field measurement and templating: openings, floor-to-floor heights, mounting surfaces and embeds measured; templates made for curves and returns": { price: [300, 900], labor: 1, basis: "est", q: 1 },
      "Shop drawings: elevations, sections, connection details and finish schedule; guard and stair design to the 200 lb concentrated and 50 lb/ft loads (IBC 1607), engineer's stamp where required": { price: [500, 2000], labor: 1, basis: "est", q: 1, note: "an engineer's stamp adds $500-$1,500 where required" },
      "Finish samples and a shop mockup section for the owner's approval before fabrication": { price: [400, 1500], labor: 0.7, basis: "est" },
      "Railings and guards: 1-1/2 in. square-tube steel posts at 4 ft o.c., top and bottom rails, 1/2 in. square pickets at 4 in. clear (or 6063 aluminum equivalents), shop-welded and ground smooth": { price: [85, 170], labor: 0.65, basis: "derived", q: 55, note: "shop fabrication only (steel picket guard 36-42 in.); finish and field installation are their own lines; aluminum runs 10-20% more" },
      "Handrail: 1-1/2 in. round or pipe handrail at 34-38 in. with wall brackets at 4 ft o.c., returns to the wall and 12 in. extensions at the stair ends": { price: [40, 85], labor: 0.6, basis: "derived", q: 25, note: "shop-fabricated pipe handrail with brackets and returns; installation is its own line" },
      "Infill: 1/2 in. tempered or laminated glass panels in shoe or clip mounts, or 1/8 in. stainless cable at 3 in. o.c. with tensioners": { price: [60, 200], labor: 0.4, basis: "est", note: "cable infill $40-$90/linear ft; glass panels in a base shoe $150-$300/linear ft" },
      "Stairs: C12 channel stringers, concrete-filled pans or checker-plate treads, landings and closed risers, per flight": { price: [9000, 18000], labor: 0.5, basis: "est", note: "per flight of 12-14 risers with its landing, fabricated and erected; railings separate" },
      "Canopies and awnings: HSS frame, outriggers and hangers, standing-seam or perforated panel roof, shop-assembled in sections": { price: [7000, 18000], labor: 0.45, basis: "est", note: "per canopy of about 60 sqft ($120-$300/sqft)" },
      "Gates, screens, brackets and custom pieces: cut, formed, welded and fit in the shop to the approved drawings": { price: [300, 1200], labor: 0.6, basis: "est", q: 1, note: "per small piece (pedestrian gate, screen panel or bracket set); large gates and screens run $1,500-$5,000" },
      "Finish: hot-dip galvanizing (ASTM A123), powder coat over zinc primer (AAMA 2604), or two-coat urethane; stainless passivated and brushed": { price: [4, 10], labor: 0.35, basis: "est", q: 220, note: "per sqft of railing elevation (length x height); galvanizing plus powder coat runs toward the top" },
      "Delivery to the site and hoisting by forklift or crane": { price: [250, 900], labor: 0.5, basis: "est", q: 1 },
      "Installation: posts core-drilled and grouted or surface-mounted on 1/2 in. epoxy or wedge anchors into concrete, lagged into blocking, or welded to embeds": { price: [350, 750], labor: 0.85, basis: "est", q: 9, note: "per piece set: a guard section of about 8-12 ft or one handrail run, anchors included" },
      "Field welding and grinding by a certified welder, with fire watch": { price: [120, 190], labor: 0.85, basis: "est", note: "certified welder with rig plus a fire-watch helper" },
      "Grout and sealant at post bases, escutcheons and touch-up of the finish at field connections": { price: [15, 40], labor: 0.8, basis: "est", q: 22, note: "per post base or wall bracket" },
      "Load test and inspection: guards and handrails checked plumb and to the design load, welds inspected": { price: [200, 600], labor: 0.95, basis: "est", q: 1 },
      "Cleanup and demobilization: protective wrap removed, cores and cutoffs hauled": { price: [150, 450], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "prefab-modular": {
    op: 0.3,
    opNote: "modular builder-dealer acting as the general contractor",
    benchmark: {
      unit: "sqft",
      measures: "finished floor area of the modular home",
      price: [120, 200],
      typicalQty: [1400, 2400],
      jobQty: 1900,
      minJob: 90000,
      sources: ["HomeAdvisor 2025: modular home $180,000-$360,000 total (average $270,000); $80-$160/sqft installed", "HomeAdvisor 2025: base unit $50-$100/sqft; foundation $7-$30/sqft; delivery $5,000-$15,000; permits $500-$5,000"],
    },
    steps: {
      "Design and engineering: modular set drawings, factory plans and third-party or state modular program approval, stamped for the site's snow, wind and seismic loads": { price: [2500, 8000], labor: 0.9, basis: "est", q: 1, note: "site-specific engineering and state approval; factory plans are in the module price" },
      "Permits: local building permit for the foundation, site work and set; state modular insignia or label fees": { price: [1500, 5000], labor: 0, fee: true, basis: "src", q: 1, note: "building permit and state label fees; impact and tap fees excluded" },
      "Site preparation: access route for carriers and the crane graded and matted, staging area cleared, crane pad compacted": { price: [2500, 8000], labor: 0.45, basis: "derived", q: 1, note: "carrier access, staging and crane pad; clearing the lot is separate" },
      "Foundation: crawl-space stem wall, basement or pier foundation to the set plan, with anchor bolts, sill plates and marriage-wall bearing": { price: [90, 170], labor: 0.5, basis: "derived", q: 184, note: "per ft of perimeter for a crawl-space stem wall with marriage-wall piers (about $8-$16/sqft); a full basement runs $250-$400/ft" },
      "Utilities to the set point: water, sewer, gas and electrical service stubbed to the foundation": { price: [50, 120], labor: 0.55, basis: "derived", q: 120, note: "per ft of route from the street or meter, all services combined; tap and impact fees excluded" },
      "Factory-built modules or panels: framed, insulated, roughed-in and finished to the stated level in the plant, per module": { price: [70000, 105000], labor: 0.3, basis: "derived", q: 2, note: "per module of about 900-1,000 sqft at standard finish ($75-$110/sqft)" },
      "Factory quality control and third-party inspection at rough-in and close-up, with the certificates": { price: [500, 2000], labor: 0.8, basis: "est", q: 1 },
      "Transportation: carriers, pilot cars and oversize permits from the factory to the site, per module": { price: [3500, 8000], labor: 0.4, basis: "derived", q: 2, note: "per module, under about 200 miles" },
      "Crane: 100-300 ton hydraulic crane with operator, rigging and spreader bars, day rate, with the lift plan": { price: [6000, 16000], labor: 0.3, basis: "derived", q: 1, note: "crane and rigging for a one-day set of 2-4 modules; the set crew is its own line" },
      "Set: modules lifted, landed, leveled and bolted to the foundation, married at the mate lines, wrap removed, per module": { price: [3500, 8000], labor: 0.9, basis: "derived", q: 2, note: "per module set, leveled, bolted and married" },
      "Marriage-line connections: structural bolts and straps, floor and ceiling seams closed, drywall and flooring at the mate lines": { price: [40, 100], labor: 0.75, basis: "est", q: 60, note: "per ft of mate line" },
      "Roof close-up: hinged roof sections raised and braced, ridge and mate-line shingles, dormers and gables set": { price: [1, 3], labor: 0.7, basis: "est", q: 2300, note: "per sqft of roof area" },
      "Exterior close-up: siding, corners and trim at the mate lines and where sections meet, soffit and fascia closed": { price: [15, 40], labor: 0.65, basis: "est", q: 120, note: "per ft of exterior seam and eave closed" },
      "Utility cross-connections between modules: electrical panel and circuits, plumbing and drain connections, HVAC duct and line sets": { price: [3000, 9000], labor: 0.7, basis: "est", q: 1 },
      "Site-built elements: stairs, decks, porches, garage or breezeway framed and finished on site": { price: [5000, 20000], labor: 0.55, basis: "est", note: "per element: entry stairs $2,000-$5,000; deck or porch $8,000-$20,000; garage $40,000 and up" },
      "Interior finish at the mate lines: drywall tape and paint, flooring transitions, cabinets and trim completed": { price: [4000, 12000], labor: 0.75, basis: "est", q: 1 },
      "Final inspections: state or local final, certificate of occupancy": { price: [300, 1200], labor: 0.9, basis: "est", q: 1, note: "contractor time and the CO fee" },
      "Cleanup and demobilization: shipping wrap, carriers and cribbing removed, site graded and debris hauled": { price: [1500, 4500], labor: 0.5, basis: "est", q: 1 },
    },
  },
  "signage": {
    op: 0.25,
    opNote: "commercial sign fabricator-installer",
    benchmark: {
      unit: "unit",
      measures: "signs installed (a channel-letter set on one raceway, a cabinet or a monument each count as one)",
      price: [5000, 12000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 750,
      sources: ["Flexlume 2025: channel-letter signs $2,000-$20,000; basic signs $4,000-$6,000"],
    },
    steps: {
      "Site survey: wall and mounting conditions, dimensions, sightlines, photos, power location and the sign ordinance's size and height limits checked": { price: [150, 400], labor: 1, basis: "est", q: 1 },
      "Design and proofs: artwork, dimensioned shop drawings, color matches and renderings for the owner's sign-off": { price: [200, 800], labor: 1, basis: "est", q: 1 },
      "Sign permit application with engineering for wind load, landlord approval package and the fees": { price: [500, 1500], labor: 0.5, basis: "est", q: 1, note: "permit and landlord fees (typically $100-$500) plus wind-load engineering and package prep" },
      "Channel letters: 5 in. deep .040 aluminum returns, 3/16 in. acrylic faces with trim cap, LED modules and UL-listed power supplies, mounted on a raceway or flush": { price: [170, 350], labor: 0.35, basis: "derived", q: 14, note: "per 18-24 in. illuminated letter with its raceway share; installation is its own line" },
      "Cabinet signs: welded aluminum cabinet with polycarbonate or flex faces, LED illumination, retainer frames": { price: [3000, 8000], labor: 0.35, basis: "est", note: "per cabinet about 4x8 ft; double-faced toward the top" },
      "Monument or pylon sign: steel pole or masonry base, cabinet and letters, on a concrete caisson footing to the engineer's design": { price: [12000, 35000], labor: 0.4, basis: "est", note: "monument sign on its footing; pylon signs run $40,000-$150,000" },
      "Interior ADA and wayfinding signs: room signs with raised letters and Grade 2 Braille, directories and directionals, mounted with tape and silicone": { price: [60, 180], labor: 0.3, basis: "est", note: "per room sign; directories $500-$2,000 each" },
      "Vinyl graphics: cut vinyl or printed and laminated cast vinyl (3M IJ180 or equal) for windows, walls and vehicles, applied wet or dry": { price: [8, 18], labor: 0.5, basis: "est" },
      "Dimensional letters: cut acrylic, PVC or aluminum letters, stud-mounted flush or with spacers on a pattern": { price: [50, 150], labor: 0.3, basis: "est", note: "per letter" },
      "Existing signs removed, wall patched and painted, old electrical made safe": { price: [300, 1000], labor: 0.85, basis: "est", note: "per sign removed" },
      "Delivery and lift equipment: signs crated and delivered; bucket truck, boom lift or scaffold for the installation height": { price: [350, 900], labor: 0.4, basis: "est", q: 1 },
      "Installation: anchors into masonry, steel or blocking, raceway or letters set to the pattern, plumb and level": { price: [450, 1100], labor: 0.9, basis: "est", q: 1, note: "per sign or letter set on one raceway" },
      "Electrical: primary circuit, disconnect switch and photocell or timer to the sign location by a licensed electrician": { price: [500, 1500], labor: 0.6, basis: "est", q: 1 },
      "Final hookup, UL labels, lighting checked for even illumination": { price: [150, 400], labor: 0.9, basis: "est", q: 1 },
      "Sign inspection and permit close-out": { price: [100, 300], labor: 0.9, basis: "est", q: 1, note: "contractor time at the inspection; fees are in the permit line" },
      "Cleanup and maintenance: protective film removed, site cleaned, care instructions and warranty documents given to the owner": { price: [100, 300], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "elevator-lift": {
    op: 0.2,
    opNote: "commercial elevator contractor; union mechanic labor",
    benchmark: {
      unit: "unit",
      measures: "landings (stops) served by a new low-rise passenger elevator",
      price: [30000, 60000],
      typicalQty: [2, 4],
      jobQty: 3,
      minJob: 3500,
      sources: ["Elevator Blueprint 2026: MRL elevator $100,000-$250,000 installed; hydraulic 2-6 stops $75,000-$150,000", "Elevator Blueprint 2026: maintenance $2,400-$14,000/yr; full modernization $120,000-$400,000"],
    },
    steps: {
      "Site survey and code review: hoistway plumb and dimensions, pit depth, overhead clearance, power and machine-room space checked against ASME A17.1 and the ADA": { price: [1000, 3000], labor: 0.95, basis: "est", q: 1 },
      "Layout drawings and submittals: hoistway and pit layouts, rail bracket loads, electrical requirements and cab finishes for the engineer and owner": { price: [2500, 7500], labor: 0.9, basis: "est", q: 1 },
      "State elevator permit, plan review and the inspection fees": { price: [500, 3000], labor: 0, fee: true, basis: "est", q: 1, note: "state permit, plan review and acceptance-inspection fees; varies widely by state" },
      "Hoistway and pit modifications: pit waterproofing and ladder, sump with pump, rail-bracket steel, overhead beam and hoistway walls to the fire rating": { price: [8000, 30000], labor: 0.55, basis: "est", note: "pit, sump, ladder, rail-bracket steel and overhead beam; rated hoistway walls are often by others" },
      "Elevator equipment: machine-room-less traction or hydraulic elevator, stated capacity (2,100-3,500 lb), speed (100-150 fpm) and number of stops, with controller and drive": { price: [40000, 70000], labor: 0.35, basis: "derived", q: 1, note: "machine, controller, drive, governor, ropes or belts and counterweight for a 2-4 stop car; rails, entrances and cab are their own lines" },
      "Hydraulic jack: holeless twin jack, or in-ground cylinder in a drilled and cased hole with PVC liner": { price: [12000, 30000], labor: 0.45, basis: "est", note: "holeless twin jack; an in-ground cylinder in a drilled, cased hole runs toward the top" },
      "Residential elevator, platform lift, stairlift or dumbwaiter: unit type and capacity per the manufacturer's specification, with rails and drive": { price: [20000, 45000], labor: 0.35, basis: "est", note: "2-stop residential elevator or vertical platform lift; a straight stairlift is $3,500-$6,000, a dumbwaiter $8,000-$15,000" },
      "Delivery, rigging and hoisting of the machine, rails, car sling and doors into the hoistway and machine space": { price: [2500, 7500], labor: 0.6, basis: "est", q: 1 },
      "Guide rails, brackets, buffers and pit equipment set plumb and aligned in the hoistway": { price: [6000, 12000], labor: 0.6, basis: "est", q: 1, note: "per hoistway: car and counterweight rails, brackets, buffers and pit equipment" },
      "Hoistway entrances: doors, frames, sills, hall stations and lanterns at each landing, per stop": { price: [4000, 8000], labor: 0.45, basis: "est", q: 3, note: "per landing" },
      "Car: sling and platform, cab with the selected finishes, door operator, car operating panel, lighting and handrail": { price: [15000, 30000], labor: 0.4, basis: "derived", q: 1, note: "standard manufacturer cab line (finishes $8,000-$15,000 basic per Elevator Blueprint)" },
      "Hoistway and machine-room wiring: traveling cable, controller connections, safety circuits, pit and hoistway lights": { price: [5000, 12000], labor: 0.7, basis: "est", q: 1 },
      "Electrical by the licensed electrician: 3-phase fused disconnect, lighting circuit, GFCI outlets, sump pump circuit and the phone or monitoring line": { price: [4000, 10000], labor: 0.6, basis: "est", q: 1 },
      "Fire service, emergency lighting, two-way communication and monitoring connections per the code": { price: [2500, 7000], labor: 0.5, basis: "est", q: 1 },
      "Modernization: controller, machine, door operators, fixtures and cab interior replaced in the existing hoistway": { price: [120000, 250000], labor: 0.5, basis: "src", note: "full modernization of a low-rise car; controls only is $50,000-$70,000" },
      "Adjustment and testing: ride adjusted, safeties and brakes tested, full-load and overspeed tests witnessed": { price: [3500, 8000], labor: 0.95, basis: "est", q: 1 },
      "State inspection and the certificate of operation": { price: [1500, 4000], labor: 0.9, basis: "est", q: 1, note: "contractor crew for the witnessed acceptance test; state fees are in the permit line" },
      "Owner training and turnover: keys, manuals, wiring diagrams and the first-year warranty": { price: [500, 1500], labor: 0.95, basis: "est", q: 1 },
      "Maintenance agreement: monthly service visits, lubrication, adjustments and 24-hour callback": { price: [3500, 8000], labor: 0.8, basis: "src", note: "per year; oil-and-grease $2,400-$6,000/yr, full maintenance $5,000-$14,000/yr" },
      "Cleanup: crating and packaging removed, hoistway and machine room swept, protective coverings pulled": { price: [500, 1500], labor: 0.8, basis: "est", q: 1 },
    },
  },
};
