// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "attic-air-sealing": {
    op: 0.3,
    opNote: "residential weatherization and insulation trade",
    benchmark: {
      unit: "sqft",
      measures: "attic floor area sealed",
      price: [1.25, 3],
      typicalQty: [1000, 2000],
      jobQty: 1500,
      minJob: 600,
      sources: ["Angi 2026: blower door test $200-$450, average $325", "LatestCost 2026: attic air sealing $1,000-$6,000, $0.50-$2.50 per sqft of attic area"],
    },
    steps: {
      "Blower door pre-test at 50 pascals with the CFM50 recorded, infrared camera and smoke pencil used to map the leaks from the attic side": { price: [200, 450], labor: 0.85, basis: "src", q: 1, note: "blower door pre-test with IR scan; Angi 2026 $200-$450" },
      "Combustion safety test on the furnace and water heater (draft, spillage, CO) before and after sealing": { price: [100, 250], labor: 0.9, basis: "est", q: 1, note: "CAZ test before and after; often bundled with the audit" },
      "Existing insulation raked back from the top plates and penetrations so the seal is made at the drywall plane": { price: [0.35, 0.75], labor: 1, basis: "est", q: 500, note: "per sqft of insulation actually raked back (top-plate band and around penetrations)" },
      "Top plates and drywall seams sealed with one-part expanding foam or fire-rated caulk along every interior and exterior wall": { price: [1.25, 2.5], labor: 0.75, basis: "derived", q: 360, note: "share of the sourced $0.50-$2.50/sqft attic sealing total; about 50-80 linear ft an hour" },
      "Wire, plumbing, duct and vent penetrations foamed or caulked closed": { price: [10, 25], labor: 0.75, basis: "derived", q: 25, note: "per penetration; share of the sourced $0.50-$2.50/sqft sealing total" },
      "Chase and soffit caps: rigid foam or sheet metal cut over plumbing chases, dropped soffits and open kneewall bays, foamed at the edges": { price: [90, 250], labor: 0.6, basis: "est", q: 3, note: "per chase, soffit or kneewall bay cap" },
      "Recessed light covers: fire-rated boxes set and sealed over each can light": { price: [45, 110], labor: 0.5, basis: "est", note: "per can light; listed fire-rated cover" },
      "Flue and chimney: sheet-metal collar sealed with high-temperature caulk keeping the required clearance to combustibles": { price: [100, 250], labor: 0.6, basis: "est", note: "per flue or chimney" },
      "Attic hatch or pull-down stair weatherstripped and fitted with an insulated, latched cover": { price: [150, 350], labor: 0.45, basis: "est", q: 1, note: "pull-down stair cover tent or insulated hatch box with gasket" },
      "Bath fan and kitchen exhaust ducts connected with rigid duct to a roof or wall cap and sealed at the collar": { price: [250, 600], labor: 0.55, basis: "est", note: "per fan; rigid duct and roof or wall cap" },
      "Attic ducts sealed with mastic and mesh at every joint, boot and plenum seam": { price: [2, 5], labor: 0.8, basis: "est", note: "per linear ft of duct sealed with mastic" },
      "Insulation raked back into place and topped up to the original depth over the sealed areas": { price: [0.4, 0.9], labor: 0.85, basis: "est", q: 500, note: "per sqft restored; small top-up of blown insulation included" },
      "Blower door post-test and a report with before-and-after leakage and a photo log of the sealed points": { price: [150, 325], labor: 0.9, basis: "derived", q: 1, note: "post-test while the rig is on site; below the standalone Angi test price" },
      "Work areas vacuumed, foam trimmings and packaging hauled, ladders and lights removed": { price: [75, 175], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "radiant-barrier": {
    op: 0.3,
    opNote: "residential insulation trade",
    benchmark: {
      unit: "sqft",
      measures: "roof deck and gable area covered with foil",
      price: [0.8, 2],
      typicalQty: [1500, 2500],
      jobQty: 2000,
      minJob: 600,
      sources: ["HomeGuide 2026: radiant barrier $0.30-$2.00/sqft installed, attic $350-$2,700", "HomeAdvisor 2026: labor $0.60-$1.00/sqft, two-sided foil $0.50-$0.90/sqft; 2,000 sqft attic $1,400-$4,000"],
    },
    steps: {
      "Attic survey: roof pitch and framing, existing insulation and ventilation checked, attic temperature and access noted, layout planned": { price: [75, 200], labor: 1, basis: "est", q: 1, note: "often credited against the job" },
      "Access and safety: walk boards laid across the joists, temporary lighting, insulation protected from foot traffic": { price: [100, 225], labor: 0.8, basis: "est", q: 1 },
      "Radiant barrier foil supplied and installed: perforated double-sided aluminum (ASTM C1313, emissivity 0.05 or less) stapled to the underside of the rafters or truss top chords, seams lapped 2 in., a 3 in. air gap left at the ridge and eaves": { price: [0.8, 1.5], labor: 0.6, basis: "src", q: 1800, note: "HomeAdvisor 2026 labor $0.60-$1.00 plus two-sided foil $0.50-$0.90/sqft" },
      "Gable end walls covered with foil to block radiant gain through the end walls": { price: [0.75, 1.4], labor: 0.6, basis: "derived", q: 200, note: "as the rafter foil, easier reach" },
      "Openings cut and edges secured around roof vents, ridge vents, chimneys and recessed lights, keeping clearance from heat sources": { price: [8, 25], labor: 0.9, basis: "est", q: 10, note: "per opening cut and secured" },
      "Attic-floor lay-over: perforated foil laid loose over the existing insulation where the deck cannot be reached": { price: [0.3, 0.7], labor: 0.5, basis: "derived", note: "HomeGuide low end $0.30/sqft for a loose lay-over" },
      "Radiant barrier coating: low-emissivity paint sprayed on the underside of the roof deck": { price: [0.85, 1.6], labor: 0.5, basis: "derived", note: "HomeAdvisor spray-on material $0.65-$1.00/sqft plus spray labor" },
      "Ventilation upgrade: additional soffit or ridge vents, or a solar attic fan wired and set": { price: [400, 850], labor: 0.45, basis: "src", note: "HomeAdvisor 2026: attic fan installed average $625; per vent or fan" },
      "Cleanup and documentation: scraps and staples collected, product data and photos left for utility rebate or energy credit paperwork": { price: [75, 175], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "hardwood-refinishing": {
    op: 0.3,
    opNote: "residential flooring trade",
    benchmark: {
      unit: "sqft",
      measures: "floor area sanded and refinished",
      price: [3, 8],
      typicalQty: [400, 900],
      jobQty: 650,
      minJob: 1000,
      sources: ["HomeGuide 2026: refinishing $3-$8/sqft", "Homewyse May 2026: $6.49-$7.92/sqft basic (2-pass sand, 2 coats 2K waterborne)"],
    },
    steps: {
      "Room cleared and protected: furniture moved by the crew, doorways and HVAC registers masked with plastic, dust containment on the sanders": { price: [150, 400], labor: 0.9, basis: "est", q: 1, note: "furniture moved and containment; scales with rooms" },
      "Shoe molding or quarter round pulled and set aside for reinstallation": { price: [0.75, 1.75], labor: 1, basis: "est" },
      "Board repairs: split, stained or pet-damaged boards cut out and replaced with matching species weaved into the field": { price: [40, 100], labor: 0.8, basis: "est", note: "per board replaced and weaved in" },
      "Nails set below the surface, gaps and nail holes filled with matching wood filler after the first pass": { price: [0.2, 0.5], labor: 0.85, basis: "est", q: 650 },
      "Sanding: three to four passes with a drum or belt sander from 36 to 100 grit, edger at the walls, hand-scraped corners, buffed with a screen for a uniform scratch pattern": { price: [1.75, 3.25], labor: 0.85, basis: "derived", q: 650, note: "about 45% of the sourced $3-$8/sqft total; paper and sander wear as material" },
      "Water-popping the grain before stain for an even, deeper color": { price: [0.25, 0.6], labor: 0.95, basis: "est" },
      "Stain: penetrating oil or waterborne stain in the approved color from an on-floor sample, hand-applied and wiped, dried overnight": { price: [0.75, 1.75], labor: 0.7, basis: "est" },
      "Finish: three coats of two-component waterborne polyurethane (Bona Traffic HD or equal) or oil-modified polyurethane in the chosen sheen, abraded between coats": { price: [1.5, 3], labor: 0.55, basis: "derived", q: 650, note: "three coats 2K waterborne; about 35-40% of the sourced total" },
      "Hardwax oil finish (Rubio Monocoat or equal) applied and buffed in one or two coats": { price: [1.75, 3.5], labor: 0.5, basis: "est", note: "hardwax oil in place of the poly coats" },
      "Stairs: treads and risers sanded, stained and finished by hand to match the floor": { price: [30, 85], labor: 0.85, basis: "src", note: "per step, tread and riser by hand; cost guides 2026 $25-$85 per step" },
      "Thresholds, reducers and stair nosing sanded and finished with the floor or replaced": { price: [5, 14], labor: 0.75, basis: "est", q: 12, note: "replaced reducers run $30-$60 each" },
      "Screen and recoat only: existing finish abraded with a maroon pad and one fresh coat of finish applied": { price: [1, 2.5], labor: 0.7, basis: "src", note: "in place of sand and finish; cost guides 2026 $1-$2.50/sqft" },
      "Shoe molding reinstalled and touched up after the final coat": { price: [1.25, 3], labor: 0.9, basis: "est" },
      "Final cleanup, dust removed from sills and ledges, cure schedule explained (foot traffic, furniture and rugs) and care kit left": { price: [75, 200], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "trim-molding": {
    op: 0.3,
    opNote: "residential finish-carpentry trade",
    benchmark: {
      unit: "linear ft",
      measures: "molding installed, all profiles",
      price: [7, 16],
      typicalQty: [300, 700],
      jobQty: 500,
      minJob: 500,
      sources: ["HomeGuide 2025: crown molding $7-$16/linear ft installed", "HomeAdvisor 2025: baseboard $5.70-$9.00/linear ft installed", "Fixr 2025: whole house, 500 linear ft of crown $2,000-$4,000"],
    },
    steps: {
      "Profile selection: samples of the crown, chair rail, casing and base profiles in MDF, primed finger-joint pine, poplar or PVC brought for approval": { price: [75, 200], labor: 0.8, basis: "est", q: 1 },
      "Existing molding pried off, nails pulled, walls patched where the old profile was smaller": { price: [0.75, 2], labor: 1, basis: "est" },
      "Studs and ceiling joists located; continuous backing or a plywood nailer installed where the crown spans an unsupported ceiling": { price: [3, 7], labor: 0.7, basis: "est" },
      "Crown molding: profile cut on a compound miter saw, inside corners coped, outside corners mitered, scarf joints glued over studs, nailed with 15-gauge finish nails": { price: [7, 16], labor: 0.7, basis: "src", q: 160, note: "HomeGuide 2025 crown installed" },
      "Built-up crown: two or three stacked pieces (base cap, cove and crown) assembled for a taller profile": { price: [14, 30], labor: 0.7, basis: "derived", note: "two or three stacked pieces at the crown rate" },
      "Chair rail or picture rail set at the approved height, level around the room, coped at corners": { price: [5, 11], labor: 0.7, basis: "derived", q: 60, note: "from the baseboard and crown rates" },
      "Baseboard and base cap in the matching profile, coped inside corners, mitered outside corners": { price: [6, 11], labor: 0.65, basis: "derived", q: 160, note: "HomeAdvisor base $5.70-$9.00 plus the base cap" },
      "Casing upgrade: window and door casing with back band, head casing with crown and fillet, plinth blocks at the floor": { price: [10, 22], labor: 0.7, basis: "est", q: 120, note: "built-up casing with back band, head crown and plinths" },
      "Corner blocks, rosettes and plinth blocks at door and window corners": { price: [20, 45], labor: 0.5, basis: "est", note: "per block or rosette" },
      "Ceiling medallions, decorative brackets or corbels adhered and fastened to blocking": { price: [75, 250], labor: 0.5, basis: "est", note: "per medallion or corbel" },
      "Coffered ceiling grid: box beams built from MDF or poplar, wrapped and trimmed with crown inside each coffer": { price: [45, 100], labor: 0.65, basis: "est", note: "per linear ft of box beam" },
      "Nail holes filled, joints and gaps caulked with paintable caulk, sanded and spot-primed ready for paint": { price: [0.75, 1.75], labor: 0.9, basis: "est", q: 500 },
      "Finish: two coats of enamel or stain and clear coat on the new molding": { price: [1.5, 3.5], labor: 0.85, basis: "derived", note: "Fixr 2025 painting $150-$600 for one to three rooms" },
      "Offcuts hauled, floors vacuumed, walls touched up where the old molding was removed": { price: [75, 200], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "wainscoting": {
    op: 0.3,
    opNote: "residential finish-carpentry trade",
    benchmark: {
      unit: "sqft",
      measures: "wall area paneled (length x panel height)",
      price: [12, 30],
      typicalQty: [100, 250],
      jobQty: 175,
      minJob: 800,
      sources: ["HomeGuide 2025: wainscoting $10-$40/sqft installed", "Fixr 2025: board and batten $9-$23/sqft, raised panel $12-$33/sqft; 12x12 room about $3,600"],
    },
    steps: {
      "Layout: panel height (32 to 42 in.), stile spacing and panel widths drawn on the wall, outlets and switches located, a mock-up section approved": { price: [100, 300], labor: 0.95, basis: "est", q: 1 },
      "Existing baseboard and chair rail removed, nails pulled and the wall patched": { price: [1, 2.5], labor: 1, basis: "est" },
      "Wall prep: studs located and marked, high spots sanded, texture skimmed flat where panels will bear": { price: [0.5, 1.5], labor: 0.85, basis: "est", q: 175 },
      "Beadboard: 4x8 MDF or PVC beadboard sheets or tongue-and-groove planks glued and nailed to the studs with the seams hidden behind stiles": { price: [8, 16], labor: 0.55, basis: "derived", note: "Fixr 2025 beadboard $9-$23/sqft with trim" },
      "Raised or flat-panel wainscoting: rails and stiles in 1x4 or 1x6 MDF or poplar with panel molding or applied raised panels": { price: [11, 22], labor: 0.65, basis: "derived", note: "Fixr 2025 flat $9-$12, raised $12-$33/sqft" },
      "Board and batten: 1x4 or 1x6 battens over a skim-flat wall or MDF backer at the approved spacing, glued and nailed": { price: [7, 15], labor: 0.65, basis: "derived", q: 175, note: "Fixr 2025 board and batten $9-$23/sqft with trim; the style priced in the typical job (all four styles are conditional, one always applies)" },
      "Shiplap or nickel-gap boards run level with the gap set by spacers, nailed to studs": { price: [7, 14], labor: 0.55, basis: "derived", note: "Fixr 2025 shiplap $9-$23/sqft with trim" },
      "Cap rail or chair rail with a cove or base cap under it, coped at corners": { price: [7, 14], labor: 0.65, basis: "est", q: 50 },
      "Baseboard or base shoe at the floor to finish the bottom edge": { price: [5.5, 9.5], labor: 0.65, basis: "derived", q: 50, note: "HomeAdvisor 2025 baseboard $5.70-$9.00" },
      "Outlet and switch boxes brought flush with box extenders and new plates": { price: [18, 40], labor: 0.8, basis: "est", q: 4, note: "per box" },
      "Nail holes filled, seams and edges caulked with paintable caulk, sanded and primed": { price: [0.9, 2], labor: 0.85, basis: "est", q: 175 },
      "Two coats of enamel in the chosen sheen brushed and rolled on the paneling and trim": { price: [2, 5], labor: 0.85, basis: "src", note: "Fixr 2025 painting $2-$5/sqft" },
      "Scraps hauled, floors vacuumed and the room dusted": { price: [60, 150], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "built-in-cabinetry": {
    op: 0.35,
    opNote: "custom cabinet shop: design, shop and install overhead",
    benchmark: {
      unit: "linear ft",
      measures: "built-in face length, full-height units",
      price: [500, 1200],
      typicalQty: [8, 16],
      jobQty: 12,
      minJob: 2000,
      sources: ["HomeAdvisor 2026: custom cabinets $500-$1,200/linear ft", "Angi 2026: built-in cabinets $200-$600/linear ft, average project $4,500 ($2,000-$7,500)"],
    },
    steps: {
      "Design consultation and field measurement, then scaled drawings with elevations, a section and a hardware and finish schedule for sign-off": { price: [350, 1000], labor: 1, basis: "est", q: 1, note: "design fee; often credited to the order" },
      "Finish and hardware samples: paint color, stain on the chosen species, door style and pull samples delivered for approval": { price: [75, 250], labor: 0.6, basis: "est", q: 1 },
      "Carcass fabrication: 3/4 in. hardwood plywood boxes with 1/4 in. backs, adjustable shelves on 32 mm pin holes, face frames in poplar or the stain species": { price: [200, 380], labor: 0.55, basis: "derived", q: 12, note: "share of the HomeAdvisor $500-$1,200/linear ft custom price; base and upper boxes per linear ft of face" },
      "Doors and drawer fronts: shaker, flat or beaded panel in MDF or hardwood, sized with 1/8 in. reveals": { price: [75, 170], labor: 0.5, basis: "est", q: 12, note: "per door or drawer front" },
      "Drawer boxes: dovetailed 5/8 in. maple with full-extension soft-close undermount slides": { price: [100, 210], labor: 0.4, basis: "est", q: 4, note: "per drawer with soft-close undermount slides" },
      "Shop finish: sprayed lacquer, conversion varnish or enamel over primer, sanded between coats": { price: [65, 150], labor: 0.7, basis: "est", q: 12, note: "full-height unit, both faces of shelves" },
      "Site prep: baseboard cut back, wall patched and the floor checked for level at the footprint": { price: [6, 16], labor: 0.9, basis: "est", q: 12 },
      "Installation: units leveled on a base platform, scribed to the walls and ceiling, screwed to studs, sections joined flush": { price: [60, 130], labor: 0.9, basis: "derived", q: 12, note: "repo remodel audit: cabinet install $50-$100/linear ft before markup, scribed built-ins higher" },
      "Face trim: crown, light valance, base, fillers and scribe molding fitted so the unit reads as built into the wall": { price: [25, 60], labor: 0.7, basis: "est", q: 12 },
      "Electrical: receptacles inside the cabinet, LED puck or tape lighting with a driver and dimmer, switched at the unit": { price: [225, 550], labor: 0.6, basis: "derived", note: "repo remodel audit: new box on an existing circuit $180-$400 before markup; per device or light run" },
      "Media provisions: cable chases, grommets, ventilated equipment shelves and an infrared repeater": { price: [100, 350], labor: 0.5, basis: "est", note: "per provision" },
      "Pulls and knobs installed, hinges and slides adjusted, doors and drawers aligned": { price: [15, 40], labor: 0.45, basis: "est", q: 12, note: "per door or drawer; standard pull allowance included" },
      "Window seat cushion top, desk surface or a stone or wood countertop on the base unit": { price: [300, 1200], labor: 0.4, basis: "est", note: "wood or laminate top; stone runs higher" },
      "Finish touch-up, hardware final check, protective covering removed and the area cleaned": { price: [100, 250], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "residential-soundproofing": {
    op: 0.3,
    opNote: "residential specialty trade",
    benchmark: {
      unit: "sqft",
      measures: "wall and ceiling area treated",
      price: [14, 32],
      typicalQty: [200, 500],
      jobQty: 350,
      minJob: 1200,
      sources: ["Fixr 2025: soundproofing $10-$30/sqft in existing rooms; soundproof doors $1,200-$4,000", "HomeGuide 2026: $10-$30/sqft installed, $1,400-$4,300 per room"],
    },
    steps: {
      "Acoustic assessment: noise source and flanking paths identified, existing assembly opened at one spot, sound-level readings taken and the STC or IIC target set": { price: [250, 600], labor: 1, basis: "est", q: 1 },
      "Protection and containment: floors covered, plastic on doorways, furniture moved and covered": { price: [150, 400], labor: 0.85, basis: "est", q: 1 },
      "Existing drywall or ceiling removed to the framing and disposed of": { price: [1.25, 2.75], labor: 0.8, basis: "est", note: "removal and disposal to the framing" },
      "Cavity fill: 3 in. mineral wool batts (Rockwool Safe-n-Sound or equal) friction-fit between the studs or joists": { price: [1.5, 2.75], labor: 0.35, basis: "derived", q: 350, note: "mineral wool about $1.00-$1.30/sqft plus friction-fit labor" },
      "Decoupling: sound-isolation clips (Kinetics IsoMax or equal) and 25-gauge hat channel 24 in. o.c., or resilient channel on the framing": { price: [3, 5.5], labor: 0.5, basis: "derived", q: 350, note: "clips about one per 6-8 sqft plus hat channel; Fixr decoupling $115-$260 per wall" },
      "Mass-loaded vinyl, 1 lb per sqft, hung over the framing and lapped and taped at the seams": { price: [3, 5.5], labor: 0.4, basis: "derived", note: "Fixr 2025 MLV $200-$400 per wall" },
      "Two layers of 5/8 in. Type X drywall with a damping compound (Green Glue) between the layers, joints staggered": { price: [5.5, 9.5], labor: 0.5, basis: "derived", q: 350, note: "Fixr 2025 double drywall $160-$240 per wall plus Green Glue two tubes a sheet" },
      "Acoustical sealant at the perimeter of every layer, at the floor and ceiling joints and around penetrations": { price: [1.5, 3.5], labor: 0.6, basis: "est", q: 180, note: "per linear ft of joint sealed, each layer" },
      "Putty pads on the back of electrical boxes and backer boxes at recessed lights": { price: [20, 50], labor: 0.5, basis: "est", q: 8, note: "per box" },
      "Solid-core door with a perimeter gasket kit and an automatic door bottom, hung in a sealed frame": { price: [900, 2000], labor: 0.35, basis: "derived", q: 1, note: "gasketed solid-core door, below Fixr's $1,200-$4,000 rated acoustic doors" },
      "Floor: acoustic underlayment or a floating floor over rubber isolation mat for footfall noise": { price: [3, 8], labor: 0.45, basis: "est" },
      "Window treatment: laminated acoustic interior insert panels over the existing windows": { price: [250, 600], labor: 0.2, basis: "src", note: "Fixr 2025 window inserts $250-$600" },
      "HVAC: flexible duct connectors, lined duct or an in-line silencer where ducts link the rooms": { price: [250, 700], labor: 0.55, basis: "est", note: "per duct run" },
      "Drywall taped and finished to Level 4 and primed, trim reinstalled over the new wall thickness": { price: [2, 3.75], labor: 0.8, basis: "derived", q: 350, note: "repo drywall and painter rates; trim reinstall included" },
      "Post-treatment sound readings compared to the baseline, report given, dust cleaned and furniture returned": { price: [200, 450], labor: 0.95, basis: "est", q: 1 },
    },
  },
  "interior-remodel": {
    op: 0.35,
    opNote: "residential remodeler and general contractor",
    benchmark: {
      unit: "sqft",
      measures: "floor area remodeled (rooms taken to the framing)",
      price: [60.75, 114.75],
      typicalQty: [400, 1000],
      jobQty: 700,
      minJob: 10000,
      sources: ["JobFlex remodel method section 8 (reviewed), 2026: basement finish $45-$85/sqft before markup, x1.35 = $60.75-$114.75", "HomeGuide 2026: gut to the studs and remodel $60-$150/sqft"],
    },
    steps: {
      "Permits, plans and inspections: building permit with a floor plan, electrical and plumbing permits, rough and final inspections": { price: [700, 2000], labor: 0, fee: true, basis: "derived", q: 1, note: "building, electrical and plumbing permit fees at cost; scale with valuation (about 1-2%)" },
      "Protection and containment: floor protection along the path, plastic dust walls with zipper doors, HVAC returns sealed, a negative-air machine running": { price: [600, 1400], labor: 0.6, basis: "derived", q: 1, note: "repo 5.1 protection line; negative-air machine rental inside" },
      "Demolition of finishes: flooring, drywall, ceilings, trim and fixtures removed to the framing, debris carried out": { price: [6, 12], labor: 0.9, basis: "derived", q: 700, note: "per sqft of room floor; walls, ceiling, floor and trim out (repo gut $11-$24 per kitchen sqft before markup includes cabinets)" },
      "Dumpster rental and dump fees for the demolition debris": { price: [550, 950], labor: 0.1, basis: "derived", q: 1, note: "repo audit: 20 cu yd dumpster $450-$700 before markup; a 30 yd for more than about 1,000 sqft" },
      "Structural changes: bearing wall removed with a temporary shore, engineered LVL header, posts and pads set per the engineer's letter": { price: [600, 1400], labor: 0.6, basis: "derived", note: "repo section 8: bearing wall removed $9,000-$22,000 for 12-16 ft before markup" },
      "Non-bearing walls removed or new 2x4 partitions framed 16 in. o.c. with door openings and blocking": { price: [30, 65], labor: 0.7, basis: "derived", q: 40, note: "framing or removal only; patch and paint on their own lines" },
      "Rough electrical: new circuits, receptacles to NEC spacing, switch loops, recessed LED cans, smoke and CO detectors interconnected": { price: [140, 280], labor: 0.7, basis: "derived", q: 36, note: "per device or opening with walls open; repo section 8 electrician $100-$160/h before markup" },
      "Rough plumbing: supply and drain lines moved or added for relocated fixtures": { price: [2000, 4700], labor: 0.7, basis: "derived", note: "repo audit: relocated fixture $1,500-$3,500 before markup" },
      "HVAC: supply and return registers relocated, ducts extended or a mini-split head added to the changed rooms": { price: [400, 1100], labor: 0.65, basis: "est", note: "per register or duct run; a mini-split head runs $4,000-$7,500" },
      "Insulation in exterior walls and ceilings opened during the work, R-15 walls and R-38 ceilings": { price: [1.25, 2.5], labor: 0.45, basis: "est" },
      "Drywall: 1/2 in. board hung on new walls and patches, 5/8 in. on ceilings, taped and finished to Level 4 with texture matched to the existing": { price: [2.75, 4.5], labor: 0.75, basis: "derived", q: 2500, note: "per sqft of board; repo section 8 drywall $55-$90/h before markup" },
      "Interior doors and windows: pre-hung doors hung and cased, replacement windows set and trimmed": { price: [400, 900], labor: 0.45, basis: "est", q: 5, note: "per door or window; replacement windows at the top" },
      "Flooring: new floor over the proper underlayment, or existing hardwood patched and refinished": { price: [5.5, 10], labor: 0.4, basis: "derived", q: 700, note: "repo LVP allowance $3-$4.50/sqft plus install" },
      "Transitions and thresholds at doorways and material changes": { price: [8, 20], labor: 0.5, basis: "est", q: 15 },
      "Trim package: baseboard, casing, crown and closet shelving installed, filled and caulked": { price: [6, 12], labor: 0.6, basis: "derived", q: 420, note: "HomeAdvisor 2025 baseboard $5.70-$9.00 installed" },
      "Paint: primer on new drywall, two coats on walls and ceilings, enamel on trim and doors": { price: [1.75, 3.5], labor: 0.8, basis: "derived", q: 2500, note: "per sqft of wall and ceiling surface; repo audit walls two coats $1.50-$3.50" },
      "Finish electrical and plumbing: devices, plates, light fixtures, fans and fixtures set and tested": { price: [75, 175], labor: 0.6, basis: "derived", q: 36, note: "per device or fixture; repo audit device swap $75-$150; fixtures by allowance" },
      "Final clean, punch-list walk-through, final inspection sign-off and warranty paperwork": { price: [400, 900], labor: 0.85, basis: "derived", q: 1, note: "repo audit final clean $250-$500 per room group before markup" },
    },
  },
  "laundry-room-remodel": {
    op: 0.35,
    opNote: "residential remodeler and general contractor",
    benchmark: {
      unit: "fixed",
      measures: "whole laundry room remodeled in place (about 40-80 sqft)",
      price: [8100, 20250],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 3000,
      sources: ["JobFlex remodel method section 8 (reviewed), 2026: laundry remodel in place $6,000-$15,000 before markup, x1.35 = $8,100-$20,250", "HomeAdvisor 2026: laundry room remodel $6,000-$17,000, average $11,000", "HomeGuide 2025: typical laundry remodel $5,000-$15,000, $140-$250/sqft"],
    },
    steps: {
      "Permit for the plumbing, electrical and dryer venting changes with the rough and final inspections": { price: [250, 750], labor: 0, fee: true, basis: "derived", note: "plumbing, electrical and mechanical permit fees at cost" },
      "Protection and machine handling: washer and dryer disconnected, capped and moved out of the room, floors protected": { price: [100, 225], labor: 0.9, basis: "est", q: 2, note: "per machine; floor protection included" },
      "Demolition of cabinets, shelving, flooring and damaged drywall, debris bagged and hauled": { price: [6, 14], labor: 0.85, basis: "derived", q: 64, note: "per sqft of room floor; small rooms run high" },
      "Plumbing: recessed laundry box with quarter-turn valves and hammer arrestors, 2 in. standpipe and trap, supply and drain for a utility sink": { price: [750, 1500], labor: 0.75, basis: "derived", q: 2, note: "per fixture connection (washer box, utility sink); repo audit in place $600-$1,200 before markup" },
      "Electrical: dedicated 20A laundry circuit, NEMA 14-30 dryer receptacle on a 30A/240V circuit, GFCI receptacles, lighting and a switch": { price: [550, 1200], labor: 0.7, basis: "derived", q: 3, note: "per circuit with its devices; repo audit new 20 A circuit $450-$900 before markup" },
      "Dryer vent: 4 in. rigid metal duct to the exterior with a backdraft damper hood, run under the 35 ft equivalent length limit": { price: [18, 40], labor: 0.7, basis: "derived", q: 12, note: "HomeAdvisor 2026 dryer vent about $200; wall cap and damper spread over the run" },
      "Gas line to the dryer in black iron or CSST with a shutoff valve and flex connector": { price: [400, 1000], labor: 0.7, basis: "derived", note: "repo: gas re-piped and pressure-tested" },
      "Floor drain or a washer drain pan piped to a drain to protect the floor below": { price: [250, 900], labor: 0.65, basis: "est", note: "pan with drain at the low end, floor drain at the top" },
      "Drywall patched where lines were run, moisture-resistant board at the wet wall, finished and textured to match": { price: [3.5, 6.5], labor: 0.75, basis: "derived", q: 80, note: "small patch quantities" },
      "Flooring: waterproof LVP or porcelain tile over the proper underlayment": { price: [7, 15], labor: 0.5, basis: "derived", q: 64, note: "LVP at the low end, porcelain tile at the top (repo tile and LVP anchors)" },
      "Cabinets: wall cabinets over the machines, a tall broom or pantry cabinet, base cabinet at the sink": { price: [300, 650], labor: 0.25, basis: "derived", q: 10, note: "semi-custom boxes plus install; HomeAdvisor cabinet installation $100-$300/linear ft" },
      "Countertop over the machines or the base cabinet in laminate or quartz with a sink cutout": { price: [35, 95], labor: 0.3, basis: "derived", q: 15, note: "repo audit laminate $25-$45, quartz $60-$120/sqft installed" },
      "Utility sink and faucet set and connected": { price: [500, 1100], labor: 0.45, basis: "derived", q: 1, note: "sink and faucet allowance plus set and connect" },
      "Hanging rod, folding station shelf and open shelving mounted to studs": { price: [35, 90], labor: 0.55, basis: "est", q: 8 },
      "Walls and ceiling painted two coats in a scrubbable satin": { price: [1.75, 3.5], labor: 0.8, basis: "derived", q: 300, note: "per sqft of wall and ceiling" },
      "Baseboard, casing and door trim installed and caulked": { price: [6, 12], labor: 0.6, basis: "derived", q: 45, note: "HomeAdvisor 2025 baseboard $5.70-$9.00" },
      "Washer and dryer set, leveled, connected and run through a test cycle, vent connection checked": { price: [125, 275], labor: 0.8, basis: "derived", q: 2, note: "per machine; repo appliance set $120-$250" },
      "Final clean and walk-through": { price: [200, 450], labor: 0.9, basis: "derived", q: 1, note: "repo final clean, one small room" },
    },
  },
  "home-office-buildout": {
    op: 0.35,
    opNote: "residential remodeler and general contractor",
    benchmark: {
      unit: "fixed",
      measures: "whole office build-out in one room (about 100-150 sqft) with built-ins",
      price: [16200, 33750],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 4500,
      sources: ["JobFlex remodel method section 8 (reviewed), 2026: office with built-ins and a glass door $12,000-$25,000 before markup (x1.35 = $16,200-$33,750); basic from a bedroom $3,500-$9,000", "Fixr 2025: custom bookcase $450-$3,000, soundproofing $1,000-$2,500, mini-split $1,000-$3,000"],
    },
    steps: {
      "Permit and inspections for new walls, circuits and the closet or door changes": { price: [200, 650], labor: 0, fee: true, basis: "est", note: "building and electrical permit fees at cost" },
      "Protection: floor covering, plastic on the doorway and dust control while the room is opened": { price: [300, 700], labor: 0.7, basis: "derived", q: 1, note: "repo 5.1 protection line" },
      "Removal of existing closet, carpet, shelving or a wall to make the room": { price: [3, 7], labor: 0.9, basis: "est" },
      "Framing: new 2x4 partition 16 in. o.c. with a door opening, or a closet framed for equipment and storage": { price: [35, 70], labor: 0.7, basis: "derived", note: "2x4 partition with header, blocking and door opening" },
      "Sound insulation: mineral wool in the office walls and ceiling for privacy on calls": { price: [1.75, 3.25], labor: 0.4, basis: "derived", q: 200, note: "mineral wool in open cavities" },
      "Electrical: dedicated 20A circuit, receptacles at desk height and floor, USB-C outlets, a circuit for equipment, dimmable recessed LED lighting": { price: [220, 480], labor: 0.65, basis: "derived", q: 12, note: "per circuit, receptacle or light; repo audit circuit $450-$900, new box $180-$400, wafer $110-$275 before markup" },
      "Data and low voltage: Cat6 drops to a patch panel or the router, coax or fiber where needed, conduit for future cabling": { price: [150, 350], labor: 0.7, basis: "est", q: 3, note: "per drop" },
      "Task and accent lighting: pendant or sconce boxes, under-shelf LED strips with a driver": { price: [200, 500], labor: 0.55, basis: "est", q: 3, note: "per fixture or LED run with driver" },
      "HVAC: supply and return extended or a ductless mini-split added so the closed room holds temperature": { price: [600, 1500], labor: 0.65, basis: "derived", note: "duct extension; a ductless mini-split runs $3,500-$6,500" },
      "Drywall: new board on the partition, patches at boxes and drops, finished to Level 4": { price: [3, 5.5], labor: 0.75, basis: "derived", q: 120, note: "small patch quantities" },
      "Door: solid-core pre-hung door with a perimeter seal and privacy lock": { price: [650, 1300], labor: 0.4, basis: "est", q: 1 },
      "Glass partition or French doors to borrow light": { price: [2000, 4500], labor: 0.35, basis: "derived", note: "section 8 difference for the glass door version" },
      "Flooring: LVP, carpet tile or hardwood with transitions at the door": { price: [5.5, 11], labor: 0.4, basis: "derived", q: 132, note: "Fixr 2025 flooring per sqft plus install and transition" },
      "Built-ins: desk with cable management, shelving, filing drawers and a credenza in plywood with a shop finish": { price: [450, 950], labor: 0.45, basis: "derived", q: 10, note: "HomeAdvisor 2026 custom cabinets $500-$1,200/linear ft; desk runs are lower" },
      "Walls and ceiling painted two coats; an accent wall behind the camera position": { price: [1.75, 3.5], labor: 0.8, basis: "derived", q: 470, note: "per sqft of wall and ceiling" },
      "Baseboard, casing and shoe installed and caulked": { price: [6, 12], labor: 0.6, basis: "derived", q: 60, note: "HomeAdvisor 2025 baseboard $5.70-$9.00" },
      "Devices trimmed out, network tested, lighting scenes set, final clean and walk-through": { price: [300, 700], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "garage-conversion": {
    op: 0.35,
    opNote: "residential remodeler and general contractor",
    benchmark: {
      unit: "sqft",
      measures: "garage floor area converted",
      price: [121.5, 229.5],
      typicalQty: [400, 520],
      jobQty: 460,
      minJob: 25000,
      sources: ["JobFlex remodel method section 8 (reviewed), 2026: attached two-car, no bath $90-$170/sqft before markup, x1.35 = $121.50-$229.50", "Angi 2026: garage-to-ADU conversion $150-$400/sqft; a basic finish $25-$75/sqft", "HomeAdvisor 2025: permits $300-$1,000, electrical $1,000-$3,000, HVAC $300-$5,000"],
    },
    steps: {
      "Permits and plans: floor plan, energy compliance, zoning and parking review, ADU review where it applies, all inspections": { price: [2500, 6500], labor: 0.35, basis: "derived", q: 1, note: "plans and energy calc drafted plus city permit, review and zoning fees (about half); ADU review runs higher" },
      "Protection and demolition: garage door and opener removed, shelving and hooks cleared, slab cleaned and inspected": { price: [900, 2000], labor: 0.75, basis: "est", q: 1, note: "door and opener removed and hauled" },
      "Garage door opening infilled: 2x6 wall framed on a curb, sheathed, wrapped, insulated and finished with siding and trim to match the house": { price: [5000, 10000], labor: 0.6, basis: "est", q: 1, note: "16 ft opening: framing on a curb, sheathing, WRB, insulation, siding and trim" },
      "Windows and exterior door: egress window and a weather-rated entry door set in the infill or side walls, flashed and trimmed": { price: [1300, 3000], labor: 0.4, basis: "derived", q: 3, note: "per opening; HomeAdvisor windows $500-$2,000 and doors $200-$1,000 before flashing, trim and egress sizing" },
      "Floor: slab moisture-tested, 6 mil vapor barrier and pressure-treated sleepers with plywood or a floating subfloor to bring the floor level with the house": { price: [7, 12], labor: 0.5, basis: "derived", q: 460, note: "sleepers and 3/4 in. plywood over poly" },
      "Slab replaced or a raised framed floor built where the slab slopes to the door": { price: [12, 25], labor: 0.5, basis: "est" },
      "Interior framing: partitions for a bedroom, bath or closet, furring on the masonry walls": { price: [35, 70], labor: 0.7, basis: "derived" },
      "Insulation: R-15 in the walls, R-38 or R-49 in the ceiling, R-10 under the floor, air-sealed at the top plates": { price: [2, 3.5], labor: 0.45, basis: "derived", q: 1520, note: "per sqft of surface insulated (walls, ceiling and floor, about 3.3 x the floor)" },
      "Fire separation: 5/8 in. Type X drywall and a self-closing 20-minute door where the space still borders the house or a remaining garage": { price: [3.5, 6.5], labor: 0.7, basis: "est", note: "rated self-closing door adds $700-$1,400" },
      "Electrical: sub-panel or new circuits, receptacles to NEC spacing, lighting, smoke and CO detectors, bath and kitchen circuits": { price: [250, 500], labor: 0.7, basis: "derived", q: 24, note: "per circuit, device or alarm point; a sub-panel counts as about six points" },
      "Plumbing rough-in for a bathroom or kitchenette: drains cut into the slab, supply lines and a water heater tie-in": { price: [2500, 5000], labor: 0.7, basis: "derived", note: "per fixture with the slab cut; section 8 bath +$15,000-$30,000" },
      "HVAC: ductless mini-split heat pump sized for the room, or the house system extended with a supply and return": { price: [4000, 7500], labor: 0.4, basis: "derived", q: 1, note: "single-zone ductless heat pump installed; HomeAdvisor HVAC $300-$5,000" },
      "Drywall on walls and ceiling, taped and finished to Level 4": { price: [3, 4.75], labor: 0.75, basis: "derived", q: 1060, note: "per sqft of wall and ceiling board" },
      "Flooring over the new subfloor with transitions at the doors": { price: [6, 10.5], labor: 0.4, basis: "derived", q: 460, note: "LVP over the new subfloor with transitions" },
      "Interior doors, casing, baseboard and closet trim installed and caulked": { price: [10, 20], labor: 0.6, basis: "derived", q: 150, note: "per linear ft of base and casing; the door slabs spread into it" },
      "Walls, ceiling and trim primed and painted two coats": { price: [2, 3.75], labor: 0.8, basis: "derived", q: 1060, note: "per sqft of wall and ceiling" },
      "Exterior restoration: driveway apron and landscaping at the old door, gutters extended over the infill": { price: [12, 30], labor: 0.5, basis: "est" },
      "Final inspection, certificate of occupancy, final clean and walk-through": { price: [500, 1200], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "fireplace": {
    op: 0.3,
    opNote: "residential hearth dealer-installer",
    benchmark: {
      unit: "unit",
      measures: "fireplace installed, all-in",
      price: [6500, 15000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 3000,
      sources: ["The Stove Shop 2026: direct-vent prefab gas fireplace on a blank wall $8,200-$16,200 installed", "HomeGuide 2026: gas fireplace installation $2,300-$10,000"],
    },
    steps: {
      "Site review and permit: clearances to combustibles, vent route and termination location checked, gas load confirmed, mechanical and gas permits pulled": { price: [250, 650], labor: 0.5, basis: "est", q: 1, note: "site review plus the gas and mechanical permit fee" },
      "Protection: floors covered from the entry to the fireplace wall, furniture moved and covered, dust barrier at the opening": { price: [100, 300], labor: 0.8, basis: "est", q: 1 },
      "Existing fireplace, insert or stove removed and hauled, chimney or wall opening prepared": { price: [350, 900], labor: 0.8, basis: "est" },
      "Chase or enclosure framed with the manufacturer's clearances, a header over the unit and blocking for the mantel and finish": { price: [35, 75], labor: 0.7, basis: "derived", q: 10, note: "cost guides 2026: chase framing and drywall $400-$900" },
      "Direct-vent gas fireplace (ANSI Z21.88 listed) set in the framing, leveled and secured, with the log set and burner installed": { price: [2800, 6000], labor: 0.12, basis: "derived", q: 1, note: "cost guides 2026: direct-vent unit $1,500-$5,000, plus setting" },
      "EPA-certified wood-burning fireplace or insert set with the firebox liner and damper": { price: [3500, 7500], labor: 0.15, basis: "est" },
      "Electric fireplace recessed in the wall with a dedicated receptacle": { price: [900, 2800], labor: 0.25, basis: "est" },
      "Venting: coaxial direct-vent pipe run through the wall or roof with firestops at each floor and a listed termination cap": { price: [60, 140], labor: 0.35, basis: "est", q: 6, note: "termination cap spread over the run" },
      "Class A insulated chimney from the wood unit through the roof with a storm collar, cap and spark arrestor": { price: [90, 200], labor: 0.35, basis: "est" },
      "Roof or wall flashing at the vent penetration, sealed and counterflashed": { price: [150, 450], labor: 0.6, basis: "est", q: 1 },
      "Gas line: 1/2 in. or 3/4 in. black iron or CSST from the nearest supply with a shutoff, drip leg and flex connector, pressure-tested": { price: [15, 45], labor: 0.65, basis: "src", q: 30, note: "cost guides 2026: gas line $15-$50/linear ft" },
      "Electrical: 120V receptacle inside the chase for the blower, ignition and a wall switch or remote receiver": { price: [400, 800], labor: 0.7, basis: "src", q: 1, note: "The Stove Shop 2026: power to a fireplace $400-$800" },
      "Hearth: non-combustible hearth extension in tile or stone to the listed depth in front of the opening": { price: [30, 70], labor: 0.55, basis: "est", q: 8 },
      "Surround: tile, stone veneer or slab facing set on cement board around the opening": { price: [25, 55], labor: 0.55, basis: "est", q: 30, note: "tile or stone veneer; slab runs higher" },
      "Mantel and legs in wood, stone or cast at the listed clearance above the opening": { price: [600, 1800], labor: 0.35, basis: "est", q: 1 },
      "Drywall around the chase, taped, finished and painted to match the room": { price: [4, 7.5], labor: 0.75, basis: "derived", q: 80, note: "small quantities, hung, finished and painted" },
      "Commissioning: gas leak test, manifold pressure set, ignition and flame check, CO test, blower and remote programmed, owner walk-through": { price: [200, 450], labor: 0.95, basis: "est", q: 1 },
      "Final clean, packaging hauled and the warranty registered with the manufacturer": { price: [100, 250], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "painting": {
    op: 0.3,
    opNote: "residential painting contractor, specialty trade",
    benchmark: {
      unit: "sqft",
      measures: "wall and ceiling area painted",
      price: [1.9, 3.6],
      typicalQty: [1000, 4000],
      jobQty: 2500,
      minJob: 500,
      sources: ["HomeGuide 2026: painters charge $1-$3/sqft; a room $350-$850; trim $1-$4/linear ft", "HomeGuide 2026: whole-home interior $3,500-$10,000 (1,500 sqft home $4,500-$6,000); labor 70-85% of the job"],
    },
    steps: {
      "Protection and masking: canvas drop cloths on floors, plastic and paper masking over cabinets, counters, fixtures and furniture; switch plates, hardware and register covers removed and bagged": { price: [0.15, 0.35], labor: 0.75, basis: "derived", q: 700, note: "per sqft of floor area covered" },
      "Pressure wash siding and trim at low pressure with a mildewcide wash, rinsed and allowed to dry before coating": { price: [0.2, 0.5], labor: 0.9, basis: "est", note: "per sqft of siding washed" },
      "Surface prep: scrape and sand loose or failed paint to a feathered edge, dull glossy surfaces, fill nail holes and dents, re-caulk gaps at trim with paintable acrylic-latex caulk": { price: [0.2, 0.55], labor: 0.9, basis: "derived", q: 1800, note: "per sqft of wall surface prepped; about 15% of the paint line" },
      "Drywall and plaster repair: cracks, dents and nail pops cut back, taped and filled with setting compound, sanded flush and spot-primed": { price: [60, 95], labor: 0.85, basis: "derived", note: "painter/drywall rate $55-90/h (JobFlex remodel method section 8) plus compound" },
      "Lead-safe work practices under the EPA RRP rule: containment, HEPA cleanup and certified-renovator documentation": { price: [400, 1200], labor: 0.6, basis: "est", note: "per job; scales with the rooms disturbed" },
      "Primer: stain-blocking or bonding primer on bare, patched and repaired areas; full prime coat on new drywall or a dark-to-light color change": { price: [0.45, 0.9], labor: 0.7, basis: "derived", q: 250, note: "per sqft primed (spot-prime on a repaint, full coat on new board)" },
      "Walls: two finish coats of premium 100% acrylic-latex in the scheduled sheen, cut in by brush and rolled with a 1/2 in. nap roller": { price: [1.2, 2.4], labor: 0.8, basis: "derived", q: 1800, note: "HomeGuide walls $1-2/sqft of surface, lifted for premium acrylic" },
      "Ceilings: two coats of flat ceiling paint, rolled with a 3/4 in. nap roller for a uniform texture": { price: [1, 2], labor: 0.82, basis: "src", q: 700 },
      "Trim, baseboard, casing and crown: two coats of waterborne alkyd enamel in satin or semi-gloss, brushed or sprayed and back-brushed": { price: [1.5, 3.25], labor: 0.85, basis: "src", q: 360 },
      "Doors: both faces and edges, sanded between coats, two coats of waterborne enamel sprayed or brushed; hardware removed and reinstalled": { price: [90, 180], labor: 0.88, basis: "derived", q: 6, note: "two sides at $40-125 per side (2026 guides)" },
      "Window sashes, frames and sills prepped and coated in two coats of enamel, glass cut in by hand and razor-cleaned": { price: [75, 175], labor: 0.9, basis: "derived" },
      "Accent walls or additional colors: extra coat and separate cut-in for each scheduled color beyond the field color": { price: [0.4, 0.9], labor: 0.85, basis: "est" },
      "Exterior siding and body: two coats of 100% acrylic exterior paint or solid stain, sprayed and back-rolled": { price: [1.75, 3.75], labor: 0.78, basis: "est" },
      "Exterior trim, fascia, soffit, gutters and downspouts coated in two coats of exterior enamel": { price: [2, 4.5], labor: 0.85, basis: "est" },
      "Ladders, scaffolding or a lift staged and moved for ceilings, stairwells and walls above 12 ft": { price: [250, 700], labor: 0.4, basis: "est", note: "one stairwell or high wall; a lift rental day $300-500 is extra per added day" },
      "Walk-through with the client, touch-ups, masking removed, plates and hardware reinstalled, floors vacuumed and wiped; labeled leftover paint left for the owner": { price: [150, 400], labor: 0.9, basis: "est", q: 1, note: "scales with the rooms painted" },
    },
  },
  "drywall": {
    op: 0.25,
    opNote: "residential and light-commercial drywall subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "board area hung and finished (walls and ceilings)",
      price: [2.25, 4.25],
      typicalQty: [800, 3200],
      jobQty: 2000,
      minJob: 450,
      sources: ["HomeGuide 2026: drywall installed $1.50-$3.50/sqft hung, taped and finished; board $0.50-$0.80/sqft", "HomeGuide 2026: hanging only $0.85-$1.90/sqft; taping and mudding $0.35-$1.10/sqft", "Homewyse May 2026: drywall installation $2.26-$2.69/sqft"],
    },
    steps: {
      "Dust control and protection: floors covered, doorways and HVAC registers sealed with plastic, zip-wall barriers at the work area": { price: [0.2, 0.5], labor: 0.6, basis: "est", q: 500, note: "per sqft of floor area in the work zone" },
      "Remove damaged drywall or plaster and lath to the framing, debris bagged and hauled, dump fees included": { price: [1.2, 2.75], labor: 0.75, basis: "derived", note: "plaster and lath at the high end" },
      "Framing adjustments: new 2x4 or 25-gauge metal-stud partitions, furring over uneven masonry, shimming out-of-plane studs, blocking for grab bars and cabinets": { price: [15, 35], labor: 0.65, basis: "est", note: "per linear ft of wall framed or furred" },
      "Board delivery and stocking to each room, 1/2 in. or 5/8 in. sheets staged flat": { price: [150, 400], labor: 0.5, basis: "est", q: 1, note: "scales with sheet count, about $0.10/sqft of board" },
      "Hang walls: 1/2 in. regular gypsum board, screwed 16 in. o.c. with 1-1/4 in. drywall screws, joints staggered and gaps at electrical boxes held tight": { price: [1.05, 1.85], labor: 0.45, basis: "derived", q: 1500 },
      "Hang ceilings: 5/8 in. or 1/2 in. sag-resistant ceiling board across the joists, screwed 12 in. o.c. with adhesive at framing": { price: [1.25, 2.15], labor: 0.5, basis: "derived", q: 500 },
      "Moisture and mold-resistant board (purple or green board) at bathrooms, laundry and around tubs outside the wet zone": { price: [1.3, 2.2], labor: 0.42, basis: "derived", note: "hung price for moisture-resistant board, in place of the regular board line" },
      "5/8 in. Type X fire-rated board at the garage-to-house wall and ceiling, or at any rated assembly the plans call out": { price: [1.3, 2.2], labor: 0.45, basis: "derived", note: "hung price for Type X board, in place of the regular board line" },
      "Corner bead: paper-faced metal or vinyl bead on outside corners, J-bead at exposed edges, arch bead at curved openings": { price: [1.75, 3.25], labor: 0.7, basis: "derived", q: 120 },
      "Tape and finish to Level 4: paper tape bedded in all joints and inside corners, three coats of joint compound, screw heads spotted, sanded smooth": { price: [0.8, 1.7], labor: 0.88, basis: "derived", q: 2000, note: "HomeGuide installed total less the hang price" },
      "Level 5 skim coat over the whole surface for gloss paint, dark colors or critical side lighting": { price: [0.6, 1.3], labor: 0.85, basis: "derived" },
      "Texture: orange peel, knockdown or matched existing texture sprayed and knocked down, with a spot test to confirm the match": { price: [0.8, 1.8], labor: 0.8, basis: "est" },
      "Fire and smoke sealing at penetrations in rated walls with firestop sealant and putty pads at boxes": { price: [300, 900], labor: 0.6, basis: "est", note: "scales with the penetrations in the rated walls" },
      "Patch repairs: cut out to a square, add backing, new board, taped and finished to blend with the existing wall": { price: [125, 350], labor: 0.85, basis: "derived", note: "first patch on a visit $300-550 (the trip minimum), each more $95-190" },
      "Access panels set flush at valves, junction boxes and cleanouts": { price: [120, 300], labor: 0.6, basis: "est" },
      "PVA drywall primer rolled on all new board to seal the paper and compound before paint": { price: [0.3, 0.65], labor: 0.65, basis: "est" },
      "Final sanding, dust vacuumed with HEPA, scrap board and compound buckets hauled to the dump": { price: [250, 600], labor: 0.65, basis: "est", q: 1, note: "scales with the job; includes the dump fee" },
    },
  },
  "flooring-installation": {
    op: 0.3,
    opNote: "residential flooring contractor, specialty trade",
    benchmark: {
      unit: "sqft",
      measures: "floor area finished",
      price: [8, 14.5],
      typicalQty: [300, 1000],
      jobQty: 650,
      minJob: 750,
      sources: ["HomeGuide 2026: new flooring $4-$15/sqft installed, labor $2-$8/sqft", "HomeGuide 2025: LVP $4-$16/sqft installed (material $2-$10, labor $2-$6)", "Angi 2026: old flooring removal $1.50-$3.50/sqft"],
    },
    steps: {
      "Move furniture and appliances out of the rooms and return them after installation": { price: [50, 85], labor: 1, basis: "est", note: "per worker-hour" },
      "Remove existing flooring: carpet and pad with tack strip pulled, glued vinyl or wood scraped up, or tile broken out; staples pulled and debris bagged": { price: [1.25, 3.25], labor: 0.9, basis: "src", q: 650, note: "carpet at the low end; glued vinyl, wood or tile at the high end (tile $3-7)" },
      "Subfloor prep: adhesive residue scraped, squeaks re-screwed, seams sanded, loose or water-damaged plywood replaced, floor vacuumed": { price: [0.4, 1.25], labor: 0.75, basis: "est", q: 650 },
      "Concrete moisture test: in-situ RH probes (ASTM F2170) or calcium chloride (ASTM F1869) with results on file before glue-down or wood": { price: [250, 600], labor: 0.5, basis: "est" },
      "Moisture mitigation: two-part epoxy vapor barrier rolled over the slab where readings exceed the product limit": { price: [3, 6.5], labor: 0.4, basis: "est" },
      "Floor flattening: self-leveling underlayment poured over primed substrate to bring the floor within 3/16 in. in 10 ft": { price: [2.5, 5.5], labor: 0.45, basis: "est" },
      "Underlayment: 1/4 in. plywood, 1/4 in. cement board, or attached-pad foam or cork underlayment with seams taped": { price: [0.5, 1.5], labor: 0.5, basis: "derived", q: 650, note: "foam or cork at the low end, 1/4 in. plywood or cement board at the high end" },
      "Luxury vinyl plank or laminate: floating click-lock installation with 1/4 in. expansion gaps, end joints staggered 8 in. minimum, planks cut around jambs and cabinets": { price: [5, 9], labor: 0.42, basis: "src", q: 650, note: "standard-grade LVP or laminate supplied and installed" },
      "Hardwood: 3/4 in. solid nailed 8 in. o.c. over 15 lb felt, or engineered plank glued down with urethane adhesive; racked and acclimated before install": { price: [10, 17], labor: 0.36, basis: "derived", note: "standard prefinished oak or engineered plank supplied and installed" },
      "Carpet: tack strip at the perimeter, 8 lb rebond pad, seams heat-taped, carpet power-stretched and tucked": { price: [40, 70], labor: 0.22, basis: "derived", note: "carpet and 8 lb pad supplied and installed; Fixr 2025 average $67/sq yard" },
      "Sheet vinyl or linoleum fully adhered with flash-cove or coved base, seams heat-welded": { price: [5.5, 11], labor: 0.45, basis: "est" },
      "Stairs: treads, risers and matching stair nosing installed and fastened per step": { price: [80, 180], labor: 0.55, basis: "est", note: "per step" },
      "Transitions: T-molding, reducers, end caps and thresholds at doorways and material changes, color-matched to the floor": { price: [9, 18], labor: 0.4, basis: "derived", q: 12 },
      "Baseboard and shoe molding removed and reinstalled, or new primed shoe nailed to the base after the floor is down": { price: [2.5, 5], labor: 0.75, basis: "derived", q: 180, note: "new baseboard instead of shoe runs $6-9/linear ft installed" },
      "Doors undercut and door bottoms trimmed for the new floor height": { price: [40, 85], labor: 0.95, basis: "est" },
      "Toilets and appliances pulled, reset on new wax rings or flex lines and reconnected": { price: [100, 250], labor: 0.8, basis: "est" },
      "Old flooring and pad hauled to the dump; floor vacuumed and damp-mopped; leftover boxes and warranty registration left with the owner": { price: [200, 500], labor: 0.4, basis: "est", q: 1, note: "scales with the old flooring volume; dump fees are most of it" },
    },
  },
  "kitchen-remodel": {
    op: 0.35,
    opNote: "residential remodeler; repo ranges x 1.35",
    benchmark: {
      unit: "sqft",
      measures: "kitchen floor area remodeled",
      price: [305, 530],
      typicalQty: [120, 216],
      jobQty: 168,
      minJob: 18900,
      sources: ["JobFlex REMODEL_JOBS / remodel method section 8 (reviewed 2026): full 12x14 kitchen, same layout, semi-custom, 3 cm quartz, LVP $38,000-$66,000 before markup (x1.35 / 168 sqft = $305-$530/sqft)", "JobFlex REMODEL_JOBS (reviewed 2026): 10x10 galley, same layout, stock cabinets $22,000-$40,000 before markup ($297-$540/sqft at x1.35)", "HomeGuide 2026: quartz countertops $50-$200/sqft installed"],
    },
    steps: {
      "Permits and inspections: building, electrical and plumbing permits pulled, rough and final inspections scheduled": { price: [300, 1500], labor: 0, fee: true, basis: "src", q: 1, note: "permit fees at cost; King County, Bay Area, NYC $800-2,500" },
      "Protection and dust control: Ram Board on floors in the path, plastic dust walls with zipper doors, HVAC registers sealed, temporary kitchen set up for the owner": { price: [400, 1000], labor: 0.6, basis: "derived", q: 1, note: "repo protection $250-600 plus the temporary kitchen, x1.35" },
      "Demolition of cabinets, countertops, backsplash, sink and appliances: disconnected, removed and hauled": { price: [50, 110], labor: 0.95, basis: "derived", q: 36, note: "about 80% of the repo's $1,800-4,000 gut for a 12x14 (x1.35) over ~36 linear ft of run" },
      "Removal of existing flooring and underlayment down to the subfloor": { price: [2.5, 5.5], labor: 0.95, basis: "derived", q: 168, note: "the rest of the repo gut range over the floor area" },
      "Dumpster and disposal fees for demolition debris": { price: [600, 950], labor: 0.1, basis: "derived", q: 1, note: "20 cu yd dumpster, repo $450-700 x1.35" },
      "Wall removal: non-bearing wall taken out, or a bearing wall replaced with an engineered LVL header, posts and footings": { price: [350, 1400], labor: 0.65, basis: "derived", note: "non-bearing $350-750/linear ft; bearing with LVL, posts and footings $850-2,100/linear ft (section 8 x1.35)" },
      "Framing changes: new partition or pony wall, soffit removal, furring, blocking for wall cabinets and the range hood": { price: [30, 75], labor: 0.7, basis: "est" },
      "Rough plumbing: sink supply and 1-1/2 in. drain relocated, dishwasher and ice-maker lines, pot filler, gas line to the range with shutoff": { price: [800, 1650], labor: 0.75, basis: "derived", q: 2, note: "per fixture in place (repo $600-1,200 x1.35); a relocated fixture $2,000-4,700" },
      "Rough electrical: dedicated 20A small-appliance circuits, 240V/50A range circuit, dishwasher and disposal circuits, microwave, GFCI protection, recessed LED cans, under-cabinet lighting wiring, island receptacle": { price: [600, 1200], labor: 0.75, basis: "derived", q: 6, note: "per new 20 A circuit (repo $450-900 x1.35); 50 A range circuit $950-2,150; a box on an existing circuit $250-550" },
      "Range hood venting: 6 in. or 8 in. rigid duct to the exterior with a backdraft damper and wall or roof cap": { price: [550, 1300], labor: 0.7, basis: "est", q: 1 },
      "HVAC register relocated or toe-kick register added where cabinets cover the existing one": { price: [250, 600], labor: 0.7, basis: "est" },
      "Insulation in opened exterior walls: R-15 batts or spray foam before the walls close": { price: [1.5, 3], labor: 0.5, basis: "est" },
      "Drywall and patching: new 1/2 in. board where walls were opened, patches at old boxes and holes, taped and finished to Level 4": { price: [5, 10], labor: 0.8, basis: "derived", q: 70, note: "small-area patching; repo first-opening minimum $250-450 before markup" },
      "Flooring: tile, LVP or hardwood over the proper underlayment, run under the appliance openings": { price: [7, 12], labor: 0.4, basis: "derived", q: 116, note: "LVP (repo $3-4.50 material + $2-3.50 labor, x1.35); tile runs $18-35" },
      "Cabinets installed: wall, base and tall boxes leveled and screwed to studs, scribed to walls, fillers, toe kicks, end panels and crown": { price: [340, 675], labor: 0.2, basis: "derived", q: 42, note: "semi-custom $200-400/linear ft + install $50-100, x1.35; stock $200-400, custom $610-1,215" },
      "Countertops: 3 cm quartz or granite templated, fabricated with the chosen edge, undermount sink cutout and faucet holes, seams color-matched": { price: [80, 160], labor: 0.35, basis: "derived", q: 64, note: "3 cm quartz $60-120 installed (fabricator) x1.35; granite similar, laminate $34-61" },
      "Backsplash tile set on modified thinset, grouted and caulked at the counter, with outlet extenders and trim profile": { price: [24, 42], labor: 0.8, basis: "derived", q: 35, note: "subway tile $3-6 + labor $15-25, x1.35" },
      "Fixtures and appliances set and connected: sink, faucet, disposal, dishwasher, range, hood, refrigerator water line, microwave": { price: [300, 700], labor: 0.5, basis: "derived", q: 8, note: "per fixture or appliance; sink, faucet and disposal carry standard allowances, owner appliances are set only (range $160-340, dishwasher $245-470, hood $340-675)" },
      "Finish electrical: devices, plates, pendant and recessed trims, under-cabinet LED strips with driver and dimmer": { price: [100, 250], labor: 0.7, basis: "derived", q: 10, note: "per device or fixture (repo swap $75-150 x1.35); hardwired under-cabinet LED with driver and dimmer $1,200-2,700 per 16 ft run" },
      "Walls and ceiling primed and painted two coats in the scheduled sheen": { price: [2.75, 4.5], labor: 0.8, basis: "derived", q: 370, note: "repo kitchen paint $0.50 + $2-3 labor, x1.35" },
      "Trim: baseboard, casing and shoe molding installed, filled and caulked; floor transitions at doorways": { price: [6, 12], labor: 0.65, basis: "derived", q: 50 },
      "Cabinet pulls and knobs drilled with a jig and installed; final clean, punch list walk-through and warranty paperwork": { price: [900, 1900], labor: 0.6, basis: "derived", q: 1, note: "about 35-40 pulls on a standard allowance plus the final clean (repo $250-500 x1.35)" },
    },
  },
  "bathroom-remodel": {
    op: 0.35,
    opNote: "residential remodeler; repo ranges x 1.35",
    benchmark: {
      unit: "unit",
      measures: "bathrooms remodeled (full hall bath gut, about 5x8)",
      price: [24300, 43200],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 8100,
      sources: ["JobFlex REMODEL_JOBS / remodel method section 8 (reviewed 2026): hall bath gut 5x8 $18,000-$32,000 before markup (x1.35 = $24,300-$43,200); tiled shower with glass instead of the tub +$2,000-$4,000", "JobFlex remodel method section 8 (reviewed 2026): powder room in place $6,000-$12,000, primary bath $35,000-$70,000 before markup"],
    },
    steps: {
      "Permits and inspections: building, plumbing and electrical permits, rough and final inspections": { price: [350, 1200], labor: 0, fee: true, basis: "src", q: 1, note: "permit fees at cost; Seattle $600-1,500" },
      "Protection and dust containment: floor runners in the hallway, plastic on the door, exhaust fan or negative-air unit, a second bath kept available for the owner": { price: [340, 810], labor: 0.6, basis: "derived", q: 1, note: "repo protection $250-600 x1.35" },
      "Fixtures removed: toilet, vanity, tub or shower, mirror, accessories and lighting disconnected and hauled": { price: [140, 320], labor: 0.9, basis: "derived", q: 5, note: "about 40% of the repo's $1,200-2,800 gut (x1.35) over ~5 fixtures" },
      "Tile, backer and flooring demolished to the studs and subfloor, debris bagged, carried out and disposed of": { price: [5, 10.5], labor: 0.75, basis: "derived", q: 200, note: "rest of the repo gut plus the 10 cu yd dumpster ($400-650), x1.35, per sqft of surface removed" },
      "Framing: shower curb and bench, recessed niche, blocking for grab bars, glass and the vanity, wall moved or furred to fit the new tub": { price: [20, 50], labor: 0.8, basis: "est" },
      "Rough plumbing: supply and drain moved or replaced, 2 in. shower drain, pressure-balance or thermostatic valve with the trim set, tub overflow, toilet flange at finished floor": { price: [800, 1650], labor: 0.75, basis: "derived", q: 3, note: "per fixture in place (repo $600-1,200 x1.35); relocated $2,000-4,700; tub-to-shower drain and valve $1,200-2,450" },
      "Rough electrical: 20A GFCI circuit, vanity light and sconce boxes, exhaust fan circuit, switch loops, heated-floor thermostat wiring": { price: [200, 600], labor: 0.75, basis: "derived", q: 5, note: "per box, GFCI or switch loop (repo GFCI $120-200 x1.35); a new 20 A GFCI bath circuit $610-1,350" },
      "Exhaust fan: 80-110 CFM ENERGY STAR fan with a humidity sensor, ducted with rigid duct to a roof or wall cap": { price: [1200, 2700], labor: 0.65, basis: "derived", q: 1, note: "repo new fan ducted to a cap $1,000-2,200 x1.35 less the permit; replacement on the existing duct $470-950" },
      "Subfloor replaced with 3/4 in. plywood where water damage is found, sistered joists": { price: [8, 18], labor: 0.7, basis: "est" },
      "Wall board: 1/2 in. cement board at the wet walls, moisture-resistant drywall elsewhere, ceiling board, taped and finished": { price: [5, 9], labor: 0.6, basis: "derived", q: 200, note: "cement board at the wet walls, moisture-resistant drywall elsewhere" },
      "Shower pan: Schluter-KERDI foam tray or a hand-floated mud pan with a bonded drain, flood-tested for 24 hours before tile": { price: [1100, 2700], labor: 0.6, basis: "derived", q: 1, note: "foam tray $1,100-1,600, mud pan $1,600-2,700 (repo x1.35)" },
      "Waterproofing: KERDI sheet membrane or RedGard liquid membrane on the shower walls, curb, niche and ceiling, seams banded and corners sealed": { price: [6.5, 12], labor: 0.55, basis: "derived", q: 95, note: "repo membrane $2-4 + $3-5, x1.35" },
      "Electric radiant floor heat: heating mat embedded in the thinset with a floor sensor and programmable thermostat": { price: [15, 28], labor: 0.4, basis: "est" },
      "Floor tile: porcelain set on modified thinset with leveling clips, grouted with high-performance grout, sealed": { price: [18, 34], labor: 0.7, basis: "derived", q: 40, note: "repo floor tile $3-8 + $10-18, x1.35" },
      "Shower and wall tile: set on modified thinset with a laid-out pattern, edge profiles or bullnose, grouted and silicone-caulked at every change of plane": { price: [22, 44], labor: 0.72, basis: "derived", q: 90, note: "repo wall tile $3-8 + $12-25, x1.35; mosaics and niches $28-50" },
      "Vanity and top set and leveled, undermount sink, faucet and drain assembly connected": { price: [1700, 4000], labor: 0.3, basis: "derived", q: 1, note: "36 in. vanity with top, faucet and under-sink line on standard allowances (section 8 $1,400-3,200 x1.35)" },
      "Fixtures set: toilet on a new wax ring, shower trim and head, tub filler, towel bars, paper holder and grab bars into blocking": { price: [200, 600], labor: 0.35, basis: "derived", q: 5, note: "per fixture: toilet on a standard allowance $540-1,150, shower trim and head $350-700, each accessory $80-200" },
      "Frameless 3/8 in. tempered glass shower door and panel, measured after tile and installed with a header or clamps": { price: [2000, 4000], labor: 0.35, basis: "derived", q: 1, note: "60 in. door and panel (repo $1,500-3,000 x1.35); single 30 in. door $1,200-2,150" },
      "Walls and ceiling primed and painted two coats of moisture-resistant bath paint": { price: [3, 4.75], labor: 0.82, basis: "derived", q: 170, note: "repo bath paint labor $2-3 + material, x1.35" },
      "Trim and door: baseboard, casing and threshold installed, filled and caulked": { price: [7, 14], labor: 0.6, basis: "derived", q: 35 },
      "Mirror, lighting, fan grille and accessories installed; final clean, silicone cure time observed, walk-through and warranty": { price: [750, 1600], labor: 0.5, basis: "derived", q: 1, note: "mirror and vanity light on standard allowances plus the final clean (repo $250-500 x1.35)" },
    },
  },
  "tile-stone": {
    op: 0.25,
    opNote: "residential tile subcontractor, specialty trade",
    benchmark: {
      unit: "sqft",
      measures: "tile area installed (floor and wall)",
      price: [22, 42],
      typicalQty: [100, 400],
      jobQty: 250,
      minJob: 600,
      sources: ["HomeGuide 2026: tile installation $10-$50/sqft installed, $2,000-$10,000 for 200 sqft", "Homewyse May 2026: tile floor $16.38-$20.21/sqft installed (12x12 ceramic, set and grouted)"],
    },
    steps: {
      "Protection and staging: floors and finished surfaces covered, wet saw set up outside or in containment, tile delivered and stacked by room": { price: [200, 500], labor: 0.8, basis: "est", q: 1, note: "scales with rooms and the wet-saw setup" },
      "Substrate prep: flatness checked to 1/8 in. in 10 ft for large-format tile, high spots ground, low spots filled with patch or self-leveler, dust vacuumed": { price: [1.25, 3], labor: 0.7, basis: "derived", q: 150 },
      "Underlayment: 1/4 in. cement board screwed and taped over thinset, or Schluter-DITRA uncoupling membrane bonded to the subfloor": { price: [2.75, 5.5], labor: 0.53, basis: "derived", q: 150 },
      "Crack-isolation membrane over slab cracks and control joints so movement does not telegraph through the tile": { price: [2, 4], labor: 0.45, basis: "est" },
      "Waterproofing: sheet or liquid membrane rated to ANSI A118.10 on shower walls, floors, curbs and tub decks, seams banded": { price: [5, 10], labor: 0.55, basis: "derived" },
      "Shower pan: pre-sloped mud bed with a bonded membrane and drain, or a foam tray system, flood-tested before tile": { price: [900, 2000], labor: 0.55, basis: "derived", note: "foam tray $900-1,300, mud pan $1,300-2,000" },
      "Layout: center lines snapped, pattern dry-laid to balance cuts at walls and doorways, grout joint width and pattern approved with the owner": { price: [150, 400], labor: 1, basis: "est", q: 1 },
      "Floor tile set: porcelain or ceramic on modified thinset (ANSI A118.4 or A118.15), large-format back-buttered, leveling clips, 95% coverage in wet areas": { price: [13, 24], labor: 0.62, basis: "src", q: 150, note: "standard porcelain supplied and set on thinset; grout and sealing are their own lines" },
      "Wall tile set: field tile on thinset with spacers, cuts polished at exposed edges, outlets and valves cut clean": { price: [18, 34], labor: 0.68, basis: "derived", q: 100, note: "standard wall tile supplied and set" },
      "Natural stone: marble, travertine or slate sealed before grouting and set in white thinset to avoid staining, edges honed where exposed": { price: [22, 45], labor: 0.55, basis: "est" },
      "Mosaic and accent bands set on a mesh backing with a flat trowel, aligned with the field tile joints": { price: [28, 50], labor: 0.65, basis: "derived" },
      "Edge profiles and trim: Schluter metal profiles, bullnose or pencil liner at exposed edges, curbs and niche returns": { price: [9, 17], labor: 0.4, basis: "derived", q: 30 },
      "Recessed niche or shower bench tiled, sloped to drain, with mitered or profiled edges": { price: [400, 1000], labor: 0.7, basis: "est", note: "a niche $400-700, a bench up to $1,000+" },
      "Grouting: high-performance cement grout or epoxy grout in the chosen color, joints packed, cleaned and haze removed": { price: [1.5, 3], labor: 0.75, basis: "derived", q: 250, note: "epoxy grout +$1.50-3.00" },
      "Movement joints: color-matched 100% silicone at changes of plane, corners and perimeter per TCNA EJ171": { price: [2.5, 4.5], labor: 0.75, basis: "derived", q: 60 },
      "Sealing: penetrating sealer on natural stone and cement grout after cure": { price: [0.9, 1.75], labor: 0.6, basis: "derived", q: 250 },
      "Cleanup: thinset and grout buckets hauled, floors washed, scraps and extra tile boxed and left for the owner": { price: [150, 400], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "millwork-cabinet": {
    op: 0.3,
    opNote: "custom cabinet shop selling direct",
    benchmark: {
      unit: "linear ft",
      measures: "cabinet run (base and wall measured separately)",
      price: [550, 1150],
      typicalQty: [20, 50],
      jobQty: 35,
      minJob: 3000,
      sources: ["HomeGuide 2026: custom cabinets $500-$1,200/linear ft installed; $15,000-$30,000 for an average kitchen", "HomeGuide 2026: labor to build and install custom cabinets $200-$300/linear ft", "HomeGuide 2026: cabinet installation labor $50-$300/linear ft"],
    },
    steps: {
      "Field measurement of the rooms and shop drawings with elevations, sections and a hardware schedule for the owner's signature": { price: [500, 1500], labor: 1, basis: "est", q: 1, note: "scales with the rooms drawn" },
      "Door style, species, finish and hardware samples delivered for selection and approval": { price: [100, 350], labor: 0.3, basis: "est", q: 1 },
      "Fabrication of cabinet boxes: 3/4 in. plywood carcasses with edge-banded interiors, dovetailed hardwood drawer boxes, doors and drawer fronts in the chosen style": { price: [275, 600], labor: 0.55, basis: "derived", q: 35, note: "share of HomeGuide's $500-1,200/linear ft custom installed price" },
      "Shop finish: sprayed catalyzed conversion varnish or lacquer over stain or a tinted primer and enamel, sanded between coats": { price: [70, 180], labor: 0.7, basis: "derived", q: 35 },
      "Hardware: Blum or Salice soft-close hinges and full-extension undermount drawer slides fitted in the shop": { price: [25, 85], labor: 0.3, basis: "est", q: 50, note: "per hinge or per drawer slide pair; slides $70-120 fitted, hinges $15-30" },
      "Delivery and protection: cabinets blanketed and staged, floors covered along the carry path": { price: [300, 800], labor: 0.7, basis: "est", q: 1 },
      "Removal of the existing cabinets, shelving or closet system and disposal": { price: [30, 70], labor: 0.85, basis: "est" },
      "Installation of base, wall and tall cabinets: leveled on shims, screwed to studs with 2-1/2 in. cabinet screws, scribed to walls and ceilings": { price: [80, 160], labor: 0.95, basis: "src", q: 35 },
      "Closet system: adjustable shelving, double-hang and long-hang rods, drawer stacks and shoe shelves mounted to cleats and studs": { price: [120, 350], labor: 0.35, basis: "est" },
      "Finished end panels, fillers, toe kicks, crown, light rail and scribe molding fitted and fastened": { price: [40, 110], labor: 0.5, basis: "est", q: 35, note: "per linear ft of cabinet run" },
      "Interior accessories: pull-out trash, lazy susan, tray dividers, spice pull-outs, hamper and valet rod": { price: [150, 450], labor: 0.2, basis: "est" },
      "Pulls and knobs drilled with a jig and installed; doors and drawers aligned and gaps set": { price: [15, 35], labor: 0.55, basis: "est", q: 45, note: "pull or knob on a standard allowance, installed" },
      "Field verification of countertop template readiness and coordination with the fabricator": { price: [100, 300], labor: 1, basis: "est" },
      "Touch-up of the finish, punch-list adjustments and cleanup after the other trades are done": { price: [70, 110], labor: 0.9, basis: "derived", q: 8, note: "finish carpenter $65-110/h (JobFlex remodel method section 8)" },
    },
  },
  "countertop-installer": {
    op: 0.25,
    opNote: "countertop fabricator-installer, specialty trade",
    benchmark: {
      unit: "sqft",
      measures: "finished countertop area",
      price: [65, 125],
      typicalQty: [30, 80],
      jobQty: 55,
      minJob: 1200,
      sources: ["HomeGuide 2026: quartz countertops $50-$200/sqft installed, $1,500-$8,000 for an average kitchen", "JobFlex kitchen anchors (reviewed 2026): quartz $60-$120/sqft, granite $50-$100/sqft installed (fabricator's price)"],
    },
    steps: {
      "Slab or sheet material supplied: 3 cm quartz, granite, marble, quartzite, solid surface or porcelain in the selected color, viewed and tagged at the yard": { price: [28, 55], labor: 0.05, basis: "derived", q: 55, note: "standard 3 cm quartz or granite per finished sqft, yield included" },
      "Digital laser template of the cabinets after they are set, with sink, cooktop and faucet locations and overhangs confirmed with the owner": { price: [150, 350], labor: 0.9, basis: "est", q: 1 },
      "Removal of the existing countertops and backsplash, plumbing disconnected, debris hauled": { price: [10, 30], labor: 0.8, basis: "est", note: "laminate at the low end, stone or tile tops at the high end" },
      "CNC fabrication: slab cut to template, seams planned to minimize visible joints, vein-matched where the stone allows": { price: [12, 30], labor: 0.6, basis: "derived", q: 55 },
      "Edge profile: eased, bullnose, ogee or mitered edge polished on all exposed edges": { price: [5, 18], labor: 0.85, basis: "est", q: 30, note: "eased or bevel; bullnose and ogee $15-45, mitered $40-80" },
      "Undermount sink cutout polished on the reveal, with sink clips and bead of silicone; drop-in cutouts rough-cut": { price: [150, 350], labor: 0.85, basis: "est", q: 1 },
      "Cooktop cutout with the burner clearances the appliance requires": { price: [100, 250], labor: 0.85, basis: "est" },
      "Faucet, soap dispenser and filtered-water holes drilled to the fixture spec": { price: [25, 60], labor: 0.9, basis: "est", q: 2 },
      "Delivery and installation: tops set on beads of silicone, leveled and shimmed, seams joined with color-matched epoxy and pulled tight with seam setters": { price: [8, 18], labor: 0.85, basis: "derived", q: 55 },
      "Backsplash: 4 in. matching splash, or full-height slab splash behind the range and sink": { price: [25, 60], labor: 0.45, basis: "est", note: "4 in. splash; full-height slab splash is priced as top area" },
      "Waterfall end panel mitered and joined at the island or peninsula": { price: [900, 2500], labor: 0.5, basis: "est" },
      "Steel support brackets or corbels under overhangs beyond 10 in. on quartz and 6 in. on stone": { price: [60, 180], labor: 0.4, basis: "est" },
      "Penetrating sealer applied to natural stone and grout lines at the seam": { price: [1, 2.5], labor: 0.8, basis: "est" },
      "Final polish, silicone at the wall joint, protective film removed, cleanup and care instructions": { price: [100, 300], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "finish-carpentry": {
    op: 0.3,
    opNote: "residential finish carpentry trade",
    benchmark: {
      unit: "linear ft",
      measures: "trim installed (base and casing), doors and hardware included",
      price: [11, 22],
      typicalQty: [300, 1000],
      jobQty: 650,
      minJob: 400,
      sources: ["HomeGuide 2026: interior trim $4-$10/linear ft installed; baseboard $6-$9; casing $5-$10; crown $7-$16", "HomeGuide 2026: interior door $50-$500 for the door plus $100-$300 installation"],
    },
    steps: {
      "Site check: material acclimated on site, walls and floors checked for level, trim layout and reveals confirmed with the owner": { price: [150, 400], labor: 1, basis: "est", q: 1 },
      "Interior doors: pre-hung solid-core or hollow-core doors hung plumb, shimmed at the hinges, latches aligned and swing checked": { price: [275, 650], labor: 0.5, basis: "derived", q: 8, note: "standard pre-hung door supplied and hung; solid-core at the high end" },
      "Door hardware: hinges, passage and privacy sets, ball catches, stops and dummy levers installed and adjusted": { price: [60, 140], labor: 0.55, basis: "est", q: 8, note: "standard passage or privacy set supplied and installed" },
      "Door and window casing: primed MDF, poplar or stained hardwood in the chosen profile, mitered or with head casings and back band": { price: [5, 10], labor: 0.65, basis: "src", q: 310 },
      "Window stools, aprons and jamb extensions fitted to the drywall depth": { price: [150, 350], labor: 0.7, basis: "est" },
      "Baseboard: profile and height selected, coped inside corners, mitered outside corners, scarfed joints over studs": { price: [5.5, 9.5], labor: 0.65, basis: "src", q: 340 },
      "Shoe molding or quarter round at the base after finished floors are down": { price: [2.5, 5.5], labor: 0.75, basis: "derived" },
      "Crown molding: single or built-up profile with coped inside corners, nailed into blocking or the top plate": { price: [8, 16], labor: 0.65, basis: "src" },
      "Closet shelving and rod: 1x12 shelf on cleats with a chrome rod and center support, or a wire system": { price: [25, 60], labor: 0.5, basis: "est" },
      "Stair trim: skirt boards, treads and risers capped, handrail with brackets, newels and balusters set to code spacing": { price: [2500, 7000], labor: 0.55, basis: "est", note: "per flight of about 13 risers" },
      "Specialty features: window seat, box beams, coffered grid, mantel or built-up columns per the drawings": { price: [800, 3000], labor: 0.6, basis: "est", note: "per feature; a coffered ceiling runs $25-50/sqft of ceiling" },
      "Fastening and finish prep: 15 and 18-gauge nails, glue at miters, nail holes filled, joints caulked and sanded ready for paint": { price: [0.75, 1.75], labor: 0.9, basis: "est", q: 650 },
      "Stain-grade work: species matched, joints tight and unfilled, no exposed fasteners, delivered ready for the finisher": { price: [3, 8], labor: 0.8, basis: "est", note: "added to the trim line for stain-grade species and joinery" },
      "Scrap hauled, floors vacuumed, doors and hardware protected until paint": { price: [150, 400], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "insulation-weatherization": {
    op: 0.25,
    opNote: "residential insulation contractor, specialty trade",
    benchmark: {
      unit: "sqft",
      measures: "attic floor area insulated and air sealed",
      price: [2.5, 4.75],
      typicalQty: [800, 2000],
      jobQty: 1400,
      minJob: 1000,
      sources: ["HomeGuide 2026: blown-in insulation $0.90-$2.40/sqft, $900-$3,600 total", "Angi 2026: home energy audit $212-$698; blower door test $200-$450"],
    },
    steps: {
      "Energy assessment: blower door pre-test (CFM50 recorded), infrared scan, existing insulation depth and R-value measured, combustion appliances checked": { price: [250, 550], labor: 0.9, basis: "src", q: 1 },
      "Removal of old, wet or rodent-contaminated insulation by insulation vacuum into bags, disposed of, attic sanitized": { price: [1.5, 3.5], labor: 0.75, basis: "derived", note: "wet or rodent-contaminated, with sanitizing; clean removal $1-2" },
      "Attic air sealing: top plates, wire and pipe penetrations, chase openings and dropped soffits sealed with one-part foam, fire-rated caulk and rigid foam caps": { price: [75, 120], labor: 0.7, basis: "derived", q: 10, note: "installer rate with foam and caulk; a typical attic takes 6-12 hours" },
      "Rafter baffles at every soffit vent bay to keep the air path open, with a blown-in dam at the eave": { price: [8, 20], labor: 0.6, basis: "est", q: 30 },
      "Attic hatch or pull-down stair: rigid dam around the opening, insulated cover, weatherstripping": { price: [150, 450], labor: 0.5, basis: "est", q: 1 },
      "Blown-in attic insulation: loose-fill cellulose or fiberglass to the target R-value (R-49 or R-60), depth markers installed": { price: [1.2, 2.4], labor: 0.4, basis: "src", q: 1400 },
      "Dense-pack wall insulation: cellulose blown through 2 in. holes drilled from the exterior or interior, holes plugged and patched": { price: [2.25, 4.5], labor: 0.55, basis: "src", note: "2025-2026 guides: dense-pack cellulose $1.60-4.20/sqft of wall, plus hole patching" },
      "Crawlspace floor: R-19 or R-30 unfaced batts between joists held with insulation supports, or closed-cell foam at the rim joist": { price: [1.75, 3.5], labor: 0.5, basis: "est" },
      "Crawlspace ground vapor barrier: 6 mil to 12 mil polyethylene lapped 12 in., sealed to piers and the wall": { price: [0.8, 2], labor: 0.55, basis: "est" },
      "Closed-cell spray foam at the rim joist or roof deck, 2 lb density, applied to the listed thickness and R-value": { price: [3, 6], labor: 0.45, basis: "src", note: "closed-cell $3-5/sqft installed at about 2 in.; each added inch $1.75-3.50" },
      "Weatherstripping on exterior doors, door sweeps, caulk at window trim and sill plates": { price: [60, 175], labor: 0.6, basis: "est", q: 3, note: "per door or window" },
      "Ductwork in the attic or crawl sealed with mastic and mesh at joints and boots": { price: [4, 10], labor: 0.75, basis: "est" },
      "Blower door post-test with the before-and-after CFM50 and a rebate or utility program report": { price: [150, 350], labor: 0.9, basis: "derived", q: 1, note: "post-test only; a full blower door test runs $200-450" },
      "Cleanup: insulation vacuumed from the living space, bags and packaging hauled, work areas wiped down": { price: [100, 300], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "acoustic-ceiling": {
    op: 0.2,
    opNote: "commercial specialty subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "ceiling area (room footprint)",
      price: [5.5, 10],
      typicalQty: [1000, 6000],
      jobQty: 3500,
      minJob: 1200,
      sources: ["Fixr 2025: suspended acoustic ceiling $9.35/sqft installed on average; grid $1.50-$2.25/sqft material", "Homewyse 2026: drop-in acoustic ceiling tile $6.65-$9.29/sqft installed"],
    },
    steps: {
      "Submittals: reflected ceiling plan, grid and panel data sheets, seismic calculations and samples for architect approval": { price: [400, 1200], labor: 0.9, basis: "est", q: 1 },
      "Lifts, scaffolding and floor protection staged; room cleared and furniture covered": { price: [500, 1500], labor: 0.4, basis: "est", q: 1, note: "scales with area and ceiling height; lift rental counted as material" },
      "Existing ceiling grid and panels removed, hangers cut, material hauled and disposed": { price: [0.75, 1.75], labor: 0.8, basis: "est" },
      "Layout: finished height benchmarked with a laser, grid centered so border panels are equal and no less than half a panel": { price: [250, 600], labor: 1, basis: "est", q: 1 },
      "Hanger wires: 12-gauge galvanized wire at 4 ft o.c. to structure, three tight turns, wrapped to the main tee": { price: [0.35, 0.8], labor: 0.75, basis: "est", q: 3500 },
      "Perimeter wall angle: 7/8 in. or 2 in. shadowline molding leveled and fastened 16 in. o.c. at the walls": { price: [2, 4.5], labor: 0.65, basis: "est", q: 400 },
      "Suspension grid: 15/16 in. or 9/16 in. hot-dipped galvanized mains and cross tees (Armstrong Prelude or equal) leveled to 1/8 in. in 12 ft": { price: [1.5, 3], labor: 0.5, basis: "derived", q: 3500, note: "Fixr grid $1.50-2.25/sqft material plus hanging labor" },
      "Seismic bracing: compression struts and four-way 12-gauge splay wires at 12 ft o.c., 2 in. wall angle and stabilizer bars per ASTM E580": { price: [0.5, 1.25], labor: 0.6, basis: "est" },
      "Cutouts and independent support for light fixtures, diffusers, sprinkler drops, speakers and sensors, with fixture clips": { price: [25, 60], labor: 0.8, basis: "est", q: 60 },
      "Acoustical panels: 2x2 or 2x4 mineral fiber or fiberglass lay-in with the specified NRC and CAC, tegular or square edge": { price: [1.6, 3.6], labor: 0.25, basis: "derived", q: 3500, note: "standard 2x4 mineral fiber; Fixr mineral fiber $1.08-6.60/sqft" },
      "Specialty panels: cleanroom vinyl-faced, high-humidity, gypsum lay-in or wood or metal panels where the plans call for them": { price: [4, 12], labor: 0.2, basis: "est" },
      "Access panels or hinged sections at valves, dampers and junction boxes": { price: [75, 200], labor: 0.6, basis: "est", q: 4 },
      "Attic stock of panels and tees left for the owner, protective film removed, lifts demobilized and floors cleaned": { price: [300, 800], labor: 0.7, basis: "est", q: 1, note: "scales with the area" },
    },
  },
  "attic-insulation": {
    op: 0.25,
    opNote: "residential insulation contractor, specialty trade",
    benchmark: {
      unit: "sqft",
      measures: "attic floor area insulated",
      price: [2, 3.75],
      typicalQty: [800, 1800],
      jobQty: 1300,
      minJob: 900,
      sources: ["HomeGuide 2026: blown-in insulation $0.90-$2.40/sqft, $900-$3,600 total", "HomeEnergyDecisions 2026: attic insulation removal $1-$2/sqft for dry, uncontaminated insulation"],
    },
    steps: {
      "Attic inspection: existing depth and type measured, moisture and roof leaks noted, knob-and-tube wiring, bath fans and ventilation checked, photos taken": { price: [100, 300], labor: 0.95, basis: "est", q: 1 },
      "Protection: drop cloths under the hatch and along the path, blower hose run outside through a window": { price: [75, 200], labor: 0.8, basis: "est", q: 1 },
      "Existing insulation vacuumed out with an insulation vacuum and bagged for disposal": { price: [1, 2.25], labor: 0.7, basis: "src" },
      "Rodent cleanup: droppings vacuumed with HEPA, attic sanitized and deodorized": { price: [1.5, 4], labor: 0.75, basis: "est", note: "full decontamination can reach $7/sqft" },
      "Penetrations sealed before insulating: top plates, wire and pipe holes, chases and the drywall seam foamed and caulked": { price: [75, 120], labor: 0.7, basis: "derived", q: 6, note: "installer rate with foam and caulk; a typical attic takes 4-8 hours" },
      "Recessed light covers: fire-rated boxes over non-IC cans so insulation can cover them safely": { price: [40, 90], labor: 0.4, basis: "est" },
      "Soffit baffles stapled in every rafter bay at the eaves to keep the intake vents open": { price: [8, 20], labor: 0.6, basis: "est", q: 28 },
      "Attic hatch dam and insulated cover: rigid dam around the opening, R-10 or better foam cover, weatherstripped": { price: [150, 400], labor: 0.5, basis: "est", q: 1 },
      "Blown-in loose-fill fiberglass or cellulose installed to the target depth for R-49 or R-60, leveled evenly across the attic": { price: [1.2, 2.4], labor: 0.4, basis: "src", q: 1300 },
      "Faced or unfaced fiberglass batts laid between and across the joists where blown-in does not fit": { price: [1, 2.2], labor: 0.45, basis: "est" },
      "Open-cell spray foam on the underside of the roof deck to bring the attic inside the conditioned space": { price: [2, 4], labor: 0.45, basis: "derived", note: "open-cell $1.50-3.50/sqft installed, 5-6 in. on the deck; per sqft of roof deck" },
      "Bath and kitchen exhaust ducts connected to a roof or wall cap so they do not dump into the insulation": { price: [200, 500], labor: 0.6, basis: "est" },
      "Depth rulers placed every 300 sqft and an attic card posted with the material, depth and R-value": { price: [25, 75], labor: 0.7, basis: "est", q: 1 },
      "Cleanup and paperwork: living space vacuumed, bags hauled, rebate or utility program forms prepared for the owner": { price: [100, 250], labor: 0.9, basis: "est", q: 1 },
    },
  },
};
