// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "leak-detection": {
    op: 0.4,
    opNote: "small service-call firm; equipment-heavy detection visits",
    benchmark: {
      unit: "fixed",
      measures: "one leak-detection visit",
      price: [325, 850],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 175,
      sources: ["HomeGuide 2026: slab leak detection $150-$400, average $280", "Drizzlex 2026: plumber leak detection $175-$350; hidden slab or wall leaks $1,000+"],
    },
    steps: {
      "Intake and walk-through: water bill history, meter reading with all fixtures off, visible staining, warm spots and sound of running water noted": { price: [60, 125], labor: 0.95, basis: "est", q: 1, note: "trip and intake; many firms fold it into a flat detection fee" },
      "Meter and static pressure test: the house isolated at the main, meter low-flow indicator watched, pressure held on a gauge to confirm a loss": { price: [45, 100], labor: 0.95, basis: "est", q: 1 },
      "Isolation pressure test of each system separately: hot, cold, irrigation, pool or spa lines, to narrow the leak to one system": { price: [35, 75], labor: 0.95, basis: "est", q: 2, note: "per system isolated and held" },
      "Electronic acoustic detection: ground microphone and correlator on slabs, walls and yard lines with the system pressurized": { price: [100, 200], labor: 0.85, basis: "derived", q: 1.25, note: "specialist rate with correlator gear; plumber leak-detection time runs $75-$150/hr" },
      "Thermal imaging of floors, walls and ceilings to trace a hot-water slab leak or hidden moisture": { price: [100, 200], labor: 0.85, basis: "derived", note: "same specialist rate with a thermal camera" },
      "Tracer gas test: nitrogen-hydrogen mix introduced into the line and traced with a gas detector": { price: [400, 900], labor: 0.75, basis: "src", note: "tracer gas location quoted $400-$2,000; pool helium test $500-$800" },
      "Camera inspection of drain lines with a self-leveling camera and locator, recorded": { price: [2.5, 6], labor: 0.85, basis: "derived", note: "sewer camera $125-$500 per run of 50-100 ft" },
      "Dye test of tubs, showers, toilets and drains to separate a fixture leak from a pipe leak": { price: [35, 85], labor: 0.95, basis: "est", note: "per fixture tested" },
      "Pool and spa pressure test of the plumbing lines and dye test of the shell and fittings": { price: [200, 500], labor: 0.9, basis: "src", note: "HomeGuide 2026: pool line pressure test $200-$500" },
      "Moisture mapping with a pin and pinless meter of the affected floors and walls": { price: [0.2, 0.5], labor: 0.95, basis: "est", q: 120 },
      "Leak location marked on the floor or ground with paint and depth noted for the repair crew": { price: [20, 50], labor: 0.95, basis: "est", q: 1, note: "per located leak point" },
      "Written report with photos, thermal images, the located points and the recommended repair method": { price: [50, 125], labor: 0.95, basis: "est", q: 1 },
      "Small access opening cut to confirm the leak before the report": { price: [100, 250], labor: 0.9, basis: "est", note: "per opening; patching by others" },
    },
  },
  "drain-cleaning": {
    op: 0.4,
    opNote: "drain service calls; truck, jetter and camera overhead",
    benchmark: {
      unit: "fixed",
      measures: "one main-line drain call",
      price: [400, 1000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 150,
      sources: ["HomeGuide 2026: main sewer line cleaning $200-$500; with hydro jetting $600-$1,400", "HomeGuide 2026: sewer camera inspection $125-$500"],
    },
    steps: {
      "Assessment: which fixtures back up, cleanout located, line size and material identified, method chosen with the customer": { price: [50, 125], labor: 0.95, basis: "est", q: 1, note: "service-call or trip fee, often credited toward the work" },
      "Work area protected with drop cloths and the floor sanitized after the work": { price: [20, 50], labor: 0.8, basis: "est", q: 1 },
      "Cable a fixture or branch line (1-1/4 in. to 2 in.) through the trap arm or cleanout with a drum machine and the right cutter head": { price: [110, 250], labor: 0.9, basis: "derived", note: "HomeGuide: $100-$275 per fixture call; trip carried in step 0" },
      "Cable the main sewer line (3 in. to 4 in.) from the cleanout with a sectional machine and a cutter sized to the pipe": { price: [200, 450], labor: 0.85, basis: "src", q: 1, note: "HomeGuide: main sewer line cleaning $200-$500" },
      "Toilet pulled to reach the line and reset with a new wax ring and bolts": { price: [125, 250], labor: 0.9, basis: "est" },
      "Hydro-jetting with a 4,000-psi, 18-gpm jetter and rotating nozzles to scour grease, sludge and roots from the full pipe wall": { price: [250, 450], labor: 0.6, basis: "derived", note: "jetting runs $600-$1,400 per job at 2-3 hours; jetter counted as equipment" },
      "Root cutting with a chain-flail or root-saw head on the cable or jetter": { price: [150, 400], labor: 0.85, basis: "est" },
      "Descaling of cast-iron pipe with a chain knocker to restore the full diameter": { price: [8, 20], labor: 0.85, basis: "src", note: "descaling $5-$20/LF on top of the call fee; cast iron at the high end" },
      "Camera inspection of the cleared line with a self-leveling camera, recorded and shown to the customer": { price: [2, 5], labor: 0.85, basis: "derived", q: 80, note: "HomeGuide: camera inspection $125-$500 per line of about 80-100 ft" },
      "Line located with a sonde and marked on the surface with depth for any future repair": { price: [100, 250], labor: 0.95, basis: "est", note: "per defect located" },
      "Two-way cleanout installed on the main line at the house": { price: [1400, 3500], labor: 0.7, basis: "src", note: "Angi and Forbes 2026: two-way cleanout $1,400-$3,500 installed" },
      "Foaming root inhibitor treatment applied to the line after clearing": { price: [100, 300], labor: 0.45, basis: "est", note: "per application" },
      "Report with the video file, findings and any recommended repair": { price: [25, 75], labor: 0.9, basis: "est", q: 1 },
      "Equipment cleaned, debris bagged and removed, work area sanitized": { price: [25, 60], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "backflow-preventer": {
    op: 0.3,
    opNote: "residential plumbing specialty trade",
    benchmark: {
      unit: "unit",
      measures: "assemblies installed (3/4-1 in.)",
      price: [600, 1800],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 350,
      sources: ["RateYourPlumber 2025: installed DCVA $300-$800, RPZ $600-$1,500, PVB $150-$500", "HomeGuide 2026: backflow preventer $200-$1,000 installed by type"],
    },
    steps: {
      "Hazard assessment and device selection: reduced-pressure assembly (ASSE 1013) for high hazard, double-check (ASSE 1015) for low hazard, pressure vacuum breaker (ASSE 1020) for irrigation, per the water purveyor's cross-connection rules": { price: [75, 175], labor: 1, basis: "est", q: 1 },
      "Plumbing permit and the purveyor's installation application with the approved-assembly list": { price: [50, 200], labor: 0, fee: true, basis: "src", q: 1, note: "residential permit $25-$150 (RateYourPlumber 2025); purveyor application usually free" },
      "Water shutdown scheduled with the occupants or the purveyor for the tie-in": { price: [25, 100], labor: 0.9, basis: "est", q: 1, note: "coordination; a purveyor turn-off fee where charged" },
      "Existing assembly or non-compliant device removed and hauled off": { price: [75, 200], labor: 0.9, basis: "est" },
      "Excavation and concrete pad for an exterior above-ground assembly, or setting of a below-grade vault": { price: [250, 800], labor: 0.6, basis: "est" },
      "Backflow assembly supplied and installed by size (3/4 in. to 2 in. threaded, 2-1/2 in. and larger flanged) with full-port shutoffs, unions, strainer and test cocks, 12 in. minimum above grade or floor": { price: [400, 1100], labor: 0.4, basis: "src", q: 1, note: "3/4-1 in.: DCVA $300-$800, RPZ $600-$1,500 installed (RateYourPlumber 2025); 1-1/2 to 2 in. runs $1,500-$3,000+" },
      "Piping modifications to fit the assembly: Type L copper, brass or Schedule 80 PVC by size, with the required straight runs and supports": { price: [25, 55], labor: 0.65, basis: "est", q: 4 },
      "Support stand and bracing for larger assemblies": { price: [150, 400], labor: 0.4, basis: "est" },
      "Insulated enclosure (ASSE 1060) with heat trace for freeze protection": { price: [500, 1500], labor: 0.3, basis: "est", note: "ASSE 1060 enclosure with heater; insulated bags alone run $100-$400" },
      "Air-gap drain sized to the relief-valve discharge and run to a floor drain or outdoors": { price: [100, 400], labor: 0.7, basis: "derived", note: "RPZ drain pan or air-gap adds $100-$400" },
      "Thermal expansion tank on the domestic system now closed by the check valves": { price: [200, 450], labor: 0.55, basis: "est" },
      "Initial certification test by a certified tester with a calibrated gauge, forms filed with the purveyor and the tag attached": { price: [60, 150], labor: 0.9, basis: "src", q: 1, note: "RPZ test $75-$150, DCVA $60-$120 (RateYourPlumber 2025)" },
      "Backfill, surface restoration and cleanup": { price: [100, 350], labor: 0.85, basis: "est" },
      "Annual test reminder set and the test report copy left with the owner": { price: [0, 25], labor: 1, basis: "est", q: 1, note: "courtesy; often no charge" },
    },
  },
  "sump-pump": {
    op: 0.3,
    opNote: "residential plumbing and waterproofing trade",
    benchmark: {
      unit: "unit",
      measures: "sump systems installed",
      price: [1000, 2800],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 300,
      sources: ["The Basement Guide 2026: new system with pit $1,200-$2,500; pump swap in an existing pit $650-$1,200", "FixUpFirst 2026: new install with pit $800-$2,500; pump swap in an existing pit $300-$700"],
    },
    steps: {
      "Assessment: water table and seepage pattern, existing basin and pump condition, required capacity in GPH at the lift head, discharge route checked": { price: [75, 150], labor: 1, basis: "est", q: 1 },
      "Plumbing or building permit where the jurisdiction requires one for a new pit or exterior discharge": { price: [50, 200], labor: 0, fee: true, basis: "est" },
      "Old pump, check valve and failed basin removed and disposed of": { price: [75, 200], labor: 0.85, basis: "est" },
      "Slab saw-cut and broken out, pit excavated for the basin and the spoils hauled off": { price: [600, 1500], labor: 0.8, basis: "src", note: "new-pit labor $600-$1,800 (FixUpFirst 2026)" },
      "Perforated polyethylene basin (18 in. by 22 in. to 30 in.) set in washed gravel with a gasketed lid": { price: [150, 350], labor: 0.5, basis: "est", q: 1 },
      "Interior perimeter drain tile tied into the basin": { price: [35, 85], labor: 0.75, basis: "est", note: "slab cut, tile and re-pour along the run" },
      "Primary pump: 1/3 or 1/2 HP cast-iron submersible with vertical float, rated GPH at 10 ft of head, set on a stand in the basin": { price: [300, 650], labor: 0.4, basis: "derived", q: 1, note: "pump swap in an existing pit $300-$700 (FixUpFirst 2026)" },
      "Battery backup pump with 12 V deep-cycle battery, smart charger and high-water alarm": { price: [600, 1500], labor: 0.35, basis: "src", note: "installed backup quoted $300-$800 (The Basement Guide 2026) to $600-$2,000+ (2026 cost guides)" },
      "Water-powered backup ejector on the domestic supply with a backflow preventer": { price: [450, 1100], labor: 0.45, basis: "derived", note: "water-powered backup $300-$1,000 installed plus the backflow device" },
      "Discharge piping: 1-1/2 in. Schedule 40 PVC with a silent check valve and union, through the rim joist or wall and sealed": { price: [15, 35], labor: 0.7, basis: "est", q: 10, note: "check valve, union and wall penetration spread over the run" },
      "Exterior discharge: buried 4 in. line to daylight or a pop-up emitter at least 10 ft from the foundation, sloped to drain": { price: [15, 35], labor: 0.7, basis: "est", q: 15 },
      "Dedicated GFCI-protected receptacle within reach of the basin": { price: [200, 450], labor: 0.75, basis: "est", note: "new dedicated circuit from the panel" },
      "Sealed lid with pipe and cord grommets to keep radon and moisture out of the basement": { price: [50, 125], labor: 0.5, basis: "est", q: 1 },
      "Concrete floor patched around the basin and finished flush": { price: [15, 35], labor: 0.8, basis: "est", q: 8, note: "small patch; minimum-charge pricing" },
      "Test: basin filled and pumped through several cycles, float and check valve checked, alarm and backup tested": { price: [50, 125], labor: 1, basis: "est", q: 1 },
      "Wi-Fi water alarm or monitor at the pit": { price: [100, 250], labor: 0.3, basis: "est" },
      "Cleanup, old parts hauled off and pump operation explained to the homeowner": { price: [50, 125], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "residential-hvac": {
    op: 0.3,
    opNote: "residential HVAC trade; JobFlex card marks equipment +35%, materials +25%",
    benchmark: {
      unit: "unit",
      measures: "split systems replaced (AC, coil, furnace)",
      price: [9000, 15500],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 3500,
      sources: ["HomeCostCalcs 2026: furnace + AC replacement $7,000-$14,000 standard, $10,000-$20,000 high efficiency", "Today's Homeowner 2025: complete HVAC system install $5,000-$12,500", "JobFlex HVAC rate card 2026 (src/lib/hvac/ledger.ts): 3-ton AC + 80k 96% furnace builds to about $13,700"],
    },
    steps: {
      "Manual J room-by-room load calculation, Manual S equipment selection and a duct check, report given to the homeowner": { price: [100, 300], labor: 1, basis: "est", q: 1, note: "often folded into the sale" },
      "Mechanical permit with the final inspection scheduled; utility rebate and manufacturer promotion paperwork filed": { price: [150, 400], labor: 0, fee: true, basis: "derived", q: 1, note: "mechanical permit (JobFlex HVAC card $250); rebate paperwork folded in" },
      "Refrigerant recovered per EPA 608, old furnace, condenser, coil and pad disconnected and removed, hauled for recycling": { price: [450, 800], labor: 0.75, basis: "derived", q: 1, note: "JobFlex card: removal $450 + disposal $150" },
      "Gas furnace by input and efficiency (80% or 96% AFUE, single-stage, two-stage or modulating, ECM blower), set on the platform with a new return drop": { price: [2000, 3600], labor: 0.27, basis: "derived", q: 1, note: "JobFlex card: $200 per 10k BTU output at cost +35% plus $750 set; 80k 96% about $2,800" },
      "Air conditioner or heat pump condenser by tonnage and SEER2 or HSPF2 rating, set level on a new composite pad with service clearance": { price: [3000, 5600], labor: 0.12, basis: "derived", q: 1, note: "JobFlex card: AC $950/ton, HP $1,250/ton at cost +35%, plus $450 set and pad; 3-ton AC about $4,400" },
      "Matched cased evaporator coil with TXV, or a variable-speed air handler with electric heat strips by kW": { price: [1300, 2800], labor: 0.21, basis: "derived", q: 1, note: "JobFlex card: coil $350/ton or air handler $550/ton at cost +35%, plus $375 or $600 set; strips $45/kW extra" },
      "Refrigerant line set: 3/8 in. and 3/4 in. ACR copper, brazed under nitrogen, suction line insulated with 3/4 in. closed-cell foam, UV-wrapped outdoors": { price: [20, 32], labor: 0.55, basis: "derived", q: 25, note: "JobFlex card: $14/ft labor + $9/ft copper +25%" },
      "Electrical: weatherproof disconnect and sealtite whip at the condenser, breaker sized to the nameplate, 18/8 thermostat wire": { price: [275, 450], labor: 0.68, basis: "derived", q: 1, note: "JobFlex card: $225 connect + disconnect and whip +25%" },
      "Condensate: 3/4 in. PVC primary drain with trap and cleanout, secondary pan under attic or closet units, float switch wired to shut the system down": { price: [150, 350], labor: 0.55, basis: "derived", q: 1, note: "JobFlex card: drain kit $60 and pan $40 +25%, plus about an hour" },
      "Gas connection with flex, drip leg and shutoff, and 2 in. or 3 in. PVC intake and exhaust venting for a condensing furnace through the wall or roof": { price: [35, 65], labor: 0.5, basis: "derived", q: 12, note: "JobFlex card: gas connect $150, flex kit, vent kit $120, neutralizer and $12/ft venting spread over a 10-15 ft run" },
      "Sheet-metal supply and return plenums, transitions to the existing trunk and a 4 in. media filter rack": { price: [350, 800], labor: 0.6, basis: "est", q: 1 },
      "Duct modifications: new supply or return runs in R-8 flex or sheet metal, sealed with mastic": { price: [18, 40], labor: 0.6, basis: "derived", note: "JobFlex card: $220 labor + $95 run per ~20 ft flex run; sheet-metal replacement $25-$55/LF (HomeGuide)" },
      "Thermostat: programmable or smart communicating thermostat mounted, wired and set up on the homeowner's app": { price: [300, 550], labor: 0.35, basis: "derived", q: 1, note: "JobFlex card: $150 labor + $180 stat +25%; communicating stat about 1.6x" },
      "Evacuation to 500 microns, refrigerant charge weighed in and verified by subcooling and superheat, startup sheet completed": { price: [150, 300], labor: 0.9, basis: "derived", q: 1, note: "JobFlex card start-up $300, split with commissioning" },
      "Commissioning: static pressure, temperature split, gas pressure and combustion check, airflow at every register verified": { price: [150, 350], labor: 0.95, basis: "derived", q: 1, note: "JobFlex card start-up $300" },
      "Manufacturer warranty registered, homeowner walk-through on filters and thermostat, cleanup and packaging hauled off": { price: [75, 175], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "whole-house-fan": {
    op: 0.3,
    opNote: "residential ventilation specialty installer",
    benchmark: {
      unit: "unit",
      measures: "whole-house fans installed",
      price: [1300, 3000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 800,
      sources: ["HomeGuide 2026: whole-house fan $600-$2,300 installed; labor $600-$1,600 with a new circuit", "Homewyse May 2026: $1,045-$1,899 per fan installed with a new circuit, before permit and GC overhead"],
    },
    steps: {
      "Sizing and attic check: fan CFM at 2 to 3 CFM per square foot of living area, attic net free vent area verified at 1 square foot per 750 CFM, combustion appliances noted": { price: [40, 125], labor: 1, basis: "est", q: 1 },
      "Building and electrical permit where the jurisdiction requires one": { price: [75, 250], labor: 0, fee: true, basis: "est" },
      "Roof, gable or soffit vents added to reach the required net free area for the fan": { price: [150, 400], labor: 0.6, basis: "est", note: "per vent added" },
      "Ceiling opening located between joists, cut and framed for the intake grille": { price: [125, 300], labor: 0.85, basis: "est", q: 1 },
      "Whole-house fan by CFM (1,500 to 4,500) with an insulated, self-closing damper box (R-38 or better) and brushless motor, hung from the rafters on its isolation straps": { price: [700, 1500], labor: 0.2, basis: "derived", q: 1, note: "HomeGuide: fan $300-$1,500 before labor; insulated-damper brushless models sit in the upper half" },
      "Insulated flexible duct from the fan to the damper box, sized to the fan and kept straight": { price: [8, 18], labor: 0.5, basis: "est", q: 6 },
      "Intake grille and damper box set flush in the ceiling and sealed to the drywall": { price: [75, 200], labor: 0.8, basis: "est", q: 1 },
      "Dedicated 15 A circuit run from the panel to the fan with a disconnect switch in the attic": { price: [7, 14], labor: 0.7, basis: "derived", q: 35, note: "a new circuit adds about $300-$800 per HomeGuide labor ranges; breaker and disconnect spread over the run" },
      "Controls: wall switch with countdown timer, two-speed control, wireless remote or app module": { price: [75, 250], labor: 0.4, basis: "est", q: 1 },
      "Attic insulation moved back around the box and air-sealed so the fan does not short-circuit through the ceiling": { price: [60, 175], labor: 0.8, basis: "est", q: 1 },
      "Test at full speed with windows open, ceiling grille checked for closure and back-draft test at gas appliances": { price: [40, 100], labor: 1, basis: "est", q: 1 },
      "Drywall touch-up around the grille": { price: [8, 20], labor: 0.85, basis: "est", note: "small patch; paint by homeowner" },
      "Cleanup, packaging removed and operation explained to the homeowner": { price: [25, 60], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "iaq-specialist": {
    op: 0.3,
    opNote: "residential HVAC and IAQ specialty trade",
    benchmark: {
      unit: "fixed",
      measures: "one IAQ assessment and upgrade",
      price: [1800, 4200],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 300,
      sources: ["HomeAdvisor 2025: indoor air quality test $292-$584, average $437", "HomeGuide 2026: extended media filter $400-$800 and UV light $400-$800 installed", "HomeGuide 2026: whole-house air purifier $400-$4,000, average $2,610"],
    },
    steps: {
      "On-site assessment: walk-through, particulate, CO2, VOC, humidity and CO readings logged, HVAC filtration and ventilation inspected": { price: [100, 175], labor: 0.9, basis: "derived", q: 2.5, note: "basic IAQ test $292-$584 (HomeAdvisor 2025) at about 2-3 hours on site" },
      "Laboratory samples: mold spore, radon, formaldehyde or allergen samples sent to an accredited lab": { price: [40, 150], labor: 0, fee: true, basis: "est", note: "accredited lab fee per sample, passed through at cost" },
      "Written report with readings, lab results and prioritized recommendations": { price: [100, 250], labor: 0.95, basis: "est", q: 1 },
      "Media filter cabinet with a 4 in. or 5 in. MERV 13 filter installed at the return with a new filter rack and sealed transitions": { price: [400, 800], labor: 0.45, basis: "src", q: 1, note: "HomeGuide 2026: extended media filter $400-$800 installed" },
      "UV-C germicidal lamp at the evaporator coil to control biological growth": { price: [400, 800], labor: 0.35, basis: "src", q: 1, note: "HomeGuide 2026: UV filter $400-$800 installed" },
      "Whole-home air purifier (HEPA bypass, electronic or photocatalytic) ducted to the air handler": { price: [800, 2500], labor: 0.3, basis: "src", note: "HomeGuide 2026: electronic $500-$2,000, HEPA $1,000-$4,000 installed" },
      "Energy- or heat-recovery ventilator by CFM with balanced intake and exhaust, hoods and dampers": { price: [1800, 4000], labor: 0.45, basis: "derived", note: "ducted ERV/HRV $2,500-$6,000 in existing homes with ducting (Rise); ducts priced in step 7" },
      "Insulated duct for the ventilator or purifier, sealed with mastic": { price: [15, 35], labor: 0.6, basis: "est" },
      "Whole-house humidifier (bypass, fan-powered or steam) with humidistat and drain": { price: [500, 1300], labor: 0.45, basis: "src", note: "whole-house humidifier $400-$1,200 installed (HomeGuide 2026); steam units $1,200-$2,500" },
      "Whole-house dehumidifier ducted to the return with a condensate drain": { price: [1500, 3000], labor: 0.35, basis: "src", note: "HomeGuide 2026: $1,100-$3,500 installed" },
      "Source-removal duct cleaning with a negative-air machine and agitation, registers cleaned": { price: [450, 1000], labor: 0.85, basis: "src", note: "HomeGuide 2026: air duct cleaning $450-$1,000" },
      "IAQ controls: sensor-integrated thermostat or standalone monitor with humidity, CO2 and particulate readouts": { price: [250, 600], labor: 0.35, basis: "est", q: 1 },
      "Bath and kitchen exhaust fan upgrades by CFM with timers and exterior terminations": { price: [350, 800], labor: 0.6, basis: "est", note: "per fan with timer and exterior termination" },
      "Combustion safety: CO monitors and a spillage test at gas appliances": { price: [75, 175], labor: 0.6, basis: "est", q: 2, note: "per gas appliance: CO alarm plus spillage test" },
      "Commissioning: airflow and static pressure verified, ventilation balanced, post-installation readings compared with the assessment": { price: [150, 350], labor: 0.95, basis: "est", q: 1 },
      "Maintenance schedule and filter sizes left with the homeowner, warranties registered": { price: [25, 75], labor: 1, basis: "est", q: 1 },
    },
  },
  "duct-sealing": {
    op: 0.3,
    opNote: "residential HVAC and energy retrofit trade",
    benchmark: {
      unit: "unit",
      measures: "duct systems sealed and tested",
      price: [1200, 3200],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 350,
      sources: ["HomeGuide 2026: air duct sealing $1-$2/sqft or $1,000-$6,000; Aeroseal $1,500-$6,900", "Angi 2026: duct leakage test $115-$450, average $325"],
    },
    steps: {
      "Pre-test: duct leakage test with a calibrated fan at 25 Pa, total leakage and leakage to outside recorded in CFM25": { price: [150, 350], labor: 0.9, basis: "derived", q: 1, note: "standalone duct leakage test $115-$450 (Angi 2026); lower inside a sealing job" },
      "Visual inspection of accessible ducts in the attic, crawlspace or basement: disconnected runs, crushed flex and open boots noted with photos": { price: [75, 175], labor: 1, basis: "est", q: 1 },
      "Preparation: registers removed and openings plugged with foam blocks, the furnace, coil and filter protected": { price: [100, 250], labor: 0.85, basis: "est", q: 1 },
      "Disconnected or crushed runs reconnected or replaced with R-8 flex and strapped": { price: [150, 350], labor: 0.6, basis: "derived", note: "JobFlex HVAC card: $220 labor + $95 run +25% per run" },
      "Hand sealing of accessible joints, seams, takeoffs and plenums with UL 181 water-based mastic and fiber mesh": { price: [2, 5], labor: 0.8, basis: "est", q: 120, note: "per LF of accessible duct sealed" },
      "Aerosol sealing: computer-controlled sealant injected at 25 Pa from inside the ducts with real-time leakage readout until the target is reached": { price: [1200, 2600], labor: 0.6, basis: "derived", note: "2026 guides: Aeroseal about $1,500-$3,500 for a single-family home with tests; tests priced here in steps 0 and 10" },
      "Boots sealed to the drywall or subfloor at every register with mastic or foam": { price: [15, 40], labor: 0.85, basis: "derived", q: 12, note: "JobFlex card $45 per register covers joints and boots together" },
      "Air handler cabinet, filter rack and plenum seams sealed with foil tape and mastic": { price: [100, 250], labor: 0.8, basis: "est", q: 1 },
      "Duct insulation: R-8 wrap on ducts in unconditioned space": { price: [3, 8], labor: 0.6, basis: "derived", note: "JobFlex card: $35 labor + $28 wrap +25% per ~15 ft run" },
      "Registers reinstalled, plugs removed, a new filter installed": { price: [50, 125], labor: 0.8, basis: "est", q: 1 },
      "Post-test at 25 Pa with a before-and-after certificate showing the leakage reduction": { price: [125, 300], labor: 0.9, basis: "derived", q: 1, note: "retest $150-$300 (HERS testing guides 2026)" },
      "Static pressure and airflow check to confirm the system is not over-restricted after sealing": { price: [75, 175], labor: 0.95, basis: "est", q: 1 },
      "Utility rebate paperwork filed with the test certificate": { price: [25, 100], labor: 1, basis: "est" },
    },
  },
  "radiant-floor-heating": {
    op: 0.25,
    opNote: "hydronic specialty trade; larger tickets carry a lower markup",
    benchmark: {
      unit: "sqft",
      measures: "heated floor area",
      price: [9, 18],
      typicalQty: [500, 1500],
      jobQty: 1000,
      minJob: 1200,
      sources: ["HomeGuide 2026: hydronic radiant floor $7-$17/sqft; whole house $10,000-$34,000", "HomeGuide 2026: new boiler $3,200-$9,000 installed when a heat source is added"],
    },
    steps: {
      "Heat-loss calculation room by room, tubing layout with loop lengths and spacing (6 in. to 12 in. on center), zoning and supply-temperature design": { price: [400, 1200], labor: 1, basis: "est", q: 1, note: "scales with rooms and zones" },
      "Mechanical, plumbing and electrical permits with rough-in and final inspections": { price: [200, 600], labor: 0, fee: true, basis: "est", q: 1, note: "three permits together; scale with job value in many cities" },
      "Floor preparation: subfloor cleaned or 2 in. XPS insulation (R-10) and vapor barrier under a slab, edge insulation at the perimeter": { price: [1.5, 3.5], labor: 0.4, basis: "derived", q: 1000, note: "2 in. XPS, vapor barrier and edge strip under a slab; subfloor cleaning alone runs under $0.50" },
      "Hydronic tubing: 1/2 in. oxygen-barrier PEX stapled to foam, tied to wire mesh, or in aluminum transfer plates under the subfloor, looped per the layout": { price: [3, 6], labor: 0.6, basis: "derived", q: 1000, note: "PEX at $0.50-$1.00/ft, 1-1.5 ft per sqft, plus placement labor; transfer plates at the high end" },
      "Electric radiant mat or cable (120 V or 240 V, 12 to 15 W per square foot) embedded in self-leveling underlayment or thinset": { price: [8, 15], labor: 0.35, basis: "src", note: "HomeGuide 2026: electric floor heating $8-$15/sqft" },
      "Stainless manifold with flow meters, balancing valves and zone actuators, mounted in a recessed cabinet": { price: [700, 1600], labor: 0.35, basis: "est", q: 1 },
      "Heat source: condensing boiler (95% AFUE) by MBH, or air-to-water heat pump, with venting and gas connection": { price: [4500, 9000], labor: 0.35, basis: "src", note: "new boiler $3,200-$9,000 installed (HomeGuide 2026); 2025 replacements average about $6,100" },
      "Near-boiler piping: circulator pumps, mixing valve, expansion tank, air separator, fill valve and relief valve, one set per zone group": { price: [1500, 3500], labor: 0.55, basis: "est", q: 1 },
      "Gypsum overpour or concrete topping over the tubing (1-1/2 in. typical), poured and cured": { price: [3.5, 7], labor: 0.5, basis: "derived", note: "gypcrete over tubing quoted $4-$12/sqft; whole-floor pours at the low end" },
      "Thermostats with floor sensors, one per zone, wired to the zone controller": { price: [200, 450], labor: 0.45, basis: "est", q: 3, note: "per zone" },
      "Electrical: circuit for the boiler and pumps, or GFCI-protected dedicated circuits for the electric mats": { price: [400, 900], labor: 0.65, basis: "est", q: 1 },
      "Pressure test: tubing at 60 to 100 psi air before the pour and held through it, or resistance and megger test of the electric cable, logged": { price: [150, 350], labor: 0.9, basis: "est", q: 1 },
      "Fill, purge, glycol where specified and flow balancing at the manifold": { price: [250, 600], labor: 0.8, basis: "est", q: 1 },
      "Startup and commissioning: supply temperatures, outdoor reset and floor sensors set, homeowner walk-through": { price: [250, 500], labor: 0.95, basis: "est", q: 1 },
    },
  },
  "fire-alarm": {
    op: 0.2,
    opNote: "commercial specialty subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "building gross area",
      price: [2, 5],
      typicalQty: [5000, 20000],
      jobQty: 12500,
      minJob: 5000,
      sources: ["Spectrum Fire Protection 2026: commercial fire alarm $3-$7/sqft installed", "Safe and Sound 2026: $1-$3/sqft new construction, $4-$12 occupied retrofit; addressable panel $2,000-$10,000+"],
    },
    steps: {
      "Design and shop drawings: device layout, battery and voltage-drop calculations, NFPA 72 submittal stamped and filed with the fire marshal": { price: [1500, 4000], labor: 1, basis: "est", q: 1, note: "scales with building area and device count" },
      "Fire alarm permit, plan review and the AHJ acceptance test scheduled": { price: [400, 1500], labor: 0, fee: true, basis: "src", q: 1, note: "permit $300-$1,500 (Spectrum 2026); plan review $200-$500 (Safe and Sound 2026); scales with area" },
      "Existing panel and devices decommissioned and removed with the monitoring company notified": { price: [500, 1500], labor: 0.9, basis: "est", note: "per system" },
      "Addressable fire alarm control panel by loop and NAC capacity, with enclosure, power supply and standby batteries sized to the calculation": { price: [3000, 8000], labor: 0.3, basis: "src", q: 1, note: "panels $1,500-$8,000 (Spectrum 2026); addressable $2,000-$10,000+ (Safe and Sound 2026)" },
      "Fire alarm cable: FPL, FPLR or FPLP by gauge, run in raceway or open where the code allows, supported and marked": { price: [1.5, 3], labor: 0.75, basis: "derived", q: 3500, note: "cable-only share of the $3-$8/ft conduit-and-wiring figure (Spectrum 2026)" },
      "Raceway: 3/4 in. EMT with boxes and fittings for exposed or protected runs": { price: [8, 15], labor: 0.7, basis: "est" },
      "Initiating devices: smoke and heat detectors, duct detectors, manual pull stations, waterflow and tamper monitor modules": { price: [150, 350], labor: 0.5, basis: "src", q: 22, note: "smoke $150-$400, heat $125-$350, pull station $100-$250 installed (Spectrum 2026); duct detectors run higher" },
      "Notification appliances: horn-strobes, strobes and speakers set to the candela and coverage on the drawings": { price: [150, 350], labor: 0.5, basis: "src", q: 20, note: "horn/strobe $150-$400 installed (Spectrum 2026)" },
      "Remote annunciator at the fire department entrance": { price: [1200, 2500], labor: 0.4, basis: "est" },
      "Dual-path communicator (cellular and IP) to the central station": { price: [600, 1500], labor: 0.35, basis: "src", q: 1, note: "monitoring equipment $500-$2,000 (Spectrum 2026)" },
      "Interfaces: elevator recall, HVAC shutdown, door holder release, sprinkler monitoring and other relay outputs": { price: [250, 600], labor: 0.6, basis: "est", q: 3, note: "per relay or control interface" },
      "Firestopping at every cable and raceway penetration through rated walls and floors": { price: [50, 125], labor: 0.7, basis: "est", q: 10, note: "per penetration" },
      "Programming: device addressing, zone mapping, sequence of operations, labels and the device map at the panel": { price: [800, 2000], labor: 1, basis: "est", q: 1, note: "scales with device count" },
      "Pre-test of every device, then the AHJ acceptance test with the NFPA 72 record of completion": { price: [800, 2000], labor: 1, basis: "src", q: 1, note: "acceptance testing $500-$2,000 (Spectrum 2026); scales with device count" },
      "Monitoring account set up with the central station and signal test": { price: [100, 300], labor: 0.9, basis: "est", note: "recurring monitoring quoted separately" },
      "Owner training, as-built drawings, O&M and inspection log turned over; packaging hauled off": { price: [400, 1000], labor: 0.9, basis: "est", q: 1, note: "scales with building size" },
    },
  },
  "residential-sprinkler-retrofit": {
    op: 0.25,
    opNote: "fire sprinkler subcontractor on residential retrofits",
    benchmark: {
      unit: "sqft",
      measures: "floor area protected",
      price: [4, 8],
      typicalQty: [1500, 2800],
      jobQty: 2150,
      minJob: 5000,
      sources: ["HomeGuide 2026: sprinkler retrofit $2-$7/sqft", "NFSA 2025: residential retrofit bid $5.14/sqft; West Coast in-unit retrofits $5-$10/sqft"],
    },
    steps: {
      "Water supply evaluation: flow and pressure test at the meter or hose bib, meter size and service line checked against the NFPA 13D demand": { price: [150, 400], labor: 0.9, basis: "est", q: 1 },
      "NFPA 13D design: head layout, hydraulic calculations and plans submitted to the fire marshal and building department": { price: [800, 2000], labor: 1, basis: "est", q: 1, note: "scales with home size and head count" },
      "Fire sprinkler permit with rough-in and final inspections scheduled": { price: [200, 800], labor: 0, fee: true, basis: "est", q: 1, note: "some jurisdictions charge per head or by area" },
      "Water service upgrade: 1 in. or larger service line from the meter and meter upsizing with the purveyor": { price: [50, 150], labor: 0.6, basis: "src", note: "JobFlex utility bid data: water service in a yard $50-$150/LF national; purveyor meter fee extra" },
      "Stored-water tank and pump sized to the two-head demand": { price: [3500, 7000], labor: 0.3, basis: "est", note: "tank and pump package installed" },
      "Riser: control valve, check valve, pressure gauge, drain and waterflow switch in an accessible location": { price: [800, 1800], labor: 0.45, basis: "est", q: 1 },
      "Backflow preventer at the sprinkler connection as the purveyor requires": { price: [500, 1200], labor: 0.4, basis: "derived", note: "1 in. DCVA $300-$800 installed (RateYourPlumber 2025) plus the tie-in" },
      "Ceiling and wall openings cut for the pipe runs and heads, marked for patching": { price: [30, 75], labor: 0.95, basis: "est", q: 22, note: "per opening" },
      "Sprinkler piping: listed CPVC or PEX by size run through the attic, joists and walls with hangers per the listing": { price: [10, 18], labor: 0.65, basis: "derived", q: 320, note: "CPVC $8-$12/LF installed in open construction; retrofit through finished spaces runs higher" },
      "Freeze protection: insulation tented over pipe in the attic and at exterior walls": { price: [2, 5], labor: 0.6, basis: "est" },
      "Residential concealed pendent and sidewall heads by K-factor and temperature rating, with white cover plates": { price: [90, 180], labor: 0.5, basis: "derived", q: 20, note: "concealed head $25-$45 plus cover plate, fittings and install" },
      "Tie-in to the domestic plumbing for a multipurpose network": { price: [300, 800], labor: 0.6, basis: "est" },
      "Waterflow switch wired to an exterior bell or the home alarm panel": { price: [250, 600], labor: 0.6, basis: "est", q: 1 },
      "Drywall patch: openings closed, taped and textured to match, ready for paint": { price: [8, 16], labor: 0.85, basis: "est", q: 50 },
      "Hydrostatic test and flush, flow test at the inspector's test connection, final inspection": { price: [300, 700], labor: 0.95, basis: "est", q: 1 },
      "Owner documents: as-built plan, insurance certificate, maintenance instructions; cleanup and debris hauled off": { price: [150, 400], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "electrical": {
    op: 0.2,
    opNote: "commercial electrical subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "floor area wired (commercial build-out)",
      price: [16, 32],
      typicalQty: [2500, 7500],
      jobQty: 5000,
      minJob: 1500,
      sources: ["Homewyse 2026: light fixture installed $394-$583 each; appliance circuit $741-$910 per circuit", "Fixr 2025: electrician $88-$163/hour; new outlet $120-$200 installed"],
    },
    steps: {
      "Electrical permit, plan review and inspections: load calculation submitted, rough-in, service and final inspections scheduled and fees paid": { price: [600, 1800], labor: 0, fee: true, basis: "est", q: 1, note: "city electrical permit, usually valuation-based; scales with job size" },
      "Submittals and coordination: one-line diagram, panel schedules, fixture and gear cut sheets, lead times confirmed with the supplier before rough-in": { price: [800, 2400], labor: 1, basis: "est", q: 1, note: "PM and drafting hours; scales with job size" },
      "Utility coordination: service application, meter or CT cabinet specification, scheduled shutdown and reconnect with the utility": { price: [500, 1500], labor: 1, basis: "est", note: "coordination only; utility charges passed through" },
      "Lockout-tagout of affected feeders, temporary power and lighting kept live for the occupied areas, floor and finish protection in the work zone": { price: [800, 2400], labor: 0.7, basis: "est", q: 1, note: "scales with the occupied area kept live" },
      "Demolition: existing devices, fixtures, raceway and wire removed back to the source, abandoned conductors pulled out, boxes blanked and made safe": { price: [35, 90], labor: 0.9, basis: "derived", note: "per device, fixture or circuit removed: 0.3-0.6 h at $110-150/h" },
      "Service entrance: meter base or CT cabinet, service disconnect, service-entrance conductors sized to the calculated load, grounding electrode system (two rods, Ufer and water bond, GEC by AWG)": { price: [9000, 24000], labor: 0.45, basis: "est", note: "200-400 A 3-phase service; 800 A and up runs higher" },
      "Distribution gear: main distribution panel and branch panelboards by amperage, voltage and space count (for example 400 A, 208Y/120 V 3-phase, 42-space), mounted, bonded and labeled": { price: [4500, 9500], labor: 0.35, basis: "derived", q: 2, note: "225 A 42-space panelboard installed; a 400-800 A main distribution panel runs $12,000-30,000" },
      "Feeders: EMT, rigid or Schedule 40 PVC raceway by trade size with THHN/THWN-2 copper conductors by AWG or kcmil, pulled and terminated at both ends": { price: [35, 90], labor: 0.45, basis: "derived", q: 150, note: "100-225 A feeder in EMT; copper by AWG/kcmil drives the spread" },
      "Branch-circuit raceway and wire: 3/4 in. EMT with #12 or #10 THHN copper, boxes, fittings and supports every 10 ft, or MC cable where the specification allows": { price: [9, 20], labor: 0.65, basis: "derived", q: 3500, note: "3/4 in. EMT with #12 THHN ~$14-20/ft; MC cable ~$9-12/ft" },
      "Wiring devices: 20 A specification-grade receptacles (GFCI in wet and kitchen locations, isolated-ground where scheduled), switches, cover plates": { price: [90, 180], labor: 0.75, basis: "derived", q: 80, note: "spec-grade device, box, plate, termination; from Fixr $120-200 installed outlet" },
      "Lighting fixtures: LED troffers, high-bays, strips and downlights by lumen output and color temperature, hung, wired and lamped per the fixture schedule": { price: [260, 520], labor: 0.4, basis: "derived", q: 65, note: "2x4 LED troffer or downlight installed; high-bays $450-800" },
      "Lighting controls: occupancy and vacancy sensors, daylight-harvesting photocells, 0-10 V dimming and time-clock control as the energy code (IECC) requires": { price: [180, 420], labor: 0.5, basis: "est", q: 15 },
      "Emergency and exit lighting: battery-backed exit signs and emergency heads on the life-safety circuit, 90-minute test": { price: [220, 450], labor: 0.45, basis: "est", q: 10 },
      "Equipment connections: fused or non-fused disconnects, motor starters and sealtite whips to HVAC units, kitchen equipment, pumps and owner-furnished machines": { price: [650, 1600], labor: 0.6, basis: "derived", q: 5, note: "disconnect, whip and termination; from Homewyse $741-910 per appliance circuit" },
      "Firestopping of every raceway and cable penetration through rated walls and floors with a UL-listed system, labeled": { price: [60, 160], labor: 0.7, basis: "est", q: 20, note: "per penetration" },
      "Testing: insulation-resistance (megger) test on feeders, lug torque to the manufacturer's values, phase rotation on three-phase equipment, GFCI and AFCI trip test": { price: [600, 1800], labor: 0.95, basis: "est", q: 1, note: "scales with feeder and panel count" },
      "Typed panel schedules, circuit and device labeling, arc-flash warning labels and as-built drawings turned over to the owner": { price: [500, 1500], labor: 0.9, basis: "est", q: 1 },
      "Daily cleanup, packaging and scrap wire recycled, demolished fixtures and ballasts disposed of at a licensed facility": { price: [400, 1200], labor: 0.6, basis: "est", q: 1, note: "includes lamp and ballast disposal fees" },
    },
  },
  "plumbing": {
    op: 0.2,
    opNote: "commercial plumbing subcontractor",
    benchmark: {
      unit: "unit",
      measures: "plumbing fixtures installed (fixture count)",
      price: [3500, 7000],
      typicalQty: [8, 20],
      jobQty: 14,
      minJob: 2000,
      sources: ["Homewyse 2026: toilet installed $635-$1,151; faucet installed $514-$845", "Fixr 2025: plumber $75-$150/hour"],
    },
    steps: {
      "Plumbing permit, plan review and inspections: underground, rough-in and final inspections scheduled, backflow and medical-gas permits where the project needs them": { price: [500, 1500], labor: 0, fee: true, basis: "est", q: 1, note: "city plumbing permit and inspections; scales with fixture count" },
      "Submittals: fixture schedule with cut sheets, pipe and valve schedule, isometric riser drawings and coordination with the mechanical and electrical trades": { price: [600, 1800], labor: 1, basis: "est", q: 1 },
      "Utility coordination: water and sewer tap applications, meter sizing and a scheduled shutdown of the existing service": { price: [500, 1500], labor: 1, basis: "est", note: "coordination only; tap, meter and impact fees passed through at the utility's rate" },
      "Demolition: existing fixtures, water heaters and piping disconnected, capped at the source and removed, waste lines plugged against sewer gas": { price: [120, 300], labor: 0.85, basis: "est", note: "per fixture or heater removed" },
      "Saw-cut and break out the slab along the underground pipe routes, trench to grade and haul the rubble": { price: [15, 35], labor: 0.7, basis: "est", note: "per sqft of slab cut, broken out and hauled; slab patch by others" },
      "Underground sanitary and storm drainage: Schedule 40 PVC, ABS or service-weight cast iron by diameter, bedded in sand, sloped 1/4 in. per ft (1/8 in. per ft at 4 in. and larger), backfilled and compacted": { price: [45, 95], labor: 0.6, basis: "derived", q: 100, note: "3-4 in. PVC or cast iron in trench, bedded and backfilled" },
      "Above-ground drain, waste and vent rough-in: Schedule 40 PVC solvent-weld or no-hub cast iron with stainless couplings by diameter, hung on rod and clevis, vents through the roof with lead or neoprene flashings": { price: [30, 60], labor: 0.6, basis: "derived", q: 220, note: "1-1/2 to 4 in. PVC or no-hub, hung" },
      "Domestic hot and cold water rough-in: Type L copper with lead-free solder, or PEX-A with expansion fittings, by diameter, run in trunk-and-branch layout with dielectric unions at the equipment": { price: [18, 40], labor: 0.6, basis: "derived", q: 320, note: "1/2 to 1-1/4 in. copper or PEX-A" },
      "Hot-water recirculation return line with an aquastat-controlled bronze circulator and check valve": { price: [22, 45], labor: 0.6, basis: "est", note: "return piping; circulator adds $600-1,200" },
      "Fuel gas piping: Schedule 40 black steel threaded or CSST (bonded per the manufacturer) by size, with drip legs, unions and a shutoff at every appliance": { price: [25, 55], labor: 0.6, basis: "derived", note: "from Fixr black iron $15-30/ft residential, commercial sizes higher" },
      "Fixture rough-in: stub-outs, angle stops, water-hammer arrestors on quick-closing valves, and floor- or wall-mount carriers for wall-hung fixtures": { price: [350, 800], labor: 0.65, basis: "est", q: 14, note: "per fixture; wall-hung carriers at the high end" },
      "Cleanouts, floor drains with trap primers, floor sinks and roof drains with overflow domes set to the drawings": { price: [300, 900], labor: 0.5, basis: "est", q: 5 },
      "Water heating equipment: commercial tank or tankless heaters, thermostatic mixing valve (ASSE 1017), expansion tank and pressure-reducing valve set and piped": { price: [3500, 9500], labor: 0.3, basis: "est", q: 1, note: "light-commercial tank or tankless with mixing valve and expansion tank" },
      "Reduced-pressure backflow preventer at the service entrance with test cocks and an air-gap drain": { price: [2000, 4500], labor: 0.35, basis: "est", note: "1-2 in. RPZ assembly installed" },
      "Fixture set: water closets, urinals, lavatories, sinks, faucets and flush valves per the schedule, ADA-compliant where scheduled, sealed and adjusted": { price: [900, 2200], labor: 0.3, basis: "derived", q: 14, note: "commercial fixture with trim installed; from Homewyse toilet $635-1,151 and faucet $514-845" },
      "Pipe insulation: 1 in. fiberglass with ASJ jacket on hot, recirculation and roof-drain piping, 1/2 in. on cold in unconditioned space": { price: [6, 13], labor: 0.6, basis: "est", q: 150 },
      "Firestopping every pipe penetration through rated walls and floors with a UL-listed sleeve or collar system, labeled": { price: [60, 150], labor: 0.7, basis: "est", q: 15, note: "per penetration" },
      "Testing: DWV water or 5-psi air test, domestic water hydrostatic test at 100 psi for one hour, gas test at 1.5 times working pressure, all witnessed by the inspector": { price: [500, 1500], labor: 0.9, basis: "est", q: 1 },
      "Disinfection: potable system chlorinated and flushed per AWWA C651 with a bacteriological sample sent to the lab": { price: [400, 1200], labor: 0.6, basis: "est", q: 1, note: "includes the lab sample fee" },
      "Startup, valve tags and pipe labels, as-built drawings and the O&M binder turned over; construction debris hauled off": { price: [500, 1500], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "hvac": {
    op: 0.2,
    opNote: "commercial HVAC subcontractor (RTU/VRF, SMACNA, NEBB)",
    benchmark: {
      unit: "sqft",
      measures: "conditioned floor area served",
      price: [16, 34],
      typicalQty: [3000, 10000],
      jobQty: 6500,
      minJob: 5000,
      sources: ["Fixr 2025: galvanized sheet-metal ductwork $21.38-$62.36/linear ft installed", "Homewyse 2026: heat pump installed from $6,638-$7,837 per unit (residential reference)"],
    },
    steps: {
      "Design and submittals: block load per ASHRAE or Manual N, equipment selections, duct sizing, sequence of operations and stamped drawings submitted to the building department": { price: [2500, 7500], labor: 1, basis: "est", q: 1, note: "load calc, selections and stamped drawings; scales with building size" },
      "Mechanical permit, plan review and inspections scheduled, rebate and utility incentive paperwork filed": { price: [600, 2000], labor: 0, fee: true, basis: "est", q: 1, note: "mechanical permit and plan review; scales with valuation" },
      "Demolition: EPA 608 refrigerant recovery, existing units disconnected and removed, old duct and hangers taken down, all hauled and recycled": { price: [1200, 3500], labor: 0.85, basis: "est", note: "per unit removed with EPA 608 recovery" },
      "Crane or lift: rooftop units set with a certified rigger, lift plan, street or parking closure and flag crew for the pick day": { price: [2500, 6000], labor: 0.35, basis: "est", note: "crane day, rigger and closure" },
      "Roof curbs and curb adapters matched to the new unit footprint, set level and flashed into the roof by the roofing contractor": { price: [1200, 3000], labor: 0.4, basis: "est" },
      "Equipment: packaged rooftop units, split systems, heat pumps or VRF outdoor units by tonnage, SEER2 or IEER rating and gas heating input (MBH), set, leveled and anchored": { price: [9000, 22000], labor: 0.2, basis: "derived", q: 3, note: "5-10 ton gas/electric RTU or split set and anchored; 15-25 ton units $30,000-60,000" },
      "Air handlers, fan coils or indoor VRF units by CFM and cooling capacity, hung or set on isolation pads with service clearance": { price: [3000, 8000], labor: 0.35, basis: "est", q: 1 },
      "Supply and return ductwork: galvanized rectangular and spiral round by size, gauge per SMACNA, joints sealed to Seal Class A with mastic, hung on strap or trapeze": { price: [40, 90], labor: 0.6, basis: "derived", q: 900, note: "galvanized rectangular and spiral with fittings; Fixr residential $21-62/ft" },
      "Duct insulation: R-6 or R-8 foil-faced wrap on ducts outside the conditioned space, or 1 in. acoustic liner where specified": { price: [3, 6.5], labor: 0.55, basis: "est", q: 2000 },
      "Air terminals: diffusers, grilles, registers, VAV terminal units, balancing dampers and fire or smoke dampers at rated walls, set to the drawings": { price: [200, 550], labor: 0.45, basis: "est", q: 30, note: "mostly diffusers and grilles; VAV boxes $1,500-3,000 and fire dampers $400-900 each" },
      "Refrigerant piping: ACR copper by size, brazed under a nitrogen purge, insulated with closed-cell foam and UV-protected outdoors": { price: [30, 65], labor: 0.65, basis: "derived", q: 40, note: "repo rate card line set $14 labor + $9 material per ft (residential); commercial sizes higher" },
      "Condensate drains: Schedule 40 PVC with a trap sized to the unit's static pressure, secondary pan and float switch at each indoor unit": { price: [14, 30], labor: 0.65, basis: "est", q: 60 },
      "Gas piping and flue venting to gas-fired units: black steel or CSST with drip leg and shutoff, Category IV PVC or stainless vent terminated per the manufacturer": { price: [30, 65], labor: 0.6, basis: "est" },
      "Exhaust fans, make-up air and energy-recovery ventilators by CFM with roof or wall hoods and backdraft dampers": { price: [1200, 5500], labor: 0.4, basis: "est", note: "exhaust fans at the low end; ERVs and make-up air units $8,000-25,000" },
      "Controls: thermostats or DDC controllers, economizer and CO2 demand-ventilation sensors, control wiring and points tied to the building automation system": { price: [500, 1800], labor: 0.55, basis: "est", q: 3 },
      "Evacuation to 500 microns, refrigerant charge weighed in and verified by subcooling and superheat, startup and manufacturer start-up sheet on each system": { price: [450, 1100], labor: 0.9, basis: "derived", q: 4, note: "per system; repo rate card evacuate/weigh-in $350 + startup $300" },
      "Test, adjust and balance: every terminal balanced to design CFM, static pressure profile, with a NEBB or AABC report": { price: [2500, 7000], labor: 1, basis: "est", q: 1, note: "about $80-150 per terminal balanced" },
      "Commissioning: sequence of operations verified point by point, O&M manuals, warranty registration and owner training": { price: [2000, 6000], labor: 1, basis: "est", q: 1 },
      "Cleanup, protective wrap and packaging removed, construction filters replaced with new at turnover": { price: [400, 1200], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "fire-protection": {
    op: 0.18,
    opNote: "commercial fire sprinkler subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "sprinklered floor area",
      price: [3, 7],
      typicalQty: [5000, 20000],
      jobQty: 12500,
      minJob: 2500,
      sources: ["Bob Vila 2025 (citing Angi): sprinkler systems $0.80-$7/sqft, average $2/sqft", "Fixr 2025: sprinklers $1.30-$1.50/sqft new construction, $1.75-$2/sqft in an existing home"],
    },
    steps: {
      "Hydraulic design: hydrant flow test (static and residual), hazard classification per NFPA 13, density and design area, stamped drawings and hydraulic calculations submitted to the AHJ and the owner's insurer": { price: [2500, 6000], labor: 1, basis: "est", q: 1, note: "flow test, NFPA 13 design and calcs; scales with building size" },
      "Fire sprinkler permit, plan review, rough-in and final inspections with the fire marshal witnessing the tests": { price: [500, 2000], labor: 0, fee: true, basis: "est", q: 1, note: "fire marshal permit and inspections" },
      "Impairment plan and fire watch while the existing system is out of service, tags posted and the monitoring company notified": { price: [500, 2500], labor: 1, basis: "est", note: "fire watch billed by the shift" },
      "Underground fire service: C900 PVC or ductile iron by size from the tap to the riser room, thrust blocks, flushed per NFPA 24 before connection": { price: [90, 200], labor: 0.5, basis: "est", note: "4-6 in. C900 in trench with thrust blocks" },
      "Riser assembly: OS&Y or butterfly control valve with tamper switch, alarm check or riser check valve, waterflow switch, pressure gauges, main drain and inspector's test connection": { price: [4500, 9500], labor: 0.35, basis: "est", q: 1 },
      "Double-check or reduced-pressure detector assembly at the fire service as the water purveyor requires, with test cocks and drain": { price: [6000, 15000], labor: 0.3, basis: "est", note: "4-6 in. DCDA or RPDA installed" },
      "Fire department connection with check valve, ball drip and sign, piped to the riser": { price: [1800, 4000], labor: 0.4, basis: "est", q: 1 },
      "Fire pump and jockey pump with controllers, test header and flow meter, sized to the demand": { price: [60000, 150000], labor: 0.3, basis: "est", note: "electric fire pump, controller and jockey; diesel or larger runs higher" },
      "Feed and cross mains: Schedule 10 black steel with grooved couplings or Schedule 40 threaded, by size, hung per NFPA 13": { price: [30, 60], labor: 0.55, basis: "est", q: 350, note: "2-1/2 to 4 in. Schedule 10 grooved" },
      "Branch lines: 1 in. to 1-1/4 in. Schedule 40 threaded steel, or listed CPVC in light-hazard areas, with armovers and drops to each head": { price: [14, 28], labor: 0.6, basis: "derived", q: 1100, note: "1 to 1-1/4 in. threaded steel or CPVC; Bob Vila CPVC systems $1-2/sqft" },
      "Sprinkler heads: pendent, upright, sidewall or concealed by K-factor and temperature rating, with escutcheons or cover plates": { price: [75, 160], labor: 0.6, basis: "derived", q: 75, note: "head, escutcheon and install; Bob Vila heads $6.75-36 each material" },
      "Seismic sway bracing and flexible couplings at the riser and across seismic joints": { price: [250, 600], labor: 0.55, basis: "est" },
      "Dry-pipe or preaction valve with air compressor or nitrogen generator and low-point drains": { price: [15000, 35000], labor: 0.35, basis: "est" },
      "Standpipe hose valves and connections at each floor landing": { price: [900, 2200], labor: 0.45, basis: "est" },
      "Firestopping at every pipe penetration through rated walls and floors with a listed system": { price: [60, 150], labor: 0.7, basis: "est", q: 15, note: "per penetration" },
      "Hydrostatic test at 200 psi for two hours, system flush, main drain test, waterflow alarm test and the contractor's material and test certificate": { price: [1000, 3000], labor: 0.9, basis: "est", q: 1 },
      "Waterflow and tamper switches wired to the fire alarm panel or a dedicated communicator for monitoring": { price: [1200, 3500], labor: 0.6, basis: "est", q: 1 },
      "Hydraulic placard, valve signs, spare head cabinet with wrench, and as-built drawings turned over": { price: [500, 1400], labor: 0.5, basis: "est", q: 1 },
      "Cleanup, cutting oil wiped from the piping and scrap hauled off": { price: [300, 900], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "security-lowvoltage": {
    op: 0.25,
    opNote: "commercial low-voltage integrator, equipment-heavy",
    benchmark: {
      unit: "unit",
      measures: "cable drops plus security devices (each drop, camera, controlled door, sensor)",
      price: [450, 1300],
      typicalQty: [30, 70],
      jobQty: 50,
      minJob: 500,
      sources: ["Fixr 2025: Cat6 data drop $125-$250 installed", "Homewyse 2026: network wiring run $291-$349; home security system $805-$1,141"],
    },
    steps: {
      "Site survey and design: device locations, camera fields of view, door hardware schedule, riser diagram and IT coordination on switch ports, VLANs and IP addressing": { price: [800, 2500], labor: 1, basis: "est", q: 1, note: "scales with device count" },
      "Low-voltage permit and inspection where the jurisdiction requires one": { price: [100, 500], labor: 0, fee: true, basis: "est", note: "low-voltage permit where required" },
      "Pathways: J-hooks, bridle rings, conduit sleeves and core drills through walls and floors, surface raceway in finished spaces, firestopped where rated": { price: [6, 16], labor: 0.7, basis: "est", q: 400 },
      "Structured cabling: Category 6 or 6A plenum-rated cable per drop, terminated to keystone jacks and patch panels, labeled to the drawings": { price: [175, 325], labor: 0.65, basis: "src", q: 26, note: "Fixr $125-250 per Cat6 drop; Homewyse $291-349 per run; plenum Cat6A at the high end" },
      "Fiber backbone: OM4 multimode or OS2 single-mode by strand count, terminated LC and tested end to end": { price: [8, 20], labor: 0.6, basis: "est", note: "per ft including terminations spread over the run" },
      "Telecom rack or wall cabinet with patch panels, cable management, PDU, UPS and grounding busbar": { price: [1800, 4500], labor: 0.3, basis: "est", q: 1 },
      "Device cabling: 18/2, 22/4 and composite reader cable, siamese coax or Cat 6 for PoE, pulled from the head-end to each device": { price: [1.5, 3.5], labor: 0.7, basis: "est", q: 1500 },
      "Access control per door: controller, reader, electric strike or mag lock, request-to-exit sensor, door contact and power supply": { price: [2500, 5000], labor: 0.4, basis: "est", q: 4, note: "per controlled door, hardware included" },
      "Video surveillance: IP cameras by resolution and lens (dome, bullet, turret, PTZ), network video recorder with storage sized to the retention period, monitors": { price: [700, 1500], labor: 0.35, basis: "derived", q: 8, note: "per IP camera with its share of the NVR and storage" },
      "Intrusion detection: control panel, keypads, door and window contacts, motion and glass-break detectors, siren and cellular or IP communicator": { price: [150, 350], labor: 0.5, basis: "derived", q: 12, note: "per device with its share of the panel; Fixr home system $750-2,000" },
      "Intercom or video entry stations at the entrances tied to the access system": { price: [1500, 4000], labor: 0.35, basis: "est" },
      "PoE network switches sized to the device count and power budget, configured on the security VLAN": { price: [900, 2800], labor: 0.2, basis: "est", q: 1 },
      "Head-end build-out: enclosures, power supplies, battery backup and grounding at the equipment room": { price: [1200, 3500], labor: 0.4, basis: "est", q: 1 },
      "Programming: credentials and schedules, camera views and recording rules, alarm partitions, notifications and the mobile app": { price: [1000, 3500], labor: 1, basis: "est", q: 1, note: "scales with device count" },
      "Testing and certification: every drop certified to TIA-568 with a printed test report, camera focus and walk test of every device": { price: [600, 2000], labor: 1, basis: "est", q: 1, note: "about $20-40 per drop certified" },
      "Monitoring account activation with the central station and signal test": { price: [100, 300], labor: 0.8, basis: "est", note: "activation only; monthly monitoring quoted separately" },
      "Owner training, as-built drawings and device schedule; packaging and cable scrap hauled off": { price: [400, 1200], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "residential-electrical": {
    op: 0.3,
    opNote: "residential electrical specialty trade",
    benchmark: {
      unit: "unit",
      measures: "devices, fixtures and alarms installed (points)",
      price: [175, 400],
      typicalQty: [10, 36],
      jobQty: 23,
      minJob: 250,
      sources: ["Fixr 2025: outlet installed $120-$200; recessed light $176-$328 per light", "Homewyse 2026: new outlet $297-$360; appliance circuit $741-$910"],
    },
    steps: {
      "Electrical permit with rough-in and final inspections scheduled with the building department": { price: [100, 350], labor: 0, fee: true, basis: "est", q: 1, note: "city electrical permit" },
      "Utility coordination: meter pull and reconnect scheduled with the power company": { price: [150, 400], labor: 1, basis: "est", note: "coordination only; utility reconnect charges passed through" },
      "Floors, furniture and finishes protected, power shut off and locked out for the work areas": { price: [75, 200], labor: 0.85, basis: "est", q: 1 },
      "Old fixtures, devices and abandoned wiring removed, dead wires terminated in accessible junction boxes, materials hauled away": { price: [25, 60], labor: 0.9, basis: "est", note: "per device or fixture removed" },
      "Service upgrade: 200 A meter-main or meter base, service-entrance conductors, two 8-ft ground rods, #4 copper grounding electrode conductor, water and gas bonding": { price: [1600, 3200], labor: 0.55, basis: "derived", note: "meter base, SE cable, grounding; with the panel line ~$3,400-6,800 (Fixr 200 A $1,800-4,500; repo audit $3,200-6,500)" },
      "Panel replacement: 200 A 40-space main breaker panel, existing circuits landed on new breakers with AFCI and GFCI protection where the code requires, directory typed": { price: [1800, 3600], labor: 0.6, basis: "derived", note: "200 A 40-space panel with AFCI/GFCI breakers" },
      "Subpanel: 100 A or 125 A panel fed with 2-2-2-4 aluminum SER or copper feeder, separate ground and neutral bars, for the garage, addition or shop": { price: [1200, 2600], labor: 0.55, basis: "est" },
      "New branch-circuit homerun: 14-2 or 12-2 NM-B (Romex) from the panel to the first box on a 15 A or 20 A breaker, stapled and protected": { price: [4, 9], labor: 0.7, basis: "derived", q: 120, note: "NM-B in open framing ~0.05 h/ft plus $0.8-1.5/ft cable" },
      "Wire fished through finished walls and ceilings, with access holes cut and blocks drilled": { price: [120, 300], labor: 0.95, basis: "est", note: "per run fished through finished walls" },
      "Receptacles and switches: tamper-resistant 15 A or 20 A, GFCI in kitchen, bath, garage and outdoor locations, dimmers and 3-way switches, boxes and plates": { price: [110, 220], labor: 0.75, basis: "src", q: 12, note: "Fixr 2025: outlet installed $120-200 (avg $141)" },
      "Light fixtures: 4 in. or 6 in. LED recessed wafers, surface fixtures, ceiling fans on fan-rated braced boxes, exterior fixtures": { price: [150, 330], labor: 0.6, basis: "src", q: 8, note: "Fixr 2025: recessed light $176-328 per light; owner-supplied fixture at labor only" },
      "Interconnected smoke and carbon monoxide alarms in bedrooms, hallways and on each floor": { price: [110, 200], labor: 0.6, basis: "derived", q: 3, note: "Fixr 2025: hardwired detector $70-150 (avg $112); interconnected smoke/CO combo higher" },
      "Dedicated appliance circuit: range, dryer, EV charger or hot tub on 30 A to 60 A, 10-3 or 6-3 NM-B, with the NEMA receptacle or hardwired connection": { price: [550, 1400], labor: 0.6, basis: "src", note: "Homewyse 2026: appliance circuit $741-910; EV and hot-tub runs at the high end" },
      "Exterior weather-resistant GFCI receptacles with in-use covers": { price: [180, 350], labor: 0.65, basis: "est" },
      "Code corrections: ungrounded outlets replaced with GFCI-protected devices, open splices boxed, double-tapped breakers corrected, missing bonding added": { price: [100, 250], labor: 0.8, basis: "est", note: "per correction" },
      "Drywall patch of access holes, taped and textured ready for paint": { price: [8, 18], labor: 0.85, basis: "est", note: "small patches carry a $250-450 minimum" },
      "Circuit testing: every outlet checked for polarity and ground, GFCI and AFCI trip test, breaker torque, panel directory filled in": { price: [100, 250], labor: 1, basis: "est", q: 1 },
      "Cleanup and haul-away of old panels, fixtures and packaging; final walk-through with the homeowner": { price: [75, 200], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "surge-protection": {
    op: 0.35,
    opNote: "small residential electrical service call",
    benchmark: {
      unit: "unit",
      measures: "surge protective devices installed",
      price: [300, 800],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 250,
      sources: ["Bob Vila 2025 (citing Angi/HomeAdvisor): whole-house surge protector $70-$700 installed, average $300", "Fixr 2025: electrician service visit $176-$327"],
    },
    steps: {
      "Site assessment: service size and type, panel make and available spaces, condition of the grounding electrode system, sensitive equipment inventory": { price: [50, 150], labor: 1, basis: "est", q: 1, note: "trip and assessment; often credited when the job is booked" },
      "Electrical permit and inspection where the jurisdiction requires one for panel work": { price: [75, 200], labor: 0, fee: true, basis: "est", note: "city electrical permit" },
      "Grounding correction: missing or loose ground rod, water-pipe bond or grounding electrode conductor added or reterminated so the SPD has a low-impedance path": { price: [200, 550], labor: 0.6, basis: "est" },
      "Type 1 surge protective device at the meter socket or service entrance, utility-approved meter-collar or enclosure model": { price: [350, 700], labor: 0.25, basis: "est", note: "utility-approved meter-collar SPD; the utility may charge for the meter pull" },
      "Type 2 whole-home surge protective device at the main panel, UL 1449 listed, 80 kA to 100 kA per phase, on a dedicated 2-pole breaker with leads kept under 18 in.": { price: [180, 380], labor: 0.1, basis: "derived", q: 1, note: "device ($100-250 list) and 2-pole breaker supplied; install labor is the panel-work line" },
      "Type 2 surge protective device at each subpanel (garage, shop, ADU) fed from the main": { price: [250, 500], labor: 0.45, basis: "est", note: "device plus its own install at the subpanel" },
      "Type 3 point-of-use surge protection: receptacle-style or plug-in units at the AV system, computers and network gear": { price: [40, 120], labor: 0.3, basis: "est" },
      "HVAC condenser surge protector wired at the outdoor disconnect": { price: [150, 300], labor: 0.5, basis: "derived", note: "repo HVAC rate card surge protector $130 cost + install" },
      "Coax, telephone and Ethernet line protectors at the service entrance, bonded to the grounding system": { price: [60, 150], labor: 0.6, basis: "est" },
      "Panel work: dead front removed, device mounted and wired, breaker labeled, panel closed and directory updated": { price: [125, 275], labor: 0.9, basis: "derived", q: 1, note: "1-2 h at Fixr $88-163/h" },
      "Verification: status indicators checked, breaker torque, ground resistance reading logged, homeowner shown what the indicator lights mean": { price: [30, 80], labor: 1, basis: "est", q: 1 },
      "Warranty registration for the device and the connected-equipment coverage, documentation left with the homeowner": { price: [10, 40], labor: 1, basis: "est", q: 1 },
    },
  },
  "residential-plumbing": {
    op: 0.35,
    opNote: "residential service plumbing, small jobs",
    benchmark: {
      unit: "unit",
      measures: "fixtures or repair points served",
      price: [300, 700],
      typicalQty: [2, 4],
      jobQty: 3,
      minJob: 250,
      sources: ["Homewyse 2026: plumbing leak repair $340-$411 per leak; faucet installed $514-$845", "Fixr 2025: plumber $75-$150/hour, average $90"],
    },
    steps: {
      "Diagnosis: static pressure reading at the hose bib, fixture-by-fixture check for leaks, slow drains and failed valves, findings explained before work starts": { price: [125, 200], labor: 1, basis: "derived", q: 1, note: "service rate; Fixr $75-150/h, repo remodel method $110-180/h before markup" },
      "Plumbing permit and inspection for fixture relocations, water heater or repipe work": { price: [75, 250], labor: 0, fee: true, basis: "est", note: "city plumbing permit" },
      "Floors and cabinets protected, water shut off at the main and the lines drained down": { price: [60, 150], labor: 1, basis: "est", q: 1 },
      "Old fixtures, faucets, valves and failed pipe sections removed and hauled away": { price: [40, 110], labor: 0.85, basis: "est", note: "per fixture or section removed" },
      "Water line repair or replacement: PEX-A with expansion fittings or Type L copper by size, spliced to the existing with push-fit or sweat transitions": { price: [18, 40], labor: 0.7, basis: "est", q: 12, note: "short repair runs; long runs are repiping" },
      "Drain line repair or replacement: Schedule 40 ABS or PVC by size with shielded couplings to the existing, sloped 1/4 in. per ft": { price: [25, 55], labor: 0.65, basis: "est", q: 6 },
      "Quarter-turn angle stops and braided stainless supply lines at each fixture served": { price: [85, 160], labor: 0.6, basis: "est", q: 3, note: "per fixture: two stops and supplies" },
      "Toilet set: new wax ring or waxless seal, closet bolts, supply and shutoff, caulked at the floor": { price: [200, 420], labor: 0.8, basis: "src", note: "Fixr 2025: toilet install labor $150-440; the toilet itself is an allowance" },
      "Faucet, sink, garbage disposal or dishwasher connection: mounted, plumbed with a P-trap and air gap, tested": { price: [200, 450], labor: 0.75, basis: "src", note: "Fixr 2025: kitchen faucet install $150-400; fixture is an allowance" },
      "Tub and shower valve: pressure-balance or thermostatic valve set behind the wall with trim, spout and shower head": { price: [700, 1500], labor: 0.65, basis: "derived", note: "valve and trim from behind the wall; opening and patch are the access line" },
      "Frost-free hose bib with vacuum breaker, through-wall and sealed": { price: [200, 420], labor: 0.7, basis: "est" },
      "Pressure-reducing valve set to 60 psi and a thermal expansion tank at the water heater": { price: [550, 1100], labor: 0.55, basis: "est" },
      "Stoppage cleared by cable machine through the cleanout or trap arm with the right cutter for the line size": { price: [175, 375], labor: 0.9, basis: "est", note: "main-line cabling from a cleanout runs $250-500" },
      "Access openings cut in drywall or tile for concealed pipe, then patched, taped and textured ready for paint": { price: [18, 45], labor: 0.85, basis: "derived", note: "repo remodel method: drywall patch $250-450 first opening; tile openings by others" },
      "Pressure test of the repaired lines at house pressure, every joint checked dry, inspector sign-off where permitted": { price: [60, 150], labor: 1, basis: "est", q: 1 },
      "Cleanup, old parts hauled off, aerators flushed, warranty on the labor and installed parts explained to the homeowner": { price: [40, 110], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "gas-line": {
    op: 0.3,
    opNote: "residential plumbing/gas specialty trade",
    benchmark: {
      unit: "linear ft",
      measures: "gas pipe run length",
      price: [28, 60],
      typicalQty: [20, 60],
      jobQty: 40,
      minJob: 350,
      sources: ["Fixr 2025: gas line $500-$2,000, average $800 for a 25 ft line to a furnace; black iron $15-$30/linear ft installed", "Homewyse 2026: gas line from $864-$1,060 per piping run"],
    },
    steps: {
      "Load calculation and sizing: total BTU/hr demand of every appliance, pipe sized by the longest-run method per NFPA 54 / IFGC tables, sizing schematic prepared": { price: [40, 120], labor: 1, basis: "est", q: 1 },
      "Gas permit, pressure-test inspection and final inspection scheduled with the building department": { price: [60, 200], labor: 0, fee: true, basis: "est", q: 1, note: "city gas or plumbing permit" },
      "Utility coordination: meter upsizing or elevated-pressure service requested from the gas company": { price: [100, 300], labor: 1, basis: "est", note: "coordination only; the utility's meter or service charge is passed through" },
      "811 utility locate and trench for the exterior yard line at 18 in. minimum cover, spoils stockpiled": { price: [6, 14], labor: 0.6, basis: "est", note: "811 locate is free; trencher at 18 in. cover" },
      "Underground gas line: yellow polyethylene (MDPE) with heat-fused or mechanical fittings, tracer wire, warning tape and anodeless risers at each end": { price: [12, 25], labor: 0.55, basis: "src", note: "Fixr 2025: polyethylene $11-20/ft installed; risers included" },
      "Interior gas piping: Schedule 40 black steel, threaded with pipe dope rated for gas, sized per the schematic, supported every 6 to 10 ft": { price: [14, 28], labor: 0.65, basis: "src", q: 40, note: "Fixr 2025: black iron $15-30/ft, new line $10-25/ft installed" },
      "CSST runs with arc-resistant jacket, listed fittings and bonding to the electrical grounding system with #6 copper": { price: [12, 24], labor: 0.6, basis: "src", note: "Fixr 2025: CSST $11-21/ft installed; bonding included" },
      "Shutoff valve, drip leg (sediment trap) and union at each appliance, plus the system shutoff at the entry": { price: [60, 140], labor: 0.55, basis: "derived", q: 2, note: "Fixr 2025: shutoffs for 3-4 appliances $210-500" },
      "Appliance connection with a listed flexible connector and startup of the range, dryer, furnace, water heater, fireplace or grill": { price: [100, 225], labor: 0.75, basis: "derived", q: 1, note: "Fixr 2025: hook-up of 3-4 appliances $220-350, plus startup" },
      "Line regulator at each appliance and the 2-psi entry regulator for a pounds-to-inches system": { price: [150, 350], labor: 0.5, basis: "est" },
      "Propane: tank set and first- and second-stage regulators with the propane supplier's tie-in": { price: [600, 2000], labor: 0.4, basis: "est", note: "set and tie-in; a leased tank is billed by the propane supplier" },
      "Wall and foundation penetrations sleeved, sealed and protected with nail plates where the pipe passes through framing": { price: [25, 70], labor: 0.8, basis: "est", q: 3 },
      "Pressure test at 1.5 times working pressure and not less than 3 psi for 10 minutes, or as the jurisdiction requires, on a gauge witnessed by the inspector": { price: [60, 175], labor: 0.9, basis: "est", q: 1 },
      "Purge of the new line, every joint leak-checked with solution or electronic detector under gas, appliances lit and adjusted": { price: [50, 150], labor: 1, basis: "est", q: 1 },
      "Trench backfilled in compacted lifts and the lawn or surface restored": { price: [35, 80], labor: 0.7, basis: "est", note: "backfill and seed or sod patch" },
      "Pipe labeled at the shutoffs and an as-built sketch of the routing left with the owner": { price: [15, 45], labor: 1, basis: "est", q: 1 },
    },
  },
  "water-heater-replacement": {
    op: 0.3,
    opNote: "residential plumbing specialty trade",
    benchmark: {
      unit: "unit",
      measures: "water heaters replaced",
      price: [1700, 3500],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 1200,
      sources: ["Fixr 2025: 50-gallon water heater installed $900-$2,500, average $1,800", "Homewyse 2026: water heater replacement from $1,586-$1,843 per heater", "Bob Vila 2025 (citing Angi): permit $25-$300; removal $100-$500; labor $150-$450"],
    },
    steps: {
      "Plumbing and mechanical permit with the final inspection scheduled": { price: [50, 250], labor: 0, fee: true, basis: "src", q: 1, note: "Bob Vila 2025: $25-300" },
      "Old heater shut off, drained, disconnected from gas or power, water and vent, removed and hauled for recycling": { price: [125, 275], labor: 0.8, basis: "derived", q: 1, note: "repo rate card remove $150; Fixr disposal $50-150" },
      "New storage water heater by capacity and fuel (40-, 50- or 75-gallon gas atmospheric, power-vent or electric) with its UEF rating and warranty term, set level on a stand where the code requires": { price: [1200, 2200], labor: 0.22, basis: "derived", q: 1, note: "repo rate card $26/gal gas ($18 electric) cost + 35% + set labor; 75-gal and power-vent at or above the high end" },
      "Water connections: new 3/4 in. ball-valve shutoff, dielectric nipples, braided stainless or copper flex connectors": { price: [100, 220], labor: 0.55, basis: "derived", q: 1, note: "repo rate card flex lines, dielectrics, shutoff $45 + labor" },
      "Gas connection: new flexible connector, sediment trap and shutoff, leak-checked under pressure": { price: [120, 260], labor: 0.7, basis: "derived", note: "repo rate card gas connect $150 + flex kit $55" },
      "Electrical connection: new 10-2 whip and disconnect on the existing 30 A circuit, verified": { price: [120, 280], labor: 0.7, basis: "derived", note: "repo rate card electrical connect $225" },
      "Venting: draft hood and B-vent by diameter to the existing chimney or flue, or Schedule 40 PVC intake and exhaust for a power-vent model, terminated per the manufacturer": { price: [20, 45], labor: 0.55, basis: "derived", note: "repo rate card venting $12/ft + B-vent kit; PVC for power vent" },
      "Thermal expansion tank sized to the heater, teed into the cold side and pre-charged to house pressure": { price: [140, 280], labor: 0.4, basis: "src", q: 1, note: "Fixr 2025: expansion tank adds $150-400" },
      "Drain pan under the heater with a 3/4 in. drain piped to the exterior or a floor drain": { price: [90, 220], labor: 0.5, basis: "derived", note: "repo rate card pan $40 + drain piping" },
      "Seismic strapping: two 22-gauge straps at the upper and lower third, lagged into studs": { price: [60, 150], labor: 0.6, basis: "derived", note: "repo rate card straps $30" },
      "Temperature and pressure relief valve discharge line in 3/4 in. copper or CPVC to an approved termination with an air gap": { price: [50, 140], labor: 0.55, basis: "derived", q: 1, note: "repo rate card T&P kit $30" },
      "Condensate neutralizer and drain for a condensing power-vent heater": { price: [150, 300], labor: 0.5, basis: "derived", note: "repo rate card neutralizer $60" },
      "Pipe insulation on the first 6 ft of hot and cold lines at the heater": { price: [4, 9], labor: 0.5, basis: "est", q: 6 },
      "Startup: tank filled and purged of air, burner lit or elements energized, thermostat set to 120 F, draft and combustion checked, every joint tested": { price: [60, 175], labor: 1, basis: "est", q: 1 },
      "Haul-away and cleanup, manufacturer warranty registered, operation and maintenance explained to the homeowner": { price: [50, 150], labor: 0.6, basis: "derived", q: 1, note: "repo rate card disposal $150; Fixr $50-150" },
    },
  },
  "tankless-water-heater": {
    op: 0.3,
    opNote: "residential plumbing specialty trade",
    benchmark: {
      unit: "unit",
      measures: "tankless heaters installed",
      price: [3500, 6500],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 2500,
      sources: ["Fixr 2025: gas tankless installed $2,500-$4,500, average $2,811; 6-10 h labor at $75-$130/hour", "Homewyse 2026: tankless gas water heater from $3,293-$3,859 per heater"],
    },
    steps: {
      "Sizing survey: peak flow in GPM at the required temperature rise, gas meter and line capacity, electrical service, vent route and condensate path confirmed": { price: [75, 200], labor: 1, basis: "est", q: 1 },
      "Plumbing, mechanical and gas permits with the final inspection scheduled": { price: [150, 450], labor: 0, fee: true, basis: "est", q: 1, note: "plumbing, mechanical and gas permits" },
      "Existing tank heater drained, disconnected, removed and hauled for recycling": { price: [150, 300], labor: 0.8, basis: "derived", note: "repo rate card remove $150 + disposal" },
      "Condensing tankless heater by input and flow (for example 199,000 BTU, 9 to 11 GPM, UEF 0.93 or better) mounted on its bracket with service clearance": { price: [2100, 3400], labor: 0.25, basis: "derived", q: 1, note: "Fixr 2025 units: Navien $1,075-1,535, Rinnai $900-1,995; repo rate card $1,400 cost + 35% + set labor" },
      "Gas line upsized to 3/4 in. or 1 in. black steel or CSST from the meter to the unit with sediment trap and shutoff, sized for the full input": { price: [18, 35], labor: 0.6, basis: "derived", note: "repo rate card gas pipe $18/ft labor; Fixr black iron $15-30/ft" },
      "Gas meter upgrade requested from the utility to carry the added input": { price: [100, 500], labor: 0, fee: true, basis: "est", note: "utility charge passed through; many utilities upsize the meter free" },
      "Venting: 2 in. or 3 in. PVC or polypropylene, twin-pipe or concentric, with the termination kit through the wall or roof": { price: [22, 48], labor: 0.6, basis: "derived", q: 10, note: "repo rate card venting $12/ft + vent kit $120" },
      "Condensate neutralizer cartridge and 1/2 in. drain line to an approved termination": { price: [140, 280], labor: 0.4, basis: "derived", q: 1, note: "repo rate card neutralizer $60" },
      "Isolation service-valve kit with purge ports, 3/4 in. water connections and a pressure relief valve piped to an approved point": { price: [180, 360], labor: 0.4, basis: "derived", q: 1, note: "repo rate card isolation kit $85" },
      "Electrical: 120 V receptacle or hardwired circuit for the controls and fan, or dedicated 240 V circuits for an electric tankless unit": { price: [175, 450], labor: 0.7, basis: "derived", note: "120 V receptacle (repo $225 connect); electric tankless circuits run $1,200-2,500" },
      "Recirculation kit or dedicated return line with the unit's onboard pump for faster hot water at distant fixtures": { price: [350, 900], labor: 0.5, basis: "est" },
      "Scale prevention: sediment pre-filter and a template-assisted crystallization (TAC) or softener treatment ahead of the unit": { price: [400, 1200], labor: 0.3, basis: "est" },
      "Wall or roof penetrations for the vent and condensate, flashed and weather-sealed": { price: [100, 250], labor: 0.75, basis: "est", q: 2 },
      "Startup: lines purged, temperature set to 120 F, dip switches set for altitude and gas type, combustion analysis and flow verified at the farthest fixture": { price: [125, 300], labor: 1, basis: "est", q: 1 },
      "Annual descaling procedure shown to the homeowner, warranty registered, packaging and old unit hauled off": { price: [75, 200], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "whole-house-repiping": {
    op: 0.3,
    opNote: "residential repipe specialty trade",
    benchmark: {
      unit: "unit",
      measures: "plumbing fixtures served (stub-outs)",
      price: [750, 1500],
      typicalQty: [8, 16],
      jobQty: 12,
      minJob: 3500,
      sources: ["Homewyse 2026: repipe water supply lines from $3,438-$4,113 per job (basic, walls not repaired)", "Fixr 2025: plumber $75-$150/hour"],
    },
    steps: {
      "Walk-through and layout: fixture count, existing pipe material, routing through attic, crawlspace and walls, manifold and shutoff locations marked": { price: [100, 300], labor: 1, basis: "est", q: 1 },
      "Plumbing permit with rough-in pressure test and final inspections scheduled": { price: [150, 500], labor: 0, fee: true, basis: "est", q: 1, note: "city plumbing permit" },
      "Floor protection, plastic dust barriers on doorways and furniture covered in every room where walls are opened": { price: [200, 500], labor: 0.8, basis: "est", q: 1 },
      "Access openings cut in drywall or plaster at fixtures, chases and ceilings, sized for the work and marked for patching": { price: [35, 90], labor: 1, basis: "est", q: 16, note: "per opening cut; the patch is its own line" },
      "Old galvanized, polybutylene or failed copper drained, cut and abandoned in place; exposed sections in the crawlspace, basement or attic removed and hauled": { price: [1.5, 4], labor: 0.9, basis: "est", q: 100, note: "per ft of exposed pipe removed" },
      "New water main from the meter or entry to the house: 1 in. PEX-A or Type L copper, with a new full-port main shutoff and pressure-reducing valve": { price: [25, 55], labor: 0.55, basis: "derived", q: 30, note: "1 in. line with the new main shutoff and PRV spread over the run" },
      "Trunk lines: 3/4 in. PEX-A with expansion fittings or Type L copper, run through the attic or crawlspace and supported per code": { price: [9, 18], labor: 0.7, basis: "derived", q: 120, note: "retrofit PEX-A ~0.06-0.1 labor h/ft + $2-3/ft pipe and fittings" },
      "Branch lines: 1/2 in. PEX-A or Type L copper from the trunk or manifold to each fixture, sleeved through framing with nail plates": { price: [8, 16], labor: 0.72, basis: "derived", q: 200, note: "retrofit PEX-A ~0.06-0.1 labor h/ft + $2-3/ft pipe and fittings" },
      "PEX manifold with individual quarter-turn shutoffs for each fixture, mounted in an accessible location": { price: [500, 1200], labor: 0.4, basis: "est" },
      "Fixture stub-outs: drop-ear elbows or copper stub-outs, new quarter-turn angle stops and braided supply lines at each fixture": { price: [100, 220], labor: 0.6, basis: "derived", q: 12, note: "per fixture: stub-out, two stops, supplies" },
      "Frost-free hose bibs with vacuum breakers replaced and connected to the new system": { price: [150, 320], labor: 0.6, basis: "est", q: 2 },
      "Water heater reconnected with new flex connectors, dielectric unions and a thermal expansion tank": { price: [200, 450], labor: 0.6, basis: "derived", q: 1, note: "repo rate card flex lines $45 + expansion tank $60 + labor" },
      "Hot-water recirculation return line and pump for fast hot water": { price: [15, 35], labor: 0.6, basis: "est", note: "pump adds $400-900" },
      "Pipe insulation on lines in the attic, crawlspace or garage and fire blocking restored at every penetration": { price: [3, 7], labor: 0.6, basis: "est", q: 100 },
      "Rough-in pressure test at 100 psi held for the inspector, every joint checked": { price: [100, 250], labor: 1, basis: "est", q: 1 },
      "Drywall patch: openings closed, taped, mudded and textured to match, ready for paint": { price: [10, 22], labor: 0.85, basis: "est", q: 48, note: "texture match; paint by the homeowner" },
      "System flushed, aerators cleaned, every fixture run and checked for leaks and pressure": { price: [100, 250], labor: 1, basis: "est", q: 1 },
      "Final cleanup, old pipe and debris hauled off, warranty documents delivered": { price: [150, 400], labor: 0.7, basis: "est", q: 1 },
    },
  },
};
