// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "roadway-highway": {
    op: 0.15,
    opNote: "public-works civil and paving bid",
    benchmark: {
      unit: "sq yards",
      measures: "roadway pavement area, lanes plus shoulders",
      price: [85, 170],
      typicalQty: [25000, 60000],
      jobQty: 42500,
      minJob: 500000,
      sources: ["Under the Hard Hat 2025: two-lane rural road $2-3M/mile, four-lane rural highway $4-6M/mile", "AsphaPro 2026: highway $80-$200/sq yd all-in", "WisDOT avg unit prices FY2023-25: HMA $68-$100/ton, base aggregate $12-$24/ton, common excavation $8.65-$14.47/CY"],
    },
    steps: {
      "Pre-construction: survey control and construction staking from the DOT plans, utility coordination meeting, NPDES permit and SWPPP posted, and submittals approved (mix designs, aggregate sources, QC plan)": { price: [35000, 110000], labor: 0.85, basis: "derived", q: 1, note: "scales with job: about 1-2% of contract (survey, staking, submittals)" },
      "Maintenance of traffic through the project: DOT-standard temporary traffic control plan with advance signs, drums, arrow boards, changeable message signs, temporary barrier and the lane-closure phasing": { price: [80000, 300000], labor: 0.5, basis: "derived", q: 1, note: "scales with job: 2-6% of contract; WisDOT lump-sum traffic control averages $32k per project across all sizes" },
      "Clearing and grubbing inside the construction limits: trees, stumps and brush removed, debris chipped or hauled off": { price: [0.1, 0.35], labor: 0.35, basis: "derived", q: 600000, note: "WisDOT clearing $3,500-$6,800/acre plus grubbing $1,200-$3,400/acre" },
      "Erosion and sediment control per the SWPPP: silt fence, inlet protection, stabilized entrances and slope seeding, maintained weekly and after rain": { price: [3, 7], labor: 0.5, basis: "derived", q: 21000, note: "per LF of silt fence line; WisDOT silt fence $2/LF, inlet protection $60-$120 ea, tracking pad $350-$700 ea, maintenance included" },
      "Removal of the existing pavement, curb and drainage structures: saw-cut, broken out, loaded and hauled to a recycler": { price: [4, 10], labor: 0.4, basis: "src", note: "WisDOT removing asphalt $3.31-$4.94/SY, concrete $3.90-$6.42/SY; curb and structures included" },
      "Roadway excavation and embankment: cut to grade, fill placed in 8 in. lifts and compacted to 95% standard Proctor, borrow imported where the cut is short": { price: [9, 20], labor: 0.3, basis: "src", q: 60000, note: "WisDOT common excavation $8.65-$14.47/CY, borrow $7-$9/CY; TxDOT roadway excavation $13/CY" },
      "Storm drainage pipe: reinforced concrete (Class III) or HDPE at the stated diameter laid on stone bedding to grade, trench backfilled in compacted lifts": { price: [85, 170], labor: 0.35, basis: "src", q: 2000, note: "18-24 in. RCP: WisDOT $83-$147/LF, TxDOT $82-$118/LF" },
      "Drainage structures: precast catch basins, manholes, curb inlets and headwalls set on stone, frames and grates raised to finished grade": { price: [2500, 5500], labor: 0.4, basis: "src", q: 30, note: "WisDOT inlets $2.0-$3.1k, catch basins $2.5-$2.8k, 4 ft manholes $3.4-$4.2k" },
      "Utility crossings and relocations: steel or PVC casings bored or trenched under the roadway for water, sewer and conduit": { price: [120, 350], labor: 0.45, basis: "est", note: "bored steel casing 12-24 in.; open-cut PVC sleeves at the low end" },
      "Subgrade preparation: scarify, moisture-condition and compact the top 12 in. to 95%, proof-roll with a loaded tandem, undercut soft areas and rebuild with geotextile and stone": { price: [1.5, 4.5], labor: 0.35, basis: "derived", q: 45000 },
      "Aggregate base course: DOT-spec dense-graded crushed stone spread and compacted in lifts to the stated depth (typically 8-12 in.), tonnage named": { price: [40, 75], labor: 0.25, basis: "derived", q: 11800, note: "WisDOT dense base $12-$24/ton at about 2 tons/CY; other states $25-$40/ton" },
      "Prime coat: MC-30 or emulsified asphalt prime on the finished base before the first lift": { price: [0.8, 1.8], labor: 0.25, basis: "derived", q: 28300, note: "about 0.25 gal/SY at $3-$5/gal applied" },
      "Hot-mix asphalt binder course at the stated compacted depth (typically 3-4 in.): Superpave mix named, paver-laid with tonnage named, tack coat between lifts": { price: [16, 26], labor: 0.2, basis: "derived", q: 28300, note: "3.5 in. at 0.19 ton/SY x $80-$120/ton (WisDOT $68-$100, TxDOT $91), tack included" },
      "Hot-mix asphalt surface course at the stated compacted depth (typically 1.5-2 in.): mix and tonnage named, rolled to the specified density with longitudinal joints staggered": { price: [9, 14], labor: 0.2, basis: "derived", q: 28300, note: "1.75 in. at 0.096 ton/SY x $90-$130/ton" },
      "Portland cement concrete pavement: slipformed at the stated thickness with dowel baskets, tie bars, sawed joints sealed and a sprayed curing compound": { price: [60, 110], labor: 0.3, basis: "src", note: "WisDOT 8-10 in. concrete pavement $50-$84/SY; 11-12 in. $75-$150/SY" },
      "Concrete curb and gutter or barrier curb at the DOT standard profile, slipformed with expansion joints and the driveway aprons": { price: [26, 45], labor: 0.45, basis: "src", q: 2000, note: "WisDOT 30 in. curb and gutter $24-$47/LF; TxDOT $36/LF" },
      "Shoulders: aggregate or paved shoulders graded and compacted at the stated width and slope": { price: [8, 22], labor: 0.25, basis: "derived", q: 14200, note: "aggregate shoulder at the low end, 3 in. paved shoulder on base at the high end" },
      "Guardrail with MASH terminals and delineators at the plan locations": { price: [35, 65], labor: 0.35, basis: "derived", note: "WisDOT MGS rail $27-$31/LF plus terminals $3.7-$4.0k each spread over the run" },
      "Permanent pavement markings: thermoplastic or epoxy lines, symbols and raised markers at the plan spacing": { price: [0.6, 1.8], labor: 0.4, basis: "derived", q: 31700, note: "WisDOT 4 in. epoxy $0.50-$0.79/LF, paint $0.21-$0.49/LF; symbols and raised markers blended in" },
      "Signs and posts, plus signal and lighting foundations and conduit": { price: [500, 3000], labor: 0.4, basis: "est", note: "sign assembly at the low end, signal or light-pole foundation with conduit at the high end" },
      "Quality control testing at the DOT frequency: nuclear density and cores on base and asphalt, gradation and asphalt content, concrete cylinders and air": { price: [25000, 75000], labor: 0.8, basis: "est", q: 1, note: "scales with job: about 0.5-1.5% of contract" },
      "Final: topsoil, seed and mulch on the slopes, cleanup, punch-list walk with the inspector and the as-built drawings": { price: [60000, 200000], labor: 0.45, basis: "derived", q: 1, note: "scales with slope area: WisDOT topsoil $1.78-$4.37/SY, mulching $0.30/SY, plus seed" },
    },
  },
  "road-construction": {
    op: 0.15,
    opNote: "public-works and developer civil bids",
    benchmark: {
      unit: "linear ft",
      measures: "road centerline length, 28 ft street with curb both sides",
      price: [250, 600],
      typicalQty: [800, 2200],
      jobQty: 1500,
      minJob: 100000,
      sources: ["AsphaPro 2026: residential street $30-$60/sq yd, collector $40-$80/sq yd; rural 2-lane $1-3M/mile", "Under the Hard Hat 2025: two-lane rural road $2-3M/mile, two-lane urban road $3-5M/mile", "TxDOT 3-yr avg bids (Caliche 2026): curb and gutter $36/LF, dense-graded HMA $91/ton, roadway excavation $13/CY"],
    },
    steps: {
      "Construction staking: centerline, offsets, curb lines and grade stakes set from the civil plans, right-of-way and easements flagged": { price: [6000, 18000], labor: 0.9, basis: "derived", q: 1, note: "scales with length: about $4-$12 per LF of road" },
      "Permits and agency: grading and right-of-way permits, pre-construction meeting with the city or county inspector, haul route and work hours approved": { price: [2000, 10000], labor: 0, fee: true, basis: "est", q: 1, note: "grading and ROW permit plus the agency plan-review and inspection fees" },
      "Traffic control and detour at the tie-in: signs, barricades and flaggers, with resident and emergency access kept open": { price: [2000, 8000], labor: 0.7, basis: "derived", note: "2-5 days of flaggers and devices at $1,000-$2,000/day" },
      "Clearing, grubbing and topsoil strip: vegetation removed, topsoil stockpiled for the shoulders and swales": { price: [0.15, 0.45], labor: 0.35, basis: "derived", q: 90000, note: "WisDOT clearing and grubbing by the acre, plus topsoil strip" },
      "Pulverize or remove the old road: full-depth reclamation of the asphalt and base as new sub-base, or excavation and haul-off": { price: [3, 9], labor: 0.35, basis: "est", note: "full-depth reclamation at the low end, excavation and haul-off at the high end" },
      "Mass excavation and fill: cut to subgrade, embankment placed in 8 in. lifts compacted to 95%, ditch lines and shoulders shaped": { price: [10, 22], labor: 0.3, basis: "src", q: 4500, note: "WisDOT common excavation $8.65-$14.47/CY; TxDOT $13/CY; small-site premium" },
      "Underground utilities in the road: water main, sanitary sewer, storm sewer and dry-utility conduit set before the base, trenches backfilled in compacted lifts": { price: [120, 380], labor: 0.4, basis: "derived", note: "per LF of each utility laid before the base; JobFlex utility bid research, restoration excluded" },
      "Storm structures: catch basins, curb inlets and junction boxes set on stone and raised to grade": { price: [2500, 5500], labor: 0.4, basis: "src", q: 8, note: "WisDOT inlets $2.0-$3.1k, catch basins $2.5-$2.8k, manholes $3.4-$4.2k" },
      "Culverts at driveways and cross-drains: RCP or HDPE at the stated diameter with flared ends and riprap at the outlets": { price: [60, 150], labor: 0.35, basis: "src", note: "WisDOT 12-24 in. culvert pipe $46-$127/LF plus apron endwalls $350-$770 ea" },
      "Subgrade: top 12 in. moisture-conditioned and compacted to 95%, proof-rolled, soft areas undercut and replaced, geogrid where the soils report requires it": { price: [1.5, 4.5], labor: 0.35, basis: "derived", q: 5330 },
      "Sub-base: 3 in. minus crushed rock spread and compacted at the stated depth": { price: [30, 55], labor: 0.25, basis: "derived", note: "WisDOT 3 in. dense base $13-$18/ton, breaker run $29-$56/CY" },
      "Aggregate base: dense-graded crushed stone at the stated depth (typically 6-10 in.) compacted to 98%, tonnage named": { price: [40, 75], labor: 0.25, basis: "derived", q: 1110, note: "WisDOT dense base $12-$24/ton at about 2 tons/CY; other states $25-$40/ton" },
      "Concrete curb and gutter: 6 in. barrier or roll curb slipformed to the standard detail, expansion joints at the stated spacing": { price: [26, 48], labor: 0.45, basis: "src", q: 3000, note: "WisDOT 30 in. curb and gutter $24-$47/LF; TxDOT $36/LF" },
      "Prime coat on the base, or tack coat on the reclaimed surface, before the first asphalt lift": { price: [0.8, 1.8], labor: 0.25, basis: "derived", q: 4670 },
      "Hot-mix binder course at the stated compacted depth (typically 2-3 in.), mix type and tonnage named, paver-laid and rolled": { price: [13, 22], labor: 0.2, basis: "derived", q: 4670, note: "2.5 in. at 0.14 ton/SY x $85-$130/ton, small-job premium" },
      "Hot-mix surface course at the stated compacted depth (typically 1.5-2 in.), mix type and tonnage named, joints staggered from the binder": { price: [9.5, 15], labor: 0.2, basis: "derived", q: 4670, note: "1.75 in. at 0.096 ton/SY x $95-$140/ton" },
      "Sidewalk: 4 in. concrete at the plan width with ADA curb ramps at each corner": { price: [7, 13], labor: 0.5, basis: "src", note: "TxDOT 4 in. sidewalk $75/SY ($8.33/sqft); WisDOT $6.62-$7.63/sqft; ramps add $2.8k-$6.5k each" },
      "Street signs, stop signs and street-light conduit and bases": { price: [400, 2500], labor: 0.4, basis: "est", note: "sign and post at the low end, light-pole base with conduit at the high end" },
      "Striping: centerline, edge lines and stop bars in paint or thermoplastic": { price: [0.35, 1.5], labor: 0.45, basis: "src", note: "WisDOT 4 in. paint $0.21-$0.49/LF; thermoplastic toward the high end" },
      "Shoulder and swale finish: topsoil, seed and mulch, and driveway tie-ins matched to the existing": { price: [0.25, 0.75], labor: 0.45, basis: "derived", q: 24000, note: "topsoil, seed and mulch; WisDOT topsoil $1.78-$4.37/SY" },
      "Density and thickness testing: nuclear density on subgrade, base and asphalt, cores where required, and the inspector's sign-off": { price: [3000, 10000], labor: 0.8, basis: "est", q: 1 },
      "Final sweep, punch list, as-builts and the maintenance bond for acceptance": { price: [5000, 15000], labor: 0.4, basis: "est", q: 1, note: "maintenance bond about 1-2% of contract plus as-builts; scales with job" },
    },
  },
  "road-milling": {
    op: 0.15,
    opNote: "paving subcontractor on public bids",
    benchmark: {
      unit: "sq yards",
      measures: "milled area",
      price: [3, 8],
      typicalQty: [4000, 16000],
      jobQty: 10000,
      minJob: 3500,
      sources: ["WisDOT avg unit prices FY2023-25: asphalt milling $1.50-$1.99/SY (large state jobs)", "Federal Way WA overlay bid tab 2026: planing $4.20-$8.00/SY", "WSDOT Northwest Region bids 2023-26: planing median $8.50/SY"],
    },
    steps: {
      "Pre-milling survey: depth confirmed against cores or the existing section, manholes, valves, monuments and detector loops marked and photographed, milling limits painted": { price: [800, 2500], labor: 0.9, basis: "est", q: 1 },
      "Traffic control for the milling train: lane closure with signs, cones and an arrow board, flaggers at intersections and driveways": { price: [3000, 9000], labor: 0.7, basis: "derived", q: 1, note: "3-5 days of lane closure at $1,000-$2,000/day; scales with days on site" },
      "Utility structures plated or ramped ahead of the mill so the drum clears them": { price: [40, 120], labor: 0.7, basis: "est", q: 20 },
      "Cold milling of the asphalt surface at the stated depth (typically 1.5-2 in. for an overlay, full depth for a rebuild) in continuous passes, grade and slope held by sonic ski or string line": { price: [1.75, 4.5], labor: 0.3, basis: "src", q: 10000, note: "WisDOT $1.50-$1.99/SY on big jobs; city jobs $4.20-$8.00/SY (Federal Way 2026)" },
      "Edge milling along the curb line and gutter lip so the new overlay meets the gutter flush": { price: [1, 3], labor: 0.4, basis: "est" },
      "Butt joints and tapers milled at the project limits, intersections and driveways so the overlay ties in without a bump": { price: [2, 6], labor: 0.45, basis: "derived", q: 600, note: "WisDOT butt-joint removal $8.91-$9.48/SY of joint area" },
      "Fine milling around manholes, valve boxes and inlets and in tight radii with a small (2-4 ft) mill": { price: [75, 200], labor: 0.5, basis: "est", q: 20 },
      "Millings loaded from the mill conveyor into trucks and hauled to the recycling yard or the owner's stockpile": { price: [6, 16], labor: 0.4, basis: "derived", q: 650, note: "trucking at $90-$130/hr per truck; WisDOT milling by the ton $5.52-$10.02" },
      "Milled surface swept with a pickup broom and the joints and gutters blown clean before it opens to traffic or is tacked": { price: [0.15, 0.45], labor: 0.5, basis: "derived", q: 10000, note: "pickup sweeper at $110-$160/hr" },
      "Temporary asphalt wedges at the open milled edges and driveways so traffic can cross before paving": { price: [150, 450], labor: 0.5, basis: "est" },
      "Manhole and valve-box frames raised to the overlay grade with riser rings or rebuilt frames": { price: [400, 1100], labor: 0.55, basis: "src", note: "WisDOT adjusting manhole covers $755-$798 ea, inlet covers $593-$700 ea" },
      "Tack coat: SS-1h emulsion at the stated rate on the milled surface ahead of the paver": { price: [0.25, 0.75], labor: 0.3, basis: "derived", note: "0.05-0.07 gal/SY; WisDOT tack coat $2.90-$2.98/gal" },
      "Milled surface check: depth measured with a straight edge and gauge every 100 ft, scabs and loose material corrected": { price: [300, 1000], labor: 1, basis: "est", q: 1 },
      "Cleanup: spilled millings swept at the load-out, dust controlled with a water truck, milling machine and trucks removed": { price: [500, 2000], labor: 0.5, basis: "est", q: 1 },
    },
  },
  "chip-seal": {
    op: 0.15,
    opNote: "public-works pavement preservation bids",
    benchmark: {
      unit: "sq yards",
      measures: "treated road area",
      price: [2.5, 6],
      typicalQty: [10000, 50000],
      jobQty: 30000,
      minJob: 10000,
      sources: ["SaveMyRoad (Ergon) 2025: conventional chip seal averages $2.25/sq yd", "WisDOT avg unit prices FY2023-25: seal-coat asphalt $2.77-$4.39/gal; seal coat $165.90/ton of cover aggregate"],
    },
    steps: {
      "Pavement condition walk: cracks, potholes, edge failures and bleeding mapped, and the emulsion and chip rates set from the surface texture and traffic": { price: [500, 2000], labor: 0.9, basis: "est", q: 1 },
      "Traffic control: pilot car, flaggers and signs for one-lane operation, loose-chip and reduced-speed signs posted through the cure": { price: [4000, 12000], labor: 0.75, basis: "derived", q: 1, note: "pilot car, 2-4 flaggers and signs for 2-4 days; scales with days" },
      "Crack sealing of cracks over 1/4 in. with hot-pour rubberized sealant, blotted with sand": { price: [0.75, 2], labor: 0.55, basis: "src", note: "TruTec 2026: municipal $0.60-$1.00/LF, commercial $0.90-$1.50/LF" },
      "Patching of potholes and failed areas with hot-mix asphalt, compacted flush and cured before the seal": { price: [40, 110], labor: 0.45, basis: "derived", note: "hot-mix patch $4-$10/sqft (FixAsphalt 2025); JobFlex utility research $40-$150/SY" },
      "Surface cleaning: power broom and blower to remove dust, vegetation and debris; manholes and valves covered, gutters and driveways masked": { price: [0.1, 0.3], labor: 0.5, basis: "est", q: 30000 },
      "Asphalt emulsion (CRS-2P or HFRS-2P polymer-modified) sprayed at the stated rate (typically 0.35-0.45 gal per sq yard) by a computer-controlled distributor at the spray temperature": { price: [1, 1.8], labor: 0.15, basis: "derived", q: 30000, note: "0.35-0.45 gal/SY x WisDOT $2.77-$4.39/gal, distributor included" },
      "Cover aggregate: clean, dry 3/8 in. or 1/2 in. chips (pre-coated where specified) spread by a self-propelled chip spreader immediately behind the distributor at the stated rate, tonnage named": { price: [0.55, 1.25], labor: 0.25, basis: "derived", q: 30000, note: "20-25 lb/SY of chips; WisDOT seal coat $165.90/ton" },
      "Rolling with pneumatic rubber-tire rollers in three passes within minutes of the chip spread to seat the aggregate": { price: [0.1, 0.3], labor: 0.4, basis: "est", q: 30000 },
      "Second course: a second emulsion shot and 1/4 in. chips over the first course": { price: [1.5, 3], labor: 0.2, basis: "derived", note: "second shot plus 1/4 in. chips, about 60-70% of the first course" },
      "Initial sweep of loose chips after cure (next morning), and a second sweep after 2-3 days of traffic, sweepings hauled off": { price: [0.1, 0.3], labor: 0.5, basis: "est", q: 30000 },
      "Fog seal: diluted CSS-1h emulsion sprayed at about 0.10 gal per sq yard over the swept chips to lock the surface and darken it": { price: [0.25, 0.6], labor: 0.3, basis: "derived", note: "about 0.10 gal/SY diluted emulsion, distributor included" },
      "Manholes and valves uncovered, masking pulled, gutters and driveway aprons cleaned of emulsion and chips": { price: [25, 75], labor: 0.9, basis: "est", q: 30 },
      "Pavement markings: temporary tabs through the cure, then paint or thermoplastic lines replaced": { price: [0.3, 1.2], labor: 0.45, basis: "src", note: "WisDOT 4 in. paint $0.21-$0.49/LF, temporary tabs and tape up to $1+/LF" },
      "Cleanup: excess chips swept from driveways, sidewalks and shoulders, signs pulled and the lanes opened at speed": { price: [800, 3000], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "slurry-seal": {
    op: 0.18,
    opNote: "pavement-preservation specialty sub, municipal and HOA",
    benchmark: {
      unit: "sq yards",
      measures: "treated pavement area",
      price: [2.25, 5],
      typicalQty: [8000, 40000],
      jobQty: 24000,
      minJob: 5000,
      sources: ["SaveMyRoad (Ergon) 2025: conventional slurry seal averages $2.50/sq yd, premium slurry $2.75/sq yd", "Homewyse May 2026: slurry seal $0.66-$1.08/sqft on small residential jobs"],
    },
    steps: {
      "Surface evaluation and mix design: ISSA A105 Type I, II or III chosen for the traffic, mix design submitted with the aggregate source, emulsion (CQS-1h or polymer-modified) and additives": { price: [800, 2500], labor: 0.7, basis: "est", q: 1 },
      "Notices and traffic control: residents and tenants notified 48 hours ahead, no-parking signs posted, lanes closed with cones and flaggers through placement and cure": { price: [2500, 8000], labor: 0.7, basis: "est", q: 1, note: "notices, no-parking signs and flaggers; scales with phases" },
      "Crack sealing of cracks over 1/4 in. with hot-applied sealant at least a week ahead of the slurry": { price: [0.75, 2], labor: 0.55, basis: "src", note: "TruTec 2026: municipal $0.60-$1.00/LF, commercial $0.90-$1.50/LF" },
      "Patching of failed areas and potholes with hot-mix asphalt, compacted flush": { price: [40, 110], labor: 0.45, basis: "derived", note: "hot-mix patch $4-$10/sqft (FixAsphalt 2025)" },
      "Cleaning: power broom, blower and hand work, oil spots scrubbed and primed, vegetation removed from cracks and edges": { price: [0.1, 0.35], labor: 0.55, basis: "est", q: 24000 },
      "Manholes, valve covers, monuments and inlets masked with roofing felt or covers so they lift clean": { price: [20, 60], labor: 0.85, basis: "est", q: 40 },
      "Tack of oxidized or absorbent surfaces with diluted emulsion before the slurry": { price: [0.15, 0.4], labor: 0.35, basis: "est" },
      "Slurry seal placed by a continuous-flow slurry machine: Type II at 15-18 lb or Type III at 18-22 lb of dry aggregate per sq yard, spread with a rubber strike-off box, hand-squeegeed at edges and around structures": { price: [1.6, 3.2], labor: 0.3, basis: "src", q: 24000, note: "SaveMyRoad 2025: $2.50/SY average; Type III and polymer-modified mixes at the high end" },
      "Second course placed after the first cures": { price: [1.5, 2.8], labor: 0.3, basis: "derived", note: "second course priced a little under the first" },
      "Joints, radii, intersections and driveway approaches worked with hand squeegees so there are no ridges or drop-offs": { price: [0.3, 1], labor: 0.9, basis: "est", q: 3000 },
      "Rolling with a pneumatic roller once the mat has set": { price: [0.08, 0.25], labor: 0.45, basis: "est" },
      "Cure and uncover: surface closed 2-4 hours until it takes traffic, covers pulled and structures cleaned": { price: [15, 50], labor: 0.9, basis: "est", q: 40, note: "per structure uncovered and cleaned" },
      "Pavement markings replaced after 24 hours of cure: paint or thermoplastic stripes, stalls and legends": { price: [0.3, 1], labor: 0.5, basis: "src", note: "WisDOT 4 in. paint $0.21-$0.49/LF; parking stalls and legends toward the high end" },
      "Cleanup: drips and tracking cleaned off curbs and driveways, loose material swept after 24-48 hours, lanes opened": { price: [600, 2500], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "crack-sealing": {
    op: 0.18,
    opNote: "pavement-maintenance specialty sub",
    benchmark: {
      unit: "linear ft",
      measures: "crack length sealed",
      price: [0.9, 2.5],
      typicalQty: [3000, 15000],
      jobQty: 9000,
      minJob: 750,
      sources: ["TruTec 2026: crack sealing $0.60-$1.00/LF municipal, $0.90-$1.50/LF commercial, $1.50-$3.00/LF routed", "HomeGuide 2026: asphalt crack sealing $0.50-$3.00/LF, $100-$250 minimum"],
    },
    steps: {
      "Crack survey: cracks walked and measured by width (1/4-1/2 in., 1/2-1 in., over 1 in.), working cracks noted, alligatored areas excluded and marked for patching": { price: [300, 1000], labor: 0.9, basis: "est", q: 1 },
      "Traffic control: cones, signs and a lane closure with a flagger for the crew and the melter": { price: [1000, 4000], labor: 0.75, basis: "derived", q: 1, note: "flagger, cones and signs for 1-3 days" },
      "Routing: cracks 1/4-3/4 in. routed with a random-crack router to a 1/2 in. by 1/2 in. reservoir (or the stated dimensions) for a full sealant band": { price: [0.35, 0.9], labor: 0.6, basis: "derived", note: "routed $1.50-$3.00/LF vs $0.90-$1.50/LF unrouted (TruTec 2026)" },
      "Cleaning: compressed air and a hot-air lance to dry the crack and blow out dust, vegetation and moisture": { price: [0.1, 0.3], labor: 0.7, basis: "est", q: 9000 },
      "Hot-pour sealant: rubberized asphalt meeting ASTM D6690 Type II (Type IV in cold climates) melted in an oil-jacketed melter and applied with a wand at about 380 deg F": { price: [0.45, 1.1], labor: 0.45, basis: "derived", q: 9000, note: "sealant about $0.18-$0.35/LF plus melter and crew (TruTec 2026)" },
      "Overband: sealant squeegeed in a 2-3 in. band over the crack, or struck flush where the specification calls for flush fill": { price: [0.05, 0.2], labor: 0.6, basis: "est", q: 9000 },
      "Wide cracks and joints over 1 in. filled with a polymer-modified mastic with aggregate, placed in lifts": { price: [3, 8], labor: 0.45, basis: "est" },
      "Pavement-to-gutter and curb joints sealed along the concrete edge": { price: [0.8, 2], labor: 0.5, basis: "est" },
      "Blotting: sand or a detackifier over the fresh sealant so traffic does not track it before it cools": { price: [0.02, 0.06], labor: 0.6, basis: "est", q: 25000, note: "per sq yd of the pavement section sealed, not of the blotted band" },
      "Cure and open: sealant cooled 30-60 minutes before traffic, tracking checked": { price: [150, 500], labor: 0.9, basis: "est", q: 1 },
      "Cleanup: routing dust swept, sealant spills scraped, signs and cones removed": { price: [200, 700], labor: 0.8, basis: "est", q: 1 },
      "Sealed-footage map by section, delivered with the invoice": { price: [150, 500], labor: 1, basis: "est", q: 1 },
    },
  },
  "sealcoating": {
    op: 0.25,
    opNote: "small commercial and residential service trade",
    benchmark: {
      unit: "sqft",
      measures: "sealed pavement area",
      price: [0.22, 0.55],
      typicalQty: [10000, 60000],
      jobQty: 35000,
      minJob: 750,
      sources: ["HomeGuide 2025: asphalt sealcoating $0.14-$0.25/sqft", "FixAsphalt 2025: lot sealcoating $0.20-$0.50/sqft; with crack sealing and striping $0.65-$0.90/sqft (NJ)"],
    },
    steps: {
      "Site walk and scheduling: area measured, oil spots, alligatored areas and drainage noted, two dry days over 50 deg F scheduled, tenants notified to move cars": { price: [150, 500], labor: 0.9, basis: "est", q: 1 },
      "Barricades and no-parking: cones, tape and signs at every entrance, lot closed in phases so the tenants keep access": { price: [300, 1200], labor: 0.6, basis: "est" },
      "Cleaning: power broom and blower, wire brush at the edges and cracks, weeds pulled, caked dirt pressure-washed": { price: [0.02, 0.05], labor: 0.75, basis: "est", q: 35000 },
      "Oil spots scrubbed and coated with an oil-spot primer so the sealer bonds": { price: [10, 30], labor: 0.6, basis: "est", q: 25 },
      "Hot rubberized crack filling of cracks 1/4 in. to 1 in. wide": { price: [0.75, 2], labor: 0.5, basis: "src", q: 1500, note: "FixAsphalt 2025: crack filling $1-$2/LF; TruTec 2026 commercial $0.90-$1.50/LF" },
      "Alligatored areas skim-patched with a trowel-grade patch mix, or cut out and patched with hot-mix": { price: [3, 9], labor: 0.5, basis: "derived", note: "FixAsphalt 2025: patching $4-$10/sqft; skim patch at the low end" },
      "First coat: asphalt-emulsion sealer (or refined coal-tar where allowed) mixed with 2-4 lb of sand per gallon and a latex additive, spray or squeegee applied at the stated rate": { price: [0.07, 0.15], labor: 0.45, basis: "derived", q: 35000, note: "about half of a two-coat price of $0.14-$0.30/sqft" },
      "Second coat applied in the cross direction after the first cures (2-4 hours)": { price: [0.05, 0.12], labor: 0.45, basis: "derived", q: 35000 },
      "Third coat on drive lanes and entrances": { price: [0.05, 0.12], labor: 0.45, basis: "derived" },
      "Edges cut in by hand brush at curbs, sidewalks, buildings and structures, masked for a clean line": { price: [0.1, 0.3], labor: 0.85, basis: "est", q: 1200 },
      "Cure: lot closed 24-48 hours (longer in cool weather) before it opens to traffic": { price: [0, 150], labor: 0.5, basis: "est", q: 1, note: "idle cure time; nearly free unless the crew returns to open the lot" },
      "Re-striping: stalls, ADA stalls and hatching, fire lane, arrows and stop bars in traffic paint on the cured sealer": { price: [0.25, 0.6], labor: 0.55, basis: "derived", note: "4 in. traffic paint; FixAsphalt 2025 striping $0.02-$0.06 per sqft of lot" },
      "Stencils and curb paint: ADA symbols, arrows, stall numbers, NO PARKING and painted curbs": { price: [25, 90], labor: 0.6, basis: "est" },
      "Barricades removed, lot edges swept, spills washed off the concrete": { price: [100, 400], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "pothole-repair": {
    op: 0.22,
    opNote: "commercial paving maintenance sub",
    benchmark: {
      unit: "sqft",
      measures: "patched area",
      price: [7, 17],
      typicalQty: [150, 650],
      jobQty: 400,
      minJob: 1500,
      sources: ["FixAsphalt 2025: asphalt patching $4-$10/sqft, $2,500-$5,000 minimum (NJ)", "JobFlex utility bid research 2026: full-depth HMA patch $40-$150/sq yd national, saw-cut $1.50-$3/LF"],
    },
    steps: {
      "Pothole survey: each hole measured for area and depth, photographed and numbered, and the method chosen per hole (hot-mix cutout, infrared or cold patch)": { price: [100, 350], labor: 0.9, basis: "est", q: 1 },
      "Traffic control: cones, signs and a flagger while the crew and truck occupy the lane": { price: [300, 1000], labor: 0.75, basis: "est", q: 1 },
      "Saw-cut or mill the patch edges 12 in. beyond the failed area into sound pavement, faces vertical and squared": { price: [1.25, 3], labor: 0.6, basis: "src", q: 280, note: "saw-cut asphalt $1.50-$3/LF national (Neenah WI 2024 bid tab)" },
      "Remove the failed asphalt and loose base to sound material, base recompacted and crushed stone added where it is soft": { price: [1, 3], labor: 0.55, basis: "est", q: 400 },
      "Tack coat sprayed on the vertical faces and floor of the cutout": { price: [8, 25], labor: 0.6, basis: "est", q: 12, note: "per patch" },
      "Hot-mix asphalt patch (surface mix at 3 in. compacted or matched to the existing) placed hot from a hot box and compacted with a vibratory plate or roller, crowned 1/4 in.": { price: [3.5, 7.5], labor: 0.45, basis: "derived", q: 400, note: "3 in. hot-mix placed and compacted; FixAsphalt 2025 patching $4-$10/sqft all-in" },
      "Infrared repair: the existing asphalt heated 8-10 minutes, raked, rejuvenator added, new hot-mix blended in and compacted to a seamless patch": { price: [3, 8], labor: 0.55, basis: "est" },
      "Cold patch: high-performance cold mix compacted in lifts as a temporary or winter repair": { price: [60, 200], labor: 0.6, basis: "est", note: "per pothole" },
      "Patch seams sealed with a hot-pour sealant band": { price: [0.75, 2], labor: 0.5, basis: "src", q: 280, note: "FixAsphalt 2025 crack filling $1-$2/LF" },
      "Removed asphalt hauled to a recycler": { price: [30, 90], labor: 0.2, basis: "est", q: 6, note: "small loads, mostly truck time and the recycler fee" },
      "Cleanup: patch area swept, cones pulled, patches opened to traffic once cooled": { price: [75, 250], labor: 0.85, basis: "est", q: 1 },
      "Patch log with locations and photos, and the warranty on the hot-mix cutout patches": { price: [75, 250], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "concrete-curb-gutter": {
    op: 0.18,
    opNote: "concrete flatwork sub on civil and commercial work",
    benchmark: {
      unit: "linear ft",
      measures: "curb and gutter length",
      price: [35, 75],
      typicalQty: [200, 1000],
      jobQty: 600,
      minJob: 2500,
      sources: ["WisDOT avg unit prices FY2023-25: 30 in. curb and gutter $24-$47/LF", "TxDOT 3-yr avg bids (Caliche 2026): curb and gutter Ty II $36/LF", "Homewyse May 2026: concrete curb $47-$58/LF on a small job"],
    },
    steps: {
      "Layout: line and grade from the plan or matched to the existing curb, string line and stakes set, radii and driveway openings marked": { price: [500, 1500], labor: 0.9, basis: "est", q: 1 },
      "Traffic and pedestrian control: cones, signs, and barricades at the open trench and fresh concrete": { price: [500, 2500], labor: 0.7, basis: "est", q: 1 },
      "Saw-cut and remove the existing curb and gutter, broken out and hauled to a recycler, with the asphalt cut back 12-18 in. from the gutter lip": { price: [8, 18], labor: 0.55, basis: "derived", note: "WisDOT removing curb and gutter $5.19-$6.07/LF plus saw-cut and asphalt cut-back" },
      "Excavate to the section, compact the subgrade and place 4-6 in. of compacted crushed stone base": { price: [70, 150], labor: 0.45, basis: "est", q: 33, note: "per CY of base placed, excavation included" },
      "Forms set to line and grade with radius forms, or a slipform curb machine on string line, at the stated profile (6 in. vertical, roll or mountable curb with an 18-30 in. gutter pan)": { price: [4, 9], labor: 0.8, basis: "est", q: 600 },
      "Tie-in dowels drilled and epoxied into the existing curb ends, #4 by 18 in.": { price: [15, 40], labor: 0.7, basis: "est", q: 6 },
      "Concrete: 4,000 psi air-entrained (5-7% air) mix placed, consolidated and finished to the profile with the pan sloped to drain, broom finish and tooled edges": { price: [14, 26], labor: 0.45, basis: "derived", q: 600, note: "0.07-0.09 CY/LF at $160-$190/CY delivered, placed and finished" },
      "Joints: contraction joints tooled or sawed at 10 ft, 1/2 in. expansion joints with preformed filler at 50-100 ft, at radius points and at every structure": { price: [8, 25], labor: 0.8, basis: "est", q: 68 },
      "Driveway aprons and depressed curb cuts formed at the openings with the drop and transitions per the standard detail": { price: [900, 2500], labor: 0.5, basis: "est" },
      "Curb inlet and catch basin throats formed into the curb line": { price: [600, 1800], labor: 0.55, basis: "est" },
      "Curing compound sprayed or wet cure; forms stripped after 24 hours and honeycomb patched": { price: [0.5, 1.5], labor: 0.7, basis: "est", q: 600 },
      "Backfill: topsoil behind the curb, compacted stone in front so the gutter lip meets the pavement": { price: [2, 5], labor: 0.6, basis: "est", q: 600 },
      "Asphalt patch along the gutter lip where the pavement was cut back": { price: [5, 12], labor: 0.45, basis: "derived", note: "FixAsphalt 2025 patching $4-$10/sqft" },
      "Cleanup: washout contained, forms and spoils removed, sweep, and the curb opened to traffic after 7 days": { price: [300, 1000], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "sidewalk": {
    op: 0.2,
    opNote: "concrete flatwork sub, municipal and commercial",
    benchmark: {
      unit: "sqft",
      measures: "sidewalk area",
      price: [9, 18],
      typicalQty: [500, 2500],
      jobQty: 1500,
      minJob: 2000,
      sources: ["TxDOT 3-yr avg bids (Caliche 2026): 4 in. sidewalk $75/sq yd ($8.33/sqft)", "WisDOT avg unit prices FY2023-25: 4 in. sidewalk $6.62-$7.63/sqft", "Homewyse May 2026: concrete sidewalk $12.00-$14.71/sqft on a small job, no base or removal"],
    },
    steps: {
      "Layout and grade: walk staked for width and alignment, cross slope held to 2% max and running slope to 5% max, driveway crossings and ramp locations marked": { price: [300, 900], labor: 0.9, basis: "est", q: 1 },
      "Right-of-way or encroachment permit, inspection scheduling and the 811 utility locate": { price: [100, 500], labor: 0, fee: true, basis: "src", q: 1, note: "ROW or encroachment permit; 811 locate is free" },
      "Pedestrian and traffic control: detour signs, barricades and a covered walkway where the route stays open": { price: [500, 2500], labor: 0.6, basis: "est" },
      "Demolition of the existing sidewalk: saw-cut at the joints, broken out and hauled to a recycler": { price: [2, 5], labor: 0.55, basis: "derived", note: "WisDOT removing sidewalk $7.01-$7.78/SY on big jobs; small jobs add haul and saw-cut" },
      "Tree root pruning under the walk by hand or air spade with an arborist's direction, and a root barrier along the walk": { price: [15, 45], labor: 0.6, basis: "est" },
      "Excavation to grade and subgrade compacted to 95%": { price: [0.75, 2], labor: 0.55, basis: "est", q: 1500 },
      "Aggregate base: 4 in. of crushed stone compacted under the walk": { price: [65, 140], labor: 0.35, basis: "est", q: 18.5, note: "per CY placed and compacted" },
      "Forms set to line and grade with 1/2 in. expansion joints at 20-30 ft and at every structure, driveway and building": { price: [2.5, 6], labor: 0.8, basis: "est", q: 600 },
      "Reinforcement: 6x6 W1.4 welded wire mesh or synthetic fibers, and #4 rebar at driveway crossings": { price: [0.4, 1.2], labor: 0.5, basis: "est" },
      "Concrete: 4 in. (6 in. at driveway crossings) of 4,000 psi air-entrained concrete screeded, floated and broom-finished, tooled edges and contraction joints at 5 ft": { price: [4.5, 8], labor: 0.45, basis: "derived", q: 1500, note: "4 in. concrete about 0.0125 CY/sqft at $160-$190/CY plus place and finish" },
      "ADA curb ramps at intersections with detectable warning panels": { price: [2800, 6500], labor: 0.5, basis: "src", note: "TxDOT curb ramp $2,790 ea (ramp only); with removal and warning panels up to $6.5k" },
      "Curing compound or wet cure, kept clear of foot traffic 24 hours and vehicles 7 days": { price: [0.1, 0.3], labor: 0.6, basis: "est", q: 1500 },
      "Edges backfilled with topsoil and seeded or sodded, asphalt wedge at driveway aprons": { price: [1.5, 4], labor: 0.55, basis: "est", q: 600 },
      "Cleanup: spoils and forms hauled off, sweep, and the city inspection sign-off": { price: [300, 1000], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "ada-ramp": {
    op: 0.18,
    opNote: "public-works concrete specialty sub",
    benchmark: {
      unit: "unit",
      measures: "curb ramps built",
      price: [4500, 12000],
      typicalQty: [2, 8],
      jobQty: 5,
      minJob: 4000,
      sources: ["TxDOT 3-yr avg bids (Caliche 2026): curb ramp Ty 1 $2,790 each (ramp item only)", "WisDOT avg unit prices FY2023-25: detectable warning field $43-$54/sqft, 4 in. sidewalk $6.62-$7.63/sqft"],
    },
    steps: {
      "Survey and ramp design: existing grades shot at the corner, the ramp type chosen to hold a 1:12 (8.33%) running slope, 2% cross slope, a 4 ft by 4 ft landing and 1:10 flares, drawn for the inspector": { price: [250, 800], labor: 0.9, basis: "est", q: 5, note: "per ramp" },
      "Permits and coordination: right-of-way permit, the PROWAG or state standard drawing, and conflicts with signal poles, push-buttons and utilities resolved": { price: [150, 800], labor: 0, fee: true, basis: "est", q: 1, note: "ROW permit fee; coordination time sits in the survey step" },
      "Pedestrian detour and traffic control at the corner: signs, barricades and a temporary accessible walkway": { price: [1500, 5000], labor: 0.6, basis: "est", q: 1, note: "scales with corners and days" },
      "Saw-cut and remove the existing curb, gutter and sidewalk in the ramp footprint, hauled off": { price: [3, 7], labor: 0.55, basis: "est", q: 900 },
      "Valve boxes, pull boxes, sign posts and pedestrian push-buttons adjusted or relocated out of the ramp": { price: [300, 1500], labor: 0.55, basis: "est" },
      "Subgrade compacted and 4 in. of crushed stone base placed under the ramp and landing": { price: [1, 2.5], labor: 0.5, basis: "est", q: 750 },
      "Forms set to the surveyed elevations for the ramp, landing and flares or returned curbs, slopes checked with a smart level before the pour": { price: [300, 800], labor: 0.85, basis: "est", q: 5, note: "per ramp" },
      "Concrete: 6 in. of 4,000 psi air-entrained concrete on the ramp and landing, broom finish across the direction of travel, no lip over 1/4 in. at the gutter": { price: [8, 15], labor: 0.5, basis: "derived", q: 750, note: "6 in. concrete on small hand-finished pours; TxDOT ramp item $2,790 ea" },
      "Depressed curb and gutter transitions with the gutter counter-slope held to 5% max": { price: [30, 60], labor: 0.5, basis: "derived", q: 75, note: "curb and gutter $24-$47/LF (WisDOT) plus the depressed transitions" },
      "Detectable warning surface: cast-in-place or surface-applied truncated dome panels 24 in. deep across the full ramp width at the back of curb, contrasting color": { price: [350, 800], labor: 0.3, basis: "src", q: 5, note: "per ramp: 8-10 sqft at WisDOT $43-$54/sqft (radial $61-$73/sqft)" },
      "Cure and slope verification: every running and cross slope read with a smart level after cure and recorded": { price: [100, 300], labor: 0.9, basis: "est", q: 5, note: "per ramp" },
      "Adjacent sidewalk, asphalt and lawn restored, signs reset": { price: [4, 10], labor: 0.5, basis: "est", q: 300 },
      "Cleanup and the inspection sign-off with the as-built slope form": { price: [300, 1000], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "parking-lot-construction": {
    op: 0.2,
    opNote: "commercial site-paving sub",
    benchmark: {
      unit: "sq yards",
      measures: "paved lot area",
      price: [45, 95],
      typicalQty: [2000, 8000],
      jobQty: 5000,
      minJob: 25000,
      sources: ["AsphaPro 2026: residential street or lot pavement $30-$60/sq yd; all-in components $4.85-$14.30/sqft", "WisDOT avg unit prices FY2023-25: HMA $68-$100/ton, base aggregate $12-$24/ton, curb and gutter $24-$47/LF"],
    },
    steps: {
      "Construction staking from the civil site plan: lot limits, curb lines, islands, drainage structures and finished grades set": { price: [2500, 7000], labor: 0.9, basis: "est", q: 1 },
      "Permits and coordination: grading permit, stormwater and SWPPP filing, inspection scheduling and the 811 locate": { price: [1000, 5000], labor: 0, fee: true, basis: "est", q: 1, note: "grading permit and stormwater/NOI filing fees" },
      "Erosion control: silt fence, inlet protection and a stabilized construction entrance": { price: [3, 7], labor: 0.5, basis: "derived", q: 900, note: "WisDOT silt fence $2/LF, inlet protection $60-$120 ea, tracking pad $350-$700 ea" },
      "Demolition of the existing pavement, slabs or structures in the footprint, hauled to a recycler": { price: [5, 15], labor: 0.45, basis: "derived", note: "WisDOT removing pavement $3.31-$6.42/SY on big jobs; small sites and slabs higher" },
      "Mass grading: cut and fill to subgrade with the lot pitched 1-2% to the inlets, fill compacted to 95%": { price: [10, 25], labor: 0.3, basis: "src", q: 2500, note: "WisDOT common excavation $8.65-$14.47/CY; TxDOT $13/CY; small-site premium" },
      "Storm drainage: RCP or HDPE pipe at the stated diameter from the inlets to the outfall or detention system": { price: [45, 110], labor: 0.4, basis: "src", q: 500, note: "12-18 in. HDPE or RCP; WisDOT RCP $79-$112/LF" },
      "Drainage structures: catch basins, curb inlets, junction boxes and the outlet control structure set to grade": { price: [2000, 5000], labor: 0.4, basis: "src", q: 5, note: "WisDOT inlets $2.0-$3.1k, catch basins $2.5-$2.8k" },
      "Conduit and concrete bases for site lighting, with sleeves for irrigation and signage": { price: [1200, 3500], labor: 0.5, basis: "est", note: "per light-pole base with its conduit run" },
      "Subgrade preparation: proof-roll, undercut soft spots and rebuild with stone over geotextile": { price: [1, 3.5], labor: 0.35, basis: "est", q: 5000 },
      "Aggregate base at the stated depth (typically 6-8 in.) compacted to 98%, tonnage named": { price: [40, 75], labor: 0.25, basis: "derived", q: 1110, note: "WisDOT dense base $12-$24/ton at about 2 tons/CY; other states $25-$40/ton" },
      "Concrete curb and gutter and island curbs (6 in. vertical or the plan profile) slipformed or formed": { price: [24, 45], labor: 0.45, basis: "src", q: 1200, note: "WisDOT curb and gutter $24-$47/LF; TxDOT $36/LF" },
      "Concrete pads at the dumpster enclosure and heavy-duty drive lanes: 6-8 in. reinforced 4,000 psi": { price: [8, 14], labor: 0.45, basis: "derived", note: "WisDOT 6-8 in. concrete driveway $65-$85/SY" },
      "Prime coat on the base before the first asphalt lift": { price: [0.8, 1.8], labor: 0.25, basis: "derived", q: 5000 },
      "Hot-mix binder course at the stated compacted depth (typically 2-3 in.), mix and tonnage named": { price: [12, 20], labor: 0.2, basis: "derived", q: 5000, note: "2.5 in. at 0.14 ton/SY x $90-$135/ton" },
      "Hot-mix surface course at the stated compacted depth (typically 1.5 in.), mix and tonnage named, rolled to density": { price: [8, 13], labor: 0.2, basis: "derived", q: 5000, note: "1.5 in. at 0.083 ton/SY x $100-$150/ton" },
      "Sidewalks, ADA ramps and the accessible route from the stalls to the entrance": { price: [8, 15], labor: 0.5, basis: "derived", note: "TxDOT sidewalk $8.33/sqft; ramps and landings push it up" },
      "Striping: stalls, ADA stalls with access aisles and hatching, fire lane, arrows and stop bars in traffic paint": { price: [0.3, 0.7], labor: 0.55, basis: "derived", q: 4000, note: "4 in. traffic paint; WisDOT paint $0.21-$0.49/LF on long runs" },
      "Signs, posts, bollards and wheel stops set": { price: [175, 700], labor: 0.4, basis: "src", q: 30, note: "FixAsphalt 2025: signs $135-$250 ea, concrete wheel stops $175-$325 ea; bollards $500-$1,500" },
      "Islands and perimeter: topsoil, seed or sod and tree wells": { price: [0.5, 2], labor: 0.5, basis: "est", q: 3000 },
      "Density testing on base and asphalt and concrete cylinders on the curb and pads": { price: [1500, 5000], labor: 0.8, basis: "est", q: 1 },
      "Final sweep, as-builts and the stormwater inspection sign-off": { price: [1500, 5000], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "parking-lot-maintenance": {
    op: 0.25,
    opNote: "commercial property maintenance service",
    benchmark: {
      unit: "sqft",
      measures: "lot area maintained",
      price: [0.28, 0.7],
      typicalQty: [20000, 100000],
      jobQty: 60000,
      minJob: 1500,
      sources: ["FixAsphalt 2025: sealcoat with crack sealing and striping $0.65-$0.90/sqft (NJ); crack filling $1-$2/LF", "HomeGuide 2025: sealcoating $0.14-$0.25/sqft", "TruTec 2026: commercial crack sealing $0.90-$1.50/LF"],
    },
    steps: {
      "Condition survey: lot walked and mapped by section for cracks, alligatored areas, potholes, drainage and structure condition and faded markings, with a phasing plan so tenants keep parking": { price: [300, 1200], labor: 0.9, basis: "est", q: 1 },
      "Tenant notices and phasing barricades: cones, tape and signs sectioning the lot so half stays open": { price: [400, 1500], labor: 0.6, basis: "est", q: 1 },
      "Sweeping and blowing the lot, weeds pulled from cracks and edges": { price: [0.01, 0.04], labor: 0.6, basis: "est", q: 60000 },
      "Full-depth asphalt patches: saw-cut, remove, base recompacted, hot-mix at 3-4 in. compacted": { price: [5, 12], labor: 0.45, basis: "src", note: "FixAsphalt 2025: patching $4-$10/sqft, with a $2,500-$5,000 minimum" },
      "Infrared or skin patches on alligatored areas": { price: [2.5, 6], labor: 0.55, basis: "est" },
      "Crack sealing of cracks over 1/4 in. with hot-pour rubberized sealant": { price: [0.9, 2], labor: 0.5, basis: "src", q: 2400, note: "TruTec 2026 commercial $0.90-$1.50/LF; FixAsphalt 2025 $1-$2/LF" },
      "Catch basin and drain repairs: frame reset, throat re-mortared, grate replaced": { price: [800, 2500], labor: 0.55, basis: "est" },
      "Curb repair: broken sections replaced and wheel stops reset or replaced": { price: [35, 80], labor: 0.5, basis: "est" },
      "Sealcoat: two coats of asphalt-emulsion sealer with sand, spray or squeegee applied": { price: [0.13, 0.28], labor: 0.45, basis: "src", q: 60000, note: "HomeGuide 2025 $0.14-$0.25/sqft; commercial lots $0.17-$0.35/sqft" },
      "Cure and phase change: each section closed 24 hours before the next section starts": { price: [100, 500], labor: 0.8, basis: "est", q: 1 },
      "Re-striping matched to the existing layout or the new plan: stalls, drive aisles, arrows and stop bars": { price: [0.25, 0.55], labor: 0.55, basis: "derived", q: 4500, note: "4 in. traffic paint; FixAsphalt 2025 striping $0.02-$0.06 per sqft of lot" },
      "ADA compliance: van stall, access aisles with hatching, signs at 60 in. and the stall count brought to code": { price: [400, 1200], labor: 0.45, basis: "est", note: "per ADA stall: stall and aisle paint, symbol, sign on post" },
      "Stencils and curb painting: symbols, numbers, fire lane and painted curbs": { price: [25, 90], labor: 0.6, basis: "est", q: 20 },
      "Bollards, signs and speed bumps replaced or added": { price: [200, 1200], labor: 0.45, basis: "derived", note: "FixAsphalt 2025: signs $135-$250 ea, wheel stops $175-$325 ea; bollards and speed bumps higher" },
      "Cleanup and a maintenance schedule left with the owner: crack seal yearly, sealcoat every 2-4 years": { price: [150, 500], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "traffic-control": {
    op: 0.2,
    opNote: "commercial specialty subcontractor",
    benchmark: {
      unit: "hour",
      measures: "flagger-hours on site",
      price: [80, 150],
      typicalQty: [40, 160],
      jobQty: 100,
      minJob: 800,
      sources: ["WSDOT Northwest Region bids 2023-26: flaggers $74-$110/hr (median $86); Federal Way WA 2026 $60-$75/hr", "JobFlex utility bid research 2026: lane closure with two flaggers, devices and a supervisor $1,000-$2,000/day national", "WisDOT avg unit prices FY2023-25: arrow board $10/day, PCMS $27-$38/day, TMA $200-$390/day (long state contracts)"],
    },
    steps: {
      "Temporary traffic control plan: MUTCD Part 6 typical application or a site-specific plan drawn, permitted with the DOT or city, and the closure schedule approved": { price: [300, 1500], labor: 0.85, basis: "est", q: 1, note: "typical application adapted at the low end; site-specific engineered plan costs more" },
      "Site review: traffic volumes, speed, sight distance, pedestrian and bus routes and business access noted; taper lengths and buffer space computed for the posted speed": { price: [150, 600], labor: 0.9, basis: "est", q: 1 },
      "Public notice: portable message signs placed a week ahead and notices to police, fire, transit and schools": { price: [800, 2500], labor: 0.4, basis: "est" },
      "Advance warning signs: 48 in. orange diamond signs (ROAD WORK AHEAD, LANE CLOSED, FLAGGER AHEAD) on portable stands at the spacing for the speed": { price: [40, 120], labor: 0.4, basis: "derived", q: 8, note: "per sign for a job of about a week: $5-$15/day rental plus placement" },
      "Channelizing devices: 28 in. or 36 in. cones, drums with retroreflective bands and warning lights, Type III barricades, set at the taper and tangent spacing": { price: [8, 25], labor: 0.3, basis: "derived", q: 30, note: "per device for a job of about a week: $1-$4/day plus placement" },
      "Arrow board at the closure taper and portable changeable message signs": { price: [350, 1100], labor: 0.1, basis: "derived", q: 1, note: "per unit per week: arrow board $75-$150/day, PCMS $150-$300/day" },
      "Truck-mounted attenuator shadow vehicle protecting the crew": { price: [90, 175], labor: 0.5, basis: "est", note: "truck, attenuator and operator" },
      "Certified flaggers with STOP and SLOW paddles, Class 2 or Class 3 high-visibility apparel and radios at each flagger station": { price: [45, 75], labor: 0.9, basis: "src", q: 100, note: "WSDOT NWR $74-$110/hr; Federal Way 2026 $60-$75/hr; national $45-$80/hr" },
      "Pilot car for one-lane two-way operation": { price: [60, 100], labor: 0.75, basis: "est" },
      "Pedestrian accommodation: accessible temporary walkway, pedestrian barricades and detour signs": { price: [6, 18], labor: 0.45, basis: "est" },
      "Temporary pavement markings and covering of conflicting permanent signs": { price: [0.5, 2], labor: 0.45, basis: "src", note: "WisDOT temporary paint $0.26-$0.55/LF, removable tape $0.93-$1.73/LF" },
      "Daily setup, walk-through and pickup: devices placed at the start of the shift, reset through the shift, and picked up or dropped to the overnight layout, logged": { price: [600, 2000], labor: 0.85, basis: "est", q: 1, note: "scales with days: about $120-$400 per day" },
      "Night operations: lighted devices, portable light towers and the night-shift crew": { price: [80, 160], labor: 0.6, basis: "est" },
      "Certified traffic control supervisor on site with daily inspection reports and the traffic control diary": { price: [65, 110], labor: 0.9, basis: "derived", q: 10, note: "WSDOT NWR other traffic-control labor $60-$144/hr" },
      "Emergency call-out and replacement of struck or stolen devices": { price: [150, 500], labor: 0.5, basis: "est" },
      "Demobilization: every device removed, permanent signs uncovered, and the closure log delivered for the permit close-out": { price: [200, 700], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "road-striping": {
    op: 0.2,
    opNote: "specialty subcontractor",
    benchmark: {
      unit: "linear ft",
      measures: "painted line length, 4 in. equivalent",
      price: [0.5, 1.4],
      typicalQty: [5000, 35000],
      jobQty: 20000,
      minJob: 1000,
      sources: ["WisDOT avg unit prices FY2023-25: 4 in. paint line $0.21-$0.49/LF, epoxy $0.50-$0.79/LF, epoxy arrow $222-$230 ea", "FixAsphalt 2025: line striping $0.02-$0.06 per sqft of lot"],
    },
    steps: {
      "Layout: control points taken from the striping plan or the existing markings, offsets measured and spotted with paint every 25-50 ft": { price: [400, 1500], labor: 0.9, basis: "est", q: 1 },
      "Traffic control for a moving operation: shadow vehicle with an arrow board, cones behind the striper through the dry time": { price: [800, 3000], labor: 0.6, basis: "derived", q: 1, note: "shadow truck with arrow board at $90-$175/hr for 1-2 days" },
      "Removal of conflicting or old markings by waterblasting or grinding, debris vacuumed": { price: [0.75, 2.5], labor: 0.5, basis: "est" },
      "Surface preparation: sweep and blow the line path; new asphalt cured and new concrete cured 30 days with the curing compound removed": { price: [0.02, 0.08], labor: 0.7, basis: "est", q: 20000 },
      "Primer or sealer on new concrete, or on aged asphalt ahead of thermoplastic": { price: [0.1, 0.35], labor: 0.4, basis: "est" },
      "Waterborne traffic paint lines (4 in. white or yellow at 15 mil wet) with glass beads dropped at 6-8 lb per gallon": { price: [0.18, 0.45], labor: 0.45, basis: "src", q: 20000, note: "WisDOT 4 in. paint $0.21-$0.49/LF" },
      "Thermoplastic lines (90-125 mil extruded, or 60 mil sprayed) meeting AASHTO M249, with intermix and drop-on beads": { price: [0.9, 2.5], labor: 0.4, basis: "est", note: "4 in. thermoplastic; long state runs sit under $1/LF" },
      "Preformed tape or epoxy lines set per the manufacturer at the plan locations": { price: [0.8, 4], labor: 0.3, basis: "src", note: "WisDOT epoxy $0.50-$0.79/LF; grooved tape $8-$14/LF" },
      "Symbols and legends: arrows, ONLY, crosswalk bars, stop bars and railroad crossings hand-applied in thermoplastic or stenciled paint": { price: [120, 350], labor: 0.5, basis: "src", q: 25, note: "WisDOT arrow paint $178-$193 ea, epoxy $222-$230; word epoxy $242-$257" },
      "Raised pavement markers set in bituminous or epoxy adhesive at the plan spacing, snowplowable castings where required": { price: [6, 45], labor: 0.45, basis: "est", note: "plain raised markers at the low end, snowplowable castings at the high end" },
      "Retroreflectivity readings with a handheld retroreflectometer (ASTM E1710) and the report per the specification": { price: [300, 1200], labor: 0.85, basis: "est", q: 1 },
      "Curb painting: fire lane red, no-parking yellow and the stall ends": { price: [0.5, 1.5], labor: 0.6, basis: "est" },
      "Cleanup: overspray removed, cones pulled and the lanes opened once the lines are dry": { price: [150, 500], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "guardrail": {
    op: 0.15,
    opNote: "public-works bid",
    benchmark: {
      unit: "linear ft",
      measures: "guardrail length, terminals included",
      price: [45, 95],
      typicalQty: [200, 800],
      jobQty: 500,
      minJob: 5000,
      sources: ["WisDOT avg unit prices FY2023-25: MGS guardrail $26.92-$30.76/LF; MGS energy-absorbing terminal $3,709-$3,986 ea", "TxDOT 3-yr avg bids (Caliche 2026): guardrail end treatment installed $3,138 ea"],
    },
    steps: {
      "Layout: post spacing (6 ft 3 in. standard) and rail height (31 in. for MGS) staked, terminal locations and runout grading checked, 811 locate for the post line": { price: [500, 1500], labor: 0.9, basis: "est", q: 1 },
      "Traffic control: shoulder or lane closure with signs, drums and a truck-mounted attenuator": { price: [1500, 5000], labor: 0.6, basis: "est", q: 1, note: "shoulder closure with a TMA for 2-3 days" },
      "Removal of the existing guardrail, posts and terminals, salvaged or hauled to scrap": { price: [3, 8], labor: 0.6, basis: "src", note: "WisDOT removing guardrail $2.36-$2.89/LF on long runs" },
      "Grading behind the rail and at the terminal runout area to the standard slope": { price: [0.5, 2], labor: 0.4, basis: "est" },
      "Posts: W6x8.5 steel or 6x8 treated timber posts, 6 ft long, driven with a post driver at the spacing; drilled and backfilled where rock is met": { price: [70, 140], labor: 0.4, basis: "src", q: 81, note: "WisDOT replacing guardrail posts and blocks $89-$110 ea" },
      "Blockouts: 8 in. or 12 in. composite, timber or steel blockouts bolted to the posts": { price: [12, 30], labor: 0.35, basis: "est", q: 81 },
      "W-beam rail: 12-gauge galvanized W-beam (AASHTO M180) lapped in the direction of traffic, splice bolts torqued, mid-span splices for MGS": { price: [14, 26], labor: 0.35, basis: "src", q: 500, note: "WisDOT replacing rail and hardware $15-$19/LF; MGS all-in $27-$31/LF with posts" },
      "Thrie-beam transitions with nested rail and the connection to the bridge rail or concrete barrier": { price: [85, 130], labor: 0.35, basis: "src", note: "WisDOT MGS thrie-beam transition $91-$95/LF" },
      "End terminals: MASH TL-3 energy-absorbing tangent terminals, with the anchor, grading and offset per the manufacturer": { price: [3000, 4800], labor: 0.25, basis: "src", q: 2, note: "WisDOT MGS EAT $3,709-$3,986 ea; TxDOT $3,138 ea" },
      "Trailing-end anchors or buried-in-backslope terminals": { price: [900, 2500], labor: 0.35, basis: "src", note: "WisDOT beam-guard anchorages $946-$2,188 ea" },
      "Delineators with reflective sheeting on the posts at the plan spacing": { price: [25, 60], labor: 0.5, basis: "src", q: 10, note: "WisDOT steel delineator posts $29-$34 ea" },
      "Cable barrier: driven posts and tensioned cables to the manufacturer's tension": { price: [18, 35], labor: 0.35, basis: "est" },
      "Height and torque check, bolt tightening, and the certified installer's inspection report": { price: [300, 900], labor: 0.95, basis: "est", q: 1 },
      "Cleanup: post holes backfilled, disturbed shoulder seeded, traffic control removed": { price: [300, 1000], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "road-sign": {
    op: 0.2,
    opNote: "specialty subcontractor",
    benchmark: {
      unit: "unit",
      measures: "signs installed, each with its post",
      price: [350, 900],
      typicalQty: [10, 40],
      jobQty: 25,
      minJob: 1000,
      sources: ["WisDOT avg unit prices FY2023-25: Type II reflective signs $21-$31/sqft, 2x2 in. tubular steel posts $190-$243 ea, sign removal $27-$34 ea", "FixAsphalt 2025: traffic signs $135-$250 per sign installed on lots"],
    },
    steps: {
      "Sign inventory and MUTCD review: locations, messages, sizes and mounting heights per the MUTCD and the state supplement, placement staked and the 811 locate": { price: [400, 1500], labor: 0.9, basis: "est", q: 1 },
      "Traffic control for the installation crew: cones, signs and a shadow vehicle on the shoulder": { price: [800, 3000], labor: 0.6, basis: "est", q: 1 },
      "Sign fabrication: 0.080 in. or 0.100 in. aluminum blanks with ASTM D4956 Type XI prismatic sheeting (Type IX where specified), digitally printed or cut legend, anti-graffiti overlay where required": { price: [90, 260], labor: 0.25, basis: "derived", q: 25, note: "4-9 sqft sign at WisDOT $21-$31/sqft; Type XI sheeting at the high end" },
      "Removal of the existing signs and posts, salvaged to the owner or recycled": { price: [30, 90], labor: 0.8, basis: "src", note: "WisDOT removing signs $27-$34 ea, small sign supports $28-$34 ea" },
      "Post foundations: driven anchor sleeves or concrete footings sized for the sign area and wind load": { price: [50, 180], labor: 0.55, basis: "est", q: 22, note: "driven anchor sleeve at the low end, concrete footing at the high end" },
      "Breakaway posts: 2 in. square perforated steel telescoping posts or U-channel with a breakaway coupler, or 4x4 timber in the anchor": { price: [80, 200], labor: 0.35, basis: "derived", q: 22, note: "WisDOT 2x2 in. tubular steel posts $190-$243 ea installed with anchor" },
      "Multi-post and large-sign supports: 3 in. or 4 in. square tube or W-beam posts in concrete foundations with slip bases": { price: [800, 3000], labor: 0.4, basis: "est" },
      "Sign mounting: signs bolted with theft-resistant hardware at 7 ft clearance (5 ft rural) and the lateral offset, stacked assemblies per the MUTCD": { price: [25, 70], labor: 0.85, basis: "est", q: 25 },
      "Overhead, mast-arm or bridge-mounted signs with the brackets and the lift": { price: [500, 2500], labor: 0.5, basis: "est", note: "sign, brackets and bucket truck; the structure itself is excluded" },
      "Street name signs and post-mounted delineators": { price: [60, 250], labor: 0.5, basis: "est" },
      "Retroreflectivity verification and a night drive inspection of every new sign": { price: [200, 700], labor: 0.95, basis: "est", q: 1 },
      "Sign inventory log with GPS location, photo and install date for the owner's asset system": { price: [200, 800], labor: 0.95, basis: "est", q: 1 },
      "Cleanup: footings backfilled and seeded, spoils removed, traffic control pulled": { price: [150, 500], labor: 0.85, basis: "est", q: 1 },
    },
  },
};
