// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "landscaping": {
    op: 0.3,
    opNote: "residential landscape install contractor",
    benchmark: {
      unit: "sqft",
      measures: "landscaped area installed (planting beds plus new lawn)",
      price: [5, 12],
      typicalQty: [1000, 3000],
      jobQty: 2000,
      minJob: 1500,
      sources: ["HomeGuide 2026: sod $1-$2/sqft installed; shrub planted $25-$85; tree planted $200-$700", "Fixr 2025: landscaping $5-$20/sqft, average job $10,000 ($8,000-$15,000)"],
    },
    steps: {
      "Utility locate (811 ticket) and flagging of irrigation lines, lighting wire and drain pipe before any digging; planting plan staked and paint-marked on the ground for the owner's walk-through": { price: [150, 400], labor: 0.9, basis: "est", q: 1, note: "811 ticket is free; foreman time to flag private lines and paint the plan" },
      "Protect existing trees, hardscape, siding and the driveway: fencing at the drip line, plywood over pavers and mats under equipment traffic": { price: [250, 700], labor: 0.55, basis: "est", q: 1, note: "drip-line fencing, plywood and mat rental; scales with the site" },
      "Remove existing lawn, overgrown shrubs, groundcover and weeds by sod cutter and hand, roots included; green waste hauled to a composting facility": { price: [0.75, 2], labor: 0.7, basis: "derived", note: "HomeGuide resod $1.50-$4.00/sqft less new sod $1-$2/sqft; overgrown shrubs and roots at the high end" },
      "Rough grade the planting areas to drain away from the foundation (minimum 2% for the first 10 ft) with a skid steer and hand raking": { price: [0.35, 0.9], labor: 0.75, basis: "est", q: 2000, note: "skid steer counted as material; cut/fill with imported soil is priced by the cu yard" },
      "Soil amendment: till 2-3 in. of screened compost into the top 6-8 in. of the beds and lawn areas, or import screened topsoil where the native soil is unworkable": { price: [65, 115], labor: 0.45, basis: "derived", q: 15, note: "screened compost $30-$55/cu yd delivered plus about one crew-hour per yard to spread and till" },
      "Steel or aluminum bed edging, 4 in. tall, pinned in place with stakes every 30 in., or a spade-cut natural edge along the bed lines": { price: [3.5, 8], labor: 0.5, basis: "derived", q: 160, note: "steel edging $2.50-$4/ft at supply plus install; a spade-cut edge runs $1-$2/ft" },
      "Trees supplied and planted: caliper or container size stated, root flare set at grade, pit dug two to three times the root ball, backfilled with native soil, water basin formed, staked and guyed for the first season": { price: [250, 700], labor: 0.35, basis: "src", q: 2, note: "HomeGuide 2026: $200-$700 to plant a tree; 15 gal or 1.5-2 in. caliper" },
      "Shrubs supplied and planted by container size (1, 3, 5 or 15 gal) as scheduled on the plan, spaced for mature size, with a slow-release starter fertilizer": { price: [40, 95], labor: 0.35, basis: "derived", q: 25, note: "HomeGuide $25-$85 per shrub planted; blended 3 and 5 gal; 15 gal runs $175-$300" },
      "Perennials, ornamental grasses and groundcover supplied and planted from 1 gal or 4 in. pots at the plan spacing, bed watered in the day of planting": { price: [12, 28], labor: 0.45, basis: "derived", q: 60, note: "1 gal perennial $10-$18 at the nursery plus planting; 4 in. pots at the low end" },
      "Weed barrier fabric under stone or bark areas only (not under planted beds), overlapped 6 in. and pinned": { price: [0.4, 0.9], labor: 0.5, basis: "est" },
      "Mulch: 3 in. of shredded hardwood or bark supplied and spread in every bed, pulled back from trunks and stems, or decorative stone at the stated size and depth": { price: [65, 130], labor: 0.5, basis: "derived", q: 7.5, note: "HomeGuide $0.50-$1.25/sqft installed at 3 in. (about 108 sqft per cu yd); decorative stone runs $100-$200/cu yd" },
      "Lawn: finish-grade, rake and roll the soil, then sod laid in staggered rows with tight seams and rolled, or hydroseed or drill-seed at the stated blend with straw or paper mulch cover": { price: [1.1, 2.1], labor: 0.5, basis: "src", q: 1200, note: "HomeGuide 2026: sod installed $1-$2/sqft; hydroseed runs about half" },
      "Irrigation coordination: drip lines and emitters run to every new tree and shrub, spray heads adjusted to the new lawn line, controller schedule set for establishment watering": { price: [150, 450], labor: 0.65, basis: "est", note: "per irrigation zone reworked" },
      "Boulders or landscape accent stone placed by mini-excavator, buried one-third for a natural set": { price: [200, 600], labor: 0.45, basis: "est", note: "1-2 ton boulder delivered and set" },
      "Low-voltage landscape lighting: transformer, wire, path and uplight fixtures placed and aimed at night": { price: [200, 450], labor: 0.45, basis: "est", note: "per fixture, transformer and wire spread over the fixtures" },
      "Initial watering-in of all plantings and sod, a written establishment watering schedule and a walk-through with the owner": { price: [150, 400], labor: 0.9, basis: "est", q: 1 },
      "Final cleanup: hardscape blown and washed, excess soil and green waste hauled off, pots and stakes removed, protection taken down": { price: [300, 800], labor: 0.6, basis: "est", q: 1, note: "includes one green-waste or soil load; scales with job size" },
      "Establishment maintenance: weekly visits for the first 30-90 days covering watering checks, weeding, mowing the new lawn and replacing plants that fail under the warranty": { price: [450, 1200], labor: 0.85, basis: "est", note: "scales with the period: about $60-$100 per weekly visit" },
    },
  },
  "hardscape": {
    op: 0.3,
    opNote: "residential hardscape specialty contractor",
    benchmark: {
      unit: "sqft",
      measures: "paver patio area installed",
      price: [13, 25],
      typicalQty: [200, 600],
      jobQty: 400,
      minJob: 2500,
      sources: ["HomeGuide 2026: paver patio $10-$17/sqft installed (materials $4-$6, labor $6-$11)", "American Paving Design 2025: patios, walks and pool decks $10-$25/sqft installed", "Fixr 2025: segmental retaining wall $15-$35/sqft of face, labor from $15/sqft"],
    },
    steps: {
      "Layout and grade shots: string lines and stakes set from the plan, finished elevations shot with a laser to confirm slope away from the house (1/8 to 1/4 in. per ft) and step rises": { price: [200, 500], labor: 0.95, basis: "est", q: 1 },
      "Utility locate (811) and marking of irrigation, lighting and drain lines; lawn, driveway and neighboring surfaces protected with plywood and mats": { price: [150, 450], labor: 0.6, basis: "est", q: 1 },
      "Demolition and haul-away of the existing concrete, pavers, deck or lawn in the footprint, broken up by skid steer and jackhammer and hauled to a recycler": { price: [2, 5], labor: 0.55, basis: "derived", note: "concrete patio broken out and hauled; a lawn-only strip runs $1-$2/sqft" },
      "Excavation of the footprint to the full base depth (typically 7-9 in. for patios, 12 in. or more for driveways) plus 6 in. beyond the edges, spoils stockpiled or hauled off": { price: [40, 80], labor: 0.45, basis: "est", q: 12, note: "mini-excavator or skid steer dig plus haul-off and dump fees" },
      "Subgrade compacted with a plate compactor and non-woven geotextile separation fabric laid over the soil, overlapped 12 in.": { price: [0.4, 0.9], labor: 0.5, basis: "est", q: 420 },
      "Crushed aggregate base (3/4-minus with fines) supplied, placed and compacted in 3-4 in. lifts to the stated total depth, screeded to the finished slope": { price: [75, 125], labor: 0.4, basis: "derived", q: 9, note: "3/4-minus $30-$50/ton delivered at about 1.4 tons per compacted cu yd, plus placing and compaction" },
      "Retaining wall: leveling pad of compacted 3/4 crushed stone, segmental block courses set level and glued, 4 in. perforated drain pipe behind the base course, 12 in. of clean drainage stone backfill wrapped in fabric, geogrid at the layers the height requires": { price: [28, 55], labor: 0.5, basis: "src", note: "per sqft of wall face with drainage and geogrid; Fixr segmental $15-$35, HomeGuide concrete walls $15-$45; engineered walls over 4 ft cost more" },
      "Seat wall, pillar or step block units set on the base and glued with a masonry adhesive, wall caps cut and adhered": { price: [60, 130], labor: 0.5, basis: "est", note: "seat wall 18-24 in. high with caps" },
      "Bedding layer: 1 in. of concrete sand or 1/4 in. chip screeded over the base": { price: [0.4, 0.9], labor: 0.7, basis: "est", q: 400 },
      "Pavers supplied and laid in the stated pattern and color (manufacturer, style and thickness stated), soldier-course border, cuts made with a wet saw": { price: [6.5, 11], labor: 0.45, basis: "derived", q: 400, note: "HomeGuide paver material $4-$6/sqft plus laying, border and cuts" },
      "Edge restraint: rigid PVC or aluminum paver edging spiked every 8-12 in. along every unsupported edge, or a concrete toe": { price: [3, 6], labor: 0.5, basis: "derived", q: 60, note: "PVC or aluminum edge $1-$1.50/ft plus spikes and install" },
      "Polymeric sand swept into the joints, plate-compacted through a pad, misted and set": { price: [0.8, 1.6], labor: 0.4, basis: "derived", q: 400, note: "polymeric sand $30-$45 per 50 lb bag at 40-60 sqft per bag plus sweep and compaction" },
      "Surface drainage: channel drain, catch basin and solid 4 in. PVC pipe run to daylight, a dry well or the storm connection": { price: [25, 60], labor: 0.55, basis: "est", note: "channel drain sections at the high end, solid pipe runs at the low end" },
      "Conduit sleeves under the pavers for future lighting, gas or irrigation lines": { price: [60, 180], labor: 0.6, basis: "est", note: "per sleeve" },
      "Fire pit, outdoor kitchen base or built-in grill enclosure built from wall block or CMU with the cap and vent stated": { price: [1500, 5000], labor: 0.45, basis: "est", note: "block fire pit $1,500-$2,500; grill-island base $3,000-$6,000 without appliances" },
      "Low-voltage lighting in the wall caps, step risers and along the path, transformer and wire included": { price: [180, 400], labor: 0.45, basis: "est", note: "per fixture, transformer and wire spread over the fixtures" },
      "Backfill and restoration of the lawn and beds disturbed at the edges with topsoil and sod or seed": { price: [1.5, 3.5], labor: 0.55, basis: "est", q: 120, note: "narrow strips along the new edges" },
      "Final cleanup: surface washed, excess base and spoils hauled off, equipment removed, walk-through and the manufacturer's paver warranty registered": { price: [250, 600], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "irrigation-contractor": {
    op: 0.3,
    opNote: "residential irrigation specialty trade",
    benchmark: {
      unit: "unit",
      measures: "irrigation zones installed (whole system spread per zone)",
      price: [800, 1600],
      typicalQty: [4, 8],
      jobQty: 6,
      minJob: 1500,
      sources: ["HomeGuide 2026: $600-$2,000 per zone; $3,000-$10,000 for a 1/4-acre lawn", "LawnLove 2025: $590-$1,340 per zone; drip $225-$900 per zone", "Fixr 2025: 5 zones $3,250-$6,000; 7 zones $4,550-$7,000"],
    },
    steps: {
      "Site walk and water test: static and working pressure measured at the hose bib or meter, flow available in gallons per minute, soil type noted and the property sketched into a zone map by plant type and sun exposure": { price: [100, 300], labor: 0.95, basis: "est", q: 1, note: "design walk, flow test and zone map" },
      "Utility locate (811) and marking of gas, electric, phone and cable before trenching; lawn and beds photographed for restoration": { price: [60, 150], labor: 0.95, basis: "est", q: 1, note: "811 ticket is free; crew time to mark and photograph" },
      "Permit and backflow registration with the water purveyor, and the inspection scheduled": { price: [50, 250], labor: 0, fee: true, basis: "src", q: 1, note: "irrigation or plumbing permit and backflow registration; LawnLove 2025: permits $42-$200" },
      "Point of connection: tee into the main after the meter or off the house supply with a brass ball valve and a Schedule 80 PVC riser": { price: [200, 450], labor: 0.6, basis: "est", q: 1 },
      "Backflow preventer supplied and installed at the stated type (pressure vacuum breaker or reduced-pressure assembly per the local code), with unions, a stainless enclosure and initial certification test": { price: [500, 1300], labor: 0.4, basis: "est", q: 1, note: "PVB about $500-$800; reduced-pressure assembly with a stainless enclosure $1,000-$2,000" },
      "Trenching with a vibratory plow or trencher to 12 in. for laterals and 18 in. for the mainline, lawn seams closed behind the plow": { price: [0.8, 1.6], labor: 0.65, basis: "derived", q: 1100, note: "LawnLove labor $45-$100/hr; a 2-person plow crew pulls about 1,000-1,200 ft a day, plus plow rental (counted as material)" },
      "Mainline: Schedule 40 PVC or 1 in. HDPE poly pipe from the backflow to each valve manifold, solvent-welded or barbed-and-clamped": { price: [2, 4], labor: 0.5, basis: "est", q: 150 },
      "Zone valves in a valve box: 1 in. electric solenoid valves with flow control, manifold assembly, gravel sump and a box lid at grade": { price: [120, 220], labor: 0.5, basis: "derived", q: 6, note: "per valve: valve $25-$45, box $25-$40, fittings and about an hour" },
      "Lateral lines: Class 200 PVC or poly pipe from each valve to the heads, sized so the zone runs within the available flow": { price: [0.55, 1.2], labor: 0.6, basis: "est", q: 1000 },
      "Spray and rotor heads: 4 in. or 6 in. pop-up bodies on swing joints, matched-precipitation nozzles set head-to-head for the lawn areas": { price: [25, 45], labor: 0.55, basis: "derived", q: 35, note: "per head: head $5-$20 (LawnLove) plus swing joint, nozzle and install" },
      "Drip zones for beds and trees: pressure regulator and filter at the valve, 1/2 in. drip tubing, inline emitter tubing or point emitters at every plant, ending in flush caps": { price: [300, 800], labor: 0.55, basis: "src", q: 1, note: "per drip zone, valve priced in step 7; LawnLove 2025: drip $225-$900 per zone" },
      "Wire: multi-strand direct-burial valve wire in the mainline trench, waterproof connectors at every valve": { price: [0.5, 1.1], labor: 0.5, basis: "est", q: 200 },
      "Controller: weather-based smart controller (WaterSense listed) mounted and wired, or the owner's existing controller connected, with a wireless rain or soil-moisture sensor": { price: [300, 700], labor: 0.35, basis: "derived", q: 1, note: "Fixr smart controller $200-$500 plus rain or soil sensor $17-$75 (LawnLove) and install" },
      "Master valve and flow sensor at the point of connection so the controller shuts the system down on a break": { price: [350, 800], labor: 0.4, basis: "est" },
      "Sleeving under walks and driveways: Schedule 40 PVC sleeves bored or trenched across the pavement": { price: [10, 30], labor: 0.7, basis: "est", note: "short bores under a walk or drive" },
      "Flush every line before heads go on, pressure-test the mainline, adjust every head's arc and radius, program run times by zone and teach the owner the controller": { price: [150, 400], labor: 0.95, basis: "est", q: 1 },
      "Trench restoration: settle and tamp the seams, topsoil where needed, sod or seed patches where the plow lifted the lawn": { price: [150, 450], labor: 0.6, basis: "est", q: 1, note: "scales with trench footage" },
      "As-built zone map with valve locations left with the owner, plus the first-season winterization or spring startup": { price: [100, 250], labor: 0.9, basis: "derived", q: 1, note: "Fixr winterization $75-$150 plus the as-built map" },
    },
  },
  "asphalt-paving": {
    op: 0.25,
    opNote: "residential and small-lot paving contractor",
    benchmark: {
      unit: "sqft",
      measures: "new asphalt driveway area on a new base",
      price: [6, 12],
      typicalQty: [400, 1200],
      jobQty: 800,
      minJob: 2000,
      sources: ["HomeGuide 2026: asphalt driveway $5-$12/sqft installed; 20x20 ft $2,000-$4,800", "HomeAdvisor 2025: new asphalt driveway $7-$13/sqft; average job $5,347; hot mix $100-$200/ton"],
    },
    steps: {
      "Site measure and grade check: area shot with a wheel and laser, drainage direction confirmed to the street or a catch basin, soft spots probed and marked": { price: [100, 300], labor: 0.95, basis: "est", q: 1 },
      "Utility locate (811) and marking of gas, water and sprinkler lines in the paving footprint; garage, walks and lawn edges protected": { price: [100, 250], labor: 0.85, basis: "est", q: 1 },
      "Traffic control and phasing: cones, barricades and signs so the lot stays partly open, or the driveway blocked for the cure period": { price: [200, 800], labor: 0.5, basis: "est", note: "driveway barricades at the low end; lot phasing with signs and cones at the high end; scales with lot size" },
      "Remove the existing asphalt or concrete to full depth with a skid steer and breaker, loaded and hauled to an asphalt recycler (thickness stated)": { price: [1, 2], labor: 0.45, basis: "src", note: "HomeAdvisor 2025: removal $1-$2/sqft" },
      "Milling the existing asphalt surface at the stated depth with millings hauled off or left for the owner": { price: [0.4, 1.25], labor: 0.3, basis: "derived", note: "public bids run $10-$25/sq yd for plane plus 2 in. overlay (repo utility data); small jobs carry the mill's mobilization" },
      "Subgrade preparation: cut or fill to the design grade, proof-roll with a loaded truck, and undercut and replace soft areas with crushed stone": { price: [0.6, 1.6], labor: 0.45, basis: "est", q: 800 },
      "Aggregate base: 3/4-minus crushed stone supplied, spread and compacted in lifts to the stated depth (typically 6-8 in. for driveways, 8-12 in. for lots; tonnage named)": { price: [55, 100], labor: 0.3, basis: "derived", q: 15, note: "crushed stone $30-$50/ton (PriceBook) at 1.4-1.5 tons per cu yd plus spreading and compaction" },
      "Fine grading and compaction of the base to a smooth, tight surface at the finished slope, with a vibratory roller": { price: [0.25, 0.6], labor: 0.55, basis: "est", q: 800 },
      "Tack coat: SS-1h emulsion sprayed on the milled or existing surface and against every joint, curb and gutter edge before paving": { price: [0.1, 0.25], labor: 0.35, basis: "est" },
      "Binder (base) course: hot-mix asphalt at the stated compacted depth (typically 2-2.5 in.), machine-laid with a paver and the tonnage named": { price: [1.75, 3.25], labor: 0.3, basis: "derived", note: "HomeAdvisor hot mix $100-$200/ton at about 73 sqft per ton for 2.25 in., plus paver crew; lots over 10,000 sqft run lower" },
      "Surface course: hot-mix asphalt at the stated compacted depth (typically 1.5-2 in.) with the mix type and tonnage named, laid by paver at 275-300 deg F": { price: [2.25, 4], labor: 0.35, basis: "derived", q: 800, note: "HomeAdvisor hot mix $100-$200/ton at about 82 sqft per ton for 2 in., plus small-job lay-down; lots over 10,000 sqft run $1.25-$2.25" },
      "Compaction: steel-drum breakdown and finish rolling plus a rubber-tire roller on lots, hand-tamped at edges and around structures": { price: [0.15, 0.4], labor: 0.5, basis: "est", q: 800 },
      "Edging: 45-degree cut and tamped asphalt edge, or a hand-laid asphalt curb along the drive": { price: [1.5, 4], labor: 0.7, basis: "est", q: 130, note: "tamped edge; a hand-laid asphalt curb runs $8-$15/ft" },
      "Transitions: saw-cut butt joints at the street, garage apron and walks, matched to the existing elevation": { price: [4, 10], labor: 0.6, basis: "derived", q: 30, note: "saw-cut $1.50-$3/ft (public bids, repo) plus the keyed butt joint" },
      "Manholes, valve boxes and catch-basin frames raised to the new grade with riser rings": { price: [300, 900], labor: 0.55, basis: "est", note: "valve boxes at the low end, manholes at the high end" },
      "Striping: stalls, ADA spaces, arrows and stop bars in traffic paint after the surface cures": { price: [0.25, 0.6], labor: 0.6, basis: "src", note: "4 in. lines $0.20-$1.00/ft, most $0.20-$0.50 (striping guides 2025-2026); symbols as foot equivalents" },
      "Sealcoat option: two coats of asphalt-emulsion sealer applied after the new asphalt cures 90 days or more": { price: [0.18, 0.4], labor: 0.55, basis: "derived", note: "commercial sealcoat $0.14-$0.25/sqft; small driveways hit a $250-$400 minimum" },
      "Cleanup, backfill of the edges with topsoil, seed where the lawn was disturbed, and the cure and use instructions left with the owner": { price: [150, 450], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "pool-spa": {
    op: 0.3,
    opNote: "residential pool builder managing subs",
    benchmark: {
      unit: "sqft",
      measures: "pool water surface area (gunite pool, deck, fence and equipment included)",
      price: [120, 260],
      typicalQty: [300, 500],
      jobQty: 400,
      minJob: 35000,
      sources: ["HomeGuide 2026: gunite pool $100-$250/sqft, $50,000-$120,000", "Fixr 2025: concrete pool $50,000-$90,000 (12x24 shotcrete, tiled, basic equipment $60,000); built-in gunite $100.50-$278/sqft", "Pool Research 2024: 14x28 concrete pool about $60,000 ($30,000-$150,000)"],
    },
    steps: {
      "Layout and permits: pool outlined on the ground from the engineered plan, setbacks and utility easements checked, building, electrical, plumbing and barrier permits pulled and the HOA approval filed": { price: [800, 2500], labor: 0.3, basis: "derived", q: 1, note: "mostly permit fees (MySitePlan 2026: permits $450-$1,800) plus layout and HOA filing" },
      "Utility locate (811), access route protection with plywood and mats, temporary fence, and a soils report or bore where the jurisdiction requires it": { price: [700, 2200], labor: 0.35, basis: "est", q: 1, note: "a soils report adds $1,000-$2,500 where required" },
      "Excavation of the pool shape and depths with an excavator, over-dig for the shell and plumbing, spoils hauled off or spread on site": { price: [20, 50], labor: 0.4, basis: "derived", q: 100, note: "dig plus haul-off; MySitePlan 2026: excavation and site prep $500-$4,500 per pool, about 80-110 cu yd for a 400 sqft pool" },
      "Steel: #3 and #4 rebar grid at the engineered spacing (typically 12 in. o.c. walls, 6 in. o.c. in beams and steps) tied and held off the soil on dobies": { price: [2.5, 5], labor: 0.55, basis: "est", q: 830, note: "per sqft of shell surface (floor plus walls)" },
      "Plumbing loops: Schedule 40 PVC suction, return and skimmer lines, main drains with VGB-compliant covers, spa jets and air lines, pressure-tested and held under pressure through the shell work": { price: [10, 20], labor: 0.6, basis: "est", q: 350, note: "per foot of pipe; a basic pool runs 300-400 ft" },
      "Electrical rough and bonding: #8 bare copper bonding grid tied to the steel, conduit for lights and the equipment feed, panel or subpanel per NEC 680": { price: [2500, 6000], labor: 0.6, basis: "est", q: 1, note: "bonding, light conduit, equipment feed and subpanel" },
      "Shotcrete or gunite shell shot to the engineered thickness (typically 6 in. floors, 8 in. walls, 12 in. beam), troweled to shape and water-cured 7 days": { price: [14, 24], labor: 0.45, basis: "est", q: 830, note: "per sqft of shell surface; a 400 sqft pool has about 800-850 sqft of shell" },
      "Equipment pad and equipment set: variable-speed pump, cartridge or DE filter, gas or heat-pump heater, salt chlorine generator and automation panel, plumbed on a concrete pad": { price: [8000, 15000], labor: 0.2, basis: "derived", q: 1, note: "package: VS pump $700-$1,300, filter $500-$2,000, heater $3,450-$5,450 (Fixr), plus salt system and automation" },
      "Waterline tile: 6 in. glass or porcelain tile set in thinset over the beam, grouted, with the spa spillway and step markers tiled": { price: [25, 55], labor: 0.6, basis: "est", q: 82, note: "porcelain at the low end, glass at the high end" },
      "Coping: precast, travertine or poured-in-place bullnose at the stated material, set on the beam with a mastic expansion joint at the deck": { price: [30, 65], labor: 0.5, basis: "est", q: 82 },
      "Deck: broom-finish concrete, pavers or travertine at the stated area with a 1/4 in. per ft slope away from the pool": { price: [9, 18], labor: 0.5, basis: "derived", q: 600, note: "broom-finish concrete; MySitePlan 2026: pool deck $3,000-$20,000; pavers or travertine run $15-$30/sqft" },
      "Backfill around the shell with the excavated soil in lifts and compacted; utility trenches to the equipment pad closed": { price: [30, 60], labor: 0.55, basis: "est", q: 15 },
      "Pool lights, water features, deck jets and the spa blower installed and wired": { price: [600, 1800], labor: 0.35, basis: "src", note: "per light or feature; MySitePlan 2026: lighting $450-$1,800" },
      "Plaster or pebble interior finish applied over the cured shell at the stated product and color, brushed and acid-washed as the product requires": { price: [5, 10], labor: 0.55, basis: "src", q: 830, note: "per sqft of interior surface; Pool Research 2024: plaster $4-$10/sqft; white plaster at the low end, quartz or pebble at the high end" },
      "Safety barrier: 4 ft fence with self-closing, self-latching gates, door alarms or a safety cover to the pool barrier code": { price: [30, 60], labor: 0.45, basis: "derived", q: 110, note: "Fixr pool fence $3,000-$10,000, MySitePlan $1,500-$10,000; 4 ft aluminum with self-closing gates" },
      "Fill and startup: water delivered or hose-filled, chemistry balanced daily during the 28-day plaster cure, pump and filter started, automation programmed": { price: [700, 1800], labor: 0.55, basis: "est", q: 1, note: "water delivery, when needed, at the high end" },
      "Inspections at pre-gunite steel, bonding and rough plumbing, pre-plaster and final, with the barrier inspection signed off": { price: [250, 700], labor: 0.9, basis: "est", q: 1, note: "the builder's scheduling and attendance; inspection fees are in the permits (step 0)" },
      "Pool school: owner walked through the equipment, chemistry and cleaning, manufacturer warranties registered, site cleaned and access route restored": { price: [400, 1200], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "snow-removal": {
    op: 0.25,
    opNote: "commercial snow contractor; standby and weather risk",
    benchmark: {
      unit: "sqft",
      measures: "paved lot area served for one season (about 10 pushes and 15 salt runs)",
      price: [0.12, 0.3],
      typicalQty: [20000, 80000],
      jobQty: 50000,
      minJob: 150,
      sources: ["HomeGuide 2026: commercial lots $50-$200/hr; salting $150-$350 per acre", "Trillium 2026: seasonal contracts $2,000-$10,000; lots over 50,000 sqft $300-$600+ per event", "LawnLove 2026: about $6,000 per season for a 50-space lot"],
    },
    steps: {
      "Pre-season site walk and mapped plan: plow routes, snow stacking zones, priority areas (entrances, fire lanes, ADA stalls), curb and island hazards and the trigger depth and response time written up": { price: [250, 600], labor: 0.95, basis: "est", q: 1 },
      "Marker stakes at curbs, islands, hydrants, drains and landscape edges before the first freeze, pulled in spring": { price: [3, 8], labor: 0.6, basis: "est", q: 50, note: "per stake, set in fall and pulled in spring" },
      "Pre-treatment: liquid brine or salt applied to the lot and walks ahead of a forecast event so ice does not bond": { price: [0.002, 0.005], labor: 0.35, basis: "est", note: "per sqft per application; brine about $90-$220 per acre" },
      "Lot plowing at the stated trigger depth (typically 2 in.) with trucks or a loader with a pusher box, snow stacked in the mapped zones, per push": { price: [0.0035, 0.008], labor: 0.5, basis: "src", q: 500000, note: "per sqft per push ($150-$350 per acre per push, snow guides 2025-2026); a season's quantity is lot area times pushes" },
      "Drive lanes, entrances and fire lanes plowed open on the priority pass and reopened during the event at the stated interval": { price: [0.003, 0.007], labor: 0.5, basis: "est", note: "per sqft per priority pass" },
      "Sidewalks, entrances and steps cleared with a walk-behind blower and shovels, to the stated width and within the response time": { price: [0.12, 0.3], labor: 0.9, basis: "derived", q: 4000, note: "per foot per event; $25-$75/hr walk crews (Trillium, LawnLove) at about 300-500 ft per hour" },
      "Bulk rock salt applied to the lot and drive lanes with a spreader after plowing, per application": { price: [0.0035, 0.008], labor: 0.3, basis: "src", q: 750000, note: "per sqft per application; HomeGuide salting $150-$350 per acre" },
      "Calcium chloride or a treated ice melt applied to walks, steps and entrances, per application": { price: [0.12, 0.3], labor: 0.45, basis: "derived", q: 6000, note: "per foot per application on a 4-6 ft walk; Trillium walkway treatments $20-$50 per application" },
      "Loader relocation of stacked snow within the site when the stacking zones fill": { price: [175, 300], labor: 0.4, basis: "src", note: "loader with operator; HomeGuide about $280/hr" },
      "Off-site hauling: snow loaded into dump trucks and hauled to an approved disposal site": { price: [300, 650], labor: 0.4, basis: "est", note: "loader plus 1-2 dump trucks; disposal-site fees passed through" },
      "Return visits for drifting and refreeze, and clearing behind the plow at drive-lane ends after the municipal plow passes": { price: [85, 150], labor: 0.55, basis: "src", note: "plow truck; Trillium 2026 $50-$150/hr, LawnLove lots $45-$155/hr" },
      "Per-event service log: start and end times, depths, materials used and photos, delivered after every event": { price: [150, 500], labor: 0.95, basis: "est", q: 1, note: "season total for about 10-15 events" },
      "Spring cleanup: salt residue swept, stakes pulled, turf and curb damage from plowing repaired": { price: [400, 1200], labor: 0.75, basis: "est", q: 1, note: "scales with lot size" },
    },
  },
  "tree-removal": {
    op: 0.3,
    opNote: "residential tree service; high insurance overhead",
    benchmark: {
      unit: "unit",
      measures: "trees removed (mixed sizes), per tree all-in",
      price: [500, 1500],
      typicalQty: [1, 3],
      jobQty: 2,
      minJob: 300,
      sources: ["HomeGuide 2026: tree removal $400-$1,200 per tree on average, $200 small to $3,000 large", "Fixr 2025: $400-$1,100 per tree; 30-60 ft $450-$700; debris haul-off $150-$300 extra"],
    },
    steps: {
      "Arborist assessment: each tree tagged, species, DBH, height, lean, decay and target hazards noted, and the removal or pruning method chosen per tree": { price: [35, 100], labor: 1, basis: "est", q: 2, note: "per tree; many firms fold it into a free estimate (Fixr arborist visit $40-$450)" },
      "Tree removal permit or heritage-tree application with the city, and the notice to neighbors where a tree overhangs the line": { price: [60, 250], labor: 0, fee: true, basis: "src", note: "Fixr: permits $60-$150; heritage-tree applications run higher" },
      "Utility clearance: 811 locate for the drop zone and the power company's line drop or de-energizing scheduled": { price: [150, 500], labor: 0.6, basis: "est" },
      "Site protection: plywood on the lawn and driveway under the drop zone, fencing and roof, gutter and neighbor's property shielded": { price: [100, 350], labor: 0.8, basis: "est", q: 1 },
      "Traffic control on the street: cones, signs and a flagger while the crane, chipper or drop zone is in the road": { price: [400, 1200], labor: 0.75, basis: "derived", note: "one flagger day plus signs; flaggers $45-$80/hr (repo public bid data)" },
      "Small tree removal (under 12 in. DBH): felled or dismantled from the ground and chipped on site": { price: [200, 550], labor: 0.7, basis: "src", q: 1, note: "HomeGuide small tree $200-$600; Fixr up to 30 ft $150-$400" },
      "Medium tree removal (12-24 in. DBH): climbed and dismantled in sections with rigging, limbs lowered to the drop zone": { price: [600, 1300], labor: 0.7, basis: "src", q: 1, note: "HomeGuide 30-60 ft $450-$1,200; Fixr $450-$700" },
      "Large tree removal (over 24 in. DBH): climbed or bucket-truck dismantled with rigging blocks and a lowering line, trunk cut in rounds": { price: [1300, 3000], labor: 0.7, basis: "src", note: "HomeGuide 65-85 ft $1,800-$3,500; Fixr 60-100 ft $900-$1,200, over 100 ft $1,300-$2,000" },
      "Crane-assisted removal: sections picked over the house or a tight yard by a crane sized to the picks, with a certified operator and signal person": { price: [250, 550], labor: 0.3, basis: "derived", note: "crane with operator and signal person; HomeGuide crane about $500 added; 4-hr minimum typical" },
      "Pruning: crown cleaning, deadwood removal, raising or thinning per ANSI A300 with no topping, cuts made outside the branch collar": { price: [300, 800], labor: 0.85, basis: "est", note: "per tree, medium shade tree" },
      "Brush and limbs chipped through a drum chipper and hauled off, or chips left on site at the owner's request": { price: [150, 400], labor: 0.55, basis: "src", q: 1, note: "Fixr: tree debris removal $150-$300" },
      "Logs bucked to length and hauled to a recycler or mill, or cut to firewood length and stacked on site": { price: [100, 400], labor: 0.65, basis: "derived", q: 1, note: "Fixr wood splitting about $100; log haul and tipping fees" },
      "Stump grinding to 6-8 in. below grade with a self-propelled grinder, grindings raked into the hole": { price: [120, 350], labor: 0.7, basis: "src", note: "HomeGuide $120-$400 first stump; Fixr $100-$500" },
      "Rake and blow the site, repair ruts in the lawn from the equipment, remove the protection": { price: [75, 250], labor: 0.9, basis: "est", q: 1 },
      "Certificate of insurance for the owner, and the permit's replacement-tree condition met with a new tree planted": { price: [250, 700], labor: 0.4, basis: "derived", note: "HomeGuide: $200-$700 to plant a tree" },
    },
  },
  "stump-grinding": {
    op: 0.35,
    opNote: "small owner-operator service calls",
    benchmark: {
      unit: "unit",
      measures: "stumps ground (mixed sizes), per stump all-in",
      price: [100, 250],
      typicalQty: [1, 5],
      jobQty: 3,
      minJob: 125,
      sources: ["HomeGuide 2026: $120-$400 for the first stump, $30-$60 each additional; $2-$6 per inch", "Fixr 2025: $150-$300 per job (average $200); additional stumps $40-$75; $100 minimum"],
    },
    steps: {
      "Stump count and measure: diameter taken at ground level with the flare, species and height above grade noted, and access route confirmed for the grinder width": { price: [15, 50], labor: 1, basis: "est", q: 1 },
      "Utility locate (811) and a private locate for irrigation, lighting and drain lines around each stump before grinding": { price: [25, 90], labor: 0.9, basis: "est", q: 1, note: "811 is free; time to call it in and flag private lines with the owner" },
      "Access protection: plywood or mats over the lawn, walk and driveway on the grinder's route; fence panel removed and reset": { price: [75, 250], labor: 0.8, basis: "est" },
      "Cut the stump flush to the ground with a chainsaw where it stands above 6 in.": { price: [20, 60], labor: 0.95, basis: "est" },
      "Grinding of stumps up to 12 in. across, to 6-8 in. below grade with a self-propelled grinder": { price: [35, 80], labor: 0.65, basis: "src", q: 1, note: "Fixr up to 12 in. $40-$75; HomeGuide $2-$6 per inch" },
      "Grinding of stumps 12-24 in. across, to 8-12 in. below grade with a track grinder": { price: [60, 140], labor: 0.65, basis: "src", q: 2, note: "Fixr medium $75-$150; HomeGuide $2-$6 per inch" },
      "Grinding of stumps over 24 in. across, to 12 in. or more below grade, in passes with the grinder repositioned around the flare": { price: [175, 400], labor: 0.65, basis: "src", note: "HomeGuide extra-large stumps $300-$800; Fixr large $150-$250" },
      "Surface roots chased and ground beyond the stump to the stated distance for a replanting or a lawn": { price: [6, 15], labor: 0.7, basis: "derived", note: "Fixr root grinding $100-$200/hr at about 12-20 ft per hour" },
      "Grindings raked back into the hole and mounded to settle, or loaded and hauled off": { price: [15, 60], labor: 0.7, basis: "derived", q: 1.75, note: "raked back at the low end; loaded and hauled at the high end (Fixr cleanup $2-$3 per inch of stump)" },
      "Screened topsoil supplied and placed in the hole after the grindings are removed, tamped and graded to match the lawn": { price: [60, 120], labor: 0.5, basis: "est" },
      "Seed and straw or a sod patch over the filled hole, watered in": { price: [1.5, 4], labor: 0.6, basis: "est" },
      "Site raked and blown, rut repair on the access route and the protection removed": { price: [35, 90], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "erosion-control": {
    op: 0.2,
    opNote: "commercial site specialty subcontractor",
    benchmark: {
      unit: "linear ft",
      measures: "perimeter silt fence length, the site's other BMPs spread over it",
      price: [15, 35],
      typicalQty: [300, 1200],
      jobQty: 750,
      minJob: 500,
      sources: ["HomeGuide and Angi 2026: silt fence $3-$7/linear ft installed, average job $835; $500 minimums", "MnDOT average bids 2014 (MN Stormwater Manual): silt fence $1.99-$2.58/ft; straw and compost logs $2.58-$2.90/ft"],
    },
    steps: {
      "SWPPP or erosion and sediment control plan review: BMP locations confirmed on site, disturbed area and discharge points walked, and the NOI or grading-permit conditions noted": { price: [250, 750], labor: 0.9, basis: "est", q: 1 },
      "Stabilized construction entrance: geotextile under 6 in. of 2-3 in. clean crushed rock, 50 ft long by the drive width, with a rumble plate or wash rack where the permit requires": { price: [1500, 3500], labor: 0.35, basis: "derived", q: 1, note: "about 25 tons of 2-3 in. stone at $30-$45/ton plus geotextile and placement; a wash rack costs more" },
      "Silt fence: woven geotextile fabric trenched 6 in. into the ground, backfilled and compacted, wire-backed on steel posts at 6 ft or hardwood stakes at 4 ft, ends turned uphill": { price: [2.5, 5], labor: 0.65, basis: "src", q: 750, note: "HomeGuide/Angi 2026 $3-$7/ft on small jobs; MnDOT 2014 bids $1.99-$2.58/ft" },
      "Fiber wattles or compost socks (9-12 in.) staked on contour at the slope toe and on the face at the stated spacing, ends overlapped": { price: [3, 6], labor: 0.5, basis: "derived", q: 200, note: "MnDOT 2014 bids: straw log $2.90/ft, compost log $2.58/ft, plus a decade of inflation" },
      "Storm-drain inlet protection: gravel bags, a filter sack or a stone-and-fabric barrier at every downstream inlet": { price: [150, 400], labor: 0.5, basis: "est", q: 3, note: "per inlet" },
      "Diversion berm or swale cut and shaped above the work area to carry clean runoff around the disturbance": { price: [4, 12], labor: 0.4, basis: "est" },
      "Sediment trap or basin excavated to the plan volume with a rock outfall and dewatering skimmer": { price: [20, 50], labor: 0.4, basis: "est", note: "per cu yd of storage; skimmer and rock outfall spread over the volume" },
      "Rock check dams in the swales: 3-6 in. stone, 2 ft high, keyed into the banks": { price: [250, 700], labor: 0.45, basis: "est", note: "per dam" },
      "Erosion control blanket (straw, straw-coconut or turf reinforcement mat) stapled on the slopes over seed, edges trenched in at the top": { price: [2.5, 5.5], labor: 0.45, basis: "derived", note: "blanket $1-$3/sq yd material plus stapling and anchor trench" },
      "Temporary seeding and straw mulch, or hydroseed with tackifier, over the disturbed area at the stated seed mix and rate": { price: [0.06, 0.16], labor: 0.45, basis: "derived", q: 54450, note: "Fixr seed $0.14/sqft; hydroseed with tackifier at the high end" },
      "Concrete washout: lined pit or a portable container with signage, pumped and disposed of when full": { price: [300, 900], labor: 0.4, basis: "est", note: "per washout, pumping and disposal included" },
      "Dust control: water truck passes on the haul roads and exposed soil": { price: [95, 160], labor: 0.4, basis: "est", note: "water truck with driver" },
      "Weekly and post-storm inspections with a written report, corrections logged and the SWPPP binder kept current": { price: [75, 140], labor: 0.95, basis: "est", q: 20, note: "certified inspector with report" },
      "Maintenance: sediment removed from behind the fence and out of the traps when it reaches half the height, damaged sections replaced, entrance rock topped up": { price: [60, 110], labor: 0.75, basis: "est", q: 16, note: "laborer with small equipment" },
      "Final stabilization and removal: permanent seed or sod established at 70% cover, BMPs pulled, fence trench filled and the NOT filed": { price: [800, 2200], labor: 0.7, basis: "est", q: 1, note: "scales with fence length and area; BMPs pulled, touch-up seed and the NOT" },
    },
  },
};
