// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "epoxy-flooring": {
    op: 0.3,
    opNote: "residential and light-commercial coating trade",
    benchmark: {
      unit: "sqft",
      measures: "floor area coated",
      price: [5, 11],
      typicalQty: [400, 1500],
      jobQty: 950,
      minJob: 1500,
      sources: ["The Garage Guide 2026: professional epoxy $3-$7/sqft installed; polyaspartic $5-$12/sqft; diamond grinding $1-$3/sqft", "JobFlex owner 2026: epoxy flake garage floor sells at about $10/sqft"],
    },
    steps: {
      "Moisture testing before the system is ordered: in-situ relative-humidity probes (ASTM F2170) or calcium-chloride tests (ASTM F1869) at the stated number of points, readings recorded on the proposal": { price: [250, 700], labor: 0.6, basis: "est", note: "3 RH probes or calcium-chloride tests with the return visit to read them; an outside lab billed at cost would be a fee" },
      "Mobilization and protection: planetary grinder, HEPA dust extractor, mixing station and generator brought in; walls, door frames, floor drains, equipment legs and adjacent finishes masked to the coating line": { price: [200, 500], labor: 0.6, basis: "est", q: 1 },
      "Removal of the existing coating, sealer or adhesive residue with PCD tooling before profiling, spent material bagged for disposal": { price: [1.25, 3], labor: 0.8, basis: "src", note: "The Garage Guide 2026: old coating removal $1-$3/sqft" },
      "Diamond grinding (or shot blasting on large open floors) to a CSP 2-3 profile under HEPA extraction, edges and columns hand-ground to the wall, floor vacuumed and wiped clean": { price: [1.25, 2.25], labor: 0.75, basis: "src", q: 950, note: "The Garage Guide 2026: diamond grinding $1-$3/sqft; non-labor share is diamond tooling plus grinder, HEPA vacuum and generator wear (true consumables about $0.15-0.35/sqft at cost)" },
      "Crack and control-joint repair: cracks chased with a crack-chasing blade, joints cleaned out, both filled with a two-part polyurea or epoxy joint filler and ground flush": { price: [3, 6], labor: 0.65, basis: "derived", q: 95, note: "about 0.1 lf per sqft of floor on a typical slab" },
      "Spall, pit and pop-out repair with a 100% solids epoxy mortar, troweled and ground flush before the primer goes down": { price: [10, 22], labor: 0.55, basis: "est", note: "per sqft of area repaired" },
      "Moisture-mitigating epoxy primer at 16 mils (rated to 100% RH or 20 lb MVER) in place of the standard primer": { price: [2, 4], labor: 0.3, basis: "derived", note: "moisture-mitigation primers add about $2-$4/sqft over a standard primer" },
      "Epoxy primer: low-viscosity 100% solids epoxy rolled into the profile at 4-6 mils to seal the slab and anchor the base coat": { price: [0.55, 1.05], labor: 0.4, basis: "derived", q: 950 },
      "Base coat: 100% solids pigmented epoxy at 10-12 mils, squeegee-applied and back-rolled, color per the selected blend": { price: [1.4, 2.4], labor: 0.4, basis: "derived", q: 950, note: "100% solids epoxy at about $65-$110/gal and 130 sqft/gal at 10-12 mils plus pigment, rolled by a 2-person crew" },
      "Full flake broadcast: 1/4 in. vinyl flake blend broadcast to rejection into the wet base coat, then scraped, sanded and vacuumed to a uniform texture after cure": { price: [1.25, 2.25], labor: 0.5, basis: "derived", note: "flake at about 0.25 lb/sqft net plus scrape, sand and vacuum" },
      "Quartz double broadcast: colored quartz aggregate broadcast to rejection into two consecutive 100% solids epoxy body coats, scraped and vacuumed between coats": { price: [3, 5.5], labor: 0.5, basis: "est", note: "both body coats and the quartz" },
      "Metallic epoxy body coat: 100% solids clear epoxy with metallic pigment at 20-25 mils, manipulated for the effect and left to self-level": { price: [3.5, 6.5], labor: 0.5, basis: "est" },
      "Grout coat: clear 100% solids epoxy at 8-10 mils to lock the broadcast and fill the texture to the specified smoothness": { price: [0.9, 1.6], labor: 0.4, basis: "derived" },
      "Top coat: clear aliphatic polyaspartic at 8-10 mils, or two-component aliphatic urethane at 3-4 mils, UV-stable and chemical-resistant, roller-applied with slip-resistant aggregate broadcast into the wet coat where specified": { price: [1.75, 3], labor: 0.35, basis: "derived", q: 950, note: "polyaspartic at about $100-$170/gal and 120-160 sqft/gal over texture; a urethane top coat is about 25% less" },
      "Cove base: 4-6 in. epoxy cove troweled at the wall-to-floor junction with a 1 in. radius, then coated in the same system as the floor": { price: [7, 14], labor: 0.7, basis: "derived", note: "cove base pricing guides 2026: about $6-$12/lf typical, $14-$20 premium" },
      "Stem walls, curbs and equipment pads coated 4-8 in. high in the floor system with a masked, straight cut line": { price: [4, 9], labor: 0.7, basis: "est" },
      "Line striping and safety markings: pigmented polyaspartic stripes 4 in. wide masked and applied over the finished floor": { price: [1, 2.5], labor: 0.7, basis: "est", note: "per lf of 4 in. stripe" },
      "Cure and return to service: foot traffic and rolling loads allowed at the stated hours for the top coat, masking removed, final inspection under raking light with any holidays or debris inclusions corrected": { price: [100, 300], labor: 0.9, basis: "est", q: 1 },
      "Final cleanup: grinding dust, spent flake and empty containers hauled off, floor wiped, and the care sheet and warranty documents handed over": { price: [150, 350], labor: 0.6, basis: "est", q: 1 },
    },
  },
  "concrete-resurfacing": {
    op: 0.3,
    opNote: "residential and light-commercial decorative flooring trade",
    benchmark: {
      unit: "sqft",
      measures: "floor area finished",
      price: [4, 10],
      typicalQty: [600, 2500],
      jobQty: 1550,
      minJob: 2000,
      sources: ["Concrete Network 2025: polished concrete $3-$12/sqft; basic $3-$5, mid-range $5-$8, high-end $8-$12+", "Concrete Network 2025: floor overlays $3-$7/sqft basic, $7-$12 mid-range, stamped $8-$20+"],
    },
    steps: {
      "Test area and mock-up: a 4 x 4 ft panel ground and finished to the proposed exposure, color and gloss for the client to approve before production": { price: [250, 600], labor: 0.8, basis: "est", q: 1 },
      "Protection and setup: walls, cabinets, door frames and drains masked, dust walls hung at open doorways, propane or electric planetary grinder and auto-scrubber brought in": { price: [300, 700], labor: 0.6, basis: "est", q: 1 },
      "Removal of carpet, tile, vinyl or mastic and any old coating with PCD and carbide tooling, residue vacuumed and hauled off": { price: [1.5, 4], labor: 0.85, basis: "derived", note: "mastic or coating removal by grinding about $1.50-$3, tile tear-out to $4" },
      "Crack chasing and control-joint filling with a semi-rigid polyurea joint filler, shaved flush after cure so the joints polish with the floor": { price: [3, 6], labor: 0.65, basis: "derived", q: 124 },
      "Spall, pit and pop-out patching with a polishable cementitious repair mortar color-matched to the slab": { price: [10, 22], labor: 0.55, basis: "est", note: "per sqft of area patched" },
      "Metal-bond grinding in stages (30/40, then 80, then 150 grit) to the specified aggregate exposure: cream, salt-and-pepper, medium or large aggregate": { price: [1.5, 3.5], labor: 0.7, basis: "derived", q: 1550, note: "about half of a Concrete Network $3-$8/sqft basic-to-mid polished floor; cream at the low end, exposed aggregate at the high end" },
      "Lithium-silicate densifier flooded onto the slab and worked in to harden and dust-proof the surface before honing": { price: [0.25, 0.6], labor: 0.4, basis: "derived" },
      "Resin-bond honing at 100, 200 and 400 grit to close the surface and remove the grinding scratch pattern": { price: [0.75, 1.5], labor: 0.7, basis: "derived" },
      "Concrete dye (water- or acetone-based) or reactive acid stain in the selected color applied between honing steps, acid stain neutralized and rinsed": { price: [1, 2.5], labor: 0.5, basis: "est" },
      "Polishing at 800, 1,500 and 3,000 grit to the specified gloss level (Level 1 flat through Level 4 high gloss)": { price: [0.75, 1.75], labor: 0.7, basis: "derived" },
      "Polymer-modified cementitious overlay: microtopping at 1/16 in., stamped overlay at 1/4-3/8 in. or self-leveling at 1/4-1/2 in., primed, poured or troweled and cured": { price: [3.5, 7.5], labor: 0.55, basis: "src", note: "Concrete Network 2025: basic overlay $3-$7/sqft" },
      "Stamped or hand-troweled texture in the overlay with release agent and the selected pattern mats": { price: [2, 5], labor: 0.8, basis: "derived", note: "stamped overlays $8-$15 less the base overlay" },
      "Decorative saw-cut scoring in the selected layout (tile, diamond or border pattern) with a 1/8 in. blade, edges eased": { price: [1.75, 4], labor: 0.85, basis: "est" },
      "Sealer or stain guard: penetrating stain protector burnished into polished concrete, or acrylic, urethane or epoxy sealer at the stated coats over overlays and stains, slip-resistant additive where specified": { price: [0.6, 1.5], labor: 0.5, basis: "derived", q: 1550, note: "penetrating guard at the low end, urethane or epoxy sealer at the high end" },
      "High-speed burnishing with a diamond-impregnated pad to bring up the final sheen and set the guard": { price: [0.15, 0.4], labor: 0.8, basis: "est" },
      "Slurry management: grinding slurry collected, solidified and disposed of at a licensed facility; floor auto-scrubbed between steps": { price: [200, 600], labor: 0.4, basis: "est", q: 1, note: "scales with floor area: about $0.15-$0.35/sqft on large floors" },
      "Final cleanup, masking removed, walkthrough with gloss and exposure checked against the approved mock-up, and a written care sheet with the recommended cleaner and re-burnish schedule": { price: [200, 500], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "wallcovering": {
    op: 0.3,
    opNote: "residential finish trade, painting-like",
    benchmark: {
      unit: "sqft",
      measures: "wall area covered",
      price: [5, 11],
      typicalQty: [200, 600],
      jobQty: 400,
      minJob: 400,
      sources: ["Homewyse 2026: hang wallpaper $4.99-$10.53/sqft incl. standard paper, supplies and labor", "HomeAdvisor 2025: wallpaper removal $0.60-$3/sqft"],
    },
    steps: {
      "Field measure and takeoff: each wall measured, openings deducted, pattern repeat and match type read from the roll label, roll or bolt count with a 10-15% waste allowance and one dye lot confirmed": { price: [50, 150], labor: 1, basis: "est", q: 1, note: "often credited against the job" },
      "Wallcovering material supplied in the client's selection: single or double rolls of paper or non-woven, 54 in. Type II commercial vinyl by the bolt, or printed mural panels, all from one dye lot": { price: [60, 140], labor: 0, basis: "derived", q: 9, note: "per double roll (about 56 sqft, about 45 sqft usable after pattern waste); a single roll is about half; a 54 in. commercial vinyl bolt runs about $150-$300" },
      "Room protection: furniture moved and covered, floors and baseboards masked, switch and outlet covers removed and bagged, ladders and drops set": { price: [60, 180], labor: 0.85, basis: "est", q: 1 },
      "Stripping existing wallcovering: face layer scored and peeled, backing softened with steam or enzyme stripper and removed, old paste washed off and the wall rinsed": { price: [1, 2.5], labor: 0.95, basis: "src", note: "HomeAdvisor 2025: removal $0.60-$3/sqft" },
      "Wall repair: nail holes, dents and seams filled, damaged paper face sealed, textured walls skim-coated with joint compound and sanded to a Level 5 finish": { price: [1.25, 3], labor: 0.85, basis: "derived", note: "skim coat and sand to Level 5" },
      "Priming with a pigmented acrylic wallcovering primer-sealer so the covering adheres evenly and strips cleanly later": { price: [0.6, 1.2], labor: 0.7, basis: "derived", q: 400 },
      "Layout: plumb line snapped at the starting corner, pattern centered on the focal wall, drop or straight match plotted so the kill seam lands in the least visible corner": { price: [40, 120], labor: 1, basis: "est", q: 1 },
      "Hanging: strips cut with the pattern matched, pasted or pre-pasted per the product (clay, clear strippable or heavy-duty vinyl adhesive), booked, hung, smoothed, seams butted and rolled, trimmed at ceiling and base": { price: [2, 4], labor: 0.9, basis: "derived", q: 400, note: "paperhangers charge about $35-$75 per single roll hung (about 25 sqft)" },
      "Commercial vinyl: 54 in. Type II strips hung with heavy-duty clay adhesive, seams double-cut and rolled, corners wrapped 6 in. and overlapped": { price: [1.5, 3], labor: 0.85, basis: "est", note: "install only; material is the bolt line" },
      "Mural or panel installation: numbered panels dry-fitted to the wall, hung in sequence with the image aligned across seams and trimmed to the opening": { price: [35, 80], labor: 0.95, basis: "est", note: "per mural panel hung" },
      "Grasscloth, silk or textured natural covering: strips reverse-hung where the product calls for it, paste kept off the face, seams left visible as the material intends": { price: [3.5, 6.5], labor: 0.9, basis: "est", note: "premium install rate in place of the standard hanging rate" },
      "Cut-outs at outlets, switches, sconces, thermostats and vents, covering trimmed tight and cover plates reinstalled": { price: [8, 20], labor: 0.95, basis: "est", q: 8 },
      "Borders and chair-rail bands hung level at the stated height with mitered corners": { price: [2, 4.5], labor: 0.85, basis: "est", note: "install only" },
      "Ceiling installation with a second installer and platform, strips hung across the short dimension": { price: [4, 7.5], labor: 0.95, basis: "est" },
      "Scaffold or platform for stairwells and walls over 10 ft, set and moved as the work advances": { price: [150, 450], labor: 0.4, basis: "est" },
      "Seam and surface inspection under raking light after the paste dries, lifted edges re-pasted and paste residue wiped from trim and ceilings": { price: [40, 120], labor: 1, basis: "est", q: 1 },
      "Cleanup: masking removed, stripped paper and trimmings bagged and hauled, leftover rolls labeled with the dye lot and left for the owner": { price: [50, 150], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "glass-glazing": {
    op: 0.25,
    opNote: "residential and light-commercial glass shop",
    benchmark: {
      unit: "unit",
      measures: "lites (glass units) replaced",
      price: [300, 700],
      typicalQty: [4, 10],
      jobQty: 7,
      minJob: 300,
      sources: ["Angi / HomeGuide 2026 cost guides: window glass replacement about $300-$650 per window", "American Window Film (undated): commercial window film $6-$18/sqft installed, solar film $6-$10"],
    },
    steps: {
      "Site survey and field measurement of every opening: daylight opening and glass size, thickness, edge bite, setting-block positions, frame condition and the existing glazing method (stops, gaskets, tape or wet seal)": { price: [100, 250], labor: 1, basis: "est", q: 1 },
      "Temporary board-up or plywood closure of broken openings, glass swept and bagged for disposal": { price: [125, 350], labor: 0.6, basis: "est", note: "per opening" },
      "Shop drawings and submittals: glazing details, glass make-up, hardware and finish samples for approval before fabrication": { price: [500, 1800], labor: 1, basis: "est" },
      "Insulated glass units fabricated to size: 1 in. overall with 1/4 in. low-E over 1/4 in. clear, argon fill and a warm-edge spacer, tempered or laminated where safety glazing is required (CPSC 16 CFR 1201 Cat II)": { price: [175, 400], labor: 0, basis: "derived", q: 7, note: "per lite of about 10-15 sqft: 1 in. low-E argon IGU about $14-$28/sqft, tempered at the high end" },
      "Monolithic glass fabricated to size: 1/4 in. to 1/2 in. tempered, laminated or annealed, edges seamed or polished as the frame requires": { price: [100, 350], labor: 0, basis: "est", note: "per lite of about 10-15 sqft" },
      "Removal of the failed unit or broken glass: sealant cut, stops or pressure plates pulled, glass lifted out with cups, old glazing tape and gaskets stripped from the rabbet": { price: [40, 100], labor: 0.95, basis: "est" },
      "Frame preparation: rabbet cleaned and dried, weep holes cleared, new setting and edge blocks placed, glazing tape or wet-glaze bead laid to the frame type": { price: [2, 4], labor: 0.85, basis: "est", q: 98, note: "per lf of glass perimeter, about 14 lf per lite" },
      "Glass set: lite lifted and set on the blocks, stops or gaskets reinstalled, pressure plates torqued or wet cap bead applied to the full perimeter": { price: [75, 160], labor: 0.9, basis: "derived", q: 7, note: "2 glaziers, 0.75-1.5 h per lite" },
      "Perimeter weather seal: backer rod and structural or weatherseal silicone (ASTM C920 Class 50) at the frame-to-substrate joint inside and out, tooled and color-matched": { price: [2, 5], labor: 0.75, basis: "derived", q: 98, note: "both faces" },
      "Interior glass partitions and office fronts: 1/2 in. tempered lites in aluminum U-channel at head and sill, joints butt-glazed with clear silicone, patch fittings and door hardware": { price: [375, 750], labor: 0.3, basis: "est", note: "per lf of wall about 9 ft high; about $45-$80/sqft" },
      "Glass railing panels: 1/2 in. tempered or laminated lites in a base shoe or standoff system with a top cap where required": { price: [200, 450], labor: 0.3, basis: "src", note: "AG Vinyl Fencing 2026: glass railing $150-$600/lf installed, most residential jobs $200-$500" },
      "Commercial door glass: 1/4 in. tempered lites in aluminum stile-and-rail doors, glazing beads and gaskets replaced, closer and pivots adjusted": { price: [325, 650], labor: 0.5, basis: "est" },
      "Window film: solar-control, safety or privacy film applied to the cleaned interior face and squeegeed to the edge": { price: [6, 12], labor: 0.55, basis: "src", note: "American Window Film (undated): solar film $6-$10/sqft; security film higher" },
      "Access equipment: boom or scissor lift, or a glazing robot and vacuum lifter for lites over 150 lb, delivered for the days of the work": { price: [700, 2000], labor: 0.1, basis: "est", note: "equipment rental and delivery for 1-3 days" },
      "Cleanup and disposal: old glass and framing scrap recycled, labels and protective film removed, both faces of the new glass cleaned": { price: [75, 200], labor: 0.6, basis: "est", q: 1 },
      "Warranty and closeout: the fabricator's insulated-glass seal warranty (10 years against fogging) and the glazing labor warranty issued in writing": { price: [25, 75], labor: 1, basis: "est", q: 1, note: "paperwork only; often absorbed" },
    },
  },
  "shower-mirror": {
    op: 0.3,
    opNote: "residential specialty glass installer",
    benchmark: {
      unit: "unit",
      measures: "frameless shower enclosures (door and panel) installed, with the vanity mirror",
      price: [1800, 3600],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 250,
      sources: ["HomeGuide 2026: frameless shower door $600-$1,900 installed (glass $400-$1,300 plus $200-$600 labor)", "Angi 2026: frameless shower door average $1,400, most $1,000-$2,500", "Homewyse 2026: mirror installed $13.86-$19.93/sqft"],
    },
    steps: {
      "Field measurement after tile is set and grouted: each panel dimension, out-of-plumb and out-of-level readings, curb pitch, ceiling height and notches, hinge side and swing agreed and marked on the tile": { price: [75, 200], labor: 1, basis: "est", q: 1 },
      "Removal of the existing shower door, frame or curtain rod, screw holes filled and the tile cleaned of old silicone": { price: [100, 225], labor: 0.9, basis: "est" },
      "Shower glass fabricated to the measurements: 3/8 in. or 1/2 in. clear or low-iron tempered with polished edges, hinge and handle cut-outs, out-of-plumb angles and notches, and the factory water-repellent coating where selected": { price: [300, 575], labor: 0, basis: "derived", q: 2, note: "per glass piece (door or panel) of about 10-20 sqft, 3/8 in. tempered at about $25-$35/sqft" },
      "Frameless hardware set in the selected finish: wall-mount or pivot hinges, glass-to-glass and wall clamps, header or support bar, handle or towel bar, U-channel where a panel sits in channel": { price: [275, 600], labor: 0, basis: "derived", q: 1, note: "per enclosure" },
      "Enclosure installation: hinge and clamp holes drilled into tile or stone with diamond bits, anchors set into the blocking, panels plumbed on shims, door hung and adjusted for even reveals and self-close": { price: [300, 650], labor: 0.95, basis: "src", q: 1, note: "HomeGuide 2026: install labor $200-$600" },
      "Door seals: polycarbonate sweep with drip rail, side and jamb seals, and a header seal where the door meets the ceiling or a transom": { price: [50, 120], labor: 0.3, basis: "est", q: 1, note: "per door" },
      "Silicone sealing: 100% silicone at the wall and curb on the outside of the enclosure only, inside left open at the curb to weep, tooled in the matching color": { price: [2.5, 5], labor: 0.85, basis: "est", q: 20 },
      "Steam-shower enclosure: transom or full-height door with a header and vent, seals rated for steam": { price: [900, 2200], labor: 0.35, basis: "est", note: "added over a standard enclosure" },
      "Mirror supplied and installed: 1/4 in. mirror cut to size with a polished or 1 in. beveled edge, safety backing, hung on mirror mastic with a J-channel or clips and a top cleat": { price: [14, 28], labor: 0.4, basis: "src", q: 15, note: "Homewyse 2026: $13.86-$19.93/sqft; Angi 2026 custom-cut $10-$50/sqft" },
      "Mirror cut-outs and holes for outlets, switches, sconces and faucets, edges polished": { price: [30, 75], labor: 0.7, basis: "est" },
      "Removal of an existing mirror: face taped, cut free of the mastic with wire, wall skimmed where the mastic tore the drywall": { price: [75, 200], labor: 0.9, basis: "est" },
      "Interior glass accessories: shelves, shower niches, vanity tops, table tops, backsplash and cabinet-door glass cut to size with polished edges and hardware": { price: [75, 350], labor: 0.3, basis: "est", note: "per piece: shelves at the low end, tops at the high end" },
      "Protective film removed, glass cleaned on both faces, hardware finish wiped, and the 24-hour silicone cure explained before the shower is used": { price: [25, 75], labor: 1, basis: "est", q: 1 },
      "Care instructions and warranty: squeegee and cleaner guidance, coating warranty registered and the hardware and labor warranty issued in writing": { price: [15, 50], labor: 1, basis: "est", q: 1, note: "paperwork only" },
    },
  },
  "storefront-curtain-wall": {
    op: 0.2,
    opNote: "commercial specialty glazing subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "glazed elevation area",
      price: [75, 140],
      typicalQty: [400, 1200],
      jobQty: 800,
      minJob: 10000,
      sources: ["Insight Glass 2026 (Bay Area): thermally broken storefront with tempered low-E IGU $90-$140/sqft installed; one 8x9 ft opening with frame and door $5,500-$9,500", "Hotian Windows 2026: storefront $50-$150/sqft installed"],
    },
    steps: {
      "Field verification: rough openings, slab edges, embeds and anchor substrates surveyed with a laser, out-of-tolerance conditions reported to the general contractor before fabrication": { price: [500, 1500], labor: 1, basis: "est", q: 1 },
      "Shop drawings, engineering and submittals: stamped calculations for wind load (ASCE 7), deflection and thermal movement, anchor design, elevations and details, finish and glass samples": { price: [2500, 7000], labor: 1, basis: "est", q: 1, note: "stamped calcs and drafting; scales with the number of elevations" },
      "Storefront framing fabricated and installed: thermally broken extruded aluminum (2 in. x 4-1/2 in. center- or front-set), clear anodized Class I or two-coat PVDF finish, cut, notched, assembled and shimmed plumb and level to the lines": { price: [26, 46], labor: 0.45, basis: "derived", q: 800, note: "about 55% of an installed storefront sqft price" },
      "Curtain wall framing fabricated and installed: 2-1/2 in. x 7-1/2 in. (or deeper) pressure-plate stick system or unitized panels, thermally broken, hung from floor anchors with dead-load and wind-load connections": { price: [45, 80], labor: 0.45, basis: "derived", note: "curtain wall guides 2026: $45-$120/sqft installed with glass" },
      "Anchors and attachments: sill, jamb and head anchors, F-clips or T-anchors, embeds or post-installed anchors into concrete and steel, shims and isolation at dissimilar metals": { price: [20, 55], labor: 0.6, basis: "est", q: 90, note: "per anchor; about one per 8-10 sqft of elevation" },
      "Sill flashing: sill pan or subsill with end dams and a back leg, set in sealant and screwed to the substrate, weeps left open": { price: [18, 35], labor: 0.45, basis: "est", q: 80 },
      "Glazing: 1 in. insulated units (1/4 in. low-E tempered, 1/2 in. argon airspace, 1/4 in. clear tempered) set on blocks with EPDM gaskets in storefront or pressure plates and snap caps in curtain wall": { price: [24, 40], labor: 0.3, basis: "derived", q: 800, note: "1 in. tempered low-E argon IGU about $16-$25/sqft plus setting" },
      "Spandrel and opaque infill: ceramic-frit or opacified spandrel glass, insulated metal panels or aluminum plate in the same frame": { price: [28, 50], labor: 0.3, basis: "est" },
      "Entrance doors: medium- or wide-stile aluminum doors with 1/4 in. tempered glass, offset pivots or continuous hinge, surface closer, push/pull or panic hardware, threshold and weatherstrip, keyed cylinder": { price: [3500, 6500], labor: 0.2, basis: "derived", q: 2, note: "per leaf with hardware; from Insight Glass 2026 $5,500-$9,500 for an opening with frame and door" },
      "Automatic door operators: low-energy swing or full-power sliding operator with actuators and safety sensors, wired to the electrician's circuit": { price: [4500, 11000], labor: 0.35, basis: "est", note: "low-energy swing at the low end, full-power slider at the high end" },
      "Sunshades, canopies or column covers fabricated in the matching finish and attached to the framing": { price: [150, 350], labor: 0.3, basis: "est" },
      "Perimeter sealant: backer rod and silicone at the frame-to-substrate joint inside and out, splice and end-dam seals, interior insulation stuffed at the shim space": { price: [6, 12], labor: 0.7, basis: "derived", q: 200, note: "inside and out" },
      "Field water test to AAMA 501.2 on the first installed bay, with the architect or owner's representative present and any leak corrected before the rest is closed in": { price: [1500, 3500], labor: 0.8, basis: "est", note: "a third-party agency's fee is passed through at cost" },
      "Crane or lift for framing and glass: boom lift, scissor lift or crane with a glazing manipulator, rented for the installation days": { price: [1200, 3500], labor: 0.1, basis: "est", q: 1, note: "equipment rental; scales with the installation days" },
      "Final cleaning and protection: protective film removed, glass and aluminum washed, temporary labels removed, elevations protected until turnover": { price: [400, 1200], labor: 0.85, basis: "est", q: 1, note: "scales with elevation area" },
      "Closeout: finish warranty (10-20 years PVDF), insulated-glass seal warranty, hardware keying and maintenance instructions delivered": { price: [150, 500], labor: 1, basis: "est", q: 1 },
    },
  },
  "garage-flooring": {
    op: 0.35,
    opNote: "residential specialty trade, high sales overhead",
    benchmark: {
      unit: "sqft",
      measures: "garage slab area coated",
      price: [7, 12],
      typicalQty: [400, 600],
      jobQty: 500,
      minJob: 1800,
      sources: ["The Garage Guide 2026: polyaspartic $5-$12/sqft installed; 2-car garage (400 sqft) $2,400-$6,000", "The Garage Guide 2026: diamond grinding $1-$3/sqft; crack repair $0.50-$2/sqft; old coating removal $1-$3/sqft", "JobFlex owner 2026: epoxy flake garage floor sells at about $10/sqft"],
    },
    steps: {
      "Slab moisture check: plastic-sheet test (ASTM D4263) or calcium-chloride test at two points, with a look at the slab age, drains and any vapor barrier before the day is booked": { price: [75, 200], labor: 0.7, basis: "est" },
      "Garage clear-out and protection: vehicles out, shelving, water heater and door tracks masked with plastic, walls and cabinets taped to the coating line, the house door and the driveway apron protected": { price: [150, 350], labor: 0.85, basis: "est", q: 1 },
      "Stripping an old coating or peeling paint with PCD tooling until bare concrete shows across the whole floor": { price: [1, 3], labor: 0.8, basis: "src", note: "The Garage Guide 2026: old coating removal $1-$3/sqft" },
      "Degreasing of oil, transmission-fluid and tire stains with an alkaline cleaner and hot-water extraction so the coating can bond": { price: [0.5, 1], labor: 0.75, basis: "src", note: "The Garage Guide 2026: cleaning and degreasing $0.50-$1.00/sqft" },
      "Diamond grinding to a CSP 2 profile with a HEPA-vacuum grinder, edges and corners hand-ground, floor vacuumed twice and tack-wiped": { price: [1.25, 2.25], labor: 0.75, basis: "src", q: 500, note: "The Garage Guide 2026: diamond grinding $1-$3/sqft" },
      "Control joints and cracks filled with a flexible polyurea joint filler and shaved flush so the finished floor reads as one plane (joints left open on request)": { price: [3, 7], labor: 0.65, basis: "derived", q: 50, note: "The Garage Guide 2026 crack repair $0.50-$2/sqft of floor, at about 0.1 lf per sqft" },
      "Pitting and spall repair with a fast-set polyurea or epoxy patch, feathered flush before the base coat": { price: [8, 18], labor: 0.55, basis: "est", note: "per sqft of area patched" },
      "Pigmented base coat: polyaspartic or 100% solids epoxy at 6-8 mils, rolled to the masked line in the selected base color": { price: [1.5, 2.75], labor: 0.4, basis: "derived", q: 500 },
      "Full flake broadcast: 1/4 in. flake blend thrown to rejection into the wet base coat, scraped and vacuumed after cure for a uniform texture that hides dust and tire marks": { price: [1.25, 2.25], labor: 0.5, basis: "derived", q: 500, note: "flake at about 0.25 lb/sqft net plus scrape and vacuum" },
      "Clear polyaspartic top coat at 8-10 mils, UV-stable so it will not yellow at the door, hot-tire and road-salt resistant, with fine anti-slip aggregate mixed in where selected": { price: [1.75, 3], labor: 0.35, basis: "derived", q: 500, note: "polyaspartic at about $100-$170/gal and 120-160 sqft/gal over flake" },
      "Stem walls coated 4-6 in. high in the same flake system with a masked, level cut line": { price: [4, 9], labor: 0.7, basis: "est" },
      "Steps and landings into the house coated in the flake system with the nosing wrapped": { price: [75, 175], labor: 0.75, basis: "est", note: "per step or landing" },
      "Threshold edge at the garage door: coating keyed into a saw-cut groove or terminated at an aluminum threshold so the edge will not lift": { price: [8, 16], labor: 0.7, basis: "est", q: 16 },
      "Interlocking garage tile: PVC or polypropylene tiles laid loose over the cleaned slab with edge ramps at the door and cut around posts": { price: [5, 9], labor: 0.3, basis: "est", note: "tiles about $3-$6/sqft plus layout and cuts" },
      "Cure and return: walk on the floor after 6-8 hours, park on it after 24-48 hours, masking pulled and contents moved back, with the times written on the invoice": { price: [75, 200], labor: 0.95, basis: "est", q: 1 },
      "Cleanup and closeout: grinding dust and flake sweepings hauled off, driveway rinsed, care sheet and the coating warranty (lifetime against peeling where offered) handed over": { price: [100, 250], labor: 0.6, basis: "est", q: 1 },
    },
  },
};
