// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "solar": {
    op: 0.3,
    opNote: "residential solar installer; heavy sales and customer-acquisition overhead",
    benchmark: {
      unit: "unit",
      measures: "solar modules in the array (about 0.42 kW DC each)",
      price: [1050, 1400],
      typicalQty: [16, 28],
      jobQty: 22,
      minJob: 9000,
      sources: ["NREL Spring 2025 Solar Industry Update: residential PV about $2.56-$3.03/W before incentives", "Solar.com 2026: average 12 kW system about $30,500 before incentives"],
    },
    steps: {
      "Site survey and shade study: roof measured and photographed, pitch and azimuth recorded, shade analysis at each array location, attic framing and rafter spacing checked, main service panel and meter photographed": { price: [250, 600], labor: 0.95, basis: "est", q: 1 },
      "Engineering and plan set: array layout, single-line diagram, structural letter (stamped where the jurisdiction requires), string sizing and NEC 690 calculations": { price: [600, 1500], labor: 0.9, basis: "est", q: 1, note: "design, plan set and PE structural letter" },
      "Building and electrical permits and plan check, and the HOA application where the community requires one": { price: [250, 900], labor: 0, fee: true, basis: "est", q: 1, note: "building and electrical permit and plan-check fees; SolarAPP+ jurisdictions often under $400; HOA fee where charged" },
      "Utility interconnection application and net-metering agreement filed before the install": { price: [50, 400], labor: 0, fee: true, basis: "est", q: 1, note: "utility application fee; many utilities charge $0-$150 for residential net metering" },
      "Roof attachments: flashed, lag-bolted mounts into the rafters with the penetrations sealed": { price: [25, 50], labor: 0.55, basis: "derived", q: 50, note: "per flashed mount; about 2-2.5 per module" },
      "Racking: aluminum rail, mid and end clamps, splices and grounding lugs set level across the attachments": { price: [8, 14], labor: 0.4, basis: "derived", q: 165, note: "per ft of rail; about 7-8 ft of rail per module" },
      "Solar modules: monocrystalline panels of the stated wattage (400-450 W class) with the manufacturer's 25-year product and performance warranty": { price: [360, 520], labor: 0.15, basis: "derived", q: 22, note: "per 400-450 W module set and wired, carrying its share of design, sales and overhead (about $0.85-$1.25/W); from the NREL per-watt total less the other lines" },
      "Inverter: string inverter with power optimizers, or microinverters at each module, sized to the array with the AC rating stated": { price: [250, 380], labor: 0.15, basis: "derived", q: 22, note: "per microinverter (one per module); a string inverter is $2,500-$4,500 each plus $90-$150 per optimizer" },
      "Rapid shutdown: module-level device or initiator per NEC 690.12 with the roof-level labeling": { price: [70, 160], labor: 0.35, basis: "est", q: 1, note: "per module-level device or initiator; with microinverters count one initiator and label set" },
      "Roof junction box or transition box at the array edge, and the DC or AC home run in EMT or PVC conduit to the inverter and panel, wire size stated": { price: [12, 24], labor: 0.6, basis: "est", q: 60, note: "per ft of conduit and wire, junction box included" },
      "AC disconnect, PV breaker and production meter socket where the utility requires one, and any load-side or line-side tap hardware": { price: [250, 600], labor: 0.45, basis: "est", q: 2, note: "per device: disconnect, PV breaker, meter socket or tap kit" },
      "Main panel work: PV breaker under the 120% rule or a main-breaker derate; panel upgrade to 200 A where the existing service cannot carry the backfeed": { price: [1800, 4000], labor: 0.5, basis: "derived", note: "200 A panel upgrade; a main-breaker derate alone is $500-$900" },
      "Ground-mount structure: driven piles or concrete footings and racking, with the trench and conduit run to the house": { price: [6000, 14000], labor: 0.45, basis: "est", note: "per ground-mount array of about 20 modules with a 50-100 ft trench to the house (about $300-$700 per module)" },
      "Grounding and labeling: equipment grounding, bonding and the NEC 690 placards and directory at the meter and disconnects": { price: [150, 400], labor: 0.65, basis: "est", q: 1 },
      "Monitoring: gateway or consumption meter wired and set up with the owner's app and the manufacturer's warranty registration": { price: [400, 800], labor: 0.3, basis: "est", q: 1, note: "gateway with consumption CTs, set up in the app" },
      "AHJ inspection: building and electrical final with the inspector on site, corrections closed out": { price: [200, 500], labor: 0.95, basis: "est", q: 1, note: "contractor time at the final; the fee is in the permit line" },
      "Permission to operate: utility inspection, meter swap and PTO letter, then the system is energized and the owner walked through the app and the shutdown procedure": { price: [150, 450], labor: 0.95, basis: "est", q: 1 },
      "Cleanup, packaging recycled, and the incentive paperwork (federal credit documentation and local rebate applications) delivered": { price: [150, 400], labor: 0.85, basis: "est", q: 1 },
    },
  },
  "smart-home": {
    op: 0.3,
    opNote: "residential AV and automation integrator; equipment sold near MSRP",
    benchmark: {
      unit: "sqft",
      measures: "home floor area served by the system",
      price: [6, 12],
      typicalQty: [2500, 4500],
      jobQty: 3500,
      minJob: 3000,
      sources: ["unanswered.io 2026: Control4 targeted installs $15,000-$30,000, mid-size homes $30,000-$75,000", "Audio Den: 3-4 bedroom Control4 system $20,000 or more (audio in 6-8 rooms, video in 4)"],
    },
    steps: {
      "Discovery and system design: rooms walked, subsystems chosen (lighting, shades, AV, climate, security), device schedule and wiring plan drawn, equipment list and platform confirmed": { price: [1000, 3500], labor: 1, basis: "est", q: 1, note: "about 5-10% of the system price" },
      "Low-voltage prewire: Cat6 or Cat6A to each TV, access point, keypad, camera and touch panel location, home-run to the equipment rack": { price: [1.75, 3.5], labor: 0.75, basis: "est", q: 1400, note: "per ft of Cat6/Cat6A; an 80-100 ft home run is about $150-$300 per drop; retrofit fishing runs toward the top" },
      "Speaker and shade wiring: 16/2 or 16/4 speaker cable to each speaker location and power or control cable to each motorized shade pocket": { price: [1.25, 2.5], labor: 0.75, basis: "est", q: 500, note: "per ft of speaker or shade cable" },
      "Backboxes, brackets and conduit: low-voltage brackets, keypad backboxes, in-wall speaker brackets and 1-2 in. conduit to the rack for future pulls": { price: [20, 45], labor: 0.6, basis: "est", q: 30, note: "per bracket or backbox; a conduit run to the rack counts as one" },
      "Network: rack-mount router with firewall, managed PoE switch, wireless access points (Wi-Fi 6E or 7) ceiling-mounted for whole-house coverage, and a UPS": { price: [450, 950], labor: 0.3, basis: "est", q: 6, note: "per network device (router, PoE switch, access point or UPS), installed and configured" },
      "Equipment rack: enclosed or open rack with patch panel, power conditioner, cooling fan and cable management at the head-end": { price: [1200, 3000], labor: 0.35, basis: "est", q: 1 },
      "Control system: processor and interfaces (touch panels, handheld remotes, wall keypads) for the chosen platform": { price: [500, 1500], labor: 0.2, basis: "est", q: 3, note: "per processor, touch panel or handheld remote; a processor alone is $1,000-$2,500" },
      "Lighting control: smart dimmers and keypads, or a panelized lighting system with a load center, per the device schedule": { price: [250, 450], labor: 0.35, basis: "est", q: 20, note: "per smart dimmer, switch or keypad; panelized systems run about the same per load" },
      "Motorized shades: roller or honeycomb shades in the selected fabric with quiet motors on power or battery": { price: [700, 1500], labor: 0.25, basis: "est", note: "per shade, standard fabric, battery or wired motor" },
      "Climate integration: smart thermostats or an HVAC gateway tied to the control system": { price: [400, 900], labor: 0.35, basis: "est", note: "per smart thermostat or HVAC gateway" },
      "Distributed audio: in-ceiling or in-wall speakers, multi-zone amplifier and streaming sources": { price: [300, 650], labor: 0.35, basis: "est", q: 10, note: "per speaker, amplifier or streamer; in-ceiling speakers average about $350-$500 each installed" },
      "Video: displays mounted, video distribution over HDBaseT or IP, sources and a surround or soundbar system": { price: [800, 2500], labor: 0.3, basis: "est", note: "per display location mounted and integrated (display supplied by the owner unless listed); a soundbar or surround system counts as one" },
      "Security and cameras: PoE cameras, network video recorder, video doorbell and smart locks tied to the control system": { price: [350, 800], labor: 0.35, basis: "est", note: "per PoE camera, doorbell or smart lock; the NVR counts as one" },
      "Programming and integration: scenes, schedules, voice control, remote access and each subsystem brought into the single app": { price: [100, 175], labor: 1, basis: "est", q: 20, note: "integrator programming rate" },
      "Commissioning: every device tested from every interface, network load and coverage checked, firmware updated": { price: [90, 150], labor: 1, basis: "est", q: 6 },
      "Owner training and a walk-through of the app, keypads and remotes with a quick-reference card": { price: [150, 400], labor: 1, basis: "est", q: 1 },
      "Documentation: network map, IP and credential schedule, device list and as-built wiring drawings": { price: [200, 600], labor: 1, basis: "est", q: 1 },
      "Cleanup and closeout: packaging recycled, wall penetrations patched, and the service plan and warranty issued": { price: [150, 500], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "ev-charger": {
    op: 0.3,
    opNote: "residential electrical contractor; small jobs carry high overhead per job",
    benchmark: {
      unit: "unit",
      measures: "Level 2 chargers installed (40-48 A, charger included)",
      price: [1300, 2800],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 600,
      sources: ["HomeGuide 2026: complete Level 2 charger install $1,200-$3,000", "HomeGuide 2026: Level 2 charger unit $300-$800 before installation"],
    },
    steps: {
      "Site evaluation and load calculation: service size and panel capacity checked, an NEC 220.83/220.87 load calc run, the charger location and the shortest safe circuit route set": { price: [75, 250], labor: 1, basis: "est", q: 1 },
      "Electrical permit and inspection scheduling with the jurisdiction": { price: [75, 300], labor: 0, fee: true, basis: "est", q: 1, note: "electrical permit fee; scheduling time is in overhead" },
      "Panel work: 2-pole 40, 50 or 60 A breaker in the main panel, or a subpanel or 200 A panel upgrade where the load calc shows the service is full": { price: [100, 300], labor: 0.7, basis: "est", q: 1, note: "2-pole breaker installed; a subpanel is $800-$1,800 and a 200 A panel upgrade $1,800-$4,000 when the load calc calls for one" },
      "Load management device to share the available capacity so the charger runs without a service upgrade": { price: [600, 1500], labor: 0.35, basis: "est" },
      "Branch circuit: 6 AWG THHN copper in 3/4 in. EMT on a 60 A breaker for a 48 A charger, or 6-3 NM-B on a 50 A breaker for a 40 A charger, run from the panel to the charger location at the 125% continuous-load rating of NEC 625": { price: [10, 22], labor: 0.55, basis: "est", q: 35, note: "per ft of 6 AWG copper circuit, NM-B or THHN in EMT" },
      "Trenching and underground conduit: 18-24 in. trench, Schedule 40 PVC, backfilled and the surface restored for a detached garage or carport": { price: [18, 40], labor: 0.65, basis: "est", note: "trench, PVC conduit, backfill and restore; conductors are in the branch-circuit line" },
      "Wall or slab penetration: core-drilled or bored, sleeved and fire-stopped at the exterior or rated wall": { price: [100, 300], labor: 0.85, basis: "est" },
      "NEMA 14-50 receptacle on a GFCI breaker with a weatherproof in-use cover for a plug-in charger": { price: [250, 500], labor: 0.4, basis: "est", note: "receptacle, 2-pole GFCI breaker and in-use cover; the circuit is its own line" },
      "Level 2 charger: 40-48 A EVSE (Wi-Fi, app-scheduled) mounted at the marked height, hardwired, with a cable hook or retractor": { price: [600, 1000], labor: 0.2, basis: "derived", q: 1, note: "charger ($300-$800 per HomeGuide) plus mounting and hardwiring" },
      "Pedestal or bollard mount with concrete base for a parking-lot or driveway charger": { price: [900, 2000], labor: 0.45, basis: "est" },
      "Networked commercial stations: OCPP-capable Level 2 stations with payment, signage, wheel stops and accessible-stall striping": { price: [6000, 12000], labor: 0.3, basis: "est", note: "per dual-port networked station on a pedestal with signage, wheel stops and striping; feeder and trench by the foot; network plan excluded" },
      "Commissioning: circuit energized, ground-fault and polarity tested, charger paired to Wi-Fi and the app, a charge session run on the vehicle and the owner walked through scheduling": { price: [100, 250], labor: 1, basis: "est", q: 1 },
      "Utility rebate and EV-rate paperwork filed with the installation photos": { price: [50, 200], labor: 1, basis: "est" },
      "Patching and cleanup: drywall or siding penetrations patched, conduit painted to match, packaging removed and the charger warranty registered": { price: [75, 250], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "data-cabling": {
    op: 0.2,
    opNote: "commercial low-voltage specialty subcontractor",
    benchmark: {
      unit: "unit",
      measures: "cable drops installed, terminated and certified (Cat6)",
      price: [200, 375],
      typicalQty: [24, 96],
      jobQty: 60,
      minJob: 750,
      sources: ["The Network Installers 2026: Cat6 drop $125-$400 installed, terminated and tested; Cat6A $175-$500", "The Network Installers 2026: 50-150 drop projects $7,750-$64,000; telecom room setup $1,500-$4,000"],
    },
    steps: {
      "Site survey and design: drop locations counted room by room, telecom room and rack placement set, pathways routed, a cable schedule and drawing produced": { price: [400, 1500], labor: 1, basis: "est", q: 1 },
      "Pathways: J-hooks or cable tray above the ceiling, sleeves and firestop at rated walls and floors, surface raceway where walls are finished": { price: [3, 8], labor: 0.65, basis: "est", q: 250, note: "per ft of J-hook route (hooks 4-5 ft o.c.); cable tray is $15-$35/ft" },
      "Horizontal cabling: Cat6 or Cat6A plenum (CMP) or riser (CMR) cable pulled from the patch panel to each outlet location, under 295 ft per TIA-568": { price: [0.65, 1.15], labor: 0.55, basis: "derived", q: 7200, note: "Cat6 riser: certifiable cable $0.30-$0.60/ft plus pulling labor; plenum adds $0.15-$0.30/ft, Cat6A $0.30-$0.50/ft" },
      "Drop terminations: keystone jack at the work area with a faceplate or surface box, matching port on the patch panel, both ends labeled": { price: [35, 65], labor: 0.6, basis: "derived", q: 60, note: "per drop, both ends: jack ($8-$18), faceplate, panel port and labels" },
      "Backbone fiber: OM4 multimode or OS2 single-mode strands, indoor or indoor/outdoor rated, pulled between telecom rooms or buildings": { price: [3, 8], labor: 0.55, basis: "est", note: "12-strand indoor/outdoor; innerduct adds $1-$3/ft" },
      "Fiber terminations: fusion-spliced LC pigtails or field-polished connectors in a rack-mount enclosure with adapter panels": { price: [30, 60], labor: 0.7, basis: "est", note: "per strand spliced or connectorized; enclosure and adapter panels ($300-$700) at the rack" },
      "Rack or cabinet: 2- or 4-post rack or enclosed cabinet with vertical managers, rack PDU and a grounding bus bar bonded per TIA-607": { price: [1200, 3000], labor: 0.35, basis: "derived", q: 1, note: "from the $1,500-$4,000 telecom-room setup less the patch panels" },
      "Patch panels and horizontal managers: 24- or 48-port Cat6A panels with wire managers above and below": { price: [250, 600], labor: 0.35, basis: "est", q: 2, note: "per 24- or 48-port panel with its horizontal manager" },
      "Patch cords: factory-terminated cords at the panel and the work area in the stated lengths and colors": { price: [6, 14], labor: 0.2, basis: "est", q: 120 },
      "Wireless access point drops: ceiling-mounted with a PoE drop and a mounting bracket at the surveyed location": { price: [175, 350], labor: 0.6, basis: "derived", note: "drop and bracket at the per-drop rate; the access point is by the IT provider unless listed" },
      "Wall and floor penetrations: core drilling, fishing finished walls and hard-lid ceiling access with patch and paint": { price: [100, 300], labor: 0.85, basis: "est" },
      "Certification testing: every copper link tested to the TIA-568 Cat6 or Cat6A permanent-link standard with a certified tester, fiber tested by OLTS or OTDR, reports delivered": { price: [10, 22], labor: 0.95, basis: "derived", q: 60, note: "per link; testing runs about 5% of the installation" },
      "Labeling and as-builts: cables, panels and faceplates labeled to TIA-606, with the drawing updated to the installed locations": { price: [250, 800], labor: 0.9, basis: "est", q: 1 },
      "Cleanup: ceiling tiles reset, debris removed and the 25-year system warranty registered where the manufacturer offers one": { price: [150, 400], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "residential-generator": {
    op: 0.3,
    opNote: "residential generator dealer-installer",
    benchmark: {
      unit: "unit",
      measures: "standby generators installed (22-26 kW air-cooled, whole-house ATS)",
      price: [10500, 16000],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 7000,
      sources: ["HomeAdvisor 2026: 20-24 kW standby unit $5,000-$6,500 plus $1,500-$5,000 installer labor", "HomeAdvisor 2026: permits $50-$200 each; concrete pad about $1,000"],
    },
    steps: {
      "Site assessment and sizing: whole-house or essential-circuit load survey, kW selected, fuel supply and meter capacity checked, pad location set to the clearances (18 in. from the house, 60 in. from openings) and the noise ordinance": { price: [150, 400], labor: 1, basis: "est", q: 1 },
      "Permits: electrical, gas or mechanical, and zoning or HOA approval for the outdoor unit": { price: [150, 600], labor: 0, fee: true, basis: "derived", q: 1, note: "electrical and gas permits at $50-$200 each, plus zoning or HOA where required" },
      "Standby generator: air-cooled 18-26 kW (or liquid-cooled 30-60 kW) natural-gas or propane unit in a weather-rated, sound-attenuated enclosure with the manufacturer's warranty": { price: [5500, 7500], labor: 0.08, basis: "src", q: 1, note: "22-26 kW air-cooled unit set on the pad; liquid-cooled 30-60 kW units run $15,000-$30,000" },
      "Generator pad: composite pad or 4 in. reinforced concrete pad on compacted gravel, level, with the unit bolted down": { price: [250, 900], labor: 0.55, basis: "derived", q: 1, note: "composite pad on gravel at the low end, poured concrete pad at the top" },
      "Automatic transfer switch: 200 A service-entrance-rated ATS for whole-house, or a 100-200 A ATS with load-shedding modules for managed loads, mounted beside the main panel": { price: [900, 1900], labor: 0.45, basis: "est", q: 1, note: "200 A service-rated ATS installed at the main panel; load-shedding modules add $150-$300 each" },
      "Feeder: conductors from the ATS to the generator in conduit, sized to the transfer switch (3 AWG copper or 1 AWG aluminum for 100 A), buried 18-24 in. or run along the wall": { price: [18, 35], labor: 0.5, basis: "est", q: 25 },
      "Control wiring: 2-conductor or 4-conductor low-voltage cable from the ATS to the generator controller in its own conduit": { price: [4, 9], labor: 0.6, basis: "est", q: 25 },
      "Trenching for the feeder and gas line, backfilled and the lawn or hardscape restored": { price: [15, 35], labor: 0.7, basis: "est" },
      "Gas line: 3/4 to 1-1/4 in. black iron or CSST from the meter to the generator with a shut-off, sediment trap, regulator and flexible connector, pressure-tested": { price: [25, 50], labor: 0.6, basis: "est", q: 30, note: "per ft on a 20-40 ft run, shut-off, sediment trap, regulator and flex connector included" },
      "Utility gas meter upgrade requested for the added load, with the utility's fee passed through": { price: [300, 1500], labor: 0, fee: true, basis: "est", note: "utility charge where one applies; many utilities upgrade residential meters free" },
      "Propane supply: tank set, regulator and line sized for the generator's BTU rating": { price: [2500, 5000], labor: 0.35, basis: "est", note: "owned 500-gal tank set with regulators and line; a leased tank is set by the supplier for $0-$500" },
      "Battery, cold-weather kit and block heater installed for reliable starts": { price: [250, 550], labor: 0.25, basis: "est", q: 1 },
      "Manufacturer-certified startup: fuel pressure, oil, voltage and frequency checked, exercise schedule set, a transfer test under load run": { price: [250, 600], labor: 0.95, basis: "est", q: 1 },
      "Remote monitoring: Wi-Fi or cellular module paired to the owner's app with alerts": { price: [150, 450], labor: 0.3, basis: "est", q: 1 },
      "Electrical and gas inspections with the inspector on site, corrections closed out": { price: [150, 400], labor: 1, basis: "est", q: 1 },
      "Cleanup, warranty registration (5-10 years) and the owner walk-through of the exercise cycle and the maintenance schedule": { price: [150, 350], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "battery-backup": {
    op: 0.3,
    opNote: "residential solar and storage installer",
    benchmark: {
      unit: "unit",
      measures: "battery units installed (10-15 kWh each, Powerwall 3 class)",
      price: [10000, 16000],
      typicalQty: [1, 3],
      jobQty: 2,
      minJob: 8000,
      sources: ["SolarReviews 2026: Powerwall 3 $15,300-$16,200 installed before incentives", "SolarReviews 2026: expansion pack $5,900 plus $700-$1,000 labor; about $1,140-$1,200 per kWh"],
    },
    steps: {
      "Backup-load assessment: critical loads listed and metered, backup hours and battery count set, the mounting location checked for clearances, temperature and the fire-code rules (NFPA 855, IRC R328)": { price: [200, 500], labor: 1, basis: "est", q: 1 },
      "Design and permits: single-line diagram, equipment listing (UL 9540) and placards, building and electrical permit and plan check": { price: [800, 2000], labor: 0.6, basis: "est", q: 1, note: "design and plan set plus permit fees (about $300-$800)" },
      "Utility energy-storage interconnection application and the export or non-export agreement": { price: [50, 300], labor: 0, fee: true, basis: "est", q: 1, note: "utility application fee; often $0-$150 for non-export storage" },
      "Battery units: lithium iron-phosphate or NMC modules of the stated kWh (5-15 kWh each) wall- or floor-mounted on the manufacturer's bracket with vehicle-impact protection in a garage": { price: [7000, 10500], labor: 0.12, basis: "derived", q: 2, note: "per 10-15 kWh unit with integrated inverter (Powerwall 3 or equal); a DC expansion unit is $5,900-$7,000 installed, a 5 kWh module $4,500-$6,500" },
      "Hybrid or battery inverter for DC-coupled or retrofit AC-coupled storage, sized to the battery kW": { price: [3000, 6000], labor: 0.25, basis: "est" },
      "Backup gateway or microgrid interconnection device: islands the home from the grid in an outage and meters the site": { price: [1500, 2800], labor: 0.3, basis: "derived", q: 1, note: "gateway or microgrid device installed; part of the $15,300-$16,200 single-unit price" },
      "Critical-loads subpanel: 100-125 A panel with the backed-up circuits relocated from the main panel": { price: [1000, 2200], labor: 0.55, basis: "est" },
      "Conductors and conduit: AC circuit from the gateway to the panel and DC or AC wiring between the batteries and the inverter, in EMT or PVC with the wire size stated": { price: [15, 30], labor: 0.55, basis: "est", q: 45 },
      "Main panel modifications: breakers, a bus-bar tap or a main-breaker derate, and the panel upgrade where the service cannot accept the storage feed": { price: [350, 1000], labor: 0.6, basis: "est", q: 1, note: "breakers, tap or derate; a 200 A panel upgrade is $1,800-$4,000" },
      "Solar integration: existing PV tied through the gateway so the array charges the battery in an outage": { price: [500, 1500], labor: 0.7, basis: "est" },
      "Generator integration: automatic transfer input with the generator locked out from backfeeding the battery inverter": { price: [800, 2000], labor: 0.5, basis: "est" },
      "Fire and code items: 5/8 in. Type X gypsum at the mounting wall where required, heat or smoke detection in the room, spacing between units and the placards": { price: [250, 900], labor: 0.6, basis: "est", q: 1 },
      "Commissioning: firmware updated, backup transfer test with the grid disconnected, operating mode set (self-consumption, time-of-use or backup reserve), app configured": { price: [250, 600], labor: 1, basis: "est", q: 1 },
      "Inspection and permission to operate: AHJ final and the utility's approval before the system exports": { price: [200, 500], labor: 0.95, basis: "est", q: 1 },
      "Monitoring and owner training: app access, alerts, the outage behavior explained and the incentive paperwork delivered": { price: [150, 400], labor: 1, basis: "est", q: 1 },
      "Cleanup, packaging recycled and the 10-year battery warranty registered": { price: [150, 350], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "greywater-system": {
    op: 0.3,
    opNote: "residential plumbing and landscape specialty trade",
    benchmark: {
      unit: "unit",
      measures: "greywater sources connected (a washer, shower or lavatory group, each with its diverter)",
      price: [1500, 3500],
      typicalQty: [1, 3],
      jobQty: 2,
      minJob: 1500,
      sources: ["Greywater Action: full installation laundry-to-landscape $700-$2,000, branched drain $800-$3,000, pumped $1,000-$4,000"],
    },
    steps: {
      "Site and feasibility assessment: greywater sources (laundry, showers, lavatories) and their daily volume, drain access, soil percolation, slope, setbacks from wells and property lines, and the plants to be irrigated": { price: [150, 500], labor: 1, basis: "est", q: 1 },
      "Plumbing permit and drawings for the reuse system, or the permit-exempt laundry-to-landscape path where the state allows it": { price: [400, 1500], labor: 0.5, basis: "est", note: "drawings plus the plumbing permit fee (about $100-$500)" },
      "Fixture-drain separation: greywater drains rerouted from the blackwater stack, with a labeled 3-way diverter valve and an accessible handle so flow returns to the sewer on demand": { price: [300, 800], labor: 0.75, basis: "est", q: 2, note: "per source fixture with its 3-way diverter" },
      "Collection piping: 1-1/2 to 2 in. ABS or PVC DWV drain pipe sloped 1/4 in. per ft from the diverter to the surge tank or filter, with cleanouts": { price: [10, 22], labor: 0.7, basis: "est", q: 30 },
      "Surge tank: vented, screened tank sized for one laundry or shower load, with an overflow to the sewer and a drain-down at the bottom": { price: [500, 1200], labor: 0.4, basis: "est" },
      "Filtration: screen or basket filter (or a self-cleaning filter on larger systems) ahead of the distribution line, with a service access": { price: [150, 500], labor: 0.4, basis: "est", q: 1 },
      "Effluent pump and controller: submersible pump sized for the head and the distribution zone, float switch and an alarm": { price: [900, 2000], labor: 0.4, basis: "est" },
      "Distribution main: 1 in. HDPE or purple-marked PVC from the filter to the irrigation zones, buried 12 in., with a vacuum breaker and drain valve": { price: [3.5, 8], labor: 0.6, basis: "est", q: 80 },
      "Mulch basins: excavated basins with a mulch shield and an outlet at each tree or shrub, sized to the plant and the soil": { price: [80, 200], labor: 0.85, basis: "est", q: 8 },
      "Subsurface drip or branched drain zone: purple 1/2 in. drip tubing with greywater-rated emitters, or branched drain outlets, under 2 in. of mulch across the irrigated bed": { price: [2.5, 6], labor: 0.6, basis: "est", note: "per sqft of irrigated bed" },
      "Trenching for the distribution line and outlets, backfilled and the landscape restored": { price: [4, 10], labor: 0.9, basis: "est", q: 80, note: "12 in. trench, mostly hand-dug, backfilled" },
      "Indoor reuse treatment: tank, filtration, disinfection (UV or chlorine), dye injection and purple-pipe supply to toilets, with the backflow protection the code requires": { price: [9000, 18000], labor: 0.3, basis: "est", note: "NSF 350 treatment package with purple-pipe supply to the toilets" },
      "Labeling and signage: purple pipe, valve tags and the greywater warning label at each outlet and the diverter": { price: [50, 175], labor: 0.6, basis: "est", q: 1 },
      "Inspection and commissioning: the jurisdiction's inspection, a flow test with the diverter in each position, outlets balanced and the owner shown the valve and filter cleaning": { price: [150, 450], labor: 1, basis: "est", q: 1 },
      "Cleanup, restoration of the trench line, and the owner's manual with the soap and detergent guidance and the maintenance schedule": { price: [100, 350], labor: 0.9, basis: "est", q: 1 },
    },
  },
  "gate-access-control": {
    op: 0.3,
    opNote: "residential and light-commercial gate automation trade",
    benchmark: {
      unit: "unit",
      measures: "automated gates (operator, safety devices and access control per gate)",
      price: [4500, 9500],
      typicalQty: [1, 1],
      jobQty: 1,
      minJob: 2500,
      sources: ["Fixr 2026: electric gate installed $2,500-$5,500 (average $4,000)", "Fixr 2026: add-ons installed keypad $400-$800, sensors $200-$2,000, intercom $1,000-$7,000"],
    },
    steps: {
      "Site survey: gate type (swing or slide), width, weight and hardware condition, power source and distance, grade and drainage at the gate line, sight lines, vehicle stopping distance and the UL 325 usage class": { price: [125, 350], labor: 1, basis: "est", q: 1 },
      "Utility locate ticket and any permit or HOA approval for the automated gate and its posts": { price: [75, 350], labor: 0, fee: true, basis: "est", q: 1, note: "811 locate is free; the price is the permit or HOA fee where one applies" },
      "Trench and underground conduit: 18-24 in. trench with Schedule 40 PVC for power and a second conduit for control and data, backfilled and restored": { price: [14, 32], labor: 0.65, basis: "est", q: 40, note: "two conduits in one trench" },
      "Power circuit: 120 or 240 V dedicated circuit from the panel to the operator disconnect, wire size stated, by the electrician where the jurisdiction requires": { price: [4, 9], labor: 0.6, basis: "est", q: 40, note: "wire pulled in the trench conduit; breaker and disconnect included" },
      "Operator pad: reinforced concrete pad with anchor bolts set to the gate line, or the post mount for a swing operator": { price: [250, 700], labor: 0.6, basis: "est", q: 1 },
      "Gate operator: slide-gate operator (chain or rack-and-pinion, 1/2-1 HP) or swing-arm or underground operator, UL 325 listed, with the control board, limit settings and a manual release": { price: [1600, 3400], labor: 0.25, basis: "derived", q: 1, note: "UL 325 slide operator or one swing operator; a dual-swing pair adds about 70% for the second arm" },
      "Gate hardware and fabrication: new gate or repair of the existing one, hinges, wheels, track, chain or rack, catch post and posts set in concrete": { price: [2500, 7000], labor: 0.4, basis: "derived", note: "new 12-16 ft steel or aluminum gate with posts and hardware; repairing the existing gate is $400-$1,500" },
      "Entrapment protection: monitored photo-eyes and wireless edge sensors at each entrapment zone, warning signs on both faces, per UL 325 and ASTM F2200": { price: [225, 500], labor: 0.4, basis: "derived", q: 2, note: "per monitored photo-eye pair or edge sensor" },
      "Vehicle detection loops: saw-cut loops with sealant for free exit, safety and shadow, with loop detectors in the operator": { price: [350, 750], labor: 0.6, basis: "est", q: 1, note: "per saw-cut loop with its detector" },
      "Access control device: keypad, cellular or wired video intercom, proximity or RFID reader and remotes, on a pedestal or the post at the driver's reach": { price: [400, 1200], labor: 0.35, basis: "src", q: 1, note: "keypad on a gooseneck pedestal; video intercoms run $1,500-$4,000" },
      "Exit device: free-exit wand, push button or a second reader on the inside": { price: [150, 450], labor: 0.5, basis: "est", q: 1 },
      "Battery back-up or solar power kit so the gate opens through an outage": { price: [350, 1200], labor: 0.35, basis: "derived", note: "battery kit at the low end, solar kit at the top" },
      "Network connection: Ethernet or cellular link for cloud management, app control and delivery codes": { price: [250, 800], labor: 0.5, basis: "est" },
      "Barrier-arm operators and pedestals for a commercial lane, with arm, loops and signage": { price: [5500, 11000], labor: 0.35, basis: "est", note: "per lane: barrier operator, arm, loops and signage" },
      "Programming and commissioning: limits, force and speed set, entrapment tests run on every device, codes and credentials loaded, the owner trained on the release and the app": { price: [250, 600], labor: 1, basis: "est", q: 1 },
      "Cleanup and closeout: trench line restored, packaging removed, and the operator warranty (typically 2-5 years) and the maintenance schedule issued": { price: [125, 350], labor: 0.85, basis: "est", q: 1 },
    },
  },
};
