// The price book for this group of specialties — generated from the
// 2026-09-18 price research (docs/pricing-step-prices.md); edit by hand
// freely, scripts/qa/step-prices.check.ts keeps it whole. Customer prices,
// US national, standard grade, overhead and profit included (./types).
import type { StepPriceMap } from "./types";

export const PRICES: StepPriceMap = {
  "waterproofing": {
    op: 0.2,
    opNote: "commercial specialty subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "membrane area (net substrate)",
      price: [7, 15],
      typicalQty: [1500, 5000],
      jobQty: 3250,
      minJob: 5000,
      sources: ["Jaspector (undated): below-grade sheet membranes $7-$15/sqft installed on new construction, premium $15-$25; dimple drainage board $2-$6/sqft", "ConstructEstimates 2026: sheet membrane waterproofing $8-$15/sqft installed; below-grade exterior membrane $7-$15/sqft"],
    },
    steps: {
      "Pre-installation survey and submittals: substrate condition, moisture and cure of the concrete, tie-in points to existing membranes, drainage outlets, and the manufacturer's product data, details and warranty application": { price: [800, 2500], labor: 1, basis: "est", q: 1 },
      "Excavation along the foundation wall to the top of the footing with a 3 ft working width, shored or benched, spoils stockpiled clear of the edge": { price: [30, 75], labor: 0.5, basis: "est", note: "machine digging with benching or shoring" },
      "Substrate preparation: pressure washing or grinding, form-tie holes and honeycomb patched with non-shrink grout, fins and ridges ground off, a cant or fillet at the footing-to-wall joint": { price: [0.4, 1.1], labor: 0.8, basis: "est", q: 3250 },
      "Crack and cold-joint treatment: cracks over 1/16 in. routed and sealed, then covered with a 12 in. detail strip of the membrane": { price: [6, 14], labor: 0.7, basis: "est", q: 150 },
      "Primer or surface conditioner rolled or sprayed at the manufacturer's rate onto the dry, clean substrate": { price: [0.3, 0.65], labor: 0.45, basis: "derived", q: 3250 },
      "Sheet membrane: 60-mil self-adhered rubberized-asphalt sheet, or 40-mil HDPE-faced blindside sheet, shingle-lapped 2-1/2 in. at side laps and 3 in. at end laps, rolled with a hand roller": { price: [3.5, 6], labor: 0.4, basis: "derived", q: 3250, note: "the membrane's share of a $7-$15/sqft installed sheet system (Jaspector; ConstructEstimates 2026); 60-mil sheet material about $1.10-$1.50/sqft" },
      "Fluid-applied membrane: two-component polyurethane or single-component modified-asphalt coating spray- or roller-applied to 60 mils dry with reinforcing fabric at joints": { price: [3.5, 6.5], labor: 0.45, basis: "est" },
      "Hot rubberized asphalt: 215-mil monolithic membrane with reinforcing fabric under a plaza deck or green roof, over a primed and dry deck": { price: [7, 12], labor: 0.45, basis: "est" },
      "Detailing: inside and outside corners, footing-to-wall joint and construction joints reinforced with a second ply or liquid detailing membrane": { price: [3.5, 7.5], labor: 0.7, basis: "est", q: 490, note: "about 0.15 lf per sqft of wall (footing joint plus corners)" },
      "Penetration flashing: pipes, conduits, sleeves and tie-backs wrapped with a liquid membrane boot or a target-patch sheet": { price: [60, 150], labor: 0.7, basis: "est", q: 10 },
      "Termination: top edge clamped under an aluminum termination bar with a sealant cap bead, or turned into a reglet with counterflashing": { price: [4, 8], labor: 0.6, basis: "est", q: 406 },
      "Tie-in to the existing membrane or roofing: old surface cleaned and primed, new membrane lapped 6 in. onto it and sealed with a compatible liquid flashing": { price: [10, 22], labor: 0.7, basis: "est" },
      "Protection board: 1/4 in. asphaltic board or 1/8 in. HDPE sheet adhered over the membrane before backfill or topping": { price: [0.7, 1.4], labor: 0.4, basis: "derived", q: 3250 },
      "Drainage composite: dimpled drainage board with filter fabric hung over the membrane, bottom edge into the footing drain, laps shingle-fashion": { price: [1.5, 3], labor: 0.35, basis: "derived", q: 3250, note: "Jaspector: dimple drainage board $2-$6/sqft installed on houses; lower at commercial scale" },
      "Footing drain: 4 in. perforated pipe in washed stone wrapped in filter fabric at the footing, run to the sump or daylight": { price: [25, 50], labor: 0.5, basis: "src", note: "Jaspector: footing drain with gravel and fabric $25-$60/lf on new construction" },
      "Deck drains and scuppers: clamping-ring drains or scupper flashings set into the membrane with the flashing collar sealed": { price: [250, 700], labor: 0.4, basis: "est" },
      "Traffic-bearing deck coating: two-coat polyurethane deck system (base and aggregate top coat) to 30-40 mils dry over balconies and walkways": { price: [6, 11], labor: 0.5, basis: "est" },
      "Flood test of horizontal membranes for 24-48 hours at 2 in. depth (ASTM D5957) or electronic leak detection, and a holiday check of walls before they are covered, with any breach repaired and retested": { price: [500, 1500], labor: 0.9, basis: "est", q: 1 },
      "Backfill with free-draining granular fill placed in 12 in. lifts and compacted away from the wall so the membrane and board are not dragged": { price: [45, 85], labor: 0.35, basis: "est", note: "granular fill about $25-$45/cy plus placing and compacting" },
      "Cleanup, disposal of release liners and scrap, and the manufacturer's final inspection for the system warranty": { price: [400, 1200], labor: 0.7, basis: "est", q: 1 },
    },
  },
  "sealant-caulking": {
    op: 0.2,
    opNote: "commercial specialty subcontractor",
    benchmark: {
      unit: "linear ft",
      measures: "joint length sealed",
      price: [5, 14],
      typicalQty: [1000, 5000],
      jobQty: 3000,
      minJob: 1500,
      sources: ["Rockford Commercial Caulking (undated): exterior wall joint replacement $4-$12/lf; expansion joints $7-$18; window perimeter at elevated access $10-$16", "WCP Building Renewal 2025: window perimeter sealant $10-$16/lf; expansion joints $14-$18/lf; cold joints $12-$20/lf"],
    },
    steps: {
      "Joint survey and adhesion testing: every joint type inventoried with its width, depth, movement and substrates, and a field adhesion test of the proposed sealant on each substrate before the order": { price: [500, 1500], labor: 0.9, basis: "est", q: 1 },
      "Access equipment: boom lift, scissor lift or swing stage set for the elevations, with ground protection and barricades": { price: [1500, 5000], labor: 0.1, basis: "est", note: "boom lift about $1,500-$3,500 a week with delivery; swing stage rigging costs more; scales with duration" },
      "Removal of the failed sealant: old bead cut out with a knife and grinder, remaining film abraded off both joint faces, loose backer rod pulled": { price: [1.25, 3], labor: 0.95, basis: "derived", note: "removal is most of the gap between new-joint and replacement prices" },
      "Joint cleaning: solvent wipe by the two-cloth method (or oil-free blow-down on porous stone) so the faces are dry and dust-free": { price: [0.4, 1], labor: 0.95, basis: "est", q: 3000 },
      "Backer rod: closed-cell polyethylene rod 25% wider than the joint set to the depth that gives an hourglass bead, or bond-breaker tape at shallow joints": { price: [0.5, 1.25], labor: 0.6, basis: "est", q: 3000 },
      "Primer brushed onto the joint faces where the manufacturer's adhesion test calls for it, and always on masonry, stone and precast": { price: [0.3, 0.8], labor: 0.7, basis: "est" },
      "Masking of the finish on both sides of the joint to keep the bead lines crisp on stone, precast and metal panels": { price: [0.4, 1], labor: 0.85, basis: "est", q: 3000 },
      "Vertical joint sealant: silicone (ASTM C920 Class 50, type S or M) or polyurethane (Class 25) in the matched color, gunned into the joint and tooled concave to the backer rod for full wetting": { price: [3, 6.5], labor: 0.7, basis: "derived", q: 3000, note: "silicone about $0.55-$0.90/lf of material for a 1/2 x 1/4 in. bead, plus gunning and tooling" },
      "Horizontal joint sealant: self-leveling polyurethane or traffic-grade silicone in saw-cut, expansion and isolation joints in sidewalks, plazas and parking decks": { price: [3.5, 8], labor: 0.6, basis: "est" },
      "Glazing seals: wet seal or cap bead of silicone at the glass-to-metal edge on window and curtain-wall units": { price: [2.5, 5.5], labor: 0.75, basis: "est" },
      "Penetration and dissimilar-material seals: pipes, louvers, signs, conduits and lintels sealed with the compatible sealant": { price: [25, 70], labor: 0.8, basis: "est", q: 30 },
      "Expansion-joint systems: pre-compressed foam or extruded silicone joint systems set into the joint with the manufacturer's epoxy or adhesive": { price: [45, 110], labor: 0.35, basis: "est", note: "pre-compressed foam or extruded silicone systems" },
      "Field adhesion test on the cured sealant (ASTM C1521 hand-pull) at the stated frequency, results logged for the warranty": { price: [300, 900], labor: 0.9, basis: "est", q: 1 },
      "Water test of representative joints with a hose or spray rack, with any leak resealed": { price: [400, 1200], labor: 0.9, basis: "est" },
      "Cleanup: masking removed, smears cleaned off the finish, cartridges and old sealant disposed of, and the applicator and manufacturer warranties issued": { price: [300, 900], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "metal-cladding": {
    op: 0.2,
    opNote: "commercial specialty subcontractor",
    benchmark: {
      unit: "sqft",
      measures: "net panel area",
      price: [28, 55],
      typicalQty: [2000, 8000],
      jobQty: 5000,
      minJob: 15000,
      sources: ["Alcadex 2025: ACM panels $40-$55/sqft installed (materials and labor); 4 mm FR panel material $22-$30/sqft", "Wallnova 2025: insulated metal panels $7-$14/sqft (panel price)"],
    },
    steps: {
      "Laser survey of the wall substrate and structure, then shop drawings and engineering: panel layout, attachment calcs for wind load, thermal movement, submittals and finish samples": { price: [3000, 9000], labor: 1, basis: "est", q: 1, note: "scales with the number of elevations" },
      "Field mock-up: one bay of the full assembly (barrier, insulation, clips, panel and trims) built for approval and testing": { price: [5000, 15000], labor: 0.6, basis: "est" },
      "Removal of the existing siding or cladding, fasteners pulled, sheathing exposed and inspected, debris hauled off": { price: [1.5, 3.5], labor: 0.8, basis: "est" },
      "Air and water-resistive barrier: fluid-applied or self-adhered membrane over the sheathing, openings and penetrations flashed, laps sealed": { price: [2.5, 5], labor: 0.5, basis: "est" },
      "Continuous exterior insulation: mineral wool or polyiso boards at the stated thickness and R-value, fastened with plastic or metal washers": { price: [3, 5.5], labor: 0.45, basis: "est", q: 5000, note: "2-3 in. mineral wool or polyiso" },
      "Subframing: thermally isolated clips and Z- or hat-girts at 16-24 in. o.c. set plumb to a laser plane, fastened to the studs or structure": { price: [6, 12], labor: 0.5, basis: "est", q: 3000, note: "per lf of girt with its clips; about 0.5-0.75 lf per sqft of wall" },
      "Aluminum composite panels: 4 mm ACM routed and returned into pans with stiffeners, rear-ventilated rain-screen installation with the joints as detailed": { price: [24, 40], labor: 0.4, basis: "derived", note: "from Alcadex 2025 $40-$55/sqft for an installed ACM system, less subframing and trims" },
      "Single-skin metal panels: 22-24 ga. steel or 0.040 aluminum, preformed flush, corrugated or box-rib profile, concealed or exposed fastening": { price: [13, 25], labor: 0.45, basis: "est", q: 5000, note: "each job carries one of the panel lines (6, 7 or 8), so the self-check job includes this one" },
      "Insulated metal panels: 2-4 in. foam-core panels with tongue-and-groove joints, set in sealant, clipped to the girts, panel joints gasketed": { price: [12, 22], labor: 0.35, basis: "derived", note: "Wallnova 2025: IMP panels $7-$14/sqft, plus setting, sealant and clips" },
      "Extruded trims and flashings: base, head, jamb, sill, inside and outside corners and reveals in the matching finish": { price: [12, 25], labor: 0.5, basis: "est", q: 600 },
      "Window and door surrounds: returns and receivers formed around each opening, end-dammed sill flashing sealed to the barrier": { price: [18, 35], labor: 0.5, basis: "est", q: 400 },
      "Parapet coping: formed or extruded coping with splice plates and cleats, matched to the panel finish": { price: [30, 60], labor: 0.45, basis: "est" },
      "Joint sealing: backer rod and silicone at face-sealed panel joints and at every termination against dissimilar materials": { price: [3, 6.5], labor: 0.7, basis: "est", q: 500 },
      "Crane or lift for panels: boom lift, scissor lift or crane with panel clamps for the installation days": { price: [3000, 9000], labor: 0.1, basis: "est", q: 1, note: "boom lifts for 3-6 weeks; scales with duration" },
      "Field water test on the mock-up or first bay to the specification, with any leak corrected before production": { price: [1500, 3500], labor: 0.8, basis: "est", note: "a third-party agency's fee is passed through at cost" },
      "Cleanup and closeout: protective film removed, panels washed, scrap recycled, and the PVDF finish warranty (20 years) and weathertightness warranty issued": { price: [800, 2500], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "crawlspace-repair": {
    op: 0.35,
    opNote: "residential specialty trade, high sales overhead",
    benchmark: {
      unit: "sqft",
      measures: "crawlspace floor area encapsulated",
      price: [4, 9],
      typicalQty: [1000, 2000],
      jobQty: 1500,
      minJob: 2500,
      sources: ["Palm Build 2026: encapsulation $1,500-$15,000, averaging about $5,500; $3-$7/sqft standard, up to $10/sqft for wet or damaged spaces", "Palm Build 2026: crawl space dehumidifier $1,000-$3,500 installed; liner floor and walls $1,200-$4,000 installed", "HomeGuide 2026: crawl space dehumidifier $1,000-$3,000 installed"],
    },
    steps: {
      "Crawlspace inspection: wood moisture readings at joists and subfloor, relative humidity, standing water and grade, sagging or rotted framing, pest and fungal evidence, vents and access mapped": { price: [150, 350], labor: 1, basis: "est", q: 1, note: "many firms credit it against the job" },
      "Debris removal: old vapor barrier, fallen insulation, wood scrap and trash bagged, carried out and hauled off": { price: [70, 140], labor: 0.7, basis: "est", q: 6 },
      "Fungal and mold treatment: joists and subfloor HEPA-vacuumed, scrubbed and treated with an EPA-registered antimicrobial and a borate wood treatment": { price: [1.25, 3.25], labor: 0.75, basis: "est" },
      "Joist sistering: new joists of the same depth glued and bolted alongside the damaged joists for their full length, bearing on the sill and girder": { price: [14, 28], labor: 0.65, basis: "derived", note: "HomeAdvisor 2025: joist repair $100-$300 per joist" },
      "Girder and sill repair: rotted sections cut out and replaced with pressure-treated lumber, sill plate anchored, temporary shoring during the swap": { price: [45, 110], labor: 0.7, basis: "est" },
      "Adjustable steel jack posts on new 24 x 24 x 12 in. concrete footings under the girder, plumbed and loaded to lift the floor to level": { price: [350, 800], labor: 0.6, basis: "est" },
      "Grading and interior drainage: floor graded to a low corner, perforated drain in washed stone along the perimeter to the sump basin": { price: [20, 45], labor: 0.6, basis: "est" },
      "Sump basin and pump: sealed basin with an airtight lid, 1/3-1/2 HP submersible pump, check valve and a discharge line to daylight": { price: [900, 1800], labor: 0.45, basis: "derived", note: "Palm Build 2026: crawl space sump $600-$1,800; HomeGuide 2026: $600-$2,500 installed" },
      "Vent sealing: foundation vents closed with rigid foam plugs and sealed, outside vent covers installed": { price: [45, 110], labor: 0.7, basis: "est", q: 8 },
      "Foundation wall insulation: 2 in. closed-cell spray foam (R-13) or foil-faced rigid foam board sealed at the sill and rim joist, with the code-required 3 in. termite inspection gap": { price: [2, 3.75], labor: 0.5, basis: "derived", q: 480, note: "Palm Build 2026: wall insulation $500-$3,700 per crawlspace, board $0.60-$3.50/sqft; 2 in. closed-cell foam at the high end" },
      "Floor liner: 12-20 mil reinforced polyethylene liner over the whole floor, seams overlapped 12 in. and taped, wrapped and sealed around every pier and column": { price: [1, 2.25], labor: 0.55, basis: "derived", q: 1500, note: "Palm Build 2026: 12-20 mil liner on floor and walls $1,200-$4,000 installed; material $0.50-$2.00/sqft" },
      "Wall liner and termination: liner run up the foundation walls and piers, mechanically fastened with a termination bar and sealed with the manufacturer's tape": { price: [5, 10], labor: 0.55, basis: "est", q: 160, note: "per lf of wall perimeter" },
      "Crawlspace dehumidifier: 70-100 pint per day crawlspace-rated unit hung or set on a stand with the condensate piped to the sump or outside": { price: [1500, 2800], labor: 0.25, basis: "src", q: 1, note: "Palm Build 2026: $1,000-$3,500 installed; HomeGuide 2026: $1,000-$3,000" },
      "Conditioning air: a supply register from the house duct or an exhaust fan sized at 1 cfm per 50 sqft per IRC R408.3": { price: [300, 800], labor: 0.6, basis: "est" },
      "GFCI outlet and circuit for the dehumidifier and pump, run from the panel by the electrician": { price: [250, 600], labor: 0.65, basis: "est" },
      "Insulated, airtight access door or well cover at the crawlspace entry": { price: [250, 650], labor: 0.4, basis: "est", q: 1 },
      "Cleanup, final moisture and humidity readings recorded, and the liner and workmanship warranty (typically 25 years on the liner) issued": { price: [100, 300], labor: 0.8, basis: "est", q: 1 },
    },
  },
  "basement-waterproofing": {
    op: 0.35,
    opNote: "residential specialty trade, high sales overhead",
    benchmark: {
      unit: "linear ft",
      measures: "perimeter length of interior drain",
      price: [60, 120],
      typicalQty: [80, 180],
      jobQty: 130,
      minJob: 3000,
      sources: ["This Old House 2026: weeping-tile drainage system $60-$120/lf; sump pump installed $1,200-$2,500", "Jaspector (undated): interior perimeter drains $70-$150/lf installed; sump pump $1,200-$3,500", "Basement Waterproofing Scientists 2025: interior drain tile $40-$85/lf"],
    },
    steps: {
      "Water-intrusion assessment: source and path traced (cove joint, wall cracks, tie holes, window wells or hydrostatic floor seepage), wall type and floor thickness noted, sump location and discharge route set": { price: [150, 400], labor: 1, basis: "est", q: 1, note: "often free from firms that sell the system" },
      "Removal and reset of finishes at the perimeter: baseboard, drywall and framing cut back 12-24 in. from the wall and set aside": { price: [15, 35], labor: 0.9, basis: "est" },
      "Interior perimeter cut: slab saw-cut 12 in. from the wall, concrete broken out and removed, trench dug to the footing and spoils carried out": { price: [18, 35], labor: 0.85, basis: "derived", q: 130, note: "about 40% of an installed interior drain system price" },
      "Interior drain tile: 4 in. perforated corrugated or rigid PVC drain laid beside the footing on washed stone, with a wall-drainage flange to catch the cove joint and weep holes drilled in block walls": { price: [14, 28], labor: 0.55, basis: "derived", q: 130 },
      "Wall vapor barrier: dimpled membrane or 20-mil poly hung 4-8 ft up the wall, sealed at the top and tucked into the drain so wall water runs to the tile": { price: [1, 2.25], labor: 0.5, basis: "est", q: 780 },
      "Sump basin and pump: 18 x 24 in. basin with a sealed, radon-ready lid, 1/3-1/2 HP cast-iron submersible pump with a float switch and check valve": { price: [1100, 2200], labor: 0.5, basis: "src", q: 1, note: "This Old House 2026: sump pump installed $1,200-$2,500" },
      "Battery back-up pump on the same basin with a charger and alarm for outages": { price: [600, 1300], labor: 0.35, basis: "est" },
      "Discharge line: 1-1/2 in. PVC through the rim or wall, buried 10-20 ft to daylight, a pop-up emitter or the storm connection, with a freeze guard": { price: [15, 35], labor: 0.6, basis: "est", q: 25 },
      "Concrete restoration: trench re-poured with 3,000-psi concrete troweled flush to the slab": { price: [10, 20], labor: 0.6, basis: "est", q: 130 },
      "Wall-crack injection: poured-wall cracks ported and injected with expanding polyurethane, surface-sealed with epoxy paste": { price: [60, 125], labor: 0.7, basis: "derived", note: "This Old House 2026: $800-$1,500 per crack; about $60-$125 per lf" },
      "Exterior excavation to the footing along the leaking wall, shored, spoils stockpiled, deck or steps removed and reset as needed": { price: [45, 100], labor: 0.6, basis: "derived", note: "This Old House 2026: excavation $50-$200/cy" },
      "Exterior wall waterproofing: wall cleaned and parged, 60-mil membrane or elastomeric coating applied, drainage board hung and a new footing drain laid to the sump or daylight": { price: [6.5, 13], labor: 0.5, basis: "est" },
      "Backfill in lifts with free-draining stone and soil, grade sloped 6 in. in 10 ft away from the house, lawn and plantings restored": { price: [35, 75], labor: 0.5, basis: "est" },
      "Window wells and well drains: galvanized or composite well set at each below-grade window with a drain to the footing tile and a clear cover": { price: [700, 1800], labor: 0.5, basis: "est" },
      "Basement dehumidifier plumbed to the sump to hold humidity under 50% after the water is stopped": { price: [1500, 2800], labor: 0.25, basis: "est" },
      "Cleanup: dust walls removed, concrete rubble hauled off, floor swept and washed, pump run-tested with water in the basin": { price: [150, 400], labor: 0.7, basis: "est", q: 1 },
      "Warranty: the transferable drainage-system warranty (lifetime where offered) and the pump warranty issued in writing with the maintenance schedule": { price: [25, 100], labor: 1, basis: "est", q: 1, note: "paperwork only" },
    },
  },
  "house-wrap": {
    op: 0.25,
    opNote: "residential specialty trade (siding and framing subs)",
    benchmark: {
      unit: "sqft",
      measures: "wall area wrapped, less openings over 20 sqft",
      price: [1.25, 2.75],
      typicalQty: [1800, 3200],
      jobQty: 2500,
      minJob: 800,
      sources: ["Homewyse 2026: install house wrap $0.70-$0.86/sqft (wrap, fasteners, basic flashing)", "Well Built Florida 2026: Tyvek installed about $0.85-$2.50/sqft (material $0.60-$1.50, labor $0.25-$1.00); 2,000 sqft mid-range job $3,190-$4,590"],
    },
    steps: {
      "Sheathing walkthrough: sheathing gaps, popped fasteners and damaged panels flagged and fixed, and the barrier product and flashing sequence confirmed with the window installer": { price: [100, 300], labor: 1, basis: "est", q: 1 },
      "Sheathing seam tape: every panel joint and corner taped with the manufacturer's acrylic tape and rolled": { price: [0.6, 1.2], labor: 0.5, basis: "est" },
      "Mechanically fastened wrap: spun-bonded polyolefin housewrap or a drainable wrap with a 1 mm drainage gap, run horizontally, lower course first, laps 6 in. horizontal and 12 in. vertical, cap nails or cap staples every 12-18 in.": { price: [0.45, 0.85], labor: 0.55, basis: "src", q: 2500, note: "Homewyse 2026: $0.70-$0.86/sqft" },
      "Fluid-applied barrier: spray- or roller-applied membrane at the stated wet-mil thickness over sheathing and joints, with joint treatment first": { price: [2, 4], labor: 0.5, basis: "est" },
      "Sill pans: wrap cut at each window and door opening and folded in, then a self-adhered or formed sill pan with back dam and end dams set over the sill flap before the unit goes in": { price: [30, 70], labor: 0.6, basis: "est", q: 20, note: "per opening" },
      "Seam taping: all horizontal and vertical laps sealed with the wrap manufacturer's tape and rolled for adhesion": { price: [0.35, 0.75], labor: 0.6, basis: "est", q: 500 },
      "Window and door flashing: wrap cut in a modified I, jamb flashing tape 4-6 in. over the fins, head flashing over that, the head flap dropped over the head flashing and taped at the corners (ASTM E2112)": { price: [35, 90], labor: 0.65, basis: "est", q: 20, note: "per opening" },
      "Penetration flashing: pipes, hose bibs, vents, electrical boxes, light blocks and deck ledger bolts flashed with self-adhered patches or preformed boots": { price: [15, 40], labor: 0.6, basis: "est", q: 12 },
      "Bottom-of-wall transition: wrap lapped over the sill plate and sealed to the foundation with a transition strip or fluid flashing": { price: [1.5, 3.5], labor: 0.6, basis: "est", q: 160 },
      "Roof-to-wall and deck transitions: step and kick-out flashing zones lapped into the wrap, ledger flashing integrated": { price: [5, 12], labor: 0.65, basis: "est" },
      "Rain-screen furring or drainage mat: 3/8 in. furring strips or an entangled-mesh mat over the barrier for a ventilated siding cavity": { price: [1, 2.25], labor: 0.55, basis: "est" },
      "Repair of tears and staple-outs and a final walk with the siding contractor so nothing is covered before it is sealed": { price: [100, 300], labor: 1, basis: "est", q: 1 },
      "Blower-door air-leakage test to the stated ACH50 with a report": { price: [250, 500], labor: 0.9, basis: "est" },
      "Third-party or building inspection of the barrier before siding, with the pass documented": { price: [100, 350], labor: 0, fee: true, basis: "est", q: 1, note: "third-party inspector billed at cost; a city inspection under the building permit usually adds little or nothing" },
      "Cleanup: wrap trimmings, tape backing and packaging removed and the barrier warranty registered": { price: [75, 200], labor: 0.8, basis: "est", q: 1 },
    },
  },
};
