// City construction cost index — 306 cities, every state and DC (researched
// 2026-09-18; methodology, per-row sources and notes in
// docs/pricing-sources-cities.md). 1.00 = US national average, total installed
// cost (materials, labor, equipment, contractor markup; no sales tax).
// factor = 0.60 x labor (BLS OEWS May 2025 construction wage for the metro,
// county-adjusted inside big metros) + 0.40 x materials (Craftsman material
// index for the ZIP area); tracks RSMeans Residential 2024 (r 0.90), HUD 2024
// cost limits (0.87) and the DoD area cost factors (0.86). Rules instead of
// the formula: Tri-Cities and Bremerton (defense wages), Lynnwood/Edmonds/Mill
// Creek (halfway King-Snohomish), Manhattan (published midpoint).
export type CityCostRow = { city: string; state: string; factor: number };

export const CITY_COST_INDEX: CityCostRow[] = [
  { city: "Seattle", state: "WA", factor: 1.25 },
  { city: "Bellevue", state: "WA", factor: 1.25 },
  { city: "Kirkland", state: "WA", factor: 1.25 },
  { city: "Redmond", state: "WA", factor: 1.25 },
  { city: "Bothell", state: "WA", factor: 1.25 },
  { city: "Renton", state: "WA", factor: 1.25 },
  { city: "Kent", state: "WA", factor: 1.25 },
  { city: "Auburn", state: "WA", factor: 1.25 },
  { city: "Federal Way", state: "WA", factor: 1.25 },
  { city: "Issaquah", state: "WA", factor: 1.25 },
  { city: "Sammamish", state: "WA", factor: 1.25 },
  { city: "Mercer Island", state: "WA", factor: 1.25 },
  { city: "Shoreline", state: "WA", factor: 1.25 },
  { city: "Lynnwood", state: "WA", factor: 1.21 },
  { city: "Edmonds", state: "WA", factor: 1.21 },
  { city: "Mill Creek", state: "WA", factor: 1.21 },
  { city: "Everett", state: "WA", factor: 1.16 },
  { city: "Marysville", state: "WA", factor: 1.16 },
  { city: "Tacoma", state: "WA", factor: 1.16 },
  { city: "Puyallup", state: "WA", factor: 1.16 },
  { city: "Lakewood", state: "WA", factor: 1.16 },
  { city: "Olympia", state: "WA", factor: 1.13 },
  { city: "Bremerton", state: "WA", factor: 1.09 },
  { city: "Spokane", state: "WA", factor: 1.06 },
  { city: "Vancouver", state: "WA", factor: 1.11 },
  { city: "Bellingham", state: "WA", factor: 1.16 },
  { city: "Yakima", state: "WA", factor: 1.04 },
  { city: "Tri-Cities", state: "WA", factor: 1.13 },
  { city: "Kennewick", state: "WA", factor: 1.13 },
  { city: "Richland", state: "WA", factor: 1.13 },
  { city: "Pasco", state: "WA", factor: 1.12 },
  { city: "Wenatchee", state: "WA", factor: 1.12 },
  { city: "Anchorage", state: "AK", factor: 1.19 },
  { city: "Fairbanks", state: "AK", factor: 1.24 },
  { city: "Juneau", state: "AK", factor: 1.22 },
  { city: "Birmingham", state: "AL", factor: 0.90 },
  { city: "Huntsville", state: "AL", factor: 0.89 },
  { city: "Mobile", state: "AL", factor: 0.88 },
  { city: "Montgomery", state: "AL", factor: 0.86 },
  { city: "Little Rock", state: "AR", factor: 0.85 },
  { city: "Fayetteville", state: "AR", factor: 0.88 },
  { city: "Bentonville", state: "AR", factor: 0.87 },
  { city: "Fort Smith", state: "AR", factor: 0.83 },
  { city: "Phoenix", state: "AZ", factor: 0.97 },
  { city: "Scottsdale", state: "AZ", factor: 0.97 },
  { city: "Mesa", state: "AZ", factor: 0.97 },
  { city: "Tucson", state: "AZ", factor: 0.91 },
  { city: "Flagstaff", state: "AZ", factor: 0.94 },
  { city: "Los Angeles", state: "CA", factor: 1.10 },
  { city: "Long Beach", state: "CA", factor: 1.10 },
  { city: "Santa Monica", state: "CA", factor: 1.10 },
  { city: "Anaheim", state: "CA", factor: 1.14 },
  { city: "Irvine", state: "CA", factor: 1.14 },
  { city: "Riverside", state: "CA", factor: 1.05 },
  { city: "San Bernardino", state: "CA", factor: 1.09 },
  { city: "San Diego", state: "CA", factor: 1.11 },
  { city: "San Francisco", state: "CA", factor: 1.30 },
  { city: "Oakland", state: "CA", factor: 1.26 },
  { city: "Walnut Creek", state: "CA", factor: 1.20 },
  { city: "San Mateo", state: "CA", factor: 1.23 },
  { city: "Palo Alto", state: "CA", factor: 1.29 },
  { city: "San Jose", state: "CA", factor: 1.28 },
  { city: "Santa Rosa", state: "CA", factor: 1.16 },
  { city: "Sacramento", state: "CA", factor: 1.11 },
  { city: "Fresno", state: "CA", factor: 1.06 },
  { city: "Bakersfield", state: "CA", factor: 1.06 },
  { city: "Stockton", state: "CA", factor: 1.07 },
  { city: "Oxnard", state: "CA", factor: 1.08 },
  { city: "Santa Barbara", state: "CA", factor: 1.06 },
  { city: "Salinas", state: "CA", factor: 1.09 },
  { city: "Denver", state: "CO", factor: 1.06 },
  { city: "Aurora", state: "CO", factor: 1.04 },
  { city: "Lakewood", state: "CO", factor: 1.04 },
  { city: "Boulder", state: "CO", factor: 1.03 },
  { city: "Colorado Springs", state: "CO", factor: 0.98 },
  { city: "Fort Collins", state: "CO", factor: 0.99 },
  { city: "Pueblo", state: "CO", factor: 0.96 },
  { city: "Hartford", state: "CT", factor: 1.08 },
  { city: "Bridgeport", state: "CT", factor: 1.09 },
  { city: "Stamford", state: "CT", factor: 1.09 },
  { city: "Greenwich", state: "CT", factor: 1.09 },
  { city: "New Haven", state: "CT", factor: 1.08 },
  { city: "Washington", state: "DC", factor: 1.05 },
  { city: "Wilmington", state: "DE", factor: 1.03 },
  { city: "Dover", state: "DE", factor: 0.94 },
  { city: "Miami", state: "FL", factor: 0.92 },
  { city: "Fort Lauderdale", state: "FL", factor: 0.96 },
  { city: "West Palm Beach", state: "FL", factor: 0.94 },
  { city: "Boca Raton", state: "FL", factor: 0.94 },
  { city: "Tampa", state: "FL", factor: 0.92 },
  { city: "St. Petersburg", state: "FL", factor: 0.91 },
  { city: "Orlando", state: "FL", factor: 0.91 },
  { city: "Jacksonville", state: "FL", factor: 0.92 },
  { city: "Tallahassee", state: "FL", factor: 0.88 },
  { city: "Sarasota", state: "FL", factor: 0.91 },
  { city: "Fort Myers", state: "FL", factor: 0.89 },
  { city: "Naples", state: "FL", factor: 0.94 },
  { city: "Pensacola", state: "FL", factor: 0.89 },
  { city: "Atlanta", state: "GA", factor: 0.97 },
  { city: "Marietta", state: "GA", factor: 0.97 },
  { city: "Lawrenceville", state: "GA", factor: 0.94 },
  { city: "Savannah", state: "GA", factor: 0.91 },
  { city: "Augusta", state: "GA", factor: 0.90 },
  { city: "Columbus", state: "GA", factor: 0.85 },
  { city: "Honolulu", state: "HI", factor: 1.25 },
  { city: "Kahului", state: "HI", factor: 1.27 },
  { city: "Hilo", state: "HI", factor: 1.24 },
  { city: "Des Moines", state: "IA", factor: 1.01 },
  { city: "Cedar Rapids", state: "IA", factor: 0.98 },
  { city: "Davenport", state: "IA", factor: 1.04 },
  { city: "Boise", state: "ID", factor: 0.97 },
  { city: "Meridian", state: "ID", factor: 0.97 },
  { city: "Idaho Falls", state: "ID", factor: 0.97 },
  { city: "Pocatello", state: "ID", factor: 0.92 },
  { city: "Coeur d'Alene", state: "ID", factor: 0.96 },
  { city: "Chicago", state: "IL", factor: 1.20 },
  { city: "Naperville", state: "IL", factor: 1.22 },
  { city: "Aurora", state: "IL", factor: 1.17 },
  { city: "Joliet", state: "IL", factor: 1.18 },
  { city: "Springfield", state: "IL", factor: 1.09 },
  { city: "Rockford", state: "IL", factor: 1.12 },
  { city: "Peoria", state: "IL", factor: 1.11 },
  { city: "Indianapolis", state: "IN", factor: 1.02 },
  { city: "Carmel", state: "IN", factor: 1.01 },
  { city: "Fort Wayne", state: "IN", factor: 0.99 },
  { city: "Evansville", state: "IN", factor: 1.00 },
  { city: "South Bend", state: "IN", factor: 0.99 },
  { city: "Wichita", state: "KS", factor: 0.92 },
  { city: "Overland Park", state: "KS", factor: 1.05 },
  { city: "Kansas City", state: "KS", factor: 1.06 },
  { city: "Topeka", state: "KS", factor: 0.94 },
  { city: "Louisville", state: "KY", factor: 0.98 },
  { city: "Lexington", state: "KY", factor: 0.94 },
  { city: "Bowling Green", state: "KY", factor: 0.90 },
  { city: "Frankfort", state: "KY", factor: 0.90 },
  { city: "New Orleans", state: "LA", factor: 0.96 },
  { city: "Metairie", state: "LA", factor: 0.88 },
  { city: "Baton Rouge", state: "LA", factor: 0.95 },
  { city: "Shreveport", state: "LA", factor: 0.90 },
  { city: "Lafayette", state: "LA", factor: 0.90 },
  { city: "Boston", state: "MA", factor: 1.22 },
  { city: "Cambridge", state: "MA", factor: 1.18 },
  { city: "Newton", state: "MA", factor: 1.18 },
  { city: "Brookline", state: "MA", factor: 1.21 },
  { city: "Lowell", state: "MA", factor: 1.17 },
  { city: "Worcester", state: "MA", factor: 1.11 },
  { city: "Springfield", state: "MA", factor: 1.09 },
  { city: "Baltimore", state: "MD", factor: 0.98 },
  { city: "Annapolis", state: "MD", factor: 1.01 },
  { city: "Bethesda", state: "MD", factor: 1.01 },
  { city: "Silver Spring", state: "MD", factor: 1.01 },
  { city: "Frederick", state: "MD", factor: 1.00 },
  { city: "Portland", state: "ME", factor: 1.03 },
  { city: "Bangor", state: "ME", factor: 0.92 },
  { city: "Lewiston", state: "ME", factor: 0.96 },
  { city: "Augusta", state: "ME", factor: 0.96 },
  { city: "Detroit", state: "MI", factor: 1.04 },
  { city: "Ann Arbor", state: "MI", factor: 1.04 },
  { city: "Grand Rapids", state: "MI", factor: 0.98 },
  { city: "Lansing", state: "MI", factor: 1.00 },
  { city: "Minneapolis", state: "MN", factor: 1.15 },
  { city: "St. Paul", state: "MN", factor: 1.17 },
  { city: "Eagan", state: "MN", factor: 1.12 },
  { city: "Rochester", state: "MN", factor: 1.09 },
  { city: "Duluth", state: "MN", factor: 1.05 },
  { city: "Kansas City", state: "MO", factor: 1.05 },
  { city: "St. Louis", state: "MO", factor: 1.12 },
  { city: "Springfield", state: "MO", factor: 0.97 },
  { city: "Jefferson City", state: "MO", factor: 1.01 },
  { city: "Jackson", state: "MS", factor: 0.85 },
  { city: "Gulfport", state: "MS", factor: 0.88 },
  { city: "Hattiesburg", state: "MS", factor: 0.85 },
  { city: "Billings", state: "MT", factor: 1.00 },
  { city: "Missoula", state: "MT", factor: 0.98 },
  { city: "Bozeman", state: "MT", factor: 1.03 },
  { city: "Great Falls", state: "MT", factor: 0.97 },
  { city: "Helena", state: "MT", factor: 0.98 },
  { city: "Charlotte", state: "NC", factor: 0.94 },
  { city: "Raleigh", state: "NC", factor: 0.95 },
  { city: "Durham", state: "NC", factor: 0.94 },
  { city: "Greensboro", state: "NC", factor: 0.91 },
  { city: "Winston-Salem", state: "NC", factor: 0.89 },
  { city: "Asheville", state: "NC", factor: 0.90 },
  { city: "Wilmington", state: "NC", factor: 0.90 },
  { city: "Fargo", state: "ND", factor: 1.00 },
  { city: "Bismarck", state: "ND", factor: 0.97 },
  { city: "Grand Forks", state: "ND", factor: 0.98 },
  { city: "Minot", state: "ND", factor: 0.98 },
  { city: "Omaha", state: "NE", factor: 0.96 },
  { city: "Lincoln", state: "NE", factor: 0.93 },
  { city: "Grand Island", state: "NE", factor: 0.89 },
  { city: "Manchester", state: "NH", factor: 0.99 },
  { city: "Nashua", state: "NH", factor: 0.99 },
  { city: "Concord", state: "NH", factor: 0.98 },
  { city: "Portsmouth", state: "NH", factor: 1.11 },
  { city: "Newark", state: "NJ", factor: 1.16 },
  { city: "Jersey City", state: "NJ", factor: 1.18 },
  { city: "Hackensack", state: "NJ", factor: 1.15 },
  { city: "Morristown", state: "NJ", factor: 1.17 },
  { city: "Edison", state: "NJ", factor: 1.19 },
  { city: "Toms River", state: "NJ", factor: 1.11 },
  { city: "Trenton", state: "NJ", factor: 1.13 },
  { city: "Cherry Hill", state: "NJ", factor: 1.05 },
  { city: "Albuquerque", state: "NM", factor: 0.91 },
  { city: "Santa Fe", state: "NM", factor: 0.90 },
  { city: "Las Cruces", state: "NM", factor: 0.86 },
  { city: "Las Vegas", state: "NV", factor: 1.03 },
  { city: "Henderson", state: "NV", factor: 1.03 },
  { city: "Reno", state: "NV", factor: 1.02 },
  { city: "Carson City", state: "NV", factor: 1.06 },
  { city: "New York", state: "NY", factor: 1.27 },
  { city: "Manhattan", state: "NY", factor: 1.27 },
  { city: "Brooklyn", state: "NY", factor: 1.11 },
  { city: "Queens", state: "NY", factor: 1.20 },
  { city: "Bronx", state: "NY", factor: 1.17 },
  { city: "Staten Island", state: "NY", factor: 1.16 },
  { city: "Hempstead", state: "NY", factor: 1.18 },
  { city: "Huntington", state: "NY", factor: 1.15 },
  { city: "White Plains", state: "NY", factor: 1.16 },
  { city: "Buffalo", state: "NY", factor: 1.02 },
  { city: "Rochester", state: "NY", factor: 1.00 },
  { city: "Syracuse", state: "NY", factor: 1.03 },
  { city: "Albany", state: "NY", factor: 1.07 },
  { city: "Columbus", state: "OH", factor: 1.05 },
  { city: "Cleveland", state: "OH", factor: 1.03 },
  { city: "Cincinnati", state: "OH", factor: 1.01 },
  { city: "Toledo", state: "OH", factor: 1.02 },
  { city: "Akron", state: "OH", factor: 1.02 },
  { city: "Dayton", state: "OH", factor: 0.99 },
  { city: "Oklahoma City", state: "OK", factor: 0.93 },
  { city: "Tulsa", state: "OK", factor: 0.92 },
  { city: "Portland", state: "OR", factor: 1.21 },
  { city: "Beaverton", state: "OR", factor: 1.17 },
  { city: "Lake Oswego", state: "OR", factor: 1.14 },
  { city: "Salem", state: "OR", factor: 1.05 },
  { city: "Eugene", state: "OR", factor: 1.03 },
  { city: "Bend", state: "OR", factor: 1.03 },
  { city: "Medford", state: "OR", factor: 1.03 },
  { city: "Philadelphia", state: "PA", factor: 1.08 },
  { city: "King of Prussia", state: "PA", factor: 1.08 },
  { city: "West Chester", state: "PA", factor: 1.06 },
  { city: "Pittsburgh", state: "PA", factor: 1.01 },
  { city: "Harrisburg", state: "PA", factor: 1.03 },
  { city: "Allentown", state: "PA", factor: 1.03 },
  { city: "Lancaster", state: "PA", factor: 0.96 },
  { city: "Scranton", state: "PA", factor: 0.97 },
  { city: "Erie", state: "PA", factor: 0.94 },
  { city: "Providence", state: "RI", factor: 1.06 },
  { city: "Newport", state: "RI", factor: 1.02 },
  { city: "Columbia", state: "SC", factor: 0.92 },
  { city: "Charleston", state: "SC", factor: 0.92 },
  { city: "Greenville", state: "SC", factor: 0.93 },
  { city: "Myrtle Beach", state: "SC", factor: 0.88 },
  { city: "Sioux Falls", state: "SD", factor: 0.93 },
  { city: "Rapid City", state: "SD", factor: 0.90 },
  { city: "Pierre", state: "SD", factor: 0.90 },
  { city: "Nashville", state: "TN", factor: 0.96 },
  { city: "Franklin", state: "TN", factor: 0.96 },
  { city: "Murfreesboro", state: "TN", factor: 0.93 },
  { city: "Memphis", state: "TN", factor: 0.93 },
  { city: "Knoxville", state: "TN", factor: 0.91 },
  { city: "Chattanooga", state: "TN", factor: 0.93 },
  { city: "Houston", state: "TX", factor: 0.92 },
  { city: "Sugar Land", state: "TX", factor: 0.92 },
  { city: "The Woodlands", state: "TX", factor: 0.88 },
  { city: "Dallas", state: "TX", factor: 0.92 },
  { city: "Plano", state: "TX", factor: 0.91 },
  { city: "Frisco", state: "TX", factor: 0.91 },
  { city: "Fort Worth", state: "TX", factor: 0.91 },
  { city: "Arlington", state: "TX", factor: 0.91 },
  { city: "Austin", state: "TX", factor: 0.94 },
  { city: "San Antonio", state: "TX", factor: 0.89 },
  { city: "El Paso", state: "TX", factor: 0.82 },
  { city: "Corpus Christi", state: "TX", factor: 0.88 },
  { city: "Lubbock", state: "TX", factor: 0.84 },
  { city: "McAllen", state: "TX", factor: 0.80 },
  { city: "Midland", state: "TX", factor: 0.92 },
  { city: "Salt Lake City", state: "UT", factor: 0.98 },
  { city: "Provo", state: "UT", factor: 0.94 },
  { city: "Ogden", state: "UT", factor: 0.93 },
  { city: "St. George", state: "UT", factor: 0.91 },
  { city: "Arlington", state: "VA", factor: 1.04 },
  { city: "Alexandria", state: "VA", factor: 1.03 },
  { city: "Fairfax", state: "VA", factor: 1.02 },
  { city: "Reston", state: "VA", factor: 1.02 },
  { city: "Ashburn", state: "VA", factor: 1.08 },
  { city: "Woodbridge", state: "VA", factor: 1.01 },
  { city: "Richmond", state: "VA", factor: 0.93 },
  { city: "Virginia Beach", state: "VA", factor: 0.92 },
  { city: "Norfolk", state: "VA", factor: 0.94 },
  { city: "Roanoke", state: "VA", factor: 0.88 },
  { city: "Charlottesville", state: "VA", factor: 0.94 },
  { city: "Burlington", state: "VT", factor: 1.01 },
  { city: "Montpelier", state: "VT", factor: 0.97 },
  { city: "Rutland", state: "VT", factor: 0.93 },
  { city: "Milwaukee", state: "WI", factor: 1.08 },
  { city: "Waukesha", state: "WI", factor: 1.08 },
  { city: "Madison", state: "WI", factor: 1.09 },
  { city: "Green Bay", state: "WI", factor: 1.04 },
  { city: "Charleston", state: "WV", factor: 0.96 },
  { city: "Huntington", state: "WV", factor: 0.93 },
  { city: "Morgantown", state: "WV", factor: 0.90 },
  { city: "Wheeling", state: "WV", factor: 0.98 },
  { city: "Cheyenne", state: "WY", factor: 0.98 },
  { city: "Casper", state: "WY", factor: 0.95 },
  { city: "Laramie", state: "WY", factor: 0.95 },
];
